### ISSUE TITLE
prom statefulset should use 1 configmap reloader container instead of 2

### ISSUE THREAD

**Issue by jhorwit2** [coreos/prometheus-operator#100]
[Currently](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L231) there is a reload container for rules and another one for the config. The underlying reloader library [supports multiple](https://github.com/jimmidyson/configmap-reload/blob/master/configmap-reload.go#L83) volume dirs. Is there a reason there isn't just one reloader with 2 volume dirs?

**Comment by jhorwit2** [comment]
Just so I don't forget; if it's decided there should be two containers the [rules reloader](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L251) should have resources limits specified

**Comment by brancz** [comment]
I haven't followed much upstream it seems that that has been added recently. Thanks for reporting, we should definitely now switch to one reloader. We'll make sure that that one has resource request and limit specified.

**Comment by brancz** [comment]
Closed by #108.
