### ISSUE TITLE
Alerts firing: ControllerManager, Scheduler and TargetDown

### ISSUE THREAD

**Issue by domcar** [coreos/prometheus-operator#1001]
**What did you do?**
I installed prometheus-operator and kube-prometheus using helm:
```
helm install coreos/prometheus-operator --name prometheus-operator
helm install coreos/kube-prometheus --name kube-prometheus --set rbacEnable=true
```
**What did you expect to see?**
Everything green in Alert Manager

**What did you see instead? Under which circumstances?**
Some Alerts are firing:
- K8s Scheduler
- K8S Controller
- NodeDiskRuningFull
- TargetDown

**Environment**
GKE

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	I used terraform to create the cluster on GKE

* Prometheus Operator Logs:
No Errors nor warnings

I guess somehow these targets get not scraped. Can you help me out on how to solve this issue please? Thanks

**Comment by domcar** [comment]
If it helps, it looks like some services have no endpoints:
```
kubectl get endpoints 
kube-system   kube-controller-manager                            <none>                                                           19h
kube-system   kube-prometheus-exporter-kube-scheduler            <none>                                                           24m
```

**Comment by sandromello** [comment]
I had a simular issue, but I've used `kubeadm` to install the cluster. I fixed those alerts editing selector of those services.

If you have kubernetes core components as pods in the `kube-system` namespace, make sure the label selector of those services match with the labels of the pods.

```
kubectl get svc kube-prom-exporter-kube-scheduler kube-prom-exporter-kube-controller-manager -n kube-system -o wide
NAME                                         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE       SELECTOR
kube-prom-exporter-kube-scheduler            ClusterIP   None         <none>        10251/TCP   3h        component=kube-scheduler
kube-prom-exporter-kube-controller-manager   ClusterIP   None         <none>        10252/TCP   3h        component=kube-controller-manager
```

```
kubectl get po -l component -n kube-system --show-labels
NAME                                                 READY     STATUS    RESTARTS   AGE       LABELS
(...)
kube-apiserver-ip-10-0-41-71.ec2.internal            1/1       Running   0          3h        component=kube-apiserver,tier=control-plane
kube-controller-manager-ip-10-0-41-71.ec2.internal   1/1       Running   0          3h        component=kube-controller-manager,tier=control-plane
kube-scheduler-ip-10-0-41-71.ec2.internal            1/1       Running   0          3h        component=kube-scheduler,tier=control-plane
```

> If any of those components were started bound to `127.0.0.1` you need to change that, please take a look at [kubeadm on prometheus](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md) for more information.

**Comment by hamid2013** [comment]
I am also facing same issue, but in my case i have used Azure acs-engine to launch the cluster.

Keep getting the Scheduler and Controller alert.

**Comment by domcar** [comment]
@sandromello The problem is that I don't have the Pods `kube-scheduler` or `controller-manager`. I think this is the reason why it doesn't work

**Comment by ScottBrenner** [comment]
This is a known issue with GKE #355 #845. I ended up just deleting the two alerts.

**Comment by hameno** [comment]
This also seems to be the case for rancher/rke deployments (at least it is happening on my dev cluster)

**Comment by gianrubio** [comment]
@domcar one way to avoid this issue is to have a flag to control if some dependencies from kube-prometheus will be deployed. Looking on [alertmanager example](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/requirements.yaml#L6) on how it's possible to skip the installation of a dependency. 

PR are always welcome :)

**Comment by vinodhbasavani** [comment]
I don't have any endpoints for kube controller manager and scheduler then how to monitor them using prometheus and prometheus operator

**Comment by bonovoxly** [comment]
@ScottBrenner what's the best way to delete an alert using helm? Is it possible to cherry-pick out the alerts, or would I need to recreate them all (minus the non-working alerts for GKE)?

**Comment by ScottBrenner** [comment]
@bonovoxly Was using `kube-prometheus`, never touched Helm.

**Comment by phyllisstein** [comment]
I ran into this issue with a cluster deployed through kops in AWS. The solution that worked for me was sitting in an old version of the repo: I had to deploy the services listed [here](https://github.com/coreos/prometheus-operator/tree/v0.17.0/contrib/kube-prometheus/manifests/k8s/self-hosted) to `kube-system`. With that done, the alerts went green.

**Comment by padgyx** [comment]
Same issue with aws eks

**Comment by vrathore18** [comment]
I am facing the same issue.  I don't have the Pods kube-scheduler or controller-manager. @domcar how did you fixed the issue??

P.S I used helm for installation. CLoud using: AWS

**Comment by chris530** [comment]
I noticed the labels the service was looking for was not returning any pods. After adding the label k8s-app=kube-controller-manager  to the control manager,  and k8s-app=kube-scheduler to the scheduler the alerts cleared up as the service could find pods now.

**Comment by rpf3** [comment]
@chris530 I had to do something very similar to the service selectors; basically null out the `component` label and add `k8s-app` label to the selector for those two services.

**Comment by flogfy** [comment]
@chris530 how were you able to add these labels to the controller manager and the kube scheduler ?  I don't even have the pods and services associated with neither kube-scheduler nor kube-controller-manager. My kubernetes is installed with RKE.

**Comment by woody3549** [comment]
Hello,

I am currently using prometheus-stack version 20.0.1
Alerts KubeSchedulerDown and KubeControllerManagerDown are currently being raised for no apparent reason.
Is that also a label issues, please ?
How did you solve it ?

Thanks for your help.
Regards,
