### ISSUE TITLE
Prometheus only loads alert rules in the "monitoring" namespace

### ISSUE THREAD

**Issue by alexanderdavidsen** [coreos/prometheus-operator#1004]
I created a new alert manager rule, using configmaps, in a different namespace. I would expect these rules to be added to Prometheus, but they are not. When creating the same rule in the "monitoring" namespace, the rules are loaded by prometheus as expected.

Is there a setting the specifies which namespaces Prometheus looks for new rules?

Edit: prometheus-operator(0.0.11) and kube-prometheus(0.0.22) is installed using helm.

**Comment by brancz** [comment]
With the latest version of the Prometheus Operator we introduced the `PrometheusRule` CRD, and it can be selected across namespace using the `ruleNamespaceSelector`.

Closing here, but feel free to re-open this issue or open a new one if you encounter any problems with it! :slightly_smiling_face:
