### ISSUE TITLE
Alertmanager container should just be called "alertmanager"

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#102]
Currently the alertmanager container name has the same name as the `Alertmanager` object. That is more confusing then useful and should be changed to just "alertmanager", the equivalent is already the case for the `Prometheus` object and corresponding container.

@alexsomesan @fabxc

**Comment by fabxc** [comment]
Mh, not sure I understand. Shouldn't it be `alertmanager-<TPR name>` like we discussed for Prometheus?

**Comment by brancz** [comment]
This is actually about something different. So a Prometheus Pod consists of containers with the following `name`s:

- `prometheus`
- `config-reloader`
- `rules-reloader`

While an Alertmanager Pod's containers are called:

- `<insert alertmanager object name>`
- `config-reloader`

And `<insert alertmanager object name>` should just be `alertmanager`.

This is just a 1 line change [here](https://github.com/coreos/prometheus-operator/blob/9001d9e780373bb624cc21c2a326694245060534/pkg/alertmanager/statefulset.go#L158).

**Comment by fabxc** [comment]
Ah, I see 👍

**Comment by brancz** [comment]
Closed by #108.
