### ISSUE TITLE
reinstalling using helm

### ISSUE THREAD

**Issue by SergeBlais** [coreos/prometheus-operator#1022]
<snip generic comments>

**Comment by SergeBlais** [comment]
Hi all,
I'm learning about this, and I tried to install prometheus a few times, but it never completely worked. So now I am trying to use helm (for the second time), and the install 

helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
won't work, it gives me the error

Error: jobs.batch "prometheus-operator-create-sm-job" already exists

How can I deal with this? 

Thanks!

**Comment by gianrubio** [comment]
hi @SergeBlais this is a know issue where the helm chart could create some "garbage", could you paste  the output of this job?  ```kubectl logs prometheus-operator-create-sm-job -n monitoring```

In any case I recommend you to delete all helm chart with --purge option, delete the monitoring namespace and recreated all again.

**Comment by SergeBlais** [comment]
Thanks, deleting the namespace did the trick. When I tried doing the log command I got this:

`bash-4.2$ kubectl logs prometheus-operator-create-sm-job -n monitoring`
`Error from server (NotFound): pods "prometheus-operator-create-sm-job" not found`

But I was able to reinstall. Continuing on to learning... ;)
