### ISSUE TITLE
Verify ConfigMap checksums before reloading

### ISSUE THREAD

**Issue by adamdecaf** [coreos/prometheus-operator#1026]
**What did you do?**

I'm managing the `Secret`'s manually myself to apply `relabel_configs`. In doing so I ran into the `configmaps.json` part of the `Secret`. 

Initially this worried me because I'd have to work through the [makeRuleConfigMap logic for consistently hashing ConfigMaps](https://github.com/coreos/prometheus-operator/blob/v0.17.0/pkg/prometheus/statefulset.go#L215), but then it seems that the [prometheus-config-reloader doesn't even verify the checksums](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/prometheus-config-reloader/main.go#L64).

I've verified a custom `Secret` with invalid checksums is reloaded without concern. 

https://github.com/coreos/prometheus-operator/issues/291 talks a bit about requiring this field's existence, but not a verification check. 

**What did you expect to see?**

Checksums should be verified, yes? Are they an artifact of an older design? Or just used for notifications (I'm not too familiar with k8s offers object watches.)

**Comment by brancz** [comment]
The checksum is only to signify whether the content of a ConfigMap has changed. This is done in order to avoid reloading Prometheus when it's not strictly necessary, or vise versa to force reload Prometheus when a ConfigMap hash has changed.

**Comment by adamdecaf** [comment]
Alright, do you think they should be verified? RBAC handles the permissions required to update ConfigMaps, so nothing like that is needed here.

**Comment by brancz** [comment]
The reloads are synchronized by the config reloaded so there can’t be a race condition there.

I don’t think there’s a reason to verify them.

**Comment by adamdecaf** [comment]
Agreed. Thanks!
