### ISSUE TITLE
cluster name in notification from alertmanager to HipChat - AWS __meta_ec2_tag_Name label and kube-prometheus

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1027]
**What did you do?**

Hello,

I'm running [kube-prometheus/self-hosted-deploy](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/self-hosted-deploy). In my K8s cluster on AWS, each node's `hostname` has the private IP (not the name of the cluster/environment - e.g. "sandbox", "dev", etc.; thus prometheus queries such as `kube_pod_info` only returns IP addresses, not names of clusters). But each ec2 instance's `Name` tag contains the **environment** (e.g. see "k8s-master-**sandbox**" below). So I'd like to get `__meta_ec2_tag_Name` to **show up** when an alert fires (so that when I receive a **notification** in HipChat from alertmanager I'll know which cluster it came from).

This [Automatically monitoring EC2 Instances](https://www.robustperception.io/automatically-monitoring-ec2-instances/) blog post appears to be close to what I'm looking for (it changes the `instance` label to be `__meta_ec2_instance_id`), except I haven't found an **easy way to customize the prometheus.yaml used by kube-prometheus**. I did find the following prometheus-operator issues:
 * The comments on [671](https://github.com/coreos/prometheus-operator/issues/671) ("Prometheus Operator with custom prometheus.yml") discuss custom prometheus config in detail, and point to [custom-configuration.md](https://github.com/coreos/prometheus-operator/blob/master/Documentation/custom-configuration.md).
 * [324](https://github.com/coreos/prometheus-operator/issues/324) "Q: How to provide a custom prometheus.yaml?"

By the way, I found it easy to provide my own alertmanager.yaml to alertmanager via the `kubectl` commands on: [Configuring Prometheus Alertmanager](https://coreos.com/tectonic/docs/latest/tectonic-prometheus-operator/user-guides/configuring-prometheus-alertmanager.html)

So far I haven't had to **fork & modify** my own copy of the prometheus-operator/kube-prometheus repo - but maybe the easiest/best overall thing that I'll have to do is fork it and then follow the instructions in custom-configuration.md?

(In the Prometheus Users public Google group I also created the following topic: [cluster name in HipChat notification message text from alertmanager](https://groups.google.com/forum/#!searchin/prometheus-users/hipchat%7Csort:date/prometheus-users/-LKx_2Prgs0/xWJQLfVdBAAJ))

I'm still kinda a prometheus newbie - any assistance would be greatly appreciated. thanks!

**Environment**

```
core@ip-192-168-xxx-xx ~/josh/prometheus-operator/contrib/kube-prometheus $ hostname
ip-192-168-xxx-xx

josh@MyMac$ aws ec2 describe-instances --filters 'Name=tag:Name,Values=k8s-master-sandbox' --query 'Reservations[*].Instances[*].[PrivateIpAddress]' --output text
192.168.xxx.xx
```

* Kubernetes version information:

```
core@ip-192-168-xxx-xx ~/josh/prometheus-operator/contrib/kube-prometheus $ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	I'm using custom terraform scripts to create a K8s cluster on AWS.

**Comment by brancz** [comment]
Related to #744

**Comment by jolson490** [comment]
Thank you @brancz - in my Googling I hadn't yet come across that issue 744.

I believe this issue 1027 can be closed (per the reply I just posted on the aforementioned topic in the Google group).
