### ISSUE TITLE
kube-prometheus: Failed to list *v1.Endpoints/Service/Pod: Unauthorized

### ISSUE THREAD

**Issue by ayashjorden** [coreos/prometheus-operator#1042]
**What did you do?**
1. Cloned this repo
2. Modified Prometheus, AlertManager and Grafana Services to be LoadBalancer
3. Executed ./hack/cluster-monitoring/deploy

**What did you expect to see?**
Some data in Grafana

**What did you see instead? Under which circumstances?**
No data in Grafana, and Prometheus pods failing on `Failed to list *v1.Endpoints: Unauthorized` (also for Service and Pod.
Checked the Prometheus-Operator RBAC guide, and the ClusterRole, Role and respective bindings looks the same.

**Environment**
Kubernetes cluster 1.9 **from scratch**.

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	From scratch, created my own automated ETCd+K8s deployment ontop of AWS.
        I used TLS certificates issued from Vault for Master/Worker communication, can that be the case?
        EDIT: I think that TLS certificates is **not** the issue as `serviceacconts` are getting a token to use.
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
1) make sure your cluster meets the requirements for the stack: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#prerequisites

2) could you try to make the services non load-balancer (just ClusterIP for now) and just access them via kubectl port-forward? I just want to make sure the load balancer services are not creating the problem.

3) The unauthorized part is definitely a problem, can you share more of the logs?

**Comment by ayashjorden** [comment]
1. It seems that my `kubelets` (authorization-mode=Webhook are missing the `--authentication-token-webhook` flag.
1.1 They're configured with TLS key-pair in kubeconfig file. does that mean that I need to provide Prometheus pods with TLS secret to query the ApiServer and Kubelets?

I'm working on 2 and 3

**Comment by brancz** [comment]
Token authentication and TLS cert authentication are not mutually exclusive, you can and should use both, apiserver -> kubelet via TLS and Prometheus -> kubelet via ServiceAccount token.

The unauthorized part in the logs does look like some ServiceAccount/RBAC problem.

**Comment by ayashjorden** [comment]
Hi @brancz,
I've cycled all k8s Worker nodes and now the `--authentication-token-webhook` is enabled on all of them.
On my ApiServer, the `authorization-mode` is set only to `Node,RBAC`, should I add the `Webhook`?

Please see [prometheus-pod-logs.log](prometheus-pod-logs.log) file.

Any other logs I can add?
Thank you
[prometheus-pod-logs.log](https://github.com/coreos/prometheus-operator/files/1784965/prometheus-pod-logs.log)

**Comment by brancz** [comment]
Are you sure your `ServiceAccount` setup works at all? On the clusters I work on (and that I can confirm that it works I only have `--authorization-mode=RBAC`. Could you run a conformance test on your cluster to make sure it's working properly?

**Comment by ephur** [comment]
I'm actually having a similar, but maybe different in scope, I used kube-prometheus as a base, but want to extend it to monitor a few other items. The logs are below, as well as the outputs showing that the roles in the proper namespaces are added for the service account.

Prometheus logs:
```
level=error ts=2018-03-06T18:12:27.089527378Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list pods in the namespace \"mongo\""
level=error ts=2018-03-06T18:12:27.08955983Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list services in the namespace \"mongo\""
```

```
kubectl -n monitoring get serviceaccount prometheus-k8s
NAME             SECRETS   AGE
prometheus-k8s   1         19h
```

```
kubectl -n mongo describe role prometheus-k8s
Name:         prometheus-k8s
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"Role","metadata":{"annotations":{},"name":"prometheus-k8s","namespace":"mongo"},"rules":[{"ap...
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  endpoints  []                 []              [get list watch]
  pods       []                 []              [get list watch]
  services   []                 []              [get list watch]
```
```
level=error ts=2018-03-06T18:12:27.089527378Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list pods in the namespace \"mongo\""
level=error ts=2018-03-06T18:12:27.08955983Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list services in the namespace \"mongo\""
```

The same role with the same permissions exist in the `kube-system` namespace, as well as the role binding in the kube-system name space, and those do not throw errors.

**Comment by ephur** [comment]
The issue I mentioned was solved when deleting the Prometheus pods and letting them get recreated.

**Comment by ayashjorden** [comment]
@ephur How your --authorization-mode looks like?

I don't understand what is missconfigured in my env...

**Comment by ayashjorden** [comment]
Removing `Node` from authorization-mode broke my cluster, added it **after** RBAC.

@ephur ,
In my cluster, I have three ApiServers, each one with own TLS crt/key from Vault, but all of them are from the same PKI backend - e.g. same CA.

Based on pure TLS, using the CA from which all keys were generated, should verify the tokens..., no?

**Comment by ayashjorden** [comment]
I totally missed https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/8db0280ef6d311b1f4f23e6bab16019c3af7aaac/docs/08-bootstrapping-kubernetes-controllers.md

Didn't configure ApiServer `--service-account-key-file=/var/lib/kubernetes/ca-key.pem`
And ControllerManager :
```  --cluster-signing-cert-file=/var/lib/kubernetes/ca.pem \\
  --cluster-signing-key-file=/var/lib/kubernetes/ca-key.pem \\
  --service-account-private-key-file=/var/lib/kubernetes/ca-key.pem \\
```

Will report once I refactor my cluster to support that

Thank you all in the meantime 👍

**Comment by ayashjorden** [comment]
@ephur Thank you for the shared TLS crt/key tip it worked!

**Comment by ayashjorden** [comment]
What I still don't understand is:
- If all of the TLS crt/key pairs issued in my cluster, **are generated by the same CA**
- and the `controller-manager` uses Master1 TLS crt/key to sign tokens

Why Master2 or Master3 can't verify the tokens ?

**Comment by djsd123** [comment]
> The issue I mentioned was solved when deleting the Prometheus pods and letting them get recreated.

Thanks, @ephur.  This worked after scrutinising the `ClusterRole` for ages.  Didn't know this could happen.  Sounds like some sort of race condition 🤔
