### ISSUE TITLE
Prometheus discovery with systemd-managed control-manager and scheduler

### ISSUE THREAD

**Issue by mdacrema** [coreos/prometheus-operator#1044]
**What did you do?**
I've deployed kube-prometheus via hack/cluster-monitoring/deploy

**What did you expect to see?**
No alerts in the prometheus alert page

**What did you see instead? Under which circumstances?**
K8SControllerManagerDown and K8SSchedulerDown alerts triggered

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Manual deploy: 
- 3 master node running etcd, apiserver, control-manager and scheduler via systemd
- 3 worker node running calico and kube-dns as pods

**Comment by brancz** [comment]
You can similar to monitoring external etcd create a Service and Endpoints object manually and add the IPs + ports to your scheduler/controller-manager there. See here for the etcd example: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md

**Comment by mdacrema** [comment]
Ok, now it works!
Basically I had to edit actual endpoints which had "subsets:null" adding labels and correct addresses and ports.
Then I created services and all the alerts disappeared.

Thank you

**Comment by brancz** [comment]
Awesome! :tada:

**Comment by arthur-mencke-hs** [comment]
@mdacrema could you share the Endpoint changes and Service objects you created?

**Comment by amencke** [comment]
@mdacrema could you share the Endpoint changes and Service objects you created?

**Comment by mdacrema** [comment]
@amencke here you are

Scheduler: https://gist.github.com/mdacrema/e6284421b497f32d6c45b9524fff18db
Controller-manager: https://gist.github.com/mdacrema/414ad0e75159ab75718c69e1e448dd8e

If you're using calico you can also find custom definitions here: https://gist.github.com/mdacrema/04402fb4a7c338da122b00932f8ac05c

**Comment by amencke** [comment]
Thanks so much @mdacrema! Did you by any chance figure out how to deal with changing IP addresses of the masters (without having to manually update the endpoint objects)?
