### ISSUE TITLE
proposal: support configuring AlertManager mesh peers

### ISSUE THREAD

**Issue by crandles** [coreos/prometheus-operator#1052]
I would like to deploy an AlertManager mesh across multiple Kubernetes clusters. To do so, this would require some extra configuration of the `-mesh.peer` flag.

AM doesn't support service discovery [yet](https://github.com/prometheus/alertmanager/issues/645) -- ideally we would add an AlertingSpec, to the AlertmanagerSpec that would discover the other endpoints, similar to Prometheus.

Until that is available, would it be possible to support a list of initial peers to the AlertmanagerSpec?

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
...
spec:
  initialPeers:
  - fqdn-01.somewhere.com:1234
  - alertmanager-multi-cluster-fqdn.com
```

This could be used in conjunction with the peers automatically added via the operator when multiple replicas are defined.

**Comment by brancz** [comment]
I completely agree with all your requirements and am open to discuss strategies to get there, however, I would like to hold off on implementations on this until we actually use the reworked gossiping which ships in Alertmanager `v0.15.0`.

**Comment by crandles** [comment]
I think we should be able to leverage the `StaticConfigs` in #1100

**Comment by brancz** [comment]
I think I'd prefer not to mix the two concerns, I think I'm happy with having this in the Alertmanager object itself.

**Comment by crandles** [comment]
I was considering `additionalPeers: []string` to more specifically allow passing a set of additional `cluster.peer`'s to append to the starting flags.

**Comment by omerlh** [comment]
> Given that our recommendation is that to run a single Alertmanager cluster per organization, I feel this might be something we should be improving then 🙂 .

@brancz can you please elaborate on that? We have multiple production clusters, and currently, we're running an alert manager on each one of them (not ideal!). What is the recommended solution that is also HA? And how can you expose all alert manager pods easily? Using LoadBalaner service will not work here, and I'm not familiar with any good solution for exposing pod IPs. This is a discovery issue, not networking...
