### ISSUE TITLE
Alertmanager's data.retention option is not configurable

### ISSUE THREAD

**Issue by bgagnon** [coreos/prometheus-operator#1055]
Unless I am mistaken, there is no way to customize the `--data.retention` flag for the Alertmanager `StatefulSet` which defaults to 120 hours.

https://github.com/coreos/prometheus-operator/blob/dedb1f41e6c9229af05b88e16dc6cced39e2f0d6/pkg/alertmanager/statefulset.go#L165

Ideally, the `Alertmanager` CRD should support the same `retention` field as the Prometheus CRD.
For example, to set `retention: 30d`.

This is mostly for capacity planning on the `storage` configuration and the `requests.storage` value of the `volumeClaimTemplate`.

**Comment by brancz** [comment]
Happy to accept PRs to add this!
