### ISSUE TITLE
Pointing to custom alertmanager

### ISSUE THREAD

**Issue by tadasv** [coreos/prometheus-operator#1059]
I started prometheus operator with helm. Now I'm about to deploy kube-prometheus with helm. Is it possible to point prometheus to an existing alertmanager that's running outside of kubernetes cluster?

I see `alertingEndpoints` option in`prometheus` config but it looks like you must point to alert manager inside the cluster.

We already have alertmanager running elsewhere, and we'd like to just send data there.

**Comment by brancz** [comment]
That's not possible today, however, I'm open to adding an option for "static" Alertmanagers.

**Comment by brancz** [comment]
As a work around that would work today: you can specify an `Endpoints` object and a respective `Service` where you manage the IP of the Alertmanager yourself. Very similar to how people monitor external etcd today: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md

**Comment by tadasv** [comment]
I'll look into Endpoints option a bit closer. But it seems that you can't point an endpoint to a CNAME. We run on AWS and we'd have to point to ELB since there's no guarantees that ELB IP will stay the same.

What would it take to support passing in arbitrary configuration to prometheus? I'd be willing to fork the code for my own use.

**Comment by brancz** [comment]
That’s what I was trying to figure out. In that case I think it’s ok for us to accept allowing to set alertmanagers statically.

Note that you still want your alertmanager cluster to be HA and you need multiple ELBs to point at each instance.

**Comment by tomplus** [comment]
Duplicated: https://github.com/coreos/prometheus-operator/issues/871

I had the same problem and I've implemented a workaround. Settings static endpoints to alertmanagers would be great.

**Comment by brancz** [comment]
@tomplus in hindsight, I think it would be ok to enable use of static (dns) addresses. This will probably require authentication as well, which we've been meaning to add anyways.

**Comment by tadasv** [comment]
@tomplus I made a workaround for now also. Since endpoints needs IPs, I created a very simple service that runs nginx which proxies to ELB DNS.

**Comment by alice-sawatzky** [comment]
Has there been any progress on this? This would be very useful for my use case; I'm likely going to need to add an nginx contianer which adds an unnecessary point of failure.

**Comment by brancz** [comment]
We recently added additional alertmanager configs that allow you to add arbitrary discovery configurations known from prometheus. This has not been released yet, we’re working hard to get this release out, but there are a few more things to be finished.

**Comment by brancz** [comment]
The `v0.20.0` release is out. The `additionalAlertmanagerConfig` feature is now available. Closing here.

**Comment by crouth-redge** [comment]
I'm going in circles through the issues and API docs trying to fathom how this is intended to work e2e.

How do I configure a `Prometheus`, `Alertmanager` and `AlertmanagerConfig` objects to work with this? So far I can get a Prom config object and it wants a _secret_ reference for the `additionalAlertManagerConfigs` - which is expected to be a config for an `Alertmanager` - but I cannot see how we are expect to use this with `AlertmanagerConfigs` and the `alertmanagerConfigSelector`

**Comment by heliapb** [comment]
Hi @crouth-redge have you check the documentation available for the alerting - https://prometheus-operator.dev/docs/developer/alerting/
