### ISSUE TITLE
Cannot Deploy helm because of apiVersion

### ISSUE THREAD

**Issue by HannanSolo** [coreos/prometheus-operator#1072]
**What did you do?**
Tried to install kuberneted prometheus on my GKE 1.9.2 cluster.
`helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring`

**What did you expect to see?**
Yay good job its up and running, have fun.

**What did you see instead? Under which circumstances?**
`Error: apiVersion "monitoring.coreos.com/v1alpha1" in kube-prometheus/charts/exporter-kube-state/templates/servicemonitor.yaml is not available
`
By using the command on top.

**Environment**

Google Kubernetes engine 1.9.2GKE 

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	Google Kubernetes Engine

**Comment by HannanSolo** [comment]
Thanks for the quick reply!!
So i tried that a got a huge Auth error.

```
Error: release prometheus-operator failed: clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["thirdpartyresources"], APIGroups:["extensions"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["alertmanager"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["alertmanagers"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheus"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheuses"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["service-monitor"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["servicemonitors"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["*"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]}] user=&{system:serviceaccount:kube-system:default d5af753a-1c86-11e8-a413-42010a8001b1 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```
And I think I should already know how to do this, do you have any tips?

**Comment by gianrubio** [comment]
This looks related on how GKE manage permission, I have no experience with GKE so I can't help you. Theres a similar issue [here](https://github.com/coreos/prometheus-operator/issues/357) discussing GKE + RBAC + prometheus operator.

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
