### ISSUE TITLE
prometheus statefulsets volumeClaimTemplate lstat error for hostPath

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#1077]
**What did you do?**
Deploy prometheus statefulsets with persistent volume hostPath

**What did you expect to see?**
hostPath volume getting mounted

**What did you see instead? Under which circumstances?**
        The persistent volume is successfully bound in Persistent Volume.  The error below is from the prometheus statefulsets pod the dir did not get mount in /tmp/.../

        Error: lstat /tmp/mydir: no such file or directory
        Error syncing pod

**Environment**

* Kubernetes version information:

 	kubectl 1.7.4
        CentOS 7.3

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

Follow the recommend prometheus storage

       apiVersion: monitoring.coreos.com/v1
       kind: Prometheus
       metadata:
           name: my-example-prometheus-name
           labels:
              prometheus: example
       spec:
           ...
           storage:
              volumeClaimTemplate:
                  spec:
                     selector:
                        matchLabels:
                             app: my-example-prometheus
                     resources:
                         requests:
                            storage: 50Gi

         ---
         apiVersion: v1
         kind: PersistentVolume
         metadata:
              name: my-pv-name
              labels:
                 app: my-example-prometheus
         spec:
            capacity:
                storage: 50Gi
            accessModes:
            - ReadWriteOnce # required
            hostPath:
                path: "/tmp/mydir"

* Prometheus Logs:

          Error from server (BadRequest): container "prometheus" in pod "my-example-prometheus-name-0" is waiting to start: lstat /tmp/mydir: no such file or directory

**Comment by brancz** [comment]
I'm not 100% sure, but I believe everything is working as intended here, the `PersistentVolume` expects that you have already created the `/tmp/mydir` directory on your host in order to use it as a volume. I believe local-volumes in Kubernetes is more what you are looking for (which is an alpha feature right now I believe).

**Comment by brancz** [comment]
The Prometheus objects supports anything that a statefulset supports, but you of course need to satisfy the requirement of hostpath.

**Comment by bamb00** [comment]
@brancz The hostPath is use in PersistenVolume but the volumeMounts has to set in prometheus statefulsets.  I don't see how that is set.

**Comment by brancz** [comment]
The Prometheus object supports PVCs and doesn't intend to support any lower level specification. If you want hostpath PVs, then make them be selected by the PVC requirements. I recommend reading this: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

In your case I believe all you're missing is the `DirectoryOrCreate` type.

**Comment by bamb00** [comment]
I'm using k8s 1.7.4 which has not supported type: DirectoryOrCreate

**Comment by brancz** [comment]
In that case you just need to make sure it already exists on the host.

**Comment by bamb00** [comment]
@brancz Is there anyway I can disable the emptyDir in volumes and use hostPath? I notice when using volumeClaimTemplate the SubPath is creted.

**Comment by brancz** [comment]
The point of hostpath is that it just mounts whatever is on the host inside the container. There’s no other way.

**Comment by bamb00** [comment]
@brancz My concerns, the subPath name is always "prometheus-db" forcing all the prometheuses storage to be in one location.  I think the subPath is not necessary from prometheus volumeMounts.
