### ISSUE TITLE
Unable to see Targets for prometheus-frontend

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#1088]
**What did you do?**
Deploy prometheus-operator, prometheus-frontend with serviceaccount, roles, rolebinding.

**What did you expect to see?**
Not getting metrics at http://ip_address:30100

The prometheus-frontend is  using system:serviceaccount:monitoring:prometheus-frontend and the serviceAccountName: prometheus-frontend is set in the prometheus-frontend deployment

**What did you see instead? Under which circumstances?**
Targets info not displaying at http://ip_address:30100/targets

**Environment**

CentOS 7.3
prometheus-operator 0.14

* Kubernetes version information:

       Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
       Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

         #  kubectl get po -n monitoring
         prometheus-frontend-0                  2/2       Running   0          5m
        
        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: prometheus-frontend
          namespace: monitoring

       ---
       apiVersion: rbac.authorization.k8s.io/v1beta1
       kind: Role
       metadata:
          name: prometheus-frontend
          namespace: monitoring
       rules:
       - apiGroups: [""]
         resources:
         - nodes
         - services
         - endpoints
         - pods
         verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources:
        - configmaps
        verbs: ["get"]

       ---
       apiVersion: rbac.authorization.k8s.io/v1beta1
       kind: RoleBinding
       metadata:
          name: prometheus-frontend
          namespace: monitoring
       roleRef:
         apiGroup: rbac.authorization.k8s.io
         kind: Role
         name: prometheus-frontend
      subjects:
      - kind: ServiceAccount
         name: prometheus-frontend
         namespace: monitoring

* Prometheus-frontend Logs:

          level=error ts=2018-03-15T05:01:22.217971764Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:177: Failed to list *v1.Endpoints: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list endpoints at the cluster scope. (get endpoints)"
          level=error ts=2018-03-15T05:01:22.220082098Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:178: Failed to list *v1.Service: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list services at the cluster scope. (get services)"
          level=error ts=2018-03-15T05:01:22.22024442Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:179: Failed to list *v1.Pod: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list pods at the cluster scope. (get pods)"

**Comment by mxinden** [comment]
@bamb00 Thanks for your bug report.

Do I understand correctly that you are facing the following two issues:
- prometheus-frontend not discovering the example-app targets
- Retrieving the `/metrics` endpoint from the prometheus-frontend instance

Did you use the [./hack/example-service-monitoring/deploy](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/example-service-monitoring/deploy) script?

Would you mind pasting the output of the following command (promtheus configuration yaml) here:
```
kubectl exec -it prometheus-frontend-0 -- cat /etc/prometheus/config/prometheus.yaml
```
(Make sure to elide any secrets)

Are you able to reproduce the same issue with [Prometheus operator 0.17](https://github.com/coreos/prometheus-operator/releases/tag/v0.17.0)?

Might be related to: https://github.com/coreos/prometheus-operator/pull/1107

**Comment by bamb00** [comment]
Thanks for pointing out #1107 I see what I did wrong.
