### ISSUE TITLE
[helm] exporter-kube-state chart ignores replicaCount

### ISSUE THREAD

**Issue by mxey** [coreos/prometheus-operator#1090]
In the deployment template, replicas is overwritten with value `1`: https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-state/templates/deployment.yaml#L15

**What did you do?**

`helm install coreos/exporter-kube-state --set replicaCount=2` 

**What did you expect to see?**

```
==> v1beta1/Deployment
NAME                                  DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
incindiary-skunk-exporter-kube-state  2        2        2           2          54s

```

**What did you see instead? Under which circumstances?**

```
==> v1beta1/Deployment
NAME                                  DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
incindiary-skunk-exporter-kube-state  1        1        1           1          54s

```

**Environment**

* Kubernetes version information:

      Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
      Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 

	kubeadm

**Comment by gianrubio** [comment]
@mxey do you mind to make a PR to fix that?
