### ISSUE TITLE
Unable to retrieve metrics from k8s custom metrics server

### ISSUE THREAD

**Issue by chlung** [coreos/prometheus-operator#1093]
**What did you do?**
I deploy Prometheus Operator(kube-prometheus/hack/cluster-monitoring/deploy) and custom metrics server(kube-prometheus/manifests/custom-metrics-api).  The metrics are able to access through curl and kubectl but not from direct api call inside a program.  I try to know if I miss somehing.

**What did you expect to see?**
I am calling /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/memory_max_usage_bytes, and I expect to get the result back just like "curl http://hostname:port//apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/memory_max_usage_bytes.
**What did you see instead? Under which circumstances?**
I see no result or error back.  When I call /apis/custom.metrics.k8s.io/v1beta1, I can see a list of metrics.
**Environment**
ubuntu 16.04
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
I am using kubeadm script from https://github.com/Mirantis/kubeadm-dind-cluster
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
This is likely something to ask in the adapter repository, as I believe it's about using the API correctly. This walk through is slightly outdated, but except for the apiGroup change it should conceptually work similarly.

**Comment by chlung** [comment]
@brancz I will post the question to adapter repo.  Thanks.
