### ISSUE TITLE
no way to set insecureSkipVerify for alertmanager connections

### ISSUE THREAD

**Issue by jpiper** [coreos/prometheus-operator#1094]
I have the problem that I need to use an external alert manager. I've created an endpoint object and service as mentioned in https://github.com/coreos/prometheus-operator/issues/871#issuecomment-356598118

The problem I'm having here is that my company doesn't sign certs for IP addresses, so I can't push via https to our external alertmanager unless I could can enable `insecureSkipVerify` for alertmanager pushes

I also tried using port 80 (the alertmanager is returning an HTTP 302 redirect to) but prometheus doesn't appear to follow the redirect (and silently fails!)

It would be great if we could surface an option to set `insecure_skip_verify` on the alertmanager's `tls_config`

> level=error ts=2018-03-16T04:04:57.777880847Z caller=notifier.go:473 component=notifier alertmanager=https://X.X.X.X:443/api/v1/alerts count=0 msg="Error sending alert" err="Post https://X.X.X.X:443/api/v1/alerts: x509: cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs"

**Comment by crandles** [comment]
I think it might be better to surface the `tls_config` ([TLSConfig](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig)) to follow how those configurations are exposed in other resources

**Comment by jpiper** [comment]
Ah good idea, I can redo my PR on Monday :)
