### ISSUE TITLE
Add statefulset_errors_total metric with alert

### ISSUE THREAD

**Issue by metalmatze** [coreos/prometheus-operator#1097]
**What did you do?**
Run the Operator and probably update the Prometheus CRD.

**What did you expect to see?**
The StatefulSet should be updated.

**What did you see instead? Under which circumstances?**
The StatefulSet was not updated. I could see this in the logs:

```
E0316 10:50:53.825175       5 operator.go:577] Sync "monitoring/prometheus" failed: updating statefulset failed: StatefulSet.apps "prometheus-prometheus" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

I'd like to have a metric for this, so we can alert on the `sum(rate(prometheus_operator_statefulset_errors_total[5m]))`. I sometimes don't see that these errors happen in the background and thus think a metric with alert would be perfect here.

**Comment by brancz** [comment]
I think a general metric on "prometheus_operator_reconcile_errors_total" would catch this and further issues. Big thumbs up! :+1:
