### ISSUE TITLE
Auto generate docs for API

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#110]
As the code is always the source of truth and the types published as part of the API should be well commented, we should be able to auto generate at least the documentation for those objects.

Not a priority, but opening this for tracking.

@alexsomesan @fabxc

**Comment by alexsomesan** [comment]
I support this. Might get us to write more of it it's in the code.
Could also help the code be more easily understandable, I guess.

Let's give it a try with some smaller package and see how it works.
