### ISSUE TITLE
Support Alertmanager >=v0.15.0 

### ISSUE THREAD

**Issue by mxinden** [coreos/prometheus-operator#1109]
With Alertmanager >=v0.15.0 the gossip library changes to https://github.com/hashicorp/memberlist. With the library, Alertmanager flags change.

This issue tracks the effort of supporting new Alertmanager versions with the Prometheus operator.

**Comment by jolson490** [comment]
Just curious, can/should this issue be closed, now that https://github.com/coreos/prometheus-operator/pull/1122 has been merged?

By the way, thank you @mxinden very much for making this change - I've been looking forward to being able to use the latest version of alertmanager.

**Comment by brancz** [comment]
@jolson490 nice catch, yes indeed this can be closed! Thanks!
