### ISSUE TITLE
Grafana: Support setting secrets from values or by overriding with --set

### ISSUE THREAD

**Issue by ehvattum** [coreos/prometheus-operator#1110]
**What did you do?**
Try to deploy a release of grafana with google auth.

**What did you expect to see?**
Sensitive credentials like `GF_AUTH_GOOGLE_CLIENT_SECRET` not stored in the plain yaml file of the deployment.

**What did you see instead? Under which circumstances?**
Sensitive credentials stored plainly, since there are no extension points into which I can create additional secrets.

It would be nice to be able to define deploy-time secrets that will be injected into the release, in the same pattern as the extraEnv-feature enables configuration of grafana for non-sentitive values.

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by gianrubio** [comment]
@ehvattum indeed these variables are not stored in secrets, do you want to contribute to the project doing a PR?

**Comment by richerve** [comment]
@ehvattum Right now you can specify those variables in `extraVars` and use a Secret to reference the values, that's what I'm doing to configure an external RDS db. You will need to manage the Secret creation as this will not be handled by kube-prometheus.

**Comment by ehvattum** [comment]
I'm working on a general fix to this, and will submit a PR.

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
