### ISSUE TITLE
helm: prometheus secrets default is empty map, should be empty list

### ISSUE THREAD

**Issue by Nonymus** [coreos/prometheus-operator#1113]
**What did you do?**
Used `kube-prometheus` helm chart as dependency in a tailored monitoring system. In its values.yaml, added a secret for prometheus:
```
---
kube-prometheus:
  prometheus:
    secrets:
      - etcd-certs
```
**What did you expect to see?**
Helm will install and configure the chart without complaining.

**What did you see instead? Under which circumstances?**
The end result is working as expected, but helm issues a warning:
`warning: cannot overwrite table with non table for secrets (map[])`

I created a pull request, #1112. Should be an easy fix.

**Environment**

* Kubernetes version information:

      Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
      Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kubespray v2.4.0

**Comment by gianrubio** [comment]
Closed by #1112
