### ISSUE TITLE
Grafana chart pointing to nowhere

### ISSUE THREAD

**Issue by alexppg** [coreos/prometheus-operator#1118]
**What did you do?**
Install the grafana chart.
**What did you expect to see?**
I expected to it to work correctly.
**What did you see instead? Under which circumstances?**
It did, mostly. By default, the prometheus datasource points to `http://{{ printf "%s-%s" .Release.Name "prometheus" }}:9090`. As I understand, this is not correct. By adding the "release name" namespace, it's impossible to make it point to the correct prometheus, since this chart doesn't include a prometheus instance. Thus, this value should be not only configurable but required to be configured, since it points nowhere by default and it's not possible to know where it will point in advance.

I hope it's clear enought.

PD: Thanks for your work! The prometheus-operator and the prometheus charts are awesome.

**Comment by brancz** [comment]
@gianrubio is probably the best to answer this :slightly_smiling_face:

**Comment by gianrubio** [comment]
Sorry @alexppg  but I don't get what didn't work in your setup or what do you want to make configurable, could you explain again? Please give more info like variables, logs or how did you create the charts.

**Comment by alexppg** [comment]
Sure @gianrubio, I'll explain myself.
When you use the grafana chart, it creates a prometheus datasource, which is pointing to `http://{{ printf "%s-%s" .Release.Name "prometheus" }}:9090`. Since the grafana chart doesn't include the installation of prometheus, it means that it will never point to a real installation of prometheus.
For example:

`helm install -f microservice.yml --namespace monitoring --name grafana coreos/kube-prometheus`

This will create the pod `monitoring-grafana`. When I create the prometheus pod, I'd execute:

`helm install -f microservice.yml --namespace something --name prometheus coreos/kube-prometheus`

Then the pod will be named `something-prometheus`.  Thus, will never point to the correct prometheus, since I can't modify the datasource.

**Comment by richerve** [comment]
@alexppg the kube-prometheus Chart is self-contained, is basically a wrapper that include a bunch of other Charts like grafana and prometheus. You will need to do only one installation of `kube-prometheus` and that will install and configure grafana, prometheus and exporters. Doing a `helm install` (a Release) for each one doesn't make sense as you're duplicating all other resources under each Release.

**Comment by alexppg** [comment]
You're absolutely write. I didn't see the option to deploy grafana in the kube-prometheus chart, sorry for the noise.
