### ISSUE TITLE
Question: Grafana Helm Chart >= 5.0.0 and grafana-watcher

### ISSUE THREAD

**Issue by richerve** [coreos/prometheus-operator#1127]
Given that with Grafana version 5.0.0 the functionality provided by grafana-watcher is basically built-in, I think it makes sense to remove the requirement of grafana-watcher and refactor the helm chart to use this built-in features.

My main question is how to approach this?
1. Modify the grafana Helm Chart on prometheus-operator and bump the major version (or at least the minor if we want to stay on 0.x).
2. Modify the grafana Helm Chart on prometheus-operator and add a conditional inside the template so that grafana-watcher is only needed when the grafana image version is < 5.0.0.
3. Contribute "upstream" on the stable Grafana Chart.

**Comment by richerve** [comment]
@gianrubio What's your opinion on this?

**Comment by gianrubio** [comment]
> Given that with Grafana version 5.0.0 the functionality provided by grafana-watcher is basically built-in, I think it makes sense to remove the requirement of grafana-watcher and refactor the helm chart to use this built-in features.

Agreed!

As we discussed on #592 and https://github.com/kubernetes/charts/pull/3490 we are working to move all the charts to upstream except kube-prometheus and prometheus operator. I already started working on node-exporter, any help for other charts will be welcome. Do you want to point the current grafana chart to the upstream?

**Comment by richerve** [comment]
TBH, upstream `stable/grafana` Chart is very clean and well maintained, of course it doesn't have grafana-watcher and uses Jobs instead but again that is the main point to remove. I will try to ask upstream if they have a path to follow for 5.0.0 and then I will work in adapting it for kube-prometheus, I mean, adjusting `values.yaml`.

**Comment by gianrubio** [comment]
@richerve we have [another issue](https://github.com/coreos/prometheus-operator/issues/1154) to track the progress of helm charts. Do you still want to work in the grafana chart?

**Comment by richerve** [comment]
Yes I can work on the grafana Chart.
