### ISSUE TITLE
Add log.level to AlertmanagerSpec

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1136]
Hello. I'd please like functionality added to [AlertmanagerSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) to allow a value to be specified for `log.level`.

More info:

I'd like something about firing alerts to be included in the alertmanager logs. The alertmanager default log level is `info`, which doesn't include alerts, but I installed alertmanager via helm and specified the `debug` level and then I found the logs do include firing alerts.

Currently with prometheus-operator the only way I could do this would be to build my own prometheus-operator with the following change:
```
~/prometheus-operator
$ git diff pkg/alertmanager/statefulset.go
@@ -173,6 +173,7 @@ func makeStatefulSetSpec(a *monitoringv1.Alertmanager, config Config) (*v1beta1.
        amArgs := []string{
                fmt.Sprintf("-config.file=%s", alertmanagerConfFile),
+               fmt.Sprintf("-log.level=debug"),
                fmt.Sprintf("-web.listen-address=:%d", 9093),
```

(There's more details in the [firing alerts not in alertmanager logs](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/prometheus-users/vI14mjI42j0) topic in the [Prometheus Users](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/prometheus-users) Google group.)

**Kubernetes version information:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes cluster kind:**

I'm using [self-hosted-deploy](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/kube-prometheus/hack/cluster-monitoring/self-hosted-deploy) to deploy kube-prometheus to a K8s cluster (which I created with my own custom terraform `cloud-config-*` scripts) running in AWS.

**Comment by brancz** [comment]
happy to have the Alertmanager log level in the AlertmanagerSpec just like the PrometheusSpec does :slightly_smiling_face: , would you like to shoot us a PR?

**Comment by jolson490** [comment]
hi @mxinden . I see you beat me to this - that you already did this via #1192 - thanks! Closing this issue.

**Comment by mxinden** [comment]
@jolson490 Oh, I was not aware of this issue. Thanks for the update here.
