### ISSUE TITLE
Support Grafana 5.0.3

### ISSUE THREAD

**Issue by michaelpietzsch** [coreos/prometheus-operator#1138]
Hi,

anyone has a clue when Grafana 5.0.3 is going to be available at the quai repo?
quay.io/repository/coreos

regards michael

**Comment by brancz** [comment]
If you shoot us a PR updating everything I'll be happy to publish the new image :slightly_smiling_face:

**Comment by alex-hempel** [comment]
I'll be happy to take a shot at this.

**Comment by brancz** [comment]
The image has since been updated and pushed. Closing.
