### ISSUE TITLE
How to provide imagePullSecrets when using helm operator?

### ISSUE THREAD

**Issue by andersflemmen** [coreos/prometheus-operator#1150]
What is the best way to provide imagePullSecrets to the different service accounts used by the operator when using helm for deployment? I am currently patching the service accounts manually, but this requires running the deployment script multiple times, as the service accounts are created when installing the chart, and any changes to the service accounts don't seem to be picked up by currently running pods. Is there a better way?

**Comment by gianrubio** [comment]
There's no support for private images for now. I'm wondering what kind of image are you deploying to require to host privately. In my case all prometheus metrics are running in custom build but I always push as public image.

**Comment by brancz** [comment]
This should be supported, different companies have different standards on this. The Prometheus and Alertmanager objects already support it so at just a matter of adding the playing with helm.

**Comment by andersflemmen** [comment]
Yes, it is company standards. Would be really nice to have indeed!

**Comment by gianrubio** [comment]
@andersflemmen would you like to contribute to the project sending a PR to us?

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
