### ISSUE TITLE
Helm: Add the ability to specify custom configuration files for Grafana

### ISSUE THREAD

**Issue by marc-sensenich** [coreos/prometheus-operator#1153]
In some cases there is the need to define additional configuration files for configuring Grafana, the one case that is being faced is to define an LDAP configuration for Grafana. Therefore, there should be an option to define and mount custom configuration files for Grafana when using the Helm chart deployment. 

A potential solution for this has been implemented in #1147

**Comment by Smana** [comment]
@marc-sensenich did find a way to configure grafana that comes with kube-prometheus ?
Actually we managed to deploy grafana with the stable/grafana thanks to your change :)

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by us, they are maintained on the upstream helm charts repo. Please open an issue there.
