### ISSUE TITLE
Official helm chart

### ISSUE THREAD

**Issue by pierreozoux** [coreos/prometheus-operator#1154]
This is a meta issue to track progress around the plan to make this an official helm chart:

 - [ ] [prometheus-operator](https://github.com/kubernetes/charts/pull/3490)
 - [x] node-exporter @gianrubio  (https://github.com/kubernetes/charts/pull/4260)
 - [ ] kube-prometheus
 - [ ] kube-state-metrics
 - [ ] grafana (we don't need to move the chart because it already exist in the upstream, we should point the requirements to upstream and adapt some variables)  (https://github.com/coreos/prometheus-operator/issues/1127)  @richerve 
 - [ ] alertmanager (created through prometheus-operator)
 - [ ] prometheus (created through prometheus-operator)

@gianrubio In #1127 you say `we are working to move all the charts to upstream except kube-prometheus and prometheus operator`
Why not kube-prometheus and prometheus operator? for instance [cert-manager helm chart](https://github.com/jetstack/cert-manager) is developped upstream, but still available as an official helm chart. This looks like best of both worlds for me :).

**Comment by gianrubio** [comment]
@pierreozoux you're very welcome to help us to move/point charts to upstream. For now I don't know if makes sense to move all chart there so any other feedback are welcome . 

ps. I edited your first comment adding more links and comments

**Comment by gianrubio** [comment]
I update the issue, assign @richerve to grafana chart

**Comment by jody-frankowski** [comment]
I think this can help a lot of users discover this tool, and I also think the "official" charts repo is an entrypoint where most users search for them at first (at least I do this).
However I see at least one potential problem which is the upsteam merging speed.

**Comment by gianrubio** [comment]
> However I see at least one potential problem which is the upsteam merging speed.

@jody-frankowski I just receive permission to merge requests in the upstream using the [OWNERS](https://blog.github.com/2017-07-06-introducing-code-owners/) file, in this case I can easily merge requests there.

**Comment by richerve** [comment]
Recently there were a couple of important PRs in upstream `stable/grafana` that made it more flexible and support Grafana > 5.0.0 in a proper way. Taking a quick look it doesn't seem to be very difficult to use stable/grafana in kube-prometheus, I will try to start to work on this, this week.

**Comment by gianrubio** [comment]
@richerve, @pierreozoux any progress on this issue?

**Comment by richerve** [comment]
@gianrubio Sorry for the late reply, I'm actively working on this, I have a private copy of stable/grafana, applied a couple of changes and will be replacing kube-prometheus grafana soon. I will send a PR with those changes, hopefully next week.
I general I think right now is technically possible to migrate the to stable/grafana without any more change but is not convenient because of the way to define the dashboards on values.yaml for example. As soon as I open the PR I will link it.

**Comment by richerve** [comment]
The aforementioned PR was merged some time ago and I'm already using that Chart instead of coreos/grafana working along side kube-prometheus. I will work on the integration next week.

**Comment by gianrubio** [comment]
FYI I'm working on the node-exporter upstream, I added a PR https://github.com/helm/charts/pull/6742 to make it full compatible with prometheus-operator/node-exporter . 

I'll point the kube-prometheus/requirements.yaml file to the upstream when the PR get merged.

**Comment by desaintmartin** [comment]
What else would we need to consider upstream grafana usable for prometheus-operator?

**Comment by vsliouniaev** [comment]
I think it's integrated but pretty awkward w.r.t. selecting data sources and adding dashboards

**Comment by gianrubio** [comment]
Issue will be closed since the helm charts have been migrated to [charts upstream](https://github.com/helm/charts/tree/master/stable/prometheus-operator)
