### ISSUE TITLE
Add node/kubelet monitoring

### ISSUE THREAD

**Issue by drampelt** [coreos/prometheus-operator#116]
I was following the [kube-prometheus](https://github.com/coreos/kube-prometheus) guide but it seems like the operator overwrites the initial config map with the configuration for the `ServiceMonitors` and as a result the kubelet monitoring is lost.

The `node-exporter`s and `kube-state-metrics` (also deleted by the operator) can be monitored again using `ServiceMonitors` but as far as I can tell the kubelets can't since it uses the `node` role.

**Comment by brancz** [comment]
When no service monitors selector is specified the configuration is not generated but can be specified by the user using a configmap named the same as the Prometheus deployment. If servicemonitors are specified, it will override the existing configmap. Not that features like alertmanager discover also will not be applied in that case.

Regarding your issue of monitoring kubelets, kubelets are going to be self-hosted so they are monitored just like any other application. Have a look at the service monitors documentation, it describes how discovery works. tl;dr create a headless service without a labelselector and then you can populate a kubernetes Endpoints object with the IP addresses of your kubelets and they will be discoverable through servicemonitors.

**Comment by drampelt** [comment]
Thanks for the detailed explanation! I'll give that a shot.
