### ISSUE TITLE
kube-prometheus: Grafana datasource provisioning?

### ISSUE THREAD

**Issue by ScottBrenner** [coreos/prometheus-operator#1161]
Quick question - what is the suggested method for Grafana datasource provisioning when using kube-prometheus? I managed to get it working using Grafana 5's method (http://docs.grafana.org/administration/provisioning/#datasources) but am wondering if there's a (better) way to do it using kube-prometheus - I've tried editing configmaps and using some of the provided generator scrips but no luck. Thanks!

edit: Seems using Grafana 5's provisioning overwrites/deletes the datasource and dashbaords created by kube-prometheus., how can I provision datasources through kube-prometheus?

**Comment by brancz** [comment]
Ultimately we want to get to a point where we do this in a very similar way to https://github.com/brancz/kubernetes-grafana, that way everything is streamlined and all generated via one language: jsonnet. It is almost at feature parity with the kube-prometheus dashboards, so if you want to get started with the future proof way I recommend contributing to that, as we will soon be switching over to it in kube-prometheus.

**Comment by ScottBrenner** [comment]
Neat, thanks!
