### ISSUE TITLE
Support for a custom scrape job on ServiceMonitor

### ISSUE THREAD

**Issue by aonz** [coreos/prometheus-operator#1165]
**What did you do?**

We launched Prometheus Operator in our Kubernetes cluster and it works fine with monitoring our pods with `ServiceMonitor`. However, we would like to also be able to monitor the existing services running on EC2 instances.

**What did you expect to see?**

After reading this issue https://github.com/coreos/prometheus-operator/issues/671, it seems like we have to choose between using `ServiceMonitor` and the manual prometheus.yaml. 

So would it be possible to extend `ServiceMonitor` to support other service discovery types beside Kubernetes? Or adding a field e.g. like `ScrapeConfig` on the `ServiceMonitor` struct to allow to specify the custom config rather than using the auto generated one?

**Comment by ephur** [comment]
Just a thought, but you could create services with a list of endpoints. This is how we monitor items that are not in the cluster. For examples take a look at:

https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by aonz** [comment]
Thank you for the info. I tried it and it seems to work with the static IPs. :)

But since most of our apps are running under an auto scaling group with dynamic IPs, it won't work well in this case. `ExternalName` did not work also, since `ServiceMonitor` will only use `Endpoints`. :(

**Comment by brancz** [comment]
Custom scrape jobs go so deeply into configuring Prometheus that we recommend to just use a custom config for it: https://github.com/coreos/prometheus-operator/blob/master/Documentation/custom-configuration.md

You still get rolling upgrades and all of those things, but you will just have to manage the configuration yourself.

**Comment by jdfalk** [comment]
Could the operator be modified to look at a second configmap/secret and concat the autogenerated with that? Something like 'prometheus-config-override' which allows the users to put in additional manual configuration that will be appended to the end of the autogenerated config. I think that would solve 99% of these problems and still put the onus on the user to ensure their custom config is correct.

It looks like that's how some other projects are approaching custom configs: https://rook.io/docs/rook/master/advanced-configuration.html#custom-cephconf-settings

**Comment by jdfalk** [comment]
As a follow up, you could eliminate the static config field of the service monitor crd and just leave that up to the user in custom configuration. Hopefully, that would keep service monitors a bit cleaner and create a clear distinction that service monitors are for kubernetes native objects vs custom config for everything else.

**Comment by brancz** [comment]
We implemented what @jdfalk suggested. It is meant as a last resort, anything that's not possible with it you will have to build your own tooling around.
