### ISSUE TITLE
kubectl apply does not work

### ISSUE THREAD

**Issue by one000mph** [coreos/prometheus-operator#118]
This may be similar to #91. Currently I have to delete and recreate Prometheus and ServiceMonitor resources with every update to the manifest.
```
[10:05:04][~]$kc -n monitoring apply -f servicemonitor-node-exporter.yaml
error: unable to decode "servicemonitor-node-exporter.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
```

**Comment by brancz** [comment]
Yes this is unfortunately a problem with `kubectl` itself. It is being tracked [upstream](https://github.com/kubernetes/kubernetes/issues/29542). FWIW  `kubectl replace` will probably do in almost all cases (I can't think of a case where it wouldn't for the TPRs of the Prometheus Operator, but there may still be one).

**Comment by whereisaaron** [comment]
There are a few things like namespaces and thirdpartyresources that cannot be apply'ed. The biggest problem is how misleading the error message is. You can't use 'replace' to create things, so you are left with no 'upsert' option. Looks like it is [fixed](https://github.com/kubernetes/kubernetes/pull/40666) for next kubectl release. In the meantime you can script around it.

```
if [[ -z $(kubectl get servicemonitor my-foo -o name 2> /dev/null) ]]; then
  kubectl create -f servicemonitor-node-exporter.yaml
else
  kubectl replace -f servicemonitor-node-exporter.yaml
fi
```

**Comment by one000mph** [comment]
@whereisaaron thanks for that workaround. Glad to see that a fix is coming down in the next release.

**Comment by brancz** [comment]
Kubernetes 1.6 was released and I just verfied it works with a Kubernetes 1.6 cluster and kubectl version 1.6 :tada:
