### ISSUE TITLE
Missing example app in Helm kube-prometheus

### ISSUE THREAD

**Issue by vielktus** [coreos/prometheus-operator#1188]
**What did you do?**
helm install kube-prometheus
**What did you expect to see?**
there's an example app prometheus instance
**What did you see instead? Under which circumstances?**
no example app

Not sure if this is missing or I should config a different way when using Helm to deploy kube-prometheus (write another helm like "prometheus-my-app" and select example-app ServiceMonitors)?

**Comment by vielktus** [comment]
Already installed prometheus-operator (helm)
I mean this example app "contrib/kube-prometheus/manifests/examples/example-app/". This is an example to create a Prometheus instance to monitor this app, as I understand. So when it comes with helm, how should I create prometheus instance (leave the config stuffs for prometheus-operator to generate) ?

**Comment by gianrubio** [comment]
Prometheus instance is automatically created when deploy kube-prometheus and prometheus-operator. The example app is basically a deployment with the right serviceMonitor and not a prometheus instance.

Please share the pods you have deployed and `helm ls` output

**Comment by vielktus** [comment]
helm list:
```
NAME               	REVISION	UPDATED                 	STATUS  CHART                     	NAMESPACE
kube-prometheus    	2       	Fri Apr  6 15:39:48 2018	DEPLOYEDkube-prometheus-0.0.43    	devops
prometheus-operator	1       	Thu Apr  5 15:28:00 2018	DEPLOYEDprometheus-operator-0.0.15	devops
```
pods:
```
NAME                                                   READY     STATUS    RESTARTS   AGE
alertmanager-kube-prometheus-0                         2/2       Running   2          1d
kube-prometheus-exporter-kube-state-7f7469d7ff-db5gk   2/2       Running   6          4d
kube-prometheus-exporter-node-jqlc5                    1/1       Running   3          4d
kube-prometheus-grafana-6cd54fd88f-x5jjf               2/2       Running   6          4d
prometheus-kube-prometheus-0                           2/2       Running   6          4d
prometheus-operator-7dc9445795-l88vb                   1/1       Running   5          5d
```
It's not really what I mean Gianrubio :). Personally, I think the idea behind Prometheus Operator is to deploy the `kind` Prometheus, and prometheus-operator will watch this object to generate Prometheus instance. So, we can define many Prometheus `kind` and choose desired ServiceMonitors. If I follow this helm, I will create a Prometheus instance included all of the metrics (the cluster and the services). I'm afraid this will not really utilize the prometheus-operator.

The YAML files in `contrib/kube-prometheus/manifests` will deploy a Prometheus instance with only metrics of K8s cluster. And the example `contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend.yaml` will deploy a Prometheus instance with only metrics of the services running on top of K8s.

So I'm wondering that if I use this helm, Should I write a seperate helm which deploys `Kind` Prometheus (with our ServiceMonitors) ? And this time, I'll have 2 Prometheus instances running (one is kube-prometheus's and one is mine) Just like the idea in `contrib/kube-prometheus/hack/cluster-monitoring/deploy`.
