### ISSUE TITLE
clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges

### ISSUE THREAD

**Issue by ghost** [coreos/prometheus-operator#1189]
**What did you do?**
Trying to install prometheus using helm on AWS cluster

**What did you expect to see?**
Correct installation

**What did you see instead? Under which circumstances?**
Error: release prometheus-operator failed: clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["thirdpartyresources"], APIGroups:["extensions"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["alertmanager"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["alertmanagers"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheus"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["prometheuses"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["service-monitor"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["servicemonitors"], APIGroups:["monitoring.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["*"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]}] user=&{system:serviceaccount:kube-system:default c2025309-2c71-11e8-8646-028e7262e308 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**Environment**
AWS

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kops
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

I have seen there are suggested fixes for this on GKE but don't seem to be able to do the same for AWS. Any help appreciated!

**Comment by brancz** [comment]
The general problem is that the user you are using is trying to grant higher privileges that you have yourself, so you need to find a way to have a user that does have enough permissions.

**Comment by oliver-whiteman** [comment]
What privileges are required? I'm struggling a bit to understand the output and what specifically it cannot do

**Comment by brancz** [comment]
What did you execute to get this error? Did you deploy the `bundle.yaml` or use the hack script to install the kube-prometheus stack?

**Comment by abhaysr** [comment]
@brancz I am having the same issue, I am trying to deploy Prometheus on 1.8.7 using the admin user. Deployed k8s using kops.

**Comment by brancz** [comment]
Could you try just running `kubectl create -f bundle.yaml` on the [`bundle.yaml`](https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml) file in the root of the repository. If you get the same error your user does not have enough permissions to deploy the stack. Your user needs all permissions that the cluster role contains in order to grant those same privileges.

**Comment by voron** [comment]
I hit similar error due to RBAC disabled in k8s, and fixed it just with helm arg `--set rbacEnable=false`

**Comment by rabun788** [comment]
I am getting the same error after building the manifest/ dir in contrib/kube-prometheus after running the build.sh script and the sed for http since im pushing to GKE.

Also getting the error with bundle.yml
```
$ kubectl create -f bundle.yaml
deployment.apps/prometheus-operator created
serviceaccount/prometheus-operator created
Error from server (AlreadyExists): error when creating "bundle.yaml": clusterrolebindings.rbac.authorization.k8s.io "prometheus-operator" already exists
Error from server (Forbidden): error when creating "bundle.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:["apiextensions.k8s.io"], Resources:["customresourcedefinitions"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["alertmanagers"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["prometheuses"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["prometheuses/finalizers"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["alertmanagers/finalizers"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["servicemonitors"], Verbs:["*"]} PolicyRule{APIGroups:["monitoring.coreos.com"], Resources:["prometheusrules"], Verbs:["*"]} PolicyRule{APIGroups:["apps"], Resources:["statefulsets"], Verbs:["*"]} PolicyRule{APIGroups:[""], Resources:["configmaps"], Verbs:["*"]} PolicyRule{APIGroups:[""], Resources:["secrets"], Verbs:["*"]} PolicyRule{APIGroups:[""], Resources:["pods"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["pods"], Verbs:["delete"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["create"]} PolicyRule{APIGroups:[""], Resources:["services"], Verbs:["update"]} PolicyRule{APIGroups:[""], Resources:["endpoints"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["endpoints"], Verbs:["create"]} PolicyRule{APIGroups:[""], Resources:["endpoints"], Verbs:["update"]} PolicyRule{APIGroups:[""], Resources:["nodes"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["nodes"], Verbs:["watch"]} PolicyRule{APIGroups:[""], Resources:["namespaces"], Verbs:["get"]} PolicyRule{APIGroups:[""], Resources:["namespaces"], Verbs:["list"]} PolicyRule{APIGroups:[""], Resources:["namespaces"], Verbs:["watch"]}] user=&{kyle_jackson@homedepot.com  [system:authenticated] map[user-assertion.cloud.google.com:[AGKDXmoVwaRUA286/L7ZNAH5lVqUG3mbQujGzXfXmFEkUA+zDDGXemTbEqYb/PhyzgBpkpSllNsoqCkRDwYkOo9SJJDuTAvk0TYgSom+ZGq0VxttT2p5hQFtgWA4SlnrKYI/y17j9IUWqmaP9MY3eYC8W1c8RTVs7GEBk0aNwpKwGzogSC+1V1LYhbiH/UdBvk+AqtKFh2hojVO8gtDWnnvJjISKvsHKD0gX84f5AmFytJll]]} ownerrules=[PolicyRule{APIGroups:["authorization.k8s.io"], Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/openapi"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/openapi/*"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/version/"], Verbs:["get"]}] ruleResolutionErrors=[]

**Comment by andig** [comment]
Same problem here. I've successfully deployed on Azure, but after deleting and deploying again this error appeared. Cannot see what should have changed on the cluster in the mean time.

**Comment by dallasclouddev** [comment]
Same problem with minishift 3.9 running on Centos.
$ ./helm install --name ingress stable/nginx-ingress
Error: release ingress failed: clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tiller:tiller" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope: User "system:serviceaccount:tiller:tiller" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope

**Comment by JanMatas** [comment]
It might be worth trying to assign cluster admin priviledges to yourself:

```kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=your.email@address.com ```

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
