### ISSUE TITLE
ConfigMap update is reseted

### ISSUE THREAD

**Issue by f0** [coreos/prometheus-operator#119]
Hi,

if i update the ConfigMap with kubectl replace , it works. After some time (Minutes)  the ConfigMap is reset to the Factory state.

Is updating the ConfigMap not supported? Witout the correct config i cannot Monitor kubernetes (and the factory ConfigMap does not work)

regards f0

**Comment by brancz** [comment]
The Prometheus Operator generates a config for you, based on the `ServiceMonitor`s discovered through the `serviceMonitorSelector`, this means that the config will be completely managed by the Operator for you. If you don't specify a selector, the config will not be managed, and you can provide your own configuration.

Aside from that, can you tell us what you are having trouble with in regards to monitoring your Kubernetes cluster? It is possible to monitor your entire Kubernetes cluster with the current state of the Operator. We started a collection of manifests to monitor clusters in [kube-prometheus](https://github.com/coreos/kube-prometheus).

**Comment by f0** [comment]
@brancz  ah ok, the i need to check this, i installed from the examples directory, and the prometheus targets page was empty

**Comment by f0** [comment]
@brancz   tested kube-prometheus , works , this can closed
