### ISSUE TITLE
master tag of docker image not update

### ISSUE THREAD

**Issue by thu2004** [coreos/prometheus-operator#1199]
**What did you do?**
Use the master branch for testing new features
https://quay.io/repository/coreos/prometheus-operator?tab=tags

**What did you expect to see?**
master tag of docker image is up to day.

**What did you see instead? Under which circumstances?**
master tag of docker image is outdated.

**Comment by mxinden** [comment]
This is a fair request. I will make sure this is automated for the future. Thanks for the notice.

**Comment by brancz** [comment]
The `master` tag is now automatically updated on successful CI runs from master. Closing here.
