### ISSUE TITLE
Use ownerReferences 

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#12]
We should set `ownerReferences` in the ObjectMeta of controller-created objects.
This will also be necessary to not delete user-created ConfigMaps for rules and configuration on teardown.

**Comment by brancz** [comment]
Sounds good!

**Comment by brancz** [comment]
This will add additional complexity when migrating from one `apiVersion` to another, but luckily we don't have to solve that problem just yet, but we need to keep it in the back of our heads.

The general problem: when migrating an object from one `apiVersion` to another, we will have to make sure that the garbage collector doesn't accidentally delete the temporarily orphaned object, until we rewrite the `ownerReference` to match the new object of the new `apiVersion`. From the design docs I understand that [`Finalizers`](https://github.com/kubernetes/kubernetes/blob/05d067d6bb626c622f0ceb5b16687c288d0d6c39/docs/proposals/garbage-collection.md#new-components) should be the way to go for this.

**Comment by brancz** [comment]
Also this one is a limitation, but I think it's one we can live with:

> OwnerReference struct: OwnerReference contains enough information to let you identify an owning object. Please refer to the inline comments for the meaning of each field. Currently, an owning object must be in the same namespace as the dependent object, so there is no namespace field.

As we don't have a governing service per Stateful-/PetSet there is no 1-to-1 relationship of them anyways.

**Comment by brancz** [comment]
Garbage collection for CRDs [has recently been merged](https://github.com/kubernetes/kubernetes/pull/47665) and from my understanding will be supported starting 1.8. Once 1.8 alphas/betas are out we can implement this and test whether it actually works correctly on our side.
