### ISSUE TITLE
Tag v0.18.1 not found in repository quay.io/coreos/prometheus-operator

### ISSUE THREAD

**Issue by wesselOC** [coreos/prometheus-operator#1210]
**What did you do?**
Followed the following guide:

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md

```
git clone -b master https://github.com/coreos/prometheus-operator.git prometheus-operator-temp;
cd prometheus-operator-temp/contrib/kube-prometheus
./hack/cluster-monitoring/self-hosted-deploy
cd -
rm -rf prometheus-operator-temp
```

**What did you expect to see?**

Running prometheus operator able to fetch the code

**What did you see instead? Under which circumstances?**

Failed to pull image "quay.io/coreos/prometheus-operator:v0.18.1": rpc error: code = Unknown desc = Tag v0.18.1 not found in repository quay.io/coreos/prometheus-operator
Error syncing pod

**Environment**

KOPS 1.7 on AWS

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	Kops

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Failed to pull image "quay.io/coreos/prometheus-operator:v0.18.1": rpc error: code = Unknown desc = Tag v0.18.1 not found in repository quay.io/coreos/prometheus-operator
Error syncing pod

```

**Comment by mxinden** [comment]
@wesselOC Thanks for reporting this. I am currently in the phase of automating the build of new images. I hope to be done with that tomorrow.

For now you would need to build the image yourself from the `release-0.18` branch. Sorry for the inconvenience.

**Comment by wesselOC** [comment]
Thanks for the feedback!. Will  try to build it myself!

**Comment by mxinden** [comment]
@wesselOC You can find the `v0.18.1` image on Quay now.

**Comment by wesselOC** [comment]
Thanks your a rockstar!
