### ISSUE TITLE
Helm: exporters x509 authentication

### ISSUE THREAD

**Issue by InTheCloudDan** [coreos/prometheus-operator#1211]
**What did you do?**

Bluemix does not allow bearerToken authentication against nodes, only x509 authentication. In the current Helm chart there is no way to specify for any or all exporters to use x509 authentication in place of bearerToken.

In my instance I manually updated that ServiceMonitor but am looking for a more maintainable way that still will work with the Helm chart. I haven't yet been able to come up with what I consider a clean implementation to update the kube-prometheus and exporter charts for this feature and was hoping someone in the community might have an idea of how to handle it.

I'd be happy to open a PR if someone had some insight on how best to achieve this.

**Environment**

* Kubernetes cluster kind: 

	bluemix

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
