### ISSUE TITLE
etcd dashboard blank when using kops

### ISSUE THREAD

**Issue by stonefury** [coreos/prometheus-operator#1212]
Could someone provide instructions or guidance on getting the etcd dashboard to work for a cluster brough up with kops?  I did not bring up an HA mode.

From what I can tell, etcd has port 2380 open, but not 2379. So I'm confused as to where the metrcs endpoint is when using kops to create the cluster.

**Comment by brancz** [comment]
The metrics endpoint of etcd is on the 2379 port (and optionally an additional one that you can specify starting with etcd v3.3). You may need to open firewall rules if you are running Prometheus on a non master (I would recommend running it on a master node though).

If your etcd is not visible through the Kubernetes API, you will need to use something along the lines of this to monitor an external etcd: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md

I will close this as there is no issue with the Prometheus Operator here.
