### ISSUE TITLE
No data points for Pods dashboard after deploying kube-prometheus

### ISSUE THREAD

**Issue by Itfly** [coreos/prometheus-operator#1214]
**What did you do?**
I deployed the latest kube-prometheus (commit:aae5278218a4b1df1ffba51ab395a64723e33668) on my kubernete cluster. It's great to show lots of metrics on Grafana UI. However, there's no data points for Pods dashboard almostly except some of pods have memory points.

**What did you expect to see?**
Expect to have data points for Pods dashboard

**What did you see instead? Under which circumstances?**
There's data on the Heapster's Grafana.

**Environment**
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
I use kubeadm to create k8s cluster:
https://kubernetes.io/docs/setup/independent/high-availability/

* Manifests:
Just run the `hack/cluster-monitoring/deploy` command

* Prometheus Operator Logs:

No error log

**Comment by brancz** [comment]
Are you successfully scraping all targets? kubelets/cadvisor?

**Comment by Itfly** [comment]
@brancz Checking the targets, the kubelet's status is down with Error:
```
server returned HTTP status 403 Forbidden
```

**Comment by Itfly** [comment]
After running the following commands on all the masters and nodes , all kubelet targets are up and data points are shown on Grafana:
```
KUBEADM_SYSTEMD_CONF=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
sed -e "/cadvisor-port=0/d" -i "$KUBEADM_SYSTEMD_CONF"
if ! grep -q "authentication-token-webhook=true" "$KUBEADM_SYSTEMD_CONF"; then
  sed -e "s/--authorization-mode=Webhook/--authentication-token-webhook=true --authorization-mode=Webhook/" -i "$KUBEADM_SYSTEMD_CONF"
fi
// for masters only
sed -e "s/- --address=127.0.0.1/- --address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-controller-manager.yaml
// for masters only
sed -e "s/- --address=127.0.0.1/- --address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-scheduler.yaml
systemctl daemon-reload
systemctl restart kubelet
```

Also  modify the configMap kubeadm-config with command `kubectl -n kube-system edit cm kubeadm-config
` by adding:
```
    controllerManagerExtraArgs:
      address: 0.0.0.0
    schedulerExtraArgs:
      address: 0.0.0.0
```
