### ISSUE TITLE
enable-admin-api is not possible

### ISSUE THREAD

**Issue by dmitrievav** [coreos/prometheus-operator#1215]
**What did you do?**

I tried to delete some stale data from Prometheus like
`curl -XPOST https://prometheus.internal.loveos.io/api/v1/admin/tsdb/clean_tombstones`
but for that I have to enable admin-api first, which is not possible at the moment

**What did you expect to see?**

some positive http response

**What did you see instead? Under which circumstances?**

`{"status":"error","errorType":"unavailable","error":"Admin APIs disabled"}`

**Environment**

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

	kops

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
We should figure out what to do here, and maybe even clean tombstones automatically with the sidecar. @fabxc what is your take on this?

**Comment by dmitrievav** [comment]
People may want to be able cleaning up some data manually, as described here https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series

Could you just introduce optional parameter for enabling "TSDB Admin APIs"?  If it is not enabled by default it should not be security concern, right? I could make and test a patch. 

`pkg/prometheus/statefulset.go
@@ -385,6 +385,10 @@ func makeStatefulSetSpec(p monitoringv1.Prometheus, c *Config, ruleConfigMaps []
                promArgs = append(promArgs, "-web.external-url="+p.Spec.ExternalURL)
        }

+       if p.Spec.EnableAdminApi == "true" {
+               promArgs = append(promArgs, "-web.enable-admin-api")
+       }
+
        webRoutePrefix := "/"
        if p.Spec.RoutePrefix != "" {
                webRoutePrefix = p.Spec.RoutePrefix`

**Comment by brancz** [comment]
Ideally I'd like to have things like cleaning tombstones directly worked into the Prometheus Operator, so people don't have to think about those operational aspects themselves, for that however these APIs would always need to be enabled.

**Comment by dmitrievav** [comment]
For that we could simply add a cronjob to Prometheus Operator manifests.

**Comment by brancz** [comment]
Something like that would most likely need to be implemented into the sidecar.

**Comment by dmitrievav** [comment]
Is not it better then sidecar ?

```
contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-cronjobs.yaml
@@ -0,0 +1,17 @@
+apiVersion: batch/v1beta1
+kind: CronJob
+metadata:
+  name: prometheus-k8s
+  namespace: monitoring
+spec:
+  schedule: "0 0 * * *"
+  jobTemplate:
+    spec:
+      template:
+        spec:
+          containers:
+          - name: prometheus-k8s-cronjob
+            image: busybox
+            args:
+            - "curl -XPOST http://prometheus-k8s:9090/api/v1/admin/tsdb/clean_tombstones"
+          restartPolicy: OnFailure
```

**Comment by dmitrievav** [comment]
To be on the same page, do you mean "prometheus-config-reloader" as a side car?

**Comment by brancz** [comment]
Yes. The name is at this point slightly misleading, but that would be a good place to have things like that.

**Comment by brancz** [comment]
@wleese that makes sense. The problem I want to avoid is enabling users to create public Prometheus servers with unauthenticated/unauthorized admin APIs.

**Comment by mobilesfinks** [comment]
@brancz I'm sure this is a problem for users of the api on the public Prometheus server. On your part, there is a default value that turns off the API. Is not it?

I now needed to delete several metrics. Unfortunately, this is not possible at the moment. I would like to still be able to configure Prometheus as the developers intended, and not to rest on your vision of the configuration situation. The operator is not a firewall. Everyone should think for themselves what and when he includes those or other options.

**Comment by brancz** [comment]
We can add it as an experimental field, what we’re trying to do here is make a user to the right thing, not necessarily restrict it in total.

We’re all part of the upstream team and even implemented those APIs, we are well aware of their existance and dangers.

**Comment by mobilesfinks** [comment]
Well, I understand. I agree that many can simply copy the configs without thinking about their essence. What about checking for the basic authentication annotations for ingress? Or as on my ingress, the presence of annotations `nginx.ingress.kubernetes.io/auth-satisfy: any`,
  `nginx.ingress.kubernetes.io/whitelist-source-range: ....`. 
This will minimize the likelihood of launching an API on a publicly accessible server

**Comment by brancz** [comment]
There are too many possibilities how people could protect their Prometheus server, we should just add the field and put a warning in the documentation, that it should always be protected.

**Comment by squat** [comment]
@mmerrill3 this work is not currently underway. Contributions are always welcome :)

**Comment by zanhsieh** [comment]
I got the similar case here. My dev and uat k8s cluster nodes mainly built via AWS spot fleet. They come and go everyday, which create lots of kubelet endpoints which could be safely removed since those internal ip addresses will never come back. 

If this feature has no plan to implement, at least please provide some document on how we could sort of hack into TSDB to clean up metrics we no longer need. Secure TSDB access should be easier than code change.

**Comment by brancz** [comment]
I don't believe this ended up being implemented, but as the conversation went, we're open for contributions regarding this, under the condition that it is marked with its dangers :slightly_smiling_face: .

**Comment by audip** [comment]
As it yet to be implemented, I'll put up a PR adding the flag and warning users about potential impact.

**Comment by Hashfyre** [comment]
Even though [v.0.28.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.28.0)
says this is included as per changelog.

having:
```
{
    "dependencies": [
        {
            "name": "kube-prometheus",
            "source": {
                "git": {
                    "remote": "https://github.com/coreos/prometheus-operator",
                    "subdir": "contrib/kube-prometheus/jsonnet/kube-prometheus"
                }
            },
            "version": "v0.28.0"
        }
    ]
}
```
and doing `jb install`

Doesn't show this change on `addons/kube-prometheus/vendor/kube-prometheus/prometheus/prometheus.libsonnet`

which looks as below:
```
        spec: {
          replicas: $._config.prometheus.replicas,
          version: $._config.versions.prometheus,
          baseImage: $._config.imageRepos.prometheus,
          serviceAccountName: 'prometheus-' + $._config.prometheus.name,
          serviceMonitorSelector: {},
          serviceMonitorNamespaceSelector: {},
          nodeSelector: { 'beta.kubernetes.io/os': 'linux' },
          ruleSelector: selector.withMatchLabels({
            role: 'alert-rules',
            prometheus: $._config.prometheus.name,
          }),
         ...
```
