### ISSUE TITLE
v1beta2.Stateful set does not exist for my deployment

### ISSUE THREAD

**Issue by stonefury** [coreos/prometheus-operator#1216]
Using Rancher 1.6 and looks like kubernetes 1.7

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.7-rancher1", GitCommit:"a1ea37c6f6d21f315a07631b17b9537881e1986a", GitTreeState:"clean", BuildDate:"2017-10-02T21:33:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

The only problem I really have at this point is the operator is trying to launch the prometheus-k8 StateFul set, using v1beta2.StatefulSet, but on our system it is v1beta1.StatefulSet.

Will I need to build the project? Any guidance on the change required? 

Thanks!

**Comment by brancz** [comment]
In the latest minor release we dropped support for Kubernetes 1.7, see the [release notes](https://github.com/coreos/prometheus-operator/releases/tag/v0.18.0).

All versions before that should be compatible, but I of course recommend also upgrading your Kubernetes cluster :slightly_smiling_face: .

Sorry for the inconvenience, but we won't be able to change that going forward. I'm going to close this, but feel free to keep asking questions, should you have any :slightly_smiling_face: .
