### ISSUE TITLE
Kubernetes 1.10+ supports RunAsGroup / RunAsNonRootGroup

### ISSUE THREAD

**Issue by Quentin-M** [coreos/prometheus-operator#1217]
Kubernetes 1.10 now supports RunAsGroup / RunAsNonRootGroup, behind a feature flag. The Prometheus Operator should consider adding support for it once those flags go GA.

See https://github.com/kubernetes/kubernetes/pull/52077

**Comment by brancz** [comment]
As it’s already part of the struct but kept behind a feature flag, we can implement this as soon as we update to the Kubernetes 1.10 client go version.

**Comment by krmayankk** [comment]
RunAsGroup graduated to beta in 1.14 and now is enabled by default

**Comment by brancz** [comment]
This should be available in the security context struct already no?

**Comment by krmayankk** [comment]
that is correct @brancz

**Comment by brancz** [comment]
In that case closing here, feel free to comment or open a new issue should this not work as expected.
