### ISSUE TITLE
kube-prometheus node-exporter does not have standard master tolerations

### ISSUE THREAD

**Issue by sudermanjr** [coreos/prometheus-operator#1241]
**What did you do?**
Installed prometheus operator using the kube-prometheus manifests

**What did you expect to see?**
Node-exporter running on all nodes (including masters)

**What did you see instead? Under which circumstances?**
Node exporter does not have toleration for node-role.kubernetes.io/master

**Environment**
OSX

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kops

* Manifests:

```
prometheus-operator/contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml```

I have forked this repo and will open a PR, but wanted an issue to go with it in case I missed something.

**Comment by brancz** [comment]
This has since been merged into master :tada: . Closing here.
