### ISSUE TITLE
ServiceMonitor can select itself

### ISSUE THREAD

**Issue by adamdecaf** [coreos/prometheus-operator#1256]
**What did you do?**

I'm setting up federation using a ServiceMonitor (mentioned previously in https://github.com/coreos/prometheus-operator/issues/647), which works, but a prometheus instance can select itself. 

I have two prometheus instances (and `kind: Prometheus` objects) in the same namespace. I'm setting up the "infra prometheus" to federate (read from) a `marathon-prometheus` instance. The `ServiceMonitor` for that looks like the following. 

<details>
<summary>marathon-prometheus ServiceMonitor</summary>

```
{
    "apiVersion": "monitoring.coreos.com/v1",
    "kind": "ServiceMonitor",
    "metadata": {
        "labels": {
            "team": "infrastructure"
        },
        "name": "marathon-prometheus",
        "namespace": "infrastructure"
    },
    "spec": {
        "endpoints": [
            {
                "honorLabels": true,
                "interval": "30s",
                "params": {
                    "match[]": [
                        "{__name__=~\".+\"}"
                    ]
                },
                "path": "/federate",
                "port": "web"
            }
        ],
        "namespaceSelector": {
            "matchNames": [
                "infrastructure"
            ]
        },
        "selector": {
            "app": "marathon-prometheus",
            "prometheus": "marathon-prometheus"
        }
    }
}
```

</details>

**What did you expect to see?**

I expected to be able to select only the `marathon-prometheus` Prometheus. 

**Environment**

* Kubernetes version information:

```
$ kubectl --context <omitted>-context version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9+coreos.1", GitCommit:"cd373fe93e046b0a0bc7e4045af1bf4171cea395", GitTreeState:"clean", BuildDate:"2018-03-13T21:28:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	tectonic-installer

**Comment by adamdecaf** [comment]
This looks to be a problem in that every `kind: Prometheus` object's `StatefulSet` is [created with a label `app=prometheus`](https://github.com/coreos/prometheus-operator/blob/release-0.16/pkg/prometheus/statefulset.go#L520). Then the label selector perform [set-based matching](https://github.com/coreos/prometheus-operator/blob/release-0.16/pkg/prometheus/operator.go#L748-L755), which matches _any_ of the labels provided in the List operator. ([k8s Docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors))

**Comment by adamdecaf** [comment]
I should note, this is also annoying because I've changed the "infra prometheus" `externalUrl` such that calling `x.x.x.x:9090/federate` on it gives a non-200 http status code. (There are extra path segments.)

**Comment by brancz** [comment]
Can you share the `Service` that this `ServiceMonitor` selects? Within that service you can specify any mapping you want regarding ports and also have a more specific label selector than just selecting the `app: prometheus` label.

> I should note, this is also annoying because I've changed the "infra prometheus" externalUrl such that calling x.x.x.x:9090/federate on it gives a non-200 http status code. (There are extra path segments.)

This is a common frustration with Prometheus. From your comment I couldn't figure out whether you managed to solve this. A common thing we do is only have the externalUrl configured but make the Prometheus server still bind its http handlers to root.

**Comment by adamdecaf** [comment]
I figured this out. I didn't realize the `targetPort` on the Service was wrong. Here's the working Service.

```json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "labels": {
            "app": "marathon-prometheus",
            "prometheus": "marathon-prometheus",
            "team": "infrastructure"
        },
        "name": "marathon-prometheus",
        "namespace": "infrastructure"
    },
    "spec": {
        "ports": [
            {
                "name": "federate",
                "port": 9090,
                "protocol": "TCP",
                "targetPort": 9090
            }
        ],
        "selector": {
            "prometheus": "marathon-prometheus"
        }
    }
}
```

**Comment by brancz** [comment]
Nice, so you're all good? :slightly_smiling_face:

**Comment by adamdecaf** [comment]
@brancz I think so. Thanks

**Comment by brancz** [comment]
Let us know if there is anything else! :slightly_smiling_face:
