### ISSUE TITLE
kube-prometheus rule HighNumberOfFailedHTTPRequests is missing the instance label

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1259]
Can someone please tell me whether you agree that the following change should be made to [etcd3.rules.yaml](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/assets/prometheus/rules/etcd3.rules.yaml)?:
```
~/prometheus-operator
$ git diff ./contrib/kube-prometheus/assets/prometheus/rules/etcd3.rules.yaml
   - alert: HighNumberOfFailedHTTPRequests
-    expr: sum(rate(etcd_http_failed_total{job="etcd"}[5m])) BY (method) / sum(rate(etcd_http_received_total{job="etcd"}[5m]))
-      BY (method) > 0.01
+    expr: sum(rate(etcd_http_failed_total{job="etcd"}[5m])) BY (method,instance) / sum(rate(etcd_http_received_total{job="etcd"}[5m]))
+      BY (method,instance) > 0.01
     for: 10m
     labels:
       severity: warning
     annotations:
       description: '{{ $value }}% of requests for {{ $labels.method }} failed on etcd
         instance {{ $labels.instance }}'
       summary: a high number of HTTP requests are failing
   - alert: HighNumberOfFailedHTTPRequests
-    expr: sum(rate(etcd_http_failed_total{job="etcd"}[5m])) BY (method) / sum(rate(etcd_http_received_total{job="etcd"}[5m]))
-      BY (method) > 0.05
+    expr: sum(rate(etcd_http_failed_total{job="etcd"}[5m])) BY (method,instance) / sum(rate(etcd_http_received_total{job="etcd"}[5m]))
+      BY (method,instance) > 0.05
     for: 5m
     labels:
       severity: critical
```

When I do this query as-is...:
![current](https://user-images.githubusercontent.com/15840507/39278263-d6036810-48b7-11e8-9992-182e3f00abf0.png)

...versus my proposed change:
![proposed](https://user-images.githubusercontent.com/15840507/39278267-de3ddb28-48b7-11e8-8e43-86481c39e8c1.png)

With the query as-is, the "instance" is missing (I've made a red circle where it should be):
![am](https://user-images.githubusercontent.com/15840507/39278314-1215a2b4-48b8-11e8-9ced-a1154ef21ce0.png)

I'd be happy to do a PR to make this change myself - it's just I'm kinda a newbie at alertmanager templating (and prom queries), so I first wanna make sure I'm not misunderstanding. Thanks.

**Comment by brancz** [comment]
this sounds good, can I recommend to make these changes on the upstream etcd repository first (it has this set of alerts in it's repository)?

**Comment by jolson490** [comment]
Note that this `` rule is defined in the following files in [etcd](https://github.com/coreos/etcd):
```
$ find . -type f | xargs grep -l HighNumberOfFailedHTTPRequests
./Documentation/etcd-mixin/mixin.libsonnet
./Documentation/op-guide/etcd3_alert.rules
./Documentation/v2/etcd_alert.rules
./Documentation/v2/etcd_alert.rules.yml
```

**Comment by jolson490** [comment]
You're right Frederic.
More info: The etcd related prom alerts a few months ago had "Etcd" added to the beginning of their names. And then `EtcdHighNumberOfFailedHTTPRequests` was [deleted](https://github.com/etcd-io/etcd/pull/9706#issuecomment-405725480).
Thus I'm closing this issue (because there's nothing to fix anymore).
