### ISSUE TITLE
Broken link in documentation - KOPSonAWS.md

### ISSUE THREAD

**Issue by matthewflannery** [coreos/prometheus-operator#1281]
**What did you do?**

Try to follow the instructions in 

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md

**What did you expect to see?**

Documentation without references to files that do not exist

**What did you see instead? Under which circumstances?**

A reference to an invalid file `./hack/cluster-monitoring/self-hosted-deploy`: 

The directory it refers to does not contain "self-hosted-deploy" 

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/hack/cluster-monitoring

**Comment by brancz** [comment]
We have updated usage with kops: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#customization

As there is really no difference to the other methods we removed the extra docs page and included it in the customization section.

I'll close this here, but do let us know and re-open or create a new issue if you feel it's not quite right :slightly_smiling_face: .
