### ISSUE TITLE
Helm: Selector for Prometheus Service does not match, Service gets no Endpoints

### ISSUE THREAD

**Issue by allsuper** [coreos/prometheus-operator#1282]
Hello, 

I did a plain Helm install of Prometheus Operator  with: 

```
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring
```
Using: `https://s3-eu-west-1.amazonaws.com/coreos-charts/stable`, which resulted in Chart installs of `kube-prometheus-0.0.59 / prometheus-operator-0.0.20`...

However the installed Service for Prometheus does not get assigened any Endpoints due to the fact, that the selectors do not match. 

```
kubectl describe services  kube-prometheus-prometheus -n monitoring
Selector:          app=prometheus,prometheus=kube-prometheus
...
```

But the pods do have this kind of Label: 
```
kubectl describe pod prometheus-kube-prometheus-prometheus-0 -n monitoring
...
Labels:         app=prometheus
                ..
                prometheus=kube-prometheus-prometheus
                ....
...
```

which, as stated and can be seen above, do not match (kube-prometheus-promethus vs kube-prometheus) so the service is not working, seems like a bug...

Thanks very much 
tommy

**Comment by allsuper** [comment]
I am sorry, there seems to be a second Service `prometheus-operated` that in deed functions and allows to forward the ports with: 
```
kubectl port-forward -n monitoring service/prometheus-operated 9090
```
So this seems to be a documentation issue: At least it's now documented here. I will close the ticket. Thanks tommy

**Comment by brancz** [comment]
Note that the `prometheus-operated` service is a single headless service for *all* prometheus servers in that namespace, so load balancing it is not a good idea as you may end up on totally differently configured prometheus servers. This service is an implementation detail of the Prometheus Operator.
