### ISSUE TITLE
k8s 1.10 with CustomResourceSubresources=true prevents operator from creating CRDs

### ISSUE THREAD

**Issue by dprotaso** [coreos/prometheus-operator#1293]
**What did you do?**

Use prometheus-operator on a kubernetes 1.10 cluster with the feature gate CustomResourceSubresources set to true

Use the bundle yaml from the root of the repo: https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml

**What did you expect to see?**

Operator/Controller is able to create CRDs

**What did you see instead? Under which circumstances?**

The operator fails to create CRDs - see logs below
https://gist.github.com/bsnchan/1f721c6e9f7aa989cb0c070ed305bd02

**Comment by brancz** [comment]
Thanks for reporting this! This is definitely a bug we need to fix! (cc @mxinden)

**Comment by williamsandrew** [comment]
Just ran into this. Is there any workarounds at the moment?

**Comment by brancz** [comment]
I'm not aware, but we should work on this, we're currently quite busy but I'm hoping we can get this fixed for the next release.

**Comment by sslavic** [comment]
It seems https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/validation/validation.go#L303 doesn't allow `description` field that `Alertmanager` and other Prometheus Operator CRDs use in `openAPIV3Schema` https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/alertmanager.crd.yaml#L15

Quick fix could be just to remove the problematic field from CRDs.

**Comment by sslavic** [comment]
Improvement for k8s 1.11 which allows `description` has been provided by @nikhita (see https://github.com/kubernetes/kubernetes/pull/64766).

**Comment by brancz** [comment]
Thanks for investigating @sslavic, I do wonder why the CRD fails to be created by the operator then though, as it shouldn't be rendered in the first place if the code doesn't have the appropriate proto/json tags.

**Comment by nikhita** [comment]
> I do wonder why the CRD fails to be created by the operator then though, as it shouldn't be rendered in the first place if the code doesn't have the appropriate proto/json tags.

I think the code has the appropriate proto/json tags. In Kubernetes, if the subresource feature is enabled, we validate that some properties should not be present at the root schema.

It is rendered, but fails validation.

**Comment by brancz** [comment]
Thanks for the quick answer and explanation @nikhita!

In that case it sounds we should skip, or at least enable to skip setting the description in the first place: https://github.com/ant31/crd-validation/blob/master/pkg/convert_types.go#L95

**Comment by nikhita** [comment]
> In that case it sounds we should skip, or at least enable to skip setting the description in the first place: https://github.com/ant31/crd-validation/blob/master/pkg/convert_types.go#L95

I understand the idea here :+1: but that would also disallow you to add descriptions in the subschemas (the non-root ones). :(

**Comment by brancz** [comment]
I see, well if it's just the root one, can we just set that one to be blank?

**Comment by nikhita** [comment]
> I see, well if it's just the root one, can we just set that one to be blank?

That should do it. I'll send a PR :)

**Comment by hobti01** [comment]
Is there any progress on this issue?
I hope @nikhita had a good holiday but also hope there is time to fix this blocking issue :)

**Comment by brancz** [comment]
@hobti01 have you tried this recently. To my knowledge this works now.

**Comment by hobti01** [comment]
I tried this yesterday, was there a change in the last 19 hours? ;)

**Comment by hobti01** [comment]
Hopefully this is not one of those "fixed in prometheus-operator but not updated in the helm chart" issues?

**Comment by hobti01** [comment]
Thanks for the hint @brancz , I can confirm that this works with updated prometheus-operator and prometheus-config-reloader images.

**Comment by brancz** [comment]
In that case I’m closing this here, but please continue to comment should there be more problems related to this, or open a new issue. Thanks a lot for testing!
