### ISSUE TITLE
Bad query on kube-prometheus Etcd "Memory" panel

### ISSUE THREAD

**Issue by bgagnon** [coreos/prometheus-operator#1295]
The _Memory_ panel for the Etcd dashboard is build on this:

```json
{
  "expr": "process_resident_memory_bytes",
  "format": "time_series",
  "intervalFactor": 2,
  "legendFormat": "{{instance}} Resident Memory",
  "metric": "process_resident_memory_bytes",
  "refId": "A",
  "step": 4
}
```
I think this grabs the `process_resident_memory_bytes` from _every_ process in the cluster, not just Etcd.

**Comment by brancz** [comment]
You're right! This should have a job selector, could you fix this in the upstream etcd repo? That's where this dashboard is defined (it was just copied in here for the lack of better tooling, which we're also fixing :) ).

**Comment by bgagnon** [comment]
A similar fix to etcd already exists at https://github.com/coreos/etcd/commit/808450129b3d002924a565737e8163316d983421

It looks like this repo's copy of the JSON dashboard is outdated.

**Comment by brancz** [comment]
Yes we've actually been working on [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler) to make vendoring a simple one off command to update all dashboards + alerts across all components. We've already started this for [etcd alerts](https://github.com/coreos/etcd/pull/9640), the dashboard should be next.
