### ISSUE TITLE
[ kube-prometheus ] How to expose grafana without port-forward

### ISSUE THREAD

**Issue by zepouet** [coreos/prometheus-operator#1301]
Hello,

I tested your solutions and it is right but I would like not to use this command `kubectl port-forward prometheus-frontend-0 9090`

Is it possible in our case ?

Thanks a lot !
Best regards,

**Comment by brancz** [comment]
We have just merged a revised version of kube-prometheus, please have a look at the [customizing section](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#customization).

**Comment by brancz** [comment]
We have just added new docs on how to expose Prometheus/Alertmanager/Grafana via Ingress: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md

I'll close this here, but if you feel the documentation is not clear or good enough feel free to re-open this issue or open a new one! :slightly_smiling_face:
