### ISSUE TITLE
Default cluster-role-binding is not necessary to run one simple prometheus operator example

### ISSUE THREAD

**Issue by ArvinDevel** [coreos/prometheus-operator#1304]
**What did you do?**
I try Prometheus-Operator on my 3-nodes kuberneters cluster followed by [tutorial](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html), but with self-defined namespace `monitor`.

**What did you expect to see?**
No error output, 3 targets shown on prometheus UI

**What did you see instead? Under which circumstances?**
no targets shown on prometheus UI

**Environment**
Ubuntu 16.04.3 & CentOS Linux 7

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

manifests in [tutorial](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html), but the two `namespace` field is changed from `default` to `monitor`. 

* Prometheus Operator Logs:
log of `kubectl logs  prometheus-prometheus-0 prometheus` is below:
```
level=error ts=2018-05-06T07:45:37.719462058Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitor:default\" cannot list services in the namespace \"monitor\""
level=error ts=2018-05-06T07:45:37.719467284Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitor:default\" cannot list endpoints in the namespace \"monitor\""
level=error ts=2018-05-06T07:45:38.7218579Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitor:default\" cannot list pods in the namespace \"monitor\""
```
* my solution

After investigate the logs, I add one cluster-role-binding to link `prometheus` cluster-role and `default` service-account of `monitor` namespace using
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitor
```
And it worked, but I'm confused with the cause reason, so call for your help, thanks.

**Comment by mxinden** [comment]
Hi @ArvinDevel,

I am not entirely sure I understand your question. Please ensure, that when you adjust the namespace in one manifest to do the same in all the other ones as well.

**Comment by ArvinDevel** [comment]
Yes, I did change all the namespace in other ones as well and I apply these manifest under my custom `monitor` namespace context. I don't why should we grand privilege to `system:serviceaccount:monitor:default` user?

**Comment by ArvinDevel** [comment]
thanks all of you.

**Comment by ArvinDevel** [comment]
Recently, I found the reason is that the `serviceaccount` is not specified, so the default serviceAccount being used is `default`. 
And this is fixed in [this pr](https://github.com/coreos/prometheus-operator/commit/c20139acce2cb599df26bb5a7885d5727d2bf94f#diff-074af51441a7c1a326433675382011ee), but the official doc is still not updated.

**Comment by brancz** [comment]
@ArvinDevel thanks a lot for the feedback, highly appreciated! Could you make a suggestion on what you would expect to find in the docs, and what you are finding? We would love to improve the docs, or if you want to we would be even happier about a PR! :slightly_smiling_face:

**Comment by ArvinDevel** [comment]
I'm not sure why the doc is not updated, maybe the pr is restricted to specific version(currently this snapshot version), and the official doc points to somewhere that I don't know.
The spec of `prometheus` should specify `serviceAccountName: prometheus` explicitly, just as [the pr](https://github.com/coreos/prometheus-operator/commit/c20139acce2cb599df26bb5a7885d5727d2bf94f#diff-074af51441a7c1a326433675382011ee) that you fixed, but [the official doc](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html) has not reflect your change, see the picture for more concrete info.
![spec-description](https://user-images.githubusercontent.com/16100052/41289698-37fcbe46-6e7d-11e8-8bdc-24429d135721.png)
