### ISSUE TITLE
Duplicate kube-state pods when using Tolerations

### ISSUE THREAD

**Issue by vielktus** [coreos/prometheus-operator#1306]
**What did you do?**
I set the values of Tolerations in `helm/exporter-kube-state/values.yaml` like this:
And `helm install -n kube-prometheus`
```
tolerations:
 - key: "key"
    operator: "Equal"
    value: "MONITOR"
    effect: "NoSchedule"
```
After that, found out in `helm/exporter-kube-state/templates/deployment.yaml`, the variables were wrongly named:
```
{{- if .Values.kube_state_metrics.tolerations }}
      tolerations:
    {{ toYaml .Values.kube_state_metrics.tolerations | indent 4 }}
    {{- end }}
```
I changed this line to below (not sure if we need to fix this? Because the Toleration field is out side of "kube_state_metrics"):
```
{{- if .Values.tolerations }}
      tolerations:
    {{ toYaml .Values.tolerations | indent 4 }}
    {{- end }}
```

**What did you expect to see?**
One pod of kube-state would be created
```
kube-prometheus-exporter-kube-state-5f855f4d8b-84r2s   2/2       Running
```

**What did you see instead? Under which circumstances?**
Two pods of kube-state were created
```
$ kubectl get pods
kube-prometheus-exporter-kube-state-5f855f4d8b-84r2s   2/2       Running   0          2d
kube-prometheus-exporter-kube-state-85689ccf67-k6w5m   0/2       Pending   0          2d
```
It seems Prometheus Operator was creating these pods.
Other Tolerations are working fine, except this kube-state. Please ask me if you need more informations

**Comment by gianrubio** [comment]
Could you past the output of `kubectl describe pod kube-prometheus-exporter-kube-state-85689ccf67-k6w5m` ?

**Comment by vielktus** [comment]
By the way, even though there's pod kube-state running, Prometheus still can not discover kube-state.

**Comment by gianrubio** [comment]
> After that, found out in helm/exporter-kube-state/templates/deployment.yaml, the variables were wrongly named:

They are right, if you want to change tolerations for kube-state you could set it in kube-prometheus/values.yaml  something like this:

```
exporter-kube-state:
  tolerations: ....
```

You should investigate why the pod is not schedule to a node, it's out of the scope of the project to explain how to manage tolerations.

Try to search about this warnings, also check the output of the events

``` vents:
  Type     Reason             Age                  From                Message
  ----     ------             ----                 ----                -------
  Warning  FailedScheduling   1m (x18798 over 3d)  default-scheduler   0/17 nodes are available: 17 PodToleratesNodeTaints.
  Normal   NotTriggerScaleUp  1m (x14808 over 3d)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

**Comment by vielktus** [comment]
"You should investigate why the pod is not schedule to a node, it's out of the scope of the project to explain how to manage tolerations."
Actually, the pod was scheduled Gianrubio. As I mentioned above, we have 2 pods (1 is running and the other is pending <- which should not be created, this issue).

For the variables in "deployment.yaml", the current variable is
```
{{- if .Values.kube_state_metrics.tolerations }}
      tolerations:
    {{ toYaml .Values.kube_state_metrics.tolerations | indent 4 }}
    {{- end }}
```
but the "Tolerations" is not under "kube_state_metrics" field in "values.yaml". So it cannot be "Values.kube_state_metrics.tolerations", it should be "Values.tolerations". Thats what I meant.

**Comment by vielktus** [comment]
"You should investigate why the pod is not schedule to a node, it's out of the scope of the project to explain how to manage tolerations."
Actually, the pod was scheduled Gianrubio. As I mentioned above, we have 2 pods (1 is running and the other is pending <- which should not be created, this issue).

**Comment by vielktus** [comment]
> Did you installed the chart and upgrade it to use tolerations ?
Yes I did. I will have a check again.

for this https://github.com/coreos/prometheus-operator/issues/1306#issuecomment-387434365, I will make a PR to get you more details.

**Comment by vielktus** [comment]
ok @gianrubio. I pushed a PR, please help me to review.
