### ISSUE TITLE
Memory calculation in the default grafana graph

### ISSUE THREAD

**Issue by alok87** [coreos/prometheus-operator#1310]
**Memory used percentage calculation needs a fix**
The default calculation for memory usage in grafana is https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/assets/grafana/nodes.dashboard.py#L157-L161
`100 * (node_memory_MemTotal - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal`

Most of the other monitoring tools like newrelic, cloudwatch, etc.. rely on the `/proc/meminfo` MemAvailable to calculate the memory usage percentage. 
```
$ cat /proc/meminfo
MemTotal:       16435624 kB
MemFree:          522892 kB
MemAvailable:    4765140 kB
Buffers:          785552 kB
```
They use the formula `100 * (node_memory_MemTotal - node_memory_MemFree) / node_memory_MemTotal` 

The above two formulas results in two different data. And the one using `/proc/meminfo`'s `MemAvailable` seems the most right way to calculate it.

I will add the fix for it, if the discussion here ends up changing it. Else will close this issue. 
@brancz 

More Info - https://kubernetes.slack.com/archives/C20HH14P7/p1525717170000406

**Comment by alok87** [comment]
Quoting Memavailable feature - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773

```Many load balancing and workload placing programs check /proc/meminfo to
estimate how much free memory is available.  They generally do this by
adding up "free" and "cached", which was fine ten years ago, but is
pretty much guaranteed to be wrong today.

It is wrong because Cached includes memory that is not freeable as page
cache, for example shared memory segments, tmpfs, and ramfs, and it does
not include reclaimable slab memory, which can take up a large fraction
of system memory on mostly idle systems with lots of files.

Currently, the amount of memory that is available for a new workload,
without pushing the system into swap, can be estimated from MemFree,
Active(file), Inactive(file), and SReclaimable, as well as the "low"
watermarks from /proc/zoneinfo.

However, this may change in the future, and user space really should not
be expected to know kernel internals to come up with an estimate for the
amount of free memory.

It is more convenient to provide such an estimate in /proc/meminfo.  If
things change in the future, we only have to change it in one place.
```

**Comment by leo1515416043** [comment]
@alok87 node_memory in grafana still not correct, as you said.

**Comment by brancz** [comment]
So you're saying it should be `100 * (node_memory_MemTotal - node_memory_MemAvailable) / node_memory_MemTotal` ? I'd be ok with that change.

**Comment by leo1515416043** [comment]
IMO, yes.  @alok87

**Comment by brancz** [comment]
(note that that change would need to be in the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) as we're just using that as a dependency and the dashboards are actually defined there)

**Comment by sichvoge** [comment]
@alok87 is there a related issue on the kubernetes-mixin project to fix that?

**Comment by alok87** [comment]
@sichvoge Created an issue

**Comment by zebozhuang** [comment]
I calculate memory with the formula: 
`node_memory_MemTotal - (((node_memory_MemFree + node_memory_Cached+ node_memory_Buffers) unless node_memory_MemAvailable) or on(instance) (node_memory_MemAvailable))`
It works on both old and new kernel.
