### ISSUE TITLE
External IP for ingress is empty - unsure about correct steps

### ISSUE THREAD

**Issue by ablekh** [coreos/prometheus-operator#1317]
**What did you do?**

Installed `prometheus-operator`, `kube-prometheus` and Grafana Helm charts as follows:
```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring --set rbacEnable=false
helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring --set global.rbacEnable=false
helm install stable/grafana --name sbdh-jh-v3-k8s-grafana --namespace monitoring --set server.service.type=LoadBalancer,server.adminUser=USER,server.adminPassword=PASS,server.image=grafana/grafana:latest,server.persistentVolume.enabled=false

# Instead of the last command, I also tried ClusterIP (default)-based and simpler version:
helm install stable/grafana --name sbdh-jh-v3-k8s-grafana --namespace monitoring
```

**What did you expect to see?**

A real IP address in EXTERNAL-IP column for `sbdh-jh-v3-k8s-grafana` service. Having said that, I realize that one of the following are likely reasons for the issue: 1) incorrect or incomplete configuration of ingress for my Prometheus and/or Grafana deployments (not sure about the process - should I just create a config.yaml file with custom values /what?/ and update relevant deployment via `helm upgrade <deployment-name> --namespace=NAMESPACE -f config.yaml`); 2) needed to use Cluster-IP instead of Load Balancer type; 3) Other.

**What did you see instead? Under which circumstances?**

Also unclear on how to setup relevant subdomains, e.g., `{prometheus | grafana}.<FQDN of my K8s cluster>`, on both sides (K8s and what IP / FQDN to point relevant DNS records at my domain provider.

**Environment**

Azure AKS - managed K8s cluster (1.9.6)

**Kubernetes version information:**

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes cluster kind:**

AKS commands via Azure CLI 2.0

**Manifests:**

N/A

**Prometheus Operator Logs:**

N/A

**Comment by ablekh** [comment]
Hey, @yuvipanda, can you help? I'm a bit stuck and this issue doesn't seem to have any love from Prometheus community :-(.

**Comment by ablekh** [comment]
@yuvipanda Thanks for replying, no problem. BTW, what is the timeline for the official z2jh release v0.7?

**Comment by gianrubio** [comment]
@ablekh please paste the output of the `kubectl get service svc-name` and `kubectl describe svc-name`

**Comment by gianrubio** [comment]
The grafana were you installed is not supported by this project, you should open an issue in the [kubernetes/charts ](https://github.com/kubernetes/charts/) upstream.

**Comment by ablekh** [comment]
@gianrubio If this project supports different Grafana package, how could I install and use it (after removing the unsupported one)? Please clarify.

**Comment by gianrubio** [comment]
@ablekh when you install[ kube-prometheus it already install](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/requirements.yaml#L61) grafana for you. No need to manually install grafana just follow [this guide](https://github.com/coreos/prometheus-operator/tree/master/helm#tldr)

**Comment by ablekh** [comment]
@gianrubio Thank you. Will follow your advice. (Sorry about delay with my reply.)
