### ISSUE TITLE
https://<host>:10250/metrics Forbidden

### ISSUE THREAD

**Issue by IvanBiv** [coreos/prometheus-operator#1328]
I see in Prometheus UI:
[prometheus-operator/helm/]
```
kubelet (0/6 up) 
Endpoint State Labels Last Scrape Error
https://192.168.88.10:10250/metrics
DOWN endpoint="https-metrics" instance="192.168.88.10:10250" namespace="kube-system" service="kubelet" 7.784s ago server returned HTTP status 403 Forbidden
…
```

I use my K8s cluster.

```
kube@server2:/data/glusterfs/data/gluster_volume/helm/fluentd-elasticsearch$ kubectl get pods -n monitoring
NAME READY STATUS RESTARTS AGE
alertmanager-kube-prometheus-0 2/2 Running 0 1d
kube-prometheus-exporter-kube-state-556565655c-bjmfc 2/2 Running 0 1d
kube-prometheus-exporter-node-n4rs4 1/1 Running 0 1d
kube-prometheus-exporter-node-pk86w 1/1 Running 0 1d
kube-prometheus-exporter-node-zl7bk 1/1 Running 0 1d
kube-prometheus-grafana-b9bb6d4f-xrjcq 2/2 Running 0 1d
prometheus-kube-prometheus-prometheus-0 2/2 Running 1 1d
prometheus-operator-6d94d55b6d-hft8z 1/1 Running 0 1d
```

I think it about RBAC. How I can fix it?

**Comment by brancz** [comment]
This means your Prometheus server does not have enough permissions to request those metrics. In `contrib/kube-prometheus` this is definitely correctly configured, so I imagine there is some problem with the helm charts. cc @gianrubio

**Comment by IvanBiv** [comment]
Before deploy with helm I do:

$ kubectl -n kube-system create sa tiller
$ kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
$ helm init --service-account tiller --upgrade

from https://github.com/coreos/prometheus-operator/tree/master/helm/prometheus-operator
But I see the same `server returned HTTP status 403 Forbidden` in `kubelet` category in Prometheus UI.

What I can do for find the reason?
