### ISSUE TITLE
tectonic: Prometheus doesn't create RBAC rules for service account

### ISSUE THREAD

**Issue by philips** [coreos/prometheus-operator#134]
Symptom after deploy:

```
$ kubectl logs prometheus-operator-996254120-d3vg7
ts=2017-02-04T02:57:56Z caller=operator.go:126 component=alertmanageroperator msg="connection established" cluster-version=v1.5.2+coreos.1
ts=2017-02-04T02:57:56Z caller=operator.go:154 component=prometheusoperator msg="connection established" cluster-version=v1.5.2+coreos.1
ts=2017-02-04T02:57:56Z caller=main.go:106 msg="Unhandled error received. Exiting..." err="Forbidden: \"/apis/extensions/v1beta1/thirdpartyresources\" (post thirdpartyresources.extensions)"
```

**Comment by brancz** [comment]
There are multiple things to solve here actually:

* RBAC rules for the Prometheus Operator itself
* Making namespaces accessed by the Prometheus Operator configurable (this then also needs to be reflected in the RBAC rules)
* RBAC rules per namespace a Prometheus object is created in
* Making namespaces accessed by the Prometheus deployment configurable (this is a Prometheus upstream issue, see https://github.com/prometheus/prometheus/issues/2280), and then it also needs to be reflected in the RBAC rules

**Comment by philips** [comment]
cc @xiang90 @hongchaodeng have y'all figured out a solution to this?

**Comment by fabxc** [comment]
Update: 

Most production concerns can be addressed by simply providing RBAC examples covering all permissions Prometheus and prometheus-operator need to function (in progress). Given provided documentation, creating said roles and binding them to the respective service accounts is the users job.
Support for service accounts needs to be added to our TPRs.

More complex are namespace restrictions. This needs changes throughout the entire chain down to Prometheus (with non-trivial implementation changes). The above should solve most use cases and we should add namespace constraints on demand.

**Comment by robszumski** [comment]
Trying this out and running into the same error. I created the RBAC roles in [the newly added doc](https://github.com/coreos/prometheus-operator/blob/master/Documentation/rbac.md)

> Support for service accounts needs to be added to our TPRs.

Does this mean that the above RBAC doc will not work right now?

**Comment by brancz** [comment]
@robszumski that was implemented with the PR adding that doc. It has not landed in a release yet but will in `v0.6.0`, which will soon be released.

**Comment by brancz** [comment]
As of #153 and #161 this can be closed, and namespace constraints are further tracked in #39

**Comment by gyliu513** [comment]
I was still having the same issue, how can I workaround this? Any steps that can help?

```
[root@bd002 ~]# kubectl logs prometheus-operator-2875442694-9lgms --namespace=monitoring
ts=2017-03-04T15:44:38Z caller=operator.go:195 component=prometheusoperator msg="connection established" cluster-version=v1.5.2
ts=2017-03-04T15:44:38Z caller=operator.go:132 component=alertmanageroperator msg="connection established" cluster-version=v1.5.2
ts=2017-03-04T15:44:38Z caller=main.go:107 msg="Unhandled error received. Exiting..." err="creating TPRs failed: Forbidden: \"/apis/extensions/v1beta1/thirdpartyresources\" (post thirdpartyresources.extensions)"
```

**Comment by phspagiari** [comment]
👍 for @gyliu513 problem. I got the same using the `kube-prometheus` deployment script in a `1.5.5` cluster in a `kube-aws` environment.

**Comment by gyliu513** [comment]
@phspagiari just FYI, if only want to test prometheus features, you can direct to https://github.com/vegasbrianc/prometheus , it is using docker-compose, pretty simple to set up a prometheus environment.

**Comment by phspagiari** [comment]
Hey @gyliu513 thanks for sharing.
I've found my problem: The `contrib/hack/kube-prometheus/deploy` uses a `NAMESPACE ` Env Var to define the namespace that will be used to deploy the `prometheus-operator`, but unfortunately there are some hardcoded `monitoring` namespace around the yamls, for example here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml#L12

I've created everything under `monitoring` namespace and works like a charm. Except for the apply vs. create problem (https://github.com/coreos/kube-prometheus/pull/27) but this is problem for another issue :)

**Comment by brancz** [comment]
@phspagiari the create vs. apply problem is solved as soon as your cluster and kubectl are >=1.6.0. 

Regarding the hardcoded namespace things, we are fully aware of this, which is why we want to package up kube-prometheus with helm and other package managers. Those will fully support those scenarios. Otherwise I can only suggest using sed for the time being in the deploy script.
