### ISSUE TITLE
[Helm] Cannot deploy prometheus-operator with storage on glusterfs

### ISSUE THREAD

**Issue by minhdanh** [coreos/prometheus-operator#1357]
**What did you do?**

I used Helm to deploy prometheus-operator with glusterfs for storage. Here's the config for the storage:

```
prometheus:
  storageSpec:
   volumeClaimTemplate:
     spec:
       storageClassName: {{ prometheus_storage_class_name }}
       accessModes: ["ReadWriteOnce"]
       resources:
         requests:
           storage: {{ prometheus_storage_request }}
     selector: {}
```
**What did you expect to see?**

I expect the pods kube-prometheus to be deployed correctly, with a dynamic glusterfs volume provisioned and mounted.

**What did you see instead? Under which circumstances?**

The pod kube-prometheus keeps staying in `ContainerCreating` status. Here's the error:
```
Events:
  Type     Reason       Age               From            Message
  ----     ------       ----              ----            -------
  Warning  FailedMount  3m (x67 over 2h)  kubelet, node4  Unable to mount volumes for pod "prometheus-kube-prometheus-prometheus-0_monitoring(44399ddc-5a53-11e8-a93b-86ce741853f4)": timeout expired waiting for volumes to attach/mount for pod "monitoring"/"prometheus-kube-prometheus-prometheus-0". list of unattached/unmounted volumes=[prometheus-kube-prometheus-prometheus-db]
````

Here're the PVC:
```
kubectl -n monitoring get pvc
NAME                                                     STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
prometheus-kube-prometheus-prometheus-db-prometheus-kp-prometheus-0   Pending                                                                        gluster-heketi   2h
```
And this is the reason why the PVC is in `Pending` status:
```
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  1m (x322 over 2h)  persistentvolume-controller  Failed to provision volume with StorageClass "gluster-heketi": create volume error: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-prometheus-kube-prometheus-prometheus-db-prometheus-kube-prometheus-prometheus-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-prometheus-kube-prometheus-prometheus-db-prometheus-kubepromethues-prometheus-0": must be no more than 63 characters
```
So apparently the volume name is too long and glusterfs refused to creat it.
The volume name is based on the PVC name, which is also long.

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

```
Kubespray (https://github.com/kubernetes-incubator/kubespray/)
```

**Comment by gianrubio** [comment]
There's not to do in helm so I created a PR to limit the volume name in 63 chars

**Comment by leifmadsen** [comment]
The name is auto-generated somehow, I suspect by the Operator container itself. No change in Helm will resolve this unless you limit the name to something like 2 chars, and even then, certain environments will still result in longer than 63 chars. I haven't figured out where this lies specifically, but it can't be resolved in Helm. It needs to be resolved in the Operator code or CRD.

**Comment by leifmadsen** [comment]
@brancz can you point out where that naming generation happens? At least I could have a fix locally. Alternatively, there could be a migration script or method to change it right? Like if you pre-created the PVCs prior to an upgrade, migrated the data, and then did your upgrade to the new naming convention, then everything should work.

Of course I'd put this in a major version change, but it seems like something that should eventually be addressed. Deployments basically can't be named more then 2 or 3 chars with the current naming convention.

**Comment by brancz** [comment]
Agreed, this should eventually be resolved. If we can work out an in-place migration I'd be most happy with that.

**Comment by gianrubio** [comment]
@brancz #1362 is address to fix that

**Comment by fgrelaud** [comment]
Hi,

is there a merge of planned ?

With the last version of kube-prometheus by helm (0.78), i got the same issue.

`  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  20s (x2 over 56s)  persistentvolume-controller  Failed to provision volume with StorageClass "gluster-heketi": create volume error: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-prometheus-kp-prometheus-db-prometheus-kp-prometheus-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-prometheus-kp-prometheus-db-prometheus-kp-prometheus-0": must be no more than 63 characters`

Is there a workaround ? Can i specify the name of the database ?

Thanks

**Comment by rmartinez3** [comment]
I just bumped into this problem as well.

``
Failed to provision volume with StorageClass “gluster”: create volume error: failed to create endpoint/service error creating service: Service “glusterfs-dynamic-prometheus-prometheus-db-prometheus-prometheus-0" is invalid: metadata.name: Invalid value: “glusterfs-dynamic-prometheus-prometheus-db-prometheus-prometheus-0”: must be no more than 63 characters
``

 Is there a way we can just set the volume name ourselves , or shorten it to prom-db ? I saw the merge request but i think we still will have a problem since that limits the volume name to 63 characters however. when the volume claim template creates the pvc it will name it as 

``
<volume-name>-<pod-name>
``

Then you have to also take in consideration that when using gluster the length limit for claimname is 45 , The reason is that glusterfs need to create an endpointname in form of glusterfs-dynamic-<claimname> and the length limit is 63.

so if using gluster will need to have a short volume name 

Thanks

**Comment by rmartinez3** [comment]
#1538 allows you to modify the pvc name. Which will then allow to set a short name so gluster can create a pvc for you. 

```
volumeClaimTemplate:
      metadata:
        name: data
```

Note that if upgrading have to delete statefulset first since statefulset does not allow you to upgrade and change pvc fields.

**Comment by brancz** [comment]
Thanks a lot for taking care of this @rmartinez3! I'll close this now as the problem has been solved thanks to your contribution! :tada:

**Comment by JannikZed** [comment]
hey, could somebody please explain where exactly I need to set this value? It's not documented here: https://github.com/helm/charts/tree/master/stable/prometheus-operator
I tried out several things, but prometheus would always just create a PVC with a 64 characters long name.
