### ISSUE TITLE
Prometheus servers are not scraped by "default"

### ISSUE THREAD

**Issue by galexrt** [coreos/prometheus-operator#136]
The created prometheus instances themselves are not scraped for metrics by "default".

From my perspective there are two ways how this can be dealt with:
1. Simply adding an ServiceMonitor for the Prometheus servers (user side, would need documentation)
2. Automatically adding a ServiceMonitor for a started Prometheus instance (project side)

This issue should be used as a discussion what way would be better and what other ways are there for changing/fixing this issue.

I personally prefer the second way, but I already "know" that some people don't want the prometheus instance scrapping itself, but simply having a toggle for that would be a good way.

**Comment by fabxc** [comment]
I don't think self-scraping is generally something to be added by default.
Meta-monitoring should be setup separately. We should add more documentation on best practices around it.

**Comment by brancz** [comment]
Closing here. Added it to the group issue for documentation (#98).
