### ISSUE TITLE
Is Prometheus Federation feature available here now ???

### ISSUE THREAD

**Issue by sujithnss** [coreos/prometheus-operator#1364]
Hi

This is just a question , do we have Prometheus Federation feature available with Prometheus Operator today ??? How we can implement the same

Best Regards
Sujith P V

**Comment by brancz** [comment]
Prometheus federation simply uses a different metrics endpoint than `/metrics`. You can configure the metrics path in the `ServiceMonitor` object. So yes, you can do federation with the Prometheus Operator.
