### ISSUE TITLE
make jimmidyson/configmap-reload image configurable

### ISSUE THREAD

**Issue by laverite** [coreos/prometheus-operator#137]
is there a way to make the jimmidyson/configmap-reload image configurable?  if prometheus is to be deployed on-prem behind a firewall forcing this image location is prohibitive.

**Comment by fabxc** [comment]
Mh, I can see the use case but would consider it to be a rather rare and
static configuration option. So I'd rather not make it part of the TPR.
This should probably be a flag of the operator binary.

**Comment by laverite** [comment]
i tried to do this at https://github.com/coreos/prometheus-operator/compare/master...laverite:no-hardcoded-configmap-reload?expand=1, with the being I don't really know Golang :)

**Comment by fabxc** [comment]
Looks pretty good. If you file a pull request we can give it a proper
review :)

**Comment by brancz** [comment]
closed by #140 and available in latest release
