### ISSUE TITLE
pec.clusterIP: Invalid value: "None": field is immutable

### ISSUE THREAD

**Issue by nesoneg** [coreos/prometheus-operator#1373]
**What did you do?**
`helm upgrade -f values.yml prometheus-v2 stable/prometheus`

**What did you expect to see?**
`Release "prometheus-v2" has been upgraded. Happy Helming!`

**What did you see instead? Under which circumstances?**
`Error: UPGRADE FAILED: Service "prometheus-v2-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "None": field is immutable && Service "prometheus-v2-node-exporter" is invalid: spec.clusterIP: Invalid value: "None": field is immutable`

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Standalone

* Manifests:

```
commit c2a0e2bd3fcf4feb436dd1c80acf5ac98751a298 (HEAD -> master)
Author: Andrey Kolesnikov <akolesnikov@wallarm.com>
Date:   Tue May 22 12:38:30 2018 +0300

    [prometheus] Fix "Invalid value: "None": field is immutable" in new chart

diff --git a/prometheus/values.yml b/prometheus/values.yml
index d387ecb..e28420b 100644
--- a/prometheus/values.yml
+++ b/prometheus/values.yml
@@ -11,6 +11,12 @@ nodeExporter:
     key: node-role.kubernetes.io/master
 pushgateway:
   enabled: false
+kubeStateMetrics:
+  service:
+    clusterIP: ""
+nodeExporter:
+  service:
+    clusterIP: ""
 networkPolicy:
   enabled: true
 rbac:
```

**Comment by vlaguduva** [comment]
I am a newbie, ran into the same issue; I think, it is complaining that clusterIP is already assigned prior to this upgrade and could not be updated to None.

**Comment by brancz** [comment]
The prometheus-operator and kube-prometheus helm charts have been migrated to the upstream stable helm charts. Because of this we are not accepting any pull requests or issues about it in this repository. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

Please open an issue on the upstream helm charts repository, as the Prometheus Operator maintainers neither use nor maintain the helm charts.

Thank you for your understanding! :slightly_smiling_face:
