### ISSUE TITLE
setting --storage.tsdb.min-block-duration and --storage.tsdb.max-block-duration

### ISSUE THREAD

**Issue by felipejfc** [coreos/prometheus-operator#1375]
Hi, I'ld like to specify both of these settings manually but can't find any way in the operator API to do it, is it possible?

**Comment by felipejfc** [comment]
I see, @Bplotka seems its not happening :/

**Comment by brancz** [comment]
Can you elaborate on the use case you why you would want to tune these flags?

**Comment by felipejfc** [comment]
It's for using [thanos](https://github.com/improbable-eng/thanos), @Bplotka can elaborate better than me

**Comment by Bplotka** [comment]
Yea, for thanos, running local compaction is not advised, so `--storage.tsdb.min-block-duration` should equal to `--storage.tsdb.max-block-duration` and all should equal to 2h.

I think currently Prometheus default for `--storage.tsdb.max-block-duration` is some calculation based on retention, so current Thanos manifests are wrong in Prom operator. (If I am right with defaults)

**Comment by brancz** [comment]
That makes sense. I'm struggling to figure out whether I would just like a "Thanos mode" or allow overriding these values. (cc @mxinden)

Thanks for elaborating, this should definitely be possible.

**Comment by Bplotka** [comment]
Yea, I think just Thanos is fine for now, until some strong argument will appear someday for general override option. Also for Thanos `--storage.tsdb.min-block-duration=--storage.tsdb.max-block-duration=2h` is totally enough (: Not need to actually modify anything further.

**Comment by brancz** [comment]
> `--storage.tsdb.min-block-duration=--storage.tsdb.max-block-duration=2h`

Yeah that was my thought exactly. I would like to discuss a deeper Thanos integration with @mxinden once he's back from vacation (monday). Ideally the sidecar is automatically added and configured appropriately from the Prometheus object as well. This would likely be an experimental feature at first, but I think it would be a good idea.

**Comment by druss17** [comment]
I came across this posting a while back and we were wondering if it is still optimal to keep min = max = 2 hr?  We would like to keep less metrics in memory and were hoping to reduce this time but wanted to confirm it would not cause issues.  Can someone please let me know what to expect if I were to lower this to min = max = 1 hr?


Thanks,

**Comment by brancz** [comment]
As compression gets better the closer we get to the 2h time, you’re not going to win a whole lot with this. There is a general problem in prometheus in regard to needing better memory management for the head block, which is currently all in memory. That’s what needs to be improved.

**Comment by druss17** [comment]
Thank you for the follow-up.

**Comment by Xtigyro** [comment]
Is there a way to lower the 2-hour mark for testing purposes only?

I need to migrate a setup of Prometheus Operator and Thanos sidecar (running a very old Thanos version - 0.4) to latest Thanos (0.15). For that some tests need to be conducted whether the uploaded data in the object store is correct and will be nice if that can be done faster with smaller pieces of data.

**Comment by Kampe** [comment]
This level of configuration is needed for the Thanos Receive component.

https://github.com/thanos-io/thanos/issues/2114
