### ISSUE TITLE
Add support for serviceMonitorNamespaceSelector to prometheus helm chart

### ISSUE THREAD

**Issue by mrueg** [coreos/prometheus-operator#1379]
**What did you do?**
Tried out the prometheus{,-operator} helm chart
**What did you expect to see?**
Support for serviceMonitorNamespaceSelector in prometheus chart, allowing me to select prometheus labels via a matchLabel / matchExpression syntax
**What did you see instead? Under which circumstances?**
Not yet supported there

I'm not fully aware how the serviceMonitorNamespaceSelector currently works, thus asking for support here.

**Comment by gianrubio** [comment]
it's not currently supported in the helm charts. Do you want to send a PR to add this feature?
You can read the how to contribute [here](https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-contribue). I'd expect this option as an optional argument [here](https://github.com/coreos/prometheus-operator/blob/b30d5e8ccd8fe5bc3f7eb7e91caaae537605af68/helm/prometheus/templates/prometheus.yaml#L64
)

**Comment by mrueg** [comment]
Yes I'd like to help. Currently I haven't got it to work though when editing the helm charts myself and it's difficult to figure out where the issue is.

**Comment by faheem-cliqz** [comment]
Had the same issue of missing `serviceMonitorNamespaceSelector` in the helm chart, couple of days ago, and can help as well. This field is part of [PrometheusSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec). It would be nice to have the `serviceMonitorNamespaceSelector` template in the [Prometheus Helm Chart](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml#L64). And then we can use it from the `kube-prometheus` chart.
