### ISSUE TITLE
Helm: Cannot use values.yaml file from prometheus and alertmanager chart

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#1380]
**What did you do?**
Configure prometheus and alertmanager chart values.yaml to use type: NodePort
**What did you expect to see?**
NodePort type sets for Alertmanager and Prometheus chart
**What did you see instead? Under which circumstances?**
The prometheus or Alertmanager service does not switch to NodePort.  Had to set the NodePort type from kube-prometheus values.yaml in order for the service to run as NodePort.  The alertmanager & prometheus chart values.yaml has the same setting for NodePort type
**Environment**
CentOS 7.4, prometheus-operator 0.19.0
* Kubernetes version information:

         Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
         Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kubeadm

* Prometheus Operator Logs:

No error return from prometehus-operator log

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
