### ISSUE TITLE
How can we add extra dashboards to Grafana

### ISSUE THREAD

**Issue by r-divakaran** [coreos/prometheus-operator#1401]
**What did you do?**
I have installed prometheus-operator and kube-prometheus using helm. Command used are
```
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring --set image.tag=v0.19.0 --set rbacEnable=true
```
and
```
helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring
```

Its working and am able to access grafana and see the default dashboards and graphs. Next I need to add some additional dashboards to grafana. So if I udnerstood correct, there is not a way or value that can be set in kube-prometheus chart installation to define additional dashboards.
So I decided to install coreos/grafana helm chart and by setting serverDashboardConfigmaps. I used the command as below
```
helm install coreos/grafana --name grafana --set image.tag=4.4.1 --set serverDashboardConfigmaps={"grafana-additional-dashboards"}
```

**What did you expect to see?**
I was expecting to have grafana up and running including my additional dashboards.

**What did you see instead? Under which circumstances?**

Grafana helm chart installation never finished, as the container was not starting and throwing below error
```
MountVolume.SetUp failed for volume "grafana-additional-dashboards" : configmaps "grafana-additional-dashboards" not found
```

The configmap I used is pasted in the manifest section

The json files are existing inside grafana-dashboards directory, from where I am executing the helm command.

**Environment**

Its my QA cluster, deployed in AWS.

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

Cluster is created using kops and is running in AWS.

* Manifests:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-additional-dashboards
data:
{{ (.Files.Glob "grafana-dashboards/*.json").AsConfig | indent 2 }}
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

Please let me know what is the best way to add additional dashboards to grafana. I actually wanted to avoid installing helm chart, as its already included in kube-prometheus.

Thanks

**Comment by aranair** [comment]
I believe serverDashboardConfigmaps should be an list/array.

I just submitted https://github.com/coreos/prometheus-operator/pull/1408 to update the README for doing exactly that. (The setup works for me)

**Comment by r-divakaran** [comment]
I have a feeling the configmap is not getting created because of a syntax issue. My configmap looks like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-dashboards
data:
 {{ (.Files.Glob "additional-dashboards/*.json").AsConfig | indent 2 }}
```

When I try to apply it directly, it throws error like
```
error: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"(.Files.Glob \"additional-dashboards/*.json\").AsConfig | indent 2":interface {}(nil)}
```

**Comment by aranair** [comment]
You can’t apply it directly. Try using helm to install/upgrade but add —dryrun —debug and check output if it fills it in properly. Or you can just check if the correct configmap is created after u install the helm chart?

**Comment by r-divakaran** [comment]
Yes as I said in my first request, initially I tried with helm and it was complaining that the config map is not found. Then I suppose the configmap creation was not working due to same error as above !?

**Comment by r-divakaran** [comment]
What am doing is:
1) Have the grafana chart locally
2) Modified the valuyes.yaml including the extra configmap
```
## A list of additional configmaps that contain -dashboard.json and/or -datasource.json files
## that should be imported into grafana.
serverDashboardConfigmaps:
  - additional-dashboards

serverDashboardFiles: {}
```
serverDashboardFiles: {}
3) I have put the extra configmap inside templates/additional-dashboards-configmap.yaml
```
cat templates/additional-dashboards-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-dashboards
data:
 { (.Files.Glob "additional-dashboards/*.json").AsConfig | indent 2 }
```
4) then trying like `helm install coreos/grafana --name grafana -f values.yaml`

```
helm install coreos/grafana --name grafana -f values.yaml --debug --dry-run | grep Source
dataSource: {}
  loadBalancerSourceRanges: []
dataSource: {}
  loadBalancerSourceRanges: []
# Source: grafana/templates/secret.yaml
# Source: grafana/templates/dashboards-configmap.yaml
# Source: grafana/templates/serviceaccount.yaml
# Source: grafana/templates/psp-clusterrole.yaml
# Source: grafana/templates/psp-clusterrolebinding.yaml
# Source: grafana/templates/svc.yaml
# Source: grafana/templates/grafana-deployment.yaml
# Source: grafana/templates/psp.yaml
# Source: grafana/templates/servicemonitors.yaml
```
Please let me know if am doing wrong in any step. Thanks!

**Comment by r-divakaran** [comment]
I was able to get this working by using the chart that is downloaded locally, rather than using a local values.yaml file using -f.
