### ISSUE TITLE
Rename RuleFile to PrometheusRule

### ISSUE THREAD

**Issue by ant31** [coreos/prometheus-operator#1425]
Generic CRD names should be avoided. `RuleFile` could be anything and used by other projects and it's not self-documented. 

We can rename it to `PrometheusRule`, which is more specific.

**Comment by mxinden** [comment]
I agree with the fact that `RuleFile` is too generic.

The name `PrometheusRule` is confusing to me. A `PrometheusRule`custom resource  would contain multiple Prometheus rules.

Instead I suggest `PrometheusRuleFile`.

@ant31 @brancz @community what do you think?

**Comment by brancz** [comment]
While semantically not 100% correct, the file part is meaningless to users, it's just a means to an end.

I still think `PrometheusRule` makes the most sense, even in the sense of a collection of rules. It's what will be most comprehensible by users. The `File` part would just cause additional confusion I believe.

**Comment by brancz** [comment]
My thought is that then we should have also called Prometheus PrometheusSet and Alertmanager AlertmanagerPeer, but the shortened versions make it clear to users what this is about, rather than detailed correctness of the term.

**Comment by ant31** [comment]
I think it's acceptable to have 'multiple' rule in a crd name PrometheusRule, it's like the resource 'Ingress' you can define many routes in, or all the RBAC resources (e.g. ClusterRole) with many rules inside.

**Comment by mxinden** [comment]
> My thought is that then we should have also called Prometheus PrometheusSet and Alertmanager AlertmanagerPeer

That is a good point.

Let's go with `PrometheusRule` then.

**Comment by ironcladlou** [comment]
I wonder if you could apply the same argument to every other CRD in any other project including `ServiceMonitor` in prometheus-operator (i.e. why not "PrometheusServiceMonitor"); the kind is arbitrary and could be defined by any number of other CRDs given their versions are unique. 

As the number of CRD-based components installed in the cluster grows, I wonder if disambiguation in the UI (e.g. CLI) is an inevitability to deal with. I'd be surprised if this hasn't already been discussed at length somewhere else (/cc @deads2k)...

**Comment by ironcladlou** [comment]
>the kind is arbitrary and could be defined by any number of other CRDs given their versions are unique.

Actually I'm not even sure if that's true...

**Comment by brancz** [comment]
When creating with kubectl, it uses the full API group, so there is no abiguity. Your argument regarding the ServiceMonitor is somewhat true, although (almost) nothing is specific to Prometheus, the concept could be used by any other monitoring system just as well.

When getting resources and there is abiguity you can specify the kind + api group, as in:

```
kubectl get servicemonitor.monitoring.coreos.com
```
