### ISSUE TITLE
Rename "Alertmanager" to "AlertManager"

### ISSUE THREAD

**Issue by aerokite** [coreos/prometheus-operator#143]
Why not following same naming convention like [Kubernetes](https://github.com/kubernetes/kubernetes) for `Alertmanager`?

Kind names are like:
* StatefulSets
* ReplicationController

And all others.

`ServiceMonitor` is following same naming convention.

Why not using `AlertManager` instead of `Alertmanager` as kind name?

**Comment by fabxc** [comment]
"Alertmanager" is the name of the project itself (
https://github.com/prometheus/alertmanager), which for better or worse was
generally decided to only have the A capitalised.

**Comment by fabxc** [comment]
Closing as we are unlikely to change this for the given reason.
