### ISSUE TITLE
Node/Kubelet cannot be scraped from the node running the prometheus pod

### ISSUE THREAD

**Issue by pimvanpelt** [coreos/prometheus-operator#1438]
**What did you do?**
*    Created RBAC bindings
```
cat << EOF | kubectl apply -f
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF

helm init --service-account tiller
```

* Installed operator and prometheus from stable chart
```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring
```
*    Applied `KUBELET_EXTRA_ARGS=--authentication-token-webhook` to kubelets from #867 
*    Observed healthy pods/services/deployments

*    Observed prometheus `/targets`    
```
$ kubectl get pods -n monitoring -o wide
NAME                                                  READY     STATUS    RESTARTS   AGE       IP             NODE
alertmanager-kube-prometheus-0                        2/2       Running   0          37m       10.38.0.3      k8s-0-3
kube-prometheus-exporter-kube-state-f9575dcfc-8smcm   2/2       Running   0          37m       10.35.0.2      k8s-1-4
kube-prometheus-exporter-node-27zbj                   1/1       Running   0          37m       192.168.3.32   k8s-0-1
kube-prometheus-exporter-node-2bttj                   1/1       Running   0          37m       192.168.3.16   k8s-master
kube-prometheus-exporter-node-8ldld                   1/1       Running   0          37m       192.168.3.42   k8s-1-3
kube-prometheus-exporter-node-h64nr                   1/1       Running   0          37m       192.168.3.34   k8s-0-3
kube-prometheus-exporter-node-kgm8p                   1/1       Running   0          37m       192.168.3.35   k8s-0-4
kube-prometheus-exporter-node-vp4jk                   1/1       Running   0          37m       192.168.3.33   k8s-0-2
kube-prometheus-exporter-node-w4zrx                   1/1       Running   0          37m       192.168.3.41   k8s-1-2
kube-prometheus-exporter-node-w5jg2                   1/1       Running   0          37m       192.168.3.43   k8s-1-4
kube-prometheus-exporter-node-x46lf                   1/1       Running   0          37m       192.168.3.40   k8s-1-1
kube-prometheus-grafana-57d5b4d79f-g9l7h              2/2       Running   0          37m       10.38.0.1      k8s-0-3
prometheus-kube-prometheus-0                          2/2       Running   1          37m       10.35.0.1      k8s-1-4
prometheus-operator-6d94d55b6d-cjr7d                  1/1       Running   0          37m       10.38.0.2      k8s-0-3
```

**What did you expect to see?**
Expected to see all nodes and all kubelets being scraped.
Node Exporter on `k8s-1-4` is up and running:
```
$ curl -I 192.168.3.43:9100/metrics
HTTP/1.1 200 OK
Content-Length: 121854
Content-Type: text/plain; version=0.0.4
Date: Tue, 05 Jun 2018 22:35:07 GMT
```

**What did you see instead? Under which circumstances?**
The node exporter and kubelet cannot be scraped on `k8s-1-4` (which is the node that the `prometheus-kube-prometheus-0` pod is running on).

```
Get https://192.168.3.43:10250/metrics/cadvisor: dial tcp 192.168.3.43:10250: connect: connection refused
Get https://192.168.3.43:10250/metrics: dial tcp 192.168.3.43:10250: connect: connection refused

Get http://192.168.3.43:9100/metrics: dial tcp 192.168.3.43:9100: connect: connection refused
```

**Environment**

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	bare metal cluster, installed on local hardware.

**Comment by brancz** [comment]
This sounds more like a firewall (maybe network policy) issue in your setup, as you said that you can't even curl the target. If there was another configuration issue you would see a 401, 403 or some sort of response.  Could you check if that might be the problem?

**Comment by pimvanpelt** [comment]
There is no firewall inhibition on the machine itself:
```
pim@k8s-1-4:~$ ip -4 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 192.168.3.43/24 brd 192.168.3.255 scope global eth0
       valid_lft forever preferred_lft forever

pim@k8s-1-4:~$ curl -I 192.168.3.43:9100/metrics
HTTP/1.1 200 OK
Content-Length: 122115
Content-Type: text/plain; version=0.0.4
Date: Wed, 06 Jun 2018 13:05:24 GMT
```

I **can** see the metrics and curl them from the host machine. Checking out the `kube-prometheus-0` pod is tricky because I don't think it contains any shell for me to exec into. 

No network policies are on the kubernetes cluster.

Perhaps `weave-net` is somehow disallowing container-to-host communication. I'll dig in to this a bit more.

**Comment by brancz** [comment]
Note that firewall rules are typically ignored when the kernel figures out that a request is actually done against a local interface, so what you're seeing would usually be the case even with firewall rules setup.

**Comment by mxinden** [comment]
@pimvanpelt in case you still need to shell into your container for debugging:

```bash
kubectl exec -it -n <namespace> <pod-name> -c prometheus -- /bin/sh
```

**Comment by JTarasovic** [comment]
I'm actually having the same / similar issue.

We are not having any issues w/ node-exporter though.

Using flannel for a network overlay. Deploying the operator from kube-prometheus/manifests.

Two prom pods, each can hit the kubelet metric endpoint for every other node but not the kubelet on the same node.
prom A -> kubelet B 👌 
prom B -> kubelet A 👌 
prom A -> kubelet A 👎 
prom B -> kubelet B 👎 

From inside the prom container, trying `wget https://${NODE_IP}:10250/metrics` gives `No route to host`. From the node itself or a busybox container on the same node, it works fine.

**Comment by mxinden** [comment]
@JTarasovic @pimvanpelt Are you sure this is related to the Prometheus project and not to your networking setup between pod and node network? Are you seeing similar issues in other places where pods try to connect to node instances?

Could you post the output of `ip route` from inside the Prometheus pod here?

**Comment by JTarasovic** [comment]
Max,

During my initial troubleshooting, it appeared to be isolated to the prom pod but on trying it again, a kubernetes launched busybox container cannot hit its own node but a docker launched busybox container can. 😭 

For reference, the prom container shows this for it's route. 10.11.0.0/16 is the flannel overlay.

```
default via 10.11.44.1 dev eth0
10.11.44.0/24 dev eth0 scope link  src 10.11.44.7
```

**Comment by JTarasovic** [comment]
Our problem was definitely a security group issue. Sorry for the noise and thanks for the help.

**Comment by brancz** [comment]
As this is quite an old issue and it seems that security groups/firewalls/networking are the primary issue here, I'm going to close this.
