### ISSUE TITLE
where to set AlertManager Config? 

### ISSUE THREAD

**Issue by jiuchongxiao** [coreos/prometheus-operator#1446]
who know where to set alertmanager configs? i want to set sent email to someone.
i create monitor by kubectl create -f manifests/

**Comment by jiuchongxiao** [comment]
@mxinden  could you help me? i am getting into a flap.thank you

**Comment by brancz** [comment]
It seems we don't have this information documented right now, so I opened a PR to address this: #1450. Feedback would be highly appreciated! :slightly_smiling_face:

**Comment by jiuchongxiao** [comment]
thank you very much for the improvement @brancz

**Comment by mxinden** [comment]
I will close this issue. @jiuchongxiao let us know if you need any further help by either opening a new issue or commenting on this one.

**Comment by jiuchongxiao** [comment]
where position the file (alertmanager-config.jsonnet or alertmanager-config-external.jsonnet、alertmanager-config.yaml) should to put? 
@brancz

**Comment by brancz** [comment]
jsonnet is a language, that generates json, in the readme we described how to build that and convert it to yaml. You can run `kubectl create -f manifests/` once you have generated the new manifests yourself with jsonnet.

**Comment by jiuchongxiao** [comment]
it works,thank you very much @brancz

**Comment by jiuchongxiao** [comment]
it works,but why i cannot find the alertmanager config info in the manifest .yaml. where it goes,and why not in ymal file?
@brancz

**Comment by brancz** [comment]
the files need to be relative to the jsonnet file you are executing
