### ISSUE TITLE
got the error

### ISSUE THREAD

**Issue by wjhboy** [coreos/prometheus-operator#1448]
Endpoint | State | Labels | Last Scrape | Error
-- | -- | -- | -- | --
https://192.168.172.133:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="192.168.172.133:10250" namespace="kube-system" service="kubelet" | 18.524s ago | server returned HTTP status 403 Forbidden
https://192.168.172.133:10250/metrics | DOWN | endpoint="https-metrics" instance="192.168.172.133:10250" namespace="kube-system" service="kubelet" | 19.117s ago | server returned HTTP status 403 Forbidden
https://192.168.172.137:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="192.168.172.137:10250" namespace="kube-system" service="kubelet" | 5.427s ago | server returned HTTP status 403 Forbidden
https://192.168.172.137:10250/metrics | DOWN | endpoint="https-metrics" instance="192.168.172.137:10250" namespace="kube-system" service="kubelet" | 27.455s ago | server returned HTTP status 403 Forbidden
https://192.168.172.138:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="192.168.172.138:10250" namespace="kube-system" service="kubelet" | 8.921s ago | server returned HTTP status 403 Forbidden
https://192.168.172.138:10250/metrics | DOWN | endpoint="https-metrics" instance="192.168.172.138:10250" namespace="kube-system" service="kubelet" | 23.012s ago | server returned HTTP status 403 Forbidden

**Comment by brancz** [comment]
The 403 Forbidden points at your Prometheus server not having the appropriate permissions. Can you share the `Pod`, `ServiceAccount`, and `ClusterRoleBinding` for this setup?

**Comment by wjhboy** [comment]
[root@master01 kubernetes]# kubectl get ServiceAccount --all-namespaces 
NAMESPACE     NAME                                 SECRETS   AGE
default       default                              1         14d
default       prometheus-operator                  1         4h
kube-public   default                              1         14d
kube-system   attachdetach-controller              1         14d
kube-system   bootstrap-signer                     1         14d
kube-system   canal                                1         14d
kube-system   certificate-controller               1         14d
kube-system   clusterrole-aggregation-controller   1         14d
kube-system   cronjob-controller                   1         14d
kube-system   daemon-set-controller                1         14d
kube-system   default                              1         14d
kube-system   deployment-controller                1         14d
kube-system   disruption-controller                1         14d
kube-system   endpoint-controller                  1         14d
kube-system   generic-garbage-collector            1         14d
kube-system   heapster                             1         2d
kube-system   horizontal-pod-autoscaler            1         14d
kube-system   job-controller                       1         14d
kube-system   kube-dns                             1         14d
kube-system   kube-proxy                           1         14d
kube-system   kubernetes-dashboard                 1         14d
kube-system   namespace-controller                 1         14d
kube-system   node-controller                      1         14d
kube-system   persistent-volume-binder             1         14d
kube-system   pod-garbage-collector                1         14d
kube-system   pv-protection-controller             1         14d
kube-system   pvc-protection-controller            1         14d
kube-system   replicaset-controller                1         14d
kube-system   replication-controller               1         14d
kube-system   resourcequota-controller             1         14d
kube-system   service-account-controller           1         14d
kube-system   service-controller                   1         14d
kube-system   statefulset-controller               1         14d
kube-system   token-cleaner                        1         14d
kube-system   ttl-controller                       1         14d
monitoring    alertmanager-main                    1         4h
monitoring    default                              1         4h
monitoring    grafana                              1         4h
monitoring    kube-state-metrics                   1         4h
monitoring    node-exporter                        1         4h
monitoring    prometheus-k8s                       1         4h
monitoring    prometheus-operator                  1         4h
weave         default                              1         8d
weave         weave-scope                          1         8d
[root@master01 kubernetes]# kubectl get ClusterRoleBinding
NAME                                                   AGE
canal-calico                                           14d
canal-flannel                                          14d
cluster-admin                                          14d
heapster                                               2d
kube-state-metrics                                     4h
kubeadm:kubelet-bootstrap                              14d
kubeadm:node-autoapprove-bootstrap                     14d
kubeadm:node-autoapprove-certificate-rotation          14d
kubeadm:node-proxier                                   14d
kubernetes-dashboard                                   14d
node-exporter                                          4h
prometheus-k8s                                         4h
prometheus-operator                                    4h
system:aws-cloud-provider                              14d
system:basic-user                                      14d
system:controller:attachdetach-controller              14d
system:controller:certificate-controller               14d
system:controller:clusterrole-aggregation-controller   14d
system:controller:cronjob-controller                   14d
system:controller:daemon-set-controller                14d
system:controller:deployment-controller                14d
system:controller:disruption-controller                14d
system:controller:endpoint-controller                  14d
system:controller:generic-garbage-collector            14d
system:controller:horizontal-pod-autoscaler            14d
system:controller:job-controller                       14d
system:controller:namespace-controller                 14d
system:controller:node-controller                      14d
system:controller:persistent-volume-binder             14d
system:controller:pod-garbage-collector                14d
system:controller:pv-protection-controller             14d
system:controller:pvc-protection-controller            14d
system:controller:replicaset-controller                14d
system:controller:replication-controller               14d
system:controller:resourcequota-controller             14d
system:controller:route-controller                     14d
system:controller:service-account-controller           14d
system:controller:service-controller                   14d
system:controller:statefulset-controller               14d
system:controller:ttl-controller                       14d
system:discovery                                       14d
system:kube-controller-manager                         14d
system:kube-dns                                        14d
system:kube-scheduler                                  14d
system:node                                            14d
system:node-proxier                                    14d
system:volume-scheduler                                14d
weave-scope                                            8d

[root@master01 kubernetes]# kubectl get pod -n monitoring 
NAME                                   READY     STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2       Running   2          4h
alertmanager-main-1                    2/2       Running   2          4h
alertmanager-main-2                    2/2       Running   2          4h
grafana-56f6bbccc-tvfnt                1/1       Running   1          4h
kube-state-metrics-5bf8c78d78-hfht4    4/4       Running   4          4h
node-exporter-j5cqn                    2/2       Running   2          4h
node-exporter-rsffh                    2/2       Running   2          4h
prometheus-k8s-0                       2/2       Running   3          4h
prometheus-k8s-1                       2/2       Running   3          4h
prometheus-operator-7f8dd94bd6-87hwk   1/1       Running   1          4h

**Comment by wjhboy** [comment]
[root@master01 kubernetes]# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
[root@master01 kubernetes]#

**Comment by wjhboy** [comment]
I used prometheus-operator-release-0.19 for the setup

**Comment by brancz** [comment]
Ah, I actually got my HTTP error codes wrong. 403 Unauthorized (against it's wording) means your serviceaccount token could not be used to _authenticate_ (if authorization fails you would have seen a 401 Forbidden), which means you don't have the `--authentication-token-webhook=true` on your kubelet, which indeed I can't see in that configuration. Could you try that? :slightly_smiling_face:

**Comment by wjhboy** [comment]
thank you ! I will add the --authentication-token-webhook=true configuration in my config file .

**Comment by wjhboy** [comment]
@brancz I have try it . the issue has been resolved
