### ISSUE TITLE
Prometheus rules not populating

### ISSUE THREAD

**Issue by melrakkian** [coreos/prometheus-operator#1452]
**What did you do?**
Installed prometheus operator and kube-prometheus package via quick start instructions (kubectl apply -f bundle.yaml for prometheus operator and kubectl create -f manifests/ for kube-prometheus).  Created an ingress to expose prometheus GUI.

**What did you expect to see?**
Expected to see rules populated within prometheus from the prometheusrule defined in prometheus-rules.yaml.

**What did you see instead? Under which circumstances?**
Prometheus lists 'No rules defined.' in the GUI.  No files exist in the /etc/prometheus/config_out/rules directory of the launched prometheus containers.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Rancher 2.0 cluster running on bare-metal servers

* Manifests:

Stock project manifests were used

* Prometheus Operator Logs:

While testing to try to isolate the issue, I deleted/recreated the prometheus-rules.yml object.  The logs from the prometheus operator after deleting and recreating were repeats of the following (seemed like the operator wasn't detecting the deletion/creation of the prometheusrule object for some reason...when I tested deleting/creating one of the servicemonitor objects, it picked up on that and updated prometheus targets):

2018-06-07T15:16:38-05:00 kube-node2 8e8a2982647d[1511]: ts=2018-06-07T20:16:38.241472963Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
2018-06-07T15:16:38-05:00 kube-node2 8e8a2982647d[1511]: ts=2018-06-07T20:16:38.256792949Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"

**Comment by stijndehaes** [comment]
Are you sure you have waited long enough for the rules to appear?
I submitted this ticket not long ago: https://github.com/coreos/prometheus-operator/issues/1323
mxinden informed me they moved the reload to a time based interval. I had to wait for up to 10 minutes for rules to appear.

**Comment by mxinden** [comment]
@melrakkian thanks for opening the issue and @stijndehaes thanks for referencing me!

With https://github.com/coreos/prometheus-operator/pull/1333 the reload of the Prometheus rules is back to being trigger based and not time based. That being said it should be fairly quick.

@melrakkian to be able to reproduce this, could you give us the following information:

1. Which commit id of the Prometheus Operator / kube-prometheus are you using?

2. The Prometheus Operator aggregates all `PrometheusRule` resources into a Kubernetes `ConfigMap` inside the same namespace as the Prometheus instance. Could you look for that `ConfigMap` and post its content here? It should be called something like: `prometheus-<prometheus-name>-rule-files`.

3. This `ConfigMap` is mounted into the Prometheus container of the Prometheus Pod. Can you `exec` into the container via `kubectl exec -it -n prometheusdeprecatedruleselectorfield-1526565040-0   prometheus-test-0 -c prometheus -- /bin/sh` and check if the Prometheus rule files are properly mounted into the container? You should be able to find them in `/etc/prometheus/rules`.

**Comment by melrakkian** [comment]
Thanks, @mxinden and @stijndehaes!

1.  I had been troubleshooting with commit id 7d08e3d69c9d1d6dbdd06762935d616cfa51b81f from a few days ago.  I just pulled down and installed the latest commit (3c226f965e2568be0d28f3d22c59cccf895e71ed), and the prometheus rules populate just fine for me now.  Wish I had thought to try that sooner ;-)
