### ISSUE TITLE
Can the configmap generated by PrometheusRule's hit the size limit?

### ISSUE THREAD

**Issue by nabadger** [coreos/prometheus-operator#1472]
As far as I'm aware there's still a 1mb size limit imposed on configmaps due to the backend storage.

I noticed that when we create `PrometheusRule` objects, the operator ends up populating a single configmap. It looks like this is handled by `makeRulesConfigMap`

Could this potentially hit the config size limit, and if so, is there a workaround? Previously I could generate multiple configmaps.

Thanks

**Comment by brancz** [comment]
Yes, that is definitely possible. To be entirely honest we were not expecting people to have that many alert definitions, but as so often that assumption was wrong. We need to fix this.

/cc @mxinden do you want to have a look at this?

**Comment by nabadger** [comment]
Thanks.

It's also worth noting that since the kubernetes `PrometheusRule` object will also need to store the `last-applied-configuration` in the annotation, the amount of rule-data we can actually add is further reduced.

**Comment by mxinden** [comment]
I got a first work in progress PR up: https://github.com/coreos/prometheus-operator/pull/1562

@nabadger in your scenario: Does a collection of rule files exceed the config map size limit of Kubernetes, or does a single rule file exceed the limit by itself?

**Comment by nabadger** [comment]
@mxinden at the moment we're not hitting limit. I doubt we will, but I saw this as a regression since the previous version took care of this automatically.
