### ISSUE TITLE
Grafana - allow for LDAP configuration in grafana.ini & ldap.toml

### ISSUE THREAD

**Issue by datarace** [coreos/prometheus-operator#1477]
**What did you do?**
Installed Helm Chart, but there is no externalization of LDAP authentication for Grafana
The Grafana Helm chart should allow for LDAP configuration in grafana.ini & ldap.toml

**Comment by gianrubio** [comment]
We're planning to use charts from upstream https://github.com/coreos/prometheus-operator/issues/1154 so this feature should be available on grafana and not here. I'm gonna close this issue for now because we are not planning to accept this feature here.
