### ISSUE TITLE
basic auth not working in ServiceMonitor

### ISSUE THREAD

**Issue by Andre-Freitas** [coreos/prometheus-operator#1487]
**What did you do?**

Added prometheus to a k8s cluster using helm chart kube-prometheus (0.0.79). All pods are running as expected:

```bash
$ kubectl -n monitoring get pods
NAME                                                 READY     STATUS    RESTARTS   AGE
alertmanager-monitor-0                               2/2       Running   0          2d
alertmanager-monitor-1                               2/2       Running   0          2d
monitor-exporter-kube-state-98b4474d4-xjj4l          2/2       Running   0          20m
monitor-exporter-node-265cf                          1/1       Running   0          20m
monitor-exporter-node-jnsj7                          1/1       Running   0          20m
monitor-exporter-node-ksnz5                          1/1       Running   0          20m
monitor-grafana-6f8c4f9d97-ht2qk                     2/2       Running   0          20m
op-prometheus-prometheus-operator-7b487b9697-7t27h   1/1       Running   0          3d
prometheus-monitor-prometheus-0                      2/2       Running   2          3d
prometheus-monitor-prometheus-1                      2/2       Running   1          2d
```
using this [info](https://coreos.com/operators/prometheus/docs/0.17.0/user-guides/basic-auth.html) i tried to create a service monitor for a existing container that is exposing prometheus metrics

```bash
$ cat basic-auth.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: device
  name: basic-auth-device-example
  namespace: monitoring
spec:
  endpoints:
  - basicAuth:
      password:
        name: auth
        key: password
      username:
        name: auth
        key: user
    port: "8888"
    interval: 30s
    path: /monitor/prometheus
  namespaceSelector:
    matchNames:
    - develop
  selector:
    matchLabels:
      app: device
      release: device
---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  namespace: develop
data:
  password: JDBjMWo1aUEjTnFncVVDVm1BUno=
  user: YWRtaW4=
type: Opaque
```
``` bash
$ kubectl create -f basic-auth.yaml 
servicemonitor "basic-auth-device-example" created
secret "auth" created
```

**What did you expect to see?**

This new device being added to the target list in prometheus

**What did you see instead? Under which circumstances?**

``` bash
ts=2018-06-14T17:15:31.89324404Z caller=operator.go:345 component=prometheusoperator msg="Prometheus updated" key=monitoring/monitor-prometheus
ts=2018-06-14T17:15:31.89333494Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/monitor-prometheus
E0614 17:15:31.901566       1 operator.go:597] Sync "monitoring/monitor-prometheus" failed: creating config failed: Could not generate basicAuth for servicemonitor basic-auth-device-example. BasicAuth username and password secret not found.
```

**Environment**

* Kubernetes version information:

``` bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:24:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

This cluster was create in Azure Container Service (AKS)

**Comment by brancz** [comment]
My hunch is that we only look for secrets in the same namespace as the Prometheus object, instead we should use the namespace of the ServiceMonitor.

@mxinden do you think you could have a look at this?

**Comment by Andre-Freitas** [comment]
i tried even having the secret in "default" namespace but with no success. I think we should use the namespace defined in namespaceSelector: as normally the secrets for a specific service with be in the same namespace as the service that we are trying to monitor and not in the namespace of the servicemonitor

**Comment by brancz** [comment]
I think we can only do the namespace of the ServiceMonitor, as the content of the `namespaceSelector` is ultimately executed by the Prometheus instance itself, so we don't know which namespace it could be. With the `v0.19.0` release you can select ServiceMonitor objects across namespaces, though so teams can just define the ServiceMonitor in their namespace and have the secret there as well. Just to make sure, could you try having the Secret in the same namespace as the executing Prometheus server and ServiceMonitor?

**Comment by mxinden** [comment]
> My hunch is that we only look for secrets in the same namespace as the Prometheus object, instead we should use the namespace of the ServiceMonitor.

Yes, that is correct. We are only looking inside the [namespace](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L1001) of the Prometheus instance for secrets.

Instead looking for secrets inside the ServiceMonitor namespace sounds good to me.

**Comment by Andre-Freitas** [comment]
@brancz i have tested the following:

1. created service device-metrics in develop namespace + secret and ServiceMonitor in monitoring namespace = **device-metrics correctly added** to prometheus target list
1. created service device-metrics and ServiceMonitor in develop namespace + secret in monitoring namespace = **device-metrics correctly added** to prometheus target list
1. created service device-metrics, ServiceMonitor and secret in develop namespace = **Could not generate basicAuth for servicemonitor basic-auth-device-example. BasicAuth username and password secret not found.**

**Comment by mxinden** [comment]
Thanks a bunch for the thorough testing!

> @mxinden it would be nice to be able to fetch secrets in the same namespace of the service that we want to monitoring, so that we dont need to replicate the existing secrets for prometheus namespace

For sure, I think the current state should be treated as a bug. In my eyes, we should only look for secrets inside the namespace of the ServiceMonitor.

@Andre-Freitas would you like to give this a shot and create a patch for it? [`loadBasicAuthSecrets`](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L1009) should be your entry point here. I am of course happy to help. If don't have time I will try to get to this in the upcoming weeks.

**Comment by Andre-Freitas** [comment]
@mxinden i don't have knowledge of Go language so i can't help in there

**Comment by brancz** [comment]
@huydinhle go for it! :slightly_smiling_face:

**Comment by mxinden** [comment]
@huydinhle absolutely! Feel free to open up a _work-in-progress_ PR early on, so we can help you or give early feedback. Thanks.

**Comment by huydinhle** [comment]
@brancz @mxinden thank you guys. Here is the WIP PR https://github.com/coreos/prometheus-operator/pull/1550. Let me know  :smile:

**Comment by mxinden** [comment]
Fixed via https://github.com/coreos/prometheus-operator/pull/1619
