### ISSUE TITLE
Cannot find memory metrics for the pods in default namespace

### ISSUE THREAD

**Issue by alanh0vx** [coreos/prometheus-operator#1489]
**What did you do?**
Installed prometheus by helm -->
_helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring

helm install --name kube-prometheus --namespace monitoring  -f custom-values.yaml coreos/kube-prometheus_

(custom-values.yaml is used for setting requested memory)

_kubectl port-forward -n monitoring prometheus-kube-prometheus-0 9090_

**What did you expect to see?**
Expecting when I check the "kube_pod_container_resource_limits_memory_bytes", it will display the graph for all pods from all namespaces

**What did you see instead? Under which circumstances?**

only able to see the graph from the namespace of "monitoring" and some from "kube-system"

some pods running our own db, rails application in default namespace, the memory metrics cannot be found
but CPU metrics can be found

**Environment**

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by brancz** [comment]
Do you actually have limits defined on those pods?

**Comment by alanh0vx** [comment]
Ok Thanks, know what I am missing now!
:)
