### ISSUE TITLE
Missing headless service

### ISSUE THREAD

**Issue by aerokite** [coreos/prometheus-operator#149]
When creating "Prometheus" instance, operator is creating a headless service "prometheus-operated". 

* What is the purpose of this "headless"  service?

And for each Prometheus, a StatefulSet is created. But no headless service named "prometheus" which is used in  StatefulSet is created. 

* Why not using "prometheus-operated" as governing Service in StatefulSet?
* Or why not creating a headless service for each statefulset by operator?

**Comment by brancz** [comment]
Actually the "prometheus-operated" is meant to be the governing `Service`. This is a bug introduced by some recent renamings. We decided to have one of these `Service`s per namespaces where at least one `StatefulSet` is created in, as the `Pod`s are all sufficiently differently named there is no need for further separation.

**Comment by TamalSaha** [comment]
@brancz totally makes sense. Any timeline for the fix?

**Comment by brancz** [comment]
As this is a bug we will be addressing this very shortly and do a release as soon as we've verified that the fix is working.

**Comment by brancz** [comment]
#150 is merged so this can be closed. Thanks for reporting and fixing!
