### ISSUE TITLE
No datapoints found for container_cpu_usage_seconds_total

### ISSUE THREAD

**Issue by alanh0vx** [coreos/prometheus-operator#1490]
**What did you do?**
```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus.yaml --namespace monitoring
```
```
kubectl port-forward -n monitoring prometheus-kube-prometheus-0 9090
kubectl port-forward $(kubectl get  pods --selector=app=kube-prometheus-grafana -n  monitoring --output=jsonpath="{.items..metada.name}") -n monitoring  3000
```

type the query from Prometheus
```
container_cpu_usage_seconds_total{image!="",namespace="monitoring"}
```

**What did you expect to see?**
able to find `container_cpu_usage_seconds_total` from the dropdown, and the corresponding graph

**What did you see instead? Under which circumstances?**
No datapoints found.

**Comment by brancz** [comment]
Could you make sure that the kubelets are being successfully scraped? You can check this in the `/targets` page of the Prometheus UI.

**Comment by alanh0vx** [comment]
Thanks, kubelets return 401, it should be the similar case as https://github.com/coreos/prometheus-operator/issues/976

**Comment by brancz** [comment]
Yes that was my suspicion :slightly_smiling_face:. We have some troubleshooting docs for this here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#troubleshooting

Let us know if that helps! :slightly_smiling_face:
