### ISSUE TITLE
Is there any way to provide different alerting rules to single prometheus?

### ISSUE THREAD

**Issue by yurchenkosv** [coreos/prometheus-operator#1498]
**What did you expect to see?**
I expect, that developers can write their own alerting rules for their projects. I have one prometheus instance (created with your CRD) and searching the way to provide multiple alerting rules with dynamic update/reload. Something, that you done with ServiceMonitor, when for each project, developer can simply write ServiceMonitor config and prometheus "knows" how to access metrics from this project.
Is there any way to provide alerting rules to prometheus somehow?

**Environment**

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	By kubespray

**Comment by brancz** [comment]
You are in luck, this is exactly why we introduced the `PrometheusRule` CRD in the latest release. You can control which rules are being picked up by a Prometheus server using the `ruleSelector` as well as the `ruleNamespaceSelector`.

Let us know whether this is what you were looking for and how it goes! :slightly_smiling_face:

**Comment by Quentin-M** [comment]
That's awesome! I am really excited to see this, thank you!

The cross-namespace ServiceMonitor was already a huge step that allows us running custom HPA across the board, while keeping separation of concerns. Enabling folks to push custom rules is is one step further towards enabling self-service monitoring/alerting.

It seems to me that the last bit is to let individual developers/teams configure how they want the alerts to be handled / who they should be sent to, without requiring them to make a change to the central alert manager configuration.

Is that something you have on your radar? Or how would you suggest us doing it otherwise?

**Comment by mxinden** [comment]
> It seems to me that the last bit is to let individual developers/teams configure how they want the alerts to be handled / who they should be sent to, without requiring them to make a change to the central alert manager configuration.

@Quentin-M I remember this coming up a couple of times before. So far it is not on our road map, but I do see the practicality in that.

@brancz What is your take on this feature?

**Comment by brancz** [comment]
We have realized that this is a problem for a while, but haven't been able to come up with anything that is sufficiently portable across organizations so far, but honestly our focus also hasn't been on this. @Quentin-M would you mind opening a new issue so we can properly track this? Personally I would really like to have a feature like that kind of feature, but I feel it's going to take some more thinking.

My rough idea is that these scenarios must be possible with ascending difficulty of setup:

* all alerts are mapped onto single receiver
* all alerts are mapped onto single receiver with template (for example all alerts from `team-x` namespace go to `team-x` slack channel/pagerduty receiver)
* arbitrary label matchers sent via single receiver
* arbitrary label matchers sent via single receiver with template (for example all alerts from `team-x` namespace go to `team-x` slack channel/pagerduty receiver)

Generally this seems possible, but `continue` semantics are making be feel uneasy about this. @mxinden do you want to have a deeper look into this?

As a side note dashboarding is also something that still needs to be addressed, but we will likely do so outside of the Prometheus Operator project, but possibly integrate it into the kube-prometheus stack.

**Comment by Quentin-M** [comment]
@mxinden @brancz 

Thank you so much for your answers guys. Given all the work towards the direction of self-service monitoring you have done, I believe this last step, not to say an easy one, would provide the prometheus-operator a compelling user-story, that would be enough of a reason to use the prometheus-operator, and that would be worth a legit article/blog post.

Even though I am using the prometheus-operator, and a lot of records/rules/alerts, I am obviously not as familiar as you guys are with the projects. But the way I see it does not involve templating, etc, but only let the users provide their own alert manager configuration, e.g. matching routes, receivers, etc. Even though not a great UX, users could be responsible for making sure the matching is correct - which would also let them subscribe to other namespaces' alerts. On the other hand, if that makes it simpler, I believe that having them being namespaced would not be a terrible constraint, say alert manager configuration provided in namespace `team-x` would only match by default the rules provided in namespace `team-x`. To be fair, writing it those lines makes me feel that this could be solved simply by deploying various Alert Managers for each team, with their own dedicated configuration..

**Comment by brancz** [comment]
I opened #1528 to take the discussion around Alertmanager configuration there instead of this issue.

In terms of this issue I'll close this here as the initial request is possible, but if you feel anything is unclear or not what you meant @yurchenkosv, then please open a new issue or comment here! :slightly_smiling_face:

**Comment by simonpasquier** [comment]
Hello! I've started a design document:
https://docs.google.com/document/d/1aVVttvocop8zNezwrNFbHh_HKRW_fhJUZqhmrr8fGK0/edit?usp=sharing

Feel free to comment there...
