### ISSUE TITLE
Sharing Grafana info: grafana snapshot and persistent dashboard ID after restart and PNG rendering

### ISSUE THREAD

**Issue by VinceMD** [coreos/prometheus-operator#1507]
**What did you do?**
I use Prometheus Operator 0.19
I did:
1. save the link to a Grafana dashboard
2. create a Grafana snapshot and save the link to the snapshot

**What did you expect to see?**
I was expecting to be able to access the same dashboard and the same snapshot through the link, even after a Grafana pod restart. For as long as the Prometheus has kept the data (I have a 30 days retention)

**What did you see instead? Under which circumstances?**
If I delete/kill the Grafana pod, then the dashboard IDs have changed and the snapshots are lost.
All links are broken.

This makes it difficult to use Grafana and impossible to integrate with our CD pipelines and other tools. Links get invalidated.

**Environment**

* Kubernetes version information:
```Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
kube-aws

* Manifests:

* Prometheus Operator Logs:

**Comment by VinceMD** [comment]
An update and partial solution:
### DASHBOARD  LINK
The UID needs to be set in the JSON of the dashboard to import. Otherwise Grafana will generate one. Example:

```    "timezone": "browser",
    "title": "Janus",
    "uid": "janus",
    "version": 1```

This works for my custom dashboard, easy to set. Now how do I do the same for pre-defined dashboards from Prom-operator? Where are they defined? Or should I export and define my own? Can someone recommend an approach to have a fix UID to all dashboards?

### SNAPOSHOT  PERSISTENCE
This does not solve the problem of snapshots disappearing. Would the solution to convert Grafana into a statefulset with PVC? If yes, is there an example on how to do that?

### PNG  RENDERING
Another idea would be to generate PNG via Grafana API. But this fails:

```t=2018-06-20T03:15:45+0000 lvl=info msg=Rendering logger=png-renderer path="d-solo/janus/janus?orgId=1&var-namespace=bharti&var-pod=ignite-janusgraph-5fcf8765c4-v6zfg&from=1529453750050&to=1529464550050&panelId=32&width=1000&height=500&tz=UTC%2B10%3A00"
t=2018-06-20T03:15:52+0000 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"```

I think it's not enough details for debugging myself. How do I turn on debugging with prom-operator?
Does anyone have a solution though?

**Comment by brancz** [comment]
Providing a UID in the dashboard json is the correct fix. If this was about any of the kubernetes dashboards, could you try with the latest state from master? #1497 pulled in all the upstream changes in the kubernetes monitoring mixin, for which we just fixed the links/uid.

**Comment by VinceMD** [comment]
@brancz thanks that worked.  Good to see one configmap per dashboard.

Just the snapshot and PNG rendering issues outstanding

**Comment by brancz** [comment]
I would prefer not to introduce persistence for Grafana into this stack. Would using the hosted grafana snapshot server be an option for you?

I actually have never heard of the png rendering feature, I would have to look at it more closely to understand why this is happening. Grafana is run completely independently from the Prometheus Operator, so there is nothing additional to do.
