### ISSUE TITLE
Integrate slack and pagerduty and add rules

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1509]
**What did you do?**
configuring Prometheus and grafana on kubernetes ENV. 
**What did you expect to see?**
Need to integrate my own slack channel and pagerduty to the prometheus and need to set custom rules
**What did you see instead? Under which circumstances?**

**Environment**
GCP 
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
	insert output of `kubectl version` here

* Kubernetes cluster kind: 
created cluster using KOPS
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Thanks for opening this issue!

Sorry to disappoint you but this is not a consulting channel, we won't do your work for you. If you are looking for consulting for Prometheus and related topics I would recommend [Robust Perception](https://www.robustperception.io/).

If you are running into problems and you feel that there is actually something wrong with the software that we are producing here, then we are more than happy to help out and improve docs. If this is the case here then please let us know what you did in detail so we can reproduce it and let us know what did not work and what you expected to happen.

**Comment by manuprometheus** [comment]
Okay,Thank you.
