### ISSUE TITLE
Alerts on kube-scheduller and kube-controller does not disappear after fixing the problem

### ISSUE THREAD

**Issue by ItamarYe** [coreos/prometheus-operator#1510]
**What did you do?**
I got alerts in the prometheus after upgrading the kubernetes from 1.9.2 to 1.9.6 about kube-scheduller and kube-controller.

The pods really was down and I started those using the instructions from this link:
https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-scheduler

Now the pods are up, But I still getting the alerts. also when I check the "up" on the prometheus I cannot see the jobs of both kube-scheduller and kube-controller

**What did you expect to see?**
I expected the alerts to disappear and the prometheus "up" graph to show the jobs

**Environment**

* Kubernetes version information:

```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kops

**Comment by brancz** [comment]
Are your pods re-created the exact same way you previously had them? Do the kube-scheduler and kube-controller-manager services actually select those pods so they are successfully discovered?

**Comment by ItamarYe** [comment]
@brancz Thanks for the quick answer.

I checked it and it didn't I re created the services using the yaml file from here:
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/cluster-monitoring.md

Thanks a lot!
