### ISSUE TITLE
Add possibility to set whether target should be namespaced

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#154]
In very specific Kubernetes components the metrics contain the `namespace` label which is relabelled onto the target, which causes label collisions. As this is special to Kubernetes components it's somewhat reasonable to have special code for this in the Prometheus Operator, however, it's a very loose concept so it should rather be kept within an annotation and outside of the TPR.

Proposed annotation name on discovered services is: `alpha.monitoring.coreos.com/namespaced`

The resulting behavior is kept as is when the annotation is set to `true` or _unset_, but when set to `false`, the `namespace` label will not be populated by discovery, therefore the exposed metrics of the target are free to use it.

@fabxc

**Comment by fabxc** [comment]
That would be "set to `true` _or unset_".

**Comment by brancz** [comment]
Yes of course. Edited.

**Comment by brancz** [comment]
Actually it would be anything but `false` will keep the current behavior.
