### ISSUE TITLE
Include kubernetes-app in grafana (enhancement request)

### ISSUE THREAD

**Issue by jalberto** [coreos/prometheus-operator#1544]
Will be great to include kuberntes-app with grafana: 

https://github.com/grafana/kubernetes-app

It provides nice kubernetes dashboards and direct integration

**Comment by aleerizw** [comment]
While kubernetes-app is nice, it seems that the project has been orphaned. The last commit was ~3 months ago :(

**Comment by brancz** [comment]
I don’t really see the point of a plug-in here, it says that it also just uses Prometheus as a metrics backend, so this is just a collection of dashboards. Seems like we should just add some more dashboards that show that information to the kubernetes monitoring mixin.

**Comment by jalberto** [comment]
@brancz not only a coleciotn of dashboards, it also talks directly to k8s API

**Comment by brancz** [comment]
Yeah, but there seems to be a lot of overlap of what kube-prometheus does and what that Grafana plugin is doing (also I wouldn't really be comfortable giving the thing that everyone uses for dashboarding TLS certificates to practically do whatever it wants in the cluster).

I would like to see an actual benefit of this plugin that gives us things we can't already do, I'm fairly certain that the majority of data is already available through Prometheus (and you can still install this plugin if you wish to do so, I just feel it's not something we should include by default).

**Comment by jalberto** [comment]
fair point.

So maybe just copying the dashboards of the plugin (they are better than
current ones) will be a good step forward IMHO

**Comment by brancz** [comment]
That would be awesome! The dashboards come from the [kubernetes monitoring mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) I'm sure everyone would be more than happy to have those in there! I'll open an issue there and tag you to see what we can do.

I'll go ahead and close this one.

**Comment by jalberto** [comment]
I dind't knew that project exists, thanks :)
