### ISSUE TITLE
Showing target down even if the pod is running

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1551]
**What did you do?**
I have configured service monitor for one of my custom application running as a pod. The same is discovered in the service discovery and also listed in target. But showing target down even if it is running
**What did you expect to see?**
I need to see the target status "up"
**What did you see instead? Under which circumstances?**
Showing target down and getting error "server returned HTTP status 404 Not Found"
**Environment**
GCP
* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
Kindly find my service yaml:
________
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: monitoring
  labels:
    k8s-app: influxdb
spec:
  ports:
  - name: web
    port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb
________________

Service Monitor yaml
______

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: influxdb
  name: monitoring-influxdb
  namespace: monitoring
spec:
   endpoints:
   - interval: 30s
     port: web
   selector:
     matchLabels:
       k8s-app: influxdb

**Comment by brancz** [comment]
That sounds like the application you are running in your pod simply doesn't have a `/metrics` endpoint on its http server.

**Comment by manuprometheus** [comment]
Sorry, Could you please tell me how can I add a /metrics endpoint in a pod. Do I need to build any custom metrices?

**Comment by brancz** [comment]
Yes if you want to scrape metrics from an application you need to make it expose metrics. You need to modify the application to do this. Generic workload metrics (CPU, memory, etc.) are already collected by the kube-prometheus stack.

**Comment by manuprometheus** [comment]
Hi, I have added the metrics and now I got the error "no token found" from the target section. Any idea on this?

**Comment by brancz** [comment]
Can you share the output that you get when you curl that `/metrics` endpoint of your target? This sounds like the metrics are not in the correct format.

**Comment by brancz** [comment]
You need to expose metrics in the Prometheus exposition format: https://prometheus.io/docs/instrumenting/exposition_formats/

You can do this with one of the existing client libraries: https://prometheus.io/docs/instrumenting/clientlibs/

**Comment by manuprometheus** [comment]
Thanks@brancz. I will check this.

**Comment by manuprometheus** [comment]
Hi,
Please let me know where can I change the  Prometheus scraping ur?

**Comment by manuprometheus** [comment]
Actually I have created the metrics in the Prometheus exposition format. and it is in  actuator/prometheus.
So I need to change the  Prometheus scraping url.

**Comment by manuprometheus** [comment]
Hi, I found that. Please ignore. Now my issue is when I curl the metrics inside the pod using localhost, it is showing the result. But when checking using the cluster IP, it is not showing any result and the Prometheus  target is checking the path http://clusterip/mycustommetricspath. and showing down status.Can anyone help me?

**Comment by brancz** [comment]
This sounds like your application is not listening on all network interfaces and instead just listens on localhost. You should change it to listen on `0.0.0.0`.

As this is not a Prometheus Operator issue I will close this issue, but feel free to continue to comment or if you think you found a problem with the Prometheus Operator then feel free to open a new issue.
