### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by mikeraimondi** [coreos/prometheus-operator#1555]
**What did you do?**
Made an empty commit in #1444 after a [failed test run](https://travis-ci.org/coreos/prometheus-operator/builds/398268649?utm_source=github_status&utm_medium=notification).

**What did you expect to see?**
Another failed test run.

**What did you see instead? Under which circumstances?**
[Tests passed](https://travis-ci.org/coreos/prometheus-operator/builds/398300981?utm_source=github_status&utm_medium=notification), after failing with the exact same code.

**Comment by brancz** [comment]
Yes we are aware of this flaky test, unfortunately this is a bug in Thanos not the Prometheus operator. Luckily it has already been fixed and will soon be released, then the flaky test will disappear :) .
