### ISSUE TITLE
Custom repository for prometheus-config-reloader

### ISSUE THREAD

**Issue by jungopro** [coreos/prometheus-operator#1557]
**What did you do?**
Trying to deploy prometheus-operator chart

**What did you expect to see?**
Successful deployment

**What did you see instead? Under which circumstances?**
Chart deployment fails with time out

**Environment**

* Kubernetes version information:

1.9

* Kubernetes cluster kind: 

kubespray

**The Problem**

in the [deployment.yaml](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/templates/deployment.yaml) file in the official helm chart, I need to pull the **prometheus-config-reloader** image from a private docker registry that requires authentication (using Artifactory)

I have a secret in kubernetes that is used to login in order to pull other images. The question is how to pass that secret as an argument to the --prometheus-configReloader arg. The relevant lines are 24-29:

```yaml
          args:
          {{- if .Values.kubeletService.enable }}
            - --kubelet-service={{ .Values.kubeletService.namespace }}/{{ .Values.kubeletService.name }}
          {{- end }}
            - --prometheus-config-reloader={{ .Values.prometheusConfigReloader.repository }}:{{ .Values.prometheusConfigReloader.tag }}
            - --config-reloader-image={{ .Values.configmapReload.repository }}:{{ .Values.configmapReload.tag }}
```

I'm aware of the use of imagePullSecrets in a manifest, but I'm unsure how to pass it as an argument to the container

Thank you
Omer

**Comment by brancz** [comment]
When you set the `imagePullSecrets` [in the Prometheus object](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) that is passed on to each Pod, so when you set it in there it should be set for all containers.

https://github.com/coreos/prometheus-operator/blob/451031460b0e8b78e3c4c7becd8f432828d88504/pkg/prometheus/statefulset.go#L169

Does that help?

**Comment by jungopro** [comment]
Hi @brancz. thanks for the reply
That makes perfect sense, I was hoping this is the configuration and no further args are needed.

At the meantime I'm struggling with installing the operator chart in a dark-site of a customer, something isn't working with pulling the image from a private artifactory repo, although I have the secret configured...

I will test it and if I have issues I will let you know.

Much appriciated, 
Omer

**Comment by brancz** [comment]
Let us know how it goes.
