### ISSUE TITLE
Need to integrate my own custom logs(in html or txt format) with prometheus

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1558]
**What did you do?**
I have configured a script that fetch the GCP,Audit log and ssh logs from my cluster environment. The data is stored as html/txt file format.  
**What did you expect to see?**
Now I want to fetch  these logs files by Prometheus and need to display the same in Prometheus GUI.Please let me know whether this is possible.
**What did you see instead? Under which circumstances?**

**Environment**
GCP
* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Prometheus is a metrics system, it is not designed for log data. See more here: https://prometheus.io/docs/introduction/faq/#how-to-feed-logs-into-prometheus?

If you want to create metrics from your log data, you can use something like [mtail](https://github.com/google/mtail) to perform aggregations on your data and make it expose those as metrics.

I'm going to close this here as this is not an issue with the Prometheus Operator, but feel free to comment further should you have more questions.
