### ISSUE TITLE
Prometheus service has no labels

### ISSUE THREAD

**Issue by galexrt** [coreos/prometheus-operator#157]
The `prometheus-$INSTANCE_NAME` and `prometheus-operated` don't have a label. Meaning that there is no way to create a ServiceMonitor to use for scraping the Prometheus instance(s). The only way is, as @brancz, mentioned to create a separate Service.

The questions for is what label(s) should the Prometheus instance service(s) should have that "Meta Monitoring" is simply possible.

**Comment by brancz** [comment]
I would suggest the `prometheus-operated` and `alertmanager-operated` named `Service`s to have the labels `app=prometheus` for prometheus and `app=alertmanager` for alertmanager. And an additional one to distinguish whether this is the `operated` `Service` which would be `operated=true`. Wdyt @fabxc ?

**Comment by galexrt** [comment]
What about when single Prometheus instance deployments should be scraped?
Let's say I have my `prometheus-main` and `prometheus-testing` and I just want to scrape `prometheus-testing`. How about adding label `instance=testing` or something to the Service for that case?

**Comment by brancz** [comment]
That's really just usage of the Prometheus Operator, as those services are not created by it, they're always created by the user - meaning the labeling is entirely up to you :slightly_smiling_face:. It wouldn't hurt though to label the `Service`s in `example/` respectively, just to be a role model.

**Comment by galexrt** [comment]
Well, I completely oversaw that the services are created by the user (me) and not automatically by prometheus-operator. I create a PR adding labels to the example service manifests.

**Comment by fabxc** [comment]
@brancz as mentioned on #98 I think there's some danger to adding `app=prometheus` to the governing service. People label their own services the same and then pull in every Prometheus pod twice unless they set a negative match on `operated=true`. Generally, they probably won't even know about that governing service.

**Comment by brancz** [comment]
I see your concern now. Maybe we need to be more expressive then with just one label, maybe `operated-prometheus=true` ?

**Comment by galexrt** [comment]
@brancz That sounds better. From my perspective this should cause less confusion/mismatching for users, exactly what @fabxc means.
