### ISSUE TITLE
CA certificate issue on Alert manager to use with Slack notification

### ISSUE THREAD

**Issue by VinceMD** [coreos/prometheus-operator#1572]
Already posted here  https://github.com/prometheus/alertmanager/issues/1453

but not sure if prometheus operator can help

Basically when using HTTPS, most of the time we need to install our company's own CA certificate.
Slack notification is not working :

level=error ts=2018-07-04T02:16:23.338459596Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post https://hooks.slack.com/services/XXX/YYYYY/ZGuxM6GbaPv637MkDlF5KxQU: x509: certificate signed by unknown authority"

I hoped inside the container of alert manage and was able to send a message to slack via a good old WGET command (curl is not present in the docker image).

It works ok but maybe wget does not verify CA cert by default.

What's the easiest way to supply a CA cert, to install it on the Docker image?

**Comment by brancz** [comment]
The Alermanager object has the “secrets” field: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec

Using this you can mount your CA cert and consume it through the Alermanager configuration.

**Comment by VinceMD** [comment]
Sorry stupid question but ( I could be wrong ) need latest version of alert manager. To specify the version with Jsonnet I tried that but no luck

```((import 'kube-prometheus/kube-prometheus.libsonnet')  {
   _config+:: {
     alertmanager+: {
       version: 'v0.15.0',
       config: importstr 'alertmanager-config.yaml',
     },
   },
 }) 
```

**Comment by VinceMD** [comment]
ok I got it working. Well sort of. I could mount the CA inside the Alert manager. But Alert manager is still not happy. Maybe an issue with my company CA.
See https://groups.google.com/forum/#!msg/prometheus-users/OYJyteldQlc/7_tAFrHxAQAJ

Anyway the trick is to use `      insecure_skip_verify: true` under http_config.
