### ISSUE TITLE
Wrong port for Alertmanager >=v0.15.0

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#1574]
Starting with Alertmanager version 0.15.0 there are different ports being used for gossiping, but even for Alertmanager >=v0.15.0 versions we still add the old ports to the StatefulSet. Here:

https://github.com/coreos/prometheus-operator/blob/041acb182d8362d7758297e80669ebb3b1e3a4b6/pkg/alertmanager/statefulset.go#L255-L270

This is a bug and should be fixed for any version >=v0.15.0. I'm not 100% certain but I think the port that is now used is `9094` for both TCP and UDP.

@mxinden

**Comment by mxinden** [comment]
@brancz we currently add two ports:
1. `9093` for the web interface `--web.listen-address=127.0.0.1:9093`
2. `6783` for gossiping `--cluster.listen-address=$(POD_IP):6783`

Could you elaborate further on what is missing / obsolete here?

**Comment by brancz** [comment]
Ah I thought we are using the default port. Any idea why we are not? My understanding this should be `9094` instead of `6783`, no?

https://github.com/prometheus/alertmanager/blob/a736a90dd031b4d2b2ee277346c2573961232e9f/cmd/alertmanager/main.go#L129

**Comment by mxinden** [comment]
@brancz No idea why we are running on `6783`. Don't think it matters, right? If you want I can change it so that we are uniform with upstream.

**Comment by brancz** [comment]
I believe this might have been the old gossip port. Yes let's make sure we're aligned with the upstream port(s).

**Comment by mickael-carl** [comment]
Any update on this issue? We now noticed this issue as well. Should something similar to #1601 be opened based on a more up-to-date version of the code?

**Comment by brancz** [comment]
If you want to rebase #1601 I'd be happy to give it another review :)
