### ISSUE TITLE
[Helm] prometheusrules CRDs are not removed after deleting a chart

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#1576]
Since Prometheus Operator 0.20.0 transforms rules ConfigMaps to CRDs automatically, but they are not cleaned up after the chart is deleted.

**What did you do?**
Installed, then subsequently uninstalled the unmodified kube-prometheus chart.

**What did you expect to see?**
That the `prometheusrules.monitoring.coreos.com` CRDs would be removed after uninstalling.

**What did you see instead? Under which circumstances?**
The CRDs are not removed.

**Environment**
* Promehteus operator version: 0.20.0
* Kubernetes version information:
	```
	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
	```

* Kubernetes cluster kind: kubeadm

**Comment by vsliouniaev** [comment]
Fixed

**Comment by gianrubio** [comment]
The CI is flaky so the helm charts didn't synced to s3. Let's keep this issue open until we make sure they were updated on s3.

**Comment by gianrubio** [comment]
The charts were synced to s3 🎉
