### ISSUE TITLE
Add deployPrometheus value to helm/kube-prometheus

### ISSUE THREAD

**Issue by StianOvrevage** [coreos/prometheus-operator#1578]
Right now we use kube-prometheus to deploy the bundle of charts that a complete Prometheus setup consists of (Prometheus, Alertmanager, Node-exporters etc etc).

However, not all options defined in the template for `prometheus` exist in the kube-prometheus chart (such as remoteWrite, https://github.com/coreos/prometheus-operator/issues/352 ).

We deploy Grafana separately since we need values not available in kube-prometheus. It would be nice to be able to NOT deploy Prometheus as part of kube-prometheus as well, and do a separate deploy while waiting for kube-prometheus to reach value-parity with the underlying charts.

**Comment by brancz** [comment]
May I suggest you to also look into other solutions than helm. This exact reason is one of the reasons why we don't use helm at all. We use jsonnet to generate all the manifests with whatever modifications we want and then have additional tooling to simply deploy the rendered Kubernetes manifests. There is a lot of documentation on how to get started already: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

**Comment by StianOvrevage** [comment]
I'm aware that you guys prefer jsonnet but around here Helm is still the de-facto standard for a lot of Kubernetes stuff and that is what our team have experience with. Adding another new component in the mix will be a very tough sell.

Is there any chance you could consider this 3-4 line change to allow us much greater flexibility while still using the Helm charts?

**Comment by vsliouniaev** [comment]
Could you not provide the value to the value to the `prometheus` chart through the `kube-prometheus` chart or am I misunderstanding something?

```
prometheus:
  remoteWrite: {}
```

**Comment by StianOvrevage** [comment]
@vsliouniaev I'm not sure. Does Helm propagate values to sub-charts like that? I thought all variables had to be re-defined in the top-level chart to be able to set them for dependent charts.

**Comment by vsliouniaev** [comment]
It does, I've used this extensively

**Comment by StianOvrevage** [comment]
Somehow I missed that completely. I've got it working now! I guess this issue and the PR can be closed as at least our problems are solved by this.
