### ISSUE TITLE
[kube-prometheus] Add more information on ksonnet to docs

### ISSUE THREAD

**Issue by jordanjennings** [coreos/prometheus-operator#1599]
The current docs say:

>"You may wish to not use ksonnet and simply render the generated manifests to files on disk, this can be done with..."

Can some additional information be given around ksonnet? Is ksonnet a recommended approach? If so, can a ksonnet example be provided? If vanilla jsonnet is recommended instead can that be specifically called out?

I think a standard setup would have at least a non-prod and prod cluster that would want to share manifests, I assume that's where ksonnet comes in? An example of a typical non-prod/prod setup would be helpful if so.

**Comment by KlavsKlavsen** [comment]
I must agree I got lost in the same doc here.. ksonnet is stated to be "optional" - and recommended approach is to compile into own git repository..
But when I run the script just given below, to do that.. it just tries to compile $1-example.json.. which ofcourse isn't there.. and I'm pretty lost..
How are we suppose to build our own config - using kube-prometheus? :(

**Comment by brancz** [comment]
Sorry for the confusion. If you want to customize anything the recommended way to do so is with jsonnet. We should be more clear about that. I opened #1727 to make some of the wordings more clear. Please let us know if and how we can improve this further! :slightly_smiling_face:

**Comment by jordanjennings** [comment]
A lot more information about jsonnet has been added to the docs since I opened this, closing this issue. Thanks!
