### ISSUE TITLE
Need to use secrets in the same namespace as the service monitor for BasicAuth on endpoints

### ISSUE THREAD

**Issue by mmerrill3** [coreos/prometheus-operator#1606]
**What did you do?**
I created a service monitor resource in a namespace that was different than the namespace where prometheus operator was running in.  This service monitor has a basic authorization section in it, where the username and password are defined by using a secret location selector.
**What did you expect to see?**
I expected prometheus operator to see the secret in the same namespace as the service monitor.
**What did you see instead? Under which circumstances?**
I saw prometheus operator only look within its own namespace for the list of secrets that could possibly match the secret defined in the basic authorization section of the service monitor resource.
**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kops cluster running in AWS

* Manifests:

n/a

* Prometheus Operator Logs:

n/a

**Comment by mmerrill3** [comment]
not sure if this is by design, but just wanted to let the coreos team know about our use case.  I can happily provide a pr to address this.

**Comment by brancz** [comment]
Hi. Yes this is indeed something we should fix, and there has already been an attempt at fixing this here: https://github.com/coreos/prometheus-operator/pull/1550. Unfortunately the effort was dropped, but if anyone wants to pick it back up, that would be highly appreciated!

**Comment by mxinden** [comment]
Fixed via https://github.com/coreos/prometheus-operator/pull/1619

@mmerrill3 let us know if this works for you.
