### ISSUE TITLE
prometheus-operator fails if PrometheusRule CRD already exists

### ISSUE THREAD

**Issue by therealgambo** [coreos/prometheus-operator#1607]
**What did you do?**
Using tag: `v0.22.0`

Delete all configurations from kubernetes that were created from the `contrib/kube-prometheus/manifests` directory except for `0prometheus-operator-0prometheusCustomResourceDefinition.yaml`

We leave the the `PrometheusRule` CRD installed, because we have rules in other namespaces, deleting the CRD removes those configurations

**What did you expect to see?**
Prometheus-operator to start normally

**What did you see instead? Under which circumstances?**
Prometheus-operator is stuck in a restart loop because of the error 

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  kops

* Manifests:

* Prometheus Operator Logs:

```
ts=2018-07-11T14:21:01.957651838Z caller=main.go:115 msg="Starting Prometheus Operator version '0.22.0'."
level=info ts=2018-07-11T14:21:02.059631942Z caller=operator.go:293 component=prometheusoperator msg="connection established" cluster-version=v1.8.7
level=info ts=2018-07-11T14:21:02.060623041Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.8.7
level=info ts=2018-07-11T14:21:02.346644997Z caller=operator.go:560 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-07-11T14:21:02.374975227Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-07-11T14:21:02.406616838Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-07-11T14:21:02.42371435Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-07-11T14:21:05.349226415Z caller=operator.go:186 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-07-11T14:21:05.450000517Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-07-11T14:21:05.551825197Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-07-11T14:21:11.558466227Z caller=main.go:175 msg="Unhandled error received. Exiting..." err="creating CRDs failed: waiting for PrometheusRule crd failed: timed out waiting for Custom Resource: failed to list CRD: json: cannot unmarshal number into Go value of type string"
```

**Comment by ArchiFleKs** [comment]
+1 I see the same issue when using : https://github.com/camilb/prometheus-kubernetes

**Comment by brancz** [comment]
Could you try to backup all `PrometheusRule` objects locally:

```
kubectl get prometheusrule --all-namespace -oyaml > prometheus-rule-backup.yaml
```

Then delete everything including the rule objects and the PrometheusRule CRD. Then try to re-create everything.

**Comment by ArchiFleKs** [comment]
I had the same issue. Just edit the clusterrole for Prometheus operator and
added Prometheusrules

**Comment by brancz** [comment]
@ArchiFleKs I see so for you this was just an RBAC issue. Let's if that also helps @therealgambo.

**Comment by jescarri** [comment]
@brancz I just ran into this exact problem.

In my case rback is not my problem, however a bad alert-rule seems to be the culprit.

This is how I detected it.

(Sorry for the quick hacky script).

````
#!/bin/bash

json2yaml() { ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))' - ; }

for i in $(kubectl get ns | grep -v NAME | awk '{ print $1 }'); do
  echo "Namespace: $i"
  for x in $(kubectl -n $i get prometheusrules | grep -v NAME | awk '{ print $1}'); do
     echo "RuleFile: $x"
     kubectl -n $i get prometheusrules -o yaml $x | yaml2json | jq .spec | json2yaml > ~/tmp/$i-$x.yaml; promtool check rules ~/tmp/$i-$x.yaml;
   done;
done
````
Output:

````
Checking /Users/jescarri/tmp/foo-bar.yaml
  FAILED:
group "commerceService", rule 0, "FailingContainers_CommRT": unknown fields in rule: description
group "commerceService", rule 2, "CPU_Usage_Alert_CommRT": unknown fields in rule: description
````

And it indeed is a malformed alert rule:

Missing annotations:

````
- name: fooName
  rules:
  - alert: FailingContainers_CommRT
    description: 'CommRT containers are severely impacted with multiple containers
      down. Check CommRT Service Runbook:'
    expr: avg(kube_pod_container_status_ready{container="foo-bar",namespace="foo",pod=~"bar.*"})
      < 0.5
    for: 3m
    labels:
      severity: critical
````

**Comment by brancz** [comment]
@jescarri that means that entire file was previously not loaded by the Prometheus server. I would suggest to remove those two faulty rules, and let the Prometheus Operator perform the ConfigMap -> PrometheusRule migration.

**Comment by jescarri** [comment]
@brancz yep, we are creating the CRD with the rules, problem with the migration is just a one time thing, and our users update the rules frequently.

I will try to figure out where is crashing, sadly no stack trace this time.

**Comment by therealgambo** [comment]
I haven't been able to re-produce this issue since it first occurred, we are now running v0.23.2

**Comment by brancz** [comment]
In that case as the original issue is solved I'm going to close this here.
