### ISSUE TITLE
How Can I setup ServiceMonitor if applications are routing through a API gateway.

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1621]
**What did you do?**
I have may applications on Kuberentes and they are routed through a API Gateway.
**What did you expect to see?**
I have need to add service monitor for my application,but since they are routed through API Gateway,I have to setup service monitor for that routing app.
**What did you see instead? Under which circumstances?**
So,when my application is deleted,the alert came as the main routing app is down. How can I add service monitor for each app when, they are  are routing through a API gateway
**Environment**
GCP
* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
> I have need to add service monitor for my application,but since they are routed through API Gateway,I have to setup service monitor for that routing app.

This sounds like you are not performing whitebox monitoring. Could you elaborate on what your architecture looks like? Generally the recommendation is to have the Prometheus server as close to the target as possible with as little indirections inbetween as possible. Ideally there is no proxy or anything in between the target and Prometheus and Prometheus directly requests the target's IP.

**Comment by manuprometheus** [comment]
Hi brancz,
We are using Kong API Gateway as a  middleware for our  API-based applications. Could you please share me a useful link for configuring  Whitebox monitoring in this Prometheus setup.

**Comment by manuprometheus** [comment]
Hi, Please close this issue, It is fixed :)
