### ISSUE TITLE
Scrape kubelets through the apiserver

### ISSUE THREAD

**Issue by directionless** [coreos/prometheus-operator#1623]
**What did you do?**

Deployed prometheus-operator, on GKE, using kube-prometheus

**What did you expect to see?**

Metrics. 

**What did you see instead? Under which circumstances?**

401 scrape errors on all the kubelet metrics

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  GKE

# Discussion

Pulling the /metrics and /metrics/cadvisor from the nodes seems problematic. I think this is partly because it's being deprecated (See https://github.com/kubernetes/kubernetes/pull/59827) But it seems to be reachable via apiserver. So, I'd like to move the kublet scrape from `https://<nodeip>:10250/metrics` to `<apiserver>/api/v1/nodes/<nodename>/proxy/metrics` (same for cadvisor).

There seems to be a lot of questions and problems scraping the kublets in GKE.

**Comment by directionless** [comment]
I can workaround this by downgrading the kubelet scrape from https, to http (as discussed in https://github.com/coreos/prometheus-operator/issues/926) but that seems undesirable. Moving the target to the apiserver seems like a better approach.

**Comment by brancz** [comment]
> Moving the target to the apiserver seems like a better approach.

I disagree. This has scalability and correctness issue, as it introduces an additional indirection. I have already thoroughly discussed this with the GKE team and the token authentication and authorization is going to ship with v1.11 of GKE (I'm not exactly sure which version of GKE 1.11, but it's coming).

**Comment by directionless** [comment]
@brancz Oh. You've already discussed this, and the current token auth/authz approach should start working soon? That seems awesome!

Is the take away that the http downgrade is the best short term mitigation, until that lands?

**Comment by brancz** [comment]
Yes I would recommend that until GKE gives you token authentication and authorization.

**Comment by directionless** [comment]
Cool. I updated the docs in https://github.com/coreos/prometheus-operator/pull/1682
