### ISSUE TITLE
kube-prometheus and etcd-mixin - on minikube

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1629]
(By the way, all the jsonnet stuff recently added to kube-prometheus is super cool.)

There's some things about kube-prometheus & etcd that I'm hoping someone can please help me understand...

`#1)` Now that we have [Static etcd configuration](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#static-etcd-configuration) (& [etcd.jsonnet](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/examples/etcd.jsonnet)), regarding [Monitoring external etcd](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-external-etcd.md):
 * should [Step 1 - Make the etcd certificates available to Prometheus pod](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-external-etcd.md#step-1---make-the-etcd-certificates-available-to-prometheus-pod) and [Step 2 - Create the Service, endpoints and ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-external-etcd.md#step-2---create-the-service-endpoints-and-servicemonitor) **be deleted**? Those things are created by `etcd.jsonnet`/`kube-prometheus-static-etcd.libsonnet`.
 * should the rest of the Steps on that page be moved/integrated into `Static etcd configuration`? Thus that entire `Monitoring external etcd` page could be deleted.

`#2)` **How do I figure out what values to use for the 5 `etcd` variables in [etcd.jsonnet](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/examples/etcd.jsonnet)?**

How I setup minikube:
```
josh@MyMac$ minikube version
minikube version: v0.28.0
josh@MyMac$ minikube start --kubernetes-version v1.9.4 --bootstrapper=kubeadm --vm-driver=virtualbox --memory 4096 --extra-config=kubelet.authentication-token-webhook=true --extra-config=kubelet.authorization-mode=Webhook --extra-config=scheduler.address=0.0.0.0 --extra-config=controller-manager.address=0.0.0.0
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
```

Here's what I tried (I used [minikube.jsonnet](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/examples/minikube.jsonnet) as a starting point to create my own version of `minikube.jsonnet` - and I've added in the stuff from `etcd.jsonnet`)...:
```
~/mkp-3a_gh
josh@MyMac$ cat minikube.jsonnet
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-static-etcd.libsonnet') +
  {
    _config+:: {
      namespace: 'monitoring',
      alertmanager+:: {
        replicas: 1,
        config: importstr 'alertmanager-config.yaml',
      },
      grafana+:: {
        config: {
          sections: {
            "auth.anonymous": {enabled: true},
          },
        },
      },
      etcd+:: {
        ips: ['192.168.99.1'],
        clientCA: importstr '/Users/josh/.minikube/ca.crt',
        clientCert: importstr '/Users/josh/.minikube/client.crt',
        clientKey: importstr '/Users/josh/.minikube/client.key',
        serverName: 'minikube',
      },
    },
    prometheus+:: {
      prometheus+: {
        spec+: {
          externalUrl: "http://192.168.99.100:30900",
          externalLabels: {
            cluster: "minikube-josh",
          },
        },
      },
    },
    alertmanager+:: {
      alertmanager+: {
        spec+: {
          externalUrl: "http://192.168.99.100:30903",
          logLevel: "debug",
        },
      },
    },
  };

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
josh@MyMac$ ./build.sh minikube.jsonnet
...
josh@MyMac$ kubectl create -f manifests/
...
```

`#2a)` ...but no etcd stuff ever shows up on http://192.168.99.100:30900/config nor http://192.168.99.100:30900/targets - so I believe (per [Step 4: verify](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-external-etcd.md#step-4-verify)) that means **prom isn't scraping/monitoring etcd**, right?

More info...

`#2b)` I'm simply using the kube config that was generated the first time I ran `minikube start` - **is this file what I should use to determine what 3 files to specify for the 3 "`clientCA/clientCert/clientKey`" variables?**:
```
josh@MyMac$ cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/josh/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/josh/.minikube/client.crt
    client-key: /Users/josh/.minikube/client.key
```
 * Reference info: https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.10.md (Sorry, some of my questions might more so be about how kubeadm sets up etcd than they are about kube-prometheus.)
 * (I did dig into my minikube to try to figure out what 3 cert files etcd uses - e.g. `kubelet.service` in minikube starts `/usr/bin/kubelet` with `--client-ca-file=/var/lib/localkube/certs/ca.crt` - and I verified that file is a copy of `/Users/josh/.minikube/ca.crt` from my Mac.)

`#2c)` **What value should I specify for `serverName`?**:
 * "minikube"? (That's what's printed when I do `minikube ssh` and then `hostname`.)
 * "https://192.168.99.100:8443"? (From `server:` in `~/.kube/config`.)
 * "minikubeCA"?
```
josh@MyMac$ openssl x509 -in /Users/josh/.minikube/ca.crt -text|grep CN
        Issuer: CN=minikubeCA
        Subject: CN=minikubeCA
```

`#2d)` **What value should I specify for `ips`?**:
 * "192.168.99.1"? On my Mac I did the equivalent of `ip addr` (reference info [here](https://github.com/kubernetes/minikube/blob/master/docs/accessing_etcd.md)):
```
josh@MyMac$ ifconfig
...
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
	inet 192.168.99.1 netmask 0xffffff00 broadcast 192.168.99.255
```
 * "192.168.99.100"? (That's what's printed by `minikube ip`.)
 * "10.0.2.15"?
```
josh@MyMac$ kubectl get pods -n kube-system -o wide | egrep "NAME|etcd"
NAME                                    READY     STATUS              RESTARTS   AGE       IP           NODE
etcd-minikube                           1/1       Running             0          20h       10.0.2.15    minikube
```

`#3)` **In minikube do I by chance need to do anything per [Step 3: Open the port](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-external-etcd.md#step-3-open-the-port)?**
 * Note that the only way I've been able to access the etcd metrics is on my Mac doing `minikube ssh` and then `curl http://127.0.0.1:2379/metrics`.

**Comment by brancz** [comment]
1) Yes I think you're absolutely right, we should have one documentation page and it should be folded into the jsonnet documentation, as you proposed.

2)  a) Yes if prometheus isn't showing the target, it's not attempting to scrape it.

b) No the certificates in the kubeconfig are not the ones to access etcd, you need to check the apiserver container.

c) The certificates (`etcd/ca.crt`, `apiserver-etcd-client.crt`, `apiserver-etcd-client.key`), can be found in `/var/lib/localkube/certs/` of your minikube VM, so you would need to copy those out of the minikube VM onto your machine and then you could use them. I just checked the certificate generated for my minikube, and valid `serverName` values would be `localhost` or `127.0.0.1`. You can also use `kubectl cp` to copy them out of the apiserver container.

2d and 3) The whole problem about monitoring your minikube's etcd is that it binds to 127.0.0.1:2379 _only_, and within host networking namespace. This means that no Pod will ever be able to reach it unless it is also run in host networking namespace, which doesn't make sense for Prometheus. This means that unless minikube changes or allows us to configure this, we won't be able to monitor the etcd server of minikube. Maybe we should document this in the readme, that monitoring etcd in minikube is currently not possible because of how etcd is setup?

**Comment by jolson490** [comment]
Thank you so much Frederic for the detailed and helpful info - all of that sounds great.

(I'm currently working on stepping up from [v0.19.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.19.0) to [v0.22.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.22.0). I've never gotten kube-prometheus to monitor etcd in minikube (and it's not a requirement for me) - I just figured I'd make a go of it with the new version `0.22.0`. But I do have v19 of kube-prometheus monitoring etcd in a K8s cluster on AWS - and I'm sure it wont be hard to get that working with v22 also.)

I'll leave this issue open for now - once I'm up & running with v22, then I'll submit a PR to make the doc updates you described.

**Comment by brancz** [comment]
That sounds fantastic, thank you so much for your involvement!
