### ISSUE TITLE
default replicas to 1 / pointer replicas

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#163]
While we default to 1 replica through the `StatefulSet`, this is not the case when reconciling. This is the reason why upstream controllers/resources have the replicas as a pointer, to be able to distinguish from set/unset to default to 1 on unset, but allow to scale to 0.

Fortunately this does not mean a breaking change for users, as parsing manifests will work the same way, but it does require a change in the struct itself. This applies to the `Prometheus` and `Alertmanger` TPR.

@fabxc

**Comment by fabxc** [comment]
I always thought of the `replicas` field as being required. On lookup, it's not documented as that though.
In general this seems fine to do – especially as we cannot validate required fields anyway.
