### ISSUE TITLE
How to use console templates?

### ISSUE THREAD

**Issue by allisonking** [coreos/prometheus-operator#1644]
**What did you do?**
I'd like to try out [console templates](https://prometheus.io/docs/visualization/consoles/). I have a prometheus instance running but I get an error at the path `/consoles/index.html.example`. I described the error here https://github.com/coreos/prometheus-operator/issues/1460 which hopefully is not a hard fix. However, I am wondering what the right way to add my own console templates into the prometheus pod would be. At first I thought I could mount a configmap, but the Prometheus CRD doesn't seem to take volumeMounts. What would you advise to be the right way to do this?
**What did you expect to see?**
An ability to see the default console templates as well as add new ones.
**What did you see instead? Under which circumstances?**
Error described in https://github.com/coreos/prometheus-operator/issues/1460, where the console libraries could not be found.
**Environment**

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	EKS

* Manifests:
none

* Prometheus Operator Logs:
This is probably a separate issue, but I get an endless stream of the following when I log prometheus operator:
```
W0717 17:54:24.778388       1 listers.go:63] can not retrieve list of objec^C54:24.855901       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.855936       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-07-17T17:54:24.8558768Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.860977       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-07-17T17:54:24.894194894Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.894240       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.894279       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.899151       1 listers.go:63] can not retrieve list of objects
```

**Comment by brancz** [comment]
You're absolutely right. Would you like to submit a PR to fix this?

**Comment by mxinden** [comment]
> * Prometheus Operator Logs:
This is probably a separate issue, but I get an endless stream of the following when I log prometheus operator:
```
W0717 17:54:24.778388       1 listers.go:63] can not retrieve list of objec^C54:24.855901       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.855936       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
l* Prometheus Operator Logs:
This is probably a separate issue, but I get an endless stream of the following when I log prometheus operator:
> ```
> W0717 17:54:24.778388       1 listers.go:63] can not retrieve list of objec^C54:24.855901       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.855936       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-07-17T17:54:24.8558768Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.860977       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-07-17T17:54:24.894194894Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.894240       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.894279       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.899151       1 listers.go:63] can not retrieve list of objects
```evel=info ts=2018-07-17T17:54:24.8558768Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.860977       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
level=info ts=2018-07-17T17:54:24.894194894Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0717 17:54:24.894240       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.894279       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0717 17:54:24.899151       1 listers.go:63] can not retrieve list of objects
```

Which version of the Prometheus Operator are you running @allisonking?

**Comment by brancz** [comment]
Sorry, just to be clear, I meant I think the built in consoles should work without bugs, however, I think extending Prometheus with executable code via ConfigMaps is not the right solution, I think for extended consoles, you should build your own images of Prometheus with the additional console templates added. ConfigMaps have a relatively low size limit, so I'd stay away from using them to add code (especially verbose javascript and html).

**Comment by allisonking** [comment]
Okay, I can build my own prometheus image. I tried passing it in with the `--prometheus-default-base-image`, but I can't figure out how to change the version. It seems to tack on `v2.3.1` to my image. I saw in the code it checks for a Tag, but I didn't see a tag flag in the code. Am I missing something?

I'll put together a pull request today for `console_libraries`!

@mxinden I'm using the `quay.io/coreos/prometheus-operator:v0.22.0` image.

**Comment by allisonking** [comment]
Put in a pull request! https://github.com/coreos/prometheus-operator/pull/1653

Another question along with the version question above... is there any way to pass in arguments to the prometheus image? For example, if my console folders aren't in the default location and I'd like to pass in a flag pointing to where they really are. 

Thanks for all the help!

**Comment by brancz** [comment]
There is not, and that's intentional. The Prometheus Operator is supposed to be able to handle breaking changes in Prometheus, if we allowed raw configuration like that, then we could never make sure of that.

**Comment by allisonking** [comment]
Thanks for the answer! I will just build my prometheus image as closely as possible to the default image, but with my own console templates then. 

Could you give me some guidance on the problem I was having above? I passed in the `--prometheus-default-base-image` flag with a string to my image and its version. However, when I apply the manifest, I get an error from kubernetes saying the image is invalid because it tacks on a default prometheus version of `v2.3.1`. How do I pass in my version to make it not use `v2.3.1`?

**Comment by brancz** [comment]
You need to just pass the image repository in that flag. The Prometheus Operator will always attempt to use the tag as specified in the `version` field. That way we can make sure that the configuration and flags are correct for the appropriate version, for example on breaking changes.

**Comment by allisonking** [comment]
I think I'm missing something-- I'm using Amazon ECR to host my image, so it has the form `1234.ecr.amazonaws.com/my-repository@sha256:abc123` which is normally what I pass in to the `image` argument in a manifest without problem

When I pass this into `prometheus-default-base-image`, then look at the pod it generates, there is an `InvalidImageName` status next to the pod, and when I describe it, I get the error:
```
Failed to apply default image tag "1234.amazonaws.com/my-repository@sha256:abc123:v2.3.1": couldn't parse image reference "1234.amazonaws.com/my-repository@sha256:abc123:v2.3.1": invalid reference format
```

I don't have a `v2.3.1`, so was wondering how to make it just look for the sha, and not tack on the 2.3.1?

Thanks a lot!

**Comment by allisonking** [comment]
Okay, I realized there's a `version` field in the Prometheus CRD-- I had been looking for it as a flag to pass into the operator. 

Does the version have to have a tag that follows semver? I'm using my sha as the version but the statefulset isn't being created and I get the error: 
```
E0724 21:51:29.144520       1 operator.go:651] Sync "default/main" failed: creating config failed: generating config failed: parse version: No Major.Minor.Patch elements found
```

Thanks for the guidance!

**Comment by brancz** [comment]
Yes that's the expectation today, if you cannot control the tag used, then you can use the `tag` field to specify a different tag. That said, I think using the exact sha is a lot more sane than tags, so I think it would be nice to add a `sha` field, to make this possible as well. The question is what should happen if one specifies both? I would probably say, if a `sha` is specified then that has precedence over `tag` as it's more exact.

**Comment by brancz** [comment]
I'll close this here, but will make sure to open an issue to track the ability to use the sha directly.
