### ISSUE TITLE
Target is disappearing,when deployment is deleted.

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1648]
**What did you do?**
Created servicemonitor and serviceaccount for an application. All are listed in Prometheus target and was working fine. But now when I delete the application the target is not showing the status down and the same target is disappearing from the Prometheus target. Please let me know How can I trouble shoot the issue
**What did you expect to see?**
Need to show the target down in Prometheus target section.
**What did you see instead? Under which circumstances?**
when I delete the application the target is not showing the status down and the same target is disappearing from the Prometheus target.
**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
Please let me know which pods logs should I check.

**Comment by brancz** [comment]
This is the correct behavior. When targets disappear from discovery, they simply disappear. What you can do to alert on something like targets unexpectedly disappearing from discovery, is you can use the `absent` function and do something like:

```
absent(up{job="my-web-app"} == 1)
```

That query would alert you if either all targets are down or all of them have disappeared from target discovery.

As this is not an issue with Prometheus or the Prometheus Operator I will close this here, but feel free to continue to comment should you have further questions, or open a new issue should you think you have found an issue.

**Comment by manuprometheus** [comment]
Sorry, I think you misunderstood my question.  I will explain it briefly. When my pod is running, then the service discovery will fetch it and shows the correct Target label. also the metrics are fetched on the target and shows the status "up". But when I delete the pod  for testing, then the target is disappearing from the target section instead of showing "down" status. And in Service Discovery, it is showing dropped status in " Target Labels".

**Comment by manuprometheus** [comment]
The same is happening for all the target including "kube-state-metrics","kubelet" etc..

**Comment by brancz** [comment]
> And in Service Discovery, it is showing dropped status in " Target Labels".

Could you share a screenshot of this? I think you may just be looking at those service discovery entries that are intended to drop that target.

If you delete a Pod, it disappears from the targets, that is the correct behavior. How is Prometheus supposed to know whether you are doing a rolling deployment or you are deleteing Pods? It just sees targets. If targets don't respond, they are down, but if discovery tells Prometheus that a Pod is gone, it simply won't attempt to scrape it - it's gone. If that's what you want to alert on, then the above expression is what you can use to visualize that it is indeed gone.

**Comment by manuprometheus** [comment]
Hi, Sorry, I missed to inform one point. When the target is down, the endpoint should normally show "down" status. But in this case, the end point itself is disappeared from the prometheus target UI. Please refer the screenshots attached below for my service "admin-backend". In the first two images, you can see the service as "up" in the target and target label for "admin-backend" is shown in the Service Discovery. 
image 1:  https://imgur.com/a/n3kWOz1
image 2: https://imgur.com/a/8ZA9giq

After I have deletd the pod, the endpoint for the service "admin-backend" is disappeared and target label in Service Discovery is showing dropped stattus. Please refer teh screenshots attached.

image 3: https://imgur.com/a/Pa4zXZR
image 4: https://imgur.com/a/HQHyJrz

Please advice on this. :-(

**Comment by brancz** [comment]
Yes that is the correct behavior. It will only show down if there is a Pod and the Pod is not answering, or answering with anything but HTTP 200. Deleting a Pod does not mean it's down, it means you removed it, and therefore Prometheus target discovery will remove it from the list of targets.

**Comment by manuprometheus** [comment]
But earlier, when I deleted a pod, then the Target showed the status down. That's why I got confused.

**Comment by brancz** [comment]
Target discovery with Kubernetes is an eventually consistent system, it may take up to 10 minutes for it to be consistent with the real world picture, that's why you should use the `for` statement in alerting rules.
