### ISSUE TITLE
How to pass '--web.enable-admin-api' flag to prometheus container

### ISSUE THREAD

**Issue by debbiswal** [coreos/prometheus-operator#1654]
I am using Prometheus-Operator release-0.17.
In kube-prometheus/manifests/prometheus/prometheus-k8s.yaml , how do i pass  the flag '--web.enable-admin-api' to prometheus container.

**Comment by brancz** [comment]
Duplicate of #1215. The discussion ended with, we can add a field to the Prometheus object to enable this, but we have to make sure, that there is a noticeable warning, to make sure people are aware what they are doing, as those endpoints can potentially be dangerous.
