### ISSUE TITLE
Alertmanager Configmap requires storing passwords in the plain on disk

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#166]
With prometheus-operator, Alertmanager is configured with a file stored in the configmap. This means passwords and security tokens for alerters get stored in the plain and Kubernetes writes them to disk on any relevant nodes.

Normally I would map secrets like that from k8s secret resource into environment variables in the container. But it appears alertmanager requires secrets get stored in plain text in the config yaml file? If so, perhaps the whole config should be a secret instead? Then k8s will keep it off disk even when mounted in the pod. For this to work the config-reloader would need to be able to watch the secret instead.

(I think both secrets and configmaps have the same size limit of 1MB - imposed by etcd record size limit).

**Comment by brancz** [comment]
IIRC secrets are not remounted on change, but are static for the lifetime of a `Pod`. That would be a problem as reloading the config at runtime is crucial.

**Comment by brancz** [comment]
Not sure what I was remembering, but it doesn't seem like it looking at the documentation.

Under "Mounted Secrets are updated automatically": https://kubernetes.io/docs/user-guide/secrets/

I'm generally fine with this change.

**Comment by fabxc** [comment]
That generally seems like a necessity, yea. If it works just as well, we should go with secrets.
