### ISSUE TITLE
Operator spinning with namespace list error

### ISSUE THREAD

**Issue by smanpathak** [coreos/prometheus-operator#1688]
**What did you do?**
Deployed prometheus-operator with bundle.yaml, followed getting-started guide
**What did you expect to see?**
Prometheus monitoring working 
**What did you see instead? Under which circumstances?**
No objects for prometheus resource, service monitor. Prometheus-operator seems spinning with this message follows in logs section.
**Environment**
Vanilla K8S cluster.
* Prometheus Operator version:
 quay.io/coreos/prometheus-operator:v0.22.2

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Platform9 bare OS K8S
* Manifests:

```
bundle.yaml,  example/user-guides/getting-started/
```

* Prometheus Operator Logs:

```
level=info ts=2018-07-24T23:26:37.259408861Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=default/prometheus
W0724 23:26:37.259456       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0724 23:26:37.259490       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W0724 23:26:37.261229       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
E0724 23:26:37.295559       1 operator.go:651] Sync "default/prometheus" failed: creating config failed: secrets "prometheus-prometheus" not found
```

**Comment by mxinden** [comment]
The second, third and fourth log line is fixed via https://github.com/coreos/prometheus-operator/pull/1697. This does not fix the repeated first log line though. This might be related to https://github.com/coreos/prometheus-operator/issues/1659.
