### ISSUE TITLE
make kube-prometheus Ksonnet create full power ClusterRole

### ISSUE THREAD

**Issue by prune998** [coreos/prometheus-operator#1696]
**What did you do?**
I'm deploying a Prometheus using the Ksonnet templates from kube-prometheus

**What did you expect to see?**
I expect my cluster to be working and scrape metrics from my applications in any `namespace`

**What did you see instead? Under which circumstances?**
By default the `ClusterRole` is created as : 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```
Which allows to gather all the nodes metrics but not the user's `services` or `pods`.

**What would solve the issue**
The `ClusterRole` should enable to scrape metrics from pods/services in any namespace as this is what most people should need. 
Maybe this power enforcement should be enabled by a true/false trigger in the config ? 

In the end, the ClusterRole should look something similar to : 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"prometheus-k8s","namespace":""},"rules":[{"apiGroups":[""],"resources":["nodes/metrics"],"verbs":["get"]},{"nonResourceURLs":["/metrics"],"verbs":["get"]}]}
  creationTimestamp: 2018-07-24T18:45:23Z
  name: prometheus-k8s
  resourceVersion: "19867614"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-k8s
  uid: b928e4d8-8f71-11e8-af1d-42010a8400e0
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
```

**Environment**

* Prometheus Operator version:

	`v0.22.2`

* Kubernetes version information:

	`1.10.5-gke.3`

* Kubernetes cluster kind: 

	GKE

**Comment by prune998** [comment]
I could submit a PR for that, but I would like to have your point on view on this first...

**Comment by prune998** [comment]
Sounds the Helm chart already do that : https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/clusterrole.yaml

```
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - nodes/metrics
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

**Comment by brancz** [comment]
It is intentional, we don't want to grant the Prometheus server essentially the ability to view _any_ pod in a cluster. The intention is that you create a `Role` and `RoleBinding` in each namespace you want to monitor.

**Comment by prune998** [comment]
so it's ok that the Helm chart and the Ksonnet does not behave the same way  ?
Thanks for your answer @brancz 
Maybe it would be good to explain this difference in behaviour in the docs ?

**Comment by brancz** [comment]
The helm charts just haven't been updated that way. The jsonnet files are basically the "upstream" and the helm charts are a downstream and are separately maintained by separate people. Helm is just so wildly popular that we wanted to offer that option, but I recommend the jsonnet way, as that's what we use in production and I can with confidence say that it's very well battle tested.

**Comment by prune998** [comment]
Do you think of a clean way to change the config so that we could add a list of namespaces that Prometheus Server should be able to scrape ? 

How would you do to, let's say, deploy the Operator + a Prom Server that would be allowed to scrape in all namespaces (or in a list) ? Maybe all Namespaces with a specific label ? 
I'm pretty new to Jsonnet so it's clearly not obvious to me.
Thanks @brancz

**Comment by brancz** [comment]
we have a tenancy model where namespaces are hand picked, but I can imagine a world where the tenant is defined by a label on a namespace, and something would deploy the Role and RoleBinding into those namespaces. I would always try to not grant ClusterRoles when not absolutely necessary.

**Comment by prune998** [comment]
so there is no way to `configure` the Jsonnet files to automatically deploy the Role and RoleBinding into those namespaces right now, right ? 
It's a manual step to achieve afterward ?
I just want to be sure before I go on find a solution for that :)

**Comment by brancz** [comment]
I think it would be reasonable to have a list of namespaces in the jsonnet files that generate the Role and RoleBinding for all the namespaces in that list. That has actually been on my list for a while anyways, as we do exactly the same thing already for the `default`, `kube-system` and `monitoring` namespaces. If you are up for it I can guide you through what needs to be done in order for that.

**Comment by prune998** [comment]
Thanks @brancz that would be really kind of you. 
I'm going to dig in the jSonnet code and come back with a PR so you'll be able to comment and guide me to do the right thing.

Things seem to take place in `prometheus_operator/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet` so the goal would be to create a loop from a namespace list that would create many `roles` and `rolebindings` ?

**Comment by brancz** [comment]
> Things seem to take place in prometheus_operator/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet so the goal would be to create a loop from a namespace list that would create many roles and rolebindings ?

Precisely. Let me know if you get stuck, but you're on the right track.

**Comment by prune998** [comment]
So, I'm stuck...

I thought I would add a config parameter like `additionalRoleNamespaces = []`
then iterate over it and generate some more roles in a new file, like : 
```
    roleSpecificNamespace:
        local role = k.rbac.v1.role;
        local policyRule = role.rulesType;
        local coreRule = policyRule.new() +
                        policyRule.withApiGroups(['']) +
                        policyRule.withResources([
                          'nodes',
                          'services',
                          'endpoints',
                          'pods',
                        ]) +
                        policyRule.withVerbs(['get', 'list', 'watch']);
        local newSpecificRole(namespace) = {                
          role.new() +
          role.mixin.metadata.withName('prometheus-' + $._config.prometheus.name) +
          role.mixin.metadata.withNamespace(namespace) +
          role.withRules(coreRule),
        },
        [newSpecificRole(x) for x in $._config.prometheus.additionalRoleNamespaces],
```

but I keep having the error `expected token OPERATOR but got "."` on the line `role.new() +`

I tried in every way without success... I've been reading the jSonnet docs many times but I don't get it...

**Comment by prune998** [comment]
OK GOT IT !!!
I've found https://github.com/google/jsonnet/blob/master/benchmarks/bench.03.jsonnet and changed my code to : 

```
    roleSpecificNamespace:
        local role = k.rbac.v1.role;
        local policyRule = role.rulesType;
        local coreRule = policyRule.new() +
                        policyRule.withApiGroups(['']) +
                        policyRule.withResources([
                          'nodes',
                          'services',
                          'endpoints',
                          'pods',
                        ]) +
                        policyRule.withVerbs(['get', 'list', 'watch']);
        local newSpecificRole(namespace) =                 
          role.new() +
          role.mixin.metadata.withName('prometheus-' + $._config.prometheus.name) +
          role.mixin.metadata.withNamespace(namespace) +
          role.withRules(coreRule);
        
        [newSpecificRole(x) for x in $._config.prometheus.additionalRoleNamespaces],
```

I'll change some vars/function names and do a PR, except if you stop me here :)

**Comment by brancz** [comment]
That looks fantastic. Small suggestion let's just add a `$._config.prometheus.namespaces` and make that default to `["default", "kube-system", $._config.namespace]`. Then people just merge their additional namespaces into that array, that would be a little more idiomatic jsonnet.

**Comment by prune998** [comment]
I've just created a PR including your reco : https://github.com/coreos/prometheus-operator/pull/1708
Feel free to comment.

I found no tests about the jsonnet files... let me know if I missed something

**Comment by brancz** [comment]
As #1708 is merged I'm closing this here. Thanks a lot for the fantastic contribution @prune998! :tada:
