### ISSUE TITLE
alertmanager-kube and prometheus-kube stay in ContainerCreating state forever

### ISSUE THREAD

**Issue by davidrama** [coreos/prometheus-operator#1704]
**What did you do?**
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus -f values2.yaml --namespace monitoring
with:

with values activating persistent storage:
`prometheus[rama]->cat values.yaml
alertmanager:
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: rook-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
      selector: {}

prometheus:
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: rook-block
        accessModes: ["ReadWriteOnce"]
        resources:
         requests:
           storage: 8Gi
      selector: {}`

**What did you expect to see?**

All containers in a Running state

**What did you see instead? Under which circumstances?**
2 pods in ContainerCreating state

prometheus[rama]->kubectl get all -n monitoring

> NAME                                                       READY     STATUS              RESTARTS   AGE
> pod/alertmanager-kube-prometheus-0                         0/2       ContainerCreating   0          5m
> pod/kube-prometheus-exporter-kube-state-67c558b665-99br8   2/2       Running             0          5m
> pod/kube-prometheus-exporter-node-8sqjt                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-hwc44                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-l52qm                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-lktg8                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-lpq5f                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-s672w                    1/1       Running             0          5m
> pod/kube-prometheus-exporter-node-zs7d7                    1/1       Running             0          5m
> pod/kube-prometheus-grafana-57d5b4d79f-4vfdc               2/2       Running             0          5m
> pod/prometheus-kube-prometheus-0                           0/3       ContainerCreating   0          5m
> pod/prometheus-operator-d75587d6-lncgv                     1/1       Running             0          5m

**Environment**

* Prometheus Operator version:

prometheus-operator-0.0.28

* Kubernetes version information:

> prometheus[rama]->kubectl version
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubespray on baremetal (ubuntu Xenial)

* Manifests:

```
prometheus[rama]->helm ls
NAME               	REVISION	UPDATED                 	STATUS  	CHART                     	NAMESPACE
kube-prometheus    	1       	Thu Jul 26 10:38:59 2018	DEPLOYED	kube-prometheus-0.0.103   	monitoring
prometheus-operator	1       	Thu Jul 26 10:38:09 2018	DEPLOYED	prometheus-operator-0.0.28	monitoring
```

* Prometheus Operator Logs:

can't find any relevant.

**Comment by brancz** [comment]
could you share `kubectl get events -n <namespace>` of the namespace you installed this into? Thanks!

**Comment by davidrama** [comment]
https://pastebin.com/nYsdHHZT

**Comment by brancz** [comment]
> Unable to mount volumes for pod "alertmanager-kube-prometheus-0_monitoring(32b268f1-90ae-11e8-abaf-e41d2dae3526)": timeout expired waiting for volumes to attach or mount for pod "monitoring"/"alertmanager-kube-prometheus-0". list of unmounted volumes=[alertmanager-kube-prometheus-db config-volume default-token-vnxkt]. list of unattached volumes=[alertmanager-kube-prometheus-db config-volume default-token-vnxkt]

That sounds like your dynamic provisioning doesn't work properly.

Could you also share `kubectl -n monitoring get pvc`?

**Comment by davidrama** [comment]
prometheus[rama]-> kubectl -n monitoring get pvc
NAME                                                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0   Bound     pvc-5831ea61-90af-11e8-abaf-e41d2dae3526   10Gi       RWO            rook-block     1h
prometheus-kube-prometheus-db-prometheus-kube-prometheus-0       Bound     pvc-5850297c-90af-11e8-abaf-e41d2dae3526   10Gi       RWO            rook-block     1h

**Comment by davidrama** [comment]
with 
prometheus[rama]-> kubectl -n monitoring get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                                                       STORAGECLASS   REASON    AGE
pvc-5831ea61-90af-11e8-abaf-e41d2dae3526   10Gi       RWO            Delete           Bound     monitoring/alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0   rook-block               1h
pvc-5850297c-90af-11e8-abaf-e41d2dae3526   10Gi       RWO            Delete           Bound     monitoring/prometheus-kube-prometheus-db-prometheus-kube-prometheus-0       rook-block               1h

**Comment by brancz** [comment]
Are you using those rook block-devices anywhere else? As in can you validate that it works properly? It sounds like it's timing out waiting for rook to make the volume available. If you can validate that it doesn't work in other cases this is probably an issue for them, rather than here, but let's first validate that.

**Comment by davidrama** [comment]
I'll get back to you ASAP about this will check.

**Comment by davidrama** [comment]
Hello did a clean install and this seems have been related to the storage part.
Now all the pods are up and running. Sorry for the noise and thanks for your time
