### ISSUE TITLE
Are the grafana dashboards reachable over grafana site with an ID

### ISSUE THREAD

**Issue by Tim-Schwalbe** [coreos/prometheus-operator#1709]
Is it possible to import the dashboard which are delivered with kube-prometheus via an ID.
If so, can someone please post all ids here.

**Comment by stealthybox** [comment]
They would need to be frequently uploaded to Grafana's site.
This is currently not happening, but there look to be some clones that have been uploaded by others.

**Comment by stealthybox** [comment]
the source is in this directory of the helm chart:
https://github.com/coreos/prometheus-operator/tree/2b3c255/helm/grafana/dashboards

pinned at ref 2b3c255

**Comment by brancz** [comment]
The IDs are:

```

          "title": "K8s / USE Method / Cluster",
          "uid": "a6e7d1362e1ddbb79db21d5bb40d7137",

          "title": "K8s / USE Method / Node",
          "uid": "4ac4f123aae0ff6dbaf4f4f66120033b",

          "title": "K8s / Compute Resources / Cluster",
          "uid": "efa86fd1d0c121a26444b636a3f509a8",

          "title": "K8s / Compute Resources / Namespace",
          "uid": "85a562078cdf77779eaa1add43ccec1e",

          "title": "K8s / Compute Resources / Pod",
          "uid": "6581e46e4e5c7ba40a07646395ef7b23",

          "title": "Nodes",
          "uid": "fa49a4706d07a042595b664c87fb33ea",

          "title": "Pods",
          "uid": "ab4f13a9892a76a4d21ce8c2445bf4ea",

          "title": "StatefulSets",
          "uid": "a31c1f46e6f727cb37c0d731a7245005",

```

But as @stealthybox said I wonder what you want to do with these IDs, we intentionally deploy the dashboards via files as we can version them that way.
