### ISSUE TITLE
Kube-Prometheus Nodes labeled with IP Address

### ISSUE THREAD

**Issue by mitchellmaler** [coreos/prometheus-operator#1712]
**What did you do?**
Installed kube-prometheus
**What did you expect to see?**
Nodes labeled with their name instead of IP address
**What did you see instead? Under which circumstances?**
IP address of the node name

Is there a way to modify the kube-prometheus deployment to label the nodes using their name instead of IP address without manually modifying the manifests after jb generation?

**Comment by brancz** [comment]
Can you specify in more detail where you expected this? Prometheus will always use an IP for the target. If you are thinking of the Grafana dashboards, then that's just an improvement we need to make to the "Nodes" dashboard, just like we have done for the "K8s / USE Method / Node" dashboard.

Note that targets really should just have the labels that uniquely identify them. Everything else can be added at query time, by joining two metrics onto another.

**Comment by mitchellmaler** [comment]
@brancz Yea I guess I was just expecting to load Prometheus and see each target with its name and not the IP Address. I guess I was worried the node exporter targets and alerts would just say the IP which would make it difficult to know what node was having the issue.

**Comment by brancz** [comment]
If they don't (I believe they don't), then we should add that information by joining the node name onto them in the alert rule expression, just like we do to get additional Pod information in alerts and dashboards.
