### ISSUE TITLE
Grafana (kube-prometheus) API returns 403 for most requests

### ISSUE THREAD

**Issue by markusdresch** [coreos/prometheus-operator#1719]
**What did you do?**
Install coreos prometheus-operator and kube-prometheus helm charts on Azure Kubernetes Service (AKS)
```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring
```
Grafana is exposed using an ingress rule.
**What did you expect to see?**
Nice fancy widgets displaying metrics about everything kubernetes has to offer.
**What did you see instead? Under which circumstances?**
Widgets with a red exclamation mark stating that the API returned 403 Access denied.
**Environment**
Microsoft AKS
* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.20.0
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 
azure shell (AKS)

The only working (out of the box) widget is pod network IO. When i open the pod dashboard and remove all URL parameters named "container" or "container_name" from CPU/Memory widget queries, the metrics are returned. I can't persist those changes though, as POST to /api/dashboards/db/ yields 403 as well.

I also exposed kube-prometheus:9090 using ingress rules and all metrics are available there. Changing the admin password and the organization name works (PUT api/user/password, PUT api/orgs/1).

**Comment by markusdresch** [comment]
a little more debug info, all listed urls return http 403 errors.

## pods dashboard:
`/api/datasources/proxy/1/api/v1/series?match[]=kube_pod_info{namespace=~".*"}&start=1533257470&end=1533279070`
> removing `namespace=~".*"` returns data ok

`/api/datasources/proxy/1/api/v1/query_range?query=sum by(container_name) (container_memory_usage_bytes{pod_name="undefined", container_name=~"$container", container_name!="POD"})&start=1533257470&end=1533279070&step=15`
> removing `container_name=~"$container", container_name!="POD"` returns data ok

`/api/datasources/proxy/1/api/v1/query_range?query=sum by (container_name)(rate(container_cpu_usage_seconds_total{image!="",container_name!="POD",pod_name="undefined"}[1m]))&start=1533257470&end=1533279070&step=30`
> removing `image!="",container_name!="POD"` returns data ok

### on select pods namespace:
`/api/datasources/proxy/1/api/v1/series?match[]=kube_pod_container_info{namespace="monitoring", pod="kube-prometheus-exporter-node-pskw2"}&start=1533257871&end=1533279471`
> removing `namespace="monitoring"` returns data ok

## deployments, statefulsets dashboards:
nothing works

## nodes dashboard:
```
/api/datasources/proxy/1/api/v1/query_range?query=node_memory_Cached{instance="10.240.0.6:9100"}&start=1533275975&end=1533279575&step=30
/api/datasources/proxy/1/api/v1/query_range?query=node_memory_MemFree{instance="10.240.0.6:9100"}&start=1533275975&end=1533279575&step=30
/api/datasources/proxy/1/api/v1/query_range?query=sum by (instance) (rate(node_disk_bytes_read{instance="10.240.0.6:9100"}[2m]))&start=1533275975&end=1533279575&step=60
/api/datasources/proxy/1/api/v1/query_range?query=sum by (instance) (rate(node_disk_bytes_written{instance="10.240.0.6:9100"}[2m]))&start=1533275975&end=1533279575&step=60
/api/datasources/proxy/1/api/v1/query_range?query=sum by (instance) (rate(node_disk_io_time_ms{instance="10.240.0.6:9100"}[2m]))&start=1533275975&end=1533279575&step=60
/api/datasources/proxy/1/api/v1/query_range?query=rate(node_network_receive_bytes{instance="10.240.0.6:9100",device!~"lo"}[5m])&start=1533275975&end=1533279575&step=30
/api/datasources/proxy/1/api/v1/query_range?query=rate(node_network_transmit_bytes{instance="10.240.0.6:9100",device!~"lo"}[5m])&start=1533275975&end=1533279575&step=30
/api/datasources/proxy/1/api/v1/query_range?query=((node_memory_MemTotal{instance="10.240.0.6:9100"} - node_memory_MemFree{instance="10.240.0.6:9100"}  - node_memory_Buffers{instance="10.240.0.6:9100"} - node_memory_Cached{instance="10.240.0.6:9100"}) / node_memory_MemTotal{instance="10.240.0.6:9100"}) * 100&start=1533275975&end=1533279575&step=60
```
> removing `instance="10.240.0.6:9100"` returns data ok

`/api/datasources/proxy/1/api/v1/query_range?query=(sum(node_filesystem_size{device!="rootfs",instance="10.240.0.6:9100"}) - sum(node_filesystem_free{device!="rootfs",instance="10.240.0.6:9100"})) / sum(node_filesystem_size{device!="rootfs",instance="10.240.0.6:9100"})&start=1533275975&end=1533279575&step=60`
> no way to make this one return data.

## kubernetes cluster health, status, resource request etc. dashboards:
nothing works, partially due to managed apiserver on AKS i guess... although many queries like node_filesystem_size etc. are available in prometheus.

**Comment by slnowak** [comment]
@markusdresch did you manage to fix it? I think we're getting the same issue - however it happens on Amazon EKS instead of Azure.

**Comment by markusdresch** [comment]
@slnowak unfortunately not. also didn't get any response on the grafana forums. switched to azure omsagent in the meantime.

**Comment by slnowak** [comment]
Turned out in our case it was too restrictive AWS WAF rules - it considers prometheus query as an sql injection attempt.

**Comment by markusdresch** [comment]
oh that sounds reasonable. had an application gateway with OWASP firewall in front as well, so this might have been the issue.

**Comment by hoiama** [comment]
To resolve issues with Grafana requests being blocked due to large request bodies, follow these steps:

    1- Go to the AWS Management Console.
    2-Search for WAF and navigate to the Web ACLs section.
    3-Locate and select the Web ACL associated with your application.
    4-Under Rules, find the AWS-AWSManagedRulesCommonRuleSet rule group.
    5-Edit this rule group and locate the rule named SizeRestrictions_BODY.
    6-Change its action to Override to Count.

This modification prevents the SizeRestrictions_BODY rule from outright blocking requests with large bodies, such as those generated by Grafana, while still allowing you to monitor their occurrences in logs.
