### ISSUE TITLE
Deploying whole stacks with exporters: operator, operator+bash or helm?

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#172]
I just finished [simple automated deployment/update, display, delete scripts](https://github.com/whereisaaron/kubernetes-prometheus-operator-deployment) for a stack consisting of:
- prometheus-operator with RBAC
- 'main' Prometheus with ConfigMap, RBAC, TLS Ingress, DNS CNAME, and Basic Auth
- 'main' Alertmanger with ConfigMap, RBAC (no access), TLS Ingress, DNS CNAME, and Basic Auth
- kube-state metrics Deployment with RBAC
- node-extractor DaemonSet with RBACS (no access)

I just did this with simple `bash` scripts, `kubectl`, `envsubst`, and `cli53`, based on many of the manifest examples here. I am deploying this to clusters from CI/CD and using it for alerts and as a datasource for Grafana.

I am decently happy with it, I see the main limitations currently being security:
- Prometheus and Alertmanager Pods have no TLS or auth within the cluster - could be fixed with an haproxy sidecar
- Alarmmonitor receivers have passwords in the plain in the ConfigMap - could be changed to use a Secret
- Metrics end-points for exporters are have no authentication - not sure if this can be easily fixed without sidecars on everything?

The stable ['prometheus' chart](https://github.com/kubernetes/charts/tree/master/stable/prometheus) for helm is not dissimilar from what prometheus-operator and my script is doing. Except prometheus-operator does more to simplify updating the Prometheus scraping configuration with ServiceMonitors.

Do you see prometheus-operator eventually doing all of the above for me (everything my script does), or do you see prometheus-operator maybe be part of a [helm chart](https://github.com/kubernetes/helm) or similar. E.g. where prometheus-operator focuses on active management of the configuration files, and the helm chart provides the supplemental resources like exporters and Services/Ingresses?

**Comment by brancz** [comment]
Such an effort exists in [kube-prometheus](https://github.com/coreos/kube-prometheus) and there is work moving it to a helm chart by one of the helm chart maintainers: https://github.com/mgoodness/kube-prometheus-charts

As this is alpha software, so is the helm chart, everything is subject to change, therefore we will not be pushing for getting it into stable helm charts just yet.

**Comment by whereisaaron** [comment]
Thanks for the pointers @brancz. Regarding 'kube-prometheus', I didn't look at it earlier (but should have) because I didn't realize it used 'prometheus-operator'. The README section with 'vs' made it appear to be an alternative to 'prometheus-operator'.

> **Prometheus Operator vs. kube-prometheus**
The Prometheus Operator makes the Prometheus configuration Kubernetes native and manages and operates Prometheus and Alertmanager clusters. It is a piece of the puzzle regarding full end-to-end monitoring.
*kube-prometheus is a collection of manifests to help getting started with monitoring Kubernetes itself and applications running on top of it.*

Maybe it could be explicit about that? e.g.

> kube-prometheus combines Prometheus Operator with a collection of manifests to help getting started with monitoring Kubernetes itself and applications running on top of it.

**Comment by brancz** [comment]
Very true, thanks for pointing that out! The README was adapted in #177 :slightly_smiling_face:

**Comment by brancz** [comment]
With scripts being available in `contrib/kube-prometheus/hack/cluster-monitoring` and the [helm chart](https://github.com/mgoodness/kube-prometheus-charts) being actively developed do you think we can close this issue? Do you think we should add additional documentation linking to the two?

**Comment by whereisaaron** [comment]
Sure. I'd like helm charts to include RBAC and network policies. But that is for those projects to cover.

**Comment by brancz** [comment]
Definitely! I'm sure @mgoodness is all for stabilizing the chart along with the Prometheus Operator itself. RBAC, network policies, etc all go along with that in my opinion. Keep the good feedback coming @whereisaaron, always appreciated! :slightly_smiling_face:

**Comment by mgoodness** [comment]
I've not had a need/opportunity to work with RBAC or network policies yet, which is why my charts currently don't address those mechanisms. They are about to become areas of great interest to me, though, so expect to see the charts improve very soon.

And I'm *very* open to issues & PRs!

**Comment by brancz** [comment]
As a heads up rbac rules are already [in this repository](https://github.com/coreos/prometheus-operator/tree/master/example/rbac) and there is [documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/rbac.md) for it. And a [PR for adding network policies](https://github.com/coreos/prometheus-operator/pull/156) is already open, it's currently lacking documentation, but the network policies are a start!

If everyone agrees I would like to keep this repository complete in all of those things RBAC rules, network policies, etc. Then [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) is a complete deployment ready opinionated batteries included manifest collection and script. The helm chart I see as an important part as it makes kube-prometheus configurable as in batteries included, but exchangeable :slightly_smiling_face: .
