### ISSUE TITLE
How to change alertmanager securityContext

### ISSUE THREAD

**Issue by camrossi** [coreos/prometheus-operator#1735]
**What did you do?**
I installed prometheus via Helm.
Alertmanager is not starting due to permission issues. I narrow it down to the default securityContext configuration not being correct. I need to run it as root. 
I first tried to edit (kubect edit) the Alertmanager stateful set but any changes I made there are not applied. 
From the documentation and some other issues that are open I think I need to use jsonnet to change this parameter but after 2h I just gave up. I can't understand how to do it. 

**What did you expect to see?**
Ability to change Stateful set config.

**What did you see instead? Under which circumstances?**
Steteful set config is reverted back. 
**Environment**

* Prometheus Operator version:

quay.io/coreos/prometheus-operator                               v0.20.0

* Kubernetes version information:

cisco@k8s-01:~/prometheus/vendor/prometheus-operator$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubespray

**Comment by brancz** [comment]
There is .spec.securityContext in the Alermanager object, you can use that to explicitly set that you want to run as root, however that is definitely not recommended to do.

**Comment by brancz** [comment]
The Prometheus Operator registers new resources, meaning that similar to the StatefulSet there is now an Alertmanager type in Kubernetes. So to edit that you just do

kubectl -n monitoring edit alertmanager-main

I think that error that you’re seeing is not coming from the Alertmanager itself though. I think there is something wrong with your cluster.

**Comment by camrossi** [comment]
It was that simple... thank you! 

After changing it it works perfectly fine now the permission error is gone. 
It might have to do with the CNI plugin that we are using, I was trying to get this working so our developers can see the working vs non working situation! 

Again thank you a lot!
