### ISSUE TITLE
Kubelet (1/2) Up

### ISSUE THREAD

**Issue by salman-hayder** [coreos/prometheus-operator#1741]
I am trying to implement prometheus but grafana not showing all graphs, it shows Data Points not Available, I checked targets through Prometheus and its showing error for one kubelet service, getsockopt: connection refused, in targets execpt this, every service is up.
![ss](https://user-images.githubusercontent.com/40059719/43639806-e23349d4-9736-11e8-949e-af5c42c881ec.png)
I tried alot but unable to solve this issue, kubelet restarted but still same issue.

**Comment by brancz** [comment]
The insecure cAdvisor port has been disabled by default for some time, is now deprecated and even removed in latest versions of Kubernetes. You should use the secure version under `/metrics/cadvisor` under the main kubelet http server.

**Comment by yanhongwang** [comment]
Hello @brancz 

I also met the similar **kubernetes-cadvisor** error within Prometheus under Kubernetes **1.11.3**

http://xx.xx.xx.xx:4194/metrics | down | Get http://xx.xx.xx.xx:4194/metrics: dial tcp xx.xx.xx.xx:4194: getsockopt: connection refused

What do you mean the secure version under main kubelet http server?
How to fix this connection refused problem?

Thanks very much.

**Comment by brancz** [comment]
The `:10250` port of the kubelet is https and requires authentication and authorization, that's what I mean by the secure one :slightly_smiling_face: .

**Comment by victorboissiere** [comment]
How to do I update the cadvisor endpoint to `/metrics/cadvisor` ? By default is still use the old port with `metrics` ?
GKE 1.11

**Comment by vrathore18** [comment]
Facing the same issue

**Comment by thamaraiselvam** [comment]
Same here. How to update cadvisor endpoint?
