### ISSUE TITLE
introduce releases for kube-prometheus dependencies

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1754]
I'm creating this issue is per [this comment](
https://github.com/coreos/prometheus-operator/issues/1731#issuecomment-409715453) (about relatively soon starting to do releases for [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)) that was written by @brancz .

I'd like to be able to do a command (e.g. `jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus/@v0.22.0`) to install a specific release/version of kube-prometheus, and also get a corresponding version (not the latest off master) for not only `kubernetes-mixin` but for each of the dependencies of kube-prometheus (currently [kube-prometheus/jsonnetfile.json](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json) specifies `"version": "master"` for all of the dependencies except [prometheus-operator](https://github.com/coreos/prometheus-operator)).

I'd like this so that at any point I can run such a command and then use it to generate manifests and be guaranteed that (as long as I don't have a syntax error in my own `*.jsonnet` file :) ) [build.sh](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/build.sh) will always complete successfully.

**Comment by jolson490** [comment]
hi @brancz . I'm wondering what do you think about this issue?

**Comment by brancz** [comment]
Yes I generally agree, there are some difficulties around this however, primarily that only git repos can be package sources which makes it difficult to publish versions of the etcd mixin for example. Also I know that the Kubernetes mixin still has some todos for control plane dashboards, then however I can see a 0.1.0 for the Kubernetes mixin.

**Comment by jolson490** [comment]
This issue has been resolved - we now have https://github.com/coreos/kube-prometheus/releases/tag/v0.1.0
