### ISSUE TITLE
jb install doesn't get the specified prometheusOperator version

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1757]
Currently on https://quay.io/repository/coreos/prometheus-operator?tab=tags the newest tag is v0.22.2 (but I noticed it looks like 0.23.0 is about to be [cut](https://github.com/coreos/prometheus-operator/commit/c740d3a#diff-82fad0038871d3e9af1baf18e5082567)).

The [copy of prometheus-operator.libsonnet on the v0.22.2 release/branch](https://github.com/coreos/prometheus-operator/blob/v0.22.2/jsonnet/prometheus-operator/prometheus-operator.libsonnet#L8) specifies `prometheusOperator: 'v0.22.2',`. (And the [v0.22.0 copy](https://github.com/coreos/prometheus-operator/blob/v0.22.0/jsonnet/prometheus-operator/prometheus-operator.libsonnet#L8) specifies `v0.22.0`.)

I did a `jb install` of `@v0.22.0`...:
```
~/tmp/jb
josh@MyMac$ mkdir v0.22.0
~/tmp/jb
josh@MyMac$ cd $_
~/tmp/jb/v0.22.0
josh@MyMac$ jb init
~/tmp/jb/v0.22.0
josh@MyMac$ jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus/@v0.22.0

Cloning into 'vendor/.tmp/jsonnetpkg-kube-prometheus-v0.22.0140722120'...
remote: Counting objects: 35586, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 35586 (delta 20), reused 34 (delta 15), pack-reused 35521
Receiving objects: 100% (35586/35586), 51.18 MiB | 10.12 MiB/s, done.
Resolving deltas: 100% (19766/19766), done.
Checking out files: 100% (6501/6501), done.
Note: checking out 'v0.22.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 11469474 Merge pull request #1597 from mxinden/cut-0.22.0

Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master617343111'...
remote: Counting objects: 2487, done.
remote: Total 2487 (delta 0), reused 0 (delta 0), pack-reused 2487
Receiving objects: 100% (2487/2487), 1.96 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (931/931), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-kubernetes-mixin-master245271610'...
remote: Counting objects: 383, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 383 (delta 10), reused 11 (delta 4), pack-reused 359
Receiving objects: 100% (383/383), 4.88 MiB | 6.35 MiB/s, done.
Resolving deltas: 100% (210/210), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-grafonnet-master624218193'...
remote: Counting objects: 961, done.
remote: Total 961 (delta 0), reused 0 (delta 0), pack-reused 960
Receiving objects: 100% (961/961), 300.33 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (545/545), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-grafana-builder-master406795644'...
remote: Counting objects: 4713, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 4713 (delta 3), reused 5 (delta 3), pack-reused 4703
Receiving objects: 100% (4713/4713), 13.38 MiB | 5.74 MiB/s, done.
Resolving deltas: 100% (1323/1323), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-grafana-master672716971'...
remote: Counting objects: 406, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 406 (delta 3), reused 14 (delta 3), pack-reused 387
Receiving objects: 100% (406/406), 109.02 KiB | 858.00 KiB/s, done.
Resolving deltas: 100% (180/180), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-grafonnet-master421415950'...
remote: Counting objects: 961, done.
remote: Total 961 (delta 0), reused 0 (delta 0), pack-reused 960
Receiving objects: 100% (961/961), 300.33 KiB | 1.47 MiB/s, done.
Resolving deltas: 100% (545/545), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master878828565'...
remote: Counting objects: 2487, done.
remote: Total 2487 (delta 0), reused 0 (delta 0), pack-reused 2487
Receiving objects: 100% (2487/2487), 1.96 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (931/931), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-prometheus-operator-master464282224'...
remote: Counting objects: 35586, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 35586 (delta 20), reused 34 (delta 15), pack-reused 35521
Receiving objects: 100% (35586/35586), 51.18 MiB | 7.58 MiB/s, done.
Resolving deltas: 100% (19766/19766), done.
Checking out files: 100% (6501/6501), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master945903887'...
remote: Counting objects: 2487, done.
remote: Total 2487 (delta 0), reused 0 (delta 0), pack-reused 2487
Receiving objects: 100% (2487/2487), 1.96 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (931/931), done.
Already on 'master'
Your branch is up to date with 'origin/master'.

Cloning into 'vendor/.tmp/jsonnetpkg-etcd-mixin-master505274146'...
remote: Counting objects: 82201, done.
remote: Total 82201 (delta 0), reused 0 (delta 0), pack-reused 82201
Receiving objects: 100% (82201/82201), 42.49 MiB | 9.90 MiB/s, done.
Resolving deltas: 100% (52388/52388), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
```

Note that the key lines in that ^ output from `jb install` are:
 * `HEAD is now at 11469474 Merge pull request #1597 from mxinden/cut-0.22.0`
 * `Already on 'master'` (in the `Cloning into 'vendor/.tmp/jsonnetpkg-prometheus-operator-master464282224'...` section)

...but the problem is that `v0.23.0` (not `v0.22.0`) is in `prometheus-operator.libsonnet`:
```
~/tmp/jb/v0.22.0
josh@MyMac$ find . -name prometheus-operator.libsonnet
./vendor/prometheus-operator/prometheus-operator.libsonnet
~/tmp/jb/v0.22.0
josh@MyMac$ grep 'prometheusOperator:' ./vendor/prometheus-operator/prometheus-operator.libsonnet
      prometheusOperator: 'v0.23.0',
      prometheusOperator: 'quay.io/coreos/prometheus-operator',
```

By the way, I found this issue by trying to use this `vendor/` folder to create `manifests/` and then trying to do `kubectl create -f manifests/ || true` but I encountered this:
```
core@ip-192-168-213-199 ~ $ kubectl get pods -n monitoring | grep -v Running
NAME                                   READY     STATUS             RESTARTS   AGE
prometheus-operator-79f799ff6d-9b2dg   0/1       ImagePullBackOff   0          33m
core@ip-192-168-213-199 ~ $ kubectl -n monitoring logs prometheus-operator-79f799ff6d-9b2dg
Error from server (BadRequest): container "prometheus-operator" in pod "prometheus-operator-79f799ff6d-9b2dg" is waiting to start: trying and failing to pull image
core@ip-192-168-213-199 ~ $ kubectl describe pod -n monitoring prometheus-operator-79f799ff6d-9b2dg | grep "Image:"
    Image:         quay.io/coreos/prometheus-operator:v0.23.0
```

If I'm doing the `jb install` command incorrectly, please let me know the correct way to get a given release of prometheus-operator/kube-prometheus; I also tried the following (i.e. `@release-0.22` - which I noticed by clicking the "Branch:" drop-down menu on [this page](https://github.com/coreos/prometheus-operator/blob/master/jsonnet/prometheus-operator/prometheus-operator.libsonnet)) but that doesn't work at all:
```
~/tmp/jb
josh@MyMac$ mkdir release-0.22
~/tmp/jb
josh@MyMac$ cd $_
~/tmp/jb/release-0.22
josh@MyMac$ jb init
~/tmp/jb/release-0.22
josh@MyMac$ jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus/@release-0.22
Cloning into 'vendor/.tmp/jsonnetpkg-kube-prometheus-release-0.22283057921'...
remote: Counting objects: 35586, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 35586 (delta 20), reused 34 (delta 15), pack-reused 35522
Receiving objects: 100% (35586/35586), 51.13 MiB | 12.06 MiB/s, done.
Resolving deltas: 100% (19763/19763), done.
Checking out files: 100% (6501/6501), done.
Branch 'release-0.22' set up to track remote branch 'release-0.22' from 'origin'.
Switched to a new branch 'release-0.22'
...
~/tmp/jb/release-0.22
josh@MyMac$ grep 'prometheusOperator:' ./vendor/prometheus-operator/prometheus-operator.libsonnet
      prometheusOperator: 'v0.23.0',
      prometheusOperator: 'quay.io/coreos/prometheus-operator',
```

Please let me know if this issue should instead be created in: https://github.com/jsonnet-bundler/jsonnet-bundler

**Comment by brancz** [comment]
As I mentioned on the other thread, this is all as intended. The kube-prometheus project is an entirely separate project and does not follow versions of the prometheus operator at all. Version tags on this repo have no meaning of stability or even cross versions. In fact it is intentional that the prometheus operator and kube-prometheus project have disjunct versions, as we are intending to extract the kube-prometheus project into a separate repository, from where we will eventually be doing versioned releases, but for now kube-prometheus is an unversioned and unstable collection of jsonnet code.

**Comment by jolson490** [comment]
Thank you very much Frederic for your response here and on [the other thread](https://github.com/coreos/prometheus-operator/issues/1743#issuecomment-411032977).

Even if kube-prometheus currently isn't versioned, the thing that tripped me up here is the [*: cut 0.23.0](https://github.com/coreos/prometheus-operator/commit/c740d3a) commit has been merged to master, but `v0.23.0` doesn't yet exist on https://quay.io/repository/coreos/prometheus-operator?tab=tags

Is it correct to expect to be able to `jb install` anytime and have it produce manifests that are usable? i.e. should the master branch always be usable?
If not, then I think I'll have to go back to checking in a known working copy of manifests to my own code repository (and each time I re-deploy kube-prometheus I'll have my own modified copy of [build.sh](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/build.sh) that doesn't do `rm -rf manifests` but rather re-generates only the manifests files that I need to customize).

**Comment by brancz** [comment]
> Even if kube-prometheus currently isn't versioned, the thing that tripped me up here is the *: cut 0.23.0 commit has been merged to master, but v0.23.0 doesn't yet exist on https://quay.io/repository/coreos/prometheus-operator?tab=tags

That a combination of you following the project very closely and us not finishing the release process yesterday, we are finishing the release as we speak. :slightly_smiling_face: 

> Is it correct to expect to be able to jb install anytime and have it produce manifests that are usable? i.e. should the master branch always be usable?

This is true if you are checking in your lockfile, which you should do to have reproducible builds. Otherwise this will never be true, even with versioned packages the versions are going to be able to be specified with version constraints so it's intended for you to explicitly update dependencies and install them consistently through locking.

**Comment by jolson490** [comment]
Sounds good, thanks.
I do indeed check in my `jsonnetfile.lock.json`.
So I believe we're all good here - nothing further for this issue - you can please feel free to close this issue #1757. (Anything further about this general topic of releases is covered by #1754.)

**Comment by brancz** [comment]
Perfect! :slightly_smiling_face:
