### ISSUE TITLE
prometheus-operator fails in kubernetes version 1.11.0 but works in 1.11.1

### ISSUE THREAD

**Issue by Josbrafe** [coreos/prometheus-operator#1758]
Kindly assist.
Prometheus-operator fails on kube version 1.11.0 but works in 1.11.1:
failure error:
iled to list *v1.Service: services is forbidden: User \"system:serviceaccount:default:default\" cannot list services in the namespace \"default\""
level=error ts=2018-08-06T20:10:12.825066997Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods in the namespace \"default\""

failed version:
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

working version: 

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

prometheus-operator version: 21 
used on both clusters.

[root@kubeletmaster kube]# kubectl logs prometheus-operator-6b6459cdc7-g54wp 
level=info ts=2018-08-06T19:27:05.424948862Z caller=operator.go:292 component=prometheusoperator msg="connection established" cluster-version=v1.11.1
level=info ts=2018-08-06T19:27:05.424987519Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.11.1
level=info ts=2018-08-06T19:27:05.805108068Z caller=operator.go:560 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-08-06T19:27:05.903898592Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-08-06T19:27:05.922908662Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-08-06T19:27:05.985785046Z caller=operator.go:1125 component=prometheusoperator msg="CRD created" crd=PrometheusRule
level=info ts=2018-08-06T19:27:08.822257041Z caller=operator.go:186 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T19:27:15.032524972Z caller=operator.go:306 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T20:07:45.664976408Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:45.732145981Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:45.802617131Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:45.978360333Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.011139033Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.157119153Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.275295286Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.404764143Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.431583844Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.577902039Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.618099469Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.654095493Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.768988073Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.907290483Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:46.935083692Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.055883559Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.143998454Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.259287508Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.279301155Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.399406092Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.474961033Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.533879478Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:47.615561783Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus

kubectl logs prometheus-operator-6b6459cdc7-v6ppt |head -20
level=info ts=2018-08-06T19:33:04.176816621Z caller=operator.go:292 component=prometheusoperator msg="connection established" cluster-version=v1.11.0
level=info ts=2018-08-06T19:33:04.249648804Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.11.0
level=info ts=2018-08-06T19:33:04.653295425Z caller=operator.go:560 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-08-06T19:33:04.65477744Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-08-06T19:33:04.665586226Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-08-06T19:33:04.756561803Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-08-06T19:33:07.655639323Z caller=operator.go:186 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T19:33:13.762567498Z caller=operator.go:306 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T20:07:26.609246596Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.750055981Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.767879317Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.848786929Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.865831524Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.882687443Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.949233911Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.967223997Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.049375251Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.068426204Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.08576563Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.149406214Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus

below are the service jobs ran on both cluster:

[root@kubeletmaster kube]# cat serviceMonitorSelector.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
[root@kubeletmaster kube]# cat example-app.yaml 
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 8080
[root@kubeletmaster kube]# cat svc-example.yaml 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
[root@kubeletmaster kube]# cat serviceaccount.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
[root@kubeletmaster kube]# cat clusterrole.yaml 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: default
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - configmaps
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
[root@kubeletmaster kube]# cat clusterrolebinding.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
[root@kubeletmaster kube]# cat servicemonitor.yaml 
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
[root@kubeletmaster kube]# cat prometheus_nodeport.yaml 
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
[root@kubeletmaster kube]# 

failed cluster:

kubectl get all --namespace=default 
NAME                                       READY     STATUS    RESTARTS   AGE
pod/example-app-94c8bc8-6pcvj              1/1       Running   0          22m
pod/example-app-94c8bc8-cjdgz              1/1       Running   0          22m
pod/example-app-94c8bc8-l7cqx              1/1       Running   0          22m
pod/prometheus-operator-6b6459cdc7-v6ppt   1/1       Running   0          54m
pod/prometheus-prometheus-0                3/3       Running   1          18m

NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/example-app           ClusterIP   10.108.7.48      <none>        8080/TCP         21m
service/kubernetes            ClusterIP   10.96.0.1        <none>        443/TCP          83d
service/prometheus            NodePort    10.103.128.164   <none>        9090:30900/TCP   17m
service/prometheus-operated   ClusterIP   None             <none>        9090/TCP         18m

NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-app           3         3         3            3           22m
deployment.apps/prometheus-operator   1         1         1            1           54m

NAME                                             DESIRED   CURRENT   READY     AGE
replicaset.apps/example-app-94c8bc8              3         3         3         22m
replicaset.apps/prometheus-operator-6b6459cdc7   1         1         1         54m

NAME                                     DESIRED   CURRENT   AGE
statefulset.apps/prometheus-prometheus   1         1         18m

working cluster:

[root@kubeletmaster kube]# kubectl get all --namespace=default 
NAME                                       READY     STATUS             RESTARTS   AGE
pod/example-app-94c8bc8-4xrvd              1/1       Running            0          23m
pod/example-app-94c8bc8-fvf2z              0/1       ImagePullBackOff   0          23m
pod/example-app-94c8bc8-gtns8              0/1       ImagePullBackOff   0          23m
pod/prometheus-operator-6b6459cdc7-g54wp   1/1       Running            0          1h
pod/prometheus-prometheus-0                3/3       Running            1          19m

NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/example-app           ClusterIP   10.98.37.147    <none>        8080/TCP         22m
service/kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP          1d
service/prometheus            NodePort    10.110.35.171   <none>        9090:30900/TCP   19m
service/prometheus-operated   ClusterIP   None            <none>        9090/TCP         19m

NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-app           3         3         3            1           23m
deployment.apps/prometheus-operator   1         1         1            1           1h

NAME                                             DESIRED   CURRENT   READY     AGE
replicaset.apps/example-app-94c8bc8              3         3         1         23m
replicaset.apps/prometheus-operator-6b6459cdc7   1         1         1         1h

NAME                                     DESIRED   CURRENT   AGE
statefulset.apps/prometheus-prometheus   1         1         19m
[root@kubeletmaster kube]# 

Kind Regards,
Joseph

**Comment by brancz** [comment]
Just making sure I understand correctly. The logs wit the errors that you shared, are those from the Prometheus pod or the Prometheus Operator pod?

**Comment by Josbrafe** [comment]
Those are the logs from the Prometheus pod for kubernetes version 1.11.0.

**Comment by Josbrafe** [comment]
error log from prometheus-prometheus-0 pod on kube 1.11.0:
iled to list *v1.Service: services is forbidden: User "system:serviceaccount:default:default" cannot list services in the namespace "default""
level=error ts=2018-08-06T20:10:12.825066997Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default""

log from the prometheus-operator on kube 1.11.0:
kubectl logs prometheus-operator-6b6459cdc7-v6ppt |head -20
level=info ts=2018-08-06T19:33:04.176816621Z caller=operator.go:292 component=prometheusoperator msg="connection established" cluster-version=v1.11.0
level=info ts=2018-08-06T19:33:04.249648804Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.11.0
level=info ts=2018-08-06T19:33:04.653295425Z caller=operator.go:560 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-08-06T19:33:04.65477744Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-08-06T19:33:04.665586226Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-08-06T19:33:04.756561803Z caller=operator.go:1132 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-08-06T19:33:07.655639323Z caller=operator.go:186 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T19:33:13.762567498Z caller=operator.go:306 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-08-06T20:07:26.609246596Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.750055981Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.767879317Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.848786929Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.865831524Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.882687443Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.949233911Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:26.967223997Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.049375251Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.068426204Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.08576563Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus
level=info ts=2018-08-06T20:07:27.149406214Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=default/prometheus

**Comment by Josbrafe** [comment]
This is the details from cluster 1.11.0:

kubectl -n default get pod prometheus-prometheus-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-08-06T20:07:26Z
  generateName: prometheus-prometheus-
  labels:
    app: prometheus
    controller-revision-hash: prometheus-prometheus-7847c856c7
    prometheus: prometheus
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-0
  name: prometheus-prometheus-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: prometheus-prometheus
    uid: 56ee2f05-99b4-11e8-9969-0050569bb90b
  resourceVersion: "11680004"
  selfLink: /api/v1/namespaces/default/pods/prometheus-prometheus-0
  uid: 56f0ce08-99b4-11e8-9969-0050569bb90b
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention=24h
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --web.route-prefix=/
    image: quay.io/prometheus/prometheus:v2.2.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /-/healthy
        port: web
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    name: prometheus
    ports:
    - containerPort: 9090
      name: web
      protocol: TCP
    readinessProbe:
      failureThreshold: 120
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        memory: 400Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus/config_out
      name: config-out
      readOnly: true
    - mountPath: /etc/prometheus/rules
      name: rules
    - mountPath: /prometheus
      name: prometheus-prometheus-db
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-v6j5p
      readOnly: true
  - args:
    - --reload-url=http://localhost:9090/-/reload
    - --config-file=/etc/prometheus/config/prometheus.yaml
    - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    command:
    - /bin/prometheus-config-reloader
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: quay.io/coreos/prometheus-config-reloader:v0.20.0
    imagePullPolicy: IfNotPresent
    name: prometheus-config-reloader
    resources:
      limits:
        cpu: 10m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus/config
      name: config
    - mountPath: /etc/prometheus/rules
      name: rules
    - mountPath: /etc/prometheus/config_out
      name: config-out
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-v6j5p
      readOnly: true
  - args:
    - --webhook-url=http://localhost:9090/-/reload
    - --volume-dir=/etc/prometheus/rules
    image: quay.io/coreos/configmap-reload:v0.0.1
    imagePullPolicy: IfNotPresent
    name: alerting-rule-files-configmap-reloader
    resources:
      limits:
        cpu: 5m
        memory: 10Mi
      requests:
        cpu: 5m
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus/rules
      name: rules
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-v6j5p
      readOnly: true
  dnsPolicy: ClusterFirst
  hostname: prometheus-prometheus-0
  nodeName: kube-dev-worker03.dev.za01.payd.co
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  subdomain: prometheus-operated
  terminationGracePeriodSeconds: 600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    secret:
      defaultMode: 420
      secretName: prometheus-prometheus
  - emptyDir: {}
    name: config-out
  - configMap:
      defaultMode: 420
      name: prometheus-prometheus-rulefiles
    name: rules
  - emptyDir: {}
    name: prometheus-prometheus-db
  - name: default-token-v6j5p
    secret:
      defaultMode: 420
      secretName: default-token-v6j5p
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-08-06T20:07:26Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-08-06T20:07:35Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-08-06T20:07:26Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://fc6eddab9b61df117b239ed36ddbad1e5a8b77c3bc24ce1004029192b272892c
    image: quay.io/coreos/configmap-reload:v0.0.1
    imageID: docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    lastState: {}
    name: alerting-rule-files-configmap-reloader
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-08-06T20:07:29Z
  - containerID: docker://9e3b938804c99a6b6261819868b93a06fa40ad3b2ce1b53f6389fab0d54ec11a
    image: quay.io/prometheus/prometheus:v2.2.1
    imageID: docker-pullable://quay.io/prometheus/prometheus@sha256:0e90814ff93acf8092d682f898de602b0bbe0fb5224cd99e54b8ff8508c72605
    lastState:
      terminated:
        containerID: docker://bd20989ce9384c0299c706ba9395736e99800f72728c5f3c365d19a0f5a89358
        exitCode: 0
        finishedAt: 2018-08-06T20:07:27Z
        reason: Completed
        startedAt: 2018-08-06T20:07:27Z
    name: prometheus
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2018-08-06T20:07:31Z
  - containerID: docker://36f27aae002215376f9aafd330f3b27c07d607d6b9b181541de09d6cbedceb47
    image: quay.io/coreos/prometheus-config-reloader:v0.20.0
    imageID: docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:9861d4e2f634740b17e922dc26cc1f9c8673dfa3a20e5cf2a7dfd849d671158e
    lastState: {}
    name: prometheus-config-reloader
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-08-06T20:07:28Z
  hostIP: 10.13.52.101
  phase: Running
  podIP: 10.42.0.4
  qosClass: Burstable
  startTime: 2018-08-06T20:07:26Z
[joseph.omojowo@kube-dev-master0.dev DEV:~] kubectl -n default get role,rolebinding -oyaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: 2018-07-19T14:53:30Z
    name: jenkins
    namespace: default
    resourceVersion: "8858739"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/roles/jenkins
    uid: 8086bef3-8b63-11e8-9969-0050569bb90b
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-07-19T14:53:30Z
    name: jenkins
    namespace: default
    resourceVersion: "8858740"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/jenkins
    uid: 80886c6a-8b63-11e8-9969-0050569bb90b
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jenkins
  subjects:
  - kind: ServiceAccount
    name: jenkins
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by Josbrafe** [comment]
thanks

**Comment by brancz** [comment]
Looks like you don't have a Role and RoleBinding for your Prometheus server in the default namespace. Which guide did you follow to set this up?

**Comment by Josbrafe** [comment]
Hi,
Below is the documentation i followed:

https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

Thanks

**Comment by prune998** [comment]
Helm charts and Jsonnet templates are supposed to create the Role and RoleBinding as needed, you should try to deploy using one of them.

In the meantime, try applying this manifest : 
```
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-k8s
    namespace: default
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
```

**Comment by brancz** [comment]
looks like the original issue was solved, closing here
