### ISSUE TITLE
How to edit helm charts for this repo

### ISSUE THREAD

**Issue by ksemaev** [coreos/prometheus-operator#1763]
Sorry for the stupied question, but I really can't understand how, for example I can add dashboard for grafana to make helm deploy it from the start.

On https://github.com/coreos/prometheus-operator/tree/master/helm is says:

> helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

But where does that repo correspond to? What git repo can I clone to add some files and to deploy everything with my changes from there?
This repo (https://github.com/coreos/prometheus-operator.git) is not working since there are no charts. Smth is moving to https://github.com/helm/charts.git but not there yet

Please advice, I'm missing some basics here, any response is hugely appreciated.

**Comment by brancz** [comment]
The helm charts are located in “helm/“ of this repository and are synchronized by CI to s3 to the location you mentioned. When installing a chart you can specify you want to install them from disk rather than a remote location. Regarding additional dashboards, this is already part of the chart if I recall correctly. @gianrubio knows best.

**Comment by ksemaev** [comment]
@brancz please correct me if I'm doing wrong:
1) Cloned the repo
2) Got into prometheus-operator/helm/kube-prometheus
3) Ran `helm install ./`

Got the error:

> Error: found in requirements.yaml, but missing in charts/ directory: alertmanager, exporter-coredns, exporter-kube-controller-manager, exporter-kube-dns, exporter-kube-etcd, exporter-kube-scheduler, exporter-kube-state, exporter-kubelets, exporter-kubernetes, exporter-node, grafana

Is there any document on how prepare repo to install from it? Or maybe youcan see my mistake here?

**Comment by brancz** [comment]
We don't use helm or these helm charts, but I would imagine what you're trying to accomplish is the same as https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-test.

**Comment by ksemaev** [comment]
@brancz  TY, trying it. But what do you mean - you don't use helm or helm charts? What is the way of installing it, if not helm?

**Comment by brancz** [comment]
The helm charts just package: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

I would recommend using that if you always want the latest state of everything. The helm charts are always lagging behind a bit as they are a downstream of the kube-prometheus project.

**Comment by ksemaev** [comment]
@brancz TY, https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-test is what I needed. Was just confused with this "How to test", it's more likely "How to customize".
