### ISSUE TITLE
Fake alert in Prometheus Alert manager

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1765]
**What did you do?**
I have created an alert rule in Prometheus for a pod's memory usage as follow:
_______________________________
sum by(container_name) (container_memory_usage_bytes{container_name!="POD",container_name="my-app",namespace="monitoring"}) > 10
_______________________________
**What did you expect to see?**
But, The alert is active even if the value is less than 10
**What did you see instead? Under which circumstances?**
I want to see the correct alert 
**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
Please see the screenshot from the below link:
____________________

https://imgur.com/a/sUWrzNO
____________________

**Comment by brancz** [comment]
The metric’s unit is bytes, I can’t imagine a program that will ever use less than 10 bytes of memory. I’m guessing you wanted to do something like 10 megabytes or 10 gigabytes.

**Comment by manuprometheus** [comment]
Sorry, That's the issue with my rule itself. I have changed "expr" in rule.
______________________________
sum(container_memory_usage_bytes{namespace="monitoring", container_name="dz-message-broker", container_name!="POD"}) by (container_name) > 700000000
______________________________
Earlier I had made the value as 7 instead of 700000000 in the above "expr" .
Thank you brancz. :)
