### ISSUE TITLE
Getting false alerts for Kube-etcd - Insufficient members 

### ISSUE THREAD

**Issue by vidhy** [coreos/prometheus-operator#1766]
Consistently getting alerts that kube-etcd insufficient members, even though everything in etcd seems to be fine.

Below is the rule being used.

https://github.com/coreos/prometheus-operator/blob/fb99938ce7f080678e39ec93c0968379d44ecf8f/helm/exporter-kube-etcd/templates/etcd3.rules.yaml#L6

When I have 3 kube-etcd pods up, the above expression evaluates to true all the time.
Hence alert is being fired.
I assume There is some issue in expression and this is not the intended behaviour. The expression should be `(count(up{job="kube-etcd"}) ==  0)> (count(up{job="kube-etcd"}) / 2 - 1) `

**Comment by michaelgeorgeattard** [comment]
I deployed `prometheus-operator` and `kube-prometheus` using helm. I did not override the `deployKubeEtcd` flag for `kube-prometheus` (default should be true).

I am not seeing `kube-etcd` deployed anywhere and I am getting the below in `/targets`:

![image](https://user-images.githubusercontent.com/5755302/43835366-fda3b954-9b11-11e8-9a32-4abf8c362f72.png)

**Comment by brancz** [comment]
I'm guessing 4001 is just the wrong port, by default etcd uses 2379, I don't know why the helm chart uses this by default.

**Comment by vidhy** [comment]
Issue not seems with the por. I exec inside and tried accessing the metrics via curl. It works. But when i try to access from a different pot it is not happening.

**Comment by vidhy** [comment]
We are on AWS and the security policy was block inbound call on 4001 port for the master nodes. Adding appropriate rule fixed the issue for me.

**Comment by brancz** [comment]
Thanks for reporting that back! In that case I'm closing this here.
