### ISSUE TITLE
Need Explanation on kube state metrics Alerts

### ISSUE THREAD

**Issue by vidhy** [coreos/prometheus-operator#1776]
I am able to see the **kube_daemonset_status_number_misscheduled** metric value is 1 for few of my daemonsets. But when i check the daemonsets and corresponding pods they are running properly on all the worker nodes. Unable to understand what does this metric mean. It is being used in the alerting rule as well.

Also it would be better if we have explanation on the metrics being exposed.

**Comment by vidhy** [comment]
I guess It is because of the cluster autoscaler. New node gets added and removed dynamically. Probabaly that is not being reflected in the metrics exposed.

**Comment by brancz** [comment]
As this metric is exposed by [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) and not specific to the prometheus-operator, please open an issue there. Thanks! :slightly_smiling_face:
