### ISSUE TITLE
Prometheus server disk space usage

### ISSUE THREAD

**Issue by secat** [coreos/prometheus-operator#1779]
Currently as stated in https://github.com/prometheus/prometheus/issues/3684 there are no metrics for the Prometheus server disk space usage.

Would it be a good idea to deploy the Prometheus statefulset with a new sidecard that would implement the solution in https://github.com/prometheus/node_exporter/pull/789 (i.e. https://github.com/prometheus/node_exporter/blob/master/text_collector_examples/directory-size.sh)?

Currently I have to monitor the Prometheus peristent volume using stackdriver, but I would like to monitor it with its own metrics.

**Comment by brancz** [comment]
> Currently I have to monitor the Prometheus peristent volume using stackdriver, but I would like to monitor it with its own metrics.

The kubelet exposes the `kubelet_volume_stats_available_bytes` metric, which to my knowledge is what stackdriver uses to monitor the PVC. Could you check if this would satisfy this? (in our setups this seems to work fine, but is a relatively young addition to Kubernetes ... it was introduced in 1.9 I believe)

**Comment by secat** [comment]
@brancz Thank you, these 2 metrics:
-` kubelet_volume_stats_capacity_bytes`
- `kubelet_volume_stats_used_bytes`
where exactly the kind of metrics I was needing to monitor my PV.

**Comment by brancz** [comment]
In that case, can we close this?

**Comment by secat** [comment]
Yes, you can close this issue.

Thank you again.
