### ISSUE TITLE
Promotion of kubernetes native resources to a stable API ?

### ISSUE THREAD

**Issue by den-is** [coreos/prometheus-operator#1780]
I'm of course maintaining my own manifests and charts, but imho this is not bad upgrade for the public as well.

> DaemonSet, Deployment, ReplicaSet - are stable since kubernetes v1.9 and are in apps/v1
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#apps

**Comment by brancz** [comment]
Which manifests are you referencing? The ones in `contrib/kube-prometheus/`? Those are generated using [ksonnet-lib](https://github.com/ksonnet/ksonnet-lib), and it currently uses the 1.8 API as a reference.

**Comment by den-is** [comment]
@brancz I'm referencing all of them

1. contrib/kube-prometheus - which absolutely didn't work on my absolutely clean kubeadm setup v1.11.1 and v1.11.2. also it didn't work on my clean setup of baremetal k8s v1.10.6.

2. helm worked just fine, but has same beta resources:
https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/templates/grafana-deployment.yaml#L1
https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-node/templates/daemonset.yaml#L2
https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/templates/deployment.yaml#L1

PS: I've just started playing with prometheus-operator and surrounding projects.
I will try to repeat kubeadm and baremetal setups using jsonnet and report issues if they repeat.
But as soon as helm worked just fine - I'm good with it. Just have to maintain my own charts to not to keep old APIs resources in prod when it is possible.

**Comment by den-is** [comment]
https://github.com/coreos/prometheus-operator/blame/master/Documentation/user-guides/cluster-monitoring.md#L42
https://github.com/coreos/prometheus-operator/blame/master/Documentation/user-guides/cluster-monitoring.md#L148
https://github.com/coreos/prometheus-operator/blame/master/Documentation/user-guides/cluster-monitoring.md#L258

**Comment by brancz** [comment]
The `apps/v1beta2` API is the one that is supported by the widest possible selection of Kubernetes versions. I just launched a 1.11.2 cluster and everything seems to work just fine, can you elaborate on any problems you have with these manifests?

**Comment by den-is** [comment]
well, if conversation about API version reached its culmination probably this issue can be closed. :))) I understood your points and have no more questions. Still much more supported versions now support v1, and only k8s1.8 holds unstable version of resources.
probably i'll just continue forking your and maintaining my charts.

regarding setup issues.
Today it worked much better. clean-kubeadm-1.11.2+calico+jsonnet.
Still have issue. Will open another ticket
