### ISSUE TITLE
operator does not create any pods

### ISSUE THREAD

**Issue by lukasz-bielinski** [coreos/prometheus-operator#1782]
**What did you do?**
a) i've build GKE cluster  1.10.5-gke.4 
b) granted admin access kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user my@user                      
c) then checkout latest tag of operator  git checkout v0.23.0
d) and then kubectl apply -f bundle.yaml

**What did you expect to see?**
i've expected to see running prometheus pods

**What did you see instead? Under which circumstances?**
no prometheues pods were created

**Environment**
GKE  1.10.5-gke.4 
3 nodes  n1-standard-1 (1 vCPU, 3.75 GB memory) 

* Prometheus Operator version:
➜  prometheus-operator git:(82ac4910)

* Kubernetes version information:
 ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE

* Manifests:

```
 
```

* Prometheus Operator Logs:

```

 kubectl logs -f prometheus-operator-79f799ff6d-t9g24 
ts=2018-08-12T13:15:47.34374112Z caller=main.go:130 msg="Starting Prometheus Operator version '0.23.0'."
level=info ts=2018-08-12T13:15:47.43686538Z caller=operator.go:314 component=prometheusoperator msg="connection established" cluster-version=v1.10.5-gke.4
level=info ts=2018-08-12T13:15:47.538695283Z caller=operator.go:176 component=alertmanageroperator msg="connection established" cluster-version=v1.10.5-gke.4
level=info ts=2018-08-12T13:15:47.835766856Z caller=operator.go:566 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-08-12T13:15:47.839664925Z caller=operator.go:1338 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-08-12T13:15:47.854286639Z caller=operator.go:1338 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-08-12T13:15:47.868882342Z caller=operator.go:1338 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-08-12T13:15:50.839696112Z caller=operator.go:192 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-08-12T13:15:56.952053004Z caller=operator.go:330 component=prometheusoperator msg="CRD API endpoints ready"
level=error ts=2018-08-12T13:15:57.06229384Z caller=operator.go:716 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"kube-system\" does not exist" err=null
level=error ts=2018-08-12T13:15:57.062728535Z caller=operator.go:716 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"kube-system\" does not exist" err=null


➜  ~ kubectl get ns
NAME          STATUS    AGE
default       Active    14m
kube-public   Active    14m
kube-system   Active    14m
```

**Comment by metalmatze** [comment]
```
level=error ts=2018-08-12T13:15:57.06229384Z caller=operator.go:716 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"kube-system\" does not exist" err=null
```

This line says that `kube-system` as a namespace does not exist, thus the statefulset could not be created and there is no way to schedule a pod.

**Comment by brancz** [comment]
You just created the bundle, which does not start anything but the Prometheus Operator, which did start successfully as you showed us logs. Did you go through the getting started? https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

**Comment by lukasz-bielinski** [comment]
@brancz  hi, i went directly for bundle installation and i got confused as i assumed that operator will create everything what's needed :)
now i moved to helm installation and everything works fine.

**Comment by brancz** [comment]
Wonderful :slightly_smiling_face:
