### ISSUE TITLE
remote_write bearer_token not passed to instance

### ISSUE THREAD

**Issue by incognick** [coreos/prometheus-operator#1788]
**What did you do?**

I'm trying to add the bearer_token to every remote_write request however it is not being added to the request. The url field is working as expected.

When I exec into the prometheus container and cat out the generated config file, only the url is there with a remote_timeout setting.

**What did you expect to see?**
Requests hitting my endpoint with an Authorization header filled in.  

**What did you see instead? Under which circumstances?**
Requests with no authorization

**Environment**
Prometheus 
```yaml
remoteWrite:
    - bearer_token: mytoken
      url: http://my-api/prom/write
```
* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.20.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kops on AWS

**Comment by azai91** [comment]
Having this issue as well. Any progress on this?

**Comment by brancz** [comment]
I don't think so, but we'd be happy to accept PRs :slightly_smiling_face: .

**Comment by brancz** [comment]
I can't reproduce this problem. In my instance this is configured just fine. I'll close this due to staleness. Please feel free to open a new issue should you continue to encounter this.
