### ISSUE TITLE
Update kube-prometheus manifests

### ISSUE THREAD

**Issue by pmcgrath** [coreos/prometheus-operator#1793]
Can we get the v0.23.1 image updated in the contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml file

Checked master and release-0.23 branches and the v0.23.1 tag, all still configured with 0.23.0 images
- quay.io/coreos/prometheus-config-reloader:v0.23.0
- quay.io/coreos/prometheus-operator:v0.23.0

Need this to sort the [excessive CPU usage](https://github.com/coreos/prometheus-operator/pull/1785) fix that you just merged

I have altered locally and verified the fix worked as expected

Apologies, could not create a PR as I have not had time to look into how you build the manifests yet

**Environment**

* Prometheus Operator version:

	v0.23.1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm v1.11.2

**Comment by brancz** [comment]
You're absolutely right, I'll get the pull request out shortly to update it.

**Comment by brancz** [comment]
Done. Let us know if everything works as expected, or open a new issue if not :slightly_smiling_face:.

**Comment by pmcgrath** [comment]
@brancz Thanks, appreciate the work here - Working as expected now
