### ISSUE TITLE
Ability to specify annotations on Prometheus instances

### ISSUE THREAD

**Issue by caseydavenport** [coreos/prometheus-operator#180]
As a user, I'd like to be able to deploy Prometheus instances with a set of defined annotations.

For example, I'd like to be able to specify a list of tolerations so that my Prometheus Pods will tolerate tainted nodes.

One way would be to simply pass the annotations on the `kind: Prometheus` TPR to the pod template in the created StatefulSet specification.

**Comment by brancz** [comment]
We previously discussed this in #95 and somewhat in #107. I completely see the benefit of this, but I'm trying to figure out how we can still guarantee good reliable defaults for Prometheus and Alertmanager clusters, when we allow the use of alpha features and potentially overriding the safe defaults we recommend to use.

Maybe the solution is just to say we allow passing through annotations, but can't guarantee anything if a user enables alpha features with those.

What are your thoughts on this @fabxc ?

**Comment by fabxc** [comment]
Yea, still on the fence about that as annotations usually are per-object. I'm not quite sure passing them done is a sane thing to do or, if we want to allow it, we should arther have an explicit field to specify annotations handed down to the pod or stateful set object.

**Comment by brancz** [comment]
Yes I would definitely say this would have to be a field in the `Prometheus` object kind.

**Comment by brancz** [comment]
We'll be able to set the tolerations directly on the Pod object now, with 1.6. We just have to wait for client-go to be released with 1.6 compatibility.

**Comment by brancz** [comment]
having upgraded to the latest release of client-go this is now possible

**Comment by kop** [comment]
Yup, taints are something that Prometheus operator is definitely missing.
Is there any outgoing work on this issue?

**Comment by brancz** [comment]
Closed by #600, which implements taints and affinity, setting custom annotations and labels is also coming up in #591 .
