### ISSUE TITLE
sync node_exporter endpoints if installed separately 

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#1803]
**What did you do?**

We run the node_exporter on all of our machines, which means that our installation process deploys this separately from Kubernetes - it doesn't make sense to run a Daemonset.

**What did you expect to see?**

I would like to sync the node_exporter endpoints in the same fashion that the kubelet endpoints are synced in prometheus-operator. I would be happy to submit a PR for this, but would like advice on whether this should be 

1. Included in prometheus-operator in the same way the kubelet is
2. Kept as an external component, to be deployed only this special case

**Comment by brancz** [comment]
While maybe a bit hacky, I think you should actually be able to reuse the kubelet's Service/Endpoints object and define the [`targetPort`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint) within either a new or the same kubelet ServiceMonitor object.

Option two also doesn't seem too bad, and arguably we should have implemented the kubelet sync as a separate component in the first place, but we are now stuck with it :slightly_smiling_face: .

**Comment by vsliouniaev** [comment]
So you're saying it would be nice if someone could extract this code ;-)

**Comment by brancz** [comment]
Actually I wasn't trying to persuade you or anything, but yes it would indeed be nice :slightly_smiling_face: . That said it would also be reasonable to use the `additionalScrapeConfigs` feature to add plain Prometheus configuration and use the `role: node` of the Kubernetes target discovery in Prometheus to discover the nodes and relabel to using the node exporter's port.

**Comment by vsliouniaev** [comment]
Thanks for the suggestion, that seems like the cleanest way to go forward with it until I have time to make the changes
