### ISSUE TITLE
How to monitor thanos S3 backups

### ISSUE THREAD

**Issue by jpiper** [coreos/prometheus-operator#1809]
Hi there, is there any way to look at logs, etc. for thanos backups to s3. I'm pretty sure I've got everything sorted - he sidecars and the querier are up and running and works.

But nothing is appearing in my bucket, and I want to work out what's going on here!

**Comment by brancz** [comment]
Do the Thanos people have some suggestions on how to debug that? If they do, then we should make sure that that's possible with the Prometheus Operator, or maybe we can even make it easier :slightly_smiling_face:

**Comment by jpiper** [comment]
Maybe an "THANOS_ARGS" variable that can be used to pass arbitrary args to the sidecare so the log level can be increased, etc?

**Comment by brancz** [comment]
log level is already passed through as the log levels of prometheus and thanos are equivalent :slightly_smiling_face:

**Comment by jpiper** [comment]
ahh excellent, let me try increasing that and see where that gets me

**Comment by brancz** [comment]
did increasing the log level help?

**Comment by jpiper** [comment]
Wait, I'm wrong on that "thanos store" front. It could just be the env vars - I'll work it out and open a PR

**Comment by brancz** [comment]
Thanos store (today) is not involved in uploading, but that has been discussed. Please do open a PR if there should be any mistakes in the env var configurations (they have also changed on master since the last release, if that's the case we should probably stick to whatever the latest release supports).

**Comment by jpiper** [comment]
You know what, I think this was a completely separate issue on my end... If I do find anything I will open a PR though :)
