### ISSUE TITLE
Prometheus operator with external prometheus server

### ISSUE THREAD

**Issue by navi86** [coreos/prometheus-operator#1810]
I am trying to configure prometheus operator with external prometheus server, but i could’t found solution to this task. What do i need to do to accomplish this task ?

**Comment by navi86** [comment]
I am trying to configure prometheus operator with external prometheus server, but i could’t found solution to this task. What do i need to do to accomplished this task ?

**Comment by brancz** [comment]
The Prometheus Operator builds on top of Kubernetes and uses Kubernetes primitives to accomplish its task. Running Prometheus outside of Kubernetes is out of scope for the Prometheus Operator.

**Comment by mxinden** [comment]
@navi86 I am closing here. Please let us know if you have further questions.
