### ISSUE TITLE
K8S 1.10.4 fails to install coreos/prometheus-operator v0.0.29 helm chart with defaults 

### ISSUE THREAD

**Issue by pickledrick** [coreos/prometheus-operator#1811]
**What did you do?**

helm --tiller-namespace helm upgrade --install prometheus-operator coreos/prometheus-operator --namespace kube-system --wait

**What did you expect to see?**

Prometheus Operator pods in kube-system come into a Running state

**What did you see instead? Under which circumstances?**

Prometheus Operator pods in kube-system are in CrashLoopBackOff with the following error in logs

**Environment**

* Prometheus Operator version:

	v0.20.0

* Kubernetes version information:

	K8S: v1.10.4
        Helm: v2.9.1

* Kubernetes cluster kind: 

	calico: 3.0.5
        coredns: 1.1.1
        etcd: 3.3.3
        k8s: 1.10.4

* Manifests:

Manifests generated using default values on upstream cores/prometheus-operator chart at chart version 0.0.29

* Prometheus Operator Logs:

https://gist.github.com/pickledrick/d411034be9c61728c52fc32e6102749f

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
