### ISSUE TITLE
Syncing kubelet endpoints fails

### ISSUE THREAD

**Issue by carlpett** [coreos/prometheus-operator#1815]
**What did you do?**
Add new nodes to cluster, on which we had a working prometheus-operator setup.

**What did you expect to see?**
kube-system/kubelet `Endpoints` object updated with new nodes.

**What did you see instead? Under which circumstances?**
`ts=2018-08-21T10:48:46.709178411Z caller=operator.go:342 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="synchronizing kubelet endpoints object failed: updating kubelet endpoints object failed: Endpoints \"kubelet\" is invalid: subsets[0].addresses[10].ip: Invalid value: \"k8s-master-24872480-0\": must be a valid IP address, (e.g. 10.9.8.7)"`

Note that all other Prometheus config updates work fine.

**Environment**
Azure, acs-engine

* Prometheus Operator version:
0.17.0 (Yes, it is old. We have some migration pains to handle before upgrading to the latest goodness)

* Kubernetes version information:
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
acs-engine

* Prometheus Operator Logs:
See above. Repeats every three minutes.

**Comment by brancz** [comment]
@mxinden you recently noticed this as well, I think we might still have to fix this, no?

**Comment by carlpett** [comment]
Some more info: The node mentioned in the error message did not have an internal IP in its' status:
```yaml
status:
  addresses:
  - address: k8s-master-24872480-0
    type: Hostname
```

While another node has
```yaml
status:
  addresses:
  - address: 10.255.255.6
    type: InternalIP
  - address: k8s-master-24872480-1
    type: Hostname
```

Looking at the kubelet logs, I found this:
`
W0820 16:09:27.181164   10850 kubelet_node_status.go:1114] Failed to set some node status fields: failed to get node address from cloud provider: Timeout after 10s
`

(This was roughly two days ago, and it doesn't seem to have tried again since, so this might be a bug in Kubernetes).

Restarting the kubelet fixed the symptoms, so that is a workaround until this situation can be handled.

**Comment by brancz** [comment]
From my point of view there are two things to do here:

1) not attempt to use the hostname at all (attempting to resolve would probably introduce new possibly strange behaviors)
2) introduce a new metric in kube-state-metrics in order to catch this behavior and alert on it in the future

**Comment by brancz** [comment]
#1816 was merged so I'm closing this, thanks a lot @carlpett for fixing this!
