### ISSUE TITLE
What is the best way to specify storage with jsonnet setup?

### ISSUE THREAD

**Issue by den-is** [coreos/prometheus-operator#1819]
Helm charts define `storageSpec` variable - which makes life super easy.

What is the best way to specify persistent storage with jsonnet setup?
If it can be provisioned before compilation with that `_config++`?
Or best way atm is to edit compiled yaml manifests and include PVCs volumeClaimTemplate there?

I'm talking about three main end-user components which might require persistent storage: prometheus, alertmanager, grafana.

[Storage](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md) documentation seems to be a little bit blurry. Not enough examples.
> The StorageClass that was created can be specified in the storage section in the Prometheus resource.

What does it mean ? should i insert somewhere in jsonnet? But example below that lines looks like normal `yaml`.

It will be super helpful to see real examples. Like showing what and where to insert.

Just IMHO editing compiled yamls looks like easiest way atm, please correct me if I'm wrong :/

**Comment by brancz** [comment]
This is the code I use in my environment to add the storage spec:

```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local pvc = k.core.v1.persistentVolumeClaim;

{
  prometheus+:: {
    prometheus+: {
      spec+: {
        storage: {
          volumeClaimTemplate:
            pvc.new() +
            pvc.mixin.spec.withAccessModes('ReadWriteOnce') +
            pvc.mixin.spec.resources.withRequests({ storage: '50Gi' }) +
            pvc.mixin.spec.withStorageClassName('fast-disks') +
            pvc.mixin.spec.selector.withMatchLabels({}),
        },
      },
    },
  },
}
```

I think this is a good candidate to have some extra documentation on though, would you like to add it to the docs? :slightly_smiling_face:

**Comment by den-is** [comment]
@brancz sure but :)))
1. first of all I've to test it on my own cluster
2. probably learn some [jk]sonnet to be confident in what I'm doing and going to share with pulic - and this is where it gonna take most of the time

**Comment by jolson490** [comment]
thanks @brancz - that certainly helps.

(I have looked into [persistent volumes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) before (with yaml files and helm), but it's been a while.)

[PrometheusSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) has a [StorageSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#storagespec) field, which has a `PersistentVolumeClaim`.
For [k.core.v1.persistentVolumeClaim](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#persistentvolumeclaim-v1-core), here is the [spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#persistentvolumeclaimspec-v1-core) - e.g. which mentions `accessModes` as 1 of the fields. 
*`#1)`* Frederic, can you please share how did you know to pre-pend `with` to each of the fields (e.g. `withAccessModes`)?

*`#2)`* What if there isn't already a StorageClass created in the cluster named 'fast-disks'? 
 * Is there a way from a kube-prometheus `*.jsonnet` file to specify that a StorageClass should be created? (I know one way to create a StorageClass is to do `kubectl apply -f` on https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/aws/default.yaml)
 * or does creating a (default) StorageClass need to be done by a cluster admin (when the cluster is created)?

*`#3a)`* The example you shared Frederic will use [dynamic volume provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) to create a PersistentVolumeClaim when kube-prometheus is [deployed/created](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#quickstart)? (And that PersistentVolumeClaim automatically gets deleted when kube-prometheus is torn-down?)
*`#3b)`* If so, then when kube-prometheus is re-deployed then will a new PersistentVolumeClaim be provisioned and thus data from before the re-deploy isn't retained?

*`#4)`* My use case is I deployed kube-prometheus to a given cluster a week ago...:
```
core@ip-192-168-xx-xx ~ $ kubectl get pods -n monitoring
NAME                                   READY     STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2       Running   0          7d
grafana-54d8db4bc4-m9sg4               1/1       Running   0          7d
kube-state-metrics-759fd68bc5-d6lq6    4/4       Running   0          7d
node-exporter-cfqxk                    2/2       Running   0          7d
node-exporter-dnjjn                    2/2       Running   0          7d
node-exporter-dps5k                    2/2       Running   0          7d
node-exporter-f24vd                    2/2       Running   0          7d
node-exporter-fhbrs                    2/2       Running   0          7d
node-exporter-gqlsp                    2/2       Running   0          7d
node-exporter-nk2df                    2/2       Running   0          7d
node-exporter-pmrnv                    2/2       Running   0          7d
node-exporter-zw7fb                    2/2       Running   0          7d
prometheus-k8s-0                       3/3       Running   1          7d
prometheus-k8s-1                       3/3       Running   1          7d
prometheus-operator-79f799ff6d-thwm2   1/1       Running   0          7d
```
...but on a given grafana dashboard when I specify to show data for the past 7 days, there's only data for the past day:
<img width="1378" alt="screen shot 2018-08-23 at 8 55 08 pm" src="https://user-images.githubusercontent.com/15840507/44560999-07fee880-a718-11e8-9e27-cab548722897.png">
Even if by default my grafana stores its data in a [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir), if the grafana pod hasn't been restarted in the past week then I would expect grafana to show data for every day the past week?
Will using the `PersistentVolumeClaim` under `PrometheusSpec` mean that data not only for prometheus but also for grafana will be retained?

Any suggestions would be much appreciated - thanks!!!

**Comment by brancz** [comment]
1) I read the ksonnet-lib code pretty extensively so I know the idioms pretty well by now, but there is also (apparently unofficial) but really nicely rendered documentation here: http://g.bryan.dev.hepti.center/ (I just reached out to the ksonnet people to see if we can somehow help on getting that documentation to be more official)

2) StorageClasses vary wildly across clusters, so there are no possibilities to unify this somehow, it's always going to be environment and setup specific. Yes, typically this is setup cluster wide by an admin of the cluster.

3a) No we intentionally don't delete the PVCs as we want the act of deleting your data to be a deliberate choice of you, as we don't want to cause accidental data-loss.
3b) When you rollout new versions of kube-prometheus the StatefulSet controller makes sure that the "old" PVCs are assigned consistently, so the new Prometheus pods will get the data they had previously on disk.

4) You're only seeing the last day of data because that's the default retention set by the Prometheus Operator, you can set `.spec.retention` to `168h` for example to have 1 week of retention.

**Comment by brancz** [comment]
Regarding your first question, see the documentation on StatefulSets: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage. It mentions "the PersistentVolumes associated with the Pods’ PersistentVolume Claims are not deleted when the Pods, or StatefulSet are deleted", this means that either rolling out a new version (let's say with kubectl apply) or deleting and re-creating the stack, would not make a difference and the Pods would again be assigned the previous storage, as it was never deleted.

Regarding the storageclass in jsonnet, you were actually very close:

```jsonnet
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';

local storageClass = k.storage.v1.storageClass;

storageClass.new() +
  storageClass.mixin.metadata.withName('gp2') +
  storageClass.withProvisioner('kubernetes.io/aws-ebs')
```

**Comment by jolson490** [comment]
ah, ok. thanks very much Frederic for pointing both of those things out.

**Comment by danhul** [comment]
@brancz I tried your suggestion above to dynamically create pvc but it fails showing the following error message "Failed to provision volume with StorageClass "cephrbd": claim Selector is not supported". I am using Ceph rbd storage class. I also tried to remove the disable the selector match label option from the jsonnet file but doesn´t help. Can you please advise? Another work around is using an existing persistent volume claim which I can create but didn´t find any example on how to use existing pvc in the jsonnet file. Any idea, appreciated.

**Comment by brancz** [comment]
Are you able to create any StatefulSet with dynamic volume provisioning?

**Comment by danhul** [comment]
@brancz yes I can create that.

**Comment by brancz** [comment]
Then you should be able to use the same `volumeClaimTemplate` as you do in any other StatefulSet in the `.spec.storage.volumeClaimTemplate` field.

**Comment by danhul** [comment]
Hei @brancz is it possible to specify existing PVC in the jsonnet file, so that prometheus rather use that PVC instead of dynamically creating.

**Comment by brancz** [comment]
Yes, the PVC just needs to select those existing volume and they need to be unbound.

**Comment by danhul** [comment]
If the PVC is created once, further runs can automatically bound to it. But, what I mean is if I create new PVC first separately and use the name of the PVC in the jsonnet configuration file. 
In the jsonnet config , is it possible to specify name of pvc instead of pvc.new() as shown below?

storage: {
      volumeClaimTemplate:
         pvc.new() +
        .....
