### ISSUE TITLE
Deploying prometheus-operator into namespace on Openshift

### ISSUE THREAD

**Issue by cunningt** [coreos/prometheus-operator#1824]
I'm trying to deploy the prometheus-operator into a namespace on openshift in the same situation as https://github.com/coreos/prometheus-operator/issues/787.    I think I've made the changes that were made in 787 (changing ClusterRoles -> Roles, ClusterRoleBindings -> RoleBindings, remove kubelet arg) - my bundle.yaml is here : https://gist.github.com/cunningt/f8e547c7a64f63b311f8e1e0be8b36d6

Everything looks like it creates correctly 

```
tcunning@tcunning-OSX:/tmp/prometheus-operator$ oc create -f bundle.yaml 
customresourcedefinition "servicemonitors.monitoring.coreos.com" created
customresourcedefinition "prometheuses.monitoring.coreos.com" created
customresourcedefinition "alertmanagers.monitoring.coreos.com" created
rolebinding "prometheus-operator" created
role "prometheus-operator" created
deployment "prometheus-operator" created
serviceaccount "prometheus-operator" created
```

but the pod won't start up because it is hitting this error

```
  | ts=2018-08-25T14:28:25.702758281Z caller=main.go:115 msg="Starting Prometheus Operator version '0.22.0'."
-- | --
  | level=info ts=2018-08-25T14:28:25.720380586Z caller=operator.go:293 component=prometheusoperator msg="connection established" cluster-version=v1.9.1+a0ce1bc657
  | level=info ts=2018-08-25T14:28:25.725357523Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.9.1+a0ce1bc657
  | ts=2018-08-25T14:28:26.000090789Z caller=main.go:175 msg="Unhandled error received. Exiting..." err="getting CRD: Alertmanager: customresourcedefinitions.apiextensions.k8s.io \"alertmanagers.monitoring.coreos.com\" is forbidden: User \"system:serviceaccount:foobar:prometheus-operator\" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope: User \"system:serviceaccount:foobar:prometheus-operator\" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope"
```

Configuration
```
tcunning@tcunning-OSX:/tmp/prometheus-operator$ minishift version
minishift v1.22.0+7163416
```

```
tcunning@tcunning-OSX:/tmp/prometheus-operator$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.64.98:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

`tcunning@tcunning-OSX:/tmp/prometheus-operator$ minishift start --openshift-version=v3.9.0 
`

**Comment by mxinden** [comment]
You are missing the `manage-crds=false` flag. By default the Prometheus Operator manages its CRDs by itself. For that it  first checks whether they already exist. In your setup the Prometheus Operator does not have the rights to do so, hence the error.

In case you want to specify not one but multiple namespaces for the Prometheus Operator to watch, you need to wait for the next release of the Prometheus Operator (this just landed in master https://github.com/coreos/prometheus-operator/pull/1813, but needs this fix github.com/coreos/prometheus-operator/pull/1828).

Let me know if this helps. Thanks for the detailed bug report!

**Comment by cunningt** [comment]
@mxinden That seemed to fix it!    Thank you for the help!

**Comment by mxinden** [comment]
Cool. Closing here. @cunningt Let us know in case you are facing any other issues.
