### ISSUE TITLE
no matches for kind "Prometheus" in version "monitoring.coreos.com/v1alpha1"

### ISSUE THREAD

**Issue by magick93** [coreos/prometheus-operator#1826]
**What did you do?**

I'm following the steps on the blog at https://coreos.com/blog/the-prometheus-operator.html

And ran `kubectl create -f https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml`

And got:

```
service "prometheus-k8s" created
error: unable to recognize "https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1alpha1"
```

**What did you expect to see?**
Not sure

**What did you see instead? Under which circumstances?**

```
service "prometheus-k8s" created
error: unable to recognize "https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1alpha1"
```

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	bare metal.
Not sure how it was installed. I have recently inherited it.

**Comment by brancz** [comment]
The very top of the blog post says:

> Note: The instructions in this post are out of date. To try out the Prometheus Operator, view the latest Prometheus docs for an up-to-date guide to get started.

I recommend the getting started guide right from this repo: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

Let us know how it goes! :slightly_smiling_face:

**Comment by yzhao1012** [comment]
Please consider make the deprecation notice more prominent.

Changing to red color might be a good idea.

Or the entire text should be hidden behind a zippy button, stating something like:
"This is deprecated, to read, click this button"
Which then shows the text after clicking the button.
