### ISSUE TITLE
Compute Resources Graphs Dramatically Overcounting Memory

### ISSUE THREAD

**Issue by Queuecumber** [coreos/prometheus-operator#1841]
This may not be your bug but the grafana charts are dramatically over counting memory usage in my cluster for some chart types. 

For example, the "Compute Resources/Cluster" chart is showing that one of my namespaces is using 18GB of memory, when I only even have 16GB installed, and the actual usage is much less. 

As far as I can tell this is because there is an entry in all the prometheus metrics with a name of "" that gives the total memory used by each pod. For example, the metric computed by the above chart is something like:

```
sum(container_memory_rss) by (namespace)
```

But this counts both a namespace with namespace_name="" which gives the total RAM used by all namespaces, and for *each pod* a container with container_name="" that gives the total RAM usage by that pod. So the double-counting is quite significant by including these. If you instead use

```
sum(container_memory_rss{namespace!="", container_name!=""}) by (namespace)
```

then it seems to give accurate values. This change would need to be propagated to everything that measures an entire namespace/pod. 

I want to make sure this isnt some weird configuration issue on my end though, I find it odd that this would have been missed by whoever made the charts unless it is a recent change to prometheus.

**Comment by metalmatze** [comment]
This is related to at least some fixes we merged into a dependency of kube-prometheus:
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/75

**Comment by Queuecumber** [comment]
OK so maybe if I repull that and remake my image it will be fixed, I can give it a shot and post a new bug there if it's still a problem

**Comment by Queuecumber** [comment]
Seems fixed by that update
