### ISSUE TITLE
Update helm charts to the latest dependency versions

### ISSUE THREAD

**Issue by greggdonovan** [coreos/prometheus-operator#1850]
**What did you do?**

I installed the latest Helm chart of the Prometheus Operator.

**What did you expect to see?**

I expected to see the the latest released version of the Prometheus Operator, Alertmanager, and Prometheus.

**What did you see instead? Under which circumstances?**
Prometheus v2.2.1 (latest is v2.3.2)
Alertmanager v0.15.1 (latest is v0.15.2)
Prometheus Operator v0.20.0 (latest is v0.23.2)

**Environment**

* Prometheus Operator version:
 v0.20.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE 1.10

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by vsliouniaev** [comment]
I think part of the slowness to respond to this issue is that the helm charts have been in the process of being migrated to https://github.com/helm/charts. This is now complete, could you see if this fixes your issue. Please be aware, there are significant changes to the way the chart is deployed between here and helm/charts

**Comment by jalberto** [comment]
@vsliouniaev it's very confusing by the documentation and comments on different issues here which chart is the "official" one, can someone clarify?
Thanks

**Comment by squat** [comment]
Hi, @vsliouniaev the official helm charts for the Prometheus Operator are in https://github.com/helm/charts. Any PRs or issues concerning the charts should be filed there. We are in the process of eliminating the charts from this repo. I hope that answers your question. I'll close this issue for now, but please write back if there are any more doubts.
