### ISSUE TITLE
Alertmanager fails to start when POD_IP is IPv6

### ISSUE THREAD

**Issue by azenk** [coreos/prometheus-operator#1858]
I attempted to deploy kube-prometheus on my ipv6 enabled kubernetes cluster.  When alertmanager starts, it crashes immediately with the dreaded "too many colons" error.   If POD_IP is ipv6 it needs to be enclosed in square brackets.  

https://github.com/coreos/prometheus-operator/blob/4253f01455fa7a578d45dcf43e251c5c229c3351/pkg/alertmanager/statefulset.go#L198

Based on a quick grep, the issue probably exists in more than this one spot.  I can't think of a quick way to fix this.  If anyone has an idea, I'm happy to work on a PR.

**Comment by mxinden** [comment]
Thanks for reporting @azenk.

Is there a global K8s flag, that  one can request, whether the given cluster is ipv4 or ipv6 based? As a last idea, this could be an option via a command line flag to the Prometheus Operator.

Both of these would break once in the future K8s supports dual stack ipv4 and ipv6.

**Comment by squeed** [comment]
You can use the brackets with v4 addresses. In other words,
```
net.Listen("tcp", "[192.168.1.1]:9000")
```
works fine.

**Comment by brancz** [comment]
Yes, we should fix that.

**Comment by mxinden** [comment]
@azenk do you want to give this a shot? Otherwise I will look into it.

**Comment by squat** [comment]
Do we have any IPv6 enabled clusters to test on? We can of course test for a positive result on an IPv4 cluster but will not be sure about the IPv6 case.

**Comment by azenk** [comment]
I'm happy to try adding the square brackets and test it on our cluster.  It looks fairly straightforward based on the little bit of poking around that I've done.
