### ISSUE TITLE
APIServerErrorsHigh error out of the box

### ISSUE THREAD

**Issue by eroji** [coreos/prometheus-operator#1867]
I installed the lastest Helm chart for prometheus-operator and kube-prometheus and I am getting APIServerErrorsHigh right out of the box.

![image](https://user-images.githubusercontent.com/13228540/45188031-b3fc0580-b1e7-11e8-8544-59e47cff353c.png)

I have a 3 master node K8s cluster running on v1.10.5. I also have Kubernetes Dashboard installed and exposed via Nginx ingress rule. The dashboard is working without any noticeable issue. However, the alert seems to indicate the dashboard having problems with the second master node just judging from the alert message.

Can anyone provide some guidance on how to troubleshoot and resolve the alert?

**Comment by brancz** [comment]
This suggests that the dashboard is performing lots of requests that are failing. You should check both the logs of the dashboard as well as the logs of that apiserver.

**Comment by eroji** [comment]
Thank you. I was able to track it down looking at logs of the dashboard pod, which indicated it wasn't able to find Heapter for metrics. Adding an args to point it to the heapter service resolved the alerts.
