### ISSUE TITLE
static_configs / staticTargets does not appear in the configuration file

### ISSUE THREAD

**Issue by yaminisridaran** [coreos/prometheus-operator#1872]
**What did you do?**
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  endpoints:
  - interval: 10s
    port: web
    path: /federate
    params:
      'match[]':
        - '{__name__="up"}'
    static_configs:
        - targets: ['10.15.10.91:30200']

**What did you expect to see?**
I expected to see the 10.15.10.91:30200 in targets

**What did you see instead? Under which circumstances?**
Targets is empty

**Environment**
kubernetes cluster

* Prometheus Operator version: 0.23.2

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by yaminisridaran** [comment]
I tried staticTargets - ['10.15.10.91:30200'] in servicemonitor

**Comment by brancz** [comment]
@metalmatze I think we reverted the static configs feature no?

I think easiest would be to make use of the additionalScrapeConfigs feature to specify arbitrary Prometheus configuration.

**Comment by metalmatze** [comment]
Yes, we've reverted the static configs feature before it got into any release.
It is superseded by the additionalScrapeConfigs, as you've said.

**Comment by yaminisridaran** [comment]
Thank you for the response. Do we have doc for additionalScrapeConfigs? I have a used case to provide static ip as endpoint in servicemonitor and consul_sd_config endpoint in servicemonitor.

**Comment by metalmatze** [comment]
I found an example in here:
https://github.com/coreos/prometheus-operator/blob/4d9a8af878be4427be34e42cde4fe40bf9d0c522/helm/prometheus/values.yaml#L353

**Comment by yaminisridaran** [comment]
Thank you. additionalScrapeConfigs works with static_config. Can I use consul_sd_config and any other service discovery with additionScrapeConfigs?

**Comment by brancz** [comment]
yes, `additionalScrapeConfigs` expects exactly the upstream `<scrape_config>` as an array: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cscrape_config%3E

**Comment by yaminisridaran** [comment]
Thank you.

**Comment by yaminisridaran** [comment]
Can I close this issue?
