### ISSUE TITLE
prometheus oom killed

### ISSUE THREAD

**Issue by phantooom** [coreos/prometheus-operator#1873]
**What did you do?**
i have a 500+ node k8s cluster, 2000+  target, 4000+ pod ,  but prometheus node only have 64g mem, i gave  prometheus 50g mem but it oom frequently。 in our env controller(for prometheus, api server etcd ,etc.) node can not scale up, so i want scale out prometheus node, in original prometheus it support use sharding(hashmod) sacle out（https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config），but in prometheus-operator i can find any config for this, there is only one doc （https://github.com/coreos/prometheus-operator/blob/master/Documentation/high-availability.md#prometheus）say it sharding will support in the feature。 

**Environment**
prometheus 2.0-rc.1
linux kernel 1.10.0-693

* Prometheus Operator version:
prometheus-operator 0.14.0

* Kubernetes version information:
k8s 1.9

1. is there any way work around to avoid oom
2. when will you support sharding

**Comment by brancz** [comment]
I’m happy with introducing sharding, but I’d like to clarify expected semantics first. The way I see it there are two choices: Should the concrete shard be specified in the Prometheus object directly and it’s up to the user to setup sharding appropriately, or should just the number of total shards be specified and .spec.replicas amount of replicas are automatically setup per shard. I’m tending towards the latter but also wondering, should each shard be it’s own statefulset?

cc @mxinden @squat @s-urbaniak @metalmatze

**Comment by mxinden** [comment]
I feel like the user should just need to set the number of shards and the Prometheus Operator configures the rest. Each shard would then be a Kubernetes statefulset.

**Comment by metalmatze** [comment]
@mxinden: I feel like having an array with an array of ServiceMonitor names for each shard feels better. Otherwise one shard might have multiple intense targets? 🤔 
I'm thinking of:
```
[
  [node-exporter],
  [prometheus, prometheus-operator, alertmanager],
  [kube-state-metrics],
]
```

**Comment by squat** [comment]
@metalmatze and non-explicitly specified ServiceMonitors are distributed among those shards?

**Comment by brancz** [comment]
I think Max's suggestion sounds good, and big chunk of work :slightly_smiling_face:, but we'll need this so we should work towards getting this down.

**Comment by phantooom** [comment]
thx: @brancz @mxinden @metalmatze @squat  
now i know  prometheus-operator not support sharding now
is there any way work around for this, can i change some params to reduce mem?
-------------------
when blueprint  was finished , i am happy to contribute to this features.

**Comment by brancz** [comment]
You can already apply functional sharding, meaning only assign a subset of jobs/ServiceMonitors to a single Prometheus server.

**Comment by phantooom** [comment]
@brancz thx is there any docs link?

**Comment by brancz** [comment]
Not really, you just need to use the `serviceMonitorSelector` of the `Prometheus` object to select the objects you want. Just like any other Kubernetes object with a selector.

**Comment by phantooom** [comment]
@brancz thx closed this issue
