### ISSUE TITLE
Grafana image args

### ISSUE THREAD

**Issue by eroji** [coreos/prometheus-operator#1882]
I am trying to expose Grafana via Nginx ingress rule but it's giving me some problems because I am trying to run it under a context path of /grafana. It appears the image supports custom args but I can't find any info on what args are supported. Are there any documentation on how to set this root url so that Nginx ingress rule routes to it correctly?

**Comment by metalmatze** [comment]
I think you're looking for this configuration option in Grafana:
http://docs.grafana.org/installation/configuration/#root-url
Also note that the Prometheus Operator uses [brancz/kubernetes-grafana](https://github.com/brancz/kubernetes-grafana). An example with a custom configuration file and be found here: https://github.com/brancz/kubernetes-grafana/blob/master/examples/custom-ini.jsonnet.

As this is not directly related to the Prometheus Operator I suggest you open an issue there if you still have problems.
