### ISSUE TITLE
Typo in build.sh: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#compiling

### ISSUE THREAD

**Issue by dmcnaught** [coreos/prometheus-operator#1885]
$1 doesn't resolve in build.sh in README: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#compiling
PR incoming.

**Comment by mxinden** [comment]
I am closing here as well. @dmcnaught first of all, still thanks for reporting the issue. This is highly appreciated. Second of all I am curious what the actual issue is, so please keep us updated.

**Comment by dmcnaught** [comment]
I get this when I added these two lines to build.sh
```
echo  "${1}-example.jsonnet"
echo  "${1-example.jsonnet}"
```
```
./build.sh welltok
+ echo welltok-example.jsonnet
welltok-example.jsonnet
+ echo welltok
welltok
```

**Comment by dmcnaught** [comment]
Right - of course. For some reason I assuming it was working differently. 
Sorry.
