### ISSUE TITLE
Allow custom configuration of services

### ISSUE THREAD

**Issue by bigkraig** [coreos/prometheus-operator#189]
In our deployment we need to use NodePorts for my ingress. What we do now is add a second service but it would be best to configure the one made by the operator.

It'd also be nice to be able to add annotations, so that we can do things like add  a `service.beta.kubernetes.io/external-traffic: OnlyLocal` annotation

**Comment by brancz** [comment]
The `Service`s created by the Operator (`alertmanager-operated` and `prometheus-operated`) are only used by the `StatefulSet`s as a governing `Service` to be able to have stable DNS names for each Prometheus/Alertmanager `Pod`. In fact they are headless, so they don't have a Cluster IP, therefore they are not even routable, and they are reconciled by the Prometheus Operator to ensure they are in this state.

Configuring a `Service` for access to the web UI is entirely left up to the user as there are endless possibilities to configure `Service`s for that purpose. Is there a reason I'm missing why the Prometheus Operator would be better suited to manage `Service`s used for this purpose?

**Comment by bigkraig** [comment]
My complaint was that they were called `prometheus` and `alertmanager` but it looks like I was on an old version of the operator. It's much more clear in v0.6.0.

**Comment by brancz** [comment]
Great! Happy we could solve that :slightly_smiling_face:
