### ISSUE TITLE
Summary Reports - Feature request

### ISSUE THREAD

**Issue by nrshrivatsan** [coreos/prometheus-operator#1900]
*Feature Request*

1. Periodic communications
2. Outlier detection

*Background*

- When using Prometheus Operator to monitor my cluster, I need to spot patterns
- Anti Patterns and Effective Patterns
- As the Budgeting personnel for a Kubernetes clusters, I need following
  - Prometheus graphs + Alert Manager alerts (Silenced/critical)
- Cadence needs to be configurable
1. Daily
2. Weekly
3. Monthly

/feature-request

**Comment by brancz** [comment]
The Prometheus Operator project is about managing the lifecycle of Prometheus and Alertmanager servers. What you are looking for is a feature set that can be built around this, but is out of scope for this project.
