### ISSUE TITLE
Monitoring gcePersistentDisk via kubelet_volume_stats_available_bytes ?

### ISSUE THREAD

**Issue by gytisgreitai** [coreos/prometheus-operator#1904]
Is there a way to see gce disks volume usage via prometheus?

e.g. given sample pod config:

```        volumeMounts:
          - mountPath: /exports
            name: gce-test-disk
      volumes:
        - name: gce-test-disk
          gcePersistentDisk:
            pdName: gce-test-disk
            fsType: ext4
```

Is it possible to see used/free space via kubelet_volume_stats_available_bytes (or any other metric?)
GCE volume plugin does implement Metris interface, and I can see volume stats for regular PVC, but not for `gcePersistentDisk`

**Environment**

* Prometheus Operator version:

v0.22.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.1", GitCommit:"7221ffe8776f399448d61b4dc9edb5c69232aece", GitTreeState:"clean", BuildDate:"2018-08-29T23:11:12Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	GKE

**Comment by brancz** [comment]
That would be an upstream concern, generally I understand the need to monitor this, but I also wonder why you don't provision this via a PVC which has proper support for this?

**Comment by metalmatze** [comment]
This should be configurable by the Kubelet, right? I was looking into that myself and I don't see these either. I don't think it has to do with configuration in the Prometheus Operator though.

**Comment by gytisgreitai** [comment]
I just thought I was overlooking something, but PVC will have to do.

Why not PVC right now? Long story short - custom internal tool that creates disks on gce and long running cron jobs on kubernetes, so it was less state to cleanup directly using gcePersistentDisk instead of PVC. But we'll just change that.

thanks again for the awesome tool.
