### ISSUE TITLE
kube-prometheus: kube-state-metrics RBAC issue (forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot)

### ISSUE THREAD

**Issue by jolson490** [coreos/prometheus-operator#1908]
**What did you do?**

Install/deploy kube-prometheus to one of our K8s clusters running in AWS.

**What did you expect to see?**

kube-state-metrics to work.

**What did you see instead? Under which circumstances?**

I have no idea as to the cause (I made no changes to how kube-prometheus defines kube-state-metrics out-of-the-box), but in one of our clusters kube-state-metrics stopped working - the following prom alerts (`KubeStateMetricsDown` & `TargetDown`) were firing:

![screen shot 2018-09-17 at 9 01 07 am](https://user-images.githubusercontent.com/15840507/45627763-3f7f5d00-ba58-11e8-9b98-c510eb2df4f4.png)

And the prom `/targets` page showed `kube-state-metrics (0/2 up)` (and the Error column for each of the 2 kube-state-metrics Endpoints said `server returned HTTP status 401 Unauthorized`).

**Workaround?**

Simply re-deploying kube-prometheus cleared up the issue.

(I'll try to remember to add a comment to this issue if/when I observe this problem happen again.)

**Environment**

Versions from our jsonnetfile.lock.json: kube-prometheus: [356dce2 8/14](https://github.com/coreos/prometheus-operator/commit/356dce2) (~ [v0.23.1](https://github.com/coreos/prometheus-operator/tree/v0.23.1/contrib/kube-prometheus)), prometheus-operator: [82ac491 8/6](https://github.com/coreos/prometheus-operator/commit/82ac491) ([v0.23.0](https://github.com/coreos/prometheus-operator/tree/v0.23.0)).

* Kubernetes version information:

```
core@ip-192-168-101-52 ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5+coreos.0", GitCommit:"e20e523e857fc8002f6ba2ebcdb3bc61bb87ab76", GitTreeState:"clean", BuildDate:"2018-07-02T17:26:49Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Custom terraform cloud-init scripts.

* Manifests:

```
core@ip-192-168-101-52 ~ $ kubectl describe clusterrole kube-state-metrics
Name:         kube-state-metrics
Labels:       app=kube-state-metrics
              chart=kube-state-metrics-0.1.0
              heritage=Tiller
              release=kube-state-metrics
Annotations:  <none>
PolicyRule:
  Resources                             Non-Resource URLs  Resource Names  Verbs
  ---------                             -----------------  --------------  -----
  endpoints                             []                 []              [list watch]
  limitranges                           []                 []              [list watch]
  namespaces                            []                 []              [list watch]
  nodes                                 []                 []              [list watch]
  persistentvolumeclaims                []                 []              [list watch]
  persistentvolumes                     []                 []              [list watch]
  pods                                  []                 []              [list watch]
  replicationcontrollers                []                 []              [list watch]
  resourcequotas                        []                 []              [list watch]
  services                              []                 []              [list watch]
  statefulsets.apps                     []                 []              [list watch]
  horizontalpodautoscalers.autoscaling  []                 []              [list watch]
  cronjobs.batch                        []                 []              [list watch]
  jobs.batch                            []                 []              [list watch]
  daemonsets.extensions                 []                 []              [list watch]
  deployments.extensions                []                 []              [list watch]
  replicasets.extensions                []                 []              [list watch]
```

* Prometheus Operator Logs:

The k-p pods:
```
core@ip-192-168-101-52 ~ $ kubectl -n monitoring get pods
NAME                                   READY     STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2       Running   0          2d
alertmanager-main-1                    2/2       Running   0          2d
alertmanager-main-2                    2/2       Running   0          2d
grafana-54d8db4bc4-q9k7f               1/1       Running   0          2d
kube-state-metrics-6647556f79-n2qbx    4/4       Running   0          2d
node-exporter-56ldd                    2/2       Running   0          2d
node-exporter-5r4gn                    2/2       Running   0          2d
node-exporter-8j87p                    2/2       Running   0          2d
node-exporter-c7thp                    2/2       Running   0          2d
node-exporter-hwd9x                    2/2       Running   0          2d
node-exporter-jv52k                    2/2       Running   0          2d
node-exporter-mf57p                    2/2       Running   0          2d
node-exporter-n4w5x                    2/2       Running   0          2d
node-exporter-pdtk2                    2/2       Running   0          2d
node-exporter-rk4hw                    2/2       Running   0          2d
node-exporter-rszzg                    2/2       Running   0          2d
node-exporter-rtsxt                    2/2       Running   0          2d
node-exporter-rxxzt                    2/2       Running   0          2d
node-exporter-wwgvj                    2/2       Running   0          2d
node-exporter-xqczv                    2/2       Running   0          2d
prometheus-k8s-0                       3/3       Running   0          2d
prometheus-k8s-1                       3/3       Running   0          2d
```

Running `kubectl -n monitoring logs kube-state-metrics-6647556f79-n2qbx -c kube-state-metrics` prints a bunch of lines like the following (this is only a subset of some of the error messages):
```
E0917 12:43:55.667874       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1beta1.Deployment: deployments.extensions is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list deployments.extensions at the cluster scope
E0914 21:26:45.477467       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1beta1.ReplicaSet: replicasets.extensions is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list replicasets.extensions at the cluster scope
E0914 21:26:58.201383       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list namespaces at the cluster scope
E0914 21:27:27.180244       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list endpoints at the cluster scope
E0914 21:27:35.589263       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1.ResourceQuota: resourcequotas is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list resourcequotas at the cluster scope
E0914 21:28:42.454194       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list persistentvolumeclaims at the cluster scope
E0914 21:28:56.391388       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list services at the cluster scope
E0914 21:29:23.659176       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1beta1.CronJob: cronjobs.batch is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list cronjobs.batch at the cluster scope
E0914 21:30:03.287403       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/collectors.go:62: Failed to list *v1beta1.DaemonSet: daemonsets.extensions is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list daemonsets.extensions at the cluster scope
```

**Comment by brancz** [comment]
Thanks for reporting! This sounds like the issue may be with the kube-rbac-proxy as that is the only thing that ever returns 401 or 403 to Prometheus, next time this occurs it would be interesting to see the logs of that.

**Comment by jolson490** [comment]
thanks Frederic.

It happened again - to be thorough I grabbed everything (please see the attached files; though I'm not sure how much they will help - kube-rbac-proxy-main.log & kube-rbac-proxy-self.log & addon-resizer.log appear to just have a bunch more `User "system:serviceaccount:monitoring:kube-state-metrics" cannot` errors like what I mentioned above from the logs for the `kube-state-metrics` container):
```
core@ip-192-168-101-52 ~/9-19 $ kubectl -n monitoring logs kube-state-metrics-6647556f79-zxr2f
Error from server (BadRequest): a container name must be specified for pod kube-state-metrics-6647556f79-zxr2f, choose one of: [kube-rbac-proxy-main kube-rbac-proxy-self kube-state-metrics addon-resizer]
core@ip-192-168-101-52 ~/9-19 $ kubectl -n monitoring logs kube-state-metrics-6647556f79-zxr2f -c kube-rbac-proxy-main > kube-rbac-proxy-main.log
core@ip-192-168-101-52 ~/9-19 $ kubectl -n monitoring logs kube-state-metrics-6647556f79-zxr2f -c kube-rbac-proxy-self > kube-rbac-proxy-self.log
core@ip-192-168-101-52 ~/9-19 $ kubectl -n monitoring logs kube-state-metrics-6647556f79-zxr2f -c kube-state-metrics > kube-state-metrics.log
core@ip-192-168-101-52 ~/9-19 $ kubectl -n monitoring logs kube-state-metrics-6647556f79-zxr2f -c addon-resizer > addon-resizer.log
```

Just curious, what is the impact of this issue? 
 * Does it mean kube-prometheus is totally in the dark - i.e. there's a 0% chance of any prom alert firing? (My understanding is kube-state-metrics is for "cluster-level metrics".)
 * Or is some monitoring still happening (because the node-exporter targets are still up/green)?

Just in the interest of full disclosure: we had a helm deployment of kube-state-metrics to the default namespace of this cluster of ours, but I deleted that deployment. (It was a totally separate instance of kube-state-metrics - which I believe would have no effect on anything in the "monitoring" namespace.)

[addon-resizer.log](https://github.com/coreos/prometheus-operator/files/2402831/addon-resizer.log)
[kube-rbac-proxy-self.log](https://github.com/coreos/prometheus-operator/files/2402832/kube-rbac-proxy-self.log)
[kube-rbac-proxy-main.log](https://github.com/coreos/prometheus-operator/files/2402833/kube-rbac-proxy-main.log)

**Comment by brancz** [comment]
Looking at those logs and the original issue again I think your ClusterRole is just missing these roles: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/kube-state-metrics-clusterRole.yaml#L58-L69

**Comment by jolson490** [comment]
Thanks very much Frederic for helping pinpoint the problem... That part of `kube-state-metrics-clusterRole.yaml` has been there for a couple months, and I'm using a newer version of k-p (that includes that part). After re-deploying k-p (and no alerts are firing), here's what that ClusterRole looks like now (it has the pieces you pointed out):
```
core@ip-192-168-101-52 ~ $ kubectl describe clusterrole kube-state-metrics
Name:         kube-state-metrics
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources                                  Non-Resource URLs  Resource Names  Verbs
  ---------                                  -----------------  --------------  -----
  configmaps                                 []                 []              [list watch]
  endpoints                                  []                 []              [list watch]
  limitranges                                []                 []              [list watch]
  namespaces                                 []                 []              [list watch]
  nodes                                      []                 []              [list watch]
  persistentvolumeclaims                     []                 []              [list watch]
  persistentvolumes                          []                 []              [list watch]
  pods                                       []                 []              [list watch]
  replicationcontrollers                     []                 []              [list watch]
  resourcequotas                             []                 []              [list watch]
  secrets                                    []                 []              [list watch]
  services                                   []                 []              [list watch]
  daemonsets.apps                            []                 []              [list watch]
  deployments.apps                           []                 []              [list watch]
  replicasets.apps                           []                 []              [list watch]
  statefulsets.apps                          []                 []              [list watch]
  tokenreviews.authentication.k8s.io         []                 []              [create]
  subjectaccessreviews.authorization.k8s.io  []                 []              [create]
  horizontalpodautoscalers.autoscaling       []                 []              [list watch]
  cronjobs.batch                             []                 []              [list watch]
  jobs.batch                                 []                 []              [list watch]
  daemonsets.extensions                      []                 []              [list watch]
  deployments.extensions                     []                 []              [list watch]
  replicasets.extensions                     []                 []              [list watch]
```

So now the question is do you by chance have any idea as to how this ClusterRole could've seemingly been modified some amount of time after k-p was deployed? I don't think anyone I work with would've done any action on this cluster to modify the ClusterRole (to delete `tokenreviews` & `subjectaccessreviews ` from the ClusterRole).

**Comment by brancz** [comment]
> Just in the interest of full disclosure: we had a helm deployment of kube-state-metrics to the default namespace of this cluster of ours, but I deleted that deployment. (It was a totally separate instance of kube-state-metrics - which I believe would have no effect on anything in the "monitoring" namespace.)

This actually sounds like it could exactly be what caused this, as the tokenreview and subjectaccessreview is an opinionated addition the kube-prometheus project adds on top of kube-state-metrics for authentication and authorization purposes.

**Comment by jolson490** [comment]
ah, sorry for the user error on my part - and thank you Frederic for figuring this out for me.

For anyone curious, just to confirm what Frederic found, I reproduced the problem by doing the following:
 * un-deployed kube-prometheus from the cluster.
 * used helm to deploy kube-state-metrics to the kube-system namespace.
 * re-deployed k-p, then right away KubeStateMetricsDown & TargetDown were firing.

(I'm closing this issue.)

**Comment by antonyaugustus** [comment]
need some help with kube-prometheus-exporter-kube-state

The pod goes into "CrashLoopBackOff". Here are logs from the kubelet. I am trying to see if anyone has come across this issue.

kubelet: E0225 20:49:43.160503   70914 pod_workers.go:186] Error syncing pod aa43554f-391a-11e9-baca-005056a7d90a ("kube-prometheus-exporter-kube-state-689f8f9bd6-vcwcf_monitoring(aa43554f-391a-11e9-baca-005056a7d90a)"), skipping: failed to "StartContainer" for "exporter-kube-state" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=exporter-kube-state pod=kube-prometheus-exporter-kube-state-689f8f9bd6-vcwcf_monitoring(aa43554f-391a-11e9-baca-005056a7d90a)"
