### ISSUE TITLE
Import multiple Prometheus Datasources to Grafana

### ISSUE THREAD

**Issue by jungopro** [coreos/prometheus-operator#1920]
**What did you do?**

tried to modifie the `datasource{}` value in [the values.yaml file](https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/values.yaml) 

**What did you expect to see?**

Datasources in the grafana web ui

**What did you see instead? Under which circumstances?**

No datasources appeared in the web ui or the logs. grafana-watcher didn't report importing any dashboards

**Environment**

kube-prometheus chart deployed on kubernetes 1.9

* Kubernetes cluster kind: 

	kubespray

I'm pretty sure I'm not following the correct syntax. Can you please provide an example on how to add multiple datasources to the helm chart referred above?

Thanks
Omer

**Comment by oded-dd** [comment]
I have the same issue with kubernetes 1.10 see the issue I have opened `Add datasource by configuration to Grafana does not work #1909`

**Comment by brancz** [comment]
As a side note, the jsonnet based stack has the possibility to configure any number of datasources: https://github.com/brancz/kubernetes-grafana/blob/9a20f81c9007e4c7409dd0b3edda1a7a78ad2c63/grafana/grafana.libsonnet#L17-L25

**Comment by eskp** [comment]
What I did is this:
1. export the configured datasource from Grafana with curl
2. created a ConfigMap manifest in the same way as you'd do for a dashboard by following this https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#customizing-kube-prometheus
3. the only change from dashboard is you have to name it "-datasource" and not "-dashboard"
4. add this name to Grafana chart's values file under serverDashboardConfigmaps key

**Comment by jungopro** [comment]
My use case was a single, separate Grafana that needs to connect to multiple Prometheus operator data source. 
The Grafana deployment itself didn’t have to be connected to Prometheus operator deployment.
I ended up using the official Grafana helm chart which has this functionality built in.
@brancz is there a path to implement that same functionality in the kube-Prometheus helm chart as well?

**Comment by vsliouniaev** [comment]
@jungopro The charts have been merged into helm/charts, and use the official grafana helm chart, this should allow you to load additional datasources from configmaps

**Comment by jungopro** [comment]
I was able to make it work, thank you
