### ISSUE TITLE
anti-affinity mixin for kube-prometheus

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#1930]
Currently the kube-prometheus stack comes with no anti-affinity rules defined for Alertmanagers or Prometheus servers, which could cause them to all be scheduled onto the same nodes. If that node goes down, then all of monitoring would be down. This is a situation we should allow to be easily avoided.

I propose to add a mixin for the kube-prometheus stack, so that no two Alertmanagers and Prometheus servers created through the same object are scheduled onto the same node.

@mxinden @squat @s-urbaniak @metalmatze

**Comment by metalmatze** [comment]
I can create a PR for this, if no one is working on this already.
