### ISSUE TITLE
Prometheus crashes if container filesystem is readonly

### ISSUE THREAD

**Issue by Dirbaio** [coreos/prometheus-operator#1932]
I'm trying to run Prometheus in a cluster with a PodSecurityPolicy with `readOnlyRootFilesystem: true`. This makes the Docker copy-on-write filesystem read-only for all containers. (EmptyDirs and other volumes are still RW).

The issue is that Prometheus seems to be trying to write logs to `/tmp`, and crashes when trying to do so because `/tmp` is read-only.

```
level=info ts=2018-09-25T08:01:08.817073731Z caller=main.go:222 msg="Starting Prometheus" version="(version=2.3.2, branch=HEAD, revision=71af5e29e815795e9dd14742ee7725682fa14b7b)"
level=info ts=2018-09-25T08:01:08.817152152Z caller=main.go:223 build_context="(go=go1.10.3, user=root@5258e0bd9cc1, date=20180712-14:02:52)"
level=info ts=2018-09-25T08:01:08.817174245Z caller=main.go:224 host_details="(Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2018-09-25T08:01:08.817191222Z caller=main.go:225 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-09-25T08:01:08.818255816Z caller=main.go:533 msg="Starting TSDB ..."
level=info ts=2018-09-25T08:01:08.819382604Z caller=web.go:415 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-09-25T08:01:18.290956912Z caller=main.go:543 msg="TSDB started"
level=info ts=2018-09-25T08:01:18.291056915Z caller=main.go:603 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2018-09-25T08:01:18.293686685Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.294965143Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.295686173Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.297812579Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.298768089Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.299530479Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-09-25T08:01:18.300306002Z caller=main.go:629 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2018-09-25T08:01:18.30034456Z caller=main.go:502 msg="Server is ready to receive web requests."
W0925 08:14:37.417373       1 reflector.go:323] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:287: watch of *v1.Endpoints ended with: too old resource version: 41104430 (41104534)
log: exiting because of error: log: cannot create log: open /tmp/prometheus.prometheus-prometheus-0.unknownuser.log.WARNING.20180925-081437.1: read-only file system
```

This could be fixed by adding an EmptyDir in `/tmp`, or, preferably, to get Prometheus to not write to `/tmp`. (not sure how, maybe a cmdline flag?)

The isssue is that I don't see any way to get the operator to add a custom volume or a custom flag to the managed Prometheus statefulsets.

* Prometheus Operator version: quay.io/coreos/prometheus-operator:v0.23.2
* Kubernetes version information: v1.11.1
* Kubernetes cluster kind: kubeadm, GCE

**Comment by brancz** [comment]
I think we should instead change Prometheus to not ever even attempt to log to `/tmp`. This is a glog thing and if I recall correctly it's possible to turn this off via some flag, and we could do this programmatically in Prometheus.

**Comment by mxinden** [comment]
Yes, the flag is [`--logtostderr=true`](https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml#L101). Could you try adding that flag @Dirbaio? Make sure to kill the Prometheus Operator deployment before changing the statefulset, otherwise the Prometheus Operator will just overwrite your change right away.

**Comment by geekofalltrades** [comment]
I'm having this issue as well (but not with the operator). We instead have a Prometheus v2.4.2 binary in a from-scratch container running as a non-root user. There is no /tmp directory in the container.

When I try to add a --logtostderr flag, I just get:

```
Error parsing commandline arguments: unknown long flag '--logtostderr'
prometheus: error: unknown long flag '--logtostderr'
```

**Comment by jeffwatts** [comment]
I was hitting this problem, too, and adding the flag `--logtostderr=true` caused the prometheus-k8s pod to enter a crash loop because the prometheus container didn't know what to do with the flag. Right now I've worked around it by scaling down the prometheus-operator deployment down to 0 replicas, adding an EmptyDir volume called tmp and mounting it at `/tmp` on the prometheus pod, then scaling prometheus-operator back up. This seems to be working for now.

**Comment by metalmatze** [comment]
In https://github.com/prometheus/prometheus/pull/4931 glog was replaced by a shim to actually use the gokit logger that Prometheus uses as a default. For all Prometheus versions starting from v2.6 and above there should be no more glog attempting to write to `/tmp`
