### ISSUE TITLE
should create-servicemonitor-job.yaml use a newer version of coreos image

### ISSUE THREAD

**Issue by ensonic** [coreos/prometheus-operator#1936]
installing the prometheus operator using helm will spin up a 'prometheus-operator-create-sm-job' though the helm hook. This pulls quay.io/coreos/hyperkube:v1.7.6_coreos.0 (210.3 MB) just to run:
./kubectl apply -f /tmp/servicemonitor/servicemonitor-operator.yaml

Unfortunately this sometimes is slow, which makes helm run over the default 300s --timeout and the install/upgrade fails. The bad part here is that it leave the cluster in a bad state - the sm-job won#t be deleted and further installs will fail. While this should be fixed on the helm side, two questions:

- why aren't you using helms crd-install hook?
https://github.com/helm/helm/blob/master/docs/charts_hooks.md#defining-a-crd-with-the-crd-install-hook

- what about bumping to the latest coreos image v1.10.5_coreos.0 (188.9 MB), the one you are using is ~ 2 year old.

**Comment by vsliouniaev** [comment]
@caiobegotti I think part of the slowness to respond to this issue is that the helm charts have been in the process of being migrated to https://github.com/helm/charts. This is now complete, could you see if this fixes your issue. Please be aware, there are significant changes to the way the chart is deployed between here and helm/charts

**Comment by ensonic** [comment]
Thanks. I'll have to figure how to change our bazel.io build rules to work with the new setup, as there are no binary releases (or are there releases to a storage bucket like the previous https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/)?

**Comment by vsliouniaev** [comment]
The charts come from the official helm repository now (https://kubernetes-charts.storage.googleapis.com/)

**Comment by ensonic** [comment]
Thanks for your help. I don't see any jobs in the new helm charts anymore. Hence closing this :)

**Comment by ensonic** [comment]
Seem that things got also rename on the way. Is there a migration doc?

```
# this one got a lot bigger
https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/prometheus-operator-0.0.29.tgz
-> https://storage.googleapis.com/kubernetes-charts/prometheus-operator-0.1.6.tgz

# whats the new version here?
https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/kube-prometheus-0.0.105.tgz
-> ???

# this looks like a huge change in the version
https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/prometheus-0.0.51.tgz
-> https://storage.googleapis.com/kubernetes-charts/prometheus-7.3.3.tgz
```
