### ISSUE TITLE
prometheus operator creates a second prometheus pod with no permissions

### ISSUE THREAD

**Issue by ricktbaker** [coreos/prometheus-operator#1971]
**What did you do?**

I've tried this in different orders, with the same results:

`helm install coreos/prometheus --name prometheus  --namespace monitoring`
`helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring`

All default values for the helm charts and this brings up the following pods:

```
prometheus-operator-d75587d6-fw689                      1/1       Running   0          16h
prometheus-prometheus-0                                 3/3       Running   1          16h
```

**What did you expect to see?**

Exactly what I saw at this point.  Everything is working as it should be.  My custom ServiceMonitors are working and life is good.

**What did you see instead? Under which circumstances?**

At some point in the past 24 hours since installing this, a new pod has come up

```
prometheus-prometheus-operator-0                        3/3       Running   1          8m
```

The runtime isn't accurate because I killed the pod and it recreated while testing.   Anyways, this pod doesn't have proper permissions and is full of errors such as

```
level=error ts=2018-10-03T03:46:11.51399747Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot list services in the namespace \"monitoring\""
level=error ts=2018-10-03T03:46:11.867251178Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to watch *v1.Pod: unknown (get pods)"
level=error ts=2018-10-03T03:46:11.867458129Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to watch *v1.Pod: unknown (get pods)"
level=error ts=2018-10-03T03:46:12.511519828Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot list endpoints in the namespace \"monitoring\""
level=error ts=2018-10-03T03:46:12.515569155Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot list services in the namespace \"monitoring\""
```

It appears the operator created a new prometheus pod.  If this is how it should be instead of my creating one first, then that is fine, but this created pod doesn't have proper permissions to the monitoring namespace for some reason.  Perhaps I just need to add that to the namespaces that prometheus has access to, but I'm not sure how to do so via the operator and helm

** Kubernetes cluster kind: **

EKS

**Comment by ricktbaker** [comment]
I think this may have been a misunderstanding on my part.  I restarted, created the prometheus-operator via helm in the monitoring namespace, and then created prometheus via helm inside the default namespace (where everything lives that I want to monitor at this point). 

So far, so good.

My question is do I need to install prometheus into each namespace I want to monitor, or is it possible to allow prometheus to monitor multiple namespaces?  Example in my original setup, if I do have things to monitor in the "monitoring" namespace, how should I be configuring this different to avoid the errors I was encountering?

**Comment by squat** [comment]
If you want to monitor workloads in multiple namespaces then you must ensure that:
- the prometheus operator is watching the target namespace;
- the workload services in question are properly labeled and selected by a ServiceMonitor deployed in that namespace [0];
- the namespaces you are interested in are labeled with labels that match the `serviceMonitorNamespaceSelector` [1] in your Prometheus object; and
- the ServiceMonitor is labeled with labels that match the `serviceMonitorSelector` [2] in your Prometheus Object.

[0] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L458
[1] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L65
[2] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L62

**Comment by ricktbaker** [comment]
@squat Thanks, I believe I have the last 3 bullet points covered, I just quite haven't figured out how to adjust the target namespaces that the prometheus operator is watching via helm variables.

**Comment by squat** [comment]
@ricktbaker looking at the helm templates, it seems that no `--namespaces` flag is passed to the operator, this means that by default the operator will watch all namespaces. :+1:

**Comment by ricktbaker** [comment]
Ok, so I guess my question now is an overall design perspective.   So 1 operator for all namespaces, but should there be a single prometheus for all namespaces as well?   We don't have huge clusters with hundreds of pods, so I'm guessing 1 prometheus should be able to handle as long as that setup is possible.

**Comment by squat** [comment]
Yes, that setup is certainly possible. As long as you are happy with one single prometheus scraping everything, and thus the result that any cluster user who can query prometheus can see cluster-wide metrics, then this is fine. If you want to restrict what metrics users can see, then you'll need different promethei, since a single prometheus is currently not capable of handling multi-tenancy.

**Comment by ricktbaker** [comment]
Thanks.  I'll go ahead and close this out now.   Appreciate the help.
