### ISSUE TITLE
Proprietary markings in Kibana, Grafana

### ISSUE THREAD

**Issue by shaaam** [coreos/prometheus-operator#1975]
We are trying to insert Proprietary markings (company name) in Kibana and Grafana dashboards. We have this in place for Nagios where the code is embedded along with code for other sidebar items. We are not trying to figure out how to get this for Kibana and Grafana dashboards. Any help here is much appreciated. Thanks!

**Comment by metalmatze** [comment]
Hey,
we are creating the Prometheus Operator and are only users of Grafana ourselves. We don't use Kibana in this project. Please ask the Grafana and Kibana people themselves. Thanks.

**Comment by shaaam** [comment]
ah, apologize for that. i ll close it out.
