### ISSUE TITLE
Setup prometheus on my cluster.

### ISSUE THREAD

**Issue by bernyemmanuel** [coreos/prometheus-operator#1978]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by squat** [comment]
@bernyemmanuel it looks like you posted only the issue template and forgot to fill it in. What issue are you seeing? Can you edit the issue body and insert the pertinent details?
