### ISSUE TITLE
skipped value for additionalScrapeConfigs: Not a table

### ISSUE THREAD

**Issue by infa-ddeore** [coreos/prometheus-operator#1981]
**What did you do?**
I am trying additional-scrape-configs example from https://github.com/coreos/prometheus-operator/tree/master/example/additional-scrape-configs it gives the warning:

    $ helm install coreos/kube-prometheus --set alertmanager.config.global.opsgenie_api_key=xxxxxx --name kube-prometheus --namespace monitoring -f override.yaml
    2018/10/06 08:42:23 warning: skipped value for additionalScrapeConfigs: Not a table. 
    2018/10/06 08:42:23 warning: skipped value for additionalScrapeConfigs: Not a table.

override.yaml:
```
prometheus:
  externalLabels:
    cluster_name: aws-us-west-2
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
````

**What did you expect to see?**
Prometheus pod with additional scrape config.

**What did you see instead? Under which circumstances?**
There is no additional scrape config.

**Environment**

* Prometheus Operator version:

	prometheus-operator-0.0.29

* Kubernetes version information:

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", 
    GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", 
    BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

    It is AWS EKS

* Manifests:

```
https://github.com/coreos/prometheus-operator/tree/master/example/additional-scrape-configs
```

* Prometheus Operator Logs:

```
level=info ts=2018-10-06T03:22:26.662612553Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.670854964Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.699447084Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.718611793Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.729231853Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.782851944Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:26.836648469Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:31.916668962Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:32.260969709Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:39.003419878Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:46.179902966Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:46.217292784Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:53.701471055Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:53.744240495Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:22:55.71089108Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:23:28.226458364Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:23:28.269146415Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-10-06T03:24:06.658357697Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
```

**Comment by squat** [comment]
@infa-ddeore it looks to me like helm is throwing a warning here because `additionalScrapeConfigs` is supposed to be a list of scrape configurations in helm [0], not a map. This is a little confusing because the Prometheus CRD declares the `AdditionalScrapeConfigs` as a struct [1]. The reason for this difference, is that the list of configurations will all get packaged into a secret automatically by helm and then configured in the prometheus object for you.

[0] https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/values.yaml#L350-L357
[1] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L164

**Comment by infa-ddeore** [comment]
Thanks for the response @squat 
I followed same example from https://github.com/coreos/prometheus-operator/blob/master/example/additional-scrape-configs/prometheus.yaml, that doesn't show additionalScrapeConfigs as list, it needs to be fixed.

I had tried additionalScrapeConfigs as list as well but didn't mention it before, it fails with config error, prometheus-kube-prometheus-0 logs:
```
level=info ts=2018-10-08T16:04:27.099321878Z caller=main.go:426 msg="Scrape manager stopped"
level=error ts=2018-10-08T16:04:27.09942051Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: unknown fields in scrape_config: key, name"
level=info ts=2018-10-08T16:04:27.09944705Z caller=main.go:584 msg="See you next time!"
```

override.yaml :

```
prometheus:
  externalLabels:
    cluster_name: aws-us-west-2
  additionalScrapeConfigs:
  - name: additional-scrape-configs
    key: prometheus-additional.yaml
```

**Comment by infa-ddeore** [comment]
thx @squat it works now
