### ISSUE TITLE
Prometheus operator does not allow to add custom resources

### ISSUE THREAD

**Issue by swapnilpatil1682** [coreos/prometheus-operator#1982]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by squat** [comment]
@swapnilpatil1682 it looks like you forgot to fill out the form in the issue body. I'll close this issue for now but please add any relevant information and re-open this issue if you still need help.
