### ISSUE TITLE
Missing additionalScrapeConfigs secret blocks all other operator updates

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#1985]
**What did you do?**
Configured a `Prometheus` resource and specified `additionalScrapeConfigs`, but to a secret that does not exist.

**What did you expect to see?**
I think Prometheus should be provisioned but without additionalScrapeConfigs loaded.
If already provisioned, this error should not prevent other configurations from being blocked.

**What did you see instead? Under which circumstances?**
The operator logs an error about not being able to find the secret, but also stops updating other configuration changes, such as memory requirements for the pods.

* Prometheus Operator version:

`0.23.2`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubeadm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  creationTimestamp: 2018-10-08T15:44:41Z
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-0.0.51
    heritage: Tiller
    prometheus: prometheus-platform
    release: prometheus-platform
  name: prometheus-platform
  namespace: monitoring
  resourceVersion: "7460811"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/prometheus-platform
  uid: 120caa49-cb11-11e8-8b49-000d3a383ab3
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: prometheus-prometheus-platform-additional-scrape-configs
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: prometheus
              prometheus: prometheus-platform
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: prometheus-platform-alertmanager
      namespace: monitoring
      port: http
  baseImage: quay.io/prometheus/prometheus
  externalLabels:
    datacenter: westus
    prometheus: platform
  externalUrl: http://prometheus-platform.monitoring:9090
  imagePullSecrets: []
  logLevel: info
  paused: false
  replicas: 1
  resources:
    requests:
      memory: 10Gi
  retention: 24h
  routePrefix: /
  ruleSelector:
    matchLabels:
      rules: prometheus-platform
  serviceAccountName: prometheus-platform
  serviceMonitorSelector:
    matchLabels:
      prometheus: prometheus-platform
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 150Gi
  version: v2.4.2
```

* Prometheus Operator Logs:

```
level=info ts=2018-10-08T15:50:09.403892451Z caller=operator.go:911 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus-platform
E1008 15:50:09.416487       1 operator.go:816] Sync "monitoring/prometheus-platform" failed: creating config failed: loading additional scrape configs from Secret failed: secret prometheus-platform-additional-scrape-configs could not be found
```

**Comment by metalmatze** [comment]
It's a question on how to deal with these errors during reconcile. IMHO we should have the reconciliation failing and then increase the `reconcile_errors_total` metric which we can then alert on. Otherwise the whole situation gets more complicated. I prefer an firing alert over reading log lines.

What do you think, @vsliouniaev?

**Comment by vsliouniaev** [comment]
@metalmatze `prometheus_operator_prometheus_reconcile_errors_total` can definitely be used for the purpose of alerting on the issue like you said. 

I think there are enough distinct components in updating Prometheus configuration that they could be handled separately and provide a better experience. However, if this is too much complexity to add at this point in the project that also makes sense.

I would like to get a sense of whether the project's intended direction is to keep the single reconciliation loop for now or if there's appetite for adding something like this eventually.

**Comment by jakexks** [comment]
This is a big issue if you are using Prometheus operator to manage multiple instances across multi-tenant namespaces. This means someone in one namespace can break another unrelated namespace by creating broken config (if the incorrect namespace is evaluated before the correct one, the correct one never gets updated)

This doesn't just affect additional scrape config, it also applies to any other incorrectly formatted CRD, e.g. PrometheusRule

**Comment by brancz** [comment]
@jakexks I don't see how this particular issue causes others to fail, it only causes the Prometheus instances related to the object that specifies a non-existent secret not to be provisioned. I think I agree with @metalmatze that this is more of a case where we would want to fail rather than silently continue. It's parallel to how secrets have to be present for Pods to mount them.

On incorrectly formatted CRDs I totally agree, we're waiting on upstream improvements on CRDs to fix this once and for all. I've reviewed these features with the apimachinery folks on upstream Kubernetes and they are coming, just no guarantee in which release just yet.

**Comment by vsliouniaev** [comment]
Ok, I see your point in this, thanks for the explanation
