### ISSUE TITLE
How to change  default link of alert on slack

### ISSUE THREAD

**Issue by ankitraijr** [coreos/prometheus-operator#1987]
I have installed Kube-Prometheus in my local kuberentes cluster I have also configured alert manager to send an alert on Slack channel. Now I want to change the default link of slack alert.
I know I have to pass this **web.external-url** as a argument in Alert-manager but in Kube-Prometheus where should I pass this value. 
Is there any way to configure it in **alertmanager-alertmanager.yaml** file given in manifest.
please suggest if there is any other way to achieve this.
Thanks.

**Comment by squat** [comment]
@ankitraijr the alertmanager CRD has a field named `externalURL` [0]. You can use this to specify the URL behind which your Alertmanager is reachable.

[0] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L647

**Comment by ankitraijr** [comment]
Thanks, It's worked like a charm...

**Comment by squat** [comment]
@ankitraijr :tada: . I'll close this for now. Please re-open it if you still find you have issues,
