### ISSUE TITLE
in target page, kube-scheduler && kube-controller-manager always in down status

### ISSUE THREAD

**Issue by boxuan666** [coreos/prometheus-operator#1991]
**What did you do?**
In the target page i found the error as follow 
![_20181010152200](https://user-images.githubusercontent.com/29724642/46719355-4b99bb80-cca0-11e8-8449-0cab67ea738c.png)

**What did you expect to see?**

no error in target page.

* Prometheus Operator version:

prometheusOperator: 'v0.23.2'

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

im using kubeadm deploy the HA k8s cluster in my env and im follow this issue [https://github.com/coreos/prometheus-operator/issues/1859](https://github.com/coreos/prometheus-operator/issues/1859) to deploy the prometheus-operator.
after that found the error like that...

pls help me solve this problem 
thanks!
:(

**Comment by boxuan666** [comment]
another problem in Alters page 
what this item mean?  
+ CPUThrottlingHigh (19 active)

```
alert: CPUThrottlingHigh
expr: 100
  * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total[5m]))
  / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total[5m]))
  > 25
for: 15m
labels:
  severity: warning
annotations:
  message: '{{ printf "%0.0f" $value }}% throttling of CPU in namespace {{
    $labels.namespace }} for {{ $labels.container_name }}.'
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
```
My cluster is almost running without application. There should be no load too high.

**Comment by squat** [comment]
@boxuan666 it looks like you figured out the problem you were having! Would you mind posting your solution or what you learned so that others experiencing the same issue as you can find help?

**Comment by boxuan666** [comment]
```
sed -e "s/- --address=127.0.0.1/- --address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-controller-manager.yaml
sed -e "s/- --address=127.0.0.1/- --address=0.0.0.0/" -i /etc/kubernetes/manifests/kube-scheduler.yaml
```
The above command will help solve **kube-scheduler && kube-controller-manager** problem in target page.

about the  CPUThrottlingHigh im still working on it.....
I don't know how you look at this CPU problem.

**Comment by metalmatze** [comment]
@boxuan666 You should check the request & limits for that container in the pod and see if the cpu settings are too low. If that's not the case you might want to get more or bigger machines.
Feel free to open another issue, but closing this as the cpu throttling discussion is unrelated.
