### ISSUE TITLE
/bin/bash: po-crdgen: command not found

### ISSUE THREAD

**Issue by justlooks** [coreos/prometheus-operator#2007]
have i missed anything ? when i make ,it says "/bin/bash: po-crdgen: command not found"

Already on 'release-1.11'
go install k8s.io/code-generator/cmd/openapi-gen
/root/go/bin/openapi-gen \
-i github.com/coreos/prometheus-operator/pkg/client/monitoring/v1,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1 \
-p github.com/coreos/prometheus-operator/pkg/client/monitoring/v1 \
--go-header-file="/root/go/src/github.com/coreos/prometheus-operator/.header"
go fmt pkg/client/monitoring/v1/openapi_generated.go
go install github.com/coreos/prometheus-operator/cmd/po-crdgen
po-crdgen prometheus > example/prometheus-operator-crd/prometheus.crd.yaml
/bin/bash: po-crdgen: command not found
make: *** [example/prometheus-operator-crd/alertmanager.crd.yaml] Error 127

**Comment by esmail-fahimi** [comment]
@justlooks what was the root cause for this?  I am getting the same error and there no references to po-crdgen anywhere.
