### ISSUE TITLE
Unable to  discover  ServiceMonitor  created in different namespace

### ISSUE THREAD

**Issue by dhirajnitk** [coreos/prometheus-operator#2015]
**What did you do?**
I am using all yamls from  manifests  located in Kube-prometheus. I have services running in different namespace(sandbox). I want to create new service monitors for all those services in the same namespace(sandbox) or monitoring namespace. I notice that prometheus-prometheus.yaml has
 ```
serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
``` 
so they will choose all servicemonitors from all  namepaces.  But the  mongoservicemonitor deployed in either  monitoring or  sandbox are never discovered by the prometheus service running in monitoring.
e.g.  **mongoservicemonitor.yaml**
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
       name: mongodb
  endpoints:
  - targetPort: 27017
```
e.g. **mongodb.yaml** (service)

```
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
```
**What did you expect to see?**
I don't see the  mongodb service monitor in the prometheus service discovery.  I am using latest release of manifests from github and Kubernetes version v1.10.1.

@brancz

**Comment by brancz** [comment]
This could be due to multiple reasons. Could you share the generated configuration that is shown in the `/config` page of the Prometheus UI?

**Comment by dhirajnitk** [comment]
Full /config page shared on google drive
> https://drive.google.com/file/d/1mHzDdUb5FZXjk6q6Mc_U--8FkRZP9n2W/view?usp=sharing
mongodbmonitor config is shown here
> - job_name: sandbox/mongodbmonitor/0
>   scrape_interval: 30s
>   scrape_timeout: 10s
>   metrics_path: /metrics
>   scheme: http
>   kubernetes_sd_configs:
>   - role: endpoints
>   relabel_configs:
>   - source_labels: [__meta_kubernetes_service_label_name]
>     separator: ;
>     regex: mongodb
>     replacement: $1
>     action: keep
>   - source_labels: [__meta_kubernetes_pod_container_port_number]
>     separator: ;
>     regex: "27017"
>     replacement: $1
>     action: keep
>   - source_labels: [__meta_kubernetes_namespace]
>     separator: ;
>     regex: (.*)
>     target_label: namespace
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_pod_name]
>     separator: ;
>     regex: (.*)
>     target_label: pod
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_service_name]
>     separator: ;
>     regex: (.*)
>     target_label: service
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_service_name]
>     separator: ;
>     regex: (.*)
>     target_label: job
>     replacement: ${1}
>     action: replace
>   - separator: ;
>     regex: (.*)
>     target_label: endpoint
>     replacement: "27017"
>     action: replace
>

**Comment by brancz** [comment]
Could you try:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
       name: mongodb
  endpoints:
  - port: metrics
```

and

```
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: metrics
    port: 27017
    targetPort: <port-name-in-pod>
```

**Comment by dhirajnitk** [comment]
I still cant find the service monitors with service discovery

The config logs for mongodb monitor is here:

> - job_name: sandbox/mongodb/0
>   scrape_interval: 30s
>   scrape_timeout: 10s
>   metrics_path: /metrics
>   scheme: http
>   kubernetes_sd_configs:
>   - role: endpoints
>   relabel_configs:
>   - source_labels: [__meta_kubernetes_service_label_name]
>     separator: ;
>     regex: mongodb
>     replacement: $1
>     action: keep
>   - source_labels: [__meta_kubernetes_endpoint_port_name]
>     separator: ;
>     regex: metrics
>     replacement: $1
>     action: keep
>   - source_labels: [__meta_kubernetes_namespace]
>     separator: ;
>     regex: (.*)
>     target_label: namespace
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_pod_name]
>     separator: ;
>     regex: (.*)
>     target_label: pod
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_service_name]
>     separator: ;
>     regex: (.*)
>     target_label: service
>     replacement: $1
>     action: replace
>   - source_labels: [__meta_kubernetes_service_name]
>     separator: ;
>     regex: (.*)
>     target_label: job
>     replacement: ${1}
>     action: replace
>   - separator: ;
>     regex: (.*)
>     target_label: endpoint
>     replacement: metrics
>     action: replace

**Comment by brancz** [comment]
Can you share the output of the "Service Discovery" page of the Prometheus UI that is respective to this config section?

**Comment by dhirajnitk** [comment]
I dont see any  logs for mongodb  in the my service discovery page.

**Comment by brancz** [comment]
Could you check the Prometheus logs? This sounds like an RBAC issue.

**Comment by dhirajnitk** [comment]
> Prometheus

 Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list pods in the namespace \"sandbox\""
You are right. It's RBAC issue. Do I need to alter example-app-deployment.yaml to make it work?

**Comment by brancz** [comment]
Your Prometheus server needs additional roles to list/watch all Pods. That's because you're asking it to with the any namespace selector.

**Comment by dhirajnitk** [comment]
> Your Prometheus server needs additional roles to list/watch all Pods. That's because you're asking it to with the any namespace selector.

Will I have to create *role.yaml and *roleBinding.yaml as its shown in contrib/kube-prometheus/examples/example-app/prometheus-frontend-role.yaml and corresponding binding.yaml.

**Comment by dhirajnitk** [comment]
Added Role and Rolebindig for new namspace as explained in https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-other-namespaces.md
Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list endpoints at the cluster scope"

**Comment by dhirajnitk** [comment]
Added Role and Rolebindig for new namspace as explained in https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/monitoring-other-namespaces.md
1.Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list endpoints at the cluster scope"
2.Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list endpoints in the namespace \"sandbox\""

**Comment by dhirajnitk** [comment]
@brancz 

1. I added a new Namespace in prometheus(Role and Rolebinding) 
2.  Installing @26.0 version of prometheus  with jb install
3.  jb update and build.sh of example.jsonnet to create new manifests
4.  Running those manifest caused 
>  "system:serviceaccount:monitoring:prometheus-k8s\" cannot list endpoints in the namespace \"monitoring\""

**Comment by dhirajnitk** [comment]
1. I get this error while running those manifests

> error: error validating "manifests/prometheus-namespaces.yaml": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false

The prometheus-namespaces.yaml file has
 

> - default
>  - kube-system
>  - sandbox

3.  The kubelet service is not discovered( 0 /10 active targets)

4.  The /config logs shared here
https://drive.google.com/file/d/1buJ6dncBgWMMUR2ByXKtf880o7in956j/view?usp=sharing

5.  The Prometheus service pods logs are fine.

**Comment by domino7** [comment]
Hello, I have similar problem, cannot discover ServiceMonitors and PrometheusRules from namespaces different than openshift-monitoring, so I decided to add description of my problem here, let me know if I should start separate issue.

**What did you do?**
Installed Cluster Monitoring Operator, installed second instance of Prometheus in the same namespace and tried to configure it to discover ServiceMonitors and PrometheusRules from entire cluster.


**What did you expect to see?**
ServiceMonitors defined in all namespaces available in service discovery and Alerts defined in PrometheuRules in all namespaces available in Prometheus alerts.

**What did you see instead? Under which circumstances?**
Only CRDs defined in namespace openshift-monitoring are discovered in Prometheus.
_Service Discovery_: only ServiceMonitors defined in ```openshift-monitoring``` namespace available
_Rules_:
Prometheus configuration:
```
rule_files:
- /etc/prometheus/rules/prometheus-ngp-rulefiles-0/*.yaml 
``` 
only PrometheusRules defined in  ```openshift-monitoring``` namespace mounted in ``` /etc/prometheus/rules/prometheus-ngp-rulefiles-0/*``` and available in Prometheus

**Environment**
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

* Cluster Monitoring Operator tested versions (same results):
```quay.io/coreos/cluster-monitoring-operator:v0.0.6``` and ```registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.16-3```
* Prometheus Operator tested versions (same results):
```quay.io/coreos/prometheus-operator:v0.23.2``` and ```registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.16-3```


* Prometheus related config:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ngp
  namespace: openshift-monitoring
spec:
  (...)
  serviceMonitorNamespaceSelector:
    any: true
  serviceMonitorSelector:
    any: true
  ruleSelector:
    any: true
  ruleNamespaceSelector:
    any: true
  version: v2.3.2
```

* RBAC configuration
 ```
apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
  name: prometheus-k8s-apps
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - nodes
  - pods
  - prometheusrules
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - tokenreviews
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  attributeRestrictions: null
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  verbs:
  - '*'

clusterrolebinding - binded to:
- system:serviceaccount:openshift-monitoring:prometheus-k8s
- system:serviceaccount:openshift-monitoring:prometheus-ngp
- system:serviceaccount:openshift-monitoring:prometheus-operator

**kind: ClusterRole**
metadata:
  creationTimestamp: 2018-10-08T13:31:25Z
  name: prometheus-operator
  resourceVersion: "5735837"
  selfLink: /oapi/v1/clusterroles/prometheus-operator
  uid: 741e8ebd-cafe-11e8-8ce3-02159dc2c52c
rules:
- apiGroups:
  - apiextensions.k8s.io
  attributeRestrictions: null
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  attributeRestrictions: null
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - apps
  attributeRestrictions: null
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - delete
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - services
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - list
  - watch

clusterrolebinding - binded to:
- system:serviceaccount:openshift-monitoring:prometheus-operator

```

* Prometheus Operator Logs:
(both Prometheus synced, there is some issue with watching resources, not sure if relevant)
```
  | level=info ts=2018-10-26T06:47:06.483377492Z caller=operator.go:893 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
  | level=info ts=2018-10-26T06:47:07.015122256Z caller=operator.go:893 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/ngp
  | level=info ts=2018-10-26T06:47:07.178506954Z caller=operator.go:893 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
  | level=info ts=2018-10-26T06:47:54.709893379Z caller=operator.go:402 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
  | (...)
  | level=info ts=2018-10-26T07:04:27.749493736Z caller=operator.go:402 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
  | W1026 07:05:24.352643       1 reflector.go:341] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:341: watch of *v1.Secret ended with: The resourceVersion for the provided watch is too old.
  | W1026 07:05:49.541097       1 reflector.go:341] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:200: watch of *v1beta2.StatefulSet ended with: The resourceVersion for the provided watch is too old.

```

* Prometheus Logs:
(some problems with scraping etcd related to reusing certificats from default  prometheus-k8s, not sure if relevant)
```
  | level=info ts=2018-10-25T23:58:09.941614592Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2018-10-25T23:58:10.18926207Z caller=main.go:629 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
  | level=error ts=2018-10-25T23:58:14.795752516Z caller=scrape.go:148 component="scrape manager" scrape_pool=openshift-monitoring/etcd/0 msg="Error creating HTTP client" err="unable to use specified client cert (/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.crt) & key (/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.key): tls: failed to find any PEM data in certificate input"
  | level=info ts=2018-10-26T01:00:04.680857788Z caller=compact.go:398 component=tsdb msg="write block" mint=1540504800000 maxt=1540512000000 ulid=01CTPY561Z9A3ZP7CSYRNPTD06
  | level=info ts=2018-10-26T01:00:05.084914907Z caller=head.go:348 component=tsdb msg="head GC completed" duration=108.960634ms
  | level=info ts=2018-10-26T01:00:05.085332503Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=4.453µs
```

**Comment by brancz** [comment]
@domino7 as an OpenShift customer, please open an issue through that system. tl;dr the cluster-monitoring stack is not mean to be used for anything but what it's already configured for. The Prometheus Operator is specifically setup to only watch the `openshift-monitoring` namespace, therefore what you are looking for will never work on 3.11 (which is also the only supported version of the cluster-monitoring stack, you're going to have a lot of trouble with 3.9).

**Comment by dhirajnitk** [comment]
@brancz

Is the cross namespace monitoring  supported in 26.0. if yes then, Could you please attach a working example of cross namespace monitoring with the example's yamls from prometheus-operator/example/user-guides.

I haden't done anything different from what was suggested in the documentation but a working example would help many devops team who don't wish to run multiple Prometheus servers in different namespaces.

Thanks

**Comment by dhirajnitk** [comment]
@brancz 

> - apiVersion: rbac.authorization.k8s.io/v1
>   kind: Role
>   metadata:
>     name: prometheus-k8s
>     namespace: foo
>   rules:
>   - apiGroups:
>     - ""
>     resources:
>     - nodes
>     - services
>     - endpoints
>     - pods
>     verbs:
>     - get
>     - list
>     - watch
> kind: RoleList
> 
> - apiVersion: rbac.authorization.k8s.io/v1
>   kind: RoleBinding
>   metadata:
>     name: prometheus-k8s
>     namespace: foo
>   roleRef:
>     apiGroup: rbac.authorization.k8s.io
>     kind: Role
>     name: prometheus-k8s
>   subjects:
>   - kind: ServiceAccount
>     name: prometheus-k8s
>     namespace: monitoring
> kind: RoleBindingList

Above are the Role and Rolebinding created for Foo namespace. I still  get this error in Promethus@25.0

`"github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:287: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list services in the namespace \"monitoring\""`

**Comment by brancz** [comment]
I'm sorry, but the way your comment is formatted is not comprehensible. Could you can format code with 3 backward ticks

```
`
```

Thank you :slightly_smiling_face:

**Comment by dhirajnitk** [comment]
@brancz

It's working fine. I had to include monitoring namespace along with foo.

>  prometheus+:: {
>       namespaces: ["default", "kube-system","monitoring", "foo"],
>     },

**Comment by subhrajit-senapati** [comment]
@dhirajnitk , can you please provide the RBAC, RBAC rolebinding, clusterrole, clusterrolebinding, other config yaml file as you have got the solution to cross namespace problem.
complete yaml file would be more helpful for "foo" namespace with "default", "kube-system","monitoring", "foo"
