### ISSUE TITLE
Helm chart: warning: cannot overwrite table with non table for value

### ISSUE THREAD

**Issue by maver1ck** [coreos/prometheus-operator#2025]
**What did you do?**
Using some of  the configuration options in helm chart like:
prometheus.rules.value 
gives warning.
The main reason is that in  https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/values.yaml#L199
we should have [] instead of {}

**What did you expect to see?**
No warnings at all.

**What did you see instead? Under which circumstances?**
```
2018/10/17 09:06:28 warning: cannot overwrite table with non table for value (map[])
```

**Environment**
Helm v2.10
K8S v1.10

* Prometheus Operator version:
prometheus-operator-0.0.29

* Kubernetes cluster kind: 

kops

* Manifests:

```
prometheus:
  rules:
    value:
    - name: node
#### more of the manifest 
```

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
