### ISSUE TITLE
Generate OpenAPI Schema

### ISSUE THREAD

**Issue by lswith** [coreos/prometheus-operator#2027]
I'd like to use this CRD in a generated client library. The library requires an openapi spec to be able to generate the custom resources.

Is there any way to publish the open-api schema for this CRD?

**Comment by ant31** [comment]
Hi, 
In the CRDs there's the openAPIv3 Spec: 
https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd 

is it what you are looking for ?

**Comment by mingfang** [comment]
Kubernetes v1.14 now publishes CRDs with openAPI spec https://github.com/kubernetes/kubernetes/pull/71192
But these CRDs https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd needs to change the spec.type = object

**Comment by squat** [comment]
Closing this issue the user hasn't commented back and the openapi schema was already available.
