### ISSUE TITLE
Upgrade prometheus-operator chart to 0.24.0

### ISSUE THREAD

**Issue by aswinkarthik** [coreos/prometheus-operator#2030]
The Prometheus operator helm chart is not updated to the latest Prometheus operator version.

Chart App Version: 0.20.0

Latest prometheus operator version: 0.24.0

**Comment by vsliouniaev** [comment]
Hi @aswinkarthik

The charts have been recently migrated to https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by metalmatze** [comment]
Yes, we're going to gradually move the rest and delete it from this repository.
