### ISSUE TITLE
Helm install does not work

### ISSUE THREAD

**Issue by AkulovNV** [coreos/prometheus-operator#2032]
**What did you do?**
```helm upgrade -i kube-prometheus coreos/kube-prometheus --namespace```

**What did you expect to see?**

> fatal: [k8smaster1]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/helm", "upgrade", "-i", "kube-prometheus", "coreos/kube-prometheus", "--namespace", "monitoring-prometheus"], "delta": "0:00:00.845282", "end": "2018-10-19 11:51:55.211387", "msg": "non-zero return code", "rc": 1, "start": "2018-10-19 11:51:54.366105", "stderr": "Error: validation failed: [unable to recognize \"\": no matches for kind \"Alertmanager\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"Prometheus\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\"]", "stderr_lines": ["Error: validation failed: [unable to recognize \"\": no matches for kind \"Alertmanager\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"Prometheus\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"PrometheusRule\" in version \"monitoring.coreos.com/v1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\", unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1alpha1\"]"], "stdout": "Release \"kube-prometheus\" does not exist. Installing it now.", "stdout_lines": ["Release \"kube-prometheus\" does not exist. Installing it now."]}

**What did you see instead? Under which circumstances?**

**Environment**
helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by AkulovNV** [comment]
@vsliouniaev yes, I deployed prometheus-operator chart before kube-prometheus

**Comment by AkulovNV** [comment]
@vsliouniaev how can I deploy and install prometheus service from helm charts?  Which repository now, why did we break everything ?!

**Comment by AkulovNV** [comment]
Where prometheus-operator and kube-prometheus?

```
helm search stable|grep prometheus
stable/prometheus                    	7.0.2        	2.3.2                       	Prometheus is a monitoring system and time series database. 
stable/prometheus-adapter            	v0.1.0       	v0.2.1                      	A Helm chart for k8s prometheus adapter                     
stable/prometheus-blackbox-exporter  	0.1.1        	0.12.0                      	Prometheus Blackbox Exporter                                
stable/prometheus-cloudwatch-exporter	0.1.4        	0.1.0                       	A Helm chart for prometheus cloudwatch-exporter             
stable/prometheus-mysql-exporter     	0.1.0        	v0.10.0                     	A Helm chart for prometheus mysql exporter with cloudsqlp...
stable/prometheus-node-exporter      	0.3.0        	0.15.2                      	A Helm chart for prometheus node-exporter                   
stable/prometheus-postgres-exporter  	0.4.0        	0.4.6                       	A Helm chart for prometheus postgres-exporter               
stable/prometheus-pushgateway        	0.1.2        	0.4.0                       	A Helm chart for prometheus pushgateway                     
stable/prometheus-rabbitmq-exporter  	0.1.4        	v0.28.0                     	Rabbitmq metrics exporter for prometheus                    
stable/prometheus-redis-exporter     	0.3.0        	0.16.0                      	Prometheus exporter for Redis metrics                       
stable/prometheus-to-sd              	0.1.1        	0.2.2                       	Scrape metrics stored in prometheus format and push them ...
```
```
helm search incubator|grep prometheus
incubator/prometheus   
```                       	0.1.4        	                   	A Helm chart for Kubernetes

**Comment by TheSamSmith** [comment]
+1, have also run into this issue and already have prometheus-operator running

**Comment by miraclefoxx** [comment]
+1, the same. Happened after I deleted minikube cluster.

**Comment by madrover** [comment]
Damn, I didn't see this one coming. Fixing the Byte Order Mark with Sublime, as suggested at https://github.com/helm/helm/issues/4935#issuecomment-440718557 fixed the issue!
So annoying!
