### ISSUE TITLE
How to push servicemonitor to a remote prometheus operator

### ISSUE THREAD

**Issue by yaminisridaran** [coreos/prometheus-operator#2037]
**What did you do?**
I have a remote prometheus operator which I will not have access to configure it. Can I create servicemonitor and push the servicemonitor to the remote prometheus operator.
**What did you expect to see?**
I should be able to configure the remote prometheus operator from my cluster.

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by squat** [comment]
@yaminisridaran do you mean you have two clusters, one with the workload and one with the operator? Or simply a separate namespace?

**Comment by yaminisridaran** [comment]
Yes. one wth workload and one with operator.

**Comment by mxinden** [comment]
You could play around with the [`--apiserver` flag](https://github.com/coreos/prometheus-operator/blob/master/cmd/operator/main.go#L111) specifying a remote API-Server. Keep in mind that this is not a supported use-case of the Prometheus Operator.

**Comment by squat** [comment]
@yaminisridaran yes, as Max mentions, this is not an intended or supported use of the Prometheus Operator. YMMV. Closing as this is not a supported use-case.
