### ISSUE TITLE
How to set the links put in alert manager fields to point to my ingress host name?

### ISSUE THREAD

**Issue by snoby** [coreos/prometheus-operator#204]
**What did you do?**
Triggered an alert that went to pagerduty.

**What did you expect to see?**
The source in the report had an http link to my prometheus graph
**What did you see instead? Under which circumstances?**
I saw the link to my prometheus graph, but it used the in cluster dns name not the ingress name I want the link to use.
**Environment**
kops 
* Kubernetes version information:

	insert output of `kubectl version` here
1.5.1
* Kubernetes cluster kind: 
kops
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:
stock from prometheus-operator contrib directory
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
To be clear I don't think anything is wrong here, just I don't know how to set the source http link correctly.

**Comment by brancz** [comment]
The source link is actually generated by Prometheus when it fires the alert, so you need to set the `externalUrl` field in the `Prometheus` object to be what you expect from your ingress. This is described in the exposing Prometheus [via ingress](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/exposing-prometheus-and-alertmanager.md#ingress) documentation. :slightly_smiling_face:

**Comment by snoby** [comment]
Thank you , I think I got confused because of the operator syntax: `monitoring.coreos.com/v1alpha1
`
Thanks for pointing me in the right direction!

**Comment by brancz** [comment]
Happy I could help :slightly_smiling_face: !
