### ISSUE TITLE
Updating podMetadata.labels is not possible

### ISSUE THREAD

**Issue by wndhydrnt** [coreos/prometheus-operator#2047]
**What did you do?**

Adding additional labels to the pods via [helm](https://github.com/coreos/prometheus-operator/blob/4d9a8af878be4427be34e42cde4fe40bf9d0c522/helm/prometheus/values.yaml#L131):

```
podMetadata:
  labels:
    foo: bar
```
**What did you expect to see?**

Pods with the new label are created.

**What did you see instead? Under which circumstances?**

After an update, Manifests of pods do not change. The labels are not applied.

After looking through the code, my guess is that the operator applies labels to the `Selector` in the manifest of the stateful set (see [here](https://github.com/coreos/prometheus-operator/blob/4e0ae644f6c0ed82e35d0c4bf0f3317bf03662e7/pkg/prometheus/statefulset.go#L776)). The labels in `podMetadata.labels` are merged with the labels for the selector (see [here](https://github.com/coreos/prometheus-operator/blob/4e0ae644f6c0ed82e35d0c4bf0f3317bf03662e7/pkg/prometheus/statefulset.go#L580)). So when updating `podMetadata.labels`, the operator tries to change the selector, which is not permitted.

**Environment**

* Prometheus Operator version:
Docker image: "quay.io/coreos/prometheus-operator:v0.20.0"

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
kops

* Prometheus Operator Logs:

```
Sync "platform/kube-prometheus" failed: updating statefulset failed: StatefulSet.apps "prometheus-kube-prometheus" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Comment by brancz** [comment]
This has been solved starting in `v0.24.0`. https://github.com/coreos/prometheus-operator/releases/tag/v0.24.0

The helm chart for the operator has been merged on the upstream charts repo, so we are not accepting changes to the repo here.

Due to the above two statements, I'm going to close this, but feel free to continue to comment should you disagree :slightly_smiling_face: .
