### ISSUE TITLE
Include grafana config.ini as a ConfigMap

### ISSUE THREAD

**Issue by coryodaniel** [coreos/prometheus-operator#2049]
Currently the config.ini is a part of the docker build. Its easy enough to add a config.ini configmap and override, but I was curious if this would be useful as default functionality to anyone else?

Happy to implement if so, if not, feel free to close!

**Comment by brancz** [comment]
If you are using the jsonnet based stack see here: https://github.com/brancz/kubernetes-grafana/blob/master/README.md#config-customization

**Comment by GramozKrasniqi** [comment]
I see it as a really good enhancement.
One use case would be creating the ini ConfigMap using Terraform.

**Comment by metalmatze** [comment]
As @brancz pointed out this would either be something for [kubernetes-grafana](https://github.com/brancz/kubernetes-grafana/blob/master/README.md#config-customization) or now [kube-prometheus](https://github.com/coreos/kube-prometheus/).
Please use these repositories going forward as this repo doesn't contain anything related to Grafana anymoer.
