### ISSUE TITLE
jsonnet generated manifest refers to secret grafana-config. What should it be?

### ISSUE THREAD

**Issue by VinceMD** [coreos/prometheus-operator#2050]
Doing a fresh install with latest version, looks like grafana is looking for a secret called grafana-config. I've been using prometheus operator before and I don't think it was needed.

What can be the content of this grafana-config secret?

**What did you do?**
```jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus
jsonnet -J vendor -m manifests ${1-main.jsonnet} | xargs -I{} sh -c 'cat $1 | gojsontoyaml > $1.yaml; rm -f $1' -- {}
kubectl -n monitoring apply -f manifests
```

**What did you expect to see?**
I expected all pods to start

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:
v0.24.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kube-aws

* Manifests:

grafana-deployment.yaml:
```
      - name: grafana-config
        secret:
          secretName: grafana-config
```

* Grafana pod describe

```
timeout expired waiting for volumes to attach or mount for pod"monitoring"/"grafana-9d6dc699b-glm56". list of unmounted volumes=[grafana-config]
```

**Comment by brancz** [comment]
That volume mount should not be there when additional config for Grafana is not explicitly configured.

@metalmatze can you have a look at this?

**Comment by metalmatze** [comment]
I can't reproduce this locally. I cannot find `grafana-config` in the current `master` branch of kube-prometheus nor after compiling them with jsonnet. Where does your `main.jsonnet` come from? Something needs to be overwritten there, I think.
This might be related to the recent changes in https://github.com/brancz/kubernetes-grafana/pull/45 if you pull that in via jsonnet-bundler?

**Comment by brancz** [comment]
Yes I was thinking of a connection with https://github.com/brancz/kubernetes-grafana/pull/45 as well. Can you just confirm that when using a version with that PR included that this does not happen? Otherwise we'll need @VinceMD to let us know more how to reproduce this :slightly_smiling_face: .

**Comment by metalmatze** [comment]
I can now confirm that this happens after running `jb update` in `contrib/kube-prometheus`. I'll commute to the office and then look at fixing this problem.

**Comment by brancz** [comment]
Yeah I just did a jb update on my stack and am seeing the same. As far as I can tell it just needs the same if statement for the volume and volume mount as creating the config object as changed in https://github.com/brancz/kubernetes-grafana/pull/45.

**Comment by brancz** [comment]
Go ahead.

**Comment by VinceMD** [comment]
When I run the job, it pulled 0.24 even though 0.25 was realised yesterday . But no big deal, 0.24 should be fine.

That is probably not important anymore but here is my config:

```
local kp = 
(import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'customisation/kube-prometheus-alert-manager-spec.libsonnet') + 
(import 'customisation/kube-prometheus-clusterrole.libsonnet') + 
#(import 'customisation/kube-prometheus-etcd-secret.libsonnet') +
(import 'customisation/kube-prometheus-ports-for-ingresses.libsonnet') + 
(import 'customisation/kube-prometheus-prometheus-spec.libsonnet') + 
(import 'customisation/kube-prometheus-storage.libsonnet') {
  _config+:: {
    namespace: 'monitoring',
  },
  grafanaDashboards+:: {
    'etcd-dashboard.json': (import 'xxx-custom-grafana-dashboards/etcd-dashboard.json'),
    'kubernetes-pods-by-namespace-dashboard.json': (import 'xxx-custom-grafana-dashboards/kubernetes-pods-by-namespace-dashboard.json'),
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by metalmatze** [comment]
@VinceMD, when you run `jb update` and then compile your manifests again this should be resolved now. Let us know if the fix helped (it did for me).

**Comment by brancz** [comment]
updating the generated manifests in https://github.com/coreos/prometheus-operator/pull/2045 as well

**Comment by VinceMD** [comment]
@metalmatze `go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb` is how I install jsonnet.
I got rid of the binary and re-install but the update function does not exist:

```jb -h
usage: jb [<flags>] <command> [<args> ...]

A jsonnet package manager

Flags:
  -h, --help  Show context-sensitive help (also try --help-long and --help-man).
      --jsonnetpkg-home="vendor"
              The directory used to cache packages in.

Commands:
  help [<command>...]
    Show help.

  init
    Initialize a new empty jsonnetfile

  install [<packages>...]
```
How do I get the update command? 
Can that be added in the documentation: install and update jb?

**Comment by VinceMD** [comment]
ok working now. The commands I used as a reference for others:

`go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb`
`jb update`
`jsonnet -J vendor -m manifests ${1-main.jsonnet} | xargs -I{} sh -c 'cat $1 | gojsontoyaml > $1.yaml; rm -f $1' -- {}`
`kubectl apply -f manifests/`

That could be go in How to update section of the doc :)

**Comment by VinceMD** [comment]
@brancz https://github.com/coreos/prometheus-operator/pull/2079 for review
