### ISSUE TITLE
Can prometheus supports horizontal pod autoscalling

### ISSUE THREAD

**Issue by yaminisridaran** [coreos/prometheus-operator#2054]
**What did you do?**
Can prometheus supports horizontal pod autoscalling ?
If yes what is the configuration I need to configure.
**What did you expect to see?**
Need to see multiple instance of prometheus with same configuration.
How prometheus operator is supporting hpa.

**Environment**
k8s cluster

**Comment by brancz** [comment]
You need to install the [Prometheus adapter for Kubernetes](https://github.com/DirectXMan12/k8s-prometheus-adapter). At some point this may be integrated into kube-prometheus, but today this is out of scope, therefore closing this.
