### ISSUE TITLE
Node exporter error strconv.ParseUint: parsing \"N/A (no PMA)\": invalid syntax

### ISSUE THREAD

**Issue by andig** [coreos/prometheus-operator#2056]
Running the stable helm chart I'm seeing a lot of these errors (every second) in the logfile:

	❯ k logs prometheus-prometheus-node-exporter-9bqsk
	time="2018-10-26T14:08:09Z" level=error msg="ERROR: infiniband collector failed after 0.001891s: strconv.ParseUint: parsing \"N/A (no PMA)\": invalid syntax" source="collector.go:132"

This is happening on Azure.

I hope this is the right place to ask about the downstream chart, too?

**Comment by brancz** [comment]
please report this on the node-exporter project itself, this repository merely defined how it is deployed

**Comment by sjdweb** [comment]
The suggestion [here](https://github.com/prometheus/node_exporter/issues/966) is to use `0.17.0-rc.0` release, how can that work with the chart? I have the latest helm chart which is using node_exporter image:

```
 Image:         quay.io/prometheus/node-exporter:v0.15.2
```
