### ISSUE TITLE
no matches for monitoring.coreos.com/, Kind=Prometheus

### ISSUE THREAD

**Issue by yaminisridaran** [coreos/prometheus-operator#2061]
**What did you do?**
Deployed the prometheus operator but I am getting this error in first time.
Second time it works fine
**What did you expect to see?**
It should not show this error in the first time deployment
**What did you see instead? Under which circumstances?**

**Environment**
kubernetes
* Prometheus Operator version:
0.23.2

**Comment by metalmatze** [comment]
Once the Prometheus Operator deployment is up and running it takes a few seconds to register the new CRDs within the cluster. Within that period of time you will see this message.
After successfully registering these CRDs you can start using them normally.

It is expected to repeat the deployment a few times with a fresh install.

**Comment by yaminisridaran** [comment]
But why? Facing lot of issues because of this behaviour.

**Comment by metalmatze** [comment]
We're extending the Kubernetes API and that just takes some seconds for it to load and set up everything. There's nothing we can do on the prometheus operator side.
You could simply apply the deployment on its own, wait a few seconds (10 seconds for example) and then apply everything else. Now you can be pretty sure that the Prometheus object (and others) are known to the Kubernetes API.

**Comment by squat** [comment]
If you are scripting this, a common pattern is to do something like:
```sh
kubectl apply -f operator.yaml
until kubectl apply -f prometheus.yaml; do
    echo "trying again in 5 seconds..."
    sleep 5
done
```
