### ISSUE TITLE
CPUThrottlingHigh on basically every pod in the system

### ISSUE THREAD

**Issue by rocketraman** [coreos/prometheus-operator#2063]
**What did you do?**

I have the Prometheus Operator, version 0.25 installed on Kubernetes 1.12.1. The alert CPUThrottlingHigh is triggering for almost every pod in my system. The cluster is basically idle.

The expression that is triggering is:

```
100
  * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total[5m]))
  / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total[5m]))
  > 25
```

and indeed the expression seems to be "correctly" triggering based on the metrics above:

![image](https://user-images.githubusercontent.com/53049/47624173-e6dbbf00-daef-11e8-8dfe-1c24887f974f.png)

![image](https://user-images.githubusercontent.com/53049/47624238-b34d6480-daf0-11e8-9a07-86d7e2fd9f92.png)

Could the underlying metrics be wrong somehow? One thing which may be relevant: this cluster has a mix of nodes with varying CPU counts and speeds. Might some value need to be normalized for these numbers to be correct?

**What did you expect to see?**

No false positive alert.

**What did you see instead? Under which circumstances?**

False positive alert. All circumstances.

**Environment**

Prometheus Operator, version 0.25 installed on Kubernetes 1.12.1

* Prometheus Operator version:

    quay.io/coreos/prometheus-operator:v0.24.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Azure ACS-Engine v0.24.2

* Manifests:

I used the manifests in kube-prometheus.

**Comment by metalmatze** [comment]
We are already discussing this alert in the repository is it created in.
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108
Feel free to join our discussion there.

kube-prometheus simply uses this alert and others.
