### ISSUE TITLE
Prometheus data storage and retention

### ISSUE THREAD

**Issue by junaidrazzaq323** [coreos/prometheus-operator#2066]
I have been reading about prometheus from various resources but getting confused about few things.

Here is my scenerio
I have a single node kubernetes setup on a centOS machine. I have a namespace "testing" that has few deployments running.

This is the promethues release that I have launched.

https://github.com/coreos/prometheus-operator
git checkout release-0.16

Questions that we have

If everything is running fine for how longs can I see the testing namespace data in grafana? Can we change it?

Lets say one of the POD in testing namespace gets evicted and recreated. Will I be able to see the data before POD eviction? If no, can we do something about it.

What will happen to the testing namespace data if promethues pods get restarted?

What will happen to the testing namespace data if entire kubernetes node get restarted?

Some of my PODs are getting evicted due to diskpressure. I need to know the disk I/O of pods. Is there a way to monitor this in grafana?

Any help will be appreciated.

Thanks

**Comment by metalmatze** [comment]
As these questions are more questions about Prometheus in general, please ask on the prometheus-users mailing list.
https://groups.google.com/forum/#!forum/prometheus-users

Feel free to open prometheus-operator or kube-prometheus related issues in the future. :blush:
