### ISSUE TITLE
Add persistent disks to default Grafana graphs

### ISSUE THREAD

**Issue by rocketraman** [coreos/prometheus-operator#2068]
This is a followup to https://github.com/coreos/prometheus-operator/issues/485.

Persistent volumes can now be monitored with the new metrics [mentioned](https://github.com/coreos/prometheus-operator/issues/485#issuecomment-376928905) by @gabreal, a dashboard with these persistent volumes would be great as one of the default out of the box dashboards.

This dashboard does pretty much the right thing, and is a good stop-gap measure: https://grafana.com/dashboards/6739.

**Comment by brancz** [comment]
I think that's a nice idea, the dashboards used in this repo are defined in the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin). Would you mind closing this here and opening this issue there? :slightly_smiling_face:

**Comment by rocketraman** [comment]
Done! https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/111
