### ISSUE TITLE
How to edit configmap-reload resource limit in statefulset?

### ISSUE THREAD

**Issue by boxuan666** [coreos/prometheus-operator#2070]
**What did you do?**

In my cluster, prometheus always triggered alert: CPUThrottlingHigh.
because some pod CPU & MEM resource limit is too low. so i edit those pod(or deploy), but i can't edit the statefulset like alertmanager & prometheus It seems that they can only be modified by CRD.

**What did you expect to see?**

I want to increase the resource limit on configmap-reload

**Environment**

* Prometheus Operator version:

```
        alertmanager: "v0.15.2",
        nodeExporter: "v0.16.0",
        kubeStateMetrics: "v1.3.1",
        kubeRbacProxy: "v0.3.1",
        addonResizer: "1.0",
        prometheusOperator: "v0.24.0",
        prometheus: "v2.4.3",
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

install by kubeadm

-------------------------------------------------------
`kubectl edit sts -n monitoring alertmanager-main`

When I finished the modification of sts, the parameters of sts still have not changed.

**Comment by boxuan666** [comment]
@squat  Yeah I got u point, However, by modifying CRD,  only can change the resource limit of Prometheus container, this cannot change the resource limit of configmap-reloader container. 
can u give me a example file? (by modifying CRD to change resource limit of configmap-reloader)

**Comment by squat** [comment]
@boxuan666 sorry I misunderstood your goal. That field only allows modifying the resources on the Prometheus pods. The resource limits on the ConfigMap reloader container are hard-coded to values that we determined empirically. Are you sure this container is causing issues because it does not have enough memory or CPU?

**Comment by squat** [comment]
@boxuan666, I think this is actually related to https://github.com/coreos/prometheus-operator/issues/2063. The resource limits on the configmap reloader container should be sufficient. Instead, the alert is being incorrectly triggered.
