### ISSUE TITLE
Can't pull metrics from aws cloudwatchexporter

### ISSUE THREAD

**Issue by AndreaFerraresi** [coreos/prometheus-operator#2073]
**What did you do?**
Installed AWS cloudwatch exporter as described here 
https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter
**What did you expect to see?**
cloudwatch exporter metrics in 

**What did you see instead? Under which circumstances?**
No metrics on prometheus but i can see the metrics coming in if I expose the cloudwatch exporter port

**Environment**
Amazon EKS

* Prometheus Operator version:

latest

* Kubernetes version information:

1.12

* Kubernetes cluster kind: 

Amazon EKS

**Comment by metalmatze** [comment]
Quickly looking at the chart I can't find a ServiceMonitor that is needed by the Prometheus Operator to start scraping the exporter.
It seems like @gianrubio wrote a lot of that exporter, so he should know best.

**Comment by gianrubio** [comment]
@AndreaFerraresi please share your ServiceMonitor and the pod labels

**Comment by AndreaFerraresi** [comment]
This was due to a very stupid mistake on my side sorry guys, going to close that one

**Comment by AmetPreply** [comment]
Hi, @gianrubio could you share please servicemonitor for cloudwatch-exporter?
I installed it via helm https://github.com/helm/charts/tree/master/stable/prometheus-cloudwatch-exporter but don't understand how to pull metrics to prometheus.
