### ISSUE TITLE
Use kube-prometheus with external prometheus server

### ISSUE THREAD

**Issue by morenweld** [coreos/prometheus-operator#2076]
Hi, everybody. Thanks you for yours work. I use kube-prometheus and all works fine.
Could you tell me can i use external prometheus database and grafana which not included in cluster and located on different server?

**Comment by brancz** [comment]
If you don't want to run Prometheus in cluster, then kube-prometheus is not the project you want to look at :slightly_smiling_face: . I'd recommend you ask how people are doing this on the [prometheus users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
