### ISSUE TITLE
how to access to the dashboard 

### ISSUE THREAD

**Issue by zyriuse75** [coreos/prometheus-operator#2080]
**What did you do?**
 i follow your procedure to setup prometheus and grafana

at the second step 

```
2. The Grafana server can be accessed via port 80 on the following DNS name from within your cluster:

   cloying-greyhound-grafana.monitoring.svc.cluster.local

   Get the Grafana URL to visit by running these commands in the same shell:

     export POD_NAME=$(kubectl get pods --namespace monitoring -l "app=cloying-greyhound-grafana" -o jsonpath="{.items[0].metadata.name}")
     kubectl --namespace monitoring port-forward $POD_NAME 3000

3. Login with the password from step 1 and the username: admin
#################################################################################
######   WARNING: Persistence is disabled!!! You will lose your data when   #####
######            the Grafana pod is terminated.                            #####
#################################################################################
```

when i try to execute  `wget cloying-greyhound-grafana.monitoring.svc.cluster.local` form the server i get 
`ERROR 503` :( 

Do you know where i change the parameter to give a more beautiful url ? 
and why i dont have access ? 
that's weird no ?

**Comment by gianrubio** [comment]
@zyriuse75 please post the logs from your grafana pod

**Comment by zyriuse75** [comment]
you will find below the log of the grafana pod 
https://gist.github.com/zyriuse75/ed6b1abd3fe09d4803a3561bb9abd1e0

**Comment by gianrubio** [comment]
What's the output if you connect to grafana using a port-forward?

**Comment by brancz** [comment]
We neither use nor maintain the helm charts in this repo. Please open an issue on the upstream helm charts repo should the issue persist.
