### ISSUE TITLE
Updating prometheus image to a new version getting revert back to original version

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#2081]
**What did you do?**
How to update the prometheus image from v2.0 to v2.2 without deleting the statefulset? I tried changing the image from statefulset but operator will immediately revert that to original version.

**What did you expect to see?**
Prometheus v2.2 gets updated

**What did you see instead? Under which circumstances?**
Revert back to original prometheus v2.0

**Environment**

* Prometheus Operator version:
0.14

* Kubernetes version information:
v1.9.5

* Kubernetes cluster kind: 
kops

* Manifests:
alertmanager, kube-state-metrics, node-exporter, prometheus-operator, prometheus

* Prometheus Operator Logs:
N/A

How to update the prometheus image? I tried changing the image from statefulset but operator will immediately revert that to original version.

**Comment by brancz** [comment]
You need to change the image and or version in the `Prometheus` object.

**Comment by bamb00** [comment]
Thanks @brancz.
