### ISSUE TITLE
How install it?

### ISSUE THREAD

**Issue by itkroplis** [coreos/prometheus-operator#2084]
Hi!

I try it install to my test Kubernetes cluster. 
I see to do
kubectl apply -f bundle.yaml

Ok I push it. I see prometheus-operator = Deployments and Pods and ReplicaSets in default Namespace.
packet@KUBERNETES1:/opt/prometheus-operator$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
prometheus-operator-c4b75f7cd-khwg5   1/1     Running   0          19m

Where is Readme about how install Prometheus and Grafana and Alert ?
I found the following examples:
kubectl create ns monitoring
git clone https://github.com/coreos/prometheus-operator.git
cd prometheus-operator
helm install --name prometheus-operator \ 
  --set rbacEnable=true --namespace=monitoring helm/prometheus-operator
helm install --name prometheus --set serviceMonitorsSelector.app=prometheus \ 
  --set ruleSelector.app=prometheus --namespace=monitoring helm/prometheus
helm install --name alertmanager --namespace=monitoring helm/alertmanager
helm install --name grafana --namespace=monitoring helm/grafana
helm install --name kube-prometheus --namespace=monitoring helm/kube-prometheus
for it output is errors:
Error: found in requirements.yaml, but missing in charts/ directory: alertmanager, prometheus, exporter-coredns, exporter-kube-controller-manager, exporter-kube-dns, exporter-kube-etcd, exporter-kube-scheduler, exporter-kube-state, exporter-kubelets, exporter-kubernetes, exporter-node, grafana

But this installs work only without kubectl apply -f bundle.yaml   (need clear cluster without prometheus-operator)

I can't see this install readme! Where can I see it?

**Comment by brancz** [comment]
Sorry, yes the `bundle.yaml` is only meant for a quickstart, the helm or jsonnet based installation includes what is in the `bundle.yaml` as well, so you want to delete the `bundle.yaml` if you want the full stack. I opened #2087 to clarify this in the readme.

**Comment by lilic** [comment]
Since there  has not had any activity for some time, closing this issue, feel free to open a new one if you are still facing this problem.
