### ISSUE TITLE
Alertmanager retention description incorrect

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#2085]
**What did you do?**
Set the alertmanager spec retention to 7d

**What did you expect to see?**
The alertmanager pod to start up with a 7 day retention parameter. According to the spec this should be allowed: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec

**What did you see instead? Under which circumstances?**
The pod crashlooping with 
```
alertmanager: error: time: unknown unit d in duration 170d, try --help
```
The accepted units are limited to `(ms|s|m|h|)`

**Prometheus Operator version:**
 v0.25.0

Opened an issue https://github.com/prometheus/alertmanager/issues/1605 since this seems like an omission in alertmanager

**Comment by brancz** [comment]
Yes you are [totally right](https://github.com/golang/go/blob/41e62b8c49d21659b48a95216e3062032285250f/src/time/format.go#L1277). Would you like to adapt our documentation?
