### ISSUE TITLE
Incorrect message in alerts KubeJobFailed and KubeJobCompletion

### ISSUE THREAD

**Issue by yuripastushenko** [coreos/prometheus-operator#2094]
**What did you do?**
run a kubernetes job with name "my-job" in "default" namespace that is taking more than 30 minutes.

**What did you expect to see?**
Alert:
Job default/my-job is taking more than 30 minutes to complete.

**What did you see instead? Under which circumstances?**
Job /kube-state-metrics is taking more than 30 minutes to complete.

* Prometheus Operator version:
	0.24.0 

I find out that it is mistake in alert in 
contrib/kube-prometheus/manifests/prometheus-rules.yaml

**Comment by squat** [comment]
should be fixed by https://github.com/coreos/prometheus-operator/pull/2096
