### ISSUE TITLE
Can not access grafana after upgrading from 0.18.1 to 0.25.0

### ISSUE THREAD

**Issue by Cherishty** [coreos/prometheus-operator#2098]
**What did you do?**
I was using kube-prometheus **0.18.1** and everything works well.
While recently I upgrade it to **0.25.0** following the Quickstart, I found that I can access grafana via **<master_ip>:30902**.
Checking the manifest I find _grafana-service.yaml_ (as well as kube-operator-service)  has been changes from 0.18.1, and now it **only** exposes 3000 port internally.

So I write a grafana service based on NodePort by myself, like below:

> apiVersion: v1
> kind: Service
> metadata:
>   name: grafana-svc
>   namespace: monitoring
>   labels:
>     app: grafana-svc
> spec:
>   type: NodePort
>   ports:
>   - port: 3000
>     protocol: TCP
>     nodePort: 30902
>     targetPort: web
>   selector:
>     app: grafana

but still can not access to curl or visit granafa via 30902
`port-forward` does not work for my scenarios since it is not full-support on k8s 1.9.5

**What did you expect to see?**
Enable to access grafana from 30902 or anyway externally.

**What did you see instead? Under which circumstances?**

**Environment**
      
* Prometheus Operator version:

	release 0.25.0 / 2018-10-24

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by metalmatze** [comment]
What happens if you do a describe on the Service? Does the Service have any Endpoints?
`kubectl describe -n monitoring svc grafana-svc`

**Comment by Cherishty** [comment]
You are right @metalmatze . I describe and compare grafana-svc(create via my yaml) against grafana(create via default manifest) as below:

> # kubectl describe -n monitoring svc grafana-svc
> Name:                     grafana-svc
> Namespace:                monitoring
> Labels:                   app=grafana-svc
> Annotations:              <none>
> Selector:                 app=grafana
> Type:                     NodePort
> IP:                       10.103.164.215
> Port:                     <unset>  3000/TCP
> TargetPort:               web/TCP
> NodePort:                 <unset>  30902/TCP
> Endpoints:                <none>
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:                   <none>
> 
> # kubectl describe -n monitoring svc grafana
> Name:              grafana
> Namespace:         monitoring
> Labels:            <none>
> Annotations:       <none>
> Selector:          app=grafana
> Type:              ClusterIP
> IP:                10.99.193.117
> Port:              http  3000/TCP
> TargetPort:        http/TCP
> Endpoints:         10.244.192.2:3000
> Session Affinity:  None
> Events:            <none> 

how could I update it ? Thanks a lot!

**Comment by Cherishty** [comment]
Meanwhile, I found the deployment guide [kube-prometheus-on-kubeadm.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md) is mismatched with 0.25.0, seems it matches with 0.18.1

**Comment by metalmatze** [comment]
I think your targetPort is not correct:

```diff
Name: grafana-svc
Namespace: monitoring
Labels: app=grafana-svc
Annotations: 
Selector: app=grafana
Type: NodePort
IP: 10.103.164.215
Port: 3000/TCP
-TargetPort: web/TCP
+TargetPort: http/TCP
NodePort: 30902/TCP
Endpoints: 
Session Affinity: None
External Traffic Policy: Cluster
Events:
```
Afterwards your svc should know where to route to.

**Comment by Cherishty** [comment]
Make sense! Thanks a lot for your guidance!
This issue can be close, but I just wonder why the default grafana/prometheus/alertmanager services are NOT exposed by Node Port ?

**Comment by brancz** [comment]
We don't want to do this by default as people are likely to expose prometheus/alertmanager/grafana to the world, in fact we used to do this and people's instances started being indexed on google and random people on the internet started accessing their monitoring infrastructure, better safe than sorry :slightly_smiling_face: .

**Comment by Cherishty** [comment]
@brancz  Thanks for your kindly clarification!
I also find in 0.25.0 grafana always need to be authorized with  admin/admin when log-in, while in 0.18.1 it does NOT need to do so.
How can I **disable** log-in  in grafana via its configuration?

I know I should open another issue to ask, but it may much good if you may give a quick solution.

Best Regards!

**Comment by metalmatze** [comment]
You need to adjust Grafana's configuration.
Take a look at the project that kube-prometheus uses as dependency. There's an example on how to achieve this with jsonnet: 

https://github.com/brancz/kubernetes-grafana/blob/455e08134e1a135f41e1032576487921a759cf51/examples/custom-ini.jsonnet#L10

**Comment by metalmatze** [comment]
Here's an example from my personal cluster:
```
...
    _config+:: {
      namespace: 'monitoring',
      grafana+:: {
        dashboards: $.grafanaDashboards,
        config: {
          sections: {
            security: {
              admin_user: 'metalmatze',
              admin_password: 'XXX',
            },
          },
        },
      },
    },
...
```

**Comment by Cherishty** [comment]
Thanks you  @metalmatze for your help . I did find this workaround in other threads, but what I want is disable authorization (which means user do NOT need to login grafana dashboard ).

Since this is a default behavior in 0.18.1, can we make this by just modifying files in manifest?

**Comment by metalmatze** [comment]
You are looking for anonymous authentication then:
http://docs.grafana.org/auth/overview/#anonymous-authentication

The config I posted above needs to be slightly changed.

**Comment by Cherishty** [comment]
Yes it does!  
Seems it is the default setting in [config](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/grafana-image/config.ini) 
 
And how can I apply this in manifest yaml  file?

**Comment by metalmatze** [comment]
Take a look at https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#customizing-kube-prometheus
This should get you started with customizing kube-prometheus.

**Comment by Cherishty** [comment]
Thanks for your reminder and rapid reply.
I will have a try for customizing it .
