### ISSUE TITLE
Track PetSet rename to StateFul set

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#21]
x-ref: https://github.com/kubernetes/kubernetes/issues/35534

Pet Sets will be renamed to Stateful Sets.
We'll have to figure out whether we breakingly move forward or adapt the operators behavior based on the used cluster version. If it's merely a rename we should be able to handle it gracefully.

**Comment by fabxc** [comment]
In 1.5 apps/v1alpha/PetSet will be deleted. Upgrade documentation exists but will require user interaction. 

Best course of action seems to be having one operator release for pre-1.5 and one for 1.5 onwards.

**Comment by kennethredler** [comment]
Is anyone working this issue now that Prometheus 1.5(.1 even) is out?

**Comment by brancz** [comment]
@kennethredler The migration to StatefulSets in terms of the operator code will be very easy, it's really just replacing the object `kind` and `apiVersion`. The operational part is a bit more complicated though, as if you had the `PetSet`s before then you need to shutdown the operator, [upgrade](http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/) the `PetSet`s to `StatefulSet`s and then start the operator version that uses `StatefulSet`s instead. The question is should we keep maintaining a version utilizing `PetSet`s to allow `1.4.x` users to get started as well. Personally that seems like a rabbit hole and if you have a self hosted cluster it should be easy enough to upgrade. Additionally if your deployment does not have high SLA requirements it might even be ok to just delete all your Prometheus/Alertmanager deployments and recreate them with the new version of the operator.

**Comment by brancz** [comment]
@kennethredler to answer your original question, I have not started working on it yet, but will very soon

**Comment by janwillies** [comment]
with latest minikube-0.14.0 (defaults to kube-1.5) the prometheus-operator fails to create pods: 

```
$ kubectl create -f https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml
$ kubectl logs prometheus-operator-478913231-hd9bw
E1218 09:51:04.412423       1 reflector.go:214] github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1alpha1.PetSet: the server could not find the requested resource
```

**Comment by haf** [comment]
Stateful is a single word so the title of this issue is wrong?

**Comment by kennethredler** [comment]
If I read [CHANGELOG.md](https://github.com/coreos/prometheus-operator/blob/master/CHANGELOG.md) correctly, this can be closed as fixed in `0.2.0`, right?

**Comment by fabxc** [comment]
Correct, thanks.

**Comment by kennethredler** [comment]
Thank you!!!
