### ISSUE TITLE
Instance creation fails with security context issues

### ISSUE THREAD

**Issue by ctron** [coreos/prometheus-operator#2102]
**What did you do?**

* Install OKD 3.11
* Deploy OLM
* Create a subscription to the Prometheus Operator
* Run through the "getting started" section

**What did you expect to see?**

* A working deployment

**What did you see instead? Under which circumstances?**

* The operator successfully deploys
* The prometheus stateful set fails with the following error:

~~~
create Pod prometheus-prometheus-0 in StatefulSet prometheus-prometheus failed error: pods "prometheus-prometheus-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000340000, 1000349999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000340000, 1000349999] spec.containers[2].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000340000, 1000349999]]
~~~

**Environment**

* Prometheus Operator version:

	0.22.2

* Kubernetes version information:

~~~
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://foobar:8443
openshift v3.11.0+aeff40b-47
kubernetes v1.11.0+d4cacc0
~~~

* Kubernetes cluster kind: 

	OKD 3.11

* Prometheus Operator Logs:

```
level=info ts=2018-11-07T15:43:06.141416547Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=hono/prometheus
W1107 15:43:06.141507       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W1107 15:43:06.141556       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
W1107 15:43:06.151212 1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
```

**Comment by brancz** [comment]
You can explicitly set “securityContext: {}” to have the openshift security context constraint or pod security policy set the appropriate security context.

**Comment by brancz** [comment]
Agreed. This was a short-sighted decision, that I think we should revert. I've actually said this a few times so let me go ahead and just make that change right now :slightly_smiling_face: .

**Comment by brancz** [comment]
I opened #2109 to fix the issues.

**Comment by austincunningham** [comment]
Seeing a similar issue on 
Prometheus Operator version: 0.30.0
```
Error creating: pods "prometheus-operator-5b8bfd696-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 65534: must be in the ranges: [1000070000, 1000079999]]
```

**Comment by devtech0101** [comment]
updated with user/gid 1000070000 but now this error.

WARNING: Running in user-mode.                     
WARNING: The user-mode requires you to manually start builds processing: 
WARNING: $ gitlab-runner run                       
WARNING: Use sudo for system-mode:                 
WARNING: $ sudo gitlab-runner...                   
                                                   
Registering runner... succeeded                     runner=FiCiWxae
PANIC: mkdir /.gitlab-runner: permission denied

**Comment by MarsianMan** [comment]
> updated with user/gid 1000070000 but now this error.
> 
> WARNING: Running in user-mode. WARNING: The user-mode requires you to manually start builds processing: WARNING: $ gitlab-runner run WARNING: Use sudo for system-mode: WARNING: $ sudo gitlab-runner...
> 
> Registering runner... succeeded runner=FiCiWxae PANIC: mkdir /.gitlab-runner: permission denied

@devtech0101  What was the fix for the gitlab runner?
