### ISSUE TITLE
etcd jsonnet alerts import

### ISSUE THREAD

**Issue by paskal** [coreos/prometheus-operator#2112]
etcd have [libsonnet](https://github.com/etcd-io/etcd/blob/master/Documentation/etcd-mixin/mixin.libsonnet) file in their repo, but here it's included only in [helm part](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/prometheusrule.yaml), not in regular one. Don't this repo want to build yaml from it as well as it does from kubernetes-mixin sources?
/cc @brancz

**Comment by brancz** [comment]
There is already an example on how to use the etcd mixin, no need for it to be in this repo :slightly_smiling_face: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#static-etcd-configuration
