### ISSUE TITLE
Add support for image digest instead of version

### ISSUE THREAD

**Issue by champtar** [coreos/prometheus-operator#2115]
**What did you do?**

Tried to use `sha256:...` instead `vx.y.z` for better reproducibility, ie
```
versions+:: {
    prometheusOperator: "sha256:f7f7ad31a2c8abfe4d05423280e85b4af045e94bb81277b0032d99eb2d3bd9ae",
}
```

**What did you expect to see?**

it works

**What did you see instead? Under which circumstances?**

It's not supported yet

**Environment**

* Prometheus Operator version:
v0.25.0

**Additional information**

I'm totally new to jsonnet, the best thing that I can come up with is:
```
-        container.new('prometheus-operator', $._config.imageRepos.prometheusOperator + ':' + $._config.versions.prometheusOperator) +
+        container.new('prometheus-operator', $._config.imageRepos.prometheusOperator + (if std.startsWith($._config.versions.prometheusOperator, 'sha256:') then '' else  ':') + $._config.versions.prometheusOperator) +
```

**Comment by brancz** [comment]
I agree we should support this, and the Prometheus and alertmanager objects do support this, so we should make it work.

**Comment by nrvnrvn** [comment]
Seems like it is absolutely legit to use digest together with tag. See https://github.com/docker/distribution/blob/master/reference/reference.go#L6

Thus I would try 
```
versions+:: {
    prometheusOperator: "v0.26.0@sha256:f7f7ad31a2c8abfe4d05423280e85b4af045e94bb81277b0032d99eb2d3bd9ae",
}
```

I'm still [gathering feedback](https://stackoverflow.com/questions/53848875/using-container-image-tags-together-with-digests) since all examples seem to suggest either tags or digests.

**Comment by champtar** [comment]
Thanks @nrvnrvn, I didn't knew that, this is interesting, but dangerous, as you can trick people
Also this is not supported by podman
```
$ podman pull k8s.gcr.io/pause-amd64:some-made-up-tag@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610
error pulling image "k8s.gcr.io/pause-amd64:some-made-up-tag@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610": unable to pull k8s.gcr.io/pause-amd64:some-made-up-tag@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610: error getting default registries to try: unable to parse 'k8s.gcr.io/pause-amd64:some-made-up-tag@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610': Docker references with both a tag and digest are currently not supported
```

**Comment by nrvnrvn** [comment]
I think you should raise it with podman for sure.
It is supported by kubernetes and docker itself. It is dangerous only in the way that the tag is ignored in this case and can be anything.
The reason behind using both is to keep image references human-readable along with making them reproducible and predictable. Omitting the tag and using only digest can be more dangerous.

**Comment by champtar** [comment]
> The reason behind using both is to keep image references human-readable along with making them reproducible and predictable. Omitting the tag and using only digest can be more dangerous.

I would argue that people will tend to compare the tag when both are present, when using only digest you will either not compare at all or copy/paste to compare
I would really like for docker/podman to verify that tag exist and match digest (ie use both)

**Comment by brancz** [comment]
All combinations are now supported. `version`, `tag`, `sha` and plain `image`.
