### ISSUE TITLE
kube-prometheus README broken link refers to removed spec file

### ISSUE THREAD

**Issue by nirdothan** [coreos/prometheus-operator#212]
[Prometheus specifications md file](https://github.com/coreos/prometheus-operator/blob/v0.6.0/Documentation/prometheus.md) is missing from master causing a broken link in [kube-prometheus README.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md ) row 23

**Comment by mxinden** [comment]
@nirdothan Thanks for the feedback, will be fixed by PR #213.
