### ISSUE TITLE
[thanos] Support for Azure Storage

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#2133]
The current documentation indicates that it's possible to use S3 and GCS but Azure is not available. Azure support was implemented relatively recently and it would be great to get this functionality into prometheus-operator

**Comment by brancz** [comment]
Is there a release of thanos with azure support? If so I'm not aware of it. Beyond that Thanos is abstracting away the provider configurations, so we will probably have breaking changes following theirs. I'm not sure we should introduce anything new that we already know is currently being broken. In general though of course we should have the possibility to use azure object storage.
