### ISSUE TITLE
Pass a grafana configuration file using other type of volumes

### ISSUE THREAD

**Issue by sishihara** [coreos/prometheus-operator#2136]
Hello,

I'm trying to deploy Prometheus and Grafana with Helm. I have to configure Grafana and I think it can be achieved by turn on ```grafana.mountGrafanaConfig``` option in the chart kube-prometheus. It looks like making Grafana to read the config file on Kubernetes worker nodes locally. So I should place config file in all workers have possibility to be scheduled Grafana Pod, right?

In large cluster I think this approach may cause some troubles. How about using other type of Volumes like NFS to centralize configuration management?

**Comment by redbaron** [comment]
you can use kube-prometheus jsonnet to have full freedom of customization without need of fork
