### ISSUE TITLE
defining Additional Scrape Configs as secrets

### ISSUE THREAD

**Issue by nickytd** [coreos/prometheus-operator#2139]
Hi 
at the moment in Prometheus CDR we can specify additional scrape configs as secrets. But in kube-prometheus helm  additionalScrapeConfigs expects a static configuration and not a reference to a secret. Shall we align the behaviour between CDR and the kube-prometheus helm chart?
Regards

**Comment by brancz** [comment]
We neither use nor maintain the helm chart. I recommend opening an issue on the upstream charts repo regarding this.
