### ISSUE TITLE
AlertmanagerMembersInconsistent rule failing

### ISSUE THREAD

**Issue by BcTpe4HbIu** [coreos/prometheus-operator#2142]
**What did you do?**
Deployed kube-prometheus via jsonnet, made alertmanager fail to discover all nodes

**What did you expect to see?**
Alert firing in alert manager

**What did you see instead? Under which circumstances?**
Error on alert rule AlertmanagerMembersInconsistent:
`multiple matches for labels: many-to-one matching must be explicit (group_left/group_right)`

**Environment**

* Prometheus Operator version:

f9091bcd99df93631d7a25de7344e0b5a6b8d3f2

* Kubernetes version information:
```
kubectl version                                                                         
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: kubespray

**Comment by brancz** [comment]
With #2143 merged, this is fixed, thanks @BcTpe4HbIu!
