### ISSUE TITLE
Whitelist the local network to avoid exposing prometheus to internet

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#215]
I'm not sure If i'm in the right repo to report this, but as I'm familiar with prometheus-operator I'll post here to discuss.

Few days ago, when I start playing with prometheus-operator I setup all my stuff and expose the prometheus over my ingress. Because I'm using let's encrypt to generate ssl certificates, my domain was exposed to the internet. Every signed certificate by lets encrypt is public accessible, including the domain, so google started indexing my prometheus-operator.  👎 

I always take care to avoid this type of issue when I'm launching a service, but believe me it' happens with everyone. I know it's partially my fault on this 😢 

Just [googled for prometheus](https://www.google.nl/search?client=safari&rls=en&q=Working+Directory+/prometheus&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=oWDJWKSxIcmGgAbCvKzwBg#q=prometheus+status++Runtime+Information+build+information&start=0&*) and I saw a lot of sites running prometheus directly exposed to the internet, this expose sensitive information to everyone. 🔥 

I have 2 suggestions for this:

1 - By default prometheus implement a simple authentication with a  random password.
2- prometheus-operator help the user to expose ingress, forcing the [whitelist ip address](  https://github.com/kubernetes/ingress/blob/dd7f8b4a972d9c7346da2b37419ff3529d3b38d0/controllers/nginx/configuration.md#whitelist-source-range)

**Comment by brancz** [comment]
Authentication has been extensively discussed on the upstream project and it will not happen that authentication will be implemented directly in Prometheus itself. However, a solution that many people use is that they expose Prometheus and Alertmanager via the [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy). That way there is at least some authentication before it. Nontheless it is probably a good idea to also limit that to a subnet which could be a VPN.

Regarding the ingress, I don't think that the Prometheus Operator should be involved in that, however it could be something the helm chart could address. (/cc @mgoodness) Other than that it is probably a good idea to write in the exposing Prometheus and Alertmanager documentation that this can happen and that whitelisting and authentication is a good idea.

I have documentation for using the [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy) on my to do list (one of the todos in #98), but haven't gotten around writing it yet.

**Comment by galexrt** [comment]
@gianrubio You could use HTTP Basic Auth for the Ingress (at least the nginx ingress), not a whitelist but at least something to protect the Prometheus.

**Comment by gianrubio** [comment]
I'm not completely satisfied using oauth on ingress to protect prometheus, because other developers can drop in the same issue (maybe they're not using operator), but it's best than nothing. 

The latest [ingress release](https://github.com/kubernetes/ingress/blob/858e3ff2354fb0f5066a88774b904b2427fb9433/examples/external-auth/nginx/README.md) has support for the oauth authentication. I'll do the docs for prometheus-operator + oauth during this weekend.

**Comment by brancz** [comment]
As an update of what's going on in the community: there is the idea of custom admission controllers, that automatically and transparently add sidecar containers. The discussion was started mainly around https://istio.io/ to automatically inject sidecar proxies that would terminate incoming ssl traffic, but the same concept should be applicable for authentication means.

**Comment by brancz** [comment]
Either way I don't think this is something the Prometheus Operator can handle by itself, it's a more general problem that needs to be solved by the community. Closing here.

Feel free to keep commenting and re-open if you feel it necessary.
