### ISSUE TITLE
What is the difference between this chart and the one in helm/stable repo?

### ISSUE THREAD

**Issue by larsduelfer** [coreos/prometheus-operator#2153]
Hi all,

while researching how to easily setup prometheus on kubernetes etc. we found this awesome project and now read a lot in various sources on the net. However, something that really confused us was that there is the one here in this repo, and the one in helm/stable for prometheus-operator. The chart here only install the operator itself whereas the one in helm/stable also installs the stuff that is here part of kube-prometheus. 

Now, are they maintained by different groups? And what else is different? We finally got the one in helm/stable running on an AKS cluster but is was really confusing especially because the values to set that you can also overwrite differ.

We would appreciate a short explanation. Thanks in advance!

Regards, Lars

**Comment by brancz** [comment]
They used to be developed here, but @gianrubio migrated them to the stable charts repo. I’ve pinged him a few days ago whether it would be safe to delete them here as I completely understand the confusion.

**Comment by jalberto** [comment]
@brancz in this comment https://github.com/coreos/prometheus-operator/issues/1850#issuecomment-432370004 @vsliouniaev claims helm/stable is the official one now, can you please clarify which one is the "official" one in the documentation?

**Comment by brancz** [comment]
The prometheus-operator team never maintained the helm charts, so I'm the wrong person to ask, I'm talking to @gianrubio about removing them from this repo though, so I guess that answers your question :slightly_smiling_face:, when we delete them we will refer to the "stable" charts repo.

**Comment by jalberto** [comment]
Thanks @brancz 
There is some contradictory information in docs and issues around, checking issue here, I can see not only me is confused, but I also suggest to clarify this matter in the docs

**Comment by vsliouniaev** [comment]
@jalberto you're looking for

https://github.com/helm/charts/tree/master/stable/prometheus-operator

The comment at the top of the readme in this repo references the changes https://github.com/coreos/prometheus-operator/blob/master/helm/README.md#warning
But should probably be updated with the direct link to the new chart.

**Comment by jalberto** [comment]
Thanks!

**Comment by brancz** [comment]
The chart has been removed from this repo and is now fully community maintained there.
