### ISSUE TITLE
Prometheus fine tuning parameters

### ISSUE THREAD

**Issue by dshmatov** [coreos/prometheus-operator#2162]
I didn't find any features of Prometheus fine tuning. Like set CLI options:
```
query.max-concurrency
storage.tsdb.max-block-duration
storage.tsdb.min-block-duration
```
Is any plan to add them?

**Comment by brancz** [comment]
These should never be modified:

```
storage.tsdb.max-block-duration
storage.tsdb.min-block-duration
```

Prometheus has been especially tuned to have well performing values for these, they are only configurable for the Prometheus team to perform performance testing. If you need this for running Thanos properly, then we already have you covered with our Thanos integration where they must both be set to 2h.

Max concurrency is for sure something that we should have. Would you like to add it? :slightly_smiling_face:

**Comment by brancz** [comment]
The remote read flags should be in the remote read spec, yes.

**Comment by brancz** [comment]
I believe all of these are available now in he spec, should any not be, please feel free to open a new issue.
