### ISSUE TITLE
Add metadata to external service to add node name

### ISSUE THREAD

**Issue by mitchellmaler** [coreos/prometheus-operator#2166]
Currently my kubelet, controller manager, scheduler, and etcd all run outside kubernetes but just in a container on the nodes. I was able to add endpoints manually and a service and then a serviceMonitor to scrape the metrics. The issue I have is the instance label is localhost and there is no meta labels to use to create a label with the pod_node_name just like normally. Is there a way to add extra metadata to the metrics like the node name or ip address from the endpoint?

**Comment by brancz** [comment]
If you set the kind in the Endpoints object to node the node name in the same object will automatically be relabeled onto your targets. Otherwise you could also make use of the additionalScrapeConfigs feature that lets you insert plain Prometheus configuration.

**Comment by mitchellmaler** [comment]
Moving to adding scrape configs manually did the job.
