### ISSUE TITLE
kube-prometheus:  Alertmanager peers - wrong service hostname

### ISSUE THREAD

**Issue by bitva77** [coreos/prometheus-operator#2175]
**What did you do?**

Install kube-prometheus

**What did you expect to see?**

The three Alertmanager pods being able to find eachother

**What did you see instead? Under which circumstances?**

each pod running individually.  This causes alerts to be sent 3 times.

* Prometheus Operator version:

kube-prometheus

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubeadm

* Prometheus Operator Logs:

```
level=warn ts=2018-11-14T21:17:18.533922323Z caller=main.go:265 msg="unable to join gossip mesh" err="3 errors occurred:\n\n* Failed to resolve alertmanager-main-0.alertmanager-operated.monitoring.svc:6783: lookup alertmanager-main-0.alertmanager-operated.monitoring.svc on 10.96.0.10:53: no such host\n* Failed to resolve alertmanager-main-1.alertmanager-operated.monitoring.svc:6783: lookup alertmanager-main-1.alertmanager-operated.monitoring.svc on 10.96.0.10:53: no such host\n* Failed to resolve alertmanager-main-2.alertmanager-operated.monitoring.svc:6783: lookup alertmanager-main-2.alertmanager-operated.monitoring.svc on 10.96.0.10:53: no such host"
```

Those services do not exist so the error is correct.  alertmanager-main and alertmanager-operated exist in the monitoring namespace.  Not main-1 or main-2, etc...

```
kubectl get services -n monitoring
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
alertmanager-main       NodePort    10.102.31.246   <none>        9093:30903/TCP      25d
alertmanager-operated   ClusterIP   None            <none>        9093/TCP,6783/TCP   25d
grafana                 NodePort    10.105.5.150    <none>        3000:30902/TCP      25d
kube-state-metrics      ClusterIP   None            <none>        8443/TCP,9443/TCP   25d
node-exporter           ClusterIP   None            <none>        9100/TCP            25d
prometheus-k8s          NodePort    10.107.49.114   <none>        9090:30900/TCP      25d
prometheus-operated     ClusterIP   None            <none>        9090/TCP            25d
prometheus-operator     ClusterIP   None            <none>        8080/TCP            25d
```

**Comment by brancz** [comment]
This is likely a dupe of https://github.com/coreos/prometheus-operator/issues/2103. Could you check the instructions I shared in there? You can also just kill a single Alertmanager and they should start discovering each other correctly. We're working on an Alertmanager release to fix this.

**Comment by bitva77** [comment]
Ah yes.  If I delete one of the Alertmanager pods, the gossip settles and cluster is formed!

Thanks!

-Matt
