### ISSUE TITLE
problem in dashboards on default namespace

### ISSUE THREAD

**Issue by meran** [coreos/prometheus-operator#2178]
**What did you do?**
I cloned the repo and ran the : kubectl create -f manifests/ || true
**What did you expect to see?**
I expect to see the pods of defaukt namespace data in the grafana dashboards
**What did you see instead? Under which circumstances?**
the pods in default namespace  has no data in dashboards
**Environment**
kbernetes 1.9.10
* Prometheus Operator version:
0.25.0
	insert image tag or Git SHA here
0ef7eae62f8a08d8d1528881983d2201aa3224a2
* Kubernetes version information:
1.9.10
	insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 
kubeadm cluster
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
kubeadm
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
level=info ts=2018-11-29T21:13:30.063741173Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:13:30.141500274Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-29T21:13:37.566768678Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:13:45.070447703Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:13:52.573807287Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:00.076994407Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:07.581134301Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:15.084440091Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:22.588634415Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:30.091848788Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:37.596223786Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:45.099684854Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:14:52.602913322Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:00.106727766Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:07.610646869Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:15.11568145Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:16.117240871Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-29T21:15:22.618651259Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:30.122726673Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:37.626922828Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:45.129829374Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-29T21:15:52.633052875Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```
insert Prometheus Operator logs relevant to the issue here
```none

**Comment by brancz** [comment]
can you share a screenshot of what you are seeing? And share the output of kubectl get pods of the namespace (possibly kubectl top as well)?

**Comment by meran** [comment]
![image](https://user-images.githubusercontent.com/542005/49288389-43dce300-f4a9-11e8-8262-46128e60782d.png)
I added some of the get pods data in default namespace
![image](https://user-images.githubusercontent.com/542005/49288580-d41b2800-f4a9-11e8-9f5b-7114971679a1.png)

kubectl top pod
W1130 14:12:08.966382    6941 top_pod.go:192] Metrics not available for pod default/1-action-management-metadata-tjkl5, age: 26h2m12.966357849s
error: Metrics not available for pod default/1-action-management-metadata-tjkl5, age: 26h2m12.966357849s

**Comment by brancz** [comment]
can you share what you are seeing on the `/targets` page of the Prometheus UI?

**Comment by meran** [comment]
issue solved. I don't know why the data points were empty but I managed to create new dashboards so the data exists

**Comment by brancz** [comment]
in that case closing here
