### ISSUE TITLE
Inconsistent job labels between prometheus-operator discovery service and kube-prometheus

### ISSUE THREAD

**Issue by seanson** [coreos/prometheus-operator#2180]
**What did you do?**

Deployed prometheus-operator with kubernetes-mixin for alerting.

**What did you expect to see?**

Matching job labels between prometheus-operator and kubernetes-mixin.

**What did you see instead? Under which circumstances?**

The job labels provisioned by [contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-bootkube.libsonnet] do not match the [upstream job selectors](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/64a06754786ca1a28929b9fb05c381085dcdd44c/config.libsonnet), which causes alerts (like CoreDNSDown and KubeVersionMismatch) that depend on these selectors to misfire.

Looking at the other configuration it looks like these are the only discovery services that append `-prometheus-discovery` and so I think the name change should happen in this repo.

**Environment**

* Prometheus Operator version:

Current master (f8343b294f49c9009478138bd5572573f28811ec)

* Kubernetes version information:

```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}```

* Kubernetes cluster kind: 

kops 1.10

* Manifests:
N/A

* Prometheus Operator Logs:
N/A

**Comment by brancz** [comment]
I commented in #2181, could you elaborate regarding my comment either here or in #2181?

**Comment by sjtyro** [comment]
Apologies, our service discovery was missing the k8s-app label and causing the metrics job label to default to the full suffixed name.

**Comment by seanson** [comment]
Closed PR as it was misconfiguration on our side for the service discovery label as per my comment in the PR. Thanks for the quick response @brancz!
