### ISSUE TITLE
readiness probe is causing Prometheus and alternmanager pods to stop

### ISSUE THREAD

**Issue by krdpk17** [coreos/prometheus-operator#2184]
**What did you do?**
In Diamanti platform (K8s based platform), I have tried to deploy Prometheus operator. 

**What did you expect to see?**
I expect Prometheus and alert manager PODs to come up. In my setup, 192.168.1.30 IP is not reachable via host machine. From container, it is reachable.  It is by design. So, we expect to either disable the readiness probe or configure it as command type.

**What did you see instead? Under which circumstances?**

I have seen that Prometheus app and alter manager pod is failing. Kubectl describe POD mentions that it is due to failure of readiness probe (below log for Prometheus POD)

```
Warning  Unhealthy              1m (x4 over 1m)  kubelet, diamanti-251  Readiness probe failed: Get http://192.168.1.30:9090/-/ready <http://192.168.1.30:9090/-/ready> : net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

  Warning  Unhealthy              1m (x4 over 1m)  kubelet, diamanti-251  Liveness probe failed: Get http://192.168.1.30:9090/-/healthy <http://192.168.1.30:9090/-/healthy> : net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Environment**
Diamanti (https://diamanti.com)
* Prometheus Operator version:
0.26 
	insert image tag or Git SHA here

* Kubernetes version information:
v1.10.7

	insert output of `kubectl version` here

* Kubernetes cluster kind: 
Diamanti
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
[diamanti@diamanti-250 duke-demo-nimata]$ kubectl logs prometheus-operator-bdf79ff67-vm42l -n monitoring
ts=2018-11-30T13:57:29.993489897Z caller=main.go:165 msg="Starting Prometheus Operator version '0.25.0'."
level=info ts=2018-11-30T13:57:30.20449681Z caller=operator.go:371 component=prometheusoperator msg="connection established" cluster-version=v1.10.7
level=info ts=2018-11-30T13:57:30.20464881Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.10.7
level=info ts=2018-11-30T13:57:31.175506408Z caller=operator.go:627 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-11-30T13:57:31.276191527Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-11-30T13:57:31.295925084Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-11-30T13:57:31.313483496Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-11-30T13:57:34.181761181Z caller=operator.go:225 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-11-30T13:57:34.473628625Z caller=operator.go:180 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2018-11-30T13:57:34.473823016Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T13:57:34.575307748Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T13:57:40.343569284Z caller=operator.go:387 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-11-30T13:57:41.27507522Z caller=operator.go:322 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2018-11-30T13:57:41.275351463Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-30T13:57:41.874170465Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-30T13:57:42.189645839Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-30T13:58:48.008041968Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:00:32.624330987Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:01:39.937784101Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:03:07.962795373Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:04:46.397779302Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:05:51.71482254Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-30T14:06:15.021595959Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-11-30T14:06:18.705412624Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-11-30T14:07:34.186084495Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
[diamanti@diamanti-250 duke-demo-nimata]$
```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
I wonder if that's actually a problem with the Prometheus Operator, the probes use the Pod IP, so this sounds like no probe would ever work on that platform, which would make it a non conformant Kubernetes cluster.

**Comment by krdpk17** [comment]
@brancz Thanks for the message. 
<< which would make it a non conformant Kubernetes cluster.>>
Do you mean that It is mandatory to use readiness probe for prometheus operator??

**Comment by brancz** [comment]
I'm saying there is nothing special about Prometheus' readiness probe that we setup, we've had it in place for a very long time and this is the first time that there has been an issue, so I'd like to make sure other readiness probes do indeed work on your cluster. Can you confirm that?
