### ISSUE TITLE
Not support custom-metrics-api after v0.18.1

### ISSUE THREAD

**Issue by lw8008** [coreos/prometheus-operator#2190]
**What did you do?**
I'm trying to get deploy guide of custom-metrics-api in the latest version but failed, only see before v0.18.1

**What did you expect to see?**
Do we still support using that?

* Prometheus Operator version:
prometheus-operator:v0.23.2

* Kubernetes version information:
v1.11.2

* Prometheus Operator Logs:

```
When i use the v0.18.1 guide, got below error in custom-metrics-apiserver:

E1203 12:26:17.652671       1 reflector.go:322] github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/informers/factory.go:130: Failed to watch *v1.Pod: unknown (get pods)
E1203 12:26:18.580130       1 reflector.go:322] github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/informers/factory.go:130: Failed to watch *v1.Node: unknown (get nodes)

```

**Comment by brancz** [comment]
Note that it was never supported, it is still in an experimental directory, but it would be nice to figure out what’s happening anyways. Can you share more precisely some steps to reproduce this?

**Comment by lw8008** [comment]
@brancz i follow this guide https://github.com/DirectXMan12/k8s-prometheus-adapter and works with prometheus-operator.
