### ISSUE TITLE
Make promArg "--storage.tsdb.min-block-duration" configurable

### ISSUE THREAD

**Issue by thomschke** [coreos/prometheus-operator#2196]
**What did you do?**
Storing historical timeseries (see prometheus/prometheus#4759)

**What did you expect to see?**
I need a prometheus instance started with `--storage.tsdb.min-block-duration` more then 2 hours.

**What did you see instead? Under which circumstances?**
This argument has a fixed value of `2h`.

https://github.com/coreos/prometheus-operator/blob/d37bc833ab4691fe67e17da69893f8a314728eed/pkg/prometheus/statefulset.go#L740

**Environment**

* Prometheus Operator version:

	0.26.0

**Comment by brancz** [comment]
It is not recommended to modify the min block duration, it is specifically chosen to be optimized on all dimensions. Two hours is the optimal point where compression is best. And increasing the time means your Prometheus server will use significantly more memory (as the 2h time frame is held in memory in form of the write-ahead-log).

**Comment by thomschke** [comment]
I understand, but it's the only chance to store historical timeseries at the moment. 

I know my use case is not very common, but at the moment I can't use your operator and have to build my own helm chart :-(

**Comment by brancz** [comment]
What do you mean by store historical timeseries? Are you talking about bulk inserting data?

**Comment by thomschke** [comment]
Yes.

**Comment by brancz** [comment]
Bulk inserting is not a supported feature in Prometheus, and this “workaround” is truly a workaround at best. If that’s what you want to do I would recommend preparing the Prometheus tsdb locally on your computer and then starting Prometheus with the produced database in its persistent volume.

For what it’s worth I’ve heard there is some work on backfilling data being done, but no ETA for this feature.

**Comment by thomschke** [comment]
Thanks for your informations.

**Comment by wangycc** [comment]
Hi @brancz I also want to modify the "--storage.tsdb.min-block-duration" parameter value.
Whenever the data flushes to disk, it will exceed the disk IO load. I want to reduce the flush interval.

**Comment by abhi4u1947** [comment]
Still open issue:

https://github.com/prometheus-operator/prometheus-operator/issues/4414#issuecomment-2402832211
