### ISSUE TITLE
Update helm chart to support Thanos v0.2.0

### ISSUE THREAD

**Issue by dbonatto** [coreos/prometheus-operator#2210]
A new version of Thanos was just released and with the features and fixes also comes some breaking changes on the configuration flags. As the Thanos version is pinned and will break the chart templates, some work will be needed to support this update.

https://github.com/improbable-eng/thanos/releases/tag/v0.2.0

**Comment by squat** [comment]
@dbonatto the helm charts have moved to a new home in 
https://github.com/helm/charts/tree/master/stable/prometheus-operator. The charts in this repo are going away. Please submit an issue there to update the charts :)
