### ISSUE TITLE
Use private repository for all images

### ISSUE THREAD

**Issue by VinceMD** [coreos/prometheus-operator#2219]
**What did you do?**
check doc https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md on how to specify private repo for docker images with jsonnet 

**What did you expect to see?**
I expected to see fields for all images used

**What did you see instead? Under which circumstances?**
I saw the doc only mentions 3 images:

- prometheus 
- prometheus-alertmanager
- Thanos

I could edit the manifests before apply but I'd rather do it the clean way with jsonnet. Is it possible to specify the following images:

```
grafana/grafana
quay.io/prometheus/node-exporter
quay.io/coreos/configmap-reload (think this comes from prometheus operator?)
quay.io/coreos/kube-rbac-proxy
quay.io/coreos/kube-state-metrics
quay.io/coreos/prometheus-config-reloader
```

**Comment by metalmatze** [comment]
Those 3 images are specified by the Prometheus Operator itself and thus need to be specified in the Custom Resource. All the other components are a pure configuration management with jsonnet.

All components have a `_config` object which itself has an `imageRepos` object specifying the base images.
Here's an excerpt from kube-state-metrics:
```jsonnet
    imageRepos+:: {
      kubeStateMetrics: 'quay.io/coreos/kube-state-metrics',
      kubeRbacProxy: 'quay.io/coreos/kube-rbac-proxy',
      addonResizer: 'quay.io/coreos/addon-resizer',
    },
```

So in the kube-prometheus.jsonnet file which assembles all components, you can introduce a `_config` object that overrides these imageRepos for all components necessary.

https://github.com/coreos/prometheus-operator/blob/a174c8b1281219526db395a669d65a5bac7fe425/contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet#L21

In this object you should do a diff like this:

```diff
  _config+:: {
    namespace: 'default',

+   imageRepos+:: {
+     kubeStateMetrics: 'my.registry.com/coreos/kube-state-metrics',
+     kubeRbacProxy: 'my.registry.com/coreos/kube-rbac-proxy',
+     addonResizer: 'my.registry.com/coreos/addon-resizer',
+     prometheusAdapter: 'my.registry.com/coreos/k8s-prometheus-adapter-amd64',
+   },
```

**Comment by VinceMD** [comment]
thanks all clear!

**Comment by patrickjane** [comment]
@metalmatze Hi, didn't want to create a new topic, since I have the exact same question. Could you elaborate a bit more on how to make those changes? I have installed the operator using kustomize / bundle.yaml. How would I patch private registries?
