### ISSUE TITLE
Ensure prometheus and alert manager are using Parallel policy

### ISSUE THREAD

**Issue by kargakis** [coreos/prometheus-operator#2221]
Both the prometheus and alert manager should be using Parallel podManagementPolicy, otherwise the deployment of the whole monitoring stack may take some time to complete unnecessarily (see https://github.com/openshift/openshift-azure/issues/850). Ideally we would like to have this fixed for OSA v3.11.

@openshift/sig-azure @openshift/sig-monitoring

**Comment by kargakis** [comment]
@mjudeikis @jim-minter

**Comment by kargakis** [comment]
Seems that the alert manager using Ordered policy is intentional

https://github.com/coreos/prometheus-operator/pull/2220#pullrequestreview-184662763

**Comment by metalmatze** [comment]
The Prometheus StatefulSet seems to have this already enabled. I'm currently digging into the code and trying to find out why this is not picked up when the StatefulSet is applied.

With regards to Alertmanager, @mxinden made some good comments: Whenever Alertmanager is running without disks we want to ensure that the state is gossiped across the cluster. Therefore recreating a single Pod one by one is want we want. Deleting and then creating Alertmanager Pods would most likely lose all state.

**Comment by kargakis** [comment]
> With regards to Alertmanager, @mxinden made some good comments: Whenever Alertmanager is running without disks we want to ensure that the state is gossiped across the cluster. Therefore recreating a single Pod one by one is want we want. Deleting and then creating Alertmanager Pods would most likely lose all state.

Interesting, it seems this is driven from the alert manager config which set in the cluster monitoring operator, right? (eg. [here](https://github.com/openshift/openshift-azure/blob/5fd69b601d1f4ec130fa1ab3d786c25cd065026d/pkg/addons/data/ConfigMap/openshift-monitoring/cluster-monitoring-config.yaml#L31) is ours) In case we use persistent storage, wouldn't it be possible to set podManagementPolicy to Parallel, then?

**Comment by squat** [comment]
In that case it could be possible to use the parallel pod management policy. We'd need to select he management policy based on the type of persistence declared in the alertmanager object.

**Comment by paulfantom** [comment]
Fixed in #2676
