### ISSUE TITLE
Can't set objstore option for thanos.

### ISSUE THREAD

**Issue by gangseok514** [coreos/prometheus-operator#2225]
**What did you do?**
Thanos latest version supports objstore.config options instead of s3.xxx (these are removed)
So when I use set thanos v0.2.0, storage configuration is not applied properly.

--objstore.config-file=/etc/thanos/thanos-s3.yaml

https://github.com/improbable-eng/thanos/blob/master/cmd/thanos/flags.go

```go
func regCommonObjStoreFlags(cmd *kingpin.CmdClause, suffix string) *pathOrContent {
	fileFlagName := fmt.Sprintf("objstore%s.config-file", suffix)
	bucketConfFile := cmd.Flag(fileFlagName, fmt.Sprintf("Path to YAML file that contains object store%s configuration.", suffix)).
		PlaceHolder("<bucket.config-yaml-path>").String()

	bucketConf := cmd.Flag(fmt.Sprintf("objstore%s.config", suffix), fmt.Sprintf("Alternative to '%s' flag. Object store%s configuration in YAML.", fileFlagName, suffix)).
		PlaceHolder("<bucket.config-yaml>").String()

	return &pathOrContent{
		name: fmt.Sprintf("objstore%s.config", suffix),

		path:    bucketConfFile,
		content: bucketConf,
	}
}
```

I can't find any related code in prometheus-operator.

**What did you expect to see?**
I want to add objstore.config and objstore.config.file options.

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by rtkgjacobs** [comment]
Related code
https://github.com/coreos/prometheus-operator/blob/0ea64587a152727e072986dbe6cd60a06b57a545/pkg/prometheus/statefulset.go#L702-L732

Errror(s) seen within sidecar when trying to use `v0.2.0` of  Thanos...

```
Error parsing commandline arguments: unknown long flag '--s3.bucket'
thanos: error: unknown long flag '--s3.bucket'
```

Looking at the thanos sidecar we can see the operator is attempting to pass in s3 bucket details via args

```
thanos-sidecar:
    Container ID:  docker://6e19519c626edbfcc6354c31935828f88e78ab5dff4cb7552d88b556edf44570
    Image:         improbable/thanos:v0.2.0
    Image ID:      docker-pullable://improbable/thanos@sha256:7555f2255dbfa7791cb9630a4633d8e22c1fba34071eec13954a2f44ec203ad1
    Ports:         10902/TCP, 10901/TCP, 10900/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      sidecar
      --prometheus.url=http://127.0.0.1:9090
      --tsdb.path=/prometheus
      --cluster.address=[$(POD_IP)]:10900
      --grpc-address=[$(POD_IP)]:10901
      --cluster.peers=thanos-peers:10900
      --s3.bucket=test
      --s3.endpoint=minio-service:9000
      --s3.insecure
      --s3.signature-version2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 18 Dec 2018 15:21:25 -0500
      Finished:     Tue, 18 Dec 2018 15:21:25 -0500
    Ready:          False
    Restart Count:  17
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /prometheus from prometheus-prometheus-operator-prometheus-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-operator-prometheus-token-bp7jx (ro)
```

However, with v0.2.0 and newer for Thanos, a `ConfigSet` with the s3 parameters should be setup in K8's and then used with a `volumeMount` via the `--objstore.config-file=/your/file.yaml` used via the `volumeMount` provided by a creates `ConfigSet`.

**Comment by gangseok514** [comment]
I made PR for this.
https://github.com/coreos/prometheus-operator/pull/2226#issuecomment-447338905
