### ISSUE TITLE
helm fails to install stable/prometheus-operator v0.26.0

### ISSUE THREAD

**Issue by shaunster666** [coreos/prometheus-operator#2229]
What did you do?

I used kops v1.10.0 to build a small cluster on GCE.

Then I installed helm v2.12.0 like this:

```
install-helm.sh
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

```
But when I executed

`helm install stable/prometheus-operator --name=prometheus-operator --namespace=monitoring`

I got this error:

Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists 

**What did you expect to see?**

I expected the chart to be installed

**What did you see instead? Under which circumstances?**

The install failed

**Environment**
GCP

* Prometheus Operator version:
v0.26.0
	

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kops create cluster dev.k8s.local  --state gs://maxown-openebs-dev/  --kubernetes-version=1.10.0 --node-count 2  --vpc openebs-e2e --zones europe-west4-a,europe-west4-b,europe-west4-c --cloud=gce --yes --node-size n1-standard-1 --master-size n1-standard-1 --master-count 1 --subnets dev

* Manifests

* Prometheus Operator Logs:

**Comment by rtkgjacobs** [comment]
From docs FYI
https://github.com/helm/charts/tree/master/stable/prometheus-operator#uninstalling-the-chart

> CRDs created by this chart are not removed by default and should be manually cleaned up:
> ```kubectl delete crd prometheuses.monitoring.coreos.com
> kubectl delete crd prometheusrules.monitoring.coreos.com
> kubectl delete crd servicemonitors.monitoring.coreos.com
> kubectl delete crd alertmanagers.monitoring.coreos.com```

**Comment by shaunster666** [comment]
Thanks for pointing this out, but I still get the same error. i.e I executed 

```
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
```

then

`helm install stable/prometheus-operator --name prometheus-operator --namespace monitoring`

and got the same error:

Error: release prometheus-operator failed: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists

However I have found a work around by disabling

`createCustomResource: false`

in prometheus-operator/values.yaml

**Comment by paskal** [comment]
This problem described as https://github.com/helm/charts/issues/9941

**Comment by shaunster666** [comment]
Helm v1.12.1 resolves this issue, many thanks...

**Comment by briantopping** [comment]
This is still a problem.

**Comment by badarou** [comment]
> Thanks for pointing this out, but I still get the same error. i.e I executed
> 
> ```
> kubectl delete crd prometheusrules.monitoring.coreos.com
> kubectl delete crd servicemonitors.monitoring.coreos.com
> kubectl delete crd alertmanagers.monitoring.coreos.com
> ```
> then
> 
> `helm install stable/prometheus-operator --name prometheus-operator --namespace monitoring`
> 
> and got the same error:
> 
> Error: release prometheus-operator failed: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
> 
> However I have found a work around by disabling
> 
> `createCustomResource: false`
> 
> in prometheus-operator/values.yaml



I have a problem is quite different.
When I execute the command
kubectl port-forward -n monitoring prometheus-prometheus-operator-prometheus-0 9090 on my cluster Kubernetes (AKS) it gives me this result
Forwarding from 127.0.0.1.19090 -> 9090
Forwarding from [:: 1]: 9090 -> 9090
and when I put the URL http://127.0.0.1:9090/targets on my browser, I have no result.

 $ kubectl get pods -n monitoring
NAME                                                                                 READY STATUS RESTARTS AGE
alertmanager-prometheus-operator-alertmanager-0            2/2   Running     0     11h
prometheus-operator-grafana-8549568bc7-zntgz                2/2   Running     0     11h
prometheus-operator-kube-state-metrics-5fc876d8f6-v5zh7 1/1 Running     0     11h
prometheus-operator-operator-75d88ccc6-t4lt5                    1/1 Running     0     11h
prometheus-operator-prometheus-node-export-zqk7t          1/1 Running     0     11h
prometheus-prometheus-operator-prometheus-0                  3/3 Running     1     11h

What should be done ? or how to forwarding prometheus from my public cloud to my local machine.
Thank you

**Comment by SaraBenShabbat** [comment]
How do I install Helm v1.12.1 ? 
How can I specified the version to install ?
