### ISSUE TITLE
Hit maximum Secret size for prometheus.yaml in Kubernetes

### ISSUE THREAD

**Issue by wleese** [coreos/prometheus-operator#2234]
**What did you do?**
Rolled out Prometheus-operator 0.26.0

**What did you see instead? Under which circumstances?**
```
operator.go:866] Sync "monitoring/platform-001" failed: creating config failed: Secret "prometheus-platform-001" is invalid: data: Too long: must have at most 1048576 characters
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Google cloud

We allow our users to create their own ServiceMonitors, meaning we have limited control over their efficiency in doing so. Is this something other people have run into? I wasn't able to find an existing issue.

Needless to say compression would help greatly. 1mb prometheus config compressed with default gzip params to 22kb.

Issue for Thanos config reloader decompression support: https://github.com/improbable-eng/thanos/issues/692

Suggestion (needs work):
https://github.com/coreos/prometheus-operator/pull/2243

**Comment by metalmatze** [comment]
I don't think there's an automatic way to fix this right now.
The thing that comes to my mind:
1. Have multiple Prometheuses running. ServiceMonitors get labels and you specify for which labels each Prometheus is responsible.
2. Have multiple Prometheuses running and tell those which namespaces to watch for ServiceMonitors and do sharing that way.

**Comment by wleese** [comment]
Thanks for the suggestions. 

This won't work for me however, as it means scaling my prometheus instances based on configuration size. Not to mention unnecessary complexity with regard to alerting and grafana dashboarding.

**Comment by wleese** [comment]
@brancz yes, but it pushes the problem out so significantly that I believe it is worth the trouble (98% compression on my sample config).

**Comment by brancz** [comment]
Makes sense, and wow 98% is a lot, but reasonable given how repetitive the config is. Thanks a lot for taking this on!
