### ISSUE TITLE
protect Prometheus from scraping large metrics endpoint 

### ISSUE THREAD

**Issue by devendra-nvidia** [coreos/prometheus-operator#2247]
**What did you do?**
I started couple of  jobs that started exposing metrics endpoint that what about 100MB. If by mistake I started 100 jobs that could put lot of pressure on prometheus. Is there a way to stop Prometheus from scraping metrics end point thats more than certain size?

**Comment by devendra-nvidia** [comment]
what restriction does SampleLimit  enforce?

**Comment by brancz** [comment]
Sample limit enforces that a single scrape cannot be larger than the given amount of samples.
