### ISSUE TITLE
kube-state-metrics fails to start when PodSecurityPolicy is enabled

### ISSUE THREAD

**Issue by idanlevin** [coreos/prometheus-operator#2249]
**What did you do?**
Create a cluster with PodSecurityPolicy enabled and try to deploy the prometheus-operator

**What did you expect to see?**
kube-state-metrics should have been deployed succesfully

**What did you see instead? Under which circumstances?**
Deployment fails to start:
```
>>kubectl get deploy -n monitoring
NAME                                                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
monitoring-grafana                                         1              1                 1                      1                 1d
monitoring-kube-state-metrics                       1              0                 0                      0                 1d
monitoring-prometheus-oper-operator         1              1                  1                      1                 1d
```

and the message is:
```
message: 'pods "monitoring-kube-state-metrics-7d5d8f9446-" is forbidden: unable to validate against any pod security policy: []'
reason: FailedCreate
```

**Environment**

* Prometheus Operator version: 

0.26.0

* Kubernetes version information:

1.12.1

* Kubernetes cluster kind: 

AKS-Engine

* Manifests:

```
insert manifests relevant to the issue
```

I deployed using `helm install stable/prometheus-operator`

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by idanlevin** [comment]
I've opened a similar issue here:
https://github.com/coreos/prometheus-operator/issues/2249

**Comment by brancz** [comment]
This seems curious to me, we have something very similar in OpenShift to PodSecurityPolicies, with which kube-state-metrics works just fine (we needed a separate policy for node-exporter as it requires hostnetwork). Do you have any policies created? Any type of restrictive PSP should work just fine.

**Comment by idanlevin** [comment]
@brancz I think you're right, I might have deleted the default PSPs. 

I've recreated them and it seems to be working.

I'll close the issue
