### ISSUE TITLE
kube-prometheus: Remove default Prometheus rules through jsonnet

### ISSUE THREAD

**Issue by twittyc** [coreos/prometheus-operator#2250]
Hey guys, I'm running K8s in EKS and therefore cannot scrap control-plan services such as kube-apiserver. Is there a way to disable/remove some of the default alerts and rules using the jsonnet config, such as the kube.apiserver section? Thanks!

**Comment by metalmatze** [comment]
We do want to do this: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/50

Currently we don't provide anything that can remove specific alerting rules.
Something like this should work tough:
```jsonnet
{
  prometheusAlerts+:: {
    groups+:
      std.map(
        function(group)
          if group.name == 'general.rules' then
            group {
              rules: [
                // iterate over rules and only returns the ones not matching the unwanted names
              ],
            }
          else
            group,
        super.groups
      ),
  },
}
```

**Comment by kppullin** [comment]
In case someone else stumbles upon this as I did, below are two working samples on my end.

1. The first example filters out the `KubeStatefulSetReplicasMismatch` alert from the `kubernetes-apps` group, leaving all other rules in place.
2. The second example _updates_ the `KubeStatefulSetReplicasMismatch` alert with a new expression.

Note: `prometheus-alerts.json` is our custom alert config file.  Omit or change `(import 'prometheus-alerts.json') +` as needed.

```
    prometheusAlerts+:: {
      groups: (import 'prometheus-alerts.json') +
        std.map(
          function(group)
            if group.name == 'kubernetes-apps' then
              group {
                rules: std.filter(function(rule)
                  rule.alert != "KubeStatefulSetReplicasMismatch",
                  group.rules
                )
              }
            else
              group,
          super.groups
        ),
    },
```

```
    prometheusAlerts+:: {
      groups: (import 'prometheus-alerts.json') +
        std.map(
          function(group)
            if group.name == 'kubernetes-apps' then
              group {
                rules: std.map(function(rule)
                  if rule.alert == "KubeStatefulSetReplicasMismatch" then
                    rule {
                      expr: "kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\",statefulset!=\"vault\"} != kube_statefulset_status_replicas{job=\"kube-state-metrics\",statefulset!=\"vault\"}"
                    }
                  else
                    rule
                  ,
                  group.rules
                )
              }
            else
              group,
          super.groups
        ),
    },
```

**Comment by wescran** [comment]
@metalmatze  @kppullin 
#### Just wanted to say thanks! 
I was having issues trying to update the default prometheus alerts. I used your second example and just dropped it into the `config.jsonnet`.
 
**If anyone else sees this**, I just made the above example into a local variable and added it to the `local kp`  as seen in the config layout seen [here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/example.jsonnet). The result looked like this for a different rule I was trying to change :
```
local update = {
  prometheusAlerts+:: {
    groups: std.map(
      function(group)
        if group.name == 'kube-prometheus-node-alerting.rules' then
          group {
            rules: std.map(function(rule)
              if rule.annotations.message == "Device {{ $labels.device }} of node-exporter {{ $labels.namespace }}/{{ $labels.pod }} will be full within the next 24 hours." then
                rule {
                  expr: |||
                    (node:node_filesystem_usage: > 0.96) and (predict_linear(node:node_filesystem_avail:[6h], 3600 * 24) < 0)
                  ||| % $._config
                }
              else if rule.annotations.message == "Device {{ $labels.device }} of node-exporter {{ $labels.namespace }}/{{ $labels.pod }} will be full within the next 2 hours." then
                rule {
                  expr: |||
                    (node:node_filesystem_usage: > 0.96) and (predict_linear(node:node_filesystem_avail:[30m], 3600 * 2) < 0)
                  ||| % $._config
                }
              else
                rule
              ,
              group.rules
            )
          }
        else
          group,
        super.groups
    ),
  },
};

local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + update + { ...
};
...
```
I'm wondering if this should be mentioned in the docs for [developing prometheus rules](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md). It mentions how to add new rules but nothing on making changes to the default rules. Being able to edit them mitigates having to manually edit the config files once generated. 

Anyways thanks again, this was a big help :)

**Comment by brancz** [comment]
@wescran if you could create a PR to add this to the docs, that would be incredibly highly appreciated! :slightly_smiling_face:

**Comment by brancz** [comment]
kube-prometheus was extracted into a separate repo (coreos/kube-prometheus). Feel free to create a PR against that repo adding docs about this. Closing here.
