### ISSUE TITLE
Feature request for --rules.alert.resend-delay Prometheus options.

### ISSUE THREAD

**Issue by zuzzas** [coreos/prometheus-operator#2253]
Wanted to specify `--rules.alert.resend-delay=29s`, but haven't found a way to specify it in the spec of a Prometheus custom object.

**Comment by brancz** [comment]
Happy to take a PR to configure this on a Prometheus object!

**Comment by zuzzas** [comment]
@brancz
And here I thought that my amazing issue will add the feature by itself. :)
