### ISSUE TITLE
grafana-watcher is stuck on Waiting for Grafana to be available

### ISSUE THREAD

**Issue by anton-pydev** [coreos/prometheus-operator#226]
**What did you do?**
I have deployed all default manifests with deploy script .
**What did you expect to see?**
Expect to see grafana up and dashboards loaded 
**What did you see instead? Under which circumstances?**
Dashboards are not loaded 
**Environment**
prometheus-opetrator  = Latest 
* Kubernetes version information:
Kubernetes = 1.5.2 
	insert output of `kubectl version` here
-bash-4.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-12T23:31:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```
kubectl -n monitoring logs grafana-3997532808-3pvd5 grafana

t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert dashboard_id"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_notification table v1"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="Add column is_default"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert_notification org_id & name"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old annotation table v4"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="create annotation table v5"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 0 v3"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 1 v3"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 2 v3"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 3 v3"
t=2017-03-22T19:58:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 4 v3"
t=2017-03-22T19:58:46+0000 lvl=info msg="Created default admin user: [admin]"
t=2017-03-22T19:58:46+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-03-22T19:58:46+0000 lvl=warn msg="Plugin dir does not exist" logger=plugins dir=/var/lib/grafana/plugins
t=2017-03-22T19:58:46+0000 lvl=info msg="Plugin dir created" logger=plugins dir=/var/lib/grafana/plugins
t=2017-03-22T19:58:46+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-03-22T19:58:46+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-03-22T19:58:46+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=

-bash-4.2$ kubectl -n monitoring logs grafana-3997532808-3pvd5 grafana-watcher
2017/03/22 19:58:45 Waiting for Grafana to be available.
2017/03/22 19:59:16 Waiting for Grafana to be available.
2017/03/22 19:59:47 Waiting for Grafana to be available.
2017/03/22 20:00:18 Waiting for Grafana to be available.
2017/03/22 20:00:49 Waiting for Grafana to be available.
2017/03/22 20:01:20 Waiting for Grafana to be available.
2017/03/22 20:01:51 Waiting for Grafana to be available.
2017/03/22 20:02:22 Waiting for Grafana to be available.
2017/03/22 20:02:53 Waiting for Grafana to be available.
2017/03/22 20:03:24 Waiting for Grafana to be available.
2017/03/22 20:03:55 Waiting for Grafana to be available.

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Thanks for reporting! Very interesting. Are you able to reproduce this?

**Comment by anton-pydev** [comment]
Appeared to be K8s DNS issue . My bad :-(

**Comment by brancz** [comment]
No problem! Could you explain what happened? It would be great if we could start collecting everything we see in a troubleshooting document. If you want to you can create a PR to the docs with a new document called `troubleshooting.md`. :slightly_smiling_face:
