### ISSUE TITLE
Need to Configure SMTP, Not sure where to begin. 

### ISSUE THREAD

**Issue by jxipol4215** [coreos/prometheus-operator#2260]
Hello, I am trying to figure out how to configure SMTP. I am using Prometheus-operator with Grafana as the front-end along with Kubernetes and I need to set up an Alert Notification using SMTP. I am having a hard time finding any tutorials. Can anyone help me? -Thank you

**Comment by ArjonBu** [comment]
So you are using Grafana for alerting? If yes, you just need to edit the configmap of grafana (grafana.ini) with the additional settings. http://docs.grafana.org/installation/configuration/#smtp 

If you are using Alertmanager https://github.com/prometheus/alertmanager/issues/275

**Comment by brancz** [comment]
As @ArjonBu already answered this, I'm going to close this here, but if you have any follow up questions, please feel free to ask.
