### ISSUE TITLE
Prometheus Operator should validate Prometheus Rule expression syntax

### ISSUE THREAD

**Issue by mikelduke** [coreos/prometheus-operator#2273]
**What did you do?**
Create a PrometheusRule with an invalid prometheus expression, like missing quotes or unmatched parentheses in the query.

**What did you expect to see?**
Prometheus Operator should syntax check and reject the invalid rule before adding it to the configmap of Prometheus Rules and log a helpful message with at least the namespace name, PrometheusRule object name, and error information. Ouput similar to promtools check rules CLI would be great.

**What did you see instead? Under which circumstances?**
Prometheus Operator adds the invalid rule to the configmap. This causes Prometheus to fail to reload the config file, while it keeps using the previous version. Finding the offender can be a pain and users must wait until the broken rule is fixed before seeing newer rule updates. If the Prometheus pod bounces, it cannot restart due to the invalid config.

**Comment by mikelduke** [comment]
It would be even better if the api server rejected the creation or update of a PrometheusRule object with bad rules.

**Comment by brancz** [comment]
Agreed. We've been thinking to add a validating webhook that validates the PromQL expressions. Biggest problem with this is cert setup is somewhat difficult so we've been discussing what we can do with the cert-manager people.

**Comment by Hashfyre** [comment]
This issue also has taken down entire prometheus monitoring stack.

For us the bad rule had:
-  `for: "2"` in stead of a `for: 2m`
- `(expr) > 10m` in stead of a `(expr) > 10`

We ended up losing monitoring data for around an hour.

**Comment by Hashfyre** [comment]
OK, I found out a way to do CI validation of `PrometheusRules` manifests.
`cat ./rulefile.yaml| yq --yaml-output .spec | promtool check rules /dev/stdin`
uses: 
 - `pip install yq`
 - `go get github.com/prometheus/prometheus/cmd/promtool`

**Comment by brancz** [comment]
I recommend @Hashfyre's solution until the validating webhook is implemented (if anyone would like to get started on this, we're happy to provide some guidance).

**Comment by mikelduke** [comment]
> OK, I found out a way to do CI validation of `PrometheusRules` manifests.
> `cat ./rulefile.yaml| yq --yaml-output .spec | promtool check rules /dev/stdin`
> uses:
> 
> * `pip install yq`
> * `go get github.com/prometheus/prometheus/cmd/promtool`

I used a similar solution. I extracted the spec from the PrometheusRule.yaml and then used promtool in the Prometheus Docker image with the yaml mounted as a volume during a CI stage instead of installing it.

**Comment by mikelduke** [comment]
> Agreed. We've been thinking to add a validating webhook that validates the PromQL expressions. Biggest problem with this is cert setup is somewhat difficult so we've been discussing what we can do with the cert-manager people.

There is a Kubernetes feature request that may help to address the cert difficulties: https://github.com/kubernetes/kubernetes/issues/72944 I like the approach of referencing a config map or secret, sounds easier to manage than storing the caBundle as a string in a config that would be distributed.

Until something is figured out with certs, what about calling the Prometheus ruleformatter when generating the rule files? This would be too late to reject the bad rules from admission to the cluster, but it would at least protect Prometheus. It could log or otherwise alert when a bad config is detected.

**Comment by brancz** [comment]
Fact is, there are already broken rules out there, so even when we have the admission webhook in place (and people use it), then there might still be legacy laying around. I'm happy with having status conditions added to the `PrometheusRule` object that reflect whether promtool was able to verify the rules or not.

**Comment by vsliouniaev** [comment]
> I recommend @Hashfyre's solution until the validating webhook is implemented (if anyone would like to get started on this, we're happy to provide some guidance).

@brancz 
Curious what your thoughts are around this, particularly around the approach to managing security. Do you envision the operator also taking care of certs and setting up the webhook configuration (as the caBundle needs to be set properly)?

**Comment by brancz** [comment]
@vsliouniaev that's exactly the reason for this statement:

> We've been thinking to add a validating webhook that validates the PromQL expressions. Biggest problem with this is cert setup is somewhat difficult so we've been discussing what we can do with the cert-manager people.

Within OpenShift we have a component that can already inject the CA into the `caBundle` field. I've spoken to the cert-manager folks before and they were not opposed to doing the same.

**Comment by vsliouniaev** [comment]
Are you suggesting doing the same thing as cert-manager or relying _on_ cert-manager to achieve the behaviour? There's some code in cert-manager that looks like it's covering the functionality of doing ca injection added a few weeks ago

**Comment by brancz** [comment]
I'm suggesting to recommend to use cert-manager to accomplish this, not replicate any functionality.

**Comment by vsliouniaev** [comment]
I'm doing some testing of this on our own clusters as a standalone component running a single instance and noticed that I can end up with a race condition if I'm deploying rules and a new version of my validation pod together where there's nothing available to validate the rules.

Wondering if you have any opinion on creating a component external to the operator itself so it could be run as multiple instances.

**Comment by brancz** [comment]
I don't see a problem creating the webhook as something that could be run individually (or in process). Ideally still part of this repo I'd say so we can be sure about compatibility.
