### ISSUE TITLE
Can't add ownerReferences to services with existing RBAC rules

### ISSUE THREAD

**Issue by abursavich** [coreos/prometheus-operator#2279]
**What did you do?**
Upgrade prometheus-operator from v0.25.0 to master, then attempt to update Prometheus.

**What did you expect to see?**
Prometheus updated.

**What did you see instead? Under which circumstances?**
Prometheus not updated and a lot of prometheus-operator error logs (see below).

It seems related to: [Set Owner References on Created Services #1946
](https://github.com/coreos/prometheus-operator/pull/1946)

Prometheus-operator was trying and failing to add ownerReferences to the prometheus-operated service, which didn't have ownerReferences before bumping prometheus-operator up from v0.25.0.

The issue went away after I gave the prometheus-operator ClusterRole permission to delete services, but I can't find anything in the documentation or examples that show prometheus-operator needing access to delete services.

**Environment**

* Prometheus Operator version:

git: 51d1e725b11ac8450e4ba1aae02740c7dbfb0e3f
image: 43bf9baaf51c2c2f5531e4d0818b787852de7cdf6589ee7685be1db72cdb095e 

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T04:08:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

OpenShift

* Manifests:

N/A

* Prometheus Operator Logs:

A lot of this, over and over:
```
E0110 06:49:49.310521       1 operator.go:867] Sync "monitoring/default" failed: synchronizing governing service failed: updating service object failed: services "prometheus-operated" is forbidden: cannot set an ownerRef on a resource you can't delete: no RBAC policy matched, <nil>
{"caller":"operator.go:967","component":"prometheusoperator","key":"monitoring/default","level":"info","msg":"sync prometheus","ts":"2019-01-10T06:49:49.327671645Z"}
```

**Comment by brancz** [comment]
Thanks for reporting! We will need to adapt the rbac roles for this to both add `services/finalizer` and `delete` on `services` for the prometheus-operator.
