### ISSUE TITLE
Feature: integrate Thanos Ruler

### ISSUE THREAD

**Issue by wleese** [coreos/prometheus-operator#2288]
When scaling up our environment, it seems that Thanos will provide a way to use a single endpoint to retrieve all metrics (be it coming from Prometheus instances or Thanos-store). This allows our (hundreds of) developers to use Grafana without thinking about where the metric lives. 
In the mean time the people responsible for maintaining Prometheus can scale to more instances (statefulsets using prometheus-operator) and do any kind of 'sharding' to ensure instances are not overloaded.

This transparency is currently not available for PrometheusRules - or rather, the alert variant. When someone creates an alert, it's associated with a prometheus instance (statefulset). Thanos Ruler seems to be a way to enable this. Would be great if prometheus-operator would support create thanos rules in the future.

https://github.com/improbable-eng/thanos/blob/master/docs/components/rule.md

> NOTE: The rule component is experimental since it has conceptual tradeoffs that might not be favorable for most use cases. It is recommended to keep deploying rules to the relevant Prometheus servers.
> 
> The rule component should in particular not be used to circumvent solving rule deployment properly at the configuration management level.

..although perhaps the above warning needs to be elaborated on first.

**Comment by brancz** [comment]
cc @metalmatze

**Comment by rafaeljesus** [comment]
Hi peeps, I just faced with this use case right now!

In our case, services are packaged and deployed as helm charts, on their side engineers can use `PrometheusRule` however it's limited to Prometheus, meaning rules relying on long term data from thanos won't work (just adding this here cos it might be helpful to someone not too familiar with this)

I don't see any other feasible way of using ruler without being a CRD too, is it your pipeline? We can perhaps collaborate, pls let me know, thx

**Comment by brancz** [comment]
Having the ruler consume PrometheusRule objects would indeed be very neat. We'll have to think about how to accomplish that.

**Comment by rafaeljesus** [comment]
nice!!

**Comment by metalmatze** [comment]
I was thinking about some labels that need to be much, but that's just from the top of my head. Need to have a quick conversation indeed.

**Comment by metalmatze** [comment]
I ran into this problem again and now for my own infrastructure.
I am not sure if this should be part of the Prometheus Operator, should it? Although we already add the Thanos sidecar, but that's somewhat related to Prometheus as a statefulset. 

My idea now was to create a controller reading PrometheusRule objects and based on labels put them into the Thanos Ruler. We could try using kubebuilder for that.

**Comment by brancz** [comment]
Do we really want a different controller for that? It seems that it's largely identical to current `PrometheusRule` management. I feel it would make sense to live here.

**Comment by metalmatze** [comment]
I don't have hard feelings about this and you're probably right, as using the PrometheusRule already requires the CRD to be installed. So adding this to our operator seems fine.

**Comment by ingvarm-gr** [comment]
A working (although not ideal) route to get configs to a thanos-ruler that we've played around with is to:
1) create a Prometheus object for your thanos-ruler, with a replica-count of 0 (this stops prometheus-operator from creating a StatefulSet)
2) Ensure you put the configmap-reloader as a sidecar on your thanos-ruler
3) Push one or more PrometheusRule(s) matching the rule selector in the object created in (1)

The down-side is that you will not be able to set the store failure policy in the rule group(s), since I don't think that's valid in the CRD, so in an ideal world, there would also be a ThanosRules CRD that caters for that setting.

**Comment by yeya24** [comment]
This is already done

**Comment by brancz** [comment]
Thanks for the reminder @yeya24

**Comment by BrewToR** [comment]
> This is already done

Hello, could you please tell me how ?
thanks !

**Comment by cyberpunk-admin** [comment]
> > This is already done
> 
> Hello, could you please tell me how ? thanks !

add thanos-ruler operator #2943
