### ISSUE TITLE
Why do I need to wait few minutes until namespace 'monitoring' is deleted?

### ISSUE THREAD

**Issue by Aracki** [coreos/prometheus-operator#2293]
I am deploying all monitoring objects with `kubectl apply -f manifests/`

I am using latest [manifests](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests) directory.

After the `kubectl delete -f manifests/` command, every kubernetes objects gets deleted in few seconds. After that, I need to wait few minutes until `monitoring` namespace object get deleted. 

What is cause of this behavior?

**Comment by brancz** [comment]
I believe what's happening is that kubectl actually waits for the namespace to be deleted, which would include waiting for each object within the namespace to be deleted. I only recently noticed this as well though, so my guess is that this was a relatively recent change. But I'm not 100% sure either what's happening. I'd recommend asking for advice on the `#sig-cli` channel on Kubernetes slack (feel free to ping me when you ask, I'm also @brancz on Kubernetes slack).
