### ISSUE TITLE
sum(container_memory_usage_bytes{...}) rule doubles values

### ISSUE THREAD

**Issue by rrichardson** [coreos/prometheus-operator#2302]
**What did you do?**;
Installed Prometheus chart and friends via Helm in a K8s cluster created by Kubeadm 1.11

**What did you expect to see?** 
Correct values aggregated by the rules: 
```

record: pod_name:container_memory_usage_bytes:sum expr: sum   by(pod_name) (container_memory_usage_bytes{container_name!="POD",pod_name!=""}) | OK |   | 16.737s ago | 17.95ms
-- | -- | -- | -- | --
record: pod_name:container_spec_cpu_shares:sum expr: sum   by(pod_name) (container_spec_cpu_shares{container_name!="POD",pod_name!=""}) | OK |   | 16.719s ago | 14.89ms
record: pod_name:container_cpu_usage:sum expr: sum   by(pod_name) (rate(container_cpu_usage_seconds_total{container_name!="POD",pod_name!=""}[5m])) | OK |   | 16.704s ago | 19.75ms
record: pod_name:container_fs_usage_bytes:sum expr: sum   by(pod_name) (container_fs_usage_bytes{container_name!="POD",pod_name!=""})
```

If the rules were changed to just use the output from Kubelet, a `sum()` would not be necessary. This would require setting `{service="kubelet", container_name!=""}`

**What did you see instead? Under which circumstances?** : In addition to NodeExporter(I think?) exporting data under these record names,  kubelet also reports data under these record names, albeit with different labels.  Kublet reports the exact sum of all containers in the Pod.. so the above rules report a value that is exactly double the actual value. 

**Environment**

* Prometheus Operator version:

    Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:faa9f8a9045092b9fe311016eb3888e2c2c824eb2b4029400f188a765b97648a

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	kubeadm on bare metal

* Manifests:

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml#L22

* Prometheus Operator Logs:

not relevant

**Comment by metalmatze** [comment]
Sorry that I have to redirect you, but this should be discussed in the upstream repository at https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by rrichardson** [comment]
No problem. Thanks!
