### ISSUE TITLE
how to get kube-controller-manager and kube-scheduler metrics when runs it as service in host server

### ISSUE THREAD

**Issue by lw8008** [coreos/prometheus-operator#2306]
**What did you do?**
I hope to add kube-controller-manager and kube-scheduler in Prometheus-operator
I read  https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html
but it seems only works when we run kube-controller-manager and kube-scheduler in container/pod rather than as linux service in the master node.

**What did you expect to see?**
Could you pls guide me if there is a way to fulfill it?

* Prometheus Operator version:

v2.2.1

* Kubernetes version information:

1.11.2

**Comment by brancz** [comment]
Yes all our examples assume they are pods (as almost all install methods, including kubeadm, do this). You can use the `additionalScrapeConfigs` feature to discover them with any normal Prometheus service discovery method, all you need to do is make sure the `job` labels are `kube-controller-manager` and `kube-scheduler` respectively.

**Comment by lw8008** [comment]
Thanks @brancz it works like a charm.
I will close it.

**Comment by brancz** [comment]
Glad it worked out :)

**Comment by Sallyan** [comment]
Hi @lw8008 How do you make it work?
I am facing the same issue. kube-controller-manager and kube-scheduler are running as service without pod. Currently the targets are shown in Prometheus with error connection refused. 
Could you kindly share some information how did you do?
Thanks!
Sally

**Comment by Sallyan** [comment]
Hi @brancz 
i searched out and find one issue related to this https://bugzilla.redhat.com/show_bug.cgi?id=1698201
it mentioned controller manager moved to secure port 10257. 
Currently on my cluster, describe service controller manager and kube-scheduler, they are listening on port 10252 and 10251
 Get http://*.*.*.*:10251/metrics: dial tcp *.*.*.*:10251: connect: connection refused

**Comment by ouyangluwei** [comment]
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
subsets:
  -
    addresses:
      - ip: x.x.x.x
      - ip: x.x.x.x
      - ip: x.x.x.x
    ports:
      - name: http-metrics
        port: 10252
        protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP


/opt/kube/bin/kube-controller-manager --address=0.0.0.0

**Comment by TomHutter** [comment]
changing service to port 10257:

~~~
kubectl -n kube-system edit svc prometheus-kube-prometheus-kube-controller-manager 
~~~

~~~
...
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
    targetPort: 10257
...
~~~

and changing service monitor for controller-manager:

~~~
kubectl -n prometheus edit servicemonitors prometheus-kube-prometheus-kube-controller-manager
~~~

~~~
...
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      serverName: localhost
...
~~~

worked for me.
