### ISSUE TITLE
Not able to deploy in Secure Environment without internet access 

### ISSUE THREAD

**Issue by anton-pydev** [coreos/prometheus-operator#232]
**What did you do?**
I am trying to deploy  prometheus in a close environment with no internet access available .
The setup looks as following : 
- I have a K8s cluster in a closed ( Telco-Grade) environment .
  No internet access is available .
  I am allowed to download images and to upload them to local Nexus repo . 
  While I am able to replace image URLs to Nexus internal URLs in  most of the manifests in kube-prometheus , 
  URL of prometheus itself is hard-coded in prometheus operator . 

What is the best approach you suggest to solve this ?

Thanks in advance.

**Comment by mxinden** [comment]
There is the [configuration option](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) `baseImage` in the Prometheus third-party-resource. It defaults to the quay.io Prometheus URL. You can specify your Nexus repo image URL instead.

Let us know if this works for you.

**Comment by brancz** [comment]
The requirement is that all "versions" are tagged the same as on the public quay image, or at least, that the version you use are available tags.

**Comment by brancz** [comment]
Closing here for now as what you are asking for is already possible, if we misunderstood feel free to reopen and comment :slightly_smiling_face:

**Comment by liamawhite** [comment]
@brancz is there a reason why the tag isn't configurable? Our internal naming follows different conventions so would require some snowflake behaviour.

**Comment by brancz** [comment]
Techincally the Tag just has to contain the same image and the tag itself needs to be parsable by the semver parser we use, as we configure Prometheus based on the version.

**Comment by liamawhite** [comment]
so you could do something like:
```
version: v2.0.0
baseImage: registry.bluemix.net/registry-deploy/prometheus
```
but not...
```
version: 2
baseImage: registry.bluemix.net/registry-deploy/prometheus
```
or
```
baseImage: registry.bluemix.net/registry-deploy/prometheus:2
```

**Comment by brancz** [comment]
@liamawhite that is correct. As otherwise we don't know the version of the image we're running. We're expecting this to be equivalent, as that is the practice taken within the Prometheus project.

**Comment by liamawhite** [comment]
ok, so it will be the same for alert manager and service monitor?

**Comment by brancz** [comment]
Alertmanger behaves the same way, yes. ServiceMonitor does not have any associated image.

**Comment by liamawhite** [comment]
ok, thanks for the help!

**Comment by brancz** [comment]
Feel free to add details/new things to the docs, so in the future people have it easier to discover this type of information :slightly_smiling_face: .
