### ISSUE TITLE
[Exporter-node charts] version and configuration upgrade?

### ISSUE THREAD

**Issue by kaarolch** [coreos/prometheus-operator#2324]
Hi, 
are you planning to upgrade node-exporter image in `exporter-node` chart to version 0.17.x? I see that in example for `kube-promtheus` there is descriptor for new version of node-exporter [prometheus-operator/contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml](https://github.com/coreos/prometheus-operator/blob/acab714bfb366d216b64e68ff184d19be6d0ec91/contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml)
If no one is working on upgrade exporter-node charts I can propose some PR to support new version.

**Comment by richerve** [comment]
@kaarolch The prometheus-operator Chart is now maintained on https://github.com/helm/charts/tree/master/stable/prometheus-operator. AFAIK the version in the prometheus-operator repo is unmaintained

**Comment by kaarolch** [comment]
@richerve Hmm, Currently operator use some part that are also defined in kube-prometheus, could you explain me what are the plan for kube-prometheus?

**Comment by kaarolch** [comment]
Rodger that, thx.
