### ISSUE TITLE
Operator fails to update managed statefulset with 'updates to statefulset spec for fields other than 'replicas' are forbidden.

### ISSUE THREAD

**Issue by euank** [coreos/prometheus-operator#233]
**What did you do?**

Updated the operator and expected it to upgrade and manage statefulsets it created in the past.

**What did you see instead? Under which circumstances?**

It spat out the errors below instead.

The relevant bit of upstream Kubernetes code is: https://github.com/kubernetes/kubernetes/blob/v1.5.5/pkg/apis/apps/validation/validation.go#L113-L115

I added some more debug logging to prometheus, and I think the update that is causing it to break is the one introduced in https://github.com/coreos/prometheus-operator/commit/a024d4b0b7288514818ce646584e2daca85fb4cb

Because of that, the 'Update' is attempting to change the args of the container, and so the update is just constantly rejected.

I think it might be necessary to create and scale-up a new statefulset and then scale-down and delete the old one for updates like that.

And we should maybe tell Kubernetes that restricting updates like that was a little short-sighted perhaps.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4+coreos.0", GitCommit:"97c11b097b1a2b194f1eddca8ce5468fcc83331c", GitTreeState:"clean", BuildDate:"2017-03-08T23:54:21Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Artisanal hand-crafted kubernetes on bare-metal.

* Manifests:

* Prometheus Operator Logs:

```
ts=2017-03-26T06:08:36Z caller=operator.go:570 component=prometheusoperator msg="sync prometheus" key=default/wob-prom
E0326 06:08:37.256310       1 operator.go:481] Sync "default/wob-prom" failed: updating statefulset failed: StatefulSet.apps "prometheus-wob-prom" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.
```

**Comment by brancz** [comment]
Yes we mentioned this in the [release notes](https://github.com/coreos/prometheus-operator/releases/tag/v0.7.0):

> This release introduces breaking changes to the generated StatefulSet's
PodTemplate, which cannot be modified for StatefulSets. The Prometheus and
Alertmanager objects have to be deleted and recreated for the StatefulSets to
be created properly.

My suggestion number one is to have Persistent Volumes, that way even when there are disruptive changes like these at least the Prometheus data is kept through deployments. Then for an upgrade like this it is easiest to set the `Paused` field in the Prometheus resource to true, that way the Prometheus Operator does not reconcile the underlying StatefulSet anymore. Then the StatefulSet can be removed, and `Paused` can be set to false and the Prometheus Operator will recreate the StatefulSet correctly.

**Comment by brancz** [comment]
I'll close this for now. Do you think we should document this more or is this enough?

**Comment by euank** [comment]
@brancz My bigger gripe is that the dream of an operator I was sold on was that I would not have to ever do this sort of manual migration. That the operator would be smart enough to just do whatever was best.

I do have persistent storage, so I did nuke the statefulsets and let it recreate them just fine. I don't see why the operator couldn't have done that for me though.

**Comment by brancz** [comment]
This is indeed something we are solving with Tectonic. However, while what you are saying is certainly possible, as long as we have explicitly not stabilized the format of the TPR and thus the generated StatefulSets we won't be performing migrations of this kind.
