### ISSUE TITLE
PrometheusRule doesn't support dry-run

### ISSUE THREAD

**Issue by pgporada** [coreos/prometheus-operator#2343]
**What did you do?**
```
kubectl edit PrometheusRule/prometheus-operator -n monitoring
:w! phil-test.yaml
kubectl diff -f phil-test.yaml -n monitoring
error: monitoring.coreos.com/v1, Kind=PrometheusRule doesn't support dry-run
```

**What did you expect to see?**
A proper diff rather than an error.

**What did you see instead? Under which circumstances?**
I saw the error above. I was intending to creating a patch to be applied with `kubectl patch`, but I am a k8s noob and am not sure if that would even work. This was detected while trying to troubleshoot https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/144

**Environment**

* Prometheus Operator version:

	The helm chart which I know isn't supported here, however this project created the CRD.

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	`Amazon EKS`

**Comment by pgporada** [comment]
I saw `monitoring.coreos.com/v1` and assumed it was something this project needed to implement support for. I am probably wrong.

**Comment by metalmatze** [comment]
In the "What's next" it says that for `kubectl diff` to work on CRDs (Custom Resource Definitions) it needs server-side apply: https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/

So for now kubectl doesn't seem to support diffing any of the Prometheus Operator objects. Once kubectl supports this, it should "just" work without us doing anything.

**Comment by pgporada** [comment]
Thanks!
