### ISSUE TITLE
rbac: make rbac default

### ISSUE THREAD

**Issue by philips** [coreos/prometheus-operator#235]
With Kubernetes v1.6 RBAC will be on by default. We should start telling people how to use that directly from the readme instead of just recommending `kubectl create -f deployment.yaml`.

**Comment by brancz** [comment]
Do you think we should be using an admin ClusterRole/ServiceAccount for ease of getting started and direct people to the RBAC documentation for more detailed roles, or provide a bundle with the exact roles?

**Comment by philips** [comment]
seems like we should ship with the exact roles. Is there a downside to doing that?

**Comment by brancz** [comment]
Just the mental overhead of RBAC rules being necessary, but I guess since it's now default everyone will rather expect them sooner or later. I'll add a bundle in the root of the repo similar to the current `deployment.yaml` that includes them.
