### ISSUE TITLE
Backup and restore Prometheus data

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2355]
**What did you do?**
I have configured persistant storage for my Prometheus. The mounted path is /prometheus. I can see the data stored in this location. But I failed to see data in grafana,when I  copy the data from here and tried to restore it on another prometheus pod(completely another prometheus setup)
**What did you expect to see?**
I want to take the data stored in /prometheus and need to restore to another prometheus.
**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by metalmatze** [comment]
I'm not sure why this doesn't work. This is pretty much what all container orchestrated Prometheuses do when they get rescheduled. They continue with the previous Prometheus data.
Can you paste the logs of the Prometheus that should take over?

**Comment by brancz** [comment]
You need to make sure to actually query at the time where there is data. If you're comfortable with sharing it, we are also happy to take a look at your backup.

**Comment by manuprometheus** [comment]
Thank you @metalmatze @brancz  for your inputs in this. Let me check the case again.

**Comment by manuprometheus** [comment]
Can anyone tell me how the data is stored in the Volume. In my Prometheus data, I can see the data is saved for the following date. 
Dec  9,Dec 15,Dec 22
How the data storing works?

**Comment by brancz** [comment]
We would need a full snapshot of the volume. Just copy and tar all the “data/“ dir.

**Comment by manuprometheus** [comment]
Yes, I got it. Thank you @brancz. I tried wrong time range. I can backup and restore now.

**Comment by mohanagandlla** [comment]
Hi, May I know how do you take the back up by a time range? because I am getting the full backup whenever I give API command 
i followed this command curl -XPOST http://<prometheus_IP>:<Port>/api/v1/admin/tsdb/snapshot
