### ISSUE TITLE
Unable to provide GCS Credentials for Thanos in 0.28.0

### ISSUE THREAD

**Issue by thomasriley** [coreos/prometheus-operator#2360]
**What did you do?**
Attempt to upgrade Prometheus Operator to 0.28.0

**What did you expect to see?**
Thanos Sidecar should authenticate and work with Google Cloud Storage

**What did you see instead? Under which circumstances?**
Operator release 0.28.0 adds support for arbitrary object storage configuration in Thanos 0.2.1 which works as expected. However, credentials for GCS are supplied to Thanos via environment variable as per the Thanos documentation however the Operator does not provision for this. Previously this worked as the Operator used to handle the GCS credentials as part of ThanosGCSSpec.

**Environment**

* Prometheus Operator version:

	v0.28.0

**Comment by thomasriley** [comment]
This is related to #2358 although with GCS the credentials can't be specified via the new Thanos config file so is not just a 'would be nice to have'.

**Comment by bwplotka** [comment]
>  can't be specified via the new Thanos config file so is not just a 'would be nice to have'.

True, but it was not possible beforehand as well. There was only `gcs.bucket` flag and required envvar to specify.

As passing custom envvars would be nice from operator perspective, adding support for this in Thanos config (in gcs config specify credentials filepath) would fix this issue as well.

**Comment by thomasriley** [comment]
> 
> True, but it was not possible beforehand as well. There was only `gcs.bucket` flag and required envvar to specify.
> 

In the last version of the operator, the credential file was specified in `ThanosGCSSpec` however this release removes that functionality with no alternative. 

I agree from a Thanos point of view, nothing has changed in terms of how GCS should be configured between either Thanos 0.1.0 and 0.2.x.

**Comment by thomasriley** [comment]
I did not word that very well at all. I should have said, nothing has changed in Thanos in how GCS is _authenticated_ between 0.1.0 & 0.2.x.

> I think the easy fix would be to add a SecretKeySelector field to mount the GOOGLE_APPLICATION_CREDENTIALS file.

This would be great! In fact, you might find it worth having the same approach for configuring AWS credentials too instead of relying upon the Thanos configuration file to help satisfy #2358 too.

**Comment by obiesmans** [comment]
How probable to merge would be a PR that implements this ?

**Comment by thomasriley** [comment]
@metalmatze would you be able to help out on this one please? We currently can't upgrade Prometheus Operator in our clusters since we can no longer configure GCS for the Thanos sidecar.

**Comment by dmyerscough** [comment]
You can define the service account in the Thanos configuration:-

```yaml
type: GCS
config:
  bucket: dev-XXXXX-XXXX-us-dev-thanos
  service_account: '{  "type": "service_account",  ........... }'
```
