### ISSUE TITLE
Codebase for addon-resizer have changed parameter --threshold

### ISSUE THREAD

**Issue by carlosedp** [coreos/prometheus-operator#2366]
The addon-resizer code has changed the parameter --threshold to --acceptance-offset since 2017. I've opened an issue on the project since their documentation is also wrong. 

The jsonnet files for the Prometheus-operator still uses the old parameter (and I believe a previous version of addon-resizer container). 

Just a heads-up in case the project updates this container.

Ref. https://github.com/kubernetes/autoscaler/issues/1645

**Comment by brancz** [comment]
In our setup we remove the addon resizer, so we don't notice this. Could you update the addon-resizer and change the relevant things in the jsonnet files? Thanks! :slightly_smiling_face:

**Comment by carlosedp** [comment]
Fixed with #2380
