### ISSUE TITLE
Override readiness/liveness values for prometheus

### ISSUE THREAD

**Issue by Zero-2** [coreos/prometheus-operator#2367]
**What did you do?**
Change Readiness/Liveness config for prometheus

**What did you expect to see?**
Define values override readiness/liveness into values.yaml file.

**What did you see instead? Under which circumstances?**
No values are available and prometheus use default values for both config.

**Comment by brancz** [comment]
If you could do some experiments and let us know how long of a timeout you would actually need that would help us a lot. Also the helm charts in this repo are no longer maintained, please report things about the helm chart to the upstream helm charts repo.

**Comment by Zero-2** [comment]
Sorry for the delay.
What's the current mantained chart repo?

**Comment by brancz** [comment]
The upstream stable charts helm/charts.
