### ISSUE TITLE
promethus-operator pod consistently exceeding 200Mi memory limit

### ISSUE THREAD

**Issue by chrisob** [coreos/prometheus-operator#2372]
**What did you do?**
Deploy Prometheus Operator using the official Helm charts, including the recommended resource request/limits for the prometheus-operator deployment:
```yaml
# override-values.yaml
prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
```

**What did you expect to see?**
Prometheus Operator (prom op) pods don't exceed 200Mi of memory, and thus don't get OOMKilled.

**What did you see instead? Under which circumstances?**
prom op pods are OOMKilled due to exceeding memory limits over and over until a CrashLoopBackoff.

**Environment**

* Prometheus Operator version:
      v0.25.0

* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
      Cluster deployed using `kubeadm`.

* Manifests:
      If needed, I can supply the entire output of `helm template`, but AFAIK only the resource limits are relevant...

* Prometheus Operator Logs:
This is all prom op is able to log before getting OOMKilled. It seems to always happen right after the cache sync init step:
```
ts=2019-02-04T16:00:51.194629125Z caller=main.go:165 msg="Starting Prometheus Operator version '0.25.0'."
level=info ts=2019-02-04T16:00:51.301535654Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.11.5
level=info ts=2019-02-04T16:00:51.30199202Z caller=operator.go:371 component=prometheusoperator msg="connection established" cluster-version=v1.11.5
level=info ts=2019-02-04T16:00:51.782901968Z caller=operator.go:627 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-02-04T16:00:51.785798441Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-02-04T16:00:51.882077317Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-02-04T16:00:51.89419149Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-02-04T16:00:54.786198053Z caller=operator.go:225 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-02-04T16:00:54.986717522Z caller=operator.go:180 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-02-04T16:00:54.986936335Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=cluster-monitoring/prometheus-operator-alertmanager
level=info ts=2019-02-04T16:01:00.915679299Z caller=operator.go:387 component=prometheusoperator msg="CRD API endpoints ready"
```

**Other info**
If I bump the memory limit higher, the prom op pod is able to finish initializing and caps out at around 360Mi memory usage: 
![screenshot from 2019-02-04 17-06-29](https://user-images.githubusercontent.com/12276488/52220478-45f36180-289f-11e9-8269-3846c2c0abac.png)

So I guess my _real_ question is, **is it expected that Prometheus Operator pods take more than 200Mi of memory?**  The cluster I'm having this issue on has only been running for ~1 month, and I have 3 other clusters where Prometheus Operator is deployed the same exact way that have been running for much longer and don't have this issue :thinking:

**Comment by chrisob** [comment]
Also worth mentioning, after ~7 minutes of running the prom op pod drops back down below 200Mi of memory:
![screenshot from 2019-02-04 17-13-55](https://user-images.githubusercontent.com/12276488/52220956-5bb55680-28a0-11e9-8b9d-59d799819a8a.png)

**Comment by brancz** [comment]
Depending on how you are running the Prometheus Operator it may need that amount, as it watches all Prometheus, ServiceMonitor, PrometheusRule, ConfigMap, Secret, StatefulSet, and Namespace objects configured, which may need some amount of memory depending on the size of your environment. That said the drop looks a little odd. Could you take a pprof memory profile and share it with us, then we could analyze the situation. (also it would be useful to graph the `go_memstats_heap_inuse_bytes{job="promteheus-operator"}` metric as that shows the actual usage by the process without garbage, as this drop might just be garbage collection happening)

**Comment by metalmatze** [comment]
Any updates on this @chrisob?

**Comment by chrisob** [comment]
@metalmatze Admittedly, since I bumped the memory resource limit, prom operator hasn't been getting OOM killed, so I haven't yet read up on how to take a memory profile as per @brancz's suggestion... 

I'm hoping to do this next week. As for sending the profile, what's the preferred way to send it to you guys?

**Comment by brancz** [comment]
You should be able to just upload the profile as an attachment on a github comment :slightly_smiling_face: . That's what people usually do on Prometheus.

**Comment by chrisob** [comment]
@brancz Apologies for the delay, I didn't realize you had already baked pprof into prom operator, and I thought I was going to have to recompile!

Anyways, attached is a profile taken with `go tool pprof -inuse_space -pdf -symbolize=remote http://localhost:8080/debug/pprof/heap`, let me know if there's some other format/params which has more useful info, as I'm not so familiar with go profiling.
[profile006.pdf](https://github.com/coreos/prometheus-operator/files/2879429/profile006.pdf)

And here is the `go_memstats_heap_inuse_bytes` metric of prom operator graphed:
![image](https://user-images.githubusercontent.com/12276488/53006533-abb22280-3435-11e9-96a4-54ccf5c85452.png)

Aaaand the "stock" Grafana memory graph (which now exceeds 700MB):
![image](https://user-images.githubusercontent.com/12276488/53006812-41e64880-3436-11e9-9001-cbbd42bb0c3f.png)

So, I guess this is something to do with go's GC?

**Comment by chrisob** [comment]
FWIW, the total size of all of the resources in this cluster that prom operator watches (you mentioned Prometheus, ServiceMonitor, PrometheusRule, ConfigMap, Secret, StatefulSet, and Namespace objects) is **155 MB**.

**Comment by brancz** [comment]
Agreed with @chrisob part of the problem seems to simply be the amount of objects in your cluster. The difference between the 700Mb and 200Mb is cached memory. The in use memory metric already includes non-gc'd memory.

**Comment by chrisob** [comment]
@brancz Thanks for the point in the right direction, I think the "correct" fix for me is to reduce the number of revisions that Helm stores in configmaps, as other pods that also read all CMs are also hitting their memory limits... :man_facepalming:
