### ISSUE TITLE
Monitor kubernetes pod resources

### ISSUE THREAD

**Issue by kishor-git** [coreos/prometheus-operator#2375]
**What did you do?**
Installed Openshfit container platform 3.11. Assessing prometheus-operator to scrape application metrics. We see ServiceMonitor resource can scrape from service. But we are looking for scraping from a pod resource.
**What did you expect to see?**
Like in prometheus, one can define scrape target on any kubernetes resource like pod by giving few  annotations, so that prometheus discovers these targets.
eg: 	prometheus.io/path: /metrics
	prometheus.io/port: "4002"
	prometheus.io/scrape: "true"
**What did you see instead? Under which circumstances?**
No way to scrape from pod resources
**Environment**
Openshfit container platform 3.11
* Prometheus Operator version:
ose-prometheus-operator:v3.11.69
* Kubernetes version information:
1.11+

**Comment by brancz** [comment]
If you are a Red Hat customer, please go through the normal bug report process via bugzilla. The ServiceMonitor indeed does scrape metrics from pods, just uses `Service` objects as a mechanism of grouping pods. It makes use of the very same Prometheus endpoints discovery you are referring to, just not via the annotations as that has a number of problems.

**Comment by kishor-git** [comment]
@brancz Thanks for the reply. Yes it is working as expected. We could see pods as well discovered by Prometheus using ServiceMonitor approach.
