### ISSUE TITLE
How can I define "evaluation_interval" in the Prometheus operator?

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2378]
**What did you do?**
I need to increase the evaluation_interval. Currently it is 30s.
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
The Prometheus object has the “evaluationInterval” field. See the API docs: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

**Comment by manuprometheus** [comment]
Thank you @brancz

**Comment by brancz** [comment]
@manuprometheus the `scrapeTimeout` field is part of the `Endpoint` struct within the ServiceMonitor. Please check the API docs next time first :slightly_smiling_face: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint

**Comment by manuprometheus** [comment]
@brancz  Thank you so much. Sure I will study the docs first. Thank you for your help. :)
