### ISSUE TITLE
Plans regarding jsonnet / ksonnet

### ISSUE THREAD

**Issue by nrobert13** [coreos/prometheus-operator#2385]
**What did you do?**
wondering
**What did you expect to see?**
nothing
**What did you see instead? Under which circumstances?**
The team behind ksonnet is stepping back from the project. As a result, work on ksonnet will end and the GitHub repositories will be archived. You can read more about our decision here.
[source](https://github.com/ksonnet/ksonnet)
**Question**
Are there any plans yet how to go further with the jsonnet stuff?

**Comment by metalmatze** [comment]
The community (including us) is currently looking into a way forward.
We'll keep you we posted!

Don't worry too much about it.

**Comment by jfuechsl** [comment]
@metalmatze Are there any updates at this moment?

**Comment by metalmatze** [comment]
A week ago a few people, the original authors and others that have heavily invested into jsonnet and ksonnet, have met to discuss the future plans of ksonnet.

Without any hesitation it was agreed to keep the best parts of ksonnet and move forward with them.
That includes ksonnet-lib, the autogenerated (from Kubernetes' OpenAPI spec) jsonnet library which we use in kube-prometheus and other projects.

Not only are the original authors of ksonnet going to help to get ksonnet into a bright future, but also a few others including people from Grafana and Red Hat. Whether the label/name of this project will continue to stay in its current form has yet to be decided, but there are enough parties involved and willing to make this work, that you don't have to worry :slightly_smiling_face: 

We have no plans to move away from jsonnet and ksonnet with kube-prometheus and keep pushing forward!

**Comment by jfuechsl** [comment]
Thanks, that's amazing news!
