### ISSUE TITLE
Add users in Grafana via Custom Value.yaml

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2386]
**What did you do?**
I want to add a user which can have only read access in Grafana through values.yaml in helm chart.

We can set adminUser and adminPassword but I want to add another user which have only read access via custom value.yaml. So if I re-install the prometheus-operator using helm, I don't have to add manually.

Is there any way possible?

**Comment by brancz** [comment]
First off, the helm charts in this repo are not maintained anymore. They have been migrated to the upstream stable charts.

Apart from that, yes you can configure Grafana so that users can have read only access, that's how we setup Grafana.

**Comment by metalmatze** [comment]
I will close this. Please follow up with the new chart for more questions.

**Comment by ArjonBu** [comment]
Did you find the solution? I can't seem to find a way to create users when Grafana is running stateless.
