### ISSUE TITLE
Feature Request: Add support for kustomize remote-base

### ISSUE THREAD

**Issue by chrisghill** [coreos/prometheus-operator#2391]
**What did you do?**
N/A

**What did you expect to see?**
N/A

**What did you see instead? Under which circumstances?**
N/A

**Environment**
N/A

I just wanted to submit a feature request to add a kustomization.yaml file to your kube-prometheus [manifests](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests) directory.  This would allow Kustomize users to use a [remote-base](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) and just maintain their overlays locally.  Then updating would be as simple as changing the ref version in the overlay file instead of downloading, extraction and moving files into a local base directory.

If you understandably don't want the kustomization.yaml file in the manifest dir, you could also just have a kustomize directory in [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) that has nothing but the kustomization.yaml file, which points to all the manifest files.

**Comment by brancz** [comment]
cc @ant31 I think you wanted to look into this

**Comment by coryodaniel** [comment]
@chrisghill give that a swing ^
