### ISSUE TITLE
Documentation is outdated for ServiceMonitor

### ISSUE THREAD

**Issue by kamilgregorczyk** [coreos/prometheus-operator#2394]
**What did you do?**
I'm trying to register my service in prometheus without modyfing it's config file. I uninstalled prometheus (installed by helm) and I installed prometheus-operator from helm, did steps from this tutorial https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html starting from ServiceMonitor part  and I couldn't see any registered targets. Then I uninstalled helm operator and followed the same guide from top to bottom and I still cannot see any targets.

**What did you expect to see?**
Service in targets/ endpoint

**What did you see instead? Under which circumstances?**
Nothing

**Environment**
MacOS + minikube

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

minikube

**Comment by aditya-konarde** [comment]
@kamilgregorczyk Hello, 

The documentation looks correct to me, could you please note what part you think is incorrect? 

Also, this guide may help with some troubleshooting: https://github.com/coreos/prometheus-operator/blob/master/Documentation/troubleshooting.md

If you can add snips from the ServiceMonitor, Service, and deployment here, that would help debug the issue.

**Comment by kamilgregorczyk** [comment]
The thing is that I create a new minikube instance, copied all the config files and I couldn't see service monitor in /targets so I don't really know which part is broken :)

**Comment by metalmatze** [comment]
All documentation on https://coreos.com/operators/prometheus/docs/latest/ is completely outdated and deprecated. You should not use it anymore. Please refer to the documentation inside this repository which should be up to date.
Additionally, the helm chart in this repository is deprecated too and move upstream to the official helm chart repository.
