### ISSUE TITLE
Clarify the relationship between components

### ISSUE THREAD

**Issue by itaysk** [coreos/prometheus-operator#2395]
This is a question/documentation ask.

Can someone please clarify the relationship between prometheus-operator, kube-prometheus and kubernetes-mixin? Do they container each-other (and in what order)? What's their relation to the prometheus helm charts.

If Kube-prometheus is a collection of configurations meant to make prometheus useful out of the box, why it also includes the operator (is it meant to be used to install the operator or the other way)? 
installing just the "operator" helm chart gave me a pretty good start including grafana dashboards, was that including kube-prometheus? why doesn't kube-prometheus have a helm chart in stable and the operator does?

**Comment by aditya-konarde** [comment]
Kubernetes-mixins is a set of [mixins](https://grafana.com/blog/2018/09/13/everything-you-need-to-know-about-monitoring-mixins/)

prometheus-operator is a Kubernetes operator, which manages the lifecycle of `Prometheus` and related resources. The spec can be found [here](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md)

Kube-prometheus is a bundle, consisting of an opinionated, all-in-one way of deploying kubernetes-mixins and prometheus-operator together, to help you get started quickly with monitoring Kubernetes with prometheus. 

If you look at the [README](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) for kube-prometheus, it states that:
```
Many of the useful dashboards and alerts come from the kubernetes-mixin project, similar to this project it provides composable jsonnet as a library for users to customize to their needs.
```
You may use the prometheus operator by itself, the add-ons that kube-prometheus provides are listed in the "Components included in this package:" section of the readme

Does that help clarify things?

**Comment by itaysk** [comment]
Thanks for your answer, I'm afraid it's still unclear.
does prometheus operator includes either kubernetes-mixins or kube-prometheus?
if not, how to explain that I installed the prometheus-operator helm chart and got grafana, with dashboards, and alerts preconfigured? maybe it's just the name of the chart that confused me.

What's the best way quickstart with things (using helm)? based on your answer i'd guess it's kube-prometheus, but there's no such chart in stable.

**Comment by brancz** [comment]
We are not the maintainers of the helm chart, and unfortunately that chart is incorrectly named, it should be named kube-prometheus, as that includes the entire stack (prometheus-operator, kubernetes-mixin, various configurations and objects to make up the entire monitoring stack).

Maybe you could raise this issue on the upstream stable charts repo and I can confirm the incorrect naming on there to communicate this to the rest of the community.

**Comment by itaysk** [comment]
@brancz thanks, the confusion was indeed with naming... I expected kube-prometheus to have a helm chart under the same name and expected the operator chart to be just the operator. 
@vsliouniaev thanks for adding the clarification in the operator readme https://github.com/helm/charts/pull/11501/files#diff-ae0db05747f536183816893bcaf18efb
