### ISSUE TITLE
Prometheus service/pod port name, change to "http"

### ISSUE THREAD

**Issue by erezzarum** [coreos/prometheus-operator#2401]
It is not possible at the moment to modify the port name that the Operator is creating, for example by default (hard coded) it is set to "web" on port 9090, this cause some conflicts if one is trying to use Istio as a service mesh.
Best practice is to use  port names starting with "http-" such as "http-prometheus" to avoid conflicts.

**Comment by metalmatze** [comment]
Personally I don't have any hard feelings about sticking with `web` as port name. We just need to make sure to properly make it configurable through the whole stack, from jsonnet into the Operator code itself.
If that is worth the effort to not conflict with Istio, I would say go for it.

**Comment by erezzarum** [comment]
@metalmatze Yes, that will be super, i was thinking it was configurable as i used the Helm chart, but i went and looked into the jsonnet and couldn't find it there as well, so then i looked into the code and saw it was hard coded.

Thanks!

**Comment by brancz** [comment]
Having it configurable sounds good to me. We should not change the default though.

**Comment by erezzarum** [comment]
@brancz Yes, there is no need to change defaults, it could break existing setups that rely on it.

**Comment by brancz** [comment]
Exactly my thought.
