### ISSUE TITLE
PrometheusRules not found/populated

### ISSUE THREAD

**Issue by muhlba91** [coreos/prometheus-operator#2405]
**What did you do?**

I have installed a plain k8s cluster using kubeadm and the helm chart in `https://github.com/coreos/prometheus-operator/tree/master/helm`. (I have also tried the charts in `https://github.com/helm/charts/tree/master/stable/prometheus-operator`.)

**What did you expect to see?**

A working Prometheus installation showing all metrics in Grafana.

**What did you see instead? Under which circumstances?**

Half of the metrics are N/A because Prometheus doesn't have any rules. The rules directory `/etc/prometheus/rules/prometheus-prometheus-rulefiles-0/` is empty.

**Environment**

* Prometheus Operator version:

	v0.28.0 (as well as 0.27.0)

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean",  BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"} 
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean",  BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm

* Prometheus Operator Logs:

```
level=debug ts=2019-02-14T09:14:02.517769619Z caller=rules.go:152 component=prometheusoperator msg="selected RuleNamespaces" namespaces=kube-system,me tallb,cert-manager,ingress-nginx,kube-public,operator,prometheus,grafana,default,exporter-node,kube-state-metrics-exporter namespace=prometheus promet heus=prometheus
level=debug ts=2019-02-14T09:14:02.51780607Z caller=rules.go:194 component=prometheusoperator msg="selected Rules" rules= namespace=prometheus prometh eus=prometheus
level=debug ts=2019-02-14T09:14:02.521917762Z caller=rules.go:69 component=prometheusoperator msg="no PrometheusRule changes" namespace=prometheus pro metheus=prometheus
```

**Comment by metalmatze** [comment]
The helm chart in this repository is deprecated.
You should try the newer one you have also tried (as written above) and check with the maintainers of that chart if it still doesn't work.
