### ISSUE TITLE
`KubeMemOvercommit` alert wrong?

### ISSUE THREAD

**Issue by eyalzek** [coreos/prometheus-operator#2406]
`KubeMemOvercommit` started firing recently so I took a look at the expression defined here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml#L573=L588

```
sum(namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)
          /
        sum(node_memory_MemTotal_bytes)
          >
        (count(node:node_num_cpu:sum)-1)
          /
        count(node:node_num_cpu:sum)
```

it's checking how much memory is used on all nodes from what's available and then compares this value to the total CPUs -1 / total CPUs ? Why is a comparison to the CPUs a factor in alerting of over committing memory? Am I reading this wrong/missing something?

**Comment by metalmatze** [comment]
That looks wrong indeed.
Can you open the same issue over at https://github.com/kubernetes-monitoring/kubernetes-mixin which is the correct upstream repository this is coming from.

It seems to be a direct copy of this (and thus a copy&paste mistake)
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/2728a81295761a9031b8152b37c2efb05ca949aa/alerts/resource_alerts.libsonnet#L14

**Comment by eyalzek** [comment]
Done: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/162

Thanks!
