### ISSUE TITLE
Adding storage spec requires manual deletion of the StatefulSet

### ISSUE THREAD

**Issue by aditya-konarde** [coreos/prometheus-operator#2408]
**What did you do?**
We have a `Prometheus` resource, which did not have `spec.Storage` set in the `PrometheusSpec`, so the statefulset does not have a PVC. 

Later, we decided to add some persistent storage to the Prometheus/Alertmanager Pods, so we added a `spec.storage` with the appropriate fields and values as described in the API spec, and applied the updated manifest.

**What did you expect to see?**
We were expecting to have the operator delete the statefulset and create a new one with the PVC in its template. 

**What did you see instead? Under which circumstances?**
Prometheus operator did not reconcile the state to get to the desired state, and the statefulset was not updated.

**Environment**

* Prometheus Operator version:
prometheusoperator.0.22.2

* Kubernetes version information:
Kubernetes Master: v1.11

* Kubernetes cluster kind: 
OpenShift : v3.11

* Manifests:

Issue description should be enough. Please let me know if manifests are needed

* Prometheus Operator Logs:

Nothing much in the logs, other than failure to update the statefulset (I need to validate if it was in log or kubernetes events)

**Comment by aditya-konarde** [comment]
Current workaround: Delete the statefulset to force a re-create by the operator

**Comment by brancz** [comment]
The operator does this automatically since [v0.24.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.24.0).

> [FEATURE] Add illegal update reconciliation by deleting StatefulSet (#1931)

**Comment by metalmatze** [comment]
Judging by your :+1: reaction, I'll close this one @aditya-konarde. Feel free to comment nevertheless.

**Comment by aditya-konarde** [comment]
Yup, was good to close. Thanks @brancz @metalmatze
