### ISSUE TITLE
Installation error: namespace kube-system doesn't match the current namespace

### ISSUE THREAD

**Issue by dannyyy** [coreos/prometheus-operator#2414]
**What did you do?**
Installing prometheus-operator Helm Chart through Rancher.
Default configuration, no overrides. Namespace is "monitoring"

**What did you expect to see?**
A successful installation

**What did you see instead? Under which circumstances?**
I install the chart into the namespace `monitoring`. Few seconds after, I get the following error message `Failed to install app prometheus-operator. Error: release prometheus-operator failed: resource's namespace kube-system doesn't match the current namespace monitoring"`

**Environment**

* Prometheus Operator version:

	2.2.2

* Kubernetes version information:

	`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

Rancher 2.1.6

* Manifests:

Default configuration

**Comment by brancz** [comment]
The helm charts are not maintained in this repo anymore, they are only an artifact left from migrating them to the upstream charts. Please report your issue there. Thanks! :slightly_smiling_face:
