### ISSUE TITLE
Configuring SMTP settings for grafana

### ISSUE THREAD

**Issue by JoshLefebvre** [coreos/prometheus-operator#2417]
I realize that this has already been asked in the following two threads: https://github.com/coreos/prometheus-operator/issues/2260 and  https://github.com/coreos/prometheus-operator/issues/1972, but following both threads has still not lead me to being able to resolve this issue and both are closed.

I have installed prometheus and grafana using the following commands: 

> helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring --set rbacEnable=false
> helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=false --namespace monitoring

Everything is running fine but there is no indication on how to find the grafana.ini file mentioned on the grafana website in order to configure the SMTP settings??? Which commands do I need to run to find this file? And which commands would I need to run in order to update this file with the correct values once it is found??

**Comment by vsliouniaev** [comment]
@JoshLefebvre You should be aware that [the chart you are using has been deprecated for some time](https://github.com/coreos/prometheus-operator/tree/master/helm#this-chart-is-deprecated). Reading through the configuration in the chart, I'm not certain that it exposes the grafana ini configurations you are looking for at all.

The configurations in [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) do allow you to make changes to the ini file. See here for more info on the ini:https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L241

**Comment by JoshLefebvre** [comment]
Ahh yeah it appears the tutorial I was following was quite old. I've since set up prometheus and grafana using the official helm charts. I am still attempting to configure smtp settings there but there seems to be good resources in the readme. Closing this.

Thank you
