### ISSUE TITLE
Customize relabel configs?

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/prometheus-operator#242]
We would like some additional labels to come over from our targets. The prometheus-operator generated `relabel_configs` only bring over certain labels, is there any way to customize?

I couldn't find anything about it in the docs. If it's not currently a feature, is there any plan to add this?

Thanks!

**Comment by snarlysodboxer** [comment]
Maybe rather than creating a way to customize `relabel_configs`, prometheus-operator could loop through all labels from a target and pass them through, maybe prepending them if necessary, or just leave them untouched for us to use as we wish.

This breaks the advantages of custom labeling.

I had to to read [the code](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/promcfg.go#L208) to understand which labels are being translated to which new labels, and the majority of the label information passed ends up being redundant, (at least in my setup.)

**Comment by brancz** [comment]
Currently all labels on a Service/Pod are already relabelled onto the targets with the `svc_` or `pod_` prefix. What are you looking to relabel onto the targets additionally?

We were trying not to introduce the entire relabeling here as well, because the point of abstracting these things was not having to learn relabeling. We understand this may still be necessary, but hope we can solve it otherwise. :slightly_smiling_face:

**Comment by snarlysodboxer** [comment]
@brancz Thanks. Keeping it simple is excellent.

As I was carefully describing my problem, I might have answered my own question.

Say I had an HA Prometheus setup named `A`with 2 replicas, and a second Prometheus setup named `B` from which I scrape setup `A` for meta-monitoring. I wanted to have a graph sourced from setup `B` about setup `A`, with two lines for any particular metric, one representing `prometheus-a-0` and the other representing `prometheus-a-1`. The only label currently coming through that can distinguish the replicas is `instance="100.96.3.59:9090"`, and it's value frequently changes as the pods get moved around, creating many short drops to zero (and color changes in Grafana) in the graph as pods get recreated.

I was concerned about being able to graph instance `prometheus-a-0` separately from `prometheus-a-1`, but, now I realize they're identical replicas, - I can't see a reason for tracking their _names_ separately, - and seeing the many drops to zero in the graph accurately represents the pods getting recreated, which is helpful information to have.

My apologies, I might have wasted your time. Let me know if I'm missing anything.

**Comment by brancz** [comment]
Actually I don't think it's a bad idea, basically what you are proposing is adding the pod name and/or service name by default to the targets, I don't see what would speak against that. It would actually allow joining metrics collected from targets easily with metrics from kube-state-metrics or cadvisor.

What do you think about by default relabeling pod name and service name onto the targets @fabxc ?

**Comment by snarlysodboxer** [comment]
@brancz I ran up against this problem again. It turns out the pod_name labels are very useful/needed for not having to sum/average two replicas together.

Thanks for fixing this!

**Comment by NiklasMerz** [comment]
I need labels to be transferred to pods. This seems to removed in #345. Do you have any plans to support custom labels? I need to use the exact names without a prefix in my specific use case.

How can I handle this?
```yaml        
        metric_relabel_configs:
        - source_labels: [pod_name]
          target_label: environment
          regex: (.+)-.+-.+
          replacement: $1
```

Thanks for helpin.

**Comment by brancz** [comment]
@NiklasMerz the idea is that you can join any label through the kube-state-metrics `kube_pod_labels` metrics onto the other metrics. Using the `label_replace` function in PromQL you can rename a label to whatever you need. I gave an example of how to do that [here](https://github.com/kubernetes/kube-state-metrics/issues/137#issuecomment-299837471).

**Comment by NiklasMerz** [comment]
@brancz Thanks for helping. If I understand this right this would help if I could change the Prometheus query. The point is I am trying to get the Gitlab Prometheus integration working so this exact query is executed by Gitlab:

```
(sum(container_memory_usage_bytes{container_name!="POD",environment="$CI_ENVIRONMENT_SLUG"}) / count(container_memory_usage_bytes{container_name!="POD",environment="$CI_ENVIRONMENT_SLUG"})) /1024/1024
```

This means I nedd to change the labels via configuration.

**Comment by batazor** [comment]
@NiklasMerz Hi. Did you integrate gitlab with Prometheus-operator?

**Comment by NiklasMerz** [comment]
@batazor Unfortunately I did not try it further.
