### ISSUE TITLE
Unable to run rules-configmap-reloader in docker 18.9.2  to 10Mi limit

### ISSUE THREAD

**Issue by gouki777** [coreos/prometheus-operator#2424]
**What did you do?**
Upgraded  dokcer version 18.9.2
**What did you expect to see?**
Pods continue running
**What did you see instead? Under which circumstances?**
```
Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod39529789-35a2-11e9-98c7-005056bd98cb/564ac56ec41f355be129131d9c0599b3de38d76068688abb9538c8456e5bc7cb/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

**Environment**

* Prometheus Operator version:

	0.29

* Kubernetes version information:

	v12.5

hi 
I look  https://github.com/coreos/prometheus-operator/releases/tag/v0.29.0  
I konw docker 18.9.2 unknown 10Mi  memory.limit   I konw memory.limit  change 100Mi is OK

I update 0.29 ,but statefulset.apps.alertmanager-main statefulset.apps.prometheus-k8s is no good.  
I  don't find statefulset.prometheus-k8s and statefulset.alertmanager-main memory.limit,
How to change the configuration. i don't find configuration.....
thanks.

<pre>
    State:          Waiting
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod39529789-35a2-11e9-98c7-005056bd98cb/9856bf0c86a0b07d86ad768429fa2a571a9eaf930b06a48f826870addd50c886/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
    Ready:          False
    Restart Count:  23
    Limits:
      cpu:     50m
      memory:  10Mi
    Requests:
      cpu:        50m
      memory:     10Mi
</pre>

**Comment by vsliouniaev** [comment]
@gouki777 This issue looks to be the same as yours: https://github.com/coreos/prometheus-operator/issues/2409

**Comment by gouki777** [comment]
i change alertmanager-main 100Mi,but no good. alertmanager-main auto change 10Mi....
<pre>
kubectl edit statefulset.apps -n monitoring alertmanager-main
        image: quay.io/coreos/configmap-reload:v0.0.1
        imagePullPolicy: IfNotPresent
        name: config-reloader
        resources:
          limits:
            cpu: 50m
            memory: 10Mi
</pre>

**Comment by brancz** [comment]
Does the Prometheus Operator log anything? It sounds to me like something is going wrong with rolling out the updated StatefulSets.

**Comment by gouki777** [comment]
my git clone https://github.com/coreos/prometheus-operator.git (0.29) and docker version 18.9.2
alertmanager-main-0 and  prometheus-k8s-0  wrong.   
  failed to write 10485760 to memory.limit_in_bytes: write...

<pre>
# pwd
/root/prometheus-operator/contrib/kube-prometheus/manifests
# kubeclet apply -f .
.......
# kubectl get po -n monitoring 
NAME                                   READY   STATUS              RESTARTS   AGE
alertmanager-main-0                    0/2     ContainerCreating   0          45s
prometheus-adapter-b7d894c9c-s5kts     1/1     Running             0          46s
prometheus-k8s-0                       2/3     CrashLoopBackOff    3          44s
prometheus-k8s-1                       2/3     CrashLoopBackOff    3          44s
prometheus-operator-566b5d5c85-jfsv8   1/1     Running             0          62s


# kubectl describe po -n monitoring prometheus-k8s-0
Name:                      prometheus-k8s-0
Namespace:                 monitoring
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 21 Feb 2019 22:21:11 +0800
      Finished:     Thu, 21 Feb 2019 22:26:09 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      POD_NAME:  prometheus-k8s-0 (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-plk9g (ro)
  rules-configmap-reloader:
    Container ID:  docker://8068194a57bbfb23865739edef952a057b43e3f9308f41b8e816fec7d9d2b6e1
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-k8s-rulefiles-0
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/podeef0512c-35e3-11e9-98c7-005056bd98cb/8068194a57bbfb23865739edef952a057b43e3f9308f41b8e816fec7d9d2b6e1/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
      Exit Code:    128
      Started:      Thu, 21 Feb 2019 22:24:02 +0800
      Finished:     Thu, 21 Feb 2019 22:24:02 +0800
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     25m
      memory:  10Mi
    Requests:
      cpu:        25m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-k8s-rulefiles-0 from prometheus-k8s-rulefiles-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-plk9g (ro)
Events:
  Type     Reason     Age                    From                      Message
  ----     ------     ----                   ----                      -------
  Normal   Scheduled  5m2s                   default-scheduler         Successfully assigned monitoring/prometheus-k8s-0 to k8s-n2-107v8-yz
  Normal   Pulled     5m1s                   kubelet, k8s-n2-107v8-yz  Container image "quay.io/coreos/prometheus-config-reloader:v0.28.0" already present on machine
  Normal   Created    5m1s                   kubelet, k8s-n2-107v8-yz  Created container
  Normal   Pulled     5m (x2 over 5m1s)      kubelet, k8s-n2-107v8-yz  Container image "quay.io/prometheus/prometheus:v2.5.0" already present on machine
  Normal   Created    5m (x2 over 5m1s)      kubelet, k8s-n2-107v8-yz  Created container
  Normal   Started    5m                     kubelet, k8s-n2-107v8-yz  Started container
  Normal   Started    4m59s (x2 over 5m1s)   kubelet, k8s-n2-107v8-yz  Started container
  Warning  BackOff    4m35s (x4 over 4m58s)  kubelet, k8s-n2-107v8-yz  Back-off restarting failed container
  Normal   Pulled     4m21s (x4 over 5m)     kubelet, k8s-n2-107v8-yz  Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Created    4m21s (x4 over 5m)     kubelet, k8s-n2-107v8-yz  Created container
  Warning  Failed     4m21s (x4 over 5m)     kubelet, k8s-n2-107v8-yz  Error: failed to start container "rules-configmap-reloader": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/podeef0512c-35e3-11e9-98c7-005056bd98cb/rules-configmap-reloader/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
<pre>

**Comment by brancz** [comment]
kube-prometheus is completely unversioned and the v0.29.0 tag _only_ relates to the prometheus operator. You will need to use current master of this repo for v0.29.0 of the prometheus operator to be in kube-prometheus. We intend to move kube-prometheus to a separate repository to avoid confusion like this.

**Comment by gouki777** [comment]
thanks. I konw.  
I change kube-prometheus 0prometheus-operator-deployment.yaml . -> v0.28.0  to v0.29.0 
pods continue running
```
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.28.0   
        image: quay.io/coreos/prometheus-operator:v0.28.0
```
