### ISSUE TITLE
Add cpu limit please

### ISSUE THREAD

**Issue by 0312birdzhang** [coreos/prometheus-operator#2425]
https://github.com/coreos/prometheus-operator/blob/7a25bf6b6bb2347dacb235659b73bc210117acc7/contrib/kube-prometheus/manifests/prometheus-prometheus.yaml#L18-L20

Prometheus use 95%+ CPU on one of my node , all pods on this node hangs.

**Comment by brancz** [comment]
The rendered manifests are just an example, you are free to modify them as you see fit, ideally following the guides we have provided for customization: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#customization-examples

Closing here as this is up to users to do.
