### ISSUE TITLE
kube-prometheus with Prometheus 2.7.0 or 2.7.1 records prometheus_rule_group_iterations_missed_total = 1

### ISSUE THREAD

**Issue by fredmtyro** [coreos/prometheus-operator#2426]
**What did you do?**
Installed kube-prometheus from prometheus-operator 0.29.0 on an empty docker desktop kubernetes cluster with Prometheus version overridden to 2.7.1. Looking at Prometheus stats for prometheus_rule_group_iterations_missed_total{job=~"prometheus-k8s"}, there seems to be a missed iteration which didn't show up in 2.5.0 or 2.6.1.

**What did you expect to see?**
0 total missed rule group iterations.

**What did you see instead? Under which circumstances?**
1 total missed rule group iterations at all times.

**Environment**
Docker Desktop Version 2.0.0.3 (31259) on a Mac

* Prometheus Operator version:

0.29.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Docker desktop though same issue arises in Kops created cluster on AWS.

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Comment by brancz** [comment]
As long as this is not increasing at a constant rate, there is nothing to worry about, this means that a rule group once took longer than the evaluation interval.

**Comment by fredmtyro** [comment]
Thank you for the response.
I agree that as long as it is not incrementing there is no significant underlying problem, I just noted the change in behaviour as it now is consistently one long rule evaluation per start where before there were none and thought that this would not be expected (and for our installation it highlighted that we were monitoring the sum of this figure over time where it is already a total).

**Comment by metalmatze** [comment]
This seems resolved.
