### ISSUE TITLE
kubelet target is down

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2434]
**What did you do?**
I change my worker node 

**What did you expect to see?**
Everything should be working as previously 

**What did you see instead? Under which circumstances?**
I am not getting any data in grafana and even in Prometheus.

While looking for the issue I found my kubelet target is down.

![image](https://user-images.githubusercontent.com/35921967/53404879-93657900-39dc-11e9-9ec4-1fa51deaa415.png)

below is my services running

kube-system   kube-dns                                                       ClusterIP      172.20.0.10      <none>             53/UDP,53/TCP                                   87d
kube-system   kubernetes-dashboard                                           LoadBalancer   172.20.207.81    acac76d69fe2e...   443:32501/TCP                                   75d
kube-system   metrics-server                                                 ClusterIP      172.20.82.155    <none>             443/TCP                                         87d
kube-system   pb-k8s-utils-prometheus-op-coredns                             ClusterIP      None             <none>             9153/TCP                                        22d
kube-system   pb-k8s-utils-prometheus-op-kube-controller-manager             ClusterIP      None             <none>             10252/TCP                                       22d
kube-system   pb-k8s-utils-prometheus-op-kube-etcd                           ClusterIP      None             <none>             4001/TCP                                        22d
kube-system   pb-k8s-utils-prometheus-op-kube-scheduler                      ClusterIP      None             <none>             10251/TCP                                       22d
kube-system   pb-k8s-utils-prometheus-op-kubelet                             ClusterIP      None             <none>             10250/TCP                                       24d
kube-system   tiller-deploy                                                  ClusterIP      172.20.255.193   <none>             44134/TCP                                       56d
monitoring    alertmanager-operated                                          ClusterIP      None             <none>             9093/TCP,6783/TCP                               22d
monitoring    alertmanager-sns-forwarder-svc                                 ClusterIP      172.20.18.219    <none>             9087/TCP                                        11d
monitoring    pb-k8s-util-prometheus-msteams                                 ClusterIP      172.20.55.185    <none>             2000/TCP                                        22d
monitoring    pb-k8s-utils-appd-machine-agent-svc                            ClusterIP      172.20.127.235   <none>             9090/TCP                                        2h
monitoring    pb-k8s-utils-prometheus-op-alertmanager                        ClusterIP      172.20.124.11    <none>             9093/TCP                                        22d
monitoring    pb-k8s-utils-prometheus-op-operator                            ClusterIP      None             <none>             8080/TCP                                        22d
monitoring    pb-k8s-utils-prometheus-op-prometheus                          LoadBalancer   172.20.191.2     a1658930427e4...   9090:30227/TCP                                  22d
monitoring    pb-k8s-utils-prometheus-operator-v1-grafana                    LoadBalancer   172.20.95.20     a164a2a4227e4...   80:32496/TCP                                    22d
monitoring    pb-k8s-utils-prometheus-operator-v1-kube-state-metrics         ClusterIP      172.20.6.181     <none>             8080/TCP                                        22d
monitoring    pb-k8s-utils-prometheus-operator-v1-prometheus-node-exporter   ClusterIP      172.20.35.50     <none>             9100/TCP                                        22d
monitoring    prometheus-operated                                            ClusterIP      None             <none>             9090/TCP   

Cause of the issue might be the port.

monitoring/pb-k8s-utils-prometheus-op-kubelet is trying to connect through 10255 but kubelete service is open on 10250. Is that is thereason? I tried to change the service to 10255 but it keep getting change to 10250. 

I am going the change by edit the service directly.
kubectl -n kube-system edit service pb-k8s-utils-prometheus-op-kubelet

Any suggetiong how I can fixed the issue. And I am on AWS

**Comment by brancz** [comment]
Could you be more precise in what you did, as it looks like you're attempting to scrape via `http` while the default configuration is `https`, so it seems you modified something. Could you please share the full setup.

**Comment by metalmatze** [comment]
Any updates on this?

**Comment by mmariani** [comment]
The default scraping configuration is indeed http; I had the same issue.

If using helm: adding  --set "kubelet.serviceMonitor.https=true" made it work for me, or setting it in values.yaml.

**Comment by brancz** [comment]
The helm charts are not maintained in this repository and all the configurations in this repository default to the https endpoints. Please open an issue on the upstream stable helm charts repo.

**Comment by omni-lchen** [comment]
I experienced the same issue with stable/prometheus-operator v5.0.2, it looks like the endpoints of kubelet service is not up to date, it still holds the nodes terminated, however the endpoints of prometheus-operator-kubelet service are showing correct, not sure this is kubernets issue, you can run the following commands to verify.
- kubectl -n kube-system get ep kubelet -o json | jq .subsets[].addresses[].ip | sort
- kubectl -n kube-system get ep prometheus-operator-kubelet -o json | jq .subsets[].addresses[].ip | sort
