### ISSUE TITLE
Instructions for monitoring kube-scheduler and kube-controller-manager not working in EKS

### ISSUE THREAD

**Issue by sverch** [coreos/prometheus-operator#2437]
**What did you do?**

Created a new EKS cluster, and tried to follow https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/cluster-monitoring.md to set up monitoring of kube-scheduler and kube-controller-manager.

**What did you expect to see?**

I expected the recommended services find the endpoints for the kube-scheduler and kube-controller-manager.  From those docs here's the kube-scheduler discovery service:

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler-prometheus-discovery
  labels:
    k8s-app: kube-scheduler
spec:
  selector:
    k8s-app: kube-scheduler
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
    protocol: TCP
```

**What did you see instead? Under which circumstances?**

Nothing is discovered, and in fact I see no pods for kube-scheduler in any namespace:

```shell
$ kubectl get all --all-namespaces
NAMESPACE     NAME                           READY   STATUS    RESTARTS   AGE
kube-system   pod/aws-node-68gsd             1/1     Running   1          6m
kube-system   pod/aws-node-mf8d6             1/1     Running   1          10m
kube-system   pod/aws-node-vkhqd             1/1     Running   1          7m
kube-system   pod/coredns-7bcbfc4774-ndksk   1/1     Running   0          17m
kube-system   pod/coredns-7bcbfc4774-nrqdd   1/1     Running   0          17m
kube-system   pod/kube-proxy-7f6mt           1/1     Running   0          10m
kube-system   pod/kube-proxy-9qcfk           1/1     Running   0          7m
kube-system   pod/kube-proxy-nqcfk           1/1     Running   0          6m

NAMESPACE     NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes   ClusterIP   172.20.0.1    <none>        443/TCP         17m
kube-system   service/kube-dns     ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   17m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     3         3         3       3            3           <none>          17m
kube-system   daemonset.apps/kube-proxy   3         3         3       3            3           <none>          17m

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   2         2         2            2           17m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-7bcbfc4774   2         2         2       17m
```

My current theory is that the kube-scheduler and kube-controller-manager are all hidden by AWS as part of the "managed control plane", while these instructions assume that these are running on and visible from kubernetes.  Is this correct?  Or am I doing something wrong?

**Environment**

* Prometheus Operator version:

Docs on current master.

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

The Terraform EKS resource: https://www.terraform.io/docs/providers/aws/r/eks_cluster.html

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Comment by brancz** [comment]
> My current theory is that the kube-scheduler and kube-controller-manager are all hidden by AWS as part of the "managed control plane", while these instructions assume that these are running on and visible from kubernetes. Is this correct? Or am I doing something wrong?

Yes I think you're right about this. The best thing would be if we had a jsonnet-patch that would remove alerts for "managed" clusters. We have a similar situation with GKE and AKS I believe. We don't have this for any of those yet, would you like to create that? :slightly_smiling_face:

**Comment by josepplaltg** [comment]
@brancz If you can provide me with some guidance I'll try to implement this jsonnet-patch, I think it's interesting and will be widely used, at least in my case ( 4 EKS clusters ), same for KubeClientCertificateExpiration.

**Comment by kskewes** [comment]
Hopefully I've copied and reflowed this correctly, but ours looks like this:
```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') {
  _config+:: {
    // Some jobs are not possible on managed Kubernetes services as some K8S Master services/pods are not exposed to customers
    // Disable jobs by adding to array, overwriting 'kube-prometheus.libsonnet' defaults
    local j = super.jobs,
    jobs: {
      [k]: j[k]
      for k in std.objectFields(j)
      if !std.setMember(k, ['KubeControllerManager', 'KubeScheduler'])
    }
}
```

**Comment by sverch** [comment]
Sorry for the delay @brancz.  I actually have mostly been following the docs at https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/cluster-monitoring.md, so even a mention that this doesn't work for EKS would resolve the issue as far as I'm concerned.  But I understand that you'd want your manifests to also reflect that.

**Comment by brancz** [comment]
@sverch could you add this to the docs? That would be highly appreciated! :slightly_smiling_face: 

@kskewes that's a great snippet, what do you think of creating a "kube-prometheus-managed-cluster.jsonnet" like we have for kops/kubeadm/etc. to remove the things that are commonly unavailable in managed clusters?

@josepplaltg `KubeClientCertificateExpiration` firing sounds like the cert rotation might be relatively low, you might just need to adapt the thresholds at which these alerts fire.

**Comment by kskewes** [comment]
Recognise your own work? It came from you in another issue on here. So thank you. I'll send a PR. :)

**Comment by brancz** [comment]
hahaha :joy: thanks for not taking credit I guess? I'd still be very thankful for a PR :slightly_smiling_face:

**Comment by sverch** [comment]
Oh yeah for sure @brancz!  Here's the PR: https://github.com/coreos/prometheus-operator/pull/2461.

**Comment by metalmatze** [comment]
With #2464 being merged I think we can close this.

**Comment by thodquach** [comment]
Hello, 
I met a similar like you: [kube-scheduler](https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/#kube-scheduler) is a part of [kubernetes control plane](https://kubernetes.io/docs/concepts/overview/components/#control-plane-components). It's components are scheduled on master node, to which on managed kubernetes solutions such as AKS, GKE or EKS, we have no access.

**Comment by hwangmoretime** [comment]
relatedly, here is a feature request for EKS to expose control plane metrics: https://github.com/aws/containers-roadmap/issues/800
