### ISSUE TITLE
kube-prometheus-exporter-kube-state crashing

### ISSUE THREAD

**Issue by antonyaugustus** [coreos/prometheus-operator#2440]
**What did you do?**
Install prometheus and prometheus-operator
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name prometheus --namespace monitoring

**What did you expect to see?**
All resources up and running

**What did you see instead? Under which circumstances?**
Pod kube-prometheus-exporter-kube-state keeps crashing

**Environment**
kubernetes v1.12.4
I have 3 masters and 10 worker nodes

* Prometheus Operator version:

	NAME                    REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
	kube-prometheus         1               Tue Oct  2 20:08:01 2018        DEPLOYED        kube-prometheus-0.0.105                         monitoring
	prometheus-operator     1               Wed Feb 27 20:57:59 2019        DEPLOYED        prometheus-operator-0.0.29      0.20.0          monitoring

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	insert how you created your cluster: kubeadm.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

Name:               kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj
Namespace:          monitoring
Priority:           0
PriorityClassName:  <none>
Node:               xxx/xxxx
Start Time:         Wed, 27 Feb 2019 21:02:53 +0000
Labels:             app=kube-prometheus-exporter-kube-state
                    component=kube-state
                    pod-template-hash=2459495682
                    release=kube-prometheus
                    version=v1.2.0
Annotations:        <none>
Status:             Running
IP:                 xxx.xxx.xxx.xxx
Controlled By:      ReplicaSet/kube-prometheus-exporter-kube-state-689f8f9bd6
Containers:
  exporter-kube-state:
    Container ID:   docker://6fb71030cbb9900a4d27206ff0d49e2554856ed227b61768667eafce9e6ff807
    Image:          gcr.io/google_containers/kube-state-metrics:v1.2.0
    Image ID:       docker-pullable://gcr.io/google_containers/kube-state-metrics@sha256:953a3b6bf0046333c656fcfa2fc3a08f4055dc3fbd5b1dcdcdf865a2534db526
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 27 Feb 2019 22:25:42 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 27 Feb 2019 22:19:40 +0000
      Finished:     Wed, 27 Feb 2019 22:20:32 +0000
    Ready:          False
    Restart Count:  18
    Limits:
      cpu:     110m
      memory:  150Mi
    Requests:
      cpu:        110m
      memory:     150Mi
    Liveness:     http-get http://:8080/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8080/ delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-prometheus-exporter-kube-state-token-mpvzd (ro)
  exporter-kube-state-addon-resizer:
    Container ID:  docker://ec579bd2ff879c0a33e98337e45d2928950a9131131efc5b8f6371a58171be6a
    Image:         gcr.io/google_containers/addon-resizer:1.7
    Image ID:      docker-pullable://gcr.io/google_containers/addon-resizer@sha256:dcec9a5c2e20b8df19f3e9eeb87d9054a9e94e71479b935d5cfdbede9ce15895
    Port:          <none>
    Host Port:     <none>
    Command:
      /pod_nanny
      --container=exporter-kube-state
      --cpu=100m
      --extra-cpu=1m
      --memory=130Mi
      --extra-memory=2Mi
      --threshold=5
      --deployment=kube-prometheus-exporter-kube-state
    State:          Running
      Started:      Wed, 27 Feb 2019 21:03:00 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  30Mi
    Requests:
      cpu:     100m
      memory:  30Mi
    Environment:
      MY_POD_NAME:       kube-prometheus-exporter-kube-state-689f8f9bd6-nnfkj (v1:metadata.name)
      MY_POD_NAMESPACE:  monitoring (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-prometheus-exporter-kube-state-token-mpvzd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-prometheus-exporter-kube-state-token-mpvzd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-prometheus-exporter-kube-state-token-mpvzd
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From                                     Message
  ----     ------   ----                  ----                                     -------
  Warning  BackOff  3m5s (x306 over 81m)  kubelet, xxx.xxx.xxx.xxx  Back-off restarting failed container

**Comment by brancz** [comment]
#2416 removed the helm charts. They are not part of this repo nor are they maintained by the prometheus-operator/kube-prometheus maintainers. Closing this here. Please open an issue on the upstream charts repo.
