### ISSUE TITLE
Feature Request: Ability to inject environment variables in the prometheus pod

### ISSUE THREAD

**Issue by sgmitchell** [coreos/prometheus-operator#2444]
### Background
I attempted to add a scrape config for google cloud instances [`gce_sd_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config) using an additional scrap config. The prometheus statefulset loaded this config successfully but failed to discover any targets because of an authentication issue.

The prometheus documentation notes that credentials will be found using the standard google SDK process by searching for:
1. a well known environment variable
2. a well know file path
3. the GCE metadata endpoint (if available)

### Workaround
There are 2 workarounds I could find.

My current workaround is to build a custom docker image and adding a secret to the prometheus object:

```
FROM quay.io/prometheus/prometheus:v2.7.1
ENV GOOGLE_APPLICATION_CREDENTIALS=/etc/prometheus/secrets/googleCreds/creds.json
```
```
apiVersion: v1
kind: Secret
...
data:
  creds.json: $B64_ENCODED_CREDS
```
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
spec:
  image: $MY_CUSTOM_IMAGE
  secrets:
  - googleCreds
  ...
```

Alternatively, [this line](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L739) _seems_ to indicate that I could set the environment variable using the deprecated thanos GCS spec

### Proposed Change
Modify the operator to allow for injecting secrets in to the prom, either by adding a new top level element `env` to the prometheus spec or extending the existing `containers` spec to allow for patching the the generated containers.

I'll have a PR ready for the patch containers solution soon

**Comment by sterchelen** [comment]
@sgmitchell Any news about your proposal ?

**Comment by sgmitchell** [comment]
#2445 implements this and should be merged in soon

**Comment by swtch1** [comment]
#2445 was merged.  This issue should likely be closed if this is the recommended pattern.
