### ISSUE TITLE
Doc: Grafana watcher

### ISSUE THREAD

**Issue by cemo** [coreos/prometheus-operator#245]
Hi, thank you so much for whole repo and guidance to make it clear things for me. Before starting to use prometheus operator I would like to do everything manual to learn as much as possible. Current organization of the repo has some doc issues regarding its potential. If you don't mind, I will open some issues to improve documentation? I would like to start about `Grafana Watcher`. There might be a README file in the directory of it.

1. What is the use case of it?
2. Example usage?
3. How grafana dashboard must be modified? (which is actually my problem)

thanks

**Comment by brancz** [comment]
Absolutely a valid case! I'll make sure we add docs about it!

**Comment by galexrt** [comment]
@brancz I added these points to #98.

**Comment by brancz** [comment]
For now I think we'll keep that documentation local to the directory it lies in, and not move it into the main `Documentation/` directory, but thanks for doing that @galexrt! We'll track it from there and close here, thanks for reporting @cemo !
