### ISSUE TITLE
`additionalScrapeConfigs.optional` doesn't unblock cluster creation with nonexistent secret

### ISSUE THREAD

**Issue by davidquarles** [coreos/prometheus-operator#2457]
**What did you do?**
I created a promethei with `additionalScrapeConfigs.optional: true`, pointing to a nonexistent secret.

**What did you expect to see?**
A new prometheus-operated statefulset with additional scrape configs injected if/when the specified secret/key exists.

**What did you see instead? Under which circumstances?**
A new `prometheus` was created, but the absence of the "optional" secret actually blocked statefulset creation.

**Additional context:**
I've written a custom controller that watches namespaces within our clusters and automatically injects a `prometheus` into each as they are spun up.  We want to functionally shard by namespace to reduce the footprint of our ingestion layer, to segment compute/storage costs by namespace, etc... with a unified cluster-level query + rule-eval layer via thanos.

I have this wired up successfully today, with the caveat that a small handful of namespaces ship high-cardinality metrics that we want to aggregate pre-ingestion.  In the absence of any match-based filtering in the ingestion layer, it seems like federating to lower-tier promethei that don't participate in the thanos cluster is a viable solution.  That said, I'd like to provide a mechanism to (optionally) use `additionalScrapeConfigs`.

Statefulsets are created if I create that secret with an empty value for the specified key, but I'd like to just leave factor that secret out of the control loop altogether and let teams create it if/when they deem that pattern necessary.  Unless I'm missing something and this functionality in fact exists, it seems like I'll have to write more nuanced logic around that secret creation, such that we create, but do not mutate.  I am of course open to any/all design feedback, ideas, etc.  Thank you!

**Environment**

* Prometheus Operator version:

`quay.io/coreos/prometheus-operator:v0.29.0`

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ kubecfg version # what we're actually deploying with, as we use jsonnet
kubecfg version: v0.9.0
jsonnet version: v0.10.0
client-go version: v0.0.0-master+$Format:%h$
```

* Kubernetes cluster kind: 

kops 1.11.0

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    name: default
    prometheus: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  additionalScrapeConfigs:
    key: config.yaml
    name: prometheus-scrape-configs
    optional: true
  baseImage: prom/prometheus
  evaluationInterval: 60s
  externalLabels:
    monitor: prometheus
    replica: $(POD_NAME)
  logFormat: json
  podMetadata:
    app: prometheus
    name: cert-manager
    prometheus: cert-manager
  priorityClassName: high-priority
  replicaExternalLabelName: replica
  replicas: 1
  resources:
    limits:
      memory: 100Gi
    requests:
      memory: 10Mi # VPA-managed
  retention: 24h
  scrapeInterval: 60s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus.io/scrape: "true"
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
  thanos:
    peers: thanos-peers.monitoring.svc.cluster.local:10900
    resources:
      limits:
        memory: 10Gi
      requests:
        memory: 10Mi # VPA-managed
    tag: v0.3.1
    version: 0.3.1
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: Monitoring
  version: v2.6.0
```

* Prometheus Operator Logs:

```
...
level=info ts=2019-03-05T19:15:17.946801922Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=cert-manager/cert-manager
E0305 19:15:17.955324       1 operator.go:870] Sync "cert-manager/cert-manager" failed: creating config failed: loading additional scrape configs from Secret failed: secret prometheus-scrape-configs could not be found
level=info ts=2019-03-05T19:15:17.991428046Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=ingress-nginx/ingress-nginx
E0305 19:15:18.001280       1 operator.go:870] Sync "ingress-nginx/ingress-nginx" failed: creating config failed: loading additional scrape configs from Secret failed: secret prometheus-scrape-configs could not be found
...
```

**Comment by brancz** [comment]
First of all thank you for this detailed write up, it's very much appreciated that you put in the time to do this.

I think you're absolutely right, we should follow the content of the `optional` field, which we do not today. We should check here:

https://github.com/coreos/prometheus-operator/blob/b8b81cb6886695887e4c34fa45c09110b264bdad/pkg/prometheus/operator.go#L1162-L1166

Whether `.Optional` in the SecretKeySelector is set to true, and instead of return those errors, we just log them on debug level, as we tolerate their absense, and if `.Optional` is false, then we fail return the error as we do now. Does that sound reasonable?

Would you like to do the PR to fix this issue?

**Comment by davidquarles** [comment]
Hey @brancz!  I'm sorry to have slept on this.  My dayjob has been pretty hectic, but there's another change that we need now, too (`--max-samples` support), and I'm going to try to tackle both this week.

**Comment by brancz** [comment]
@davidquarles no worries at all. Thanks for taking the time! Looking forward to the contribution! :)
