### ISSUE TITLE
Provide more instructions to bootstrap using helm

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#246]
How to correctly bootstrap prometheus-operator with helm? Looks like [the docs](https://github.com/coreos/prometheus-operator/blob/f70fbcabae044a17ef7b3f70057ca1bd05365ddf/helm/README.md) aren't finished yet

```
$ helm install opsgoodness/prometheus-operator 
Error: file "opsgoodness/prometheus-operator" not found
```

This command below fix, however I'll appreciate this files into [kubernetes/charts](https://github.com/kubernetes/charts/) or a coreos chart.

```
$helm repo add opsgoodness http://charts.opsgoodness.com
"opsgoodness" has been added to your repositories
```

Related to #238

**Comment by mgoodness** [comment]
The Helm charts were merged into this repo very recently. I'll be updating them this weekend to the latest version of the operator and will be sure to include the docs.

**Comment by gianrubio** [comment]
Thanks for the info @mgoodness
