### ISSUE TITLE
OOM Issues on prometheus instances

### ISSUE THREAD

**Issue by weeco** [coreos/prometheus-operator#2460]
**The problem**

I am running prometheus operator and hoped for a simple prometheus setup which runs reliably. Unfortunately I am running into lots of prometheus pod restarts (all instances) which are caused due too OOM Kills by Kubernetes.

Right now I am running 3 prometheus instances each having 20GB Ram Limit, configured for 8d retention plus a thanos sidecar container which syncs data to our Google Cloud Storage Bucket. The Bucket has no lifecycle (I could enable 14days deletion lifecycle though?). This started happening just recently after having a stable prometheus environment for a couple weeks. Thus I wonder if it's caused by Thanos which may load the prometheus data on startup into RAM and then runs out of memory because of this?

I am trying to figure out what is causing our OOM issues and how we could get rid of them. I looked into limiting the number of max samples as this has helped us before we changed our setup to prometheus operator, but apparently I have no possibility to edit such a setting. What could we do to debug this?

**Environment**

* Prometheus Operator version:

v0.28.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Google Kubernetes Engine

* Manifests:

My Prometheus CRD Manifest:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  creationTimestamp: 2019-01-23T14:39:17Z
  generation: 1
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-1.8.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-prometheus
  namespace: prometheus
  resourceVersion: "227656940"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/prometheus/prometheuses/prometheus-operator-prometheus
  uid: a96b3732-1f1c-11e9-94aa-42010a8401e2
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: prometheus-operator-prometheus-scrape-confg
  alerting:
    alertmanagers:
    - name: prometheus-operator-alertmanager
      namespace: prometheus
      pathPrefix: /
      port: web
  baseImage: eu.gcr.io/redacted-registry-v002/prometheus
  externalUrl: http://prometheus-operator-prometheus.prometheus:9090
  listenLocal: false
  logLevel: info
  nodeSelector:
    cloud.google.com/gke-nodepool: default
  paused: false
  query:
    maxSamplesPerSend: 500000
  replicas: 3
  resources:
    limits:
      cpu: 4
      memory: 20Gi
    requests:
      cpu: 1
      memory: 15Gi
  retention: 8d
  routePrefix: /
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: prometheus-operator
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-operator-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-operator
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: standard
  thanos:
    baseImage: eu.gcr.io/redacted-registry-v002/thanos
    gcs:
      credentials:
        key: credentials.json
        name: sa-thanos
    objectStorageConfig:
      key: objectStorageConfig.yaml
      name: thanos-object-storage-config
    tag: v0.2.1
  version: v2.7.1
```

* Prometheus Operator Logs:

```
// Only lots of these logs
level=info ts=2019-03-06T12:15:01.679123998Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-06T12:15:02.917486501Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-06T12:15:06.046226412Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-06T12:15:09.188421797Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-06T12:15:09.775070723Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
```

**Comment by metalmatze** [comment]
> Right now I am running 3 prometheus instances each having 20GB Ram Limit, configured for 8d retention

Personally, I'm running the kube-prometheus (along with a bunch of other workload) on a 3 node cluster on DigitalOcean that have 4GB each. So your setup should be sufficient!


> plus a thanos sidecar container which syncs data to our Google Cloud Storage Bucket. The Bucket has no lifecycle (I could enable 14days deletion lifecycle though?). This started happening just recently after having a stable prometheus environment for a couple weeks. Thus I wonder if it's caused by Thanos which may load the prometheus data on startup into RAM and then runs out of memory because of this?

The sidecar simply watches the filesystem and once there's a new block written it will ship it to object storage. The sidecar itself doesn't read the data. If you run the Thanos compactor you don't really need to set a retention of the data in object storage. We plan to go with 13 months at some point.

By looking at the Pod description `kubectl describe` can you see more information on what container caused the OOM kill?

**Comment by weeco** [comment]
I checked the pod description and it is the prometheus container. I believe I can reproduce the issue by changing the timeframe of specific Grafana dashboards from Last 3 hours to Last 7 days for instance. It seems Prometheus tries to load too many samples into RAM then?

**Comment by metalmatze** [comment]
Sure, that exactly what happens if you query data for 7 days. Because you already run Thanos, I recommend running the compactor so it can start down sampling older metrics.

**Comment by weeco** [comment]
@metalmatze In an environment where multiple teams access the same backend it is not avoidable that one out of 50 developers or so uses Last 7 days timerange at least once in a week.

I am fine when prometheus does not respond to such queries, but I am not okay that my prometheus instances can be crashed due to this. I believe I prevented this with my own prometheus setup (before I started using prometheus operator) by limiting the number of max samples. As far as I know I can not change this with prometheus operator.

**Comment by metalmatze** [comment]
If the other developers mostly look at dashboards that show the last 7 days then maybe it's worth caching the data. Something like https://github.com/Comcast/trickster might help you then. Otherwise you need to shard Prometheus per team for example. Shouldn't be that hard either with the Prometheus Operator up and running.

**Comment by weeco** [comment]
Why isn't it possible to set the maximum number of allowed samples instead if this is exactly what could take down the prometheus server? Even if I create one prometheus server for each team the problem will still exist, unless there are enough resources available to handle such big requests.

Again I do not necessarily want to allow queries reaching back 7days if there is simply too much data to evaluate. It's just unacceptable that such queries bring down my prometheus server and therefore trigger alerts (because of execution errors / no data)

**Comment by brancz** [comment]
Starting with v2.5.0 Prometheus supports the `--query.max-samples` flag. As far as I can tell we don't support this flag yet. We should though.

**Comment by davidquarles** [comment]
@brancz Would you accept a PR for that change?  It doesn't seem terribly involved.  Rule eval is currently failing on our largest cluster for this exact reason and we have no way to mitigate today.

**Comment by squat** [comment]
Closing this as we now have a way to limit the maximum samples thanks to #2505.

@weeco plz write back if you think this needs to be reopened.
