### ISSUE TITLE
exported_namespace label instead of namespace in "Kubernetes / Persistent Volumes" grafana dashboard

### ISSUE THREAD

**Issue by GAHila** [coreos/prometheus-operator#2463]
**What did you do?**
Upgraded from Prometheus 0.23 to 0.29 and grafana from the manifests file provided

**What did you expect to see?**
Expected grafana "Kubernetes / Persistent Volumes" dashboard to display namespaces

**What did you see instead? Under which circumstances?**
No namespaces listed 

**Environment**
EKS

* Prometheus Operator version:
0.29
	

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

  AWS EKS

 I upgraded everything from the manifest and used: https://github.com/coreos/prometheus-operator/blob/release-0.29/contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml for grafana dashboards. 

"Kubernetes / Persistent Volumes" grafana dashboard has two queries that are looking for exported_namespace label:

```
"query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\"}, exported_namespace)",
```
```
"query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\", exported_namespace=\"$namespace\"}, persistentvolumeclaim)",
```

However there is no such label in prometheus. I think that this is a accidental bug that needs to be fixed.

**Comment by brancz** [comment]
You're absolutely right, that should be just `namespace`. This needs to be fixed in the kubernetes-mixin directly: https://github.com/kubernetes-monitoring/kubernetes-mixin. Could you open an issue and or pull request there to fix this? Thanks! :slightly_smiling_face:

**Comment by desaintmartin** [comment]
Here you are: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/175/files
(May be split if necessary).
