### ISSUE TITLE
Job specific scrape interval

### ISSUE THREAD

**Issue by ajw** [coreos/prometheus-operator#2479]
**What did you do?**
I'm trying to using prometheus operator set to a different scrape period for a job.

**What did you expect to see?**
A configuration option  to set  a scrape interval on per job basis similar to that in prometheus configuration
```
# The job name assigned to scraped metrics by default.
job_name: <job_name>

# How frequently to scrape targets from this job.
[ scrape_interval: <duration> | default = <global_config.scrape_interval> ]
```
**What did you see instead? Under which circumstances?**
Couldn't see a way to configure this. Is it possible?

**Prometheus Operator version:**
0.29.0

**Comment by Shini31** [comment]
Hi,

You can change the scrape interval value into the dedicated service monitor:
- https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor
- https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint

**Comment by brancz** [comment]
Closing due to staleness and question has been answered.
