### ISSUE TITLE
Release 0.29.0 says Prometheus is now v2.7.1 by default but some references were missed

### ISSUE THREAD

**Issue by jstangroome** [coreos/prometheus-operator#2481]
**What did you do?**
Installed Prometheus Operator 0.29.0 via contrib/kube-prometheus/manifests/

**What did you expect to see?**
Prometheus Pods running image v2.7.1

**What did you see instead? Under which circumstances?**
Prometheus Pods running image v2.5.0

* Prometheus Operator version:

	v0.29.0 / 7a25bf6b6bb2347dacb235659b73bc210117acc7

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

https://github.com/coreos/prometheus-operator/blob/v0.29.0/contrib/kube-prometheus/manifests/prometheus-prometheus.yaml

Changelog of Operator v0.26.0 states:
>[ENHANCEMENT] Update to Proemtheus v2.5.0 as default (#2101).

And the linked PR shows `prometheus-prometheus.yaml` version update:
https://github.com/coreos/prometheus-operator/pull/2101/files#diff-9ce1faf7c759768f42198063e90d92adL28

And changelog of Operator v0.29.0 states:
>[ENHANCEMENT] Update to Prometheus v2.7.1 as default (#2374)

But the linked PR **does not** update the same `version` line of the same file:
https://github.com/coreos/prometheus-operator/pull/2374/files

I'm not sure if this is a process step missed or a bug in the template generation system.

**Comment by psemeniuk** [comment]
Alertmanager's version also.

Btw. why every release in bundled contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml has previous version of operator? In 0.29.0 there is 0.28.0.

**Comment by brancz** [comment]
kube-prometheus is a sub-project, that which version has nothing to do with the prometheus operator version. We are in the process of moving kube-prometheus out of this repo (just some technicalities to be figured out). Hopefully then this situation will be less confusing.

**Comment by metalmatze** [comment]
Exactly, whenever you want to use a release of the Prometheus Operator via kube-prometheus (`contrib/kube-prometheus`), please use the current `master` or check out one of the commits after that release, where we bump the versions in `contrib/kube-prometheus`.
