### ISSUE TITLE
kube-prometheus: conflicts on existing node-exporter

### ISSUE THREAD

**Issue by philips** [coreos/prometheus-operator#249]
**What did you do?**

Deployed kube-prometheur

**What did you expect to see?**

Everything working

**What did you see instead? Under which circumstances?**

The node-exporter daemonset of kube-prometheus conflicts with the exporter shipped with Tectonic

**Environment**

Tectonic v1.5.5 via AWS Terraform

**Comment by brancz** [comment]
I don't think this is a problem, as this is meant to be from 0 to end-to-end monitoring, all of this will eventually move into being handled by tectonic. Once we move all of kube-prometheus into a helm chart, we could potentially make it configurable whether the node-exporter is deployed at all. Would that be a suitable solution? For the time being, it is probably best to modify the hack script to deploy and just not deploy the node-exporter.

**Comment by atopuzov** [comment]
Helm solution https://github.com/coreos/prometheus-operator/pull/757

**Comment by brancz** [comment]
With helm you can now choose what do deploy of the kube-prometheus stack. Closing this here.
