### ISSUE TITLE
Error on ingesting samples

### ISSUE THREAD

**Issue by weeco** [coreos/prometheus-operator#2495]
**What did you do?**

My organization is just using Prometheus / Grafana as usual, I am not aware of a special action which triggers these errors

**What did you expect to see?**

No error logs in prometheus

**What did you see instead? Under which circumstances?**

Here and there I have troubles with prometheus not answering with data for my Grafana dashboards and I am trying to figure out it's cause. I am not sure if these warn logs are related to this, but I'd like to fix it, if possible. I see lots of warn logs (roughly 1-2 logs per second) saying:

```
level=warn ts=2019-03-18T10:12:23.315423921Z caller=scrape.go:1094 component="scrape manager" scrape_pool=kubernetes-pods target="http://10.0.70.245:1912/metrics?format=prometheus" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=8
```

**Environment**

Kubernetes, Prometheus 2.7.1, Thanos 0.2.1 with Google bucket storage (no lifecycle)

* Prometheus Operator version:

v0.28.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Google Kubernetes Engine

* Prometheus Operator Logs:

Just lots of these messages

```
level=info ts=2019-03-18T10:14:08.076761492Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-18T10:14:08.645605378Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-18T10:14:09.54931287Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
level=info ts=2019-03-18T10:14:12.239509604Z caller=operator.go:968 component=prometheusoperator msg="sync prometheus" key=prometheus/prometheus-operator-prometheus
```

**Comment by brancz** [comment]
It sounds like the target with the hostport `10.0.70.245:1912` is returning a metrics output including timestamp, and either the timestamp is not being updated for some reason or your clocks are out of sync. For the later reason we recommend to try to avoid exposing timestamp in the exposition format. In the next Prometheus release there will be a feature on Prometheus side to ignore this.
