### ISSUE TITLE
Should contrib/kube-prometheus be deprecated?

### ISSUE THREAD

**Issue by nfisher** [coreos/prometheus-operator#2496]
When looking to use the prometheus operator there appears to be 3 different options for install with varying focuses:

1. jsonnet/prometheus-operator.
2. contrib/kube-prometheus.
3. helm chart under helm org.

As a new user to the project it's not immediately clear what context to consider when choosing them. There seems to be semi-regular updates across all 3 so it's not clear any one is actually deprecated.

Would it be worthwhile deprecating 2 o the 3 forms or making a more explicit *use this one* these ones are for testing or whatever?

**Comment by brancz** [comment]
The helm chart is not maintained by us, nor did we start it or use it, so that's outside of our control. It was created out of the kube-prometheus stack.

jsonnet/prometheus-operator is the most authoritative one doesn't have the entire stack, just brings the bare minimum to start a prometheus-operator, no entire cluster-monitoring stack. kube-prometheus is the brings an entire cluster-monitoring stack that is extremely opinionated.

**Comment by nfisher** [comment]
Would it make sense to combine into one and have it so they compose (e.g. you can toggle the features you want via variables?).

I'm willing to make a PR what of the following do you think is worthwhile?

 1. update description in README giving an overview of the folder structure.
 2. update jsonnet config to have "toggle" oriented components.
 3. nothing? Close issue and carry on. :D

**Comment by brancz** [comment]
I think clarifying each existence in the main readme would be appropriate. Maybe a more elaborate statement in this section: https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus. That would not just describe the difference but actually point at the different directories and methods and also clearly state that the helm chart is not maintained by the maintainers of the prometheus-operator/kube-prometheus. What do you think?

**Comment by metalmatze** [comment]
Do you want to create a PR to the README to explain this more thoroughly, @nfisher?

**Comment by nfisher** [comment]
Yep will try to once I get our deployment of prom sorted.

**Comment by metalmatze** [comment]
[kube-prometheus](https://github.com/coreos/kube-prometheus) is now its own project and the helm chart makes use of that.
