### ISSUE TITLE
Old version of configmap-reload referenced

### ISSUE THREAD

**Issue by nfisher** [coreos/prometheus-operator#2498]
Looking at this line it appears the configmap-reload and digging into the quay repo it appears the image is 2y old. Implies the running binary contains some CVE's that have recently been patched in Go.
https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml#L117

Should this be updated to the version below or a new build generated and re-pushed (e.g. 0.2.1-go112)?
https://hub.docker.com/r/jimmidyson/configmap-reload/tags

**Comment by brancz** [comment]
Could you do a pull request replacing it with the latest upstream image? If tests just pass I'm happy to bump it, and remove us having to sync with upstream.

**Comment by pgier** [comment]
Fixed by #2952
