### ISSUE TITLE
node-exporter fails to open log file

### ISSUE THREAD

**Issue by olivier-mauras** [coreos/prometheus-operator#2507]
**What did you do?**
Installed kube-prometheus from the manifests

**What did you expect to see?**
All pods running

**What did you see instead? Under which circumstances?**
``` bash
$ kubectl -n monitoring get pods
NAME                                   READY     STATUS             RESTARTS   AGE
alertmanager-main-0                    2/2       Running            0          17h
alertmanager-main-1                    2/2       Running            0          17h
alertmanager-main-2                    2/2       Running            0          17h
grafana-6bd7d77f95-wsbp8               1/1       Running            0          19h
kube-state-metrics-5cb7b667b6-t7z6j    4/4       Running            0          19h
node-exporter-qcmm7                    1/2       CrashLoopBackOff   230        19h
node-exporter-wx6j7                    1/2       CrashLoopBackOff   230        19h
prometheus-adapter-7657dc4bcf-4nmll    1/1       Running            0          17h
prometheus-k8s-0                       3/3       Running            1          17h
prometheus-k8s-1                       3/3       Running            1          17h
prometheus-operator-78f6567cf6-fxwkk   1/1       Running            0          17h
```
**Environment**

* Prometheus Operator version:

	650359b3e627ae97a1f18cbd10d7ed9b2293c240

* Kubernetes version information:

	Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	PKS

* Prometheus Operator Logs:

``` bash
$ kubectl logs -n monitoring node-exporter-qcmm7 node-exporter
failed to open log file "/var/log/pods/bf79100c-4f03-11e9-ad40-005056ab5125/node-exporter/231.log": open /var/log/pods/bf79100c-4f03-11e9-ad40-005056ab5125/node-exporter/231.log: no such file or directory
```

**Comment by olivier-mauras** [comment]
I've had to remove entries about / mountpath in the daemonset config and now it's running fine.
I believe an incompatibility with my 1.11 version??

**Comment by metalmatze** [comment]
To me this looks like an issue with PKS. Have you check with them?

**Comment by olivier-mauras** [comment]
Could be. Guess it's worth asking them.

**Comment by brancz** [comment]
Indeed, this looks like an issue on the kubelet. Can you confirm this @olivier-mauras ?

**Comment by st3v** [comment]
I believe this is due to https://github.com/cloudfoundry-incubator/kubo-release/issues/309

**Comment by brancz** [comment]
This seems like a non-issue with the prometheus-operator, and the kube-prometheus stack moved to coreos/kube-prometheus. Closing here, please re-open on the other repository if you feel this is actually an issue with kube-prometheus.

**Comment by olivier-mauras** [comment]
Sorry for not updating, this is exactly as stated by @st3v
