### ISSUE TITLE
Configuration of cachet (an opnesource status page) with Prometheus operator.

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2509]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
Hi,

I am trying to configure cachet (an opnesource status page) with prometheus,
What I am looking for is that a way to integrate the both via API calls.
We can send API posts to cachet and change the status and add an incident etc manually.
I need to know if this is possible from prometheus ie when an alert is triggered it should send an API call (customised) to the cachet which I have configured. Please let me know whether this is possible with the Prometheus operator.

**Comment by metalmatze** [comment]
If it is possible with Prometheus then it should certainly be possible with the Prometheus Operator. We start Prometheus as a Kubernetes StatefulSet.
To figure out the first please contact the [Prometheus Users mailing list](https://prometheus.io/community/) which should be the appropriate forum to ask.

Let us know in this issue if something specific to the operator comes up. Closing for now.
