### ISSUE TITLE
 Can't attach bearer token file to Prometheus pods

### ISSUE THREAD

**Issue by slavakl** [coreos/prometheus-operator#251]
Endpoint specification allows to provide bearerTokenFile parameter which,I assume, can be used to pass a token different from a service account token.

As Prometheus nodes are created by Operator based on Prometheus resource, how a file with a token can be attached to Prometheus pods? Prometheus resource spec has nothing related to volume mount.

If this is not implemented yet, would adding a BearerToken parameter to Endpoint spec be an acceptable solution? Will be happy to submit a PR

**Comment by galexrt** [comment]
Do you mean a `bearerToken` field for the "plain" token or a path to the `bearerTokenFile`?
See https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint

**Comment by brancz** [comment]
Do you want to specify the bearer token for connecting to a kubernetes apiserver, or to be sent to your targets when scraping @slavakl ?

**Comment by slavakl** [comment]
@galexrt I could, but I'm not sure how I can mount Secret to prometheus pod. It's not in Prometheus spec.

@brancz I want a token that will be send to my targets (my applications)

**Comment by slavakl** [comment]
@brancz It seems that I misread prometheus configuration docs. token is only used to access Kubernetes API. If so, this issue can be closed.

**Comment by brancz** [comment]
Actually both is possible in the Prometheus configuration. Currently we only support setting the bearer token file, which is intended as we don't want it to be specified in plain text in our resource, that would defeat the purpose.

There is some work on kubernetes/kubernetes which automatically mounts secrets in a pod based on the serviceaccount used. I think that would make the most sense here as well.

**Comment by brancz** [comment]
This is actually related to #250, and we are aiming to fix this in the next release.

**Comment by brancz** [comment]
As #264 is merged it is now possible to mount custom secrets for bearer tokens for example. Closing here.

**Comment by slavakl** [comment]
@brancz, perfect! Thanks a lot!
