### ISSUE TITLE
Changes mentioned in release are missing from the release archive

### ISSUE THREAD

**Issue by szymonpk** [coreos/prometheus-operator#2510]
**What did you do?**

1. Downloaded [latest tar.gz for 0.29](https://github.com/coreos/prometheus-operator/releases/tag/v0.29.0)
1. And for example look for alertmanager container version (other things from the changelog are missing as well):

        $ tar xvOf prometheus-operator-0.29.0.tar.gz prometheus-operator-0.29.0/contrib/kube-prometheus/manifests/alertmanager-alertmanager.yaml | grep version

**What did you expect to see?**

According to 0.29 changelog it should be `v0.16.1`.

**What did you see instead? Under which circumstances?**

`v0.16.0`

```
$ tar xvOf prometheus-operator-0.29.0.tar.gz prometheus-operator-0.29.0/contrib/kube-prometheus/manifests/alertmanager-alertmanager.yaml | grep version
prometheus-operator-0.29.0/contrib/kube-prometheus/manifests/alertmanager-alertmanager.yaml
  version: v0.16.0
```

This is only the example, various releases are missing other things mentioned in the changelog. I went through four latest ones (from 0.26.0 to 0.29.0) and I have noticed missing bits and pieces (prometheus-operator 0.28.0 image in 0.29.0 release). Is something wrong with release script? I am not sure how it is done is it some kind of race condition? Are the manifests generated after release?

Other example:
```
$ tar xvOf prometheus-operator-0.29.0.tar.gz prometheus-operator-0.29.0/contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml | grep "image:"
prometheus-operator-0.29.0/contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
        image: quay.io/coreos/prometheus-operator:v0.28.0
```

**Environment**

* Prometheus Operator version: **v0.29.0**
* Kubernetes version information: n/a
* Kubernetes cluster kind: n/a
* Manifests: n/a
* Prometheus Operator Logs: n/a

**Comment by metalmatze** [comment]
Sorry for the confusion. Let me explain:

The Prometheus Operator has version that are released on a regular basis. Whenever we create a new release this is _only_ referencing the Prometheus Operator itself. Most likely you will see it show up as the version number that the container is running as.
Inside the same repository, we have the kube-prometheus project and that is not versioned. So for that project we don't provide any releases and you should simply use what's on `master`.

In the future we plan to extract kube-prometheus out of this repository and start versioning it as well.

Le me know if you still have questions.

**Comment by szymonpk** [comment]
OK, now it makes sense! Sorry for invalid ticket then :( Maybe I could add this hmm, let say warning to https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus?

**Comment by metalmatze** [comment]
No worries the community is not to blame! We explain that every other week and are aware of the situation.
Yes, we should add it to the section and everywhere else it makes sense. I wouldn't even mind having it in multiple places, if necessary/easier.

Would you like to do a PR on that? That would be really helpful! :+1:

**Comment by szymonpk** [comment]
I have created #2514, if you have any comments we can continue there.
