### ISSUE TITLE
Thanos gossip deprecated

### ISSUE THREAD

**Issue by mleklund** [coreos/prometheus-operator#2517]
Thanos has deprecated the gossip clustering.  Wanted to make sure maintainers were aware of the impending change.

see:
https://github.com/improbable-eng/thanos/blob/master/docs/proposals/approved/201809_gossip-removal.md

https://github.com/improbable-eng/thanos/issues/734

**Comment by metalmatze** [comment]
Thank you for notifying us.
Frederic, one of the Prometheus Operator developers/maintainers, is now one of the maintainers of Thanos too. We're in close contact with the Thanos developers and follow its development closely.

I'll close this and once we need to change the Operator for the next Thanos version we'll simply create a new issue or better - a PR. :relaxed:

**Comment by squat** [comment]
Thanks for the heads up :) we'll need to update our API types, jsonnet, and docs to get rid of the peers field and add the new relevant FileSD stuff.

**Comment by brancz** [comment]
What @squat said :100: . I personally don't think this needs any integration in the Prometheus Operator, as all of this can be generated via jsonnet. Only the ruler component might need some integration eventually, but that's tracked in #2288.

**Comment by benjaminhuo** [comment]
Hi @squat @brancz and @metalmatze , seems that I still got gossip style manifest generated in the kube-prometheus project, just wondering if the changes to support thanos service discovery available now?

![Snip20190507_39](https://user-images.githubusercontent.com/18525465/57297749-08eb7500-7103-11e9-834b-7506ee82c2c4.png)

![Snip20190507_40](https://user-images.githubusercontent.com/18525465/57297765-11dc4680-7103-11e9-8118-923ef3c777ca.png)

Thanks
Ben

**Comment by metalmatze** [comment]
No, we have not yet worked on this. Feel free to work on PRs for the necessary changes.

**Comment by brancz** [comment]
From what I understand this mostly means removing the flag from the current prometheus operator integration, more difficult is how can we enable the Querier to discover the stores. Maybe DNS discovery is sufficient though. It will need a little bit of investigation.

**Comment by benjaminhuo** [comment]
ok, I'll think about it.
From [Thanos Query yaml](https://github.com/improbable-eng/thanos/blob/master/tutorials/kubernetes-demo/manifests/thanos-querier.yaml) , possible should allow Querier to add multiple --store args ?

And then add --cluster.disable to querier, store, ruler, sidecar, remove other cluster args 

Ben

**Comment by benjaminhuo** [comment]
@brancz , looks like the [thanos sidecar --cluster.address args](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L682)  should be removed from prometheus operator thanos code, right?

And if gossip will not be supported anymore, maybe more code should be removed from the sidecar code ? for example:

https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L687
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L690
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L693
https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go#L316
https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go#L346
https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go#L349

**Comment by brancz** [comment]
Cluster peers and advertise address can be removed yes, the GRPC advertise address needs to stay, as the querier still communicates with the store API.

> And if gossip is deprecated, maybe more code should be removed from the sidecar args ?
> If we still need to support gossip, then a switch is needed to turn it on/off

As gossip is being removed entirely, I see no value it having it stick around in this experimental API, so always off I'd say.

**Comment by benjaminhuo** [comment]
The [thanos sidecar doc](https://github.com/improbable-eng/thanos/blob/master/docs/components/sidecar.md) mentioned that :
![Snip20190510_95](https://user-images.githubusercontent.com/18525465/57537982-f9299600-7379-11e9-9af2-69818cf5a826.png)

So maybe the querier can comm with the store api by specifying --store args?
![Snip20190510_96](https://user-images.githubusercontent.com/18525465/57538181-6e956680-737a-11e9-957d-e781b51d3ce8.png)

**Comment by brancz** [comment]
Good catch, sorry I was confusing `grpc-address` with `grpc-advertise-address`. You're absolutely right good catch! We should convert `grpc-advertise-address` to just `grpc-address`.
