### ISSUE TITLE
Set CRD validation spec type to object for kubernetes v1.14

### ISSUE THREAD

**Issue by mingfang** [coreos/prometheus-operator#2518]
Kubernetes v1.14 added feature to publish CRDs as openapi https://github.com/kubernetes/kubernetes/pull/71192

However as discussed here https://github.com/kubernetes/kube-openapi/issues/97 and my test cases here https://github.com/mingfang/kubernetes-crd-test shows that the spec type must be set to object for the openapi to work completely.

Looks likes this is one example of the place to change it.
https://github.com/coreos/prometheus-operator/blob/773090e44e162e9508de0073efefc1152e6cf3d9/pkg/apis/monitoring/v1/openapi_generated.go#L529

**Comment by squat** [comment]
As its name implies, this file is automatically generated using the openapi-gen tool. Is there a special annotation we need to produce a spec with `type: object`?

**Comment by mingfang** [comment]
try adding Type attribute with value "object" to SchemaProps here https://github.com/coreos/prometheus-operator/blob/773090e44e162e9508de0073efefc1152e6cf3d9/pkg/apis/monitoring/v1/openapi_generated.go#L532

Based on what I see here https://github.com/go-openapi/spec/blob/53d776530bf78a11b03a7b52dd8a083086b045e5/schema.go#L165

**Comment by squat** [comment]
This is a generated file so every time someone runs `make` that manual change would be overwritten. Ideally this would be set automatically during generation by specifying an annotation on the types.go.

Short of that, we'd need some Makefile solution to add the field in after generation. Another hack could be to add it in here: https://github.com/coreos/prometheus-operator/blob/master/pkg/k8sutil/k8sutil.go#L183:L195. Neither of those are really nice.

**Comment by brancz** [comment]
This still seems like something we want to look into.

**Comment by pgier** [comment]
I believe this was fixed in #2570.  For example, the spec type of service monitor crd was changed to `object` here: https://github.com/coreos/prometheus-operator/pull/2570/files#diff-441b9c1e9f8f49b2aabc978158ced2b9
@mingfang is there anything else to do on this or should this be closed?

**Comment by brancz** [comment]
I believe that’s correct. Closing here, but if anyone feels that this should continue to be open please feel free to comment or create a new issue.

**Comment by mingfang** [comment]
@pgier LGTM. Closing.
