### ISSUE TITLE
kube-prometheus installed failed on minikube

### ISSUE THREAD

**Issue by quakelee** [coreos/prometheus-operator#2519]
**What did you do?**
Install prometheus on minikube by kube-prometheus

**What did you expect to see?**
kube-prometheus installed

**What did you see instead? Under which circumstances?**
After I create new minikube cluster, I tried to install kube-promethues on it
kubectl create -f manifests/
namespace/monitoring created
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
clusterrole.rbac.authorization.k8s.io/prometheus-operator created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
deployment.apps/prometheus-operator created
service/prometheus-operator created
serviceaccount/prometheus-operator created
servicemonitor.monitoring.coreos.com/prometheus-operator created
alertmanager.monitoring.coreos.com/main created
secret/alertmanager-main created
service/alertmanager-main created
serviceaccount/alertmanager-main created
servicemonitor.monitoring.coreos.com/alertmanager created
secret/grafana-datasources created
configmap/grafana-dashboard-k8s-cluster-rsrc-use created
configmap/grafana-dashboard-k8s-node-rsrc-use created
configmap/grafana-dashboard-k8s-resources-cluster created
configmap/grafana-dashboard-k8s-resources-namespace created
configmap/grafana-dashboard-k8s-resources-pod created
configmap/grafana-dashboard-nodes created
configmap/grafana-dashboard-persistentvolumesusage created
configmap/grafana-dashboard-pods created
configmap/grafana-dashboard-statefulset created
configmap/grafana-dashboards created
deployment.apps/grafana created
service/grafana created
serviceaccount/grafana created
servicemonitor.monitoring.coreos.com/grafana created
clusterrole.rbac.authorization.k8s.io/kube-state-metrics created
clusterrolebinding.rbac.authorization.k8s.io/kube-state-metrics created
deployment.apps/kube-state-metrics created
role.rbac.authorization.k8s.io/kube-state-metrics created
rolebinding.rbac.authorization.k8s.io/kube-state-metrics created
service/kube-state-metrics created
serviceaccount/kube-state-metrics created
servicemonitor.monitoring.coreos.com/kube-state-metrics created
clusterrole.rbac.authorization.k8s.io/node-exporter created
clusterrolebinding.rbac.authorization.k8s.io/node-exporter created
daemonset.apps/node-exporter created
service/node-exporter created
serviceaccount/node-exporter created
servicemonitor.monitoring.coreos.com/node-exporter created
clusterrole.rbac.authorization.k8s.io/prometheus-adapter created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-adapter created
clusterrolebinding.rbac.authorization.k8s.io/resource-metrics:system:auth-delegator created
clusterrole.rbac.authorization.k8s.io/resource-metrics-server-resources created
configmap/adapter-config created
deployment.apps/prometheus-adapter created
rolebinding.rbac.authorization.k8s.io/resource-metrics-auth-reader created
service/prometheus-adapter created
serviceaccount/prometheus-adapter created
clusterrole.rbac.authorization.k8s.io/prometheus-k8s created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-k8s created
prometheus.monitoring.coreos.com/k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s-config created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s-config created
role.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s created
prometheusrule.monitoring.coreos.com/prometheus-k8s-rules created
service/prometheus-k8s created
serviceaccount/prometheus-k8s created
servicemonitor.monitoring.coreos.com/prometheus created
servicemonitor.monitoring.coreos.com/kube-apiserver created
servicemonitor.monitoring.coreos.com/coredns created
servicemonitor.monitoring.coreos.com/kube-controller-manager created
servicemonitor.monitoring.coreos.com/kube-scheduler created
servicemonitor.monitoring.coreos.com/kubelet created
Error from server (AlreadyExists): error when creating "manifests/prometheus-adapter-apiService.yaml": apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io" already exists

**Environment**

* Prometheus Operator version:

	773090e44e162e9508de0073efefc1152e6cf3d9

* Kubernetes version information:

	kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:55Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	minikube delete && minikube start --memory=8192 --bootstrapper=kubeadm --extra-config=kubelet.authentication-token-webhook=true --extra-config=kubelet.authorization-mode=Webhook --extra-config=scheduler.address=0.0.0.0 --extra-config=controller-manager.address=0.0.0.0
🔥  Deleting "minikube" from virtualbox ...
💔  The "minikube" cluster has been deleted.
😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ kubelet.authentication-token-webhook=true
    ▪ kubelet.authorization-mode=Webhook
    ▪ scheduler.address=0.0.0.0
    ▪ controller-manager.address=0.0.0.0
🚜  Pulling images required by Kubernetes v1.13.4 ...
load: 2.50  cmd: minikube-darwin- 96456 running 4.03u 8.93s
🚀  Launching Kubernetes v1.13.4 using kubeadm ...
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

* Manifests:

manifests/prometheus-adapter-apiService.yaml

* Prometheus Operator Logs:

Error from server (AlreadyExists): error when creating "manifests/prometheus-adapter-apiService.yaml": apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io" already exists

* My question
From my investigation, the minikube registered a apiservice with same name "v1beta1.metrics.k8s.io" like below 
kubectl get apiservice|grep v1beta1.metrics.k8s.io
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        3m

the content in manifests/prometheus-adapter-apiService.yaml is conflict with it.
What should I do? Should I delete minikube metrics-server and replace with prometheus-adapter? Or rename the prometheus apiservice's name?

Thanks,

Xin

**Comment by squat** [comment]
Hi Xin,

> What should I do? Should I delete minikube metrics-server and replace with prometheus-adapter? Or rename the prometheus apiservice's name?

This is really up to you. Indeed Metrics Server is already providing the metrics.k8s.io API. It does not make really sense to run both Metrics Server and Prometheus Adapter, so you can pick which one you prefer.

If you were to simply rename the Prometheus Adapter apiservice's name, then nothing would be able to consume the API it is providing, so don't do that.

Just know that if you _do_ choose to use Prometheus Adapter, then in addition to changing the apiservice you should probably also delete the Metrics Server deployment, since nothing will be consuming its API.

**Comment by brancz** [comment]
You can disable the metrics-server plugin in minikube, and this error should go away.

**Comment by quakelee** [comment]
Hi guys, 
Thank you for your explain, and I have a suggestion about this, add a notice in ReadMe about this issue would be better.
Thanks for your help!

Xin

**Comment by brancz** [comment]
Agreed we should add it to the readme.

**Comment by brancz** [comment]
I opened #2527 to address this. Thanks for bringing it up @quakelee!

**Comment by StevenACoffman** [comment]
Uh... so wait, for those of us running kubernetes clusters but not using minikube (like AWS eks), does it make sense to run metrics-server and the Prometheus Adapter?
Can Prometheus Adapter make the cluster autoscaler work?

**Comment by metalmatze** [comment]
> Uh... so wait, for those of us running kubernetes clusters but not using minikube (like AWS eks), does it make sense to run metrics-server and the Prometheus Adapter?

No, you can't run both. It is one one of both. They both implement the same APIService in Kubernetes.

**Comment by StevenACoffman** [comment]
Thanks! It might be good to make a more general note somewhere to show more universal relevance.
