### ISSUE TITLE
Warning  Unhealthy  6m (x7 over 7m)   kubelet, training-master01  Liveness probe failed: Get http://192.168.0.105:9093/api/v1/status: dial tcp 192.168.0.105:9093: connect: connection refused

### ISSUE THREAD

**Issue by guoyingying12** [coreos/prometheus-operator#2520]
env:
kubernetes-v1.11.1
prometheus-operator-0.23.2

problem:
#kubectl describe pod alertmanager-main-2 -n monitoring

  Warning  Unhealthy  16m (x7 over 17m)   kubelet, training-master01  Liveness probe failed: Get http://192.168.0.105:9093/api/v1/status: dial tcp 192.168.0.105:9093: connect: connection refused
  Warning  Unhealthy  7m (x117 over 17m)  kubelet, training-master01  Readiness probe failed: Get http://192.168.0.105:9093/api/v1/status: dial tcp 192.168.0.105:9093: connect: connection refused
  Warning  BackOff    2m (x12 over 4m)    kubelet, training-master01  Back-off restarting failed container

Can you help me?

**Comment by squat** [comment]
@guoyingying12 can you please post the logs from your failing alertmanager pod? Also, are all alertmanager pods failing their liveness probes or just one?

**Comment by guoyingying12** [comment]
only one fail.
env:
master01: alertmanager is faild
master02: alertmanager is success
node01:  alertmanager is success

logs:
#  kubectl logs alertmanager-main-2 -n monitoring 
     Error from server (BadRequest): a container name must be specified for pod alertmanager-main-2, choose one of: [alertmanager config-reloader]

"alertmanager" container logs:
# kubectl logs alertmanager-main-2 -c alertmanager -n monitoring 
level=info ts=2019-04-01T01:11:04.635447093Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.0, branch=HEAD, revision=462c969d85cf1a473587754d55e4a3c4a2abc63c)"
level=info ts=2019-04-01T01:11:04.635613399Z caller=main.go:175 build_context="(go=go1.10.3, user=root@bec9939eb862, date=20180622-11:58:41)"

"config-reloader" container logs:
# kubectl logs alertmanager-main-2 -c config-reloader -n monitoring

**Comment by guoyingying12** [comment]
"config-reloader" container didn't have logs

**Comment by guoyingying12** [comment]
> 
> 
> @guoyingying12 can you please post the logs from your failing alertmanager pod? Also, are all alertmanager pods failing their liveness probes or just one?

hi~

only one fail.
env:
master01: alertmanager is faild
master02: alertmanager is success
node01: alertmanager is success

logs:
kubectl logs alertmanager-main-2 -n monitoring

 Error from server (BadRequest): a container name must be specified for pod alertmanager-main-2, choose one of: [alertmanager config-reloader]

"alertmanager" container logs:
kubectl logs alertmanager-main-2 -c alertmanager -n monitoring

level=info ts=2019-04-01T01:11:04.635447093Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.0, branch=HEAD, revision=462c969d85cf1a473587754d55e4a3c4a2abc63c)"
level=info ts=2019-04-01T01:11:04.635613399Z caller=main.go:175 build_context="(go=go1.10.3, user=root@bec9939eb862, date=20180622-11:58:41)"

"config-reloader" container didn't have logs
kubectl logs alertmanager-main-2 -c config-reloader -n monitoring

**Comment by brancz** [comment]
Could you please make sure to update to latest versions of everything? I would like to avoid situations where the inability to create the gossip mesh caused the process to go out of ready state.

**Comment by guoyingying12** [comment]
> 
> 
> Could you please make sure to update to latest versions of everything? I would like to avoid situations where the inability to create the gossip mesh caused the process to go out of ready state.

hi~ 
   kubernetes  1.11.1
   prometheus 0.23.2

**Comment by brancz** [comment]
That’s not latest, v0.29.0 is latest of the Prometheus Operator, and v0.16.1 is latest of Alertmanager.

**Comment by brancz** [comment]
Did that solve your issue?

**Comment by guoyingying12** [comment]
No,I want to solve the reinstallation problem by another way.
