### ISSUE TITLE
Possible node:node_disk_saturation:avg_irate mis-calculation ?

### ISSUE THREAD

**Issue by nabadger** [coreos/prometheus-operator#2525]
Ref: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml

Should these recording rules be dividing by 1000? It looks like the output value is expected to be in seconds (which we already have in the newer version, where as previous metrics were `ms`).

Current
```
 expr: |
        avg(irate(node_disk_io_time_weighted_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]) / 1e3)
      record: :node_disk_saturation:avg_irate
    - expr: |
        avg by (node) (
          irate(node_disk_io_time_weighted_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]) / 1e3
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
        )
      record: node:node_disk_saturation:avg_irate
```

Previous:

```
  - expr: |
      avg(irate(node_disk_io_time_ms{job="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]) / 1e3)
    record: :node_disk_utilisation:avg_irate
  - expr: |
      avg by (node) (
        irate(node_disk_io_time_ms{job="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]) / 1e3
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
    record: node:node_disk_utilisation:avg_irate
```

**Comment by brancz** [comment]
You're totally right! We just use the kubernetes-mixin to define these: https://github.com/kubernetes-monitoring/kubernetes-mixin

Could you fix it there? Then we can bump the dependency here and fix it :slightly_smiling_face:

**Comment by nabadger** [comment]
Sure will do thanks

**Comment by brancz** [comment]
Awesome, thank you!

**Comment by nabadger** [comment]
Cool, there's a PR for that over in the kubernetes-mixin repo: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/181

**Comment by brancz** [comment]
Merged :) now we just need to update the dep and re-generate. You can find the steps here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#contributing

Just start in the `contrib/kube-prometheus/` directory with step 3.
