### ISSUE TITLE
please provide container based on alpine

### ISSUE THREAD

**Issue by reachlin** [coreos/prometheus-operator#2530]
I found operator is based on busybox which has too many security issues and is very difficult to fix. On the other hand, alpine is much better.

Please provide an image based on alpine for security compliance requirements.

**Comment by brancz** [comment]
If you have special security compliance requirements, please build your own images. Do you have any examples of existing issues with this image, if so we’re more than happy to try and fix them.

**Comment by reachlin** [comment]
it's just busybox has too many tools pre-installed that may cause problems. anyway, thx.
