### ISSUE TITLE
prometheus v2.7.1 does not support storage.tsdb.retention

### ISSUE THREAD

**Issue by bluecarrife** [coreos/prometheus-operator#2533]
In prometheus v2.7.1, storage.tsdb.retention is DEPRECATED;but for now, the master branches does not support the new arg 【storage.tsdb.retention.time】; when this arg can bu supported?

**Comment by brancz** [comment]
@paulfantom you want to give this a shot? All we need to do is starting from v2.7.0 or higher use the new flag and only below that use the old (now deprecated) flag.

**Comment by paulfantom** [comment]
Sure, it is in https://github.com/coreos/prometheus-operator/pull/2534

**Comment by paulfantom** [comment]
This took some time but as of now it is included in master branch.
