### ISSUE TITLE
**Config-reloader of alertmanager is crashing**

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2540]
I found config-reloader of alertmanager is getting terminated. From describe pod what I found is :

```
State:          Running
      Started:      Mon, 01 Apr 2019 20:29:10 +0000
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod707dc71b-54bc-11e9-89c4-0a77428fa80c/ad0657d5a36dc7cfe7552bafb9d8ac1d6aeb5bc6d220919a19524b0d8a77d7cd/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
      Exit Code:    128
```

I used HELM chart to install Prometheus-operator on AWS EKS.

Helm chart version:
prometheus-operator-1.1.0 0.26.0

How to fix it? I saw others were facing the same issue. Is there any fix or workaround as of now?

**Comment by brancz** [comment]
The fixed version has been released, I think you just need to update to latest.

**Comment by vrathore18** [comment]
@brancz I am already using stable helm version. could you confirm the version name on which this issue is fixed?

**Comment by brancz** [comment]
Please refer to the upstream charts repo and ask there, as we don't maintain the charts I can't help you.

**Comment by vsliouniaev** [comment]
Current Helm chart version is 5.0.0+

**Comment by brancz** [comment]
Closing here, should the problem persist with the new release feel free to comment.
