### ISSUE TITLE
Prometheus-server liveness fails on K8S port-forwarding with an intensive request.

### ISSUE THREAD

**Issue by Gangareddy** [coreos/prometheus-operator#2546]
**What happened?**
After port-forwarding to Prometheus-server pod on kubernetes, I tried some intensive promQL queries. The pod started to fail on liveness failure.

**Did you expect to see some different?**
I expect pod to not fail on liveness failure.

**How to reproduce it (as minimally and precisely as possible)**:
 port-forwarding to Prometheus-server pod on kubernetes,
then try some intensive promQL queries on prometheus-server

**Environment**
Kubernetes , Azure

* Prometheus Operator version:
Didn't have this problem when I was using helm charts for Prometheus as deployments  (2/2 pods )
Encountered when trying out Prometheus-operator. (3/3 with alert-rule config reloader)

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

   Azure Kuberntes Service
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
Liveness check failed ( returned 503 on localhost:9090/*/health*/)

```
insert Prometheus Operator logs relevant to the issue here
```
Connection reset by peer ( X.X.X.X:y to podIp:9090) 
**Anything else we need to know?**:

I'm speculating that there is some sort of blocking connection which makes pods fail on liveness probes when port-forwarding is done for an intensive request ( > 10s  for response).

**Comment by brancz** [comment]
This sounds more like an issue with Prometheus. Could you report it there? (also maybe this is correct as Prometheus seems to not be responsive)
