### ISSUE TITLE
Operator should be able to config external alertmanager.

### ISSUE THREAD

**Issue by tuxknight** [coreos/prometheus-operator#2548]
**What is missing?**
be able to config external alertmanager.

**Why do we need it?**

When we have multi prometheus clusters, such as  three k8s clusters with each prometheus cluster in it and 3 datacenters with one promethues cluster every datacenter,  it  will be better to have only one HA alertmanager cluster to handle all these alerts/silences .

A prometheus federation is not a good solution for it requires additional labels to identify data from each cluster. And all rules/grafana graphs have to be changed.

**Comment by brancz** [comment]
You can use the `additionalAlertManagerConfigs` feature to configure raw Prometheus config for discovering Alertmanagers so you can do whatever topology fits your use case best :slightly_smiling_face: .

**Comment by tuxknight** [comment]
Cool. It works.
Thank you.
