### ISSUE TITLE
how drop target lables [repeating data]

### ISSUE THREAD

**Issue by gouki777** [coreos/prometheus-operator#2549]
hi     
my targets have more targets .  
i want drop service="monitor-prometheus-operator-kubelet" and service="k8s-prometheus-operator-kubelet"  
i want need  service="k8s-prometheus-operator-kubelet" targets.  
i change my config.but no good  
how to do drop k8s-prometheus-operator-kubelet targets. how to do change my config? 
thanks.
<pre>
prometheus-operator
my targets  monitoring/prometheus-operator-kubelet
endpoint="http-metrics" service="k8s-prometheus-operator-kubelet"         #repeating data
endpoint="http-metrics" service="monitor-prometheus-operator-kubelet"  #repeating data
endpoint="http-metrics" service="prometheus-prometheus-operator-kubelet"
------------
my config 
    metricRelabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: drop
      regex: (k8s-prometheus|if-prometheus|).*
      source_labels:
      - __meta_kubernetes_service_name
    path: /metrics/cadvisor
    port: http-metrics
    relabel_configs:
    - action: keep
      regex: prometheus-operator-kubelet
      source_labels: __meta_kubernetes_namespace

</pre>

**Comment by brancz** [comment]
This seems like an odd target to begin with. If you installed this via the helm chart, please talk to the helm chart maintainers, we don't use or maintain the helm charts so we can't help with that topic.

**Comment by gouki777** [comment]
sorry.i know
