### ISSUE TITLE
alertmanager CrashLoopBackOff

### ISSUE THREAD

**Issue by guoyingying12** [coreos/prometheus-operator#2552]
Hello,every guys!
When I used "prometheus-operator" build prometheus, alertmanager is faild that only one.

env:
master01:  alertmanager is faild
master02:  alertmanager is success
node01:   alertmanager is success

**please look picture.**
![图片](https://user-images.githubusercontent.com/32632723/55934147-4e329900-5c62-11e9-9044-696b638563c9.png)

**# kubectl describe pod -n monitoring alertmanager-main-2**
![图片](https://user-images.githubusercontent.com/32632723/55934472-37407680-5c63-11e9-9fc6-e720cece3f97.png)

**# kubectl logs -n monitoring alertmanager-main-2 alertmanager**
level=info ts=2019-04-11T06:08:41.637781884Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.1, branch=HEAD, revision=571caec278be1f0dbadfdf5effd0bbea16562cfc)"
level=info ts=2019-04-11T06:08:41.637940142Z caller=main.go:178 build_context="(go=go1.11.5, user=root@3000aa3a06c5, date=20190131-15:05:40)"

**container "config-reloader" not have logs.**

**Comment by guoyingying12** [comment]
prometheus-operator:0.29.0
kubernetes:1.11.1

**Comment by brancz** [comment]
If you delete the pod completely does that change anything?

**Comment by guoyingying12** [comment]
If I delete the pod alertmanager-main-2,a new pod will restart,but with the same error. 

alermanager-main-2 contains two containers,  alertmanager and config-reloader. I can see by grafana that the container alertmanager is always stopped.
![图片](https://user-images.githubusercontent.com/32632723/56005808-e4b79680-5d04-11e9-8a6d-96be0786596c.png)

**Comment by guoyingying12** [comment]
> 
> 
> If you delete the pod completely does that change anything?

HI~  Can you help me?

**Comment by brancz** [comment]
Seems curious, @mxinden could you have a look at this?

**Comment by brancz** [comment]
@paulfantom @mxinden could this maybe also be the cause of our flakes?

**Comment by mxinden** [comment]
Hi @guoyingying12 ,

Thanks for the report. In order to reproduce this, would you mind giving us some more details:

- Does the crash looping Alertmanager container only ever log a single line?

  >  kubectl logs -n monitoring alertmanager-main-2 alertmanager
level=info ts=2019-04-11T06:08:41.637781884Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.1, branch=HEAD, revision=571caec278be1f0dbadfdf5effd0bbea16562cfc)"
level=info ts=2019-04-11T06:08:41.637940142Z caller=main.go:178 build_context="(go=go1.11.5, user=root@3000aa3a06c5, date=20190131-15:05:40)"

- Inside the [spec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) of the Alertmanager custom resource, can you set the `logLevel` to `debug`?

- Can you post the Alertmanager custom resource here?

- Does this issue persist, even when you remove and recreate the Alertmanager custom resource?

As a note, Alertmanager starts listening on `api/v1/status` relatively late in the startup process. Thus I would expect it to log errors of any failures beforehand.

**Comment by guoyingying12** [comment]
> Thanks for the report. In order to reproduce this, would you mind giving us some more details:
> 
>     * Does the crash looping Alertmanager container only ever log a single line?

HI ~,Sorry,I have been busy recently, and the reply is late.

Only one alertmanager is error.and only ever log a single line.
when I delete the pod alertmanager-main-2,a new pod will restart,but with the same error.

**Comment by mxinden** [comment]
@guoyingying12 Would you mind doing the following steps:

- Inside the [spec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) of the Alertmanager custom resource, can you set the `logLevel` to `debug`?

- Can you post the Alertmanager custom resource here?

- Does this issue persist, even when you remove and recreate the Alertmanager custom resource?

**Comment by guoyingying12** [comment]
> 
> 
> @guoyingying12 Would you mind doing the following steps:
> 
>     * Inside the [spec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) of the Alertmanager custom resource, can you set the `logLevel` to `debug`?
> 
>     * Can you post the Alertmanager custom resource here?
> 
>     * Does this issue persist, even when you remove and recreate the Alertmanager custom resource?

Sorry.   
Can you tell me how to modify the alertmanager custom resource management library.I don't know which yaml file to modify. I'm very sorry.

**Comment by harsh-px** [comment]
Hello @mxinden I'm seeing the same issue on alertmanager. 

prometheus-operator:0.29.0
kubernetes:1.14.2

When alertmanager starts, it just prints 2 info lines as below and then crashes after 2 minutes. I changed the logLevel to debug in the AlertManager resource with no effect.

```
level=info ts=2019-06-06T17:11:30.007373879Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.1, branch=HEAD, revision=571caec278be1f0dbadfdf5effd0bbea16562cfc)"
level=info ts=2019-06-06T17:11:30.007550871Z caller=main.go:178 build_context="(go=go1.11.5, user=root@3000aa3a06c5, date=20190131-15:05:40)"
```

Could you help us with some pointers on how we can debug this further? Thanks !

In my case, the first alertmanager pod itself fails to restarts.

**Comment by 1robroos** [comment]
Same here,
If I have 1 alertmanager, it crashes after approx 2 minutes.
If I have 2 alertmanagers, one of them crashes after approx 2 minutes.
This is on EKS.
Describing that alertmanager pod gives:
```

Warning  Unhealthy               4m53s (x6 over 5m43s)   kubelet, ip-192-168-54-36.us-west-2.compute.internal  Liveness probe failed: Get http://192.168.59.206:9093/-/healthy: dial tcp 192.168.59.206:9093: connect: connection refused
Warning  Unhealthy               4m49s (x13 over 5m49s)  kubelet, ip-192-168-54-36.us-west-2.compute.internal  Readiness probe failed: Get http://192.168.59.206:9093/-/ready: dial tcp 192.168.59.206:9093: connect: connection refused
```

**Comment by brancz** [comment]
cc @simonpasquier do you think you could have a look into this?

**Comment by simonpasquier** [comment]
Sure. Re-reading all the comments, I'm not sure what goes wrong, AlertManager should start the API server very early in the process (eg it doesn't depend on the cluster being settled). Lets start by getting the AlertManager custom resource definition (`kubectl get alertmanager -o yaml`) as well as the generated AlertManager configuration (`oc get secrets alertmanager-main -o "jsonpath={ .data['alertmanager\.yaml'] }" |  base64 -d`).

**Comment by nlamirault** [comment]
I've got the same issue using Prometheus Operator 0.31.1 and Alertmanager 0.18.0
The output logs with logLevel on debug : 

```
$ kubectl -n monitoring logs alertmanager-main-0 -c alertmanager -f            
level=info ts=2019-08-24T16:21:56.924Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=HEAD, revision=1ace0f76b7101cccc149d7298022df36039858ca)"
level=info ts=2019-08-24T16:21:56.924Z caller=main.go:198 build_context="(go=go1.12.6, user=root@868685ed3ed0, date=20190708-14:31:49)"


level=debug ts=2019-08-24T16:22:56.932Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-main-0.alertmanager-operated.monitoring.svc:6783
level=debug ts=2019-08-24T16:22:56.933Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01DK2706N4WJRQE4HRN937PTDF addr=10.8.2.17:6783
level=debug ts=2019-08-24T16:22:58.934Z caller=cluster.go:306 component=cluster memberlist="2019/08/24 16:22:58 [DEBUG] memberlist: TCP-first lookup failed for 'alertmanager-main-0.alertmanager-operated.monitoring.svc:6783', falling back to UDP: dial tcp 10.11.240.10:53: i/o timeout\n"
```

**Comment by simonpasquier** [comment]
It tells me that memberlist (clustering library used by AlertManager) takes a lot of time to resolve the peer's address (eg 1 minute) which explains why AlertManager doesn't start the web server in a timely fashion. After digging into the code, I found out that memberlist does a TCP lookup first and fallbacks to UDP if unsuccessful (eg timeout in your case). The lookup uses `github.com/miekg/dns` undercover which will read DNS configuration from `/etc/resolv.conf`. Can you share its content?

**Comment by chymy** [comment]
I've got the same issue using prometheus-operator-0.34.0, kube-prometheus-0.3.0 and Alertmanager 0.18.0.
`kubectl describe po alertmanager-main-0 -n monitoring` result:
```
  Warning  Unhealthy  4m43s (x117 over 14m)  kubelet, 10.46.179.127  Readiness probe failed: Get http://172.22.235.201:9093/-/ready: dial tcp 172.22.235.201:9093: connect: connection refused
  Warning  BackOff    3m21s                  kubelet, 10.46.179.127  Back-off restarting failed container

```

**Comment by ksiadz** [comment]
Same error. My suspicion as I have other alert manager being installed stand alone from Prometheus operator in the same cluster is probes configuration. My other alert manager has much bigger initialDelaySeconds, periodSeconds and timeoutSeconds. Could we add probes delays configuration in CRD?

**Comment by luconeb** [comment]
Confirmed the same error, the alertmanager container into the pod is failing the probes, goes CrashLoopBackOff so the Service never gets a valid Endpoint:

```  
Warning  Unhealthy  2m25s (x12 over 3m20s)  kubelet, ip-10-11-41-193.us-west-2.compute.internal  Readiness probe failed: Get http://10.11.40.233:9093/-/ready: dial tcp 10.11.40.233:9093: connect: connection refused
  Warning  Unhealthy  2m20s (x7 over 3m20s)   kubelet, ip-10-11-41-193.us-west-2.compute.internal  Liveness probe failed: Get http://10.11.40.233:9093/-/healthy: dial tcp 10.11.40.233:9093: connect: connection refused
```

Set the alertmanagerSpec.logLevel to **debug**, but the logs don't change:

```
level=info ts=2020-08-14T13:17:00.632Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2020-08-14T13:17:00.633Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
```

Mine is a single alertmanager setup through the prometheus operator on **EKS**, alertmanager:v0.21.0, K8S 1.16
Same setup runs fine on vanilla kubernetes (1.18) or even minikube. 

```
> kubectl get alertmanager -o yaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Alertmanager
  metadata:
    annotations:
      meta.helm.sh/release-name: promop
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2020-08-14T12:39:46Z"
    generation: 2
    labels:
      app: prometheus-operator-alertmanager
      app.kubernetes.io/managed-by: Helm
      chart: prometheus-operator-9.3.1
      heritage: Helm
      release: promop
    name: promop-prometheus-operator-alertmanager
    namespace: monitoring
    resourceVersion: "133748993"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/alertmanagers/promop-prometheus-operator-alertmanager
    uid: 05369573-9c39-427f-9f25-0a1857d99c43
  spec:
    baseImage: quay.io/prometheus/alertmanager
    externalUrl: http://promop-prometheus-operator-alertmanager.monitoring:9093
    listenLocal: false
    logFormat: logfmt
    logLevel: debug
    paused: false
    portName: web
    replicas: 1
    retention: 120h
    routePrefix: /
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: promop-prometheus-operator-alertmanager
    tolerations:
    - effect: NoSchedule
      key: nodetype
      operator: Equal
      value: experimental
    version: v0.21.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```
> kubectl get secrets alertmanager-promop-prometheus-operator-alertmanager -o "jsonpath={ .data['alertmanager\.yaml'] }" | base64 -d
global:
  resolve_timeout: 5m
receivers:
- name: "null"
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: "null"
```

**Comment by luconeb** [comment]
This is confirmed to be AlertManager unable to access some resources (can't say which for lack of verbosity).

My setup was running on a specifically tainted node through tolerations, and the problem disappeared when using standard nodes. Clearly that node Alertmanager was trying to run on misses some access. I'll add more details if available.

**Comment by xoxodevops** [comment]
Same problem here too :
Warning  Unhealthy  15m (x6 over 16m)    kubelet, empuls-prodenv-c1-k8node3  Liveness probe failed: Get http://192.168.150.200:9093/-/healthy: dial tcp 192.168.150.200:9093: connect: connection refused
  Warning  Unhealthy  86s (x147 over 16m)  kubelet, empuls-prodenv-c1-k8node3  Readiness probe failed: Get http://192.168.150.200:9093/-/ready: dial tcp 192.168.150.200:9093: connect: connection refused

**Comment by ghorutest** [comment]
Same error. K8s version 1.19.3
```
k get po -n monitoring
NAME                                   READY   STATUS             RESTARTS   AGE
alertmanager-main-0                    2/2     Running            36         4d1h
alertmanager-main-1                    1/2     CrashLoopBackOff   1068       4d1h
alertmanager-main-2                    2/2     Running            35         4d1h
grafana-7f567cccfc-b9h7n               1/1     Running            3          4d1h
kube-state-metrics-54bcf7f7cf-sjmvn    3/3     Running            51         4d1h
node-exporter-8tql4                    2/2     Running            0          4d1h
node-exporter-l4wc9                    2/2     Running            4          4d1h
node-exporter-mfr9w                    2/2     Running            6          4d1h
node-exporter-ps8bx                    2/2     Running            24         4d1h
prometheus-adapter-865cc8dbcd-28jp7    1/1     Running            27         4d1h
prometheus-k8s-0                       3/3     Running            10         4d1h
prometheus-k8s-1                       3/3     Running            7          4d1h
prometheus-operator-5b469f4f66-gg5mj   2/2     Running            29         4d1h
```

```
k describe pod -n monitoring alertmanager-main-1
Name:         alertmanager-main-1
Namespace:    monitoring
Priority:     0
Node:         k8s-worker-3/10.0.0.106
Start Time:   Tue, 27 Oct 2020 17:02:59 +0900
Labels:       alertmanager=main
              app=alertmanager
              controller-revision-hash=alertmanager-main-65c86799b
              statefulset.kubernetes.io/pod-name=alertmanager-main-1
Annotations:  <none>
Status:       Running
IP:           10.244.3.22
IPs:
  IP:           10.244.3.22
Controlled By:  StatefulSet/alertmanager-main
Containers:
  alertmanager:
    Container ID:  docker://6276fc51ceb9c648c49597d7456eaa9e183ed31a04bc461831a337c97880debd
    Image:         quay.io/prometheus/alertmanager:v0.21.0
    Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:24a5204b418e8fa0214cfb628486749003b039c279c56b5bddb5b10cd100d926
    Ports:         9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:    0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --storage.path=/alertmanager
      --data.retention=120h
      --cluster.listen-address=[$(POD_IP)]:9094
      --web.listen-address=:9093
      --web.route-prefix=/
      --cluster.peer=alertmanager-main-0.alertmanager-operated:9094
      --cluster.peer=alertmanager-main-1.alertmanager-operated:9094
      --cluster.peer=alertmanager-main-2.alertmanager-operated:9094
      --cluster.reconnect-timeout=5m
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   level=info ts=2020-10-31T09:48:59.627Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2020-10-31T09:48:59.627Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"

      Exit Code:    2
      Started:      Sat, 31 Oct 2020 18:48:59 +0900
      Finished:     Sat, 31 Oct 2020 18:50:39 +0900
    Ready:          False
    Restart Count:  1065
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-main-db (rw)
      /etc/alertmanager/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from alertmanager-main-token-2h9cc (ro)
  config-reloader:
    Container ID:  docker://bc9762a27cf7ee5db466b6bd6c4c9faae26f293f9f2209f5afd5f6cb1fab9aae
    Image:         jimmidyson/configmap-reload:v0.4.0
    Image ID:      docker-pullable://jimmidyson/configmap-reload@sha256:17d34fd73f9e8a78ba7da269d96822ce8972391c2838e08d92a990136adb8e4a
    Port:          <none>
    Host Port:     <none>
    Args:
      -webhook-url=http://localhost:9093/-/reload
      -volume-dir=/etc/alertmanager/config
    State:       Running
      Started:   Wed, 28 Oct 2020 17:44:14 +0900
    Last State:  Terminated
      Reason:    Error
      Message:   2020/10/28 08:31:37 Watching directory: "/etc/alertmanager/config"

      Exit Code:    2
      Started:      Wed, 28 Oct 2020 17:31:37 +0900
      Finished:     Wed, 28 Oct 2020 17:43:23 +0900
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from alertmanager-main-token-2h9cc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main
    Optional:    false
  alertmanager-main-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  alertmanager-main-token-2h9cc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main-token-2h9cc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  6m6s (x20321 over 3d1h)  kubelet  Readiness probe failed: Get "http://10.244.3.22:9093/-/ready": dial tcp 10.244.3.22:9093: connect: connection refused
  Warning  BackOff    65s (x12834 over 3d1h)   kubelet  Back-off restarting failed container
```

**Comment by wrahmann** [comment]
Is there any workaround or resolution to this problem? Every time I change replica from 1 to 2 or 3, the new alert manager instances keep crashing.

**Comment by sunlintong** [comment]
Same error. At last I found that's my dns server error. After I fixed dns, alertmanager starts without error. But anyway, the alertmanager log didn't refer to any useful log. maybe I should open a issue to alertmanager.

**Comment by umialpha** [comment]
same error, same logs, any update?

**Comment by imransetiadi** [comment]
how to fix? i'am faced same error

**Comment by I2BKeit** [comment]
Hi , I do believe you do not have a enough available resource. Check you disks,  memory.

**Comment by aidan-canva** [comment]
For what it's worth, I hit an issue with the exact same symptoms.  In our environment, we constrain all network requests (including DNS resolutions) using Cilium.  The issue was that the alertmanager Pods were failing to resolve the peer DNS values provided as container args (`--cluster.peer`).

Adding in a suitable NetworkPolicy to allow the DNS traffic resulted in both Pods coming up healthy, without needing to change livenessProbe or readinessProbe config.
