### ISSUE TITLE
Support storage.tsdb.retention.size in PrometheusSpec

### ISSUE THREAD

**Issue by bgagnon** [coreos/prometheus-operator#2563]
When Prometheus is bound to a PersistentVolumeClaim with a fixed size, the size-based retention make more sense than the time-based retention which is unpredictable if time series come and go and data rate is variable.

Realated issues:
* #2433 
* #2533

**Comment by brancz** [comment]
Note that Prometheus retention only deletes full blocks that are fully out of the retention window, so there is still some variability that you have to deal with, but yes generally speaking this is a great feature that we should allow to be made configurable.
