### ISSUE TITLE
Prometheus instance  isn't able to scrape node exporter when they are on the same host

### ISSUE THREAD

**Issue by idobry** [coreos/prometheus-operator#2576]
Hey all,
I deployed Prometheus operator using a chart from the stable repo.
I noticed that I didn't get metrics from a specific node. My cluster own 3 nodes and when Prometheus instance is on node1 I don't see this node1 metrics, only node2 and node3. I tried to deploy Prometheus on node2 and again I wa able to see node1 and node3 but not node2

I'm using kuberenetes 14.1 on prem, using centos 7.3, docker kubelet and kubeadm latest.

I managed to extract a related log from the Prometheus API: "context deadline exceeded" when Prometheus is trying to get metrics from own host node exporter

**Comment by brancz** [comment]
We don't use or maintain the helm charts, please open an issue with them first. This generally sounds like a problem with your setup though not with Prometheus or the node-exporter. Probably a networking configuration, potentially hairpin is not configured correctly.

**Comment by idobry** [comment]
@brancz you are right.
I changed `hostNetwork` to false and everything is working as expected, so the problem is not with prometheus.
