### ISSUE TITLE
Grafana default password

### ISSUE THREAD

**Issue by ArchiFleKs** [coreos/prometheus-operator#258]
**What did you do?**

- Change default admin password with grafana environment variable inside deployment.
- Disabled auth anonymous

**What did you expect to see?**

- Login to grafana and see the default dashboad imported with grafana-watcher

**What did you see instead? Under which circumstances?**

Login with new user password is OK but dashboard are not imported:

```
kubectl -n monitoring logs -f grafana-1648929015-l3crv grafana-watcher                                                      master
2017/04/03 14:00:25 Waiting for Grafana to be available.
2017/04/03 14:00:26 Waiting for Grafana to be available.
2017/04/03 14:00:27 Waiting for Grafana to be available.
2017/04/03 14:00:29 Waiting for Grafana to be available.
2017/04/03 14:00:30 Waiting for Grafana to be available.
2017/04/03 14:00:31 Waiting for Grafana to be available.
```

**Environment**

Kubernetes 1.5.1 on Coreos with Kube-AWS

* Kubernetes version information:
```
	kubectl version                                                                                                             master
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T19:15:41Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kube-aws

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
The user/password needs to be set for the grafana-watcher: 

https://github.com/coreos/prometheus-operator/blob/0ec000c87d49ade4123b21f9414d3b5d9d993051/contrib/grafana-watcher/examples/grafana-bundle.yaml#L68

I can see how having it plain text in there doesn't make a whole lot of sense, we should probably extract that to a secret which is then used as either an environment variable or from disk. As it's done with environment variables in grafana it likely makes most sense to use environment variables in the grafana-watcher as well.

A PR against the grafana-watcher adding the ability to specify user/password from an environment variable would be welcome.

**Comment by maxim28** [comment]
@brancz
Hi, i already used the latest version yaml with credentials, but still has this error "Waiting for Grafana to be available".
Also when i add admin/admin into grafana_url for grafana-watcher, this error still exists.
i run the command `hack/cluster-monitoring/deploy` described in https://github.com/coreos/prometheus-operator/tree/release-0.10/contrib/kube-prometheus without any configuration change

**Comment by maxim28** [comment]
I solved this problem by changing grafana-url from http://localhost:3000 to http://admin:admin@127.0.0.1:3000 and the grafana works.

I also add some logs into grafana-watcher code and found that if i use localhost, which will lead to a strange ip with the following error, but if you call localhost in the container, it will works normally.
```
2017/07/18 07:27:08 Error Get http://admin:admin@localhost:3000/api/datasources: dial tcp 220.250.64.20:3000: i/o timeout
2017/07/18 07:27:09 Waiting for Grafana to be available.
```

**Comment by brancz** [comment]
I think the last bit that you mentioned I have seen unrelated to grafana but in prometheus before where docker messes with the resolution of localhost, what if you just change the url from localhost to 127.0.0.1?
