### ISSUE TITLE
Prometheus resources cannot be declaratively updated.

### ISSUE THREAD

**Issue by therealmitchconnors** [coreos/prometheus-operator#2584]
Once a Prometheus object has been created, it cannot be declaratively updated, as patches require specification of the resource version.

For example:
```
helm template stable/prometheus-operator --name foo | kubectl apply -f
[succeeds]
helm template stable/prometheus-operator --name foo | kubectl apply -f
...
The prometheuses "foo" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
[fails]
```
I dropped a note in the slack channel to see if perhaps this behavior was intended, but it seems rather quiet today.

Using Prometheus operator v 2.9.1 with helm chart version 5.5.0.

**Comment by brancz** [comment]
What version of kubernetes are you using? I'm not seeing this behavior.

**Comment by therealmitchconnors** [comment]
1.11.8-gke.6

I had not considered that this could be K8s related.  I will upgrade the cluster to 1.12 and report back.

**Comment by therealmitchconnors** [comment]
After upgrading to 1.12.7-gke.10, I see no change in behavior.

**Comment by therealmitchconnors** [comment]
This seems to have been environmental.  I deleted the prometheus named "foo" and tried again, and now I can run and rerun the `helm template | kubectl apply` command without any difficulty.
