### ISSUE TITLE
operator uses deprecated APIs targeted for removal in k8s 1.16

### ISSUE THREAD

**Issue by liggitt** [coreos/prometheus-operator#2592]
The prometheus operator is used by kubernetes CI.

A [canary PR](https://github.com/kubernetes/kubernetes/pull/70672) that disables the apps/v1beta1, apps/v1beta2, and workload extensions/v1beta1 resources failed with [prometheus operator errors](https://github.com/kubernetes/kubernetes/pull/70672#issuecomment-490398939).

See the announcement around timeframes for removal of these resources: https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc

Please update to the GA resources to ensure the operator continues to work properly (and to unblock kube CI that is verifying functional clusters with deprecated workload APIs disabled)

cc @mm4tt

**Comment by metalmatze** [comment]
Thanks for notifying. We need to update in a few places, I believe. 
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L23 for Prometheus and https://github.com/coreos/prometheus-operator/blob/master/pkg/alertmanager/statefulset.go#L23 for Alertmanager.

Additionally we are working on generating new kube-prometheus manifests from a new version of ksonnet that finally has the GA resources available.

**Comment by liggitt** [comment]
> Additionally we are working on generating new kube-prometheus manifests from a new version of ksonnet that finally has the GA resources available.

the GA workload resources have been available since 1.9 (december 2017)... as a data point, when did support for them make it into the tools you're using?

**Comment by brancz** [comment]
The ksonnet tooling hasn't yet, hence we started that work. We're expecting that to merge soon though.

**Comment by mm4tt** [comment]
Hey Folks,

Allowed myself to send https://github.com/coreos/prometheus-operator/pull/2593 to speed up the migration. Would appreciate if someone can take a look.

**Comment by metalmatze** [comment]
With #2593 merged and looking the kubernetes-dev post, we still need to update our Ingress resources. However that new API is available with Kubernetes 1.14+ and will be deprecated in 1.18. I guess we should still wait until 1.16 or 1.17 to do the switch not to break to many people while they update.

**Comment by liggitt** [comment]
> However that new API is available with Kubernetes 1.14+ and will be deprecated in 1.18. I guess we should still wait until 1.16 or 1.17 to do the switch not to break to many people while they update.

if you wait until 1.16 is released to switch to networking.k8s.io/v1beta1 Ingress, you can support all current kube releases (1.14, 1.15, 1.16). After 1.16 is released is also when I'll likely open a canary PR for disabling extensions/v1beta1 Ingress (targeting 1.18) and will need a prometheus-operator image that does not depend on extensions/v1beta1.

**Comment by brancz** [comment]
> That makes sense. If you wait until 1.16 is released to switch to networking.k8s.io/v1beta1 Ingress, you can support all current kube releases (1.14, 1.15, 1.16). After 1.16 is released is also when I'll likely open a canary PR for disabling extensions/v1beta1 Ingress (targeting 1.18) and will need a prometheus-operator image that does not depend on extensions/v1beta1.

Thanks for the heads up! While this doesn't affect the prometheus-operator directly, it does indirectly, as Prometheus currently uses that API. I'll open an issue.
