### ISSUE TITLE
Install with current bundle.yaml fails (ErrImagePull)

### ISSUE THREAD

**Issue by douglas-reid** [coreos/prometheus-operator#2598]
It appears the `bundle.yaml` files were updated before the image they were updated to point to was created and published.

Ideally, the update to `bundle.yaml` would happen after the image exists.

**What happened?**

Tried installing operator directly from bundle at HEAD: 

`kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml`

Checking on the pod afterwards, I see "ErrImagePull".  Issuing describe on the pod:

`Failed to pull image "quay.io/coreos/prometheus-operator:v0.30.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/coreos/prometheus-operator:v0.30.0 not found`

Sure enough, that image doesn't exist at that repository.

**Comment by brancz** [comment]
Sorry about this, we started a release today, but then didn't finish it up. We'll fix this on Monday :) 

cc @metalmatze

**Comment by brancz** [comment]
Actually the team just finished the release, so now this should work just fine :)

**Comment by brancz** [comment]
sorry for the inconvenience

**Comment by douglas-reid** [comment]
good to know, thanks!
