### ISSUE TITLE
Enable access via `kubectl proxy`

### ISSUE THREAD

**Issue by codebje** [coreos/prometheus-operator#26]
When the kubes cluster isn't running locally, it's pretty common to need to access it via the apiserver's proxy mechanism - this is particularly useful for "infrastructure" tools, as the authentication mechanism of Kubernetes is applied.

However, the Prometheus UI uses absolute URLs with what I would go so far as to call reckless abandon, and doesn't work at all behind any proxy which doesn't rewrite all requests.

It can be made to work by adding these two arguments to prometheus:

    -web.external-url=http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/prometheus-k8s:web/
    -web.route-prefix=/

And then the UI can be reached by running `kubectl proxy` and browsing to the URL above.

**Comment by brancz** [comment]
Great suggestion! How do you imagine to configure this? Maybe we can allow custom flags to be defined in the Prometheus Spec?

**Comment by brancz** [comment]
Or maybe rather allow access via an Ingress object and then restrict the access to the Ingress endpoint to a subnet/addresses? @fabxc and I were also discussing that we might be able to secure all components in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus) behind in a common way using [dex](https://github.com/coreos/dex).

**Comment by codebje** [comment]
I'd imagine it would be a more sensible default than the current one, which only works if the nodes are directly reachable.  I can really only see two ways you'd want to expose it: either as an admin-only interface (in which case `kubectl proxy` is effective) or as a service via an Ingress.

Having a mechanism in the Prometheus spec to select between those would be useful, but I'm not familiar enough with operators and third party specs to know how you might do that.

**Comment by brancz** [comment]
@fabxc do you have an opinion about this? I have the feeling that allowing custom flags might be the best solution, just to not be opinionated about how to expose the Prometheus UI, however, it also gives up guarantees we had in terms of us controlling the setup.

**Comment by bguthrie** [comment]
👍 to the feature request. I like the idea of allowing custom flags but I'm no expert.
