### ISSUE TITLE
helm install opsgoodness/prometheus-operator causes rbac error on k8s 1.5.5

### ISSUE THREAD

**Issue by dmcnaught** [coreos/prometheus-operator#260]
**What did you do?**
```bash
helm repo add opsgoodness http://charts.opsgoodness.com
helm install opsgoodness/prometheus-operator
```
**What did you expect to see?**
adding prometheus operator

**What did you see instead? Under which circumstances?**
>>>
--- github/coreos » helm install opsgoodness/prometheus-operator
Error: release plinking-numbat failed: clusterroles.rbac.authorization.k8s.io "plinking-numbat-prometheus-operator" is forbidden: attempt to grant extra privileges: [{[*] <nil> [] [configmaps] [] []} {[*] <nil> [] [secrets] [] []} {[delete] <nil> [] [pods] [] []} {[list] <nil> [] [pods] [] []} {[create] <nil> [] [services] [] []} {[get] <nil> [] [services] [] []} {[update] <nil> [] [services] [] []} {[create] <nil> [] [endpoints] [] []} {[get] <nil> [] [endpoints] [] []} {[update] <nil> [] [endpoints] [] []} {[list] <nil> [] [nodes] [] []} {[watch] <nil> [] [nodes] [] []} {[*] <nil> [apps] [statefulsets] [] []} {[create] <nil> [extensions] [thirdpartyresources] [] []} {[get] <nil> [extensions] [thirdpartyresources] [] []} {[*] <nil> [monitoring.coreos.com] [alertmanagers] [] []} {[*] <nil> [monitoring.coreos.com] [prometheuses] [] []} {[*] <nil> [monitoring.coreos.com] [servicemonitors] [] []}] user=&{system:serviceaccount:kube-system:default 62998b8b-1407-11e7-9890-0659fdf912f6 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[{[create] <nil> [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] <nil> [] [] [] [/version /api /api/* /apis /apis/*]}] ruleResolutionErrors=[]

**Environment**
Created on AWS with kops 1.5.3, k8s 1.5.5
* Kubernetes version information:
```bash
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

kops 1.5.3

* Manifests:

* Prometheus Operator Logs:

**Comment by mgoodness** [comment]
The root cause is that Tiller (the server-side Helm component) doesn't have the permissions it needs. Give [this](https://gist.github.com/mgoodness/bd887830cd5d483446cc4cd3cb7db09d) a try, then re-deploy the chart.

**Comment by dmcnaught** [comment]
Thanks @mgoodness - the link says for K8s 1.6, but we are running on 1.5
I got this:
```bash
--- coreos/prometheus-operator » kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller

Error: unknown flag: --clusterrole
```

**Comment by brancz** [comment]
@dmcnaught you can also create the `ClusterRoleBinding` from a yaml manifest, as seen in https://github.com/coreos/prometheus-operator/blob/92b5a896d2265f89caa1f87240291ba623ea8a99/contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml

I'll close here for now, let us know if you run into another problem. Also note that the helm charts are in a very early stage, so they are likely to be incomplete and/or erroneous.

PRs welcome :slightly_smiling_face:

**Comment by brancz** [comment]
@mgoodness can you just drop a note in the helm readme stating how to give the tiller pod cluster admin rights for both 1.5 and 1.6? Thanks!
