### ISSUE TITLE
How to set storage.local.memory-chunks?

### ISSUE THREAD

**Issue by DORcode** [coreos/prometheus-operator#2602]
When deployed prometheus with prometheus-operator, How to set storage.local.memory-chunks?

**Comment by brancz** [comment]
I'd be happy to see this added :slightly_smiling_face: do you want to open a PR?

**Comment by mickael-carl** [comment]
Isn't this deprecated since [Prometheus 1.6.0](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md#160--2017-04-14) ?

**Comment by brancz** [comment]
That is correct.
