### ISSUE TITLE
some metrics and their origin

### ISSUE THREAD

**Issue by cemo** [coreos/prometheus-operator#261]
I did not want to open an issue for this but could not find really a better way. I am using dashboards of this repo without using prometheus operator and could not find what is filling `container_network_receive_bytes_total` and `container_cpu_usage_seconds_total` metrics. These seems as part of `kube-proxy` but could not find necessary scrapping configurations.

**Comment by dannyk81** [comment]
I believe they come from [cAdvsisor](https://github.com/google/cadvisor) which is embedded into kubelet.

**Comment by cemo** [comment]
which configuration of prometheus is scraping kubelet's?

**Comment by brancz** [comment]
The kubelets are a tricky one, a few Prometheus Operator features play together for those to get scraped:

* The kubelets are discovered via [this](https://github.com/coreos/prometheus-operator/blob/92b5a896d2265f89caa1f87240291ba623ea8a99/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-servicemonitors.yaml#L25-L46) `ServiceMonitor`, from which the Prometheus Operator generates a Prometheus configuration.
* The Prometheus Operator synchronizes the internal IPs of the kubelets into an Endpoints object, from which they are discovered from. The object that it is synchronized into is specified via the `--kubelet-object` flag.

**Comment by brancz** [comment]
Closing here for now. Feel free to comment here if you have further questions.

**Comment by dkoshkin** [comment]
Just found this and running into the same issue, does this metric only work when using the operator, Im trying to get these charts to work using helm charts but not able to :(.

**Comment by brancz** [comment]
It does not _only_ work with the Prometheus Operator, but it makes is especially easy to scrape them, and with out of the box configuration from kube-prometheus that will work pretty much one-click.

As there is currently just a Prometheus Operator chart I'm unsure I understand which charts you are referring to @dkoshkin .

**Comment by dkoshkin** [comment]
My bad @brancz I should have specified I was playing around with https://github.com/kubernetes/charts/tree/master/stable/grafana

**Comment by cemo** [comment]
I explained in other message but might be better to stay at here too. Default scrape interval is 1m and dashboard is using 1m for rate function. So there is not enough data for rate function. Change dashboard interval to 2m or decrease scrape interval to 30s.

**Comment by dkoshkin** [comment]
Thanks @cemo that worked!
