### ISSUE TITLE
Deploying an instance of prometheus via operator into application name space - Permission issue

### ISSUE THREAD

**Issue by cyperplex** [coreos/prometheus-operator#2612]
Hi,

Ive deployed the operator and via HELM into my cluster successfully and its working with the out of the box components .

Now when i deploy an instance via the operator into another name space to monitor application specific metrics, i get an error with permissions.

ie

level=error ts=2019-05-20T10:47:37.700320466Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:300: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:test-namespace:default\" cannot list endpoints in the namespace \"test-namespace\""
level=error ts=2019-05-20T10:47:38.701151262Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:test-namespace:default\" cannot list pods in the namespace \"test-namespace\""
level=error ts=2019-05-20T10:47:38.707869372Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:300: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:test-namespace:default\" cannot list endpoints in the namespace \"test-namespace\""
level=error ts=2019-05-20T10:47:38.707885891Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:test-namespace:default\" cannot list services in the namespace \"test-namespace\""
level=error ts=2019-05-20T10:47:39.70255881Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:test-namespace:default\" cannot list pods in the namespace \"test-namespace\""

I created the application instance of Prometheus with the following configuration.

apiVersion: v1  
kind: Service
metadata:
  name: prometheus-test
  labels:
    service: prometheus-test-instance-service
    application: test
spec:
  ports:
  - port: 9090
    name: http
  selector:
    application: test

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-test-instance
  namespace: test
  labels:
    application: test
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
        application: test 
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles-test
  namespaceSelector:
     namespace: test 
containers:
  resources:
          limits: 
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccountName: prometheus 

  alerting:
    alertmanagers:
      - namespace: test
        name: alertmanager-main
        port: web

By default i set via the Helm values to set the service account for the RBAC rules to be named Prometheus.

Do you know what extra configuration i need to add to the above file to configure it to inherit the permissions of the account created by the operator. Which has rights to all namespaces. 

Thanks

**Comment by brancz** [comment]
We neither maintain nor use the helm charts. I recommend opening an issue on the upstream helm charts repo. This look like the helm chart is not setting up RBAC permissions appropriately.
