### ISSUE TITLE
Facing Issue with SMTP setup for grafana

### ISSUE THREAD

**Issue by veeranji23** [coreos/prometheus-operator#2613]
**What happened?**

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by veeranji23** [comment]
HI All ,

When i am trying to set up SMTP set up in grafana i am unable to proceed further . Below is the set up of my SMTP setup in /etc/grafana/grafana.ini

[smtp]                                                                                                                                                                                           enabled = true                                                                                                                                                                                   host = smtp.gmail.com:25                                                                                                                                                                         user = veeranji.k23@gmail.com                                                                                                                                                                    # If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""                                                                                                   password =""Test@23""                                                                                                                                                                        ;cert_file =                                                                                                                                                                                     ;key_file =                                                                                                                                                                                      skip_verify = true                                                                                                                                                                               from_address = veeranji.k23@gmail.com                                                                                                                                                          from_name = Grafana                                                                                                                                                                              # EHLO identity in SMTP dialog (defaults to instance_name)                                                                                                                                       ehlo_identity = dashboard.example.com                                                                                                                                                                                                                                                                                                                                                             [emails]                                                                                                                                                                                         ;welcome_email_on_sign_up = false
--
Can some one please check and suggest me oin this

**Comment by brancz** [comment]
The kube-prometheus stack was extracted to its own repository: https://github.com/coreos/kube-prometheus. This doesn't seem like an issue with the prometheus-operator itself. Generally this doesn't even seem like an issue with kube-prometheus. Please first contact grafana about your problem.
