### ISSUE TITLE
Additional volumes for prometheus pod

### ISSUE THREAD

**Issue by mwieczorek** [coreos/prometheus-operator#2628]
**What is missing?**

I'd like to be able to add volumes to prometheus pod (in PrometheusSpec definition).

**Why do we need it?**

My use case:
I'd like to monitor hashicorp vault which is deployed also in k8s cluster. To do it I need a vault token. 
Current solution is to place the token in k8s secret, add this secret to prometheusspec.secrets and then use it in endpoint.bearerTokenFile. It's working but f.e. I need to refresh the token periodically.
Desired solution is to:
- add additional volume to prometheus pod, emptyDir with memory as backend
- add additional container to prometheusSpec with vault agent (vault agent will use k8s jwt token to authenticate to vault, get the vault token and put it into file in that emptyDir; vault agent will refresh the token)
- mount the emptyDir also to prometheus container (I think it should be possible after https://github.com/coreos/prometheus-operator/pull/2445) and set it in endpoint.bearerTokenFile

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by brancz** [comment]
There is already an emptyDir that you can use for this exact purpose (in fact we're already using this for templating the prometheus config, so this is perfectly good for you to use for this purpose as well).

**Comment by mwieczorek** [comment]
🤦‍♂ I'm blind
Thanks, closing.
