### ISSUE TITLE
etcdHighNumberOfFailedGRPCRequests alarm not correct due NaN return value

### ISSUE THREAD

**Issue by linecolumn** [coreos/prometheus-operator#2636]
prometheus-operator 0.30.1 (it was same on 0.30.0) on clean cluster (without any load) is constantly hit with alarms:

```
[FIRING:1] Monitoring Event Notification
*Alert:* etcdHighNumberOfFailedGRPCRequests - `critical`
 *Description:* etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd instance 10.1.1.30:2379.
 *Graph:* :chart_with_upwards_trend: *Runbook:* <|:spiral_note_pad:>
 *Details:*
  • *alertname:* `etcdHighNumberOfFailedGRPCRequests`
  • *grpc_method:* `Watch`
  • *grpc_service:* `etcdserverpb.Watch`
  • *instance:* `10.1.1.30:2379`
  • *job:* `kube-etcd`
  • *prometheus:* `monitoring/monitoring-prometheus-oper-prometheus`
  • *severity:* `critical`
```

As it seems this is covered in [https://github.com/etcd-io/etcd/pull/10629](https://github.com/etcd-io/etcd/pull/10629).

**Comment by brancz** [comment]
I commented in the etcd pull request. Let's first discuss there. I don't think that what you are seeing is the same as that pull request. I think what you are seeing is https://github.com/etcd-io/etcd/issues/10289

**Comment by brancz** [comment]
Closing here as this is really something to be solved in etcd, not here.

**Comment by siwyd** [comment]
FYI, for those using the etcd mixin, I worked around this by tweaking the etcd selector:
```
        local etcd = import "etcd-mixin/mixin.libsonnet";

        etcd {
          _config+:: {
            etcd_selector: 'job="etcd",grpc_service!="etcdserverpb.Watch"'
          },
        }
```
