### ISSUE TITLE
prometheus-operator should be able to handle some svc/prometheus-operated modifications

### ISSUE THREAD

**Issue by JensErat** [coreos/prometheus-operator#2639]
**What happened?**

I have prometheus-operator running, and another operator that adds itself to services as finalizer (it just needs to be aware they're removed).

This results in those two operators fighting over the finalizer -- prometheus-operator is removing it, the operator is adding it again.

**Did you expect to see some different?**

Finalizer persistent until removed by operator that added it.

**How to reproduce it (as minimally and precisely as possible)**:

Run

    kubectl --namespace monitoring patch svc prometheus-operated -p '{"metadata":{"finalizers": ["example.org/foo"]}}' 

Observe prometheus-operator removing the finalizer again

**Environment**

* Prometheus Operator version:

    `v0.29.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

    kubeadm on bare metal

* Manifests:

* Prometheus Operator Logs:

    have not found relevant logs

**Anything else we need to know?**:

**Comment by brancz** [comment]
Closing here as this is really just an internal thing, and if there is anything to be done in a similar but not identical way, then the recommended thing is to create another service.
