### ISSUE TITLE
kubernetes_sd_config role: node

### ISSUE THREAD

**Issue by moskitone** [coreos/prometheus-operator#2648]
**What is missing?**
There is no option to get node labels when node-exporter or kubelet are scraped.
**Why do we need it?**
There are labels provided by cloud providers like _cloud.google.com/gke-preemptible_ or other custom labels and they are missed because prometheus-soperator sets _role: endpoints_ to all targets.
It would be useful to have these labels for writing custom alert rules.

**Comment by brancz** [comment]
These are things that you would have once per cluster, so I would recommend you to do that with the `additionalScrapeConfigs` feature, where you can add arbitrary Prometheus config.

**Comment by moskitone** [comment]
It looks like strange behaviour to expose endpoint labels instead of node labels.
I think it would be much better to have the right labels for nodes like it is described here [/prometheus-kubernetes.yml](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml)
Also by adding this to `additionalScrapeConfigs` one should disable default kubelet configuration in helm values to prevent metrics doubling.
