### ISSUE TITLE
apps/v1beta2 -> apps/v1 for Deployment

### ISSUE THREAD

**Issue by mattfarina** [coreos/prometheus-operator#2649]
In the `bundle.yaml` file the `Deployment` uses `apps/v1beta2`. The GA version of this API (`apps/v1`) has been available since Kubernetes 1.9. Soon, Kubernetes will stop accepting objects versioned before `apps/v1`.

We've been telling people for several months about this. I just noticed the old verion while reading the file and thought I'd share that here, too.

**Comment by brancz** [comment]
I think @metalmatze had a work in progress PR for this, but can't find it right now. Where are we on this?

**Comment by metalmatze** [comment]
I'm honestly not sure I started for the Prometheus Operator manifests themselves. I definitely did update kube-prometheus.
Anyone can do a PR to updates this, I'd say. Here's the kube-prometheus changes https://github.com/coreos/kube-prometheus/pull/87/

**Comment by brancz** [comment]
Closed by https://github.com/coreos/prometheus-operator/pull/2652
