### ISSUE TITLE
additionalConfig -- is it real?

### ISSUE THREAD

**Issue by sbussetti** [coreos/prometheus-operator#2651]
In this comment: https://github.com/coreos/prometheus-operator/issues/1166#issuecomment-386896013 @brancz mentions an "additionalConfig" parameter for ServiceMonitors that would let me append additional configurations to a particular ServiceMonitor definition, at least if I am reading the thread correctly.

However, I cannot find any documentation in the spec (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec) nor do I actually see it implemented in the prometheus-operator codebase.  I'm currently managing my label rewriting via additionalScrapeConfigs however, things would be much simplified if, instead of managing a single monolithic blob of additional config as a k8s secret, I could just append a handful of rules onto the `metrics_relabel_configs` section of the config that is already generated by my ServiceMonitor definitions in kubernetes.

**Comment by brancz** [comment]
It’s not on the servicemonitor but on the prometheus resource itself.

**Comment by sbussetti** [comment]
Right -- is there any way to manipulate the individual configuration components at the ServiceMonitor level?

**Comment by sbussetti** [comment]
You know as opposed to having to make a copy of the `job` and generated by a service monitor, paste it into the Prometheus additionalScrapeConfigs and then add the couple additional rules I need?

**Comment by brancz** [comment]
It you just want additional relabeling rules to what the servicemonitor generates then you’re looking for the “relabelings” in the endpoint field of the servicemonitor.

**Comment by sbussetti** [comment]
oh snap
