### ISSUE TITLE
How connect to prometheus own application?

### ISSUE THREAD

**Issue by Asgoret** [coreos/prometheus-operator#2654]
I use this [documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources) , but can't get any metrics in prom. Can anybody help?

**Comment by Aracki** [comment]
You will need to provide more info

**Comment by Asgoret** [comment]
@Aracki i clarified that in OKD there is cluster-monitor, not prometheus operator so i just redeploy normal version of prom-operator
