### ISSUE TITLE
How can i change Prometheus‘s args,for example  "--storage.tsdb.retention"

### ISSUE THREAD

**Issue by zhangxingdeppon** [coreos/prometheus-operator#2666]
**What did you do?**
Good afternoon,guy,I want to extend prometheus's data retention time,but I can't find the configuration about it, I have tryed to online edit  the pod prometheus-k8s-0 .but it faild.can you help me ? thanks.
![image](https://user-images.githubusercontent.com/16789841/60959599-10194400-a33b-11e9-894c-fa5a77f13e9d.png)

I have found prometheus Spec.But the document don't describe how to change it

![image](https://user-images.githubusercontent.com/16789841/60959806-6dad9080-a33b-11e9-9c1f-2a0fb90b97c2.png)

<pre><code>
[root@ecs-5274-0318501 manifests]# kubectl -n monitoring describe deployment prometheus-operator
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Wed, 03 Jul 2019 09:38:41 +0800
Labels:                 k8s-app=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"prometheus-operator"},"name":"prometheu...
Selector:               k8s-app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.28.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.28.0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6c88446b98 (1/1 replicas created)
Events:          <none>
</code></pre>

<pre><code>

the yaml file about operator:
[root@ecs-5274-0318501 manifests]# vim 0prometheus-operator-deployment.yaml 

metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.28.0
        image: quay.io/coreos/prometheus-operator:v0.28.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator

</code></pre>
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
I recommend going through the [getting started guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md), there you'll learn about the Prometheus type object, that the Prometheus Operator introduces. That's where you set the retention.

**Comment by zhangxingdeppon** [comment]
> I recommend going through the [getting started guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md), there you'll learn about the Prometheus type object, that the Prometheus Operator introduces. That's where you set the retention.

I' m sorry.I still haven't found the relevant content.i'm bad at it ,could you give some advise please ？thanks

**Comment by brancz** [comment]
Looking at the example in the getting started guide here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#include-servicemonitors

It has this object:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```

To configure retention to be 10 hours, that object would look like this:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  retention: 10h
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```

**Comment by zhangxingdeppon** [comment]
> ```yaml
> retention: 10h
> ```

ok，I got it，I configured it according to your suggestion,the probelem have resolved recently，thanks very much,excellent.

**Comment by zhangxingdeppon** [comment]
> Looking at the example in the getting started guide here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#include-servicemonitors
> 
> It has this object:
> 
> ```yaml
> apiVersion: monitoring.coreos.com/v1
> kind: Prometheus
> metadata:
>   name: prometheus
> spec:
>   serviceAccountName: prometheus
>   serviceMonitorSelector:
>     matchLabels:
>       team: frontend
>   resources:
>     requests:
>       memory: 400Mi
>   enableAdminAPI: false
> ```
> 
> To configure retention to be 10 hours, that object would look like this:
> 
> ```yaml
> apiVersion: monitoring.coreos.com/v1
> kind: Prometheus
> metadata:
>   name: prometheus
> spec:
>   retention: 10h
>   serviceAccountName: prometheus
>   serviceMonitorSelector:
>     matchLabels:
>       team: frontend
>   resources:
>     requests:
>       memory: 400Mi
>   enableAdminAPI: false
> ```

I got it,LOL，I configured it according to your suggestion,the probelem have resolved recently，thanks very much,excellent.
