### ISSUE TITLE
update endpoints of promethues by opreator

### ISSUE THREAD

**Issue by zgfh** [coreos/prometheus-operator#2674]
**What is missing?**
when one prometheus down for a while , the metrics loss, when use service to query metric, it not work, because service will send request to the recovered prometheus

**Why do we need it?**
opreator update the endpoints of promethues service,
 according to `pod.status.containerStatuses.state.running.startedAt` of prometheus pod

**Comment by brancz** [comment]
This is not something that is to be solved by the Prometheus Operator. It is solved by something like [Thanos](https://thanos.io/).

**Comment by zgfh** [comment]
thanks for help

**Comment by zgfh** [comment]
should we add Thanos to Prometheus Operator as a option ?
