### ISSUE TITLE
How to use monitorclientset informer or lister?

### ISSUE THREAD

**Issue by wikiios** [coreos/prometheus-operator#2675]
**What did you do?**

I updated my prometheus-operator from 0.23.0 --> 0.29.0
and I found the operator was extended with cache informer & lister , however I can't find a doc for me to use it.

**Did you expect to see some different?**

A informer and lister usage doc or test.go ( which shows usage and add tests on these)

**Environment**

kubernetes 1.13.2
prometheus2

* Prometheus Operator version:

0.29.0

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version: 1.13.2`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
We don't officially support any of those code bits, if you want to use them you're free to figure it out and document it, but I don't think we will. For what it's worth, it just uses the normal kubernetes code generators, so it works the exact same way as every other API out there :)

**Comment by wikiios** [comment]
roger that, I've found my way to get use of it, thx
