### ISSUE TITLE
HPA cannot scale down and kubectl top unstable

### ISSUE THREAD

**Issue by kong62** [coreos/prometheus-operator#2677]
prometheus-operator: v0.29.0
kubeadm: 1.14.2
metrics-server: not installed

HPA:
It Can expand, but can not be reduced！
 # cat hpa-hpa.yaml 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
  labels:
    app: hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

TOP:
the data is jittery
# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
load-generator                0m           3Mi             
php-apache-6696b744c7-974xv   0m           11Mi            
php-apache-6696b744c7-gpn6w   0m           11Mi            
php-apache-6696b744c7-wp4sn   0m           11Mi            

# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
load-generator                0m           3Mi             
php-apache-6696b744c7-974xv   0m           11Mi            
php-apache-6696b744c7-gpn6w   0m           11Mi            

# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
php-apache-6696b744c7-974xv   0m           11Mi            
php-apache-6696b744c7-gpn6w   0m           11Mi            

# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
php-apache-6696b744c7-974xv   0m           11Mi            

# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
php-apache-6696b744c7-974xv   0m           11Mi            

 kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
php-apache-6696b744c7-974xv   0m           11Mi            

 kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
php-apache-6696b744c7-974xv   0m           11Mi            

# kubectl top pod
W0718 11:36:06.568216  110313 top_pod.go:266] Metrics not available for pod default/load-generator, age: 39m1.568199776s
error: Metrics not available for pod default/load-generator, age: 39m1.568199776s

# kubectl top pod
NAME                          CPU(cores)   MEMORY(bytes)   
load-generator                0m           3Mi             
php-apache-6696b744c7-974xv   0m           11Mi            
php-apache-6696b744c7-dsxcw   0m           11Mi            
php-apache-6696b744c7-gpn6w   0m           11Mi            
php-apache-6696b744c7-wp4sn   0m           11Mi            

# kubectl get pod
NAME                          READY   STATUS    RESTARTS   AGE
load-generator                1/1     Running   0          39m
php-apache-6696b744c7-974xv   1/1     Running   0          12m
php-apache-6696b744c7-dsxcw   1/1     Running   0          13m
php-apache-6696b744c7-gpn6w   1/1     Running   0          13m
php-apache-6696b744c7-wp4sn   1/1     Running   0          39m

**Comment by brancz** [comment]
cc @s-urbaniak @paulfantom we should look into this

**Comment by liupeng0518** [comment]
same issue...

**Comment by dingsongjie** [comment]
same issue...

**Comment by brancz** [comment]
Are you all successfully scraping cadvisor metrics? Can you share a graph of `up{job="kubelet"}`?

**Comment by dingsongjie** [comment]
A signle Test node  ![image](https://user-images.githubusercontent.com/10933723/65490360-97f50000-dedf-11e9-84f9-386cd2000efc.png)

**Comment by dingsongjie** [comment]
And I found some logs from kube apiserver
**loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: OpenAPI spec does not exist**

**Comment by brancz** [comment]
Can you share a screenshot of your /targets page of the Prometheus UI? There should be more than one kubelet target.

**Comment by dingsongjie** [comment]
> Can you share a screenshot of your /targets page of the Prometheus UI? There should be more than one kubelet target.

I am sorry for late reply

![image](https://user-images.githubusercontent.com/10933723/65810860-d0982080-e1e2-11e9-973c-4a0b8d7e11c8.png)

**Comment by brancz** [comment]
Curious. This does seem like it's a bug in the prometheus adapter.

**Comment by s-urbaniak** [comment]
Indeed, there is something very weird indeed :thinking: I am having fluctuating pod metrics using 1.15 too:
```
$ while true; do kubectl top pod --all-namespaces; echo ---; sleep 2; done
NAMESPACE     NAME                                         CPU(cores)   MEMORY(bytes)   
kube-system   coredns-5c98db65d4-2p99g                     4m           17Mi            
kube-system   coredns-5c98db65d4-b8fvw                     6m           17Mi            
kube-system   etcd-kind-control-plane                      22m          53Mi            
kube-system   kindnet-b97f6                                0m           8Mi             
kube-system   kube-controller-manager-kind-control-plane   30m          48Mi            
kube-system   kube-proxy-tkn4b                             3m           15Mi            
kube-system   kube-scheduler-kind-control-plane            2m           14Mi            
monitoring    alertmanager-main-0                          6m           19Mi            
monitoring    alertmanager-main-1                          6m           17Mi            
monitoring    alertmanager-main-2                          6m           19Mi            
monitoring    kube-state-metrics-ff5cb7949-ls2gx           0m           33Mi            
monitoring    node-exporter-5d55g                          0m           22Mi            
monitoring    prometheus-k8s-0                             47m          263Mi           
monitoring    prometheus-k8s-1                             30m          163Mi           
monitoring    prometheus-operator-55b978b89-bzzdw          1m           21Mi            
---
NAMESPACE     NAME                                         CPU(cores)   MEMORY(bytes)   
kube-system   coredns-5c98db65d4-2p99g                     4m           17Mi            
kube-system   coredns-5c98db65d4-b8fvw                     4m           17Mi            
kube-system   etcd-kind-control-plane                      21m          53Mi            
kube-system   kindnet-b97f6                                0m           8Mi             
kube-system   kube-controller-manager-kind-control-plane   30m          48Mi            
kube-system   kube-proxy-tkn4b                             2m           15Mi            
monitoring    alertmanager-main-0                          6m           19Mi            
monitoring    alertmanager-main-1                          0m           17Mi            
monitoring    kube-state-metrics-ff5cb7949-ls2gx           0m           33Mi            
monitoring    prometheus-k8s-0                             47m          263Mi           
monitoring    prometheus-k8s-1                             28m          163Mi           
monitoring    prometheus-operator-55b978b89-bzzdw          1m           21Mi            
---
NAMESPACE     NAME                                         CPU(cores)   MEMORY(bytes)   
kube-system   coredns-5c98db65d4-2p99g                     4m           17Mi            
kube-system   etcd-kind-control-plane                      20m          53Mi            
kube-system   kube-controller-manager-kind-control-plane   30m          48Mi            
monitoring    alertmanager-main-0                          6m           19Mi            
monitoring    alertmanager-main-1                          0m           17Mi            
monitoring    kube-state-metrics-ff5cb7949-ls2gx           0m           33Mi            
monitoring    prometheus-operator-55b978b89-bzzdw          1m           21Mi            
---
NAMESPACE     NAME                                 CPU(cores)   MEMORY(bytes)   
kube-system   coredns-5c98db65d4-2p99g             3m           17Mi            
monitoring    alertmanager-main-0                  0m           19Mi            
monitoring    kube-state-metrics-ff5cb7949-ls2gx   0m           33Mi            
---
---
```

investigating ...

**Comment by s-urbaniak** [comment]
At least for metrics present in k8s >= 1.15 we have a flaky metric:
```
sort(sum(rate(container_cpu_usage_seconds_total{namespace="monitoring",container!="POD",container!="",pod!=""}[1m])) by (pod,container))
```

`container_cpu_usage_seconds_total` returns different results upon subsequent executions. we have to look into cadvisor, why that is the case.

**Comment by s-urbaniak** [comment]
Example:
![image](https://user-images.githubusercontent.com/375856/65880626-60c89800-e392-11e9-8bcc-2de7de7100c0.png)
vs. (executed a few seconds later)
![image](https://user-images.githubusercontent.com/375856/65880660-6c1bc380-e392-11e9-979b-3ea377677093.png)

**Comment by paulfantom** [comment]
It seems that data is jittery because cadvisor library, which is vendored into kubelet and is responsible for providing basic pod metrics, decided to include timestamps to metrics exposition (added in [google/cadvisor PR](https://github.com/google/cadvisor/issues/2123)). This small change causes that basic container metrics might not be available at points in time (can be seen on a picture below) and causing `kubectl top pod` to be unreliable.

![Screenshot_20191002_153851](https://user-images.githubusercontent.com/3531758/66052473-f0a44880-e530-11e9-984f-aa03dbc34581.jpg)

**Comment by s-urbaniak** [comment]
let's fix the query in https://github.com/coreos/kube-prometheus/blob/f458e85e5d7675f7bc253072e1b4c8892b51af0f/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet#L22 then to a `[5m]` rate.

**Comment by paulfantom** [comment]
This is fixed in kube-prometheus.
