### ISSUE TITLE
"no such file or directory" - when creating prometheus container

### ISSUE THREAD

**Issue by mikebryant** [coreos/prometheus-operator#268]
**What did you do?**
Created a `Prometheus` object

**What did you expect to see?**
The prometheus instance working

**What did you see instead? Under which circumstances?**
`prometheus` container won't start with `no such file or directory`

I think this might be similar to #74

**Environment**
CoreOS / Openstack

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.1", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-18T01:43:45Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Custom / Heat

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  namespace: kube-monitoring
spec:
  baseImage: mirror-quay.docker.tech.lastmile.com/prometheus/prometheus
  externalUrl: http://prometheus.kube-monitoring.K8S_INGRESS_ROOT_DOMAIN_NAME
  replicas: 2
  version: v1.5.2
  retention: 168h
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  resources:
    requests:
      memory: 2Gi
  storage:
    class: fast
    resources:
      requests:
        storage: 50Gi
  alerting:
    alertmanagers:
    - namespace: kube-monitoring
      name: alertmanager
      port: http-metrics
```

* Prometheus Operator Logs:

```
Events:
  FirstSeen	LastSeen	Count	From						SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----						-------------	--------	------			-------
  5m		5m		2	default-scheduler						Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0", which is unexpected.]
  5m		5m		1	default-scheduler						Normal		Scheduled		Successfully assigned prometheus-k8s-0 to kubernetes-kubernetes-az1-2-1491488462
  5m		5m		1	attachdetach							Warning		FailedMount		Failed to attach volume "pvc-183973fa-1aeb-11e7-8b7f-fa163ec5da7b" on node "kubernetes-kubernetes-az1-2-1491488462" with: volume b6087d4c-a0d6-444f-a949-9eae1013bea6 is not attached to c129681b-9165-402f-9977-3dc807484b1d
  5m		5m		1	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus-config-reloader}	Normal		Pulling			pulling image "quay.io/coreos/prometheus-config-reloader:v0.0.1"
  5m		5m		1	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus-config-reloader}	Normal		Started			Started container with docker id 4db51b2b8a7b
  5m		5m		1	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus-config-reloader}	Normal		Pulled			Successfully pulled image "quay.io/coreos/prometheus-config-reloader:v0.0.1"
  5m		5m		1	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus-config-reloader}	Normal		Created			Created container with docker id 4db51b2b8a7b; Security:[seccomp=unconfined]
  5m		0s		25	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus}			Normal		Pulling			pulling image "mirror-quay.docker.tech.lastmile.com/prometheus/prometheus:v1.5.2"
  5m		0s		25	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus}			Normal		Pulled			Successfully pulled image "mirror-quay.docker.tech.lastmile.com/prometheus/prometheus:v1.5.2"
  5m		0s		25	kubelet, kubernetes-kubernetes-az1-2-1491488462	spec.containers{prometheus}			Warning		Failed			Failed to create docker container "prometheus" of pod "prometheus-k8s-0_kube-monitoring(183b44a8-1aeb-11e7-8b7f-fa163ec5da7b)" with error: Error response from daemon: no such file or directory
  5m		0s		25	kubelet, kubernetes-kubernetes-az1-2-1491488462			Warning		FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "prometheus" with RunContainerError: "runContainer: Error response from daemon: no such file or directory"


```

**Comment by brancz** [comment]
As you have a different base image, I'm guessing you compiled it yourself? What we've often seen is that this happens when you compile prometheus with the `make build` target, which _does not_ produce a statically linked binary, therefore when putting the binary in the busybox image it will try to load the libraries it was dynamically linked against but fails with that error message. To check this execute this on the produced Prometheus binary:

```
ldd ./prometheus
```

For creating a statically linked binary, you need to run `promu crossbuild`, which is what the Prometheus CI does on releases.

Why this happens: the go compiler has a subtlety, where it produces statically linked binaries if the libraries it wants to dynamically link to do not exist on your system, but if they do it does dynamically link against them, causing the error you are seeing.

Let me know if this helps.

**Comment by mikebryant** [comment]
Actually, we have an internal pull-through mirror to reduce bandwidth usage. So that different base image is just telling it to pull from our cache, go over the WAN link.

So the image we're using is pure upstream, we didn't make it ourselves.

**Comment by brancz** [comment]
I see, sorry for my hasty conclusion.

Looking through the list of events you mentioned, it seems there is a problem with the Persistent storage that is meant to be mounted into the container.

Are you using a storage provisioning method? If yes which one? If no, can you ensure there is a `PersistentVolume` matching the requirements of the `PersistentVolumeClaim`?

**Comment by mikebryant** [comment]
The `PersistentVolume` was provisioned, it's a storageclass referencing cinder:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/cinder
parameters:
  type: HighIO
```

Checking further, the volume has been mounted on the host by the kubelet.
Going in and manually creating the subPath it's expecting let the container start properly after the backoff period finished.



I've since tried this on another Kubernetes cluster, and it worked there... (Which leaves me somewhat confused, and maybe means subPath provisioning is supported, but something's broken in that particular cluster, rather than in general)

**Comment by gianrubio** [comment]
@mikebryant looks like this is related to k8s mount the volume. This was frequently to me on 1.5.2, however when I migrate to 1.5.3 this reduced a lot.

Could you share the output of this commands?

```$ kubectl get pvc --all-namespaces -o yaml```

and 

```$ kubectl get events -w -n monitoring```

**Comment by mikebryant** [comment]
Sure


[all-namespaces-pvcs.yaml.txt](https://github.com/coreos/prometheus-operator/files/910610/all-namespaces-pvcs.yaml.txt)
[kube-monitoring-events.yaml.txt](https://github.com/coreos/prometheus-operator/files/910612/kube-monitoring-events.yaml.txt)

**Comment by gianrubio** [comment]
hum.. the logs didn't add some info...

What happen's if you remove the storage class from prometheus and delete the pod?
also are you able to run a ``ls`` command in the mount point of this pvc -- just to check if the pvc are correctly mounted in the same node of pod prometheus-k8s.

**Comment by brancz** [comment]
@mikebryant have you been able to figure something out in this regard?

**Comment by mikebryant** [comment]
If there's no storageclass, then the containers start correctly.

I can find the mounted pvc (for `prometheus-k8s-1`): 
```
kubernetes-kubernetes-az1-3-1491488462 pvc-183e1fd3-1aeb-11e7-8b7f-fa163ec5da7b # ls -al
total 28
drwxr-xr-x. 3 root root  4096 Apr  6 17:27 .
drwxr-x---. 3 root root  4096 Apr  6 17:27 ..
drwx------. 2 root root 16384 Apr  6 17:27 lost+found
```
Currently `prometheus-k8s-0` starts correctly (where I manually went onto the host and created the subdir in the volume)
`prometheus-k8s-1` doesn't start, with
 ```
  2s	0s	3	kubelet, kubernetes-kubernetes-az2-4-1491491585	spec.containers{prometheus}	Warning	Failed		Failed to create docker container "prometheus" of pod "prometheus-k8s-1_kube-monitoring(901f3ea9-2055-11e7-8971-fa163eca085c)" with error: Error response from daemon: no such file or directory
  1s	0s	3	kubelet, kubernetes-kubernetes-az2-4-1491491585					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "prometheus" with RunContainerError: "runContainer: Error response from daemon: no such file or directory"
```

**Comment by brancz** [comment]
Interesting, doesn't seem like a Prometheus Operator issue, does it?

**Comment by mikebryant** [comment]
Am pretty confused. I'm going to close this for now

**Comment by anuthaharinimn** [comment]
Hi,
I'm taking the backup of Prometheus, while taking the backup, im stopping the Prometheus service and taking the backup, once the backup is completed again im starting the Prometheus service.
but backup is not happening im getting ```No such file or directory: '/mnt/dockerdata/prometheus/data/heads.db.tmp ```
My Prometheus is running in a docker swarm container.
