### ISSUE TITLE
Add blackbox exporter and BlackboxTarget CRD

### ISSUE THREAD

**Issue by david-martin** [coreos/prometheus-operator#2680]
**What is missing?**

Blackbox probing of endpoints using https://github.com/prometheus/blackbox_exporter.
More specifically, the ability to declare endpoints to probe in a kubernetes native way.

**Why do we need it?**

So that it's easy to gather metrics about endpoints with an 'out of the box' install of prometheus when using this operator.

You can get this feature already by doing a couple things:

- add an `additionalScrapeConfig` secret with blackbox probes defined
- add a blackbox exporter container to the Prometheus CR

However, it would be nice to have a `BlackboxTarget` CRD, similar to `PrometheusRule`, for defining a list of endpoints and modules to use.
This would make it a lot easier to define a list of probes in a decoupled way.
Probes could be defined in separate resources, and bundled with the application they are for.
This removes the overhead of maintaining a single central blackbox config.

**Environment**

* Prometheus Operator version:

    `master`

**Anything else we need to know?**:

I've created this issue after reaching out to some folks on forum-monitoring on coreos slack.

We've solved this problem at a layer above by creating an `application-monitoring-operator` that depends on the `prometheus-operator` and `grafana-operator`.
It sets those up and provisions prometheus and grafana in a generic way for application monitoring.
This includes the blackbox exporter and a BlackboxTarget CRD.

Here's some info on the BlackboxTarget CRD we're using currently https://github.com/integr8ly/application-monitoring-operator#blackboxtarget

and an example https://github.com/integr8ly/application-monitoring-operator/blob/master/deploy/examples/BlackboxTarget.yaml

If it makes sense, we could add something similar to the prometheus operator using this as a working example.

cc @brancz @metalmatze @s-urbaniak

**Comment by brancz** [comment]
I like this quite a lot as it is already. I'd like to discuss this part a little more:

> This would make it a lot easier to define a list of probes in a decoupled way.
> Probes could be defined in separate resources, and bundled with the application they are for.
> This removes the overhead of maintaining a single central blackbox config.

From what I can tell, so far you provision a Blackbox exporter statically with a config. I wonder if the blackbox exporter to use should be specifyable in the BlackboxTarget, to potentially allow users to define whatever probe they want, but allow there to be a default blackbox exporter instance defined as a flag to the operator that offers a set of useful standard probes (dns, http ping, etc.). What do you think?

**Comment by yeya24** [comment]
Agree on @brancz . Any progress of this feature? It' s very useful.

**Comment by brancz** [comment]
I don't think there has been progress recently.

**Comment by pb82** [comment]
@brancz Yes that's correct, we currently provision one blackbox exporter with a static config for http probing. I think it would be a good idea to let users define their probes (modules). Is your idea to ship the Prometheus operator with a default exporter and if users need different probes they create more exporters and have Prometheus scrape them? If so, wouldn't the users also have to create a scrape config for every blackbox exporter?

What do you think about having only one instance of the blackbox exporter (created and managed by the Prometheus operator) and reconcile it's configuration from a secret? Users can add additional probe modules to that secret and the Prometheus operator would update and restart the exporter.

This way users can provide their own config but don't have to worry about scrape configs.

**Comment by brancz** [comment]
People will always have to define targets in some way, which I believe we're all agreeing would be through the BlackboxProbe CRD. The way I imagine it is that distributions (kube-prometheus, OpenShift, etc.) that decide to install the prometheus operator can include a blackbox exporter out of the box with a set of useful standard probes. The BlackboxProbe would allow configuring a concrete blackbox-exporter to use, or if unspecified, use the one provided by the distribution. That way there is a very smooth and easy normal path, and only if users have an exotic blackbox probe that we don't want to have in a distribution, then they can still opt to running their own blackbox exporter and define in the blackbox probe to use that one.

**Comment by pb82** [comment]
> People will always have to define targets in some way, which I believe we're all agreeing would be through the BlackboxProbe CRD.

Yes agree

> The way I imagine it is that distributions (kube-prometheus, OpenShift, etc.) that decide to install the prometheus operator can include a blackbox exporter out of the box with a set of useful standard probes. The BlackboxProbe would allow configuring a concrete blackbox-exporter to use, or if unspecified, use the one provided by the distribution.

That sounds reasonable. Would those standard probes be configurable through the Prometheus CR or hardcoded?

One thing to keep in mind maybe: I found that the blackbox exporter doesn't act like a normal metrics endpoint that can be discovered with a service monitor. Prometheus needs to pass the URL it wants to probe (and how it wants to probe it) in the scrape request. For this reason we use an additional scrape config with some relabeling rules specifically for the blackbox exporter (see https://github.com/integr8ly/application-monitoring-operator/blob/master/templates/blackbox-exporter-job.yaml).

**Comment by brancz** [comment]
> That sounds reasonable. Would those standard probes be configurable through the Prometheus CR or hardcoded?

They would be "hardcoded" for the default blackbox exporter provided by the distribution. Any change to the out of the box provided probes would be a feature request.

> One thing to keep in mind maybe: I found that the blackbox exporter doesn't act like a normal metrics endpoint that can be discovered with a service monitor. Prometheus needs to pass the URL it wants to probe (and how it wants to probe it) in the scrape request. For this reason we use an additional scrape config with some relabeling rules specifically for the blackbox exporter (see https://github.com/integr8ly/application-monitoring-operator/blob/master/templates/blackbox-exporter-job.yaml).

Totally. That's the whole reason the BlackboxProbe CRD should exist, the prometheus operator will take care of doing what you're doing via the additional scrape config integrated in the same way as the ServiceMonitor is tightly integrated and directly generates into the resulting config. People won't need to use the additionalScrapeConfigs at all.

**Comment by NicolasT** [comment]
This sounds like an interesting feature/project. Is anyone working on it, or is it planned?

**Comment by auhlig** [comment]
If there are no takers, I'll give it a shot

**Comment by brancz** [comment]
I believe it’s free to take :)
