### ISSUE TITLE
No data points for master node in Grafana 

### ISSUE THREAD

**Issue by manavtidhan** [coreos/prometheus-operator#2681]
**What did you do?**
I deployed prometheus-operator on on premise K8s cluster
**Did you expect to see some different?**
I was expecting data points for all nodes but data points for master node is not available
**Environment**
Kubernetes v1.14.2
 on premise cluster running on 4 physical nodes

* Prometheus Operator version:
prometheus-operator-5.15.0
APP VERSION 0.31.1

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
1.14.2
   kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
There is restarts of pods , everything looks fine but when I go to Grafana , then for master nodes I am not able to see any data as there is no data points. 
```

* Prometheus Operator Logs:

```
kubectl logs my-monitor-prometheus-node-exporter-rrdkk
time="2019-07-19T06:10:30Z" level=info msg="Starting node_exporter (version=0.18.0, branch=HEAD, revision=f97f01c46cfde2ff97b5539b7964f3044c04947b)" source="node_exporter.go:156"
time="2019-07-19T06:10:30Z" level=info msg="Build context (go=go1.12.5, user=root@77cb1854c0b0, date=20190509-23:12:18)" source="node_exporter.go:157"
time="2019-07-19T06:10:30Z" level=info msg="Enabled collectors:" source="node_exporter.go:97"
time="2019-07-19T06:10:30Z" level=info msg=" - arp" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - bcache" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - bonding" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - conntrack" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - cpu" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - cpufreq" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - diskstats" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - edac" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - entropy" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - filefd" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - filesystem" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - hwmon" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - infiniband" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - ipvs" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - loadavg" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - mdadm" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - meminfo" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - netclass" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - netdev" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - netstat" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - nfs" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - nfsd" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - pressure" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - sockstat" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - stat" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - textfile" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - time" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - timex" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - uname" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - vmstat" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - xfs" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg=" - zfs" source="node_exporter.go:104"
time="2019-07-19T06:10:30Z" level=info msg="Listening on 0.0.0.0:9100" source="node_exporter.go:170"

kubectl get all
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/alertmanager-my-monitor-prometheus-oper-alertmanager-0   2/2     Running   0          63m
pod/my-monitor-grafana-64d5c74988-j67x7                      2/2     Running   0          63m
pod/my-monitor-kube-state-metrics-646894bddc-4mlds           1/1     Running   0          63m
pod/my-monitor-prometheus-node-exporter-j2v5l                1/1     Running   0          63m
pod/my-monitor-prometheus-node-exporter-pdlgj                1/1     Running   0          63m
pod/my-monitor-prometheus-node-exporter-rrdkk                1/1     Running   0          63m
pod/my-monitor-prometheus-node-exporter-s7mht                1/1     Running   0          63m
pod/my-monitor-prometheus-oper-operator-68fdbbdb9d-qxnbp     1/1     Running   0          63m
pod/prometheus-my-monitor-prometheus-oper-prometheus-0       3/3     Running   1          62m

NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/alertmanager-operated                     ClusterIP   None             <none>        9093/TCP,6783/TCP   63m
service/my-monitor-grafana                        NodePort    10.103.42.84     <none>        80:31414/TCP        63m
service/my-monitor-kube-state-metrics             ClusterIP   10.98.63.10      <none>        8080/TCP            63m
service/my-monitor-prometheus-node-exporter       ClusterIP   10.110.14.73     <none>        9100/TCP            63m
service/my-monitor-prometheus-oper-alertmanager   ClusterIP   10.97.103.84     <none>        9093/TCP            63m
service/my-monitor-prometheus-oper-operator       ClusterIP   10.110.162.169   <none>        8080/TCP            63m
service/my-monitor-prometheus-oper-prometheus     ClusterIP   10.98.35.233     <none>        9090/TCP            63m
service/prometheus-operated                       ClusterIP   None             <none>        9090/TCP            62m

NAME                                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/my-monitor-prometheus-node-exporter   4         4         4       4            4           <none>          63m

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-monitor-grafana                    1/1     1            1           63m
deployment.apps/my-monitor-kube-state-metrics         1/1     1            1           63m
deployment.apps/my-monitor-prometheus-oper-operator   1/1     1            1           63m

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/my-monitor-grafana-64d5c74988                    1         1         1       63m
replicaset.apps/my-monitor-kube-state-metrics-646894bddc         1         1         1       63m
replicaset.apps/my-monitor-prometheus-oper-operator-68fdbbdb9d   1         1         1       63m

NAME                                                                    READY   AGE
statefulset.apps/alertmanager-my-monitor-prometheus-oper-alertmanager   1/1     63m
statefulset.apps/prometheus-my-monitor-prometheus-oper-prometheus       1/1     62m

```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Can you check the `/targets` page on Prometheus? It will tell you why scrapes are failing, if they are.

**Comment by manavtidhan** [comment]
Hi Frederic,

Below is the error from /targets , can you help me how to resolve it.
![prometheus_eroor](https://user-images.githubusercontent.com/48666534/61601482-204cef80-ac68-11e9-9428-0c06c2011738.JPG)

**Comment by manavtidhan** [comment]
Below is the logs from the node-exporter of affected node

/ $ /bin/node_exporter --log.level='debug'
INFO[0000] Starting node_exporter (version=0.18.0, branch=HEAD, revision=f97f01c46cfde2ff97b5539b7964f3044c04947b)  source="node_exporter.go:156"
INFO[0000] Build context (go=go1.12.5, user=root@77cb1854c0b0, date=20190509-23:12:18)  source="node_exporter.go:157"
INFO[0000] Enabled collectors:                           source="node_exporter.go:97"
INFO[0000]  - arp                                        source="node_exporter.go:104"
INFO[0000]  - bcache                                     source="node_exporter.go:104"
INFO[0000]  - bonding                                    source="node_exporter.go:104"
INFO[0000]  - conntrack                                  source="node_exporter.go:104"
INFO[0000]  - cpu                                        source="node_exporter.go:104"
INFO[0000]  - cpufreq                                    source="node_exporter.go:104"
INFO[0000]  - diskstats                                  source="node_exporter.go:104"
INFO[0000]  - edac                                       source="node_exporter.go:104"
INFO[0000]  - entropy                                    source="node_exporter.go:104"
INFO[0000]  - filefd                                     source="node_exporter.go:104"
INFO[0000]  - filesystem                                 source="node_exporter.go:104"
INFO[0000]  - hwmon                                      source="node_exporter.go:104"
INFO[0000]  - infiniband                                 source="node_exporter.go:104"
INFO[0000]  - ipvs                                       source="node_exporter.go:104"
INFO[0000]  - loadavg                                    source="node_exporter.go:104"
INFO[0000]  - mdadm                                      source="node_exporter.go:104"
INFO[0000]  - meminfo                                    source="node_exporter.go:104"
INFO[0000]  - netclass                                   source="node_exporter.go:104"
INFO[0000]  - netdev                                     source="node_exporter.go:104"
INFO[0000]  - netstat                                    source="node_exporter.go:104"
INFO[0000]  - nfs                                        source="node_exporter.go:104"
INFO[0000]  - nfsd                                       source="node_exporter.go:104"
INFO[0000]  - pressure                                   source="node_exporter.go:104"
INFO[0000]  - sockstat                                   source="node_exporter.go:104"
INFO[0000]  - stat                                       source="node_exporter.go:104"
INFO[0000]  - textfile                                   source="node_exporter.go:104"
INFO[0000]  - time                                       source="node_exporter.go:104"
INFO[0000]  - timex                                      source="node_exporter.go:104"
INFO[0000]  - uname                                      source="node_exporter.go:104"
INFO[0000]  - vmstat                                     source="node_exporter.go:104"
INFO[0000]  - xfs                                        source="node_exporter.go:104"
INFO[0000]  - zfs                                        source="node_exporter.go:104"
INFO[0000] Listening on :9100                            source="node_exporter.go:170"
FATA[0000] listen tcp :9100: bind: address already in use  source="node_exporter.go:172"

port status on affected Node

root@hr-01:~/kubernetes/monitoring# lsof -i -P -n | grep 9100
node_expo 19152          nobody    3u  IPv6 43123680      0t0  TCP *:9100 (LISTEN)

Port status on node where preomethus/node exporter works well
root@alpha:~# lsof -i -P -n | grep 9100
node_expo 30306          nobody    3u  IPv6 6013223      0t0  TCP *:9100 (LISTEN)
node_expo 30306          nobody    5u  IPv6 6014756      0t0  TCP 10.0.4.89:9100->10.47.0.6:40038 (ESTABLISHED)

Wget from node

root@hr-01:~/kubernetes/monitoring# wget -o- localhost:9100
--2019-07-22 11:10:16--  http://localhost:9100/
Resolving localhost (localhost)... 127.0.0.1, 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:9100... connected.
HTTP request sent, awaiting response... 200 OK
Length: 150 [text/html]
Saving to: ‘index.html’

     0K                                                       100% 16.4M=0s

2019-07-22 11:10:16 (16.4 MB/s) - ‘index.html’ saved [150/150]

Wget from other node


root@alpha:~# wget -o- 10.0.4.20:9100
--2019-07-22 11:10:51--  http://10.0.4.20:9100/
Connecting to 10.0.4.20:9100... failed: No route to host.

Below is the list of iptables on the affected hosts
root@hr-01:~/kubernetes/monitoring# iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited
WEAVE-NPC-EGRESS  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
WEAVE-NPC-EGRESS  all  --  anywhere             anywhere             /* NOTE: this must go before '-j KUBE-FORWARD' */
WEAVE-NPC  all  --  anywhere             anywhere             /* NOTE: this must go before '-j KUBE-FORWARD' */
NFLOG      all  --  anywhere             anywhere             state NEW nflog-group 86
DROP       all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
FORWARD_direct  all  --  anywhere             anywhere
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_IN_ZONES  all  --  anywhere             anywhere
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_OUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere
OUTPUT_direct  all  --  anywhere             anywhere

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination
FWDI_public  all  --  anywhere             anywhere            [goto]
FWDI_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination
FWDO_public  all  --  anywhere             anywhere            [goto]
FWDO_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_direct (1 references)
target     prot opt source               destination

Chain FWDI_public (2 references)
target     prot opt source               destination
FWDI_public_log  all  --  anywhere             anywhere
FWDI_public_deny  all  --  anywhere             anywhere
FWDI_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain FWDI_public_allow (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate NEW mark match 0x64
ACCEPT     all  --  anywhere             anywhere             ctstate NEW mark match 0x65

Chain FWDI_public_deny (1 references)
target     prot opt source               destination

Chain FWDI_public_log (1 references)
target     prot opt source               destination

Chain FWDO_public (2 references)
target     prot opt source               destination
FWDO_public_log  all  --  anywhere             anywhere
FWDO_public_deny  all  --  anywhere             anywhere
FWDO_public_allow  all  --  anywhere             anywhere

Chain FWDO_public_allow (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate NEW

Chain FWDO_public_deny (1 references)
target     prot opt source               destination

Chain FWDO_public_log (1 references)
target     prot opt source               destination

Chain INPUT_ZONES (1 references)
target     prot opt source               destination
IN_public  all  --  anywhere             anywhere            [goto]
IN_public  all  --  anywhere             anywhere            [goto]

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain INPUT_direct (1 references)
target     prot opt source               destination

Chain IN_public (2 references)
target     prot opt source               destination
IN_public_log  all  --  anywhere             anywhere
IN_public_deny  all  --  anywhere             anywhere
IN_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain IN_public_allow (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:3389 ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:30000 ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6443 ctstate NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:10250 ctstate NEW

Chain IN_public_deny (1 references)
target     prot opt source               destination

Chain IN_public_log (1 references)
target     prot opt source               destination

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  192.168.0.0/16       anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             192.168.0.0/16       /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination

Chain OUTPUT_direct (1 references)
target     prot opt source               destination

Chain WEAVE-NPC (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             base-address.mcast.net/4
ACCEPT     all  --  anywhere             anywhere             PHYSDEV match --physdev-out vethwe-bridge --physdev-is-bridged
WEAVE-NPC-DEFAULT  all  --  anywhere             anywhere             state NEW
WEAVE-NPC-INGRESS  all  --  anywhere             anywhere             state NEW

Chain WEAVE-NPC-DEFAULT (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             match-set weave-;rGqyMIl1HN^cfDki~Z$3]6!N dst /* DefaultAllow ingress isolation for namespace: default */
ACCEPT     all  --  anywhere             anywhere             match-set weave-cv0rY!iG9(UN9y0AK7]x{;T1z dst /* DefaultAllow ingress isolation for namespace: jenkins-ns */
ACCEPT     all  --  anywhere             anywhere             match-set weave-]B*(W?)t*z5O17G044[gUo#$l dst /* DefaultAllow ingress isolation for namespace: kube-node-lease */
ACCEPT     all  --  anywhere             anywhere             match-set weave-Rzff}h:=]JaaJl/G;(XJpGjZ[ dst /* DefaultAllow ingress isolation for namespace: kube-public */
ACCEPT     all  --  anywhere             anywhere             match-set weave-P.B|!ZhkAr5q=XZ?3}tMBA+0 dst /* DefaultAllow ingress isolation for namespace: kube-system */
ACCEPT     all  --  anywhere             anywhere             match-set weave-xJ#0%WUTeHa;e;[L}9ci#OoC7 dst /* DefaultAllow ingress isolation for namespace: kube-logging */
ACCEPT     all  --  anywhere             anywhere             match-set weave-5XkGb;aF#YYGF.p*W_sz*NhEV dst /* DefaultAllow ingress isolation for namespace: monitor */

Chain WEAVE-NPC-EGRESS (2 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
RETURN     all  --  anywhere             anywhere             PHYSDEV match --physdev-in vethwe-bridge --physdev-is-bridged
RETURN     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
RETURN     all  --  anywhere             base-address.mcast.net/4
WEAVE-NPC-EGRESS-DEFAULT  all  --  anywhere             anywhere             state NEW
WEAVE-NPC-EGRESS-CUSTOM  all  --  anywhere             anywhere             state NEW mark match ! 0x40000/0x40000
NFLOG      all  --  anywhere             anywhere             state NEW mark match ! 0x40000/0x40000 nflog-group 86
DROP       all  --  anywhere             anywhere             mark match ! 0x40000/0x40000

Chain WEAVE-NPC-EGRESS-ACCEPT (7 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             MARK or 0x40000

Chain WEAVE-NPC-EGRESS-CUSTOM (1 references)
target     prot opt source               destination

Chain WEAVE-NPC-EGRESS-DEFAULT (1 references)
target     prot opt source               destination
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-s_+ChJId4Uy_$}G;WdH|~TK)I src /* DefaultAllow egress isolation for namespace: default */
RETURN     all  --  anywhere             anywhere             match-set weave-s_+ChJId4Uy_$}G;WdH|~TK)I src /* DefaultAllow egress isolation for namespace: default */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-(*@D~m{~yI5%Yu+?+%hJ;^Y8n src /* DefaultAllow egress isolation for namespace: jenkins-ns */
RETURN     all  --  anywhere             anywhere             match-set weave-(*@D~m{~yI5%Yu+?+%hJ;^Y8n src /* DefaultAllow egress isolation for namespace: jenkins-ns */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-sui%__gZ}{kX~oZgI_Ttqp=Dp src /* DefaultAllow egress isolation for namespace: kube-node-lease */
RETURN     all  --  anywhere             anywhere             match-set weave-sui%__gZ}{kX~oZgI_Ttqp=Dp src /* DefaultAllow egress isolation for namespace: kube-node-lease */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-41s)5vQ^o/xWGz6a20N:~?#|E src /* DefaultAllow egress isolation for namespace: kube-public */
RETURN     all  --  anywhere             anywhere             match-set weave-41s)5vQ^o/xWGz6a20N:~?#|E src /* DefaultAllow egress isolation for namespace: kube-public */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-E1ney4o[ojNrLk.6rOHi;7MPE src /* DefaultAllow egress isolation for namespace: kube-system */
RETURN     all  --  anywhere             anywhere             match-set weave-E1ney4o[ojNrLk.6rOHi;7MPE src /* DefaultAllow egress isolation for namespace: kube-system */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-z@nSzXC|l(k7D#:+VJ1N+r8tt src /* DefaultAllow egress isolation for namespace: kube-logging */
RETURN     all  --  anywhere             anywhere             match-set weave-z@nSzXC|l(k7D#:+VJ1N+r8tt src /* DefaultAllow egress isolation for namespace: kube-logging */
WEAVE-NPC-EGRESS-ACCEPT  all  --  anywhere             anywhere             match-set weave-Tki71GF4ThtkRzzajas0:Z]R_ src /* DefaultAllow egress isolation for namespace: monitor */
RETURN     all  --  anywhere             anywhere             match-set weave-Tki71GF4ThtkRzzajas0:Z]R_ src /* DefaultAllow egress isolation for namespace: monitor */

Chain WEAVE-NPC-INGRESS (1 references)
target     prot opt source               destination

Weave-NPC is used for networking with containers

**Comment by brancz** [comment]
That means prometheus can't scrape the node-exporter on that node. Most likely a firewall thing.

**Comment by manavtidhan** [comment]
thanks! , I am closing it as it resolved as my firewalld is running so i stop it and disable it .
