### ISSUE TITLE
ErrImageNeverPull for grafana-watcher:v0.0.3

### ISSUE THREAD

**Issue by icicimov** [coreos/prometheus-operator#269]
Hi,

This one sounds like missing grafana-watcher image?

Container image "quay.io/coreos/grafana-watcher:v0.0.3" is not present with pull policy of Never
Error syncing pod, skipping: failed to "StartContainer" for "grafana-watcher" with ErrImageNeverPull: "Container image \"quay.io/coreos/grafana-watcher:v0.0.3\" is not present with pull policy of Never" 

Was following this guide: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md for my Kops cluster

**Comment by brancz** [comment]
Yes, this just got merged image coming up! :)

**Comment by brancz** [comment]
It's now pushed, sorry about that! How about now?
