### ISSUE TITLE
Unable to find how to install other Thanos components apart from Sidecar

### ISSUE THREAD

**Issue by e9169** [coreos/prometheus-operator#2697]
**What did you do?**

I did read the documentation on Thanos but it's referencing to kube-prometheus to install other components of Thanos apart from the sidecar. However, kube-prometheus has removed the support for other components of Thanos.

**Did you expect to see some different?**

I would love to see how it's possible to install Thanos and all its components with Prometheus Operator, since apparently this is the way to do it now.

**Environment**

Kubernetes

* Prometheus Operator version:

Latest

* Kubernetes version information:

1.13.4

**Comment by RiRa12621** [comment]
Hey,
there is a project going by the name of kube-thanos [here](https://github.com/metalmatze/kube-thanos) that should give you what you need.
It works just like kube-prometheus but for thanos.

**Comment by yeya24** [comment]
@RiRa12621  I am wondering that does this project plan to support other thanos components in operator api later?

**Comment by e9169** [comment]
> Hey,
> there is a project going by the name of kube-thanos [here](https://github.com/metalmatze/kube-thanos) that should give you what you need.
> It works just like kube-prometheus but for thanos.

Thanks. So, is not possible to install Thanos with prometheus-operator anymore?

**Comment by brancz** [comment]
The prometheus operator never managed more than the sidecar. Most Thanos components are completely stateless so currently we don't see much reason for the prometheus operator to manage more than the sidecar. kube-thanos is meant to generate the manifests complementary to kube-prometheus to integration Thanos with the kube-prometheus stack as @RiRa12621 already mentioned.

**Comment by e9169** [comment]
> The prometheus operator never managed more than the sidecar. Most Thanos components are completely stateless so currently we don't see much reason for the prometheus operator to manage more than the sidecar. kube-thanos is meant to generate the manifests complementary to kube-prometheus to integration Thanos with the kube-prometheus stack as @RiRa12621 already mentioned.

Maybe I explained myself badly, sorry for that. You are right. We were using kube-prometheus to deploy Thanos components. However, this option is not possible anymore (because of this commit: https://github.com/coreos/kube-prometheus/commit/f1cd88fdbb2c7019f09e36f1160a1e692ca16aaf). So, my question is, how can we, using prometheus-operator or kube-prometheus, deploy Thanos apart from the sidecar?

Thanks

**Comment by brancz** [comment]
kube-thanos is exactly the same as the thanos parts of kube-prometheus was, just separating concerns into separate repos :)

**Comment by e9169** [comment]
> kube-thanos is exactly the same as the thanos parts of kube-prometheus was, just separating concerns into separate repos :)

Well... still you need to add and download a new project. We managed to do it by creating a new dependency into the jsonnet.json file and the project downloaded correctly so... at least that part wasn't terrible. Thanks again.

**Comment by brancz** [comment]
That’s how it’s intended to work, happy it worked for you! :)
