### ISSUE TITLE
Configure Grafana Query Interval with Prometheus

### ISSUE THREAD

**Issue by youngee91** [coreos/prometheus-operator#2700]
**What did you do?**
Currently, Grafana updates its graph in an interval of 30 seconds. Even though a refresh rate of 5s or 10s is used, the graph will only update every 30s. Thus, when the graph refresh in 5s, no data will be shown until the 30th second then the data will appear. It seems like the default query interval between Grafana and Prometheus is 30s. I tried to change the scrape interval on PrometheusSpec as well as the Endpoint interval. But it does not seem to work.

**Did you expect to see some different?**
Grafana to update its graph based on the customised interval such as 5s or 10s instead of 30s.

**Environment**

* Prometheus Operator version:
v0.29.0
* Kubernetes version information:
v1.14.1

**Comment by brancz** [comment]
This works as intended. This is because Grafana choses a step size, and until that step is full, it won't display new data, or rather Prometheus won't return a new data point. So this all works as expected. You would need to align the step size to be something smaller in order to see more data more quickly. The Prometheus interface dynamically sets the step, which is why you get a different result there.

**Comment by youngee91** [comment]
> This works as intended. This is because Grafana choses a step size, and until that step is full, it won't display new data, or rather Prometheus won't return a new data point. So this all works as expected. You would need to align the step size to be something smaller in order to see more data more quickly. The Prometheus interface dynamically sets the step, which is why you get a different result there.

Thank you for your reply. May i ask where can I adjust the step size for Grafana? Do you mean the min step on Grafana individual panel?

**Comment by brancz** [comment]
If I'm not mistaken it's a configuration of each Grafana panel.

**Comment by youngee91** [comment]
> If I'm not mistaken it's a configuration of each Grafana panel.

Noted. Thanks!
