### ISSUE TITLE
Custom serviceMonitorSelector inject label in ServiceMonitor 

### ISSUE THREAD

**Issue by theoldscarana** [coreos/prometheus-operator#2702]
**What did you do?**

Hi,

I deployed prometheus-operator enabling the included ServiceMonitors, I also defined a custom ServiceMonitorSelector:

serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelector:
    matchLabels:
      **prometheus: default**

I didn't find a way to assign the label to the serviceMonitors included in the operator.

**What did you expect to see??**

I expect to see my custom label in the ServiceMonitor defined in the operator

Example:

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: 2019-07-31T08:19:05Z
  generation: 1
  labels:
    app: prometheus-operator-coredns
    chart: prometheus-operator-6.0.0
    heritage: Tiller
    release: unrealistic-armadillo
     **prometheus: default**

* Prometheus Operator version: 6.0.0

* Kubernetes version information:
   ` 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"} `

**Comment by brancz** [comment]
We neither use nor maintain the helm charts, please open an issue against it on the upstream charts repo. Thanks! :)
