### ISSUE TITLE
Prometheus Operator:  Best practice for services and metrics scraping

### ISSUE THREAD

**Issue by MyMirelHub** [coreos/prometheus-operator#2706]
**What did you do?**

We have 15 kubernetes deployments which are exporting identical prometheus metrics.  We have currently set up one `monitoring-service` to match all the pod labels and these are getting picked up my one `servicemonitor`

In reference to the diagram below, Are there any technical differences/limitations between creating a service for each deployment to be monitored,  or grouping them all into one big `monitoring-service`? 

![alt text](https://github.com/coreos/prometheus-operator/raw/master/Documentation/user-guides/images/architecture.png "Logo Title Text 1")

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.29.0

* Kubernetes version information:

v1.13.6-gke.13

* Kubernetes cluster kind:

GKE
 
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
The Service name is relabeled onto the Prometheus targets which means that if there were separate services, then you would be able to group by each of those individually. If you don’t need that, then no need to do it :)
