### ISSUE TITLE
Support Volumes on `kind: Prometheus`

### ISSUE THREAD

**Issue by rchapple** [coreos/prometheus-operator#2708]
It would be useful if we had the ability to express ```Volumes``` in the Prometheus Operator's CRD ```kind: Prometheus```.  These volumes would be useful for passing data between ```initContainer``` instances that are part of a Prometheus instance pod.  A particular use case for this is when trying to use InitContainers to log into and fetch secrets from Vault, then insert them into template files (the 'vault-auth/consul-template' process).  Secrets could include things such as TLS certs, as well as login creds for scrap targets, etc.

InitContainers themselves are not currently supported in the operator's Prometheus object, either.  However, there is an existing issue that seeks to address that:
https://github.com/coreos/prometheus-operator/issues/1888

**Comment by brancz** [comment]
I'd like to focus on the end goal which is fetching secrets from vault to use by Thanos. initContainers seem like a poor mechanism for this, volumes on the other hand with something like [this](https://github.com/deislabs/secrets-store-csi-driver) seems like a reasonable approach. What do you think of that?

**Comment by rchapple** [comment]
@brancz -- To be clear, the ```initContainers``` in question here just run the Vault login and consul-template processes, in a defined order.

However, the fact that they can be used to prevent the rest of the Pod's containers from starting if they don't succeed is a desirable trait.  Such is the case where the ```initContainers``` are pulling secrets that are critical to the operation of the 'main' containers; this fast-fail prevents perhaps less obvious errors further down the line.  TBH, I thought there was a symmetry between the way the ```PromSpec``` allows for arbitrary ```Containers``` definitions, and this request for something similar but for ```initiContainers```.  Aren't they kind of similar?

Also, when you're talking about 'something like' the secrets-store-csi-driver project -- did you mean that we should try using _that_, or were you proposing that having a solution (baked into the Prometheus Operator) that leverages volumes for secret passing would be a good model?

**Comment by brancz** [comment]
I was suggesting to use _that_ csi volume provider to provide the secrets to the prometheus container as opposed to init containers (and us adding support for mounting volumes enabling to use that), as I fear they will cause inconsistent setups causing unreasonably higher support burden on us.

**Comment by rchapple** [comment]
@brancz -- If any ```initContainer``` specs in the ```PrometheusSpec``` were simply propagated to the final StatefulSet configuration (the way that the ```PrometheusSpec.Containers``` are, what additional support burden would that place on the project?  If users specified invalid ```Volume``` information, that would be their error to deal with, no?

**Comment by brancz** [comment]
I think it would be ok to add specification of init containers, however, I want us to explicitly call out that these are only meant to be used for secret fetching use cases, all other use cases are unsupported and will not be triaged (eg. config modification, permission fiddling, etc.).

**Comment by rchapple** [comment]
This work has been done, (see reference above) and is almost mergable.  Resolve some conflicts and update API docs to reflect _intended_ use of `initContainers`

**Comment by rchapple** [comment]
**Two things:**

1. The work to add `initContainers` the PrometheusSpec has [already been done](https://github.com/coreos/prometheus-operator/pull/2522), and is almost ready to merge.  All that remains is resolving conflicts and updating the API doc to suggest that users only use `initContainers` to fetch secrets, and that other uses are not supported.

2. If we consider the `initContainers` issue sorted, then`Volumes` would be a similar extension of the Prometheus CRD.  Does anyone have any objection to that in principle/theory?  I could do the work on that, modeled after the way @tongpu added `initContainers`.
