### ISSUE TITLE
Grafana-Watcher option to leave non-configmap dashboards alone

### ISSUE THREAD

**Issue by ebbeelsborg** [coreos/prometheus-operator#272]
**What did you do?**
1. Mounted a volume on the node on which Grafana runs via a PersistentVolumeClaim.
2. Checked that the volume was mounted correctly at /var/lib/grafana (this is a change to the mountPath of the original CoreOS grafana-deployment.yaml manifest that had a value of /var/grafana-storage) on the node where the (singleton) Grafana pod runs. 
3. Created a new dashboard in Grafana and saved it. Confirmed that the /var/lib/grafana/grafana.db file was updated.
4. Deleted the Grafana pod via kubectl. Waited for a new Grafana pod to be ready.
5. Navigated to the Grafana UI to check that the dashboard survived to the new pod via the volume (not so).

**What did you expect to see?**
I expected the Grafana dashboard to still exist and be available in the Grafana UI, due to the volume.

**What did you see instead? Under which circumstances?**
After deleting the Grafana pod with kubectl, it came back up (as expected), but the new dashboard was no longer there. It seems to have been "initialized" (https://github.com/coreos/prometheus-operator/blob/3f6f7a89a101e6f1ae4fced902455fc10e37521f/contrib/grafana-watcher/updater/dashboard.go#L42) by the Grafana-Watcher (which seems to mean wiping the dashboards and installing the ones from the configmap: https://github.com/coreos/prometheus-operator/blob/3f6f7a89a101e6f1ae4fced902455fc10e37521f/contrib/grafana-watcher/updater/dashboard.go#L51).

_I would like a YAML configuration option for the Watcher making it only delete and recreate the dashboards from the configmap and leave all others alone, when talking to the Grafana API._

Our workflow is to create and modify dashboards directly in the Grafana UI, and then save them. I wish for those dashboards to be persisted (just via volumes). We really prefer not to have to export them, put them in a configmap (and push to GitHub as we version control our k8s config there), and deploy that to the cluster(s) every time we change something in them. Then, with a simple backup/restore solution of the Grafana DB, we have sufficient "version" control.

**Environment**
N/A

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kops (Version 1.5.3 (git-46364f6))

* Manifests:

grafana-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

grafana-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:4.1.1
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        ports:
        - name: web
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 300m
      - name: grafana-watcher
        image: quay.io/coreos/grafana-watcher:latest
        args:
          - '--watch-dir=/var/grafana-dashboards'
          - '--grafana-url=http://admin:admin@localhost:3000'
        volumeMounts:
        - name: grafana-dashboards
          mountPath: /var/grafana-dashboards
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - name: grafana-dashboards
          mountPath: /var/grafana-dashboards
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-volume
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards

(Not including the grafana-dashboards.yaml due to its size.)

* Prometheus Operator Logs:
N/A

**Comment by fabxc** [comment]
Thanks for the detailed report.

The single purpose of the grafana-watcher is to implement a work flow where dashboards are in version control and deployed as config maps. As a result, the Grafana instance can be entirely stateless. There's no other feature.

If you want to use a different work flow there is really no reason to use the grafana-watcher. It is just our recommended way of doing things but you can just skip that part and import the dashboards via the UI into your regular Grafana setup.

Or asked differently, what do you want the watcher to do in your setup if not its only feature? The only thing I can think of is supporting both, dashboards regularly persisted in the database and some coming from config maps.
This would be mixing two very contrary approaches and I wouldn't consider this a feature worth adding.

**Comment by ebbeelsborg** [comment]
Thanks a lot for the snappy reply. We'd like the mix, yes, but I understand your point about wanting to keep it completely stateless so I'll close the issue.
