### ISSUE TITLE
how can i user multiple rule file in prometheus-operator

### ISSUE THREAD

**Issue by zxx287856774** [coreos/prometheus-operator#2720]
prometheus-operator all rule or alert config in prometheus-rules.yaml , i need use multiple rule file 

how can i config it tks

like this 
![微信截图_20190814192853](https://user-images.githubusercontent.com/13623559/63017820-d901f980-bec9-11e9-9473-9791d9424721.png)

**Comment by metalmatze** [comment]
The Prometheus Operator supports multiple PrometheusRules (which are Custom Resources) that you can deploy to your cluster and the Operator then discovers and configures.

Here is an example: 
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L1-L9

These PrometheusRule objects are discovered with this configuration:
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-prometheus.yaml#L22-L25

**Comment by zxx287856774** [comment]
tks

**Comment by LiliC** [comment]
Closing this now as the question was answered.

**Comment by zxx287856774** [comment]
create new PrometheusRule  like this
![image](https://user-images.githubusercontent.com/13623559/64673680-61f85a80-d4a1-11e9-9961-51e688c33f33.png)
