### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by lijinghuatongxue** [coreos/prometheus-operator#2735]
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/cluster-monitoring.md

？？？

**Comment by squat** [comment]
Ah, it seems that we moved this guide out into the kube-prometheus project a few months ago and forgot to clean up the broken links: https://github.com/coreos/prometheus-operator/pull/2554/commits/40bf02390829308d61ff937d9872f0fa9f69762c
