### ISSUE TITLE
Add docs for PodMonitor CRD

### ISSUE THREAD

**Issue by sichvoge** [coreos/prometheus-operator#2738]
**What is missing?**

Currently, there are only the generated docs that explains the PodMonitor API but non of the other places in our Markdown docs does mention it at all.

For example:
- https://github.com/coreos/prometheus-operator#customresourcedefinitions
- https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md

Related to #38 and #2566.

**Comment by auhlig** [comment]
As this should have been part of #2566 I'll come up with a PR for that.
