### ISSUE TITLE
creating CRDs failed: waiting for ServiceMonitor crd failed: timed out waiting for Custom Resource: failed to list CRD

### ISSUE THREAD

**Issue by zxx287856774** [coreos/prometheus-operator#2750]
kubectl logs prometheus-operator-6d5f6467fb-m6zkm -n monitoring
error log
err="creating CRDs failed: waiting for ServiceMonitor crd failed: timed out waiting for Custom Resource: failed to list CRD: json: cannot unmarshal array into Go struct field ServiceMonitorSpec.namespaceSelector of type v1.NamespaceSelector"

prometheus-operator: 0.23

what problem?
mayday

![image](https://user-images.githubusercontent.com/13623559/64501416-d55c6980-d2f3-11e9-98eb-ec2e52dec785.png)

**Comment by brancz** [comment]
First I'd recommend to update to the latest versions. You are almost 10 minor versions behind.

Then use our linting tool to figure out which of the objects you have on your cluster, is malformed: https://github.com/coreos/prometheus-operator/tree/master/cmd/lint

**Comment by zxx287856774** [comment]
tks
