### ISSUE TITLE
Target down alert [ part of kube-proxy job ] is being correclty triggered, but kube-proxies are up and running.

### ISSUE THREAD

**Issue by bgvladedivac** [coreos/prometheus-operator#2757]
**What did you do?**

Installed prometheus-operator  with small customizations. However none of the custom values override the kubeProxy component.

monitoring-prometheus-oper-kube-proxy service is up + the endpoints are found, so everything is working as expected from deployment perspective.

The values.yaml custom file => https://gist.github.com/bgvladedivac/be971be75bfbd244c8d5513f08524e05

The problem is coming from TargetDown alert ( part of the kube-proxy job ). Based on the expression syntax the trigger is correct ( since the current value is 100 ), however the alert states that 'all kube-proxy' targets are down, while this is not true. All worker nodes kube-proxies are running fine.
```yaml
alert: TargetDown
expr: 100
  * (count by(job) (up == 0) / count by(job) (up)) > 10
for: 10m
labels:
  severity: warning
annotations:
  message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
```

```yaml
alertname="TargetDown" job="kube-proxy" severity="warning" | FIRING | 2019-09-12 08:25:19.520032135 +0000 UTC | 100
```

The notification I am getting from slack:

```yaml
Alert: TargetDown - warning
 Description: 100% of the kube-proxy targets are down.
 Graph: :chart_with_upwards_trend: Runbook: <|:spiral_note_pad:>
 Details:
  • alertname: TargetDown
```

**Did you expect to see some different?**
I am expecting the trigger of TargetDown alert ( part of kube-proxy job ) to happen only when the kube-proxies are actually missing.

**Environment**
AWS EKS

* Prometheus Operator version:

    Chart: ` prometheus-operator-6.8.3`      
    App version: `0.32.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
`
   

* Kubernetes cluster kind:

   AWS EKS

* Prometheus Operator Logs:

```
level=info ts=2019-09-12T08:24:11.470628901Z caller=main.go:140 msg="Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"
level=info ts=2019-09-12T08:24:11.470681206Z caller=main.go:141 build_context="(go=go1.12.4, user=root@932a86a52b76, date=20190503-09:10:07)"
level=warn ts=2019-09-12T08:24:11.513732792Z caller=cluster.go:226 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-monitoring-prometheus-oper-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-monitoring-prometheus-oper-alertmanager-0.alertmanager-operated.monitoring.svc on 172.20.0.10:53: no such host\n\n"
level=info ts=2019-09-12T08:24:11.513771428Z caller=cluster.go:228 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2019-09-12T08:24:11.513786465Z caller=main.go:230 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-monitoring-prometheus-oper-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-monitoring-prometheus-oper-alertmanager-0.alertmanager-operated.monitoring.svc on 172.20.0.10:53: no such host\n\n"
level=info ts=2019-09-12T08:24:11.513846034Z caller=cluster.go:613 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-09-12T08:24:11.559745307Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-09-12T08:24:11.560130214Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-09-12T08:24:11.562381745Z caller=main.go:365 msg=Listening address=:9093
```

**Comment by bgvladedivac** [comment]
a small up :)

**Comment by LiliC** [comment]
@bgvladedivac how did you install the operator? It looks like its a helm chart if I understand correctly?

**Comment by bgvladedivac** [comment]
@LiliC  the operator is installed with argocd. The installation command refers to the prom-operator from the official helm chart repo.

`argocd app create monitoring 
  --repo https://github.com/helm/charts.git 
  --path stable/prometheus-operator 
  --dest-server https://kubernetes.default.svc 
  --dest-namespace monitoring`

As I said there is no overriding over the Prometheus rules. All other alerts are behaving like expected.

**Comment by brancz** [comment]
Can you share a screenshot of your /targets page of Prometheus? This may be happening because Prometheus is unable to scrape your kube proxy targets.

**Comment by bgvladedivac** [comment]
I am closing the issue, thanks a lot for the support :)
