### ISSUE TITLE
container_cpu_usage_seconds_total can not get container or image info for some pods

### ISSUE THREAD

**Issue by liuhui8** [coreos/prometheus-operator#2762]
What happened?
The cpu usage of the  pods can not be get by promql like :
   container_cpu_usage_seconds_total{image!="",pod_name=~".*.test-123.*"}
because prometheus is absent of lable 'image' or 'container',however,when i use kuebctl describe pod test-123....there is image,image id and container id:
![image](https://user-images.githubusercontent.com/50951174/65040358-c37b6600-d986-11e9-873e-db7ed8dd7ba2.png)

Did you expect to see some different? 
   most of pods can get label 'image' or 'container' from prometheus by promQl container_cpu_usage_seconds_total,so why few can not?
   is anyone can help?thanks a lot

**Comment by brancz** [comment]
This is not a question about the prometheus operator, this is about cadvisor. Please ask your question there.
