### ISSUE TITLE
RabbitMQ on Kubernetes TLS Alert CA cert could not be correctly decoded

### ISSUE THREAD

**Issue by stan-iakov** [coreos/prometheus-operator#2768]
Hi,
I am about to install a RabbitMQ image 3.7.15-debian-9-r8 on a Kubernetes Cluster 1.15.
I face an issue when the RabbitMQ container tries to start the node discovery using the Kubernetes APIs. I see the following error in the container logs:
SSL WARNING: Ignoring a CA cert as it could not be correctly decoded
TLS client: In state certify at ssl_handshake.erl:364 generated CLIENT ALERT: Fatal - Internal Error - {unexpected _error, {cqse_clause,{error,{asn,{...}}}}}
Failed to get nodes from k8s - {failed_connect, [to_address, {'kubernetes.default.svc.cluster.local',443}}

The CA certificate is self signed and is available on the Kubernetes Pod but I do not understand why the Discovery plugin is not able to decode it. I am able to read it with openssl, which means that the certificate is correct.

Any suggestions what could be causing this issue?

Thank you

**Comment by LiliC** [comment]
@stan-iakov not sure how this relates to prometheus-operator, can you explain?

**Comment by stan-iakov** [comment]
Sorry,
Indeed this is not related to prometheus.

**Comment by LiliC** [comment]
No worries, closing. :)
