### ISSUE TITLE
Outdated version on operatorhub.io

### ISSUE THREAD

**Issue by a-hat** [coreos/prometheus-operator#2769]
The current version of the prometheus-operator on operatorhub.io is from January (v0.27), see [the operatorhub github repo](https://github.com/operator-framework/community-operators/tree/master/community-operators/prometheus).

Is the Operator Lifecycle Manager something you plan to support and update with new versions in the future, or should I rather install the prometheus-operator manually?

**Comment by LiliC** [comment]
Yes, there is a PR for this already upstream. https://github.com/operator-framework/community-operators/pull/667#issue-314606148 

Closing as this is not an issue about prometheus-operator. :)

**Comment by a-hat** [comment]
Hey @LiliC, thanks so much for your answer! :) Good to hear that there is a PR for the new version.

But even if the PR gets merged, the outdated version has been on the operatorhub for over 6 months. So I was hoping for a statement on how often the prometheus-operator team plans to update operatorhub. We would like to use the OLM to stay on top of the operator updates, and this relies on frequent updates from the operator maintainers.

Sorry if this is not the right place to ask!

**Comment by LiliC** [comment]
The Prometheus team does not support/maintain the OLM prometheus-operator chart in the communit-operator repo, it's community maintained chart as the name implies. We release prometheus-operator and then its up to the community to maintain it, if they are using it. This is similar to how the Helm chart is maintained. Hopefully, that answers the question. :)
