### ISSUE TITLE
install operator using operatorhub.io command,show this

### ISSUE THREAD

**Issue by 13567436138** [coreos/prometheus-operator#2772]
Status:
  Certs Last Updated:  <nil>
  Certs Rotate At:     <nil>
  Conditions:
    Last Transition Time:  2019-09-20T05:57:56Z
    Last Update Time:      2019-09-20T05:57:56Z
    Message:               csv in namespace with no operatorgroups
    Phase:                 Failed
    Reason:                NoOperatorGroup
  Last Transition Time:    2019-09-20T05:57:56Z
  Last Update Time:        2019-09-20T05:59:09Z
  Message:                 csv in namespace with no operatorgroups
  Phase:                   Failed
  Reason:                  NoOperatorGroup
Events:
  Type     Reason           Age                     From                        Message
  ----     ------           ----                    ----                        -------
  Warning  NoOperatorGroup  2m39s (x25 over 2m42s)  operator-lifecycle-manager  csv in namespace with no operatorgroups

**Comment by LiliC** [comment]
@13567436138 hello, this question is best asked in https://github.com/operator-framework/community-operators as thats where the prometheus-operator OLM chart lives. Closing this. :)
