### ISSUE TITLE
Prometheus rule validator rejects $externalLabels in annotations

### ISSUE THREAD

**Issue by allen13** [coreos/prometheus-operator#2774]
The prometheus-operator prometheusrule validator endpoint rejects the $externalLabels variable in prometheus-operator v0.33.0 and below. `undefined variable "$externalLabels"`

Promethues started supporting $externalLabels in v2.10.0 via this MR: https://github.com/prometheus/prometheus/pull/5463

The rule validator imports v2.9.2, the version immediately before that. https://github.com/coreos/prometheus-operator/blob/v0.33.0/go.mod#L25

Are there any plans to update this dependency soon?

Thanks!

**Comment by brancz** [comment]
I see no reason to keep that version, happy to have it be latest. Do you want to take care of that?

**Comment by allen13** [comment]
Got initial MR in. go mod vendor took the liberty of updating everything. Not sure if there is any better way to do this though.

**Comment by allen13** [comment]
Struggling with getting go mod vendor to behave as expected. Any tips for updating a dependency?
