### ISSUE TITLE
sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="request config against http://127.0.0.1:9090/api/v1/status/config: Get http://127.0.0.1:9090/api/v1/status/config: dial tcp 127.0.0.1:9090: connect: connection refused"

### ISSUE THREAD

**Issue by jnunham** [coreos/prometheus-operator#2777]
I'm trying to get Thanos set up with Prometheus Operator in an AKS cluster. I'm following [this](https://medium.com/@kakashiliu/deploy-prometheus-operator-with-thanos-60210eff172b) guide and am having issues getting the sidecar to connect to Prometheus. When I get the logs of the sidecar container, I only see:

`sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="request config against http://127.0.0.1:9090/api/v1/status/config: Get http://127.0.0.1:9090/api/v1/status/config: dial tcp 127.0.0.1:9090: connect: connection refused"`

It sounds like the only prerequisite for the sidecar to come alive is to have the secret containing the information for my storage account set up (I am using Azure storage account/container).

This is my thanos section in my prometheus-operator-values.yaml file:

```thanos: 
       baseImage: improbable/thanos
       version: v0.2.1
       peers: thanos-peers.monitoring.svc:10900
       objectStorageConfig:
       key: thanos-storage-config.yaml
       name: thanos-objstore-config```

I'm not sure what I'm missing and I would love for this to be functional. I've scoured the web for people having similar issues and nothing proposed seems to be fixing it for me.

**Comment by brancz** [comment]
This looks pretty outdated. Can you try with the latest versions of both projects?

**Comment by jnunham** [comment]
> This looks pretty outdated. Can you try with the latest versions of both projects?

@brancz Yes! This was the issue. It is now throwing an error connecting to my Azure storage account. For anyone else who was following that guide and having this issue, update the thanos section in your prometheus-operator-values.yaml file to include the latest version (which can be found on the Docker website):

version:master-2019-07-19-2c5f2cde
