### ISSUE TITLE
IngressMonitor

### ISSUE THREAD

**Issue by auhlig** [coreos/prometheus-operator#2786]
**What is missing?** **Why do we need it?**

The custom resources `ServiceMonitor`,`PodMonitor` can be used to specify a set of services and pods that should be monitored and for which the Prometheus operator generates the respective scrape config section.
That would also be very useful for k8s ingresses resources.
I'd propose to add `IngressMonitor` generating the [scrape config for ingress resources](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ingress) based on that definition.
I'd be willing to come up with a PR similar to #2566 if there's a general agreement.

**Comment by brancz** [comment]
Something like this would really be most useful for blackbox exporting right? In that case I'd prefer if we could integrate something like this into the ideas discussed in #2680.

**Comment by auhlig** [comment]
Exactly what I had in mind @brancz. Closing in favour of #2680.
