### ISSUE TITLE
Include arbitrary namespace labels

### ISSUE THREAD

**Issue by Ardiea** [coreos/prometheus-operator#2789]
On of our partners wants to apply labels to all namespaces in our k8s cluster and then have our various scrape configurations discovered and created by the prometheus-operator include those labels in every metric scraped. 

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    lob: lineofbusinessname
  name: productname-dev3
```

Then when we scrape a metric from something in that namespace, in addition to adding a label "namespace=productname-dev3" we will also include something like "namespace_label_lob=lineofbusinessname"

I don't see a mechanism for this via the prometheus-operator. One idea I came up with was some kind of "join" against `kube_namespace_labels` which comes out of kube-state-metrics, but that makes the queries much more complicated. 

I'm just looking to confirm that there isn't a means to accomplish this that I have overlooked. I will have to point them to writing regular expressions against the namespace label or using replace_label calls with similar expressions. 

**What did you do?**
Not applicable

**Did you expect to see some different?**
Not applicable

**Environment**
Not applicable

* Prometheus Operator version:

`image: quay.io/coreos/prometheus-operator:v0.29.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

    Not applicable

* Manifests:

Not applicable

* Prometheus Operator Logs:

Not applicable

**Anything else we need to know?**:

**Comment by brancz** [comment]
There's nothing like that in the Prometheus Operator and also not possible to be achieved with native Prometheus capabilities. You're gonna have to do this at query time.

**Comment by Ardiea** [comment]
Perfect, thank you!
