### ISSUE TITLE
Unify namespaces

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#279]
Most of configuration has namespace defined [as monitoring](https://github.com/coreos/prometheus-operator/search?utf8=✓&q=%22namespace%3A+monitoring%22&type=) but some of samples use [default](https://github.com/coreos/prometheus-operator/search?utf8=✓&q=%22namespace%3A+default%22&type=). 

Should this project define a recommendation for namespace? My preference is to unify all the docs over monitoring namespace.

**Comment by brancz** [comment]
The one and only reason why we used the default namespace anywhere is because it doesn't need to be created, so it's one step less to try out things.
