### ISSUE TITLE
How to add seperate Promoetheus resource for monitoring istio?

### ISSUE THREAD

**Issue by sandeeprapido** [coreos/prometheus-operator#2790]
I have deployed the Pormetheus operator helm chart to scrape Kubernetes metrics. 
Now I want to deploy another Prometheus to scrape Istio metrics.
Being an amateur to operator framework, I have a few doubts,

1) Should I install another Prometheus operator helm chart for this?
2) Can I spin up a new Prometheus instance that scrapes only Istio metrics using existing helm release?

I found a helm chart by Istio team https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator, but I don't know how to integrate this in existing prom operator helm chart

**Comment by brancz** [comment]
The Prometheus Operator works just by selecting ServiceMonitors or PodMonitors which discovers targets. I don't know the helm chart as we don't use it nor do we maintain it, but just creating a ServiceMonitor or PodMonitor that discovers the istio pods/containers should do the trick. This question would be better asked on the helm charts repo though as I don't know the setup of the helm chart, so I can only guess.

**Comment by sandeeprapido** [comment]
Thanks, I have posted this in helm chart repo.
