### ISSUE TITLE
Instructions on performing upgrades

### ISSUE THREAD

**Issue by exquisitus** [coreos/prometheus-operator#2795]
I am using an openshift v3.11.0 cluster and inside the openshift-monitoring project the prometheus-operator is to be found (installation with the default openshift playbooks).
Images: quay.io/coreos/prometheus-operator:v0.23.2 , openshift/prometheus:v2.3.2

In the documentation of your project, I read as a feature of the operator "Simple Configuration: Configure the fundamentals of Prometheus like versions". But I could not find more information.

`$ kubectl describe prometheus
Name:         k8s
Namespace:    openshift-monitoring
Labels:       prometheus=k8s
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         Prometheus
 [...]
 Version:  v2.3.2
`

Is there a way to update the version of prometheus? For example if I edit the version to 2.5.0? Thank you for any help.

**Comment by brancz** [comment]
This is really an OpenShift question, so please open a bugzilla next time, but I'll answer your question here today. The cluster-monitoring stack shipped in OpenShift 3.11 is fully immutable, and does not permit users to upgrade things arbitrarily. Changes like that will automatically be reverted. What you can do is use the operator-lifecycle-manager to provision new prometheus-operator instances to manage your Prometheus instances. While the prometheus instances themselves are not supported by Red Hat, this gives you a way to at least provision them. (note though that this is also tech preview, so only limited amount of support)
