### ISSUE TITLE
No documentation about PodMonitors

### ISSUE THREAD

**Issue by MartijnZuijd** [coreos/prometheus-operator#2796]
**What did you do?**

Disclaimer: I'm new to prometheus in general. 
I want to be able to set up a PodMonitor to monitor pods that are not directly part of 
a service to be able to scrape metrics from side cars and the like. 

**Did you expect to see some different?**

After looking through the documentation I and googling a bunch I cant to seem to find any 
direct documentation or examples on how to set up a PodMonitor for this purpose let alone how to use PodMonitors in general. 

Can the docs be supplemented with this information? or is there a good reason that the PodMonitor is not documented (Deprecated or something like that)

**Comment by brancz** [comment]
The reason is that the feature is still pretty new and we just haven't written docs yet. I believe @auhlig wanted to fix that, and I believe there is already an issue about this but can't find it right now.

**Comment by MartijnZuijd** [comment]
So how would I go about using this functionality?

**Comment by auhlig** [comment]
Sorry for the delay. I'll come up with a PR in the afternoon/latest tomorrow. 
The original issue is #2738.
@MartijnZuijd In the meantime you can find examples on how to use the Podmonitor here: https://github.com/sapcc/helm-charts/tree/master/common/prometheus-server/templates/podmonitors
