### ISSUE TITLE
How to migrate prometheus data to another prometheus pod

### ISSUE THREAD

**Issue by wenj1104** [coreos/prometheus-operator#2798]
* Prometheus Operator version:

   `quay.io/coreos/prometheus-operator:v0.26.0`
   `quay.io/prometheus/prometheus:v2.5.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-07T14:30:40Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    `kubespray`

**Anything else we need to know?**:
I want to migrate the prometheus data to another prometheus pod which is in another k8s cluster.
I found that we can use snapshot.(`https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot`.)
But in my k8s cluster, `--web.enable-admin-api` is not set. So I can not use the API to create snapshot.
```
$ kubectl -n monitoring get pod prometheus-k8s-0 -o yaml | grep -A 10 containers
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention=60d
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --web.route-prefix=/
    image: quay.io/prometheus/prometheus:v2.5.0
```

Can anyone tell me how to migrate the data to another prometheus pod which is in another k8s cluster?

**Comment by brancz** [comment]
Once shutdown, you can safely take all files in the Prometheus data directory and move it to the new volume on the other cluster.

**Comment by wenj1104** [comment]
@brancz Just need to move all the files in the /prometheus directory to the new volume, then complete the migration?

**Comment by brancz** [comment]
Yes.

**Comment by wenj1104** [comment]
@brancz Okay, thank you!
