### ISSUE TITLE
"INVALID" is not a valid start token error springboot metrics

### ISSUE THREAD

**Issue by chiragthaker** [coreos/prometheus-operator#2799]
Hi , we are trying to scrape default springboot metrics to prometheus . We use prom operator and here is my service and servicemonitor and deployment file

Servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app.kubernetes.io/name: sample-app-test
    release: spinnaker-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app-test
  endpoints:
    - name: web
      scheme: http
      path: /metrics
      interval: 15s
      honorLabels: true

Service.yaml : 

apiVersion: v1
kind: Service
metadata:
  name: sample-app-test
  namespace: demo-app
  labels:
    app.kubernetes.io/name: sample-app-test
spec:
  selector:
     app.kubernetes.io/name: sample-app-test
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP

Deployment.yaml : 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-test
  namespace: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-app-test
    spec:
      containers:
      - name: sample-app-test
        image: gcr.io/***/sample-image:0.0.2-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30

I can see my app in the targets in prometheus UI but it fails with error  as shows in the image below : 
![image](https://user-images.githubusercontent.com/53787398/66558709-4e99e700-eb54-11e9-902c-24a8b10e797e.png)

Metrics of my application is working fine locally as seen below : 

![image](https://user-images.githubusercontent.com/53787398/66558779-71c49680-eb54-11e9-8293-52f67d442901.png)

Any help to fix this would really help .

**Comment by brancz** [comment]
That format is not [Prometheus exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/). Prometheus can only ingest this format. I'm not sure what your format is.

**Comment by chiragthaker** [comment]
Hi @brancz  :  Thanks for the reply , is there a way to convert this json to prometheus expected format ( time series) outside the app , i mean is there a scrapper or something available to convert this ?

**Comment by brancz** [comment]
Possible, but I highly recommend to instead have your application expose metrics in Prometheus format.

**Comment by chiragthaker** [comment]
Do you good example on converting springboot basic metrics to prometheus understandable format.

**Comment by brancz** [comment]
Unfortunately I don't know anything about this, sorry.

**Comment by chiragthaker** [comment]
Ok thanks , may be you have any good info on scrapper or example ?

**Comment by brancz** [comment]
I know next to nothing about springboot, but at first glance this looks about right: https://www.callicoder.com/spring-boot-actuator-metrics-monitoring-dashboard-prometheus-grafana/

**Comment by pgier** [comment]
@chiragthaker Looks like you are using spring 1.x which uses it's own metrics format.  In Spring 2.x micrometer was introduced for metrics which supports several formats including Prometheus.  So first choice would be to upgrade to spring 2.x and then you'll need to add the micrometer-registry-prometheus dependency to your app, and enable the prometheus micrometer endpoint with something like `management.endpoints.web.exposure.include=prometheus`.  Then the Prometheus metrics will be available on `/actuator/prometheus`.

If you can't upgrade to spring 2, then there is a micrometer backport for 1.5 which can also enable prometheus metrics in the actuator.
https://micrometer.io/docs/ref/spring/1.5

**Comment by chiragthaker** [comment]
Thanks Guys , i managed to expose app metrics in prometheus ( time series) format. I will close this ticket off.

**Comment by tarunptala** [comment]
@chiragthaker would you mind describing what was the problem in your case and how did you resolve. we have similar issue.

**Comment by abhisheks-12** [comment]
@chiragthaker  Hey chirag how did you solve this issue ?
