### ISSUE TITLE
Prometheus Operator in federated environment

### ISSUE THREAD

**Issue by rborsaru** [coreos/prometheus-operator#2815]
Hi All. 

Trying to setup prom-oper in federated mode. I have a master and a slave EKS clusters where i have prom-oper running. 
Everything is Ingress enabled and running under /prometehus path.
Prometheus running in slave . I can check everything on http://slave.example.com/prometheus. 
In order to enable federation in master i add this:
   additionalScrapeConfigs:
     - job_name: 'federate'
       metrics_path: '/prometheus/federate'
       honor_labels: true
       scrape_interval: 15s
       params:
         'match[]':
           - '{__name__=~"..*"}'
       static_configs:
       - targets:
         - 'slave.example.com'
However i cannot see anything in master - getting this error - "Get http://slave.example.com/prometheus/federate?match%5B%5D=%7B__name__%3D~%22..%2A%22%7D: context deadline exceeded".
Any idea? 

Thank you!!

**Comment by brancz** [comment]
Can you perform these requests with wget/curl from the "master" Prometheus container successfully? If not then it's unlikely to be a Prometheus or Prometheus Operator problem.

**Comment by rborsaru** [comment]
Thanks for help. It is a communication problem between the master and the slave. Investigating it now and will get back soon with updates.

**Comment by cdesewell** [comment]
Hi @rborsaru did you get to the bottom of this? we are also trying to setup a similiar monitoring stack but can't get Prometheus Operator to listen to any external /federation endpoints.

**Comment by brancz** [comment]
Closing as there wasn’t any follow up. Should the still happen feel free to continue to comment or open a new issue! :)
