### ISSUE TITLE
Can I visit the grafana without logining by configing a basic-auth ingress rule?

### ISSUE THREAD

**Issue by wikiios** [coreos/prometheus-operator#2818]
**What did you do?**
Hello I've deployed my grafana in my company.
The grafana's config file [grafana.ini] looks below:
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [auth.basic]
    enabled = true
    [auth.proxy]
    enabled = true
    header_name = X-WEBAUTH-USER
    header_property = username
    auto_sign_up = true

And I know that I can deploy a Apache proxy to visit my grafana without logining.But can I visit my grafana just by a ingress with basic auth?

**Did you expect to see some different?**
Can I visit my grafana just by a ingress with basic auth?

**Environment**
the grafana was deployed by prometheus-operator
grafana version: 6.1.6
kubernetes version: 1.13.5
nginx-ingress-controller: 0.20.0

* Prometheus Operator version:

![image](https://user-images.githubusercontent.com/7439636/67071937-60176a80-f1b6-11e9-9849-ef388f318ed4.png)

* Kubernetes version information:

    `kubectl version`
    
![image](https://user-images.githubusercontent.com/7439636/67071964-732a3a80-f1b6-11e9-9ae9-0fd15a72a5b7.png)

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
kubeadm

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Generally speaking you can yes by using the basic auth feature of your respective ingress controller, but as you are using the helm chart I would ask to to ask your question on the helm charts repo where the prometheus operator helm chart is maintained. We neither use nor maintain the helm chart, which means we don't really know the whole setup within that, so we can only guess.

**Comment by wikiios** [comment]
just fork from 
https://github.com/helm/charts/tree/master/stable/prometheus-operator

the version is 5.5.1

**Comment by wikiios** [comment]
Sry,
Can I ask that
the [auth.proxy] way can only visit grafana by http API without logining in, not ignoring browser loggin?

**Comment by wikiios** [comment]
thx, I found my solution.
