### ISSUE TITLE
Servicemonitor create is not respecting the namespace

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#283]
**What did you do?**
```
$ cat <<EOF | kubectl create -f -
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
namespace: logging
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  jobLabel: fluentd
  selector:
    matchLabels:
      app: fluentd
  namespaceSelector:
    matchNames:    
    - logging
EOF
```
**What did you expect to see?**

create service monitor in the namespace logging

**What did you see instead? Under which circumstances?**

Service monitor was created in the context namespace (default)
```
grubio@Giancarlos-MBP:~$ kubectl get servicemonitor  -n logging
No resources found.
grubio@Giancarlos-MBP:~$ kubectl get servicemonitor  -n default
NAME      KIND
fluentd   ServiceMonitor.v1alpha1.monitoring.coreos.com
```
**environment**
prom-operator v0.8.0 
k8s 1.5.3

ps. if i run ```$ cat <<EOF | kubectl create -n logging -f - ...``` it works

**Comment by brancz** [comment]
Do the logs of the Prometheus Operator show anything? As there is no way to validate TPRs at creation at the apiserver, the error only occurs once they are processed by the Operator ... sadly.

**Comment by brancz** [comment]
Actually, re-reading the situation you described, this is intentionally not picked up by the Prometheus Operator in association with the Prometheus object, as the ServiceMonitors have to be in the same namespace as the Prometheus object that they should be selected by.

**Comment by brancz** [comment]
Sorry, third attempt ... it seems this might be a bug by third party resources in 1.5.x. I just tried this on a minikube cluster 1.6 and it doesn't seem to occur.

**Comment by gianrubio** [comment]
> Sorry, third attempt ... it seems this might be a bug by third party resources in 1.5.x. I just tried this on a minikube cluster 1.6 and it doesn't seem to occur.

That's ok, I was suspecting this was related to k8s however I can't find an issue related. If in 1.6 is fixed I'm closing this issue. Thanks as always!

**Comment by brancz** [comment]
Always happy to help if I can! :slightly_smiling_face:
