### ISSUE TITLE
PromQL: container_fs_writes_bytes_total{namespace="default"}

### ISSUE THREAD

**Issue by lwx294821** [coreos/prometheus-operator#2834]
executed PromQL  on the expression browser : 

**container_fs_writes_bytes_total{namespace="default"}**

some probelms as follow:
question one:  **cann't  get all pods in namespace "default"**
question two: **some samples (datapoints) don't have label_name "container"**

**Comment by brancz** [comment]
Sorry, this is not enough information to be able to help or troubleshoot. I'm closing this, but feel free to open a new issue with more information on what you did, what you expected and what actually happened.
