### ISSUE TITLE
Questions about service monitor

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#284]
## Namespace isolation

On https://github.com/coreos/prometheus-operator/issues/283#issuecomment-293511550, @brancz said that the service monitor and operator should be in the same namespace. 

I really like to organize all k8s related objects by namespace.  If I have a pod named fluentd, I'll always keep all related resources in the same namespace , so all services, network policy, service monitor will be in the logging namespace. Is this configurable? 

## More logs/output for the users

I created a bad service monitor, the operator doesn't generate the configuration and logs and there's no clue in the logs. When operator is parsing the service monitor, to generate a new prometheus config, it can print some debug message in the logs about discarded service monitors .

Ex. bad service monitor
```
$ cat <<EOF | kubectl create -n  logging -f -
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
namespace: logging
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  jobLabel: fluentd
  selector:
    matchLabels:
      app: fluentd
  namespaceSelector:
    matchNames:    
    - logging
EOF
```

**Comment by brancz** [comment]
It's actually the `ServiceMonitor`s selected by the `Prometheus` object that have to be in the namespace as the `Prometheus` object. This was a conscious design decision at the time. Do you think it would make sense to add the namespace selector as we have it in the `ServiceMonitor` to the selection of `ServiceMonitor`s by the Prometheus object?

**Comment by gianrubio** [comment]
Yes, for me make sense to namespace the service monitor.  The service monitor should be the same behaviour of network policies.  

```
$ kubectl get networkpolicy --all-namespaces
NAMESPACE    NAME                          POD-SELECTOR                                      AGE
logging      es-input                      component=elasticsearch                           12d
logging      es-metrics-input              component=elasticsearch                           9d
logging      fluentd-prometheus-input      app=fluentd                                       13d
logging      graylog-input                 app=graylog2-server                               13d
logging      graylog-input-legacy-access   app=graylog2-server                               2d
logging      graylog-web-input             app=graylog2-server                               13d
logging      kibana-input                  app=kibana4                                       13d
logging      kopf-input                    app=kopf                                          13d
logging      mongo-input                   component=mongo                                   13d
logging      mongo-prometheus-input        component=mongo                                   13d
logging      mongo-rs-input                component=mongo                                   13d
monitoring   alertmanager-mesh             alertmanager=alertmanager-main,app=alertmanager   50d
monitoring   alertmanager-web              alertmanager=alertmanager-main,app=alertmanager   50d
monitoring   grafana                       app=grafana                                       30d
monitoring   kube-state-metrics            app=kube-state-metrics                            50d
monitoring   node-exporter                 app=node-exporter                                 19d
monitoring   prometheus                    app=prometheus,prometheus=prometheus-k8s          50d
```

WDYT to create an argument like ``--watch-namespace``? This can be useful to have multiple prometheus in the same cluster. I'll imagine this as one prometheus for developers on namespace development and another for operations on namespace ops. When this argument is blank, operator will "scrape" service monitors in all namespaces.

This ideia is clear for you?

**Comment by brancz** [comment]
Actually the Prometheus Operator and ServiceMonitor do not need to be in the same namespace, only the Prometheus object and the ServiceMonitor object. If I'm not mistaken, then it is indeed currently the same way as NetworkPolicies. The question is just do you want the ServiceMonitor objects to be in the same namespace as your Prometheus object or in the same namespace as the Pods it ultimately selects. I can see how there could be arguments for either solutions, which is why I proposed that we may want to have a namespace selector in the Prometheus object for the ServiceMonitors it selects, just like the ServiceMonitor object has for the Services it selects.

**Comment by brancz** [comment]
@fabxc What do you think about this? I feel there are strong arguments for and against having your ServiceMonitors either grouped in one namespace, where the Prometheus object is or spread out to where the actual Pods are. I feel we may need to have this namespace selector here as well. Any thoughts?

**Comment by fabxc** [comment]
We had this discussion very early on when designing the TPRs. At least my conclusion was that ServiceMonitors can already select services from different namespaces, which is quite powerful as it is. It also makes it easy to shoot yourself in the foot as things happening in other namespaces can affect your Prometheus deployment without you having any control over it. It's necessary though for basic things like federation and meta-monitoring.  

Now, also making Prometheus servers select service monitors from other namespaces, that may again select services from other namespaces, makes it nearly impossible to track what ends up being monitored. More discussion to be found in #39.


As for better error reporting. Yes, I totally agree with you @gianrubio. Unfortunately, we cannot validate TPRs. Better logging would be an easy solution though. We could also look into sending proper k8s events or starting to investigate aggregated API servers.

**Comment by gianrubio** [comment]
I don't agree with you on `servicemonitor` can only run on operator namespace. However this operator is really consistent and has a good architecture so I'm closing this issue for now.

**Comment by fabxc** [comment]
To clarify, ServiceMonitors have to be in the same namespace as the Prometheus TPR but Prometheus TPRs do not have to be in the same namespace as the operator.
ServiceMonitors can reference services running in namespaces outside of its own.

If a Prometheus could include ServiceMonitors outside of its own namespace, which in return include services outside of their own namespaces, it becomes extremely easy for people to step on each others foot. This effectively breaks the isolation namespace mean to provide.  
The approach is consistent with other resources (secrets, configmaps, service accounts, ...), which can also not be referenced/included within the same namespace.

I think any duplication of ServiceMonitors across namespaces should be dealt with by other tooling.  
For example, if I want to run the same service in two namespaces, monitored by separate Prometheus servers in those namespaces, I could have both Prometheus servers reference a single ServiceMonitor defined in some other namespace. But then ownership of that SM is not clear and someone with privilege in that namespace could delete it and impact both Prometheus deployments.  
If each Prometheus deployment has their own ServiceMonitor, this cannot happen.

**Comment by grrywlsn** [comment]
Is this likely to be revisited? 

My use case is that I'd like to delegate monitoring of services within a namespace to the team responsible for that namespace. I'd like for them to be able to to define ServiceMonitors within their namespace, which can be picked up be a centrally managed Prometheus, running in a namespace in which they do not have admin/write access.

**Comment by brancz** [comment]
It's perfectly normal to shard Prometheus by services or teams, so each team having their own Prometheus instance(s). The integration point is actually the Alertmanager, where the grouping and routing determines who is alerted for which alerts.

**Comment by punitag** [comment]
+1 use-case same as @grrywlsn
