### ISSUE TITLE
Can serviceMonitor do something like prometheus-adapter does?

### ISSUE THREAD

**Issue by mJace** [coreos/prometheus-operator#2843]
Can serviceMonitor do something like prometheus-adapter does?

Like the `metricsQuery` we set in prometheus-adapter.

Or serviceMonitor just forwards all the metrics from the pods?

**Comment by brancz** [comment]
Can you elaborate please? What is your use case?

Generally the ServiceMonitor is just a definition to tell Prometheus which targets to scrape.

**Comment by mJace** [comment]
Oh, I see.
I think I misunderstood the role for the serviceMonitor.
Thank you.
