### ISSUE TITLE
Merge configuration using patchesStrategicMerge for resouce PrometheusRule with kustomize file

### ISSUE THREAD

**Issue by Hiteshchaudhari1** [coreos/prometheus-operator#2848]
**What is missing?**
patchesStrategicMerge doesn't work for Prometheus-rules.yaml.
merging files using patchesStrategicMerge for custom resouce PrometheusRule.

**Why do we need it?**
To segregate alerting rules for specific modules into respective directory and keep conman alerts in Prometheus-rules.yaml.

* Prometheus Operator version:
version=v0.31.1

* kubernetes version:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}

* Kustomize version:
Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:windows GoArch:amd64}

**Anything else we need to know?**:

**Comment by brancz** [comment]
Is there any way to do this with CRDs? For what it's worth we do this via jsonnet.

**Comment by lackhoa** [comment]
@ Hiteshchaudhari1 Did you find any solution for this issue?
