### ISSUE TITLE
Kubelet/0 0/10 up. Kubelet/1 0/10 up. Node Exporter 6/7 up

### ISSUE THREAD

**Issue by omnipresent07** [coreos/prometheus-operator#2852]
**What happened?**

Installed prometheus-operator with the command below:

```
helm upgrade --install prometheus stable/prometheus-operator \
--set kubeEtcd.enabled=false \
--set kubeControllerManager.enabled=false \
--set kubeScheduler.enabled=false \
--set prometheusOperator.createCustomResource=true \
--set grafana.smtp.existingSecret=smtp-secret \
--set kubelet.serviceMonitor.https=false \
--set kubelet.enabled=true \
-f values.yaml \
--namespace monitoring
```

But going to `target` shows the below targets down. 

```
monitoring/prometheus-prometheus-oper-kubelet/0 (0/10 up)
monitoring/prometheus-prometheus-oper-kubelet/1 (0/10 up)
monitoring/prometheus-prometheus-oper-node-exporter/0 (6/7 up)
```

<img width="1662" alt="Screen Shot 2019-11-11 at 3 13 15 PM" src="https://user-images.githubusercontent.com/44377678/68618060-861eea80-0496-11ea-8952-9848ee19550b.png">

**Did you expect to see some different?**

Expected to see everything up in Targets

**How to reproduce it (as minimally and precisely as possible)**:

Install Prometheus using the helm command above

**Environment**

* Prometheus Operator version:

prometheus-operator-8.1.3

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind:

DI2E

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
We neither use nor maintain the helm charts. Please open an issue on the upstream helm charts repo.
