### ISSUE TITLE
error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml

### ISSUE THREAD

**Issue by jbrunetext** [coreos/prometheus-operator#2864]
**What happened?**
error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml
when you tape : kubectl describe  po -n monitoring prometheus-my-monitor-prometheus-oper-prometheus-0

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:
install chart helm 

```
helm install my-monitor stable/prometheus-operator  --namespace=monitoring
kubectl get po -n monitoring
NAME                                                     READY   STATUS        RESTARTS   AGE
alertmanager-my-monitor-prometheus-oper-alertmanager-0   0/2     Terminating   0          2s
my-monitor-grafana-7bc98cc79f-p9p4v                      2/2     Running       0          8m13s
my-monitor-kube-state-metrics-599874757-kz2g2            1/1     Running       0          8m13s
my-monitor-prometheus-node-exporter-4x2mt                1/1     Running       0          8m13s
my-monitor-prometheus-node-exporter-hgnpm                1/1     Running       0          8m13s
my-monitor-prometheus-node-exporter-xp6m2                1/1     Running       0          8m13s
my-monitor-prometheus-oper-operator-767c777656-72p8j     2/2     Running       0          8m13s
prometheus-my-monitor-prometheus-oper-prometheus-0       0/3     Terminating   0          11s
```

**Environment**
Prod / test
* Prometheus Operator version:

    `Insert image tag or Git SHA here`

```
   Name:                   prometheus-operator
Namespace:              default
CreationTimestamp:      Mon, 18 Nov 2019 12:24:49 +0100
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.34.0
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kuberne...
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.34.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.34.0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6685db5c6 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  34m   deployment-controller  Scaled up replica set prometheus-operator-6685db5c6 to 1
```

* Kubernetes version information:

    `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    cluster rke

* Manifests:

* Prometheus Operator Logs:
```
level=info ts=2019-11-18T12:00:12.4678569Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/my-monitor-prometheus-oper-alertmanager
level=info ts=2019-11-18T12:00:12.603853932Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/my-monitor-prometheus-oper-alertmanager
level=info ts=2019-11-18T12:00:12.724180397Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/my-monitor-prometheus-oper-alertmanager
level=info ts=2019-11-18T12:00:12.804118126Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/my-monitor-prometheus-oper-alertmanager
rke@julien-SATELLITE-L70-A:/data/prometheus-op/charts$ ^C
```

**Anything else we need to know?**:
```
helm list -n monitoring
NAME      	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
my-monitor	monitoring	1       	2019-11-18 12:44:58.008332225 +0100 CET	deployed	prometheus-operator-8.2.0	0.34.0     


 kubectl get nodes
NAME           STATUS   ROLES                      AGE   VERSION
192.168.0.20   Ready    controlplane,etcd,worker   44m   v1.15.5
192.168.0.21   Ready    worker                     44m   v1.15.5
rke-worker3    Ready    worker                     44m   v1.15.5
```

**Comment by jbrunetext** [comment]
kubectl -n monitoring logs  prometheus-my-monitor-prometheus-oper-prometheus-0 prometheus
level=info ts=2019-11-18T12:05:28.126Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-11-18T12:05:28.126Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-11-18T12:05:28.127Z caller=main.go:334 host_details="(Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 prometheus-my-monitor-prometheus-oper-prometheus-0 (none))"
level=info ts=2019-11-18T12:05:28.127Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-11-18T12:05:28.127Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-11-18T12:05:28.150Z caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2019-11-18T12:05:28.153Z caller=head.go:514 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2019-11-18T12:05:28.154Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-11-18T12:05:28.157Z caller=head.go:562 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2019-11-18T12:05:28.158Z caller=main.go:672 fs_type=EXT4_SUPER_MAGIC
level=info ts=2019-11-18T12:05:28.158Z caller=main.go:673 msg="TSDB started"
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:743 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:526 msg="Stopping scrape discovery manager..."
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:540 msg="Stopping notify discovery manager..."
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:562 msg="Stopping scrape manager..."
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:536 msg="Notify discovery manager stopped"
level=info ts=2019-11-18T12:05:28.159Z caller=main.go:522 msg="Scrape discovery manager stopped"
level=info ts=2019-11-18T12:05:28.159Z caller=manager.go:814 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-11-18T12:05:28.159Z caller=manager.go:820 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-11-18T12:05:28.160Z caller=main.go:556 msg="Scrape manager stopped"
level=info ts=2019-11-18T12:05:28.164Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2019-11-18T12:05:28.164Z caller=main.go:727 msg="Notifier manager stopped"
level=error ts=2019-11-18T12:05:28.164Z caller=main.go:736 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"

**Comment by jbrunetext** [comment]
timelapse
prometheus-my-monitor-prometheus-oper-prometheus-0
192.168.0.21
Pending
0
-
error
alertmanager-my-monitor-prometheus-oper-alertmanager-0
192.168.0.21
Terminated: ExitCode:${state.terminated.exitCode}
0
0 seconds
Error: cannot find volume "config-volume" to mount into container "config-reloader"

**Comment by simonpasquier** [comment]
This looks more like a problem with the Helm chart than the operator itself.

**Comment by manikanta-kondeti** [comment]
@jbrunetext were you able to find out the fix for this?
