### ISSUE TITLE
Support "api_version" for alerting configuration

### ISSUE THREAD

**Issue by simonpasquier** [coreos/prometheus-operator#2872]
The `api_version` field in [`alertmanager_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config) allows to select which version of Alertmanager API is used by Prometheus to send alerts. The default value is still `v1` to avoid breaking deployments with old versions of Alertmanager but it is recommended to use the v2 API which is available since Alertmanager v0.16.0 (released almost one year ago).

**Comment by brancz** [comment]
let's do it :)
