### ISSUE TITLE
Setting pod annotations on a Prometheus CRD does not set the annotations on the pods

### ISSUE THREAD

**Issue by eXistenZNL** [coreos/prometheus-operator#2873]
**What happened?**

I set pod annotations on a Prometheus CRD they show up when describing the Prometheus CRD:

`$ kubectl describe prometheus k8s`

```
[...stuff...]
Pod Metadata:
  Annotations:
    some-annotation: some-value
[...more stuff...]
```
but the deployed prometheus-k8s-0 and prometheus-k8s-1 pods do not show this annotation on the pod. Setting the pod annotations manually triggers Prometheus Operator to instantly remove the annotations again.

When looking at the last-applied-config annotation, it shows this:

`$ kubectl describe prometheus k8s`

```
Annotations:
        kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{},"labels":{"prometheus.........
```
This is a clear indication that the set pod annotations are not correctly applied on the pods by Prometheus Operator.

**Did you expect to see some different?**

I would suspect Prometheus Operator to correctly apply the configured [pod metadata annotations](https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/prometheus.crd.yaml#L2857) on the pods.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Prometheus CRD with a pod metadata annotation, and see that it is not correctly applied on the deployed prometheus pods.

**Environment**

* Prometheus Operator version: v0.34.0
* Kubernetes version information: v1.14.7-gke.23
* Kubernetes cluster kind: Managed by GKE
* Manifests: See description above.
* Prometheus Operator Logs: Didn't find any relevant ones

**Anything else we need to know?**:

A ticket describing kind of the same thing (although more related to Helm) is #2294 One of the comments is that there is code supporting setting the right annotations on the pods, so I tested if it was indeed working for AlertManager and just not for Prometheus. Turns out it is also not working for AlertManager, so the claim in that ticket seems to be false.

I suspect this is exactly the same thing under water, and once applying pod annotations is correctly working for Prometheus, it could also work for AlertManager.

For good measures I added the complete Alertmanager below, which again shows that despite of setting a pod annotation, it is not applied on the pod, as shown per the the last configuration annotation at the top.

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Alertmanager","metadata":{"annotations":{},"labels":{"alertmanager":"main"},"name":"main","namespace":"monitoring"},"spec":{"baseImage":"quay.io/prometheus/alertmanager","nodeSelector":{"kubernetes.io/os":"linux"},"replicas":2,"securityContext":{"fsGroup":2000,"runAsNonRoot":true,"runAsUser":1000},"serviceAccountName":"alertmanager-main","version":"v0.18.0"}}
  creationTimestamp: "2019-11-08T18:54:09Z"
  generation: 5
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
  resourceVersion: "72180626"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/alertmanagers/main
  uid: 259c8713-0259-11ea-9c46-42010aa401fa
podMetadata:
  annotations:
    test: blah
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.18.0
```

**Comment by brancz** [comment]
`podMetadata` is part of `spec`, could you try moving it under `spec` and see if that works?

**Comment by eXistenZNL** [comment]
@brancz that seems to indeed solve the problem. I somehow overlooked the extra spec, also it's pretty vague why the CRD would allow me to put in podMetadata right under the root instead of under spec if it's it used anyway.

Anyhow, solved!

**Comment by brancz** [comment]
Unfortunately that is or was a limitation of CRDs, I think there are a few new things that we can try to prevent mistakes like these now.
