### ISSUE TITLE
Prometheus pod is not able to pick up new PrometheusRule(CRD)

### ISSUE THREAD

**Issue by bgvladedivac** [coreos/prometheus-operator#2878]
**What did you do?**
Deployed the Prometheus-Operator with helm from stable.  **Have not changed any ruleSelector** indent from values.yaml . **Created our own PrometheusRules** [CRDs]. They are  created/visible at cluster scope by browsing with kubectl. The custom one is the latest.

```
kubectl get prometheusrules -n monitoring
NAME                                                              AGE
monitoring-prometheus-oper-alertmanager.rules                     24h
monitoring-prometheus-oper-etcd                                   24h
monitoring-prometheus-oper-general.rules                          24h
monitoring-prometheus-oper-k8s.rules                              24h
monitoring-prometheus-oper-kube-apiserver.rules                   24h
monitoring-prometheus-oper-kube-prometheus-node-recording.rules   24h
monitoring-prometheus-oper-kubernetes-absent                      24h
monitoring-prometheus-oper-kubernetes-apps                        24h
monitoring-prometheus-oper-kubernetes-resources                   24h
monitoring-prometheus-oper-kubernetes-storage                     24h
monitoring-prometheus-oper-kubernetes-system                      24h
monitoring-prometheus-oper-node-exporter                          24h
monitoring-prometheus-oper-node-exporter.rules                    24h
monitoring-prometheus-oper-node-network                           24h
monitoring-prometheus-oper-node-time                              24h
monitoring-prometheus-oper-node.rules                             24h
monitoring-prometheus-oper-prometheus                             24h
monitoring-prometheus-oper-prometheus-operator                    24h
monitoring-prometheus-oper-customrules                               106m
```
I saw that prometheus pod is exposing 3 containers:

1. prometheus
2. rules-configmap-reloader
3. prometheus-config-reloader

The prometheus pod(1)  mounts a volume from a config-map. In that config map all the rules are stored. This **config map does not take under consideration the new rule**, and sticks with the previous one ( all CRDS without the latest one). 

After applying the new CRD I am having a look at the logs from the rules-configmap-reloader and there are no logs:

```
kubectl logs prometheus-monitoring-prometheus-oper-prometheus-0 -n monitoring -c rules-configmap-reloader
[root@some_hostname centos]#
```
I decided to kill the pod with the idea that the deployment would recreate it and it would apply the new configuration, but again it's not working.

I was not able to find any information anywhere else regarding this. From the source code I could see a function like:

```
// makeRulesConfigMaps takes a Prometheus configuration and rule files and
// returns a list of Kubernetes ConfigMaps to be later on mounted into the
// Prometheus instance.
// If the total size of rule files exceeds the Kubernetes ConfigMap limit,
// they are split up via the simple first-fit [1] bin packing algorithm. In the
// future this can be replaced by a more sophisticated algorithm, but for now
// simplicity should be sufficient.
// [1] https://en.wikipedia.org/wiki/Bin_packing_problem#First-fit_algorithm
func makeRulesConfigMaps(p *monitoringv1.Prometheus, ruleFiles map[string]string) ([]v1.ConfigMap, error) {
```

I am just wondering if this functionality is actually implemented ( I saw the **Changelog 0.20.0 /** 2018-06-05, where they are talking about **migration paths, but I do not consider this a migration , but an update**. I feel like that this change should be in the hands of the Prometheus-Operator controller ) or if there's something with my set up that does not allow me to do that ?

Any help/guidance/hint would be highly appreciated.

**Did you expect to see some different?**
My expectation is that the Prometheus-Operator controller would tigger a workflow that ends up with an updated config-map, so that I could see my new alert/rule. 

**Environment**

* Prometheus Operator version:

    `	Chart: prometheus-operator-7.2.0
	App Version: 0.32.0`

* Kubernetes version information:

    `kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

   AWS Managed ( EKS ) 

**Anything else we need to know?**:
The Prometheus Operator supports multiple PrometheusRules (which are Custom Resources) that you can deploy to your cluster and the Operator then discovers and configures.

https://github.com/coreos/prometheus-operator/issues/2720

**Comment by vsliouniaev** [comment]
Could you please post the prometheus object and a rules object that is not being loaded? I suspect you have a mismatch in the labels.

The `prometheus.spec.ruleSelector` and `prometheus.spec.ruleNamespaceSelector` should match the labels on the `prometheusRules` you are creating. See the API doc [here](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) for more info.

**Comment by brancz** [comment]
Additionally linting the PrometheusRule object would be helpful. You can install the linting tool with:

```
go get -u -v https://github.com/coreos/prometheus-operator/tree/master/cmd/lint
```

then you can run the linter with just:

```
lint <filename>
```

if the exit code is 0 then all is good.

**Comment by bgvladedivac** [comment]
@vsliouniaev @brancz  thanks for the support and the quick feedback. I am really appreciating that two core commiters are reacting so quickly, this is a great sign for the project :)

It was indeed the ruleSelector, however what caused the confusion is that during the initial installation all the rules created with this script https://github.com/helm/charts/blob/master/stable/prometheus-operator/hack/sync_prometheus_rules.py expose those labels:

>       prometheus: k8s
>       role: alert-rules

Also in this example the labels are indeed again the  same => https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L1-L9 

I was having the expectation that those must be shared between all alerts. In my case the real default labels are:
```
  App:      prometheus-operator
  Release:  monitoring
```
