### ISSUE TITLE
Error applying prometheuses CRD

### ISSUE THREAD

**Issue by torosent** [coreos/prometheus-operator#2880]
**What happened?**

Error applying prometheuses CRD 

`The CustomResourceDefinition "prometheus.monitoring.coreos.com" is invalid: metadata.name: Invalid value: "prometheus.monitoring.coreos.com": must be spec.names.plural+"."+spec.group`

Seems to be related to 
PR https://github.com/coreos/prometheus-operator/pull/2855/

and 
https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L9

https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L15

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml`

**Environment**

* Prometheus Operator version:
   using helm chart
   `prometheus-operator-8.2.4`

* Kubernetes version information:

    `1.16.1`

* Kubernetes cluster kind:

    `AKS`

**Comment by s-urbaniak** [comment]
@torosent indeed, good catch,cc @pgier.

**Comment by pgier** [comment]
Also reported in #2879

**Comment by s-urbaniak** [comment]
Closing as it was fixed in #2885
