### ISSUE TITLE
Ignored regex on metricRelabelings

### ISSUE THREAD

**Issue by seravat** [coreos/prometheus-operator#2895]
**What did you do?**

I applied some relabelings on a service-monitor, which works fine - basic stuff just replacing a target label with values from a source metadata label, example:

      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
          targetLabel: pod_ip
        - sourceLabels:
            - __meta_kubernetes_pod_host_ip
          targetLabel: host_ip

So now instance has the node hostname instead of the ip, great!

Now I want to apply some regex on the label so instead of having something like:
instance="inf1uklab03advlsk000.paas.xxxxxx

I can have:
instance="inf1uklab03advlsk000"

Which is a simple regex. I have tried using the regex in the relabelings and metricRelabelings, with no luck:

      metricRelabelings:
        - regex: '([^.]+)\.*'
          sourceLabels:
            - instance
          targetLabel: instance

      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          regex: '([^.]+)\.*'
          targetLabel: instance

I used the following regex expressions 

([^.]+)\.* -> does not work. If i put it in the relabelings, the relabeling is ignored. If I put it in the metricRelabelings, nothing happens. No errors either

.+?(?=\.) -> Prometheus does not start, because it does not like the ?= lookahead

[^.]* -> same as first regex

Anyone had similar issues and was able to solve them? 

* Prometheus Operator version:
Version: v0.31.1
Prometheus version: v2.14.0

* Openshift version information:
Openshift v3.11.135

Cheers,
jtavares@redhat.com

**Comment by brancz** [comment]
Do you see the config you are adding in the generated config you can see in /config in the prometheus UI?

**Comment by seravat** [comment]
Yes, the config with the regex is added correctly. I tried rolling back the prometheus version to v2.3.2, which is the "official" released with Openshift 3.11 and no luck as well.

Should I send the full service monitor and the resulting prometheus configuration?

**Comment by brancz** [comment]
Yes could you also try linting the servicemonitor with the lint tool we have here: https://github.com/coreos/prometheus-operator/tree/master/cmd/lint

**Comment by seravat** [comment]
So, the service monitor sintax is fine.

Have a look at the resulting configuration for the specific job I am using regex in:

- job_name: custom-monitoring/haproxy-exporter/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - custom-monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: node
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*).paas
    target_label: node1
    replacement: $1
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: pod_ip
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_host_ip]
    separator: ;
    regex: (.*)
    target_label: host_ip
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*).paas
    target_label: node2
    replacement: $1
    action: replace
  - source_labels: [node1]
    separator: ;
    regex: (.*).paas
    target_label: node3
    replacement: $1
    action: replace

The target looks like this:

![haproxy-exporter-targets](https://user-images.githubusercontent.com/20459255/70145476-0e5c6e00-1698-11ea-996c-2bddf0dffb76.PNG)

So the  metric_relabel_configs failed and only the relabel_configs with the default regex: (.*) succeeded.

**Comment by brancz** [comment]
Metric relabeling is something that is only done at scrape time, not at discovery time. You will never see metric relabeling result in the target labels, as only the "normal" relabeling configs apply at discovery time. I think you just want to also move those relabeling rules that you have in the metric relabeling section to the normal one.

**Comment by seravat** [comment]
That makes sense, but in the "normal" relabeling configs I have the same as in the metric relabeling (testing if it was working), example:

  metric_relabel_configs:
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*).paas
    target_label: node2
    replacement: $1
    action: replace

 relabel_configs:
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*).paas
    target_label: node1
    replacement: $1
    action: replace

**Comment by brancz** [comment]
Can you share what you see in the discovery page for these targets in the Prometheus UI? It should show the value of the `__meta_kubernetes_pod_node_name` meta label before relabeling, which should give us a clue as to why we're not seeing what we expect.

**Comment by seravat** [comment]
It does have that meta tag, and the relabeling works:
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: node
    replacement: $1
    action: replace

Here goes the discovery:

custom-monitoring/haproxy-exporter/0 
Discovered Labels	Target Labels
__address__="xx.xxx.xxx.xx:9102"
__meta_kubernetes_endpoint_address_target_kind="Pod"
__meta_kubernetes_endpoint_address_target_name="haproxy-exporter-vzglb"
__meta_kubernetes_endpoint_node_name="xxxxxxxxx.paas.xxxxxx.xxxxxx.xxxxxxx"
__meta_kubernetes_endpoint_port_name="tcp"
__meta_kubernetes_endpoint_port_protocol="TCP"
__meta_kubernetes_endpoint_ready="true"
__meta_kubernetes_endpoints_name="haproxy-exporter"
__meta_kubernetes_namespace="custom-monitoring"
__meta_kubernetes_pod_annotation_openshift_io_scc="custom-monitoring"
__meta_kubernetes_pod_annotationpresent_openshift_io_scc="true"
__meta_kubernetes_pod_container_name="haproxy-exporter"
__meta_kubernetes_pod_container_port_name="scrape"
__meta_kubernetes_pod_container_port_number="9102"
__meta_kubernetes_pod_container_port_protocol="TCP"
__meta_kubernetes_pod_controller_kind="DaemonSet"
__meta_kubernetes_pod_controller_name="haproxy-exporter"
__meta_kubernetes_pod_host_ip="xx.xxx.xxx.xx"
__meta_kubernetes_pod_ip="xx.xxx.xxx.xx"
__meta_kubernetes_pod_label_app="haproxy-exporter"
__meta_kubernetes_pod_label_controller_revision_hash="1617976081"
__meta_kubernetes_pod_label_pod_template_generation="32"
__meta_kubernetes_pod_labelpresent_app="true"
__meta_kubernetes_pod_labelpresent_controller_revision_hash="true"
__meta_kubernetes_pod_labelpresent_pod_template_generation="true"
__meta_kubernetes_pod_name="haproxy-exporter-vzglb"
__meta_kubernetes_pod_node_name="xxxxxxxxx.paas.xxxxxx.xxxxxx.xxxxxxx"
__meta_kubernetes_pod_phase="Running"
__meta_kubernetes_pod_ready="true"
__meta_kubernetes_pod_uid="c404592c-169c-11ea-bc5c-005056b35287"
__meta_kubernetes_service_label_app="haproxy-exporter"
__meta_kubernetes_service_labelpresent_app="true"
__meta_kubernetes_service_name="haproxy-exporter"
__metrics_path__="/metrics"
__scheme__="http"
job="custom-monitoring/haproxy-exporter/0"

**Comment by brancz** [comment]
Ah I see yes. Prometheus automatically anchors regex, so you need to add an additional “.*” at the end of your regex.

**Comment by seravat** [comment]
@brancz worked like a charm!!
