### ISSUE TITLE
Add ability to customize prometheus configuration, e.g. add VictoriaMetrics backend support

### ISSUE THREAD

**Issue by vkuznet** [coreos/prometheus-operator#2899]
**What is missing?**
Add ability to customize prometheus configuration, e.g. I wanted to add
[VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#prometheus-setup) setup to prometheus configuration file but I can't find how it can be easily done. The only change is required is a change to prometheus config file (not only its scrape section).

**Why do we need it?**
Users should be able to provide their own prometheus configuration file, possibly via secret functionality. As such I want to customize my prometheus service to use  VictoriaMetrics fast, cost-effective and scalable time-series database.

**Environment**

* Prometheus Operator version:
```
quay.io/coreos/prometheus-operator:v0.34.0
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
You can already configure remote write and external labels, do you need anything else?

**Comment by vkuznet** [comment]
How? I can't find proper documentation for that. Any pointers/examples will be useful.

**Comment by brancz** [comment]
The Prometheus spec has the `remoteWrite` field. Check out the [API docs](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).

**Comment by vkuznet** [comment]
great, that's what I was looking for. I just tested deployment and now I see the remote_writes in `/etc/prometheus/config_out/prometheus.env.yaml` Closing the ticket.
