### ISSUE TITLE
Allow subPath configuration for Prometheus storage VolumeMount

### ISSUE THREAD

**Issue by Rastusik** [coreos/prometheus-operator#29]
Hi,

I'm getting this error: 
```
Error opening memory series storage: could not detect storage version on disk, assuming version 0, need version 1 - please wipe storage or run a version of Prometheus compatible with storage version 0" source="main.go:181
```

when trying to mount a GlusterFS PVC (created by a StorageClass). The cause of the problem seems to be this issue: https://github.com/prometheus/prometheus/issues/953 - meaning that Prometheus needs an empty directory when initializing data. The problem is that GlusterFS contains a `.trashcan` directory in the volume root by default.

I suppose the easiest fix would be to allow a subPath configuration in the StorageSpec config specification, or even easier - to store the data into a fixed subfolder by default.

**Comment by Rastusik** [comment]
I suppose a simple subPath on this  line: https://github.com/coreos/prometheus-operator/blob/master/pkg/operator/petset.go#L180

should be sufficient

**Comment by brancz** [comment]
the general problem should also now be resolved in prometheus upstream https://github.com/prometheus/prometheus/pull/2283
