### ISSUE TITLE
failed calling webhook "prometheusrulemutate.monitoring.coreos.com

### ISSUE THREAD

**Issue by leaf-ces** [coreos/prometheus-operator#2904]
[root@ces-test01 alerting]# helm install test01   -n monitor --version 8.3.3 --set prometheusOperator.admissionWebhooks.enabled=false --set prometheusOperator.admissionWebhooks.patch.enabled=false stable/prometheus-operator
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://ces-prometheus-prometheus-operator.monitor.svc:443/admission-prometheusrules/mutate?timeout=30s: service "ces-prometheus-prometheus-operator" not found

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.
