### ISSUE TITLE
Why we are using quay.io/prometheus/busybox:latest base image.

### ISSUE THREAD

**Issue by sachinmsft** [coreos/prometheus-operator#2909]
I see that we are using quay.io/prometheus/busybox:latest base image to build prometheus-operator image. Is there any reason behind this. Can not we use alpine image or any other base OS image ?

**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
My assumption is that's because Prometheus uses  quay.io/prometheus/busybox too.

**Comment by brancz** [comment]
> My assumption is that's because Prometheus uses quay.io/prometheus/busybox too.

That's correct.

**Comment by sachinmsft** [comment]
but can we use any other base OS image e.g. alpine instead of quay.io/prometheus/busybox because prometheus-operator does not have any dependency on this base image.

**Comment by simonpasquier** [comment]
Any particular reason why alpine would be better than busybox?

**Comment by sachinmsft** [comment]
I am not saying that alpine would be better than busybox. I am just trying to understand the reason behind choosing busybox. So i would assume that busybox was chosen because Prometheus uses that otherwise any base OS image would have been good. please let me know if my understanding is not correct.

**Comment by simonpasquier** [comment]
As far as I know, you're correct. Closing for now, feel free to reopen if you need more details.
