### ISSUE TITLE
Deprecate baseImage, tag, and sha fields from CRDs

### ISSUE THREAD

**Issue by pgier** [coreos/prometheus-operator#2911]
With the addition of the `image` field in #2266 to the prometheus, alertmanager, and thanos specs, it seems that we no longer need the separate `baseImage`, `tag`, and `sha` fields.  I'm thinking that if these fields are set, we can print a warning that the Image field should be used instead.  Then we could remove these fields at some point down the road.

**Comment by brancz** [comment]
Agreed. As we have a stable API we can never remove them from the existing API, but we can not use them eventually.
