### ISSUE TITLE
Cannot add env variable from Configmap to alertmanager

### ISSUE THREAD

**Issue by grzesuav** [coreos/prometheus-operator#2915]
**What is missing?**

I need to set `http_proxy`/`https_proxy` to Alertmanager, however it is impossible to define it in Alertmanager CRD

**Why do we need it?**

I need to set proxy as env variable/

**Environment**

* Prometheus Operator version:

I believe it isn't supported in any version.

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by brancz** [comment]
Alertmanager http proxy is configured via its config file not env vars. I don’t think the env vars would do what you want.

**Comment by grzesuav** [comment]
Alertmanager requires config file to be encrypted, I could have different proxy on different clusters, I have many cluster. Setting the same proxy does not work for me, necessity of having different alertmanager conf (and encrypting it) also is not tempting.

**Comment by brancz** [comment]
Secrets are not encrypted, they are encoded. Either way, since Alertmanager doesn't support env variables for this there is no other way.

**Comment by ingvarm-gr** [comment]
The approach we take to this is to have the alertmanager configuration in a "plain YAML file" (that is, just the YAML for the alertmanager configuration file), then pull it in to a Secret manifest using something like the following in helm (if this is in templates/... we expect that the actual configuration would be in config/alertmanager-configuration.yaml).

```
apiVersion: v1
kind: Secret
metadata:
  name: <Name of alertmanager secret>
data:
  alertmanager.yaml: {{ tpl (.Files.Get "config/alertmanager-configuration.yaml") . | b64enc | quote }}

```

This allows you to version-control the configuration in a readable way, but basically relies on the `tpl` call to inject anything that's actually secret. It shoudl work well to replace other configuration values as well.

**Comment by grzesuav** [comment]
I want to have the same configuration across many environments, just want to read some env dependent config from other configmap. If I read correctly, there is no such possibility right now, I consider this as a valid feature request.

**Comment by brancz** [comment]
There is no possibility for this, and there is none planned in this exact way.

**Comment by grzesuav** [comment]
OK, so as summary :
- only valid way of customizing alertmanager set up per environment is to provide a different alertmanager.yaml config ?

**Comment by brancz** [comment]
Correct.
