### ISSUE TITLE
Consider documenting the admission webhook

### ISSUE THREAD

**Issue by mickael-carl** [coreos/prometheus-operator#2916]
**What is missing?**
Currently the operator has an awesome admission webhook to validate PrometheusRules and making sure they won't break Prometheus' configuration reload. However, there are very few mentions of that webhook in the project (the most obvious clue being a mention in the changelog, an existing issue and some tests).

**Why do we need it?**
If not specifically looking for it, as an end-user it's quite difficult to figure out this feature exists. It's also not fully trivial to setup (needs TLS, hence a sidecar such as Ghostunnel is also required).

I'd be willing to just write some doc about it, though I am unsure where would be the best fit (maybe a user-guide and a small mention in the README?)

**Comment by brancz** [comment]
You're absolutely right!

> I'd be willing to just write some doc about it, though I am unsure where would be the best fit (maybe a user-guide and a small mention in the README?)

That would be awesome! A user-guide and mentioning it in the readme sounds perfect. I'd be happy to give this a review.

**Comment by kgamanji** [comment]
+1
Thank you for raising this issue.

Documentation around admission hook would be immensely helpful, especially that  it's a extremely useful feature.

**Comment by joschi36** [comment]
@mickael-carl Did you do any progress on this one?
It would be really helpful if there is documentation for the webhooks.

**Comment by 0robustus1** [comment]
It would be worthwhile to wait with the documentation for a release that includes https://github.com/coreos/prometheus-operator/pull/3134 (or write the documentation with the PR in mind) as it makes it unnecessary to deploy a sidecar (such as ghostunnel) for the TLS handling required from Kubernetes Admission Webhooks.
