### ISSUE TITLE
`external_labels` is missing in all metrics

### ISSUE THREAD

**Issue by Janesee3** [coreos/prometheus-operator#2918]
**What did you do?**
I have a Prometheus Operator that is setup via the prometheus operator helm charts. I understand that there is a `prometheus_replica` external label that is automatically added to every metric, and I can see that configuration reflected in the Prometheus UI under `/configuration`.

**Did you expect to see some different?**
All my metrics do not have any of the external labels at all. I don't see them in `/service-discovery` either.

Mysteriously, while trying this out yesterday, the labels weren't appearing until a few hours later. However, they're nowhere to be found now, not even in the historical data (last 24 hours). I haven't touched any existing scrape configs. How can I debug this? 

**Environment**

* Prometheus Operator version:
bitnami/prometheus-operator:0.34.0

* Kubernetes version information:
EKS, Kubernetes 1.14

* Prometheus Operator Logs:

Nothing particularly jarring from the logs, everything is of the INFO log level, and repeated logs on this:
`W1218 10:07:23.050503       1 reflector.go:299] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: watch of *v1.ConfigMap ended with: too old resource version: 78389013 (78389418)`

**Comment by brancz** [comment]
External labels are only attached when data is communicated to the outside so you will see them in:

* Outgoing alerts (although we do automatically drop the "prometheus_replica" label, so alerts are unique and can be deduplicated by Alertmanager)
* Remote-read endpoint
* Remote-write
* `/federate` endpoint

You should be able to find the external labels in any of those uses. Queries, targets, discovery intentionally doesn't show them as they're about the identity of the Prometheus, so when you're querying a Prometheus instance they shouldn't be shown and would always be there anyways so arguably only additional unnecessary mental overhead :slightly_smiling_face: .

Let us know if that makes sense! :slightly_smiling_face:

**Comment by Janesee3** [comment]
Oh I see! Yup it makes sense, thanks for the pointing this out!

**Comment by aantn** [comment]
What's the easiest way to add a label universally to all scraped metrics? (I understand externalLabels is not a fit for that!)
