### ISSUE TITLE
Use target-heap-size for Prometheus 1.6

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#292]
Prometheus 1.6 allows configuring estimated memory usage by storage via a new flag that's set to an explicit target heap size.  
This is in line with how we want users to simply configure memory resource requirements and we should use it if the respective Prometheus version is used.

**Comment by sdurrheimer** [comment]
@fabxc Fixed by #295 I suppose. A new release would be awesome, if you are confident enough with it.

**Comment by fabxc** [comment]
Yes, as 1.6.1 with the crash bug fixed is release now I'll tag another release after bumping the default version to 1.6.1.
