### ISSUE TITLE
unknown field "preserveUnknownFields" when creating CRDs

### ISSUE THREAD

**Issue by kouk** [coreos/prometheus-operator#2924]
**What happened?**

While creating the CRDs I receive an error `unkown field "preserveUnknownFields"`, probably due to it's introduction here:  https://github.com/coreos/prometheus-operator/pull/2903
```
error validating data: V
alidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver
.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation of
f with --validate=false
```

**Did you expect to see some different?**

According to the README the prerequisite kubernetes version is anything greater or equal than 1.8.0:
https://github.com/coreos/prometheus-operator/blob/4f896655d1ad310747d2f1aa69f39067defbb05b/README.md

I suggest either you increase the prerequisite kubernetes version to 1.15.0 (where CRD pruning [was introduced](https://kubernetes.io/blog/2019/06/19/kubernetes-1-15-release-announcement/)) or somehow make the CRDs backward compatible again?

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
```

**Environment**

* Prometheus Operator version:

    `4f896655d1ad310747d2f1aa69f39067defbb05b`
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e
8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darw
in/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6ae
face6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux
/amd64"}
```
    
* Kubernetes cluster kind:

kops

**Comment by brancz** [comment]
cc @pgier I believe we already haven an issue for this, but I can't seem to find it right now.

**Comment by pgier** [comment]
@brancz There is the similar issue https://github.com/coreos/kube-prometheus/issues/353 in kube-prometheus, that might be what you are thinking of.
So I guess we could either drop support for v1.14 and earlier in master (it seems a bit too early to do this IMO), or try to handle the earlier versions.  For the CRDs deployed by prometheus operator, we could maybe add some logic to detect the kube versions and remove the preserveUnknownFields field if necessary.  For the generated CRD yaml examples, I'm thinking we need to generate separate CRDs to handle v1.14.

**Comment by brancz** [comment]
I tend to agree that dropping 1.14 at this point is a bit early, but on the other hand there are 3 newer minor releases. I think I would be ok with generating 1.14 compatible ones until 1.18 is released (we typically maintained 4 releases backward). I think it would be ok to ask people pre 1.15 to put the prometheus operator into managed crd mode and not bother with doing other code changes.

**Comment by kouk** [comment]
if it helps anyone, in my  case I am using https://github.com/coreos/kube-prometheus to target some 1.14 clusters so I currently have to patch the generated CRDs, doing something like this:
```
 (import 'kube-prometheus/kube-prometheus.libsonnet') + {
      prometheusOperator+:: {
        '0alertmanagerCustomResourceDefinition'+: {
          spec: std.mergePatch(super.spec, {
            preserveUnknownFields: null,
          }),
        },
        '0prometheusCustomResourceDefinition'+: {
          spec: std.mergePatch(super.spec, {
            preserveUnknownFields: null,
          }),
        },
        '0servicemonitorCustomResourceDefinition'+: {
          spec: std.mergePatch(super.spec, {
            preserveUnknownFields: null,
          }),
        },
        '0podmonitorCustomResourceDefinition'+: {
          spec: std.mergePatch(super.spec, {
            preserveUnknownFields: null,
          }),
        },
        '0prometheusruleCustomResourceDefinition'+: {
          spec: std.mergePatch(super.spec, {
            preserveUnknownFields: null,
          }),
        },
      },
   }
```
Perhaps this patch can be included in coreos/kube-prometheus.

**Comment by brancz** [comment]
Yes I think that's a good idea, and document that for 1.14 use.

**Comment by paolomainardi** [comment]
are there any updates here ? Or we just change the requirements declaring support from 1.15+ or we must provide the right CRD for 1.14.

**Comment by paolomainardi** [comment]
Bump, just faced again this very annoying problem, the only working fix for now is to download crd files, patch them and apply without the offending field.

**Comment by jasonmacdonald** [comment]
I just ran into this as well, and please be aware that Kubernetes on AWS (EKS) is locked to 1.14 with no option to upgrade right now.

**Comment by cmcconnell1** [comment]
Seconding @jasonmacdonald post above. We're also hitting this problem with all of our EKS clusters and ref: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html we are running the latest EKS kube version possible.
```
k version | grep Server
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Thanks

**Comment by pgier** [comment]
I created a PR to remove the `preserveUnknownFields` from the kube-prometheus examples (https://github.com/coreos/kube-prometheus/pull/408).  The current version of prometheus-operator (v0.35.1) seems to deploy the CRDs into Kubernetes 1.14 without any issue.  I'm guessing the client library is making the necessary removal of the incompatible field.  So this seems to be only an issue when manually applying the CRDs from the examples directory or from the current kube-prometheus examples.

Is there any other change we need to make to prometheus-operator itself?

**Comment by pgier** [comment]
Closing this since I believe this is resolved by https://github.com/coreos/kube-prometheus/pull/408
