### ISSUE TITLE
How to config sending alert to email 

### ISSUE THREAD

**Issue by taibc** [coreos/prometheus-operator#2930]
**What did you do?**
I installed prometheus-operator. Now I want to config to send an alert to my gmail. But I don't know where is the config file. I didn't found any configmap for alertmanager. How can I do that ?

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

 

`Labels:                 app=prometheus-operator-operator
                        chart=prometheus-operator-8.5.0
                        heritage=Helm
                        release=prometheus-operator`

    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

   I installed k8s using kubeadm on bare metal

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Here is all of configmap

> [root@k8s-master setup]# kubectl get configmap --all-namespaces
> NAMESPACE     NAME                                                    DATA   AGE
> kube-public   cluster-info                                            2      35m
> kube-system   calico-config                                           4      32m
> kube-system   coredns                                                 1      35m
> kube-system   extension-apiserver-authentication                      6      35m
> kube-system   kube-proxy                                              2      35m
> kube-system   kubeadm-config                                          2      35m
> kube-system   kubelet-config-1.15                                     1      35m
> monitoring    prometheus-operator-apiserver                           1      18m
> monitoring    prometheus-operator-cluster-total                       1      18m
> monitoring    prometheus-operator-controller-manager                  1      18m
> monitoring    prometheus-operator-etcd                                1      18m
> monitoring    prometheus-operator-grafana                             1      18m
> monitoring    prometheus-operator-grafana-config-dashboards           1      18m
> monitoring    prometheus-operator-grafana-datasource                  1      18m
> monitoring    prometheus-operator-grafana-test                        1      18m
> monitoring    prometheus-operator-k8s-coredns                         1      18m
> monitoring    prometheus-operator-k8s-resources-cluster               1      18m
> monitoring    prometheus-operator-k8s-resources-namespace             1      18m
> monitoring    prometheus-operator-k8s-resources-node                  1      18m
> monitoring    prometheus-operator-k8s-resources-pod                   1      18m
> monitoring    prometheus-operator-k8s-resources-workload              1      18m
> monitoring    prometheus-operator-k8s-resources-workloads-namespace   1      18m
> monitoring    prometheus-operator-kubelet                             1      18m
> monitoring    prometheus-operator-namespace-by-pod                    1      18m
> monitoring    prometheus-operator-namespace-by-workload               1      18m
> monitoring    prometheus-operator-node-cluster-rsrc-use               1      18m
> monitoring    prometheus-operator-node-rsrc-use                       1      18m
> monitoring    prometheus-operator-nodes                               1      18m
> monitoring    prometheus-operator-persistentvolumesusage              1      18m
> monitoring    prometheus-operator-pod-total                           1      18m
> monitoring    prometheus-operator-pods                                1      18m
> monitoring    prometheus-operator-prometheus                          1      18m
> monitoring    prometheus-operator-proxy                               1      18m
> monitoring    prometheus-operator-scheduler                           1      18m
> monitoring    prometheus-operator-statefulset                         1      18m
> monitoring    prometheus-operator-workload-total                      1      18m
> monitoring    prometheus-prometheus-operator-prometheus-rulefiles-0   23     18m

**Comment by simonpasquier** [comment]
You need to create the configmap object holding the Alertmanager configuration, see https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md.

See also https://www.robustperception.io/sending-email-with-the-alertmanager-via-gmail for an example of Alertmanager configuration sending alerts to Gmail.

**Comment by taibc** [comment]
@simonpasquier : Thank you. But I resolved my problem. I edited the configmap "prometheus-operator-grafana". And add blow code in grafana.ini section, and turn off the feature in gmail "Less secure app access", the it done  

```
[smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = buichitai
    password = "mypasss"
    ;cert_file =
    ;key_file =
    ;skip_verify = false
    from_address = buichitai@gmail.com
    from_name = Taibc
    ;ehlo_identity = dashboard.example.com
```
