### ISSUE TITLE
监控k8s1.15 版本 schduller 和controller-manager 过一段时间失效

### ISSUE THREAD

**Issue by VEH47** [coreos/prometheus-operator#2937]
我的 k8s集群是1.15 的版本, 在使用Prometheus-operator时, 监控schduller和controller-manager时, 刚创建的第一天, 可以正常监控, service serviceMonitor  ep 都正常的. 第二天就看到ep丢失, service  和serviceMonitor状态还是正常的.
![image](https://user-images.githubusercontent.com/41114318/71881378-2038a180-316d-11ea-8e90-8910a2943366.png)
![1578386601(1)](https://user-images.githubusercontent.com/41114318/71881411-3181ae00-316d-11ea-8f39-f3708514680c.jpg)

**Comment by juzhao** [comment]
translate to English, feel free to tell me if I am wrong, see below:
********************************
My k8s cluster version is 1.15, when using Prometheus-operator to monitor schduller and controller-manager, they could be monitored on the first day, and Service/ServiceMonitor/Endpoints are all normal, but on the second day, value in Endpoints column is "None" when checked by "kubectl get ep -n kube-system", but Service/ServiceMonitor are normal

**Comment by brancz** [comment]
Judging by what you shared it looks like this never worked. Could you share the selector you use from the `Service` to select the pods, and an example of a controller-manager pod that you have in your cluster?

**Comment by juzhao** [comment]
@VEH47 could you please provide info as @brancz mentioned?
