### ISSUE TITLE
Alertmanager service config in Prometheus Object not work

### ISSUE THREAD

**Issue by zkcrescent** [coreos/prometheus-operator#2939]
**What did you do?**
Totally following [alerting guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) (no anything change),  I'm trying to create an altermanager 
and test a alert trigger from prometheus service

**Did you expect to see some different?**

the `altermanagers` field in `Prometheus Object spec` not working, I can really view the web UIs of both `prometheus server` and `alert manager`, and trigger the `test alert rule` in guide, but I cant find any alertmanagers endpoints at the `status page of prometheus server web UI`

**Environment**

Centos 7

* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.34.0

* Kubernetes version information:

 Major:"1", Minor:"14+",  GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64",GitVersion:"v1.14.6-aliyun.1"

* Kubernetes cluster kind:

 ali cloud kubernetes

* Manifests:

![image](https://user-images.githubusercontent.com/14883259/71895470-225e2880-318c-11ea-8ed3-eadf511018ea.png)
![image](https://user-images.githubusercontent.com/14883259/71895514-36098f00-318c-11ea-85c9-3f5ef29271e8.png)
![image](https://user-images.githubusercontent.com/14883259/71895519-3c980680-318c-11ea-91ee-947477e2e55c.png)

* Prometheus Operator Logs:

In fact, I dont find any error logs about  Prometheus Operator 

**Anything else we need to know?**:
I'm totally following [installation guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md) to create prometheus operator, no anything changed

thx for your help

**Comment by brancz** [comment]
Could you share your Prometheus manifest?

**Comment by zkcrescent** [comment]
> Could you share your Prometheus manifest?

![image](https://user-images.githubusercontent.com/14883259/71945227-398b2d80-3201-11ea-8f88-fb6da771c87c.png)

![image](https://user-images.githubusercontent.com/14883259/71945286-5889bf80-3201-11ea-90e1-87cb91f2e81d.png)
![image](https://user-images.githubusercontent.com/14883259/71945295-62132780-3201-11ea-996f-deb60e5036a8.png)

would you mean these?

**Comment by brancz** [comment]
Do the logs say anything?

**Comment by zkcrescent** [comment]
> Do the prometheus logs say anything?

just `sync alertmanager` and `sync prometheus`
![image](https://user-images.githubusercontent.com/14883259/71958619-b4693e00-322b-11ea-9d66-b8de4cf874e0.png)

**Comment by brancz** [comment]
That’s the prometheus operator. What about the prometheus pod itself?

**Comment by zkcrescent** [comment]
Ha... I find this error log `level=error ts=2020-01-08T07:36:34.607811441Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:default:default\" cannot list resource \"services\" in API group \"\" in the namespace \"default\""`
I think I know how to solve this problem now, Thx for your help !
