### ISSUE TITLE
Supporting EnforcedNamespaceLabel in PrometheusRuleSpec 

### ISSUE THREAD

**Issue by benjaminhuo** [coreos/prometheus-operator#2940]
Currently , EnforcedNamespaceLabel is defined in PrometheusSpec which is global to all PrometheusRules.

Maybe we can add label similar to EnforcedNamespaceLabel in PrometheusRuleSpec , this way user can define their own rules in their own namespace.

I can help to create a PR if my proposal sounds reasonable .

Thanks
Ben

**Comment by brancz** [comment]
How would enforcing a label help if the user chooses the label to enforce? That sounds like something that should be handled outside of the PrometheusRule object in tooling. The point of the enforcedNamespaceLabel is to allow teams to run Prometheus with somewhat untrusted rules being created in other namespaces.

**Comment by benjaminhuo** [comment]
Yeah, I take a look at the code comments and it seems my proposal is not necessary because it mentions : "The label value will always be the namespace of the object that is being created."

This means the enforced namespace label's value will be the namespace where the PrometheusRule is created?

"EnforcedNamespaceLabel enforces adding a namespace label of origin for each alert and metric that is user created. The label value will always be the namespace of the object that is being created."

**Comment by brancz** [comment]
Correct.

**Comment by benjaminhuo** [comment]
I thought of a scenario where setting EnforcedNamespaceLabel in PrometheusRule might be useful:

If EnforcedNamespaceLabel is defined in PrometheusSpec globally, it will add enforced namespace label and value to all PrometheusRule instances which make all these PrometheusRules locally to their namespaces, but some PrometheusRules are meant to be globally usage

**Comment by brancz** [comment]
Yes that makes sense, I think that would rather be a configuration parameter on the Prometheus object though as we want the authority to come from there as that's what the operations team would be in charge of.

**Comment by benjaminhuo** [comment]
ok, maybe an exception can be set in the PrometheusSpec to exclude the specified PrometheusRule

**Comment by brancz** [comment]
Yes I think that would be reasonable.

**Comment by benjaminhuo** [comment]
A few questions regarding PrometheusRule, I can see from the code that:

1.  Everytime PrometheusRule CR is changed, the old configmap is deleted and a new one with the same name is created and the statefulset spec is updated, will the prometheus pod be recreated/restarted ?

2. If Multiple PrometheusRule CRs are created, and the total size exceeds one configmap limit, let's say 2 configmaps are created this time, then  and the statefulset spec is updated, will the prometheus pod be recreated/restarted ?

**Comment by sev3ryn** [comment]
@benjaminhuo have you started work on this?

@brancz what do you think, about naming attribute ignoreNamespaceLabelEnforcement(bool) and placing it under PrometheusRuleSpec? 
If parameter is set to true it will not add namespace label to metrics and alerts in this PrometheusRule

**Comment by benjaminhuo** [comment]
@sev3ryn , Sorry I has been working on other stuff and haven't started working on this yet .
I can create a PR for this if you haven't

**Comment by sev3ryn** [comment]
@benjaminhuo  already added PR

@brancz my use case for this is that we do not want to limit our tenants to be able to use only their metrics, rather we want help them not to make mistakes by not including namespace label in every single metric they touch. 
Our users are developers new to k8s and Prometheus and because of awesomely made integration with k8s (thanks to you) it is not obvious at first that k8s and Prometheus are two separate worlds, so they assume by default that k8s isolation by namespace also works in Prometheus. Also it is just convenient not to add namespace to every single metric in rule files.

On the other side we still want to deploy company wide alerts based on ingress metrics and kube-state-metric - that why we need this override.

**Comment by sev3ryn** [comment]
Also about light tenancy - it is already light even with enforcing namespaces to metrics. Users still can query metrics from other namespaces using Grafana or Prometheus UI - the only way to make this enforcement hard is to use proxy like [promql-guard](https://github.com/kfdm/promql-guard) in front of Prometheus.

More context why I came to this issue :) is you can find [in this discussion](https://groups.google.com/forum/#!topic/prometheus-users/tDchiL2kSiU)

**Comment by sev3ryn** [comment]
but we can do it as you've said with even bigger flexibility. What if we do two changes instead of one ?

1. NamespaceLabelEnforcementWhitelistSelector metav1.LabelSelector (please propose better name) in PromtheusSpec
2. CommonLabels map[string]string in PromtheusRuleSpec that will give users ability to define common labels to be added to all the metrics in rule file. E.g. it is useful to define labels app, cluster, etc only once so it will be added to all the metrics in rule file

**Comment by brancz** [comment]
The field in the prometheus spec should be something like “prometheusRulesExcludedFromEnforce”, and it should be a list of namespace+name.

The second one I’m not sure I understand, you can already add external labels to prometheus which will apply to all alerts produced and each rule can define its labels.

**Comment by sev3ryn** [comment]
> The second one I’m not sure I understand, you can already add external labels to prometheus which will apply to all alerts produced and each rule can define its labels.

Here I'm talking not about alert labels but about metric labels. E.g.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-rules
spec:
  commonLabels:
    app: myapp
    version: v1
  groups:
  - name: ./fcm-pusher.rules
    rules:
    - alert: LowSuccessRate
      expr: |
        sum(rate(http_requests_total{code="200"}[5m])) 
        / sum(rate(http_requests_total[5m])) 
        < 0.95
    - record: dc:requests_total:rate5m
      expr: | 
        sum(rate(http_requests_total[5m]))
    ....
```

this construction will rewrite expressions to 
```
sum(rate(http_requests_total{code="200", app="myapp", version="v1"}[5m])) 
/ sum(rate(http_requests_total{app="myapp", version="v1"}[5m])) 
< 0.95
and
sum(rate(http_requests_total{app="myapp", version="v1"}[5m]))
```

**Comment by brancz** [comment]
That's something that should be done with tooling before creating the PrometheusRule. If this is a practice at your organization I encourage you to build tooling for this, but it's not something that can be widely applied.

**Comment by sev3ryn** [comment]
commonLabels idea requires parsing promQL expression to add labels properly so it is not doable with templating tools. And prometheus-operator already parses promQL so it is trivial to add it here.

But if you think that prometheus operator should not do this -I'm still ok with it, I'll just have to write my own operator for prometheus operator that will translate ExtendedPromethuesRule to operators PrometheusRule :)

**Comment by sev3ryn** [comment]
regarding prometheusRulesExcludedFromEnforce - why do you think list of namespace+name is better than label selector? IMHO labels is the k8s glue that should bind components together

**Comment by brancz** [comment]
In a multi tenant environment (which `enforcedNamespaceLabel` was aimed towards), we want the ability to alert on global things to be a _very_ controlled and _very_ explicit thing. We want to avoid accidentally selecting things or users knowing magic selectors.

**Comment by sev3ryn** [comment]
created PR according to spec mentioned in https://github.com/coreos/prometheus-operator/issues/2940#issuecomment-618899612 

@brancz  on occasion please review #3207. If my changes LGTY I'll proceed with modifying  tests
