### ISSUE TITLE
How to upgrade prometheus-operator?

### ISSUE THREAD

**Issue by boxuan666** [coreos/prometheus-operator#2941]
I want to upgrade prometheus-operator from v0.16.0 to v0.33.0 
where i can get document for this?

**Comment by brancz** [comment]
That’s a huge jump, I honestly can’t tell you anything better than try and make sure you have a Kubernetes cluster that is up to date. Maybe even reinstall on a new cluster.

**Comment by boxuan666** [comment]
@brancz 
Thanks. i'll try reinstall the latest version of operator in my cluster
