### ISSUE TITLE
is there any way for obtaining metrics from grpc microservices with prometheus operator ?

### ISSUE THREAD

**Issue by soorajpv** [coreos/prometheus-operator#2945]
I am planning to make a setup of below Google demo application in kubernetes. Since all the communication in done in grpc. which exporter i should use ?
https://github.com/GoogleCloudPlatform/microservices-demo

**Comment by simonpasquier** [comment]
you probably want to look at https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by soorajpv** [comment]
is there any documentation to understand the usage of the document ?

**Comment by metalmatze** [comment]
You should most likely ask the people in the other repository. This is not specific to the Prometheus Operator at all
