### ISSUE TITLE
Unify tooling image

### ISSUE THREAD

**Issue by paulfantom** [coreos/prometheus-operator#2954]
**What is missing?**
Common tooling container image. Right now we moved most of the tooling into http://quay.io/coreos/jsonnet-ci, but since new tools are being added (https://github.com/coreos/prometheus-operator/pull/2938) it might be worthwhile to create one common image with all tools in it instead of managing multiple ones.

The easiest solution would be to add `lint` tool to `quay.io/coreos/jsonnet-ci`.
Ideally, we should change the name of that image and change location of Dockerfile to reflect that this is no longer only about jsonnet.

**Why do we need it?**
To simplify tooling management and locking versions for reproducibility

This should solve issues from https://github.com/coreos/prometheus-operator/pull/2938#issuecomment-574119036

/cc @brancz @LiliC

**Comment by metalmatze** [comment]
Sounds good. Maybe even renaming the image with a grace period of using both names?

**Comment by paulfantom** [comment]
What about push it to a new repo called `quay.io/coreos/po-tooling`? This would preserve the naming schema we have for our binaries.

**Comment by brancz** [comment]
Sgtm

**Comment by paulfantom** [comment]
I'll create the second pipeline for `quay.io/coreos/po-tooling` after #2979 is merged. This way we will have a grace period :)
