### ISSUE TITLE
Pod Environment Variables

### ISSUE THREAD

**Issue by PsychoSid** [coreos/prometheus-operator#2966]
Hi,

I did ask on the Slack channel but didn't get a reply.

When using Thanos as part of the operator we access object store behind a corporate proxy which normally entails adding environment variables to set HTTP_PROXY/HTTPS_PROXY etc.

How do I do this for the Prometheus statefulset pod to able to use the Thanos sidecar to upload to object store S3/GCS etc.

Thanks

**Comment by brancz** [comment]
Have a look at the API docs, the `containers` field merges into the generated containers, so you can specify any environment variable you want by defining a container in the `containers` array with the same name as the container you want to inject the env variable definition into.

**Comment by PsychoSid** [comment]
Oh my word. I must have gone through that 3 times and missed it every time. Many thanks. All sorted now.
