### ISSUE TITLE
Some Grafana Dashboards on Prometheus Operator 0.34.0 don't have proper expressions to read Pod Metrics

### ISSUE THREAD

**Issue by scampuza** [coreos/prometheus-operator#2969]
**What happened?**

Some Grafana Dashboards on Prometheus Operator 0.34.0 don't have proper expressions to read Pod Metrics.  In example, the "Kubernetes / Compute Resources / Pod" Dashboard, has this PromQL query for reporting the CPU usage per Pod:

sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="$namespace", **pod="$pod"**, **container!="POD"**, cluster="$cluster"}) by (container)

The issue is that the labels **pod** and **container** are being exposed by Prometheus, for that specific metric as **pod_name** and **container_name** .  

This discrepancy is recurrent among other PromQL queries in this Dashboard as well as other Grafana dashboards.

**Did you expect to see some different?**

I'd expect the Grafana Dashboards to be aligned with the Prometheus K8S metrics being exposed by the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

 ✘    ~/gumgum/eks-ocean-cluster/helm   OPS-4688 ●  kubectl -n monitor describe deployment prometheus-operator
Name:                   prometheus-operator-grafana
Namespace:              monitor
CreationTimestamp:      Wed, 22 Jan 2020 20:52:26 -0500
Labels:                 app=grafana
                        chart=grafana-4.3.2
                        heritage=Helm
                        release=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=grafana,release=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=grafana
                    release=prometheus-operator
  Annotations:      checksum/config: 0b368b53e79684321f3b8139fc47595e7d12974c73c6e6be7e0ccadac7e9e5d3
                    checksum/dashboards-json-config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
                    checksum/sc-dashboard-provider-config: b976534c72bafb252c3d936056e8dccf7b552ab628ccff86b141887ad386394d
                    checksum/secret: 339b072967008a602b19fd54f51dab24607173afbc2572b9fc6ab8c8bfdc3478
  Service Account:  prometheus-operator-grafana
  Init Containers:
   grafana-sc-datasources:
    Image:      kiwigrid/k8s-sidecar:0.1.20
    Port:       <none>
    Host Port:  <none>
    Environment:
      METHOD:    LIST
      LABEL:     grafana_datasource
      FOLDER:    /etc/grafana/provisioning/datasources
      RESOURCE:  both
    Mounts:
      /etc/grafana/provisioning/datasources from sc-datasources-volume (rw)
  Containers:
   grafana-sc-dashboard:
    Image:      kiwigrid/k8s-sidecar:0.1.20
    Port:       <none>
    Host Port:  <none>
    Environment:
      LABEL:     grafana_dashboard
      FOLDER:    /tmp/dashboards
      RESOURCE:  both
    Mounts:
      /tmp/dashboards from sc-dashboard-volume (rw)
   grafana:
    Image:       grafana/grafana:6.5.2
    Ports:       80/TCP, 3000/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:3000/api/health delay=60s timeout=30s period=10s #success=1 #failure=10
    Readiness:   http-get http://:3000/api/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GF_SECURITY_ADMIN_USER:      <set to the key 'admin-user' in secret 'prometheus-operator-grafana'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'admin-password' in secret 'prometheus-operator-grafana'>  Optional: false
    Mounts:
      /etc/grafana/grafana.ini from config (rw,path="grafana.ini")
      /etc/grafana/provisioning/dashboards/sc-dashboardproviders.yaml from sc-dashboard-provider (rw,path="provider.yaml")
      /etc/grafana/provisioning/datasources from sc-datasources-volume (rw)
      /tmp/dashboards from sc-dashboard-volume (rw)
      /var/lib/grafana from storage (rw)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-operator-grafana
    Optional:  false
   storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   sc-dashboard-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   sc-dashboard-provider:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-operator-grafana-config-dashboards
    Optional:  false
   sc-datasources-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  prometheus-operator-grafana-64d79d584f (1/1 replicas created)
NewReplicaSet:   <none>
Events:          <none>

Name:                   prometheus-operator-kube-state-metrics
Namespace:              monitor
CreationTimestamp:      Wed, 22 Jan 2020 20:52:26 -0500
Labels:                 app.kubernetes.io/instance=prometheus-operator
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-state-metrics
                        helm.sh/chart=kube-state-metrics-2.6.2
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/name=kube-state-metrics
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=prometheus-operator
                    app.kubernetes.io/name=kube-state-metrics
  Service Account:  prometheus-operator-kube-state-metrics
  Containers:
   kube-state-metrics:
    Image:      quay.io/coreos/kube-state-metrics:v1.9.2
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --collectors=certificatesigningrequests
      --collectors=configmaps
      --collectors=cronjobs
      --collectors=daemonsets
      --collectors=deployments
      --collectors=endpoints
      --collectors=horizontalpodautoscalers
      --collectors=ingresses
      --collectors=jobs
      --collectors=limitranges
      --collectors=namespaces
      --collectors=nodes
      --collectors=persistentvolumeclaims
      --collectors=persistentvolumes
      --collectors=poddisruptionbudgets
      --collectors=pods
      --collectors=replicasets
      --collectors=replicationcontrollers
      --collectors=resourcequotas
      --collectors=secrets
      --collectors=services
      --collectors=statefulsets
      --collectors=storageclasses
    Liveness:     http-get http://:8080/healthz delay=5s timeout=5s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8080/ delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-kube-state-metrics-545d8dfdc (1/1 replicas created)
Events:          <none>

Name:                   prometheus-operator-operator
Namespace:              monitor
CreationTimestamp:      Wed, 22 Jan 2020 20:52:26 -0500
Labels:                 app=prometheus-operator-operator
                        chart=prometheus-operator-8.5.13
                        heritage=Helm
                        release=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=prometheus-operator-operator,release=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=prometheus-operator-operator
                    chart=prometheus-operator-8.5.13
                    heritage=Helm
                    release=prometheus-operator
  Service Account:  prometheus-operator-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/prometheus-operator-kubelet
      --logtostderr=true
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.34.0
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --config-reloader-cpu=100m
      --config-reloader-memory=25Mi
    Environment:  <none>
    Mounts:       <none>
   tls-proxy:
    Image:      squareup/ghostunnel:v1.4.1
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      server
      --listen=:8443
      --target=127.0.0.1:8080
      --key=cert/key
      --cert=cert/cert
      --disable-authentication
    Environment:  <none>
    Mounts:
      /cert from tls-proxy-secret (ro)
  Volumes:
   tls-proxy-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-operator-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-operator-66c95855d6 (1/1 replicas created)
Events:          <none>

    ~/gumgum/eks-ocean-cluster/helm   OPS-4688 ● 
* Kubernetes version information:

v1.14.9-eks-c0eccc

* Kubernetes cluster kind:

AWS EKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
This is indeed a bug in the https://github.com/kubernetes-monitoring/kubernetes-mixin project. Would you like to fix this?

**Comment by scampuza** [comment]
@brancz  What is the Bug number reported on Kubernetes Mixin Project?  I'd be interested in tackling it

**Comment by brancz** [comment]
I don't think this was reported on the kubernetes-mixin project yet. Feel free to open an issue there and fix it!

(I'm a maintainer there as well so I can review your changes as soon as you have them out :slightly_smiling_face: )

**Comment by tcrst** [comment]
Encountering the same issue on 0.34.0 with v1.14.9-eks-c0eccc cluster.

**Comment by SVronskiy** [comment]
Same problem here. Pleae fix it.

**Comment by dormunis** [comment]
Any progress with this? Anyone figure out a quick solution until this is resolved?

**Comment by brancz** [comment]
Presumably everyone here is talking about [kube-prometheus](https://github.com/coreos/kube-prometheus), as we're getting a lot of traffic about kube-prometheus issues on the prometheus-operator repository I'm going to close this here as it's causing confusion about the separation of the two projects.

Please open a new issue in the other repository with the full details of which kubernetes version, and which kube-prometheus version you are using.
