### ISSUE TITLE
getsockopt: connection refused to kube-dns using kube-prometheus setup

### ISSUE THREAD

**Issue by Karnich** [coreos/prometheus-operator#297]
**What did you do?**
Used the yaml files from kube-prometheus under contrib, to setup grafana and prometheus-operator. Without RBAC

**What did you expect to see?**
That all targets would work and be up

**What did you see instead? Under which circumstances?**
Kube-dns target is not connecting. Connection refused
`Get http://10.244.3.96:10055/metrics: dial tcp 10.244.3.96:10055: getsockopt: connection refused`

**Environment**
Kubernetes cluster on Azure

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Created using the azure cli

* Manifests:
contrib/kube-prometheus/manifests

* Description of one of the kube-dns pods:
```
Name:           kube-dns-v19-b33cn
Namespace:      kube-system
Node:           k8s-agent-5244d31c-0/10.240.0.4
Start Time:     Wed, 19 Apr 2017 09:43:01 +0200
Labels:         k8s-app=kube-dns
                kubernetes.io/cluster-service=true
                version=v19
Status:         Running
IP:             10.244.2.123
Controllers:    ReplicationController/kube-dns-v19
Containers:
  kubedns:
    Container ID:       docker://eebbdfa49332a41230bca39571df5c17365985724e277619e5322589a6e1e25d
    Image:              gcr.io/google_containers/kubedns-amd64:1.7
    Image ID:           docker-pullable://gcr.io/google_containers/kubedns-amd64@sha256:9b811ed606fd0ec2f4a8ec420968621e91ccdfc2143879e5b12a8c8321a81ebb
    Ports:              10053/UDP, 10053/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
    Limits:
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           70Mi
    State:              Running
      Started:          Wed, 19 Apr 2017 09:43:06 +0200
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz-kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:          http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-37s56 (ro)
    Environment Variables:      <none>
  dnsmasq:
    Container ID:       docker://8767904c4072a03294bf2cbe976af95e8146a744ab1fc225c4b07c18adac3345
    Image:              gcr.io/google_containers/kube-dnsmasq-amd64:1.3
    Image ID:           docker-pullable://gcr.io/google_containers/kube-dnsmasq-amd64@sha256:33f66d91ca9806dc2f5d630be8818d93455ac855bf27c519ad483fd5972a87b8
    Ports:              53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
      --log-facility=-
    State:              Running
      Started:          Wed, 19 Apr 2017 09:43:09 +0200
    Ready:              True
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-37s56 (ro)
    Environment Variables:      <none>
  healthz:
    Container ID:       docker://246a2ffd611cac6b2e0be2347ac13f4986f38a3eae3f01340cd35a7eb0eadf61
    Image:              gcr.io/google_containers/exechealthz-amd64:1.2
    Image ID:           docker-pullable://gcr.io/google_containers/exechealthz-amd64@sha256:503e158c3f65ed7399f54010571c7c977ade7fe59010695f48d9650d83488c0a
    Port:               8080/TCP
    Args:
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      --url=/healthz-dnsmasq
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      --url=/healthz-kubedns
      --port=8080
      --quiet
    Limits:
      memory:   50Mi
    Requests:
      cpu:              10m
      memory:           50Mi
    State:              Running
      Started:          Wed, 19 Apr 2017 09:43:12 +0200
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz-dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-37s56 (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         True
  PodScheduled  True
Volumes:
  default-token-37s56:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-37s56
QoS Class:      Burstable
Tolerations:    CriticalAddonsOnly=:Exists
No events.
```

I did manage to get kube-controller-manager and kube-scheduler up as targets. But ive been unsuccessful in my attempts to connect to the kube-dns. Uncertain what the issue could be here

**Comment by brancz** [comment]
@Karnich can you elaborate what the problem was and how you solved it? From glancing over the output you provided I would guess that the dnsmasq metrics sidecar is missing in your setup.

**Comment by Karnich** [comment]
@brancz I skipped scraping it. Im new to prometheus and i honestly dont know what metrics i would gain from scraping kube-dns. 

how can i check if the dnsmasq sidecar is missing? The major differences i spotted during setting it up twice was that the kube-dns was the only part of my setup that already had an exposed endpoint. It was different ports than the setup here and with different names. dns (UDP) and dns-tcp (TCP) instead of dnsmasq and skydns (if i remember correctly?)

**Comment by brancz** [comment]
The [canonical base yaml for kube-dns](https://github.com/kubernetes/kubernetes/blob/b41e415ebd886abe6bc3d018bb44ea44cd96a937/cluster/addons/dns/kubedns-controller.yaml.base) has the `kube-dns-sidecar` container in its PodTemplate, it seems to be missing from the PodTemplate you pasted. How did you setup this cluster?

**Comment by Karnich** [comment]
Hmm interesting. The Cluster is setup using the Azure CLI. 
So basically i got a healthz instead of the sidecar >.<

**Comment by Karnich** [comment]
@brancz could you enlighten me with what metrics i could get by scraping kube-dns? so i know what im missing out on here.. Would be much appreciated :)

**Comment by Karnich** [comment]
also where do i find the canonical base yaml for the api-server? I think i got the same issue with that one

**Comment by brancz** [comment]
Things like failed dns requests, number of dns requests, etc. If you don't have an immediate need to alert on those you're probably ok with leaving them out for now. IIRC the apiserver always exposes metrics as it is a native integration, you might be running into either RBAC or secure kubelet issues, that we've been seeing a lot lately, however rather with 1.6 clusters.
