### ISSUE TITLE
What is the benefits of having multiple replicas of Prometheus cluster statefulset

### ISSUE THREAD

**Issue by sachinmsft** [coreos/prometheus-operator#2971]
I see that we have provision to configure the multiple replicas of the Prometheus statefulset cluster through Prometheus CRD.

My understanding is that all the replicas will scrap the same targets configured. 
Only benefits that I see is during update of the Prometheus cluster if update policy is rolling-update.

Is there any other benefits that I am not able to see?

**Comment by brancz** [comment]
That’s all :) it’s very unlikely that you ever want more than 2 replicas.

**Comment by sachinmsft** [comment]
Thanks.
