### ISSUE TITLE
No etcd data available for Rancher-deployed cluster

### ISSUE THREAD

**Issue by vitobotta** [coreos/prometheus-operator#2972]
**What did you do?**
Hi! I installed the operator with Helm in a cluster deployed with Rancher. The Grafana dashboards for components such as etcd/scheduler/proxy show no data, and the Prometheus dashboard shows 0 active targets for those components in the Service Discovery page.

**Did you expect to see some different?**
I was expecting to see data about etcd etc.

**Environment**
Kubernetes 1.17 deployed with Rancher 2.2.4.

* Prometheus Operator version:
v0.34.0

* Kubernetes version information:
Server Version: v1.17.2

* Kubernetes cluster kind:
I deployed the cluster with Rancher, so I am wondering if the missing data is due to the fact that Rancher deploys all the Kubernetes components as containers. Can that difference explain the problem?

* Prometheus Operator Logs:
No useful information in the logs.

Thanks in advance for any help.

**Comment by brancz** [comment]
I assume you are talking about kube-prometheus not just the prometheus-operator.

Each cluster creation tool has some subleties to it. We have patches prepares for many of them, but don't have it for rancher: https://github.com/coreos/kube-prometheus#cluster-creation-tools

Would you like to figure this out and add a patch to support ranchero

**Comment by vitobotta** [comment]
Hi @brancz ! I meant the prometheus operator. However I have been told by Rancher devs that other monitoring stacks won't fully work with Rancher deployed clusters because of their architecture. So I am still using Prometheus, Grafana etc but installed by Rancher, and that works. I was hoping to use some lighter stack because Rancher's uses quite a bit of CPU/memory for a small cluster like mine. I'll close since it's not an issue with the operator. Thanks

**Comment by shibumi** [comment]
@vitobotta I ran into the same issue, but we still deployed the prometheus-operator to rancher. This works, except for a few components like `kube-scheduler` or `kube-control-manager`. It seems that rancher has no `kube-scheduler` and/or `etcd` pods in kube-system. Is this correct or is my cluster just misconfigured?

**Comment by vitobotta** [comment]
Hi @shibumi I was trying to use this because I didn't have much resources in the old cluster. I am back to using Rancher's own monitoring stack.

**Comment by shibumi** [comment]
@vitobotta ok, we don't use the internal stack, because of the vendor-lockin. It's not possible to migrate the monitoring from rancher to google cloud etc in a sane way.  My monitoring setup is working so far (except the rules for kube-scheduler, so I hoped I could get some information about it here).

**Comment by jakerbeck** [comment]
@shibumi I found this page helpful in getting prometheus-operator to monitor Rancher's etcd, kubescheduler, kubecontrollermanager, and kubeScheduler:

https://github.com/xetys/rancher-prometheus/blob/master/docs/Monitoring%20external%20etcd.md

FYI the helm project looks like it moved to kube-prometheus-stack recently: (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

Anyways, here's how I'm able to get all of the endpoints into Prometheus:
```shell
#!/bin/bash

# Create a secret that prometheus can use to read etcd metrics:
ETCD_HOST=$(kubectl get nodes | grep 'etcd' | cut -d ' ' -f1 | head -n1)
ETCD_POD=$(kubectl get pods -n cattle-system -o wide | grep "agent.*$ETCD_HOST" | cut -d ' ' -f1)
CERTS=$(kubectl -n cattle-system exec $ETCD_POD -- ls /etc/kubernetes/ssl)
ETCD_CA_FILE="kube-ca.pem"
ETCD_CERT_FILE=$(echo "$CERTS" | grep -o "kube-etcd.*.pem" | grep -v key | head -n1)
ETCD_KEY_FILE=$(echo "$CERTS" | grep -o "kube-etcd.*.pem" | grep key | head -n1)
ETCD_CA=$(kubectl -n cattle-system exec $ETCD_POD -- cat /etc/kubernetes/ssl/$ETCD_CA_FILE)
ETCD_CERT=$(kubectl -n cattle-system exec $ETCD_POD -- cat /etc/kubernetes/ssl/$ETCD_CERT_FILE)
ETCD_KEY=$(kubectl -n cattle-system exec $ETCD_POD -- cat /etc/kubernetes/ssl/$ETCD_KEY_FILE)
kubectl -n monitoring delete secret etcd-client-cert
kubectl -n monitoring create secret generic etcd-client-cert \
  --from-literal=etcd-ca="$ETCD_CA" \
  --from-literal=etcd-client="$ETCD_CERT" \
  --from-literal=etcd-client-key="$ETCD_KEY"

# Create a list of endpoints and format it so that you can pass --set values to helm:
CONTROLPLANE_MONITORING_ENDPOINTS=$(
    I=0
    kubectl get nodes | egrep "etcd|controlplane" | cut -d ' ' -f1 | while read LINE; do
        # ping probably isn't the best, but it comes with the default alpine image that im using
        IP=$(ping -c1 $LINE | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -n1)
        echo "--set kubeEtcd.endpoints[$I]=$IP --set kubeScheduler.endpoints[$I]=$IP --set kubeControllerManager.endpoints[$I]=$IP --set kubeScheduler.endpoints[$I]=$IP"
        I=$(( $I + 1 ))
    done
)

# Install:
helm upgrade \
    --install \
    --namespace monitoring \
    $CONTROLPLANE_MONITORING_ENDPOINTS \
    --set kubeEtcd.serviceMonitor.scheme=https \
    --set kubeEtcd.serviceMonitor.insecureSkipVerify=true \
    --set kubeEtcd.serviceMonitor.caFile=/etc/prometheus/secrets/etcd-client-cert/etcd-ca \
    --set kubeEtcd.serviceMonitor.certFile=/etc/prometheus/secrets/etcd-client-cert/etcd-client \
    --set kubeEtcd.serviceMonitor.keyFile=/etc/prometheus/secrets/etcd-client-cert/etcd-client-key \
    --set prometheus.prometheusSpec.secrets[0]=etcd-client-cert \
    prometheus prometheus-community/kube-prometheus-stack
```

**Comment by shibumi** [comment]
Hi @jakerbeck  thanks a lot for this comment. Is KubeAPI still down for you, too?

**Comment by jakerbeck** [comment]
> Hi @jakerbeck thanks a lot for this comment. Is KubeAPI still down for you, too?

KubeAPI monitoring is working for my clusters.  I can see 3/3 active targets in Prometheus' [Status > Service Discovery] page and 0 alerts triggering for them.

`monitoring/a-apiserver/0 (3/3 active targets)`

**Comment by shibumi** [comment]
@jakerbeck  ok weird. It's not working in my cluster. I didn't try the etcd part, I only checked the KubeAPI, KubeScheduler, KubeController part.. and that didn't work. This is not etcd related right?
