### ISSUE TITLE
Alert Manager above 0.16.2 broken

### ISSUE THREAD

**Issue by AceHack** [coreos/prometheus-operator#2975]
I'm in EKS and If I try to use any alert manager above 0.16.2 I get the following errors.

level=warn ts=2020-01-28T13:26:12.788077549Z caller=main.go:230 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.2269-monitoring.svc:9094: lookup alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.2269-monitoring.svc on 172.20.0.10:53: no such host\n\n"

caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.2269-monitoring.svc:9094

It appears to be related to 
https://github.com/docker-library/busybox/issues/61
https://github.com/docker-library/busybox/issues/48

If I downgrade to 0.16.2 or below the error goes away

**Comment by AceHack** [comment]
Can we have the operator use the fully qualified name?

**Comment by AceHack** [comment]
Also, I take that back, I still get these errors in replica 0, just not replica 1 with 0.16.2

**Comment by simonpasquier** [comment]
Are the warnings printed repeatedly or is it just at start time?

**Comment by AceHack** [comment]
Just at start time.

**Comment by simonpasquier** [comment]
Then it's only transient and doesn't affect the operations.

**Comment by stromvirvel** [comment]
I'm having the same issue with Prometheus Operator 0.35.0 and AlertManager 0.17.0. No matter if I start 1 or 3 replicas, the Pods show this log entries:

```
klf alertmanager-infra-0 -calertmanager
level=info ts=2020-01-31T17:42:53.202329667Z caller=main.go:140 msg="Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"
level=info ts=2020-01-31T17:42:53.202611369Z caller=main.go:141 build_context="(go=go1.12.4, user=root@932a86a52b76, date=20190503-09:10:07)"
level=warn ts=2020-01-31T17:42:53.39775199Z caller=cluster.go:226 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-infra-0.alertmanager-operated.infra-gitlab.svc:9094: lookup alertmanager-infra-0.alertmanager-operated.infra-gitlab.svc on 10.3.0.10:53: no such host\n\n"
level=info ts=2020-01-31T17:42:53.397798291Z caller=cluster.go:228 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-01-31T17:42:53.397825191Z caller=main.go:230 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-infra-0.alertmanager-operated.infra-gitlab.svc:9094: lookup alertmanager-infra-0.alertmanager-operated.infra-gitlab.svc on 10.3.0.10:53: no such host\n\n"
level=info ts=2020-01-31T17:42:53.398281195Z caller=cluster.go:613 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-01-31T17:42:53.433725489Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2020-01-31T17:42:53.433927591Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 1: field apiVersion not found in type config.plain\n  line 2: field kind not found in type config.plain\n  line 3: field metadata not found in type config.plain\n  line 5: field spec not found in type config.plain"
level=info ts=2020-01-31T17:42:53.434225293Z caller=cluster.go:622 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=35.885998ms
```

This is running on Azure Kubernetes 1.15.7. The Pods stay in CrashLoopBackOff.

**Comment by stromvirvel** [comment]
I was sticking too much on the first erros with the DNS resolution, so I thought it was some kind of chicken-egg issue while the pod tries to reach itself using DNS but the pod didn't get registered in the DNS since it has not started yet.

Anyway, I just had an error in the alertmanager config, which the other lines shows :)
Therefore, please disregard.

**Comment by jomach** [comment]
I had the same problem, and my error was on the config file from the alert manager. I think this can be closed

**Comment by iamacceptable-daffodil** [comment]
I had also the same problem but making changes to my config file to correct information resolved the same.

**Comment by prsshini** [comment]
What changes did you make in the config file?  I have the same problem
