### ISSUE TITLE
Thanos ruler cannot upload blocks

### ISSUE THREAD

**Issue by yeya24** [coreos/prometheus-operator#2995]
**What happened?**

The thanos ruler cannot upload blocks to object storage because of no external label specified in Ruler.

**Potential fix**

Add `--label=ruler-replica=$(POD_NAME)`  to ruler args.

**Environment**

* Prometheus Operator version: master

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
cc @pgier

**Comment by yeya24** [comment]
Maybe it is better to be a `feature request`
