### ISSUE TITLE
Add support for query_log_file

### ISSUE THREAD

**Issue by bchess** [coreos/prometheus-operator#3025]
**What is missing?**
Prometheus v2.16.0 adds the ability to log queries to a file. It's controlled via a config field called `query_log_file`. More details are at https://github.com/prometheus/prometheus/pull/6520

prometheus-operator should support setting this field.

**Comment by tiagomeireles** [comment]
It would be awesome to have. Is there a workaround to enable this until prometheus-operator supports this config field?
