### ISSUE TITLE
Setup livenessProbe

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#303]
Today my prometheus-k8s stucked and I realised that there's no livenessProbe for most of the objects like operator, alertmanager and some examples. Is this proposital? If is not can I do a PR for fix that?

**Comment by fabxc** [comment]
Could you figure out what exactly got stuck?  

Just hitting `/status` is of course easy but not generally reliable as there could be deadlocks in the storage or querying layer that make Prometheus effectively useless even though `/status` responds just fine.

We've recently discussed whether to add matching endpoints to Prometheus that run internal checks. Just no one volunteered to add them yet.

An immediate solution for the operator could be adding a scripted liveness probe that curls the query endpoint for example and checks whether it gets a result. We are certainly happy to have that added.

**Comment by gianrubio** [comment]
> Could you figure out what exactly got stuck?

Docker stuck in one node, unfurtunaly both replicas are running in the same node - all my nodes were loaded. This can be fixed using [pod anti-afinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature) by label `kubernetes.io/hostname`

> Just hitting /status is of course easy but not generally reliable as there could be deadlocks in the storage or querying layer that make Prometheus effectively useless even though /status responds just fine.

For my case just hitting status it'll fix the issue, as I understand your suggestion to probe it's to call a url like `http://prometheus-k8s.svc/api/v1/query?query=prometheus_build_info` ?

And how about alertmanager? Check `/api/v/1status` is enough?

**Comment by fabxc** [comment]
Anti-affinity also came up before. We just haven't agreed on how we want to make it configurable via our TPRs. Enabling it by default may not generally be sane.

For now we can certainly add a liveness probe hitting `/status` – better than none for sure.
Ultimately, we want something more elaborate but that should likely be done by adding `/healthy` endpoints to AM and Prometheus directly.

If you want to file a PR adding the `/status` checks, I'm happy to merge those.

**Comment by brancz** [comment]
As far as I understand that's exactly the distinction between livenessprobes readinessprobes for Pods. :slightly_smiling_face: While both are desireable, we should add what we can today.
