### ISSUE TITLE
API server SLO recording rules produce too many metrics

### ISSUE THREAD

**Issue by omerlh** [coreos/prometheus-operator#3036]
**What happened?**
When applying `status_class:apiserver_request_total:rate3d` rule, I'm getting the following error from Prometheus:
```
query processing would load too many samples into memory in query execution
```

**Did you expect to see some different?**
Yes, didn't expect an error

**How to reproduce it (as minimally and precisely as possible)**:
Run kube-prometheus and try to apply the default rules.

As a work-around, I removed the rule:
```jsonnet
$_config+: {
      prometheus+:: {
        rules+: {
          groups:
            std.map(
              function(group)
                if group.name == 'kube-apiserver-error' then
                  group {
                    rules: std.filter(function(rule)
                        std.objectHas(rule, 'record') && (rule.record != "status_class:apiserver_request_total:rate3d" || rule.record != "status_class_5xx:apiserver_request_total:ratio_rate3d"),
                        group.rules
                      )
                  }
                else
                  group,
              super.groups
            ),
        },
      },
    },
}
```

But I think it will be better to set the requested range on the SLO lib which generate this rule.

**Comment by brancz** [comment]
@metalmatze maybe we can have some intermediate aggregation so these errors don’t happen?

**Comment by metalmatze** [comment]
The underlying query is: 
```sum by(status_class) (label_replace(rate(apiserver_request_total{job="apiserver"}[3d]), "status_class", "${1}xx", "code", "([0-9]).."))```

Not really sure how we can improve that. We could first get the rate then label_replace?

**Comment by brancz** [comment]
We could do one query per status class as opposed to doing all of them at once, just to make the query load a bit less heavy on each of them. That should be a breeze with jsonnet :wink: .

**Comment by insider89** [comment]
Have same issue. Any workarounds?

**Comment by metalmatze** [comment]
I'm working on replacing the current SLO implementation entirely with a more custom and better suited one for the apiserver.

See #382

**Comment by mazzy89** [comment]
Applied helm chart 8.13.8 but the issue still persist.

**Comment by metalmatze** [comment]
This issue actually has become obsolete, because the underlying recording rules changed.
A similar problem still exists though it's with slightly different recording rules.

As this problem was never about the Prometheus Operator itself, I'm going to close this here. Please check in the future: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411
