### ISSUE TITLE
Add weavenet monitoring and grafana dashboards for weavenet

### ISSUE THREAD

**Issue by alok87** [coreos/prometheus-operator#3044]
**Released WeaveNet Grafana Dashboards for Monitoring Weave**
Today we released grafana dashboards on the weavenet prometheus metric.

- WeaveNet (node level) https://grafana.com/grafana/dashboards/11789
- WeaveNet (cluster level) https://grafana.com/grafana/dashboards/11804

How to make weave net monitoring part of prometheus installation and where should i add grafana dashboards for it, so that everyone installing prometheus and if they have weave can benefit from it.

**Comment by lilic** [comment]
I think you might want to open this issue in kube-prometheus, as it doesn't have much to do with the operator itself, but the docs are here on how to add new dashboards in that project.
https://github.com/coreos/kube-prometheus/blob/7f2e669d46d3563e128b2879a645214e8b5993ea/docs/developing-prometheus-rules-and-grafana-dashboards.md

**Comment by alok87** [comment]
thanks will do
