### ISSUE TITLE
Question: How to monitor a second k8s cluster from prometheus-operator

### ISSUE THREAD

**Issue by egeland** [coreos/prometheus-operator#305]
This is more of a 'how to' question, so please excuse me for not following the bug report template. 😓 

I have a situation where we have a 'shared' k8s cluster, where I've installed the prometheus operator and alert manager, and have another two k8s clusters ('dev' and 'prod') we need to monitor from this 'shared' cluster. 

Ideally, we'd like to have the 'shared' cluster monitor the others without needing to install another instance of prometheus on each, but I can't really see a simple path to achieve this.
Obviously, we don't want to have to manually maintain a configuration for the endpoints on the other clusters that the 'shared' prometheus should be checking.

If I were to set up prometheus operators on the other clusters, can I set up the 'shared' prometheus to pull from these two, somehow? (I'm still very new to prometheus, as you can probably guess.)
If that's possible, then maybe I set up that way, and have the 'shared' cluster do the alerting..?

Any thoughts and help (and example config) would be very much appreciated! 😅

**Comment by brancz** [comment]
I believe what you are looking for is federated Prometheus, in which case, yes it is possible to setup, however currently not something we support with the Prometheus Operator. Prometheus federation simply pulls data from the Prometheuses running in each cluster and fans it into one database.

While federated setups are not supported today by the Prometheus Operator, we are planning to support federated setups one day.

**Comment by brancz** [comment]
Let us know if you have any more questions, I'll close this here.

**Comment by egeland** [comment]
Thanks for the reply - I hope to see federated Prometheus in this operator, soon! 👍
