### ISSUE TITLE
Documentation is not clear whether I need a store as well as a sidecar with a bucket configured

### ISSUE THREAD

**Issue by jamesla** [coreos/prometheus-operator#3055]
I am trying to deploy Thanos using the prometheus operator. Currently my stack consists of:

1. prometheus
2. thanos sidecar
3. thanos query

The sidecar is configured to use an GCS bucket which appears to be configured correctly as I can run `thanos bucket ls --objstore.config-file=/bucket.yaml` and it can connect to the bucket ok (however it has 0 objects in it).

My understanding is that I can avoid having a store api since the sidecar can handle saving and reading to the bucket (and I can also do compression from the sidecar also).

Am I missing something here? Is it possible to deploy the thanos sidecar as the sole store api?

**Comment by brancz** [comment]
The sidecar does not read from object storage ever, it only writes. For reading from object store you need to deploy a thanos store. The reason why this is not part of the prometheus operator is because it doesn't need any lifecycling as it's entirely stateless.

**Comment by jamesla** [comment]
Ok thanks @brancz working now that I have added the store. If the sidecar only writes does that mean that I can enable compacting on the sidecar and avoid deploying the compactor component?

**Comment by brancz** [comment]
No, compaction happens with the compactor component as that does it against blocks in object storage whereas prometheus (not the sidecar) would only do it against the data it knows about locally.
