### ISSUE TITLE
ThanosRuler restarts instead of reloading with new PrometheusRules

### ISSUE THREAD

**Issue by decd97** [coreos/prometheus-operator#3056]
**What happened?**
When adding new PrometheusRule objects, the ThanosRuler pod will restart instead of reloading. 

**Did you expect to see something different?**
The ThanosRuler pod remain running and a call to /-/reload so that the new rules are found.

**How to reproduce it (as minimally and precisely as possible)**:
Create a running ThanosRuler pod with some PrometheusRules. Add multiple new PrometheusRule objects and see if the pod terminates.

**Anything else we need to know?**:
We're using PersistentVolumes. It seems the pod keeps running if one PrometheusRule is added, but if multiple are created at once it terminates.
This issue also seems to occur with bulk edits/deletes of PrometheusRule objects

**Comment by yeya24** [comment]
I will take a look soon. Btw, what version of prometheus operator are you using?

**Comment by declan-dennehy-transferwise** [comment]
0.36.0

**Comment by decd97** [comment]
0.36.0

**Comment by pgier** [comment]
I'm guessing this is the same issue with alertmanager that was recently fixed (https://github.com/coreos/prometheus-operator/pull/3049).  @decd97 can you try removing the `apiVersion` and `kind` fields from your volumeClaimTemplate to see if that fixes the issue?

**Comment by decd97** [comment]
@pgier There's no `apiVersion` or `kind` in our volumeClaimTemplate so this doesn't seem to be the same issue. Here is our VolumeClaimTemplate:
```
storage:
   volumeClaimTemplate:
     spec:
       resources:
         requests:
           storage: 50Gi
       storageClassName: standard
```

**Comment by pgier** [comment]
Ok, thanks for the clarification.  I think what's happening is that each time a rule is added, we're creating a configmap which is mounted as a new rule file, and then adding another `--rule-file` argument for that specific file.  Instead, we should be using a single `--rule-file` arg with a glob and then calling `reload` as you suggested.

**Comment by jalev** [comment]
I changed the statefulset code to use a hardcoded blob path, but the effect still continues, but is not present in the Prometheus object.

The only thing I can see which is different is that every time a PrometheusRule is created the ThanosRuler object's `generation` and `resourceversion` keys end up getting changed, whereas this is not the case in the Prometheus object.

**Comment by jalev** [comment]
Oh, it's actually simpler; in the Prometheus Operator code there is an explicit check to see if the Statefulset being generated matches the Statefulset that already exists. If true, do nothing.

https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L1168-L1171

![image](https://user-images.githubusercontent.com/1196058/75997881-e7604300-5ef7-11ea-8090-9b99bf7d8417.png)

Thanos Operator code doesn't have this, so naturally the StatefulSet will always be updated regardless. 👍
