### ISSUE TITLE
Need TLS-config for Thanos

### ISSUE THREAD

**Issue by Zenlil** [coreos/prometheus-operator#3059]
**What is missing?**
Options to enable TLS-config in the Prometheus-CRD (i.e the --grpc-server-tls-* options) for the Thanos Sidecar

**Why do we need it?**
To allow multi-cluster prometheus with thanos-sidecar serve grpc to Thanos-Query in a different k8-cluster. GRPC won't work properly cross-cluster (using nginx-ingress as example) without TLS

**Environment**
2 k8-cluster
one with Thanos Store+Query+Compactor + Prom-Op with sidecar
The other one with only Prom-Op with sidecar

* Prometheus Operator version:
0.37.0

**Comment by brancz** [comment]
I think this is reasonable to add. Would you like to do a PR to add this? :)

**Comment by mikonse** [comment]
This feature would also be essential to have for the ThanosRuler-CRD as thanos only supports full tls encryption/authentication if one component of the thanos system is using it (e.g. sidecar-query).

**Comment by Zenlil** [comment]
My attempt at solving this is actually on Thanos itself with a small change: https://github.com/thanos-io/thanos/pull/2227

**Comment by lilic** [comment]
I pinged Bartek on the PR, if it doesn’t get accepted then let’s implement it in the CRD.

**Comment by bwplotka** [comment]
I Will comment on the PR, TL;DR I think we can consider it in Thanos, however still config for `mTLS` would really nice to have in prometheus operator anyway!

> This feature would also be essential to have for the ThanosRuler-CRD as thanos only supports full tls encryption/authentication if one component of the thanos system is using it (e.g. sidecar-query).

Hopefully, this is will be fixed soon: https://github.com/thanos-io/thanos/pull/2226 Wonder if that affects the format of the TLS config.

**Comment by lilic** [comment]
> Wonder if that affects the format of the TLS config this issue consider.

I mean that will be merged in the future release, so for now I would suggest we add support for the TLS config fields into the CRD natively, but something to consider!

Plan to start working on this soon, but if you want @mikonse or @Zenlil to add this support to prom-operator instead, you are welcome to.
