### ISSUE TITLE
Number 1 Getting Started issue: Where & how can I actually view the dashboard

### ISSUE THREAD

**Issue by loxal** [coreos/prometheus-operator#3062]
Figuring out how to install Prometheus and installing: 1 min
Figuring out how to view the dashboard: after 10 min still no result

Maybe this would be a good point to include right on the frontpage of the documentation, i.e. the README?

**Comment by brancz** [comment]
There are no dashboards with the prometheus operator. The prometheus operator is just a controller to deploy and manage prometheus servers. Perhaps you are looking for kube-prometheus: https://github.com/coreos/kube-prometheus?

**Comment by loxal** [comment]
@brancz Thanks a lot for this clarification! Still other people might have the same question. So a corresponding hint for those who are looking for a monitoring solution incl. a visual dashboard.
