### ISSUE TITLE
PodMonitor PodMetricsEndpoint port and targetPort do the same thing

### ISSUE THREAD

**Issue by whut** [coreos/prometheus-operator#3071]
Follow up from PR #3064 

Looks like port and targetPort from PodMonitor does the same thing: https://github.com/coreos/prometheus-operator/blob/v0.37.0/pkg/prometheus/promcfg.go#L475-L482 (except port does not support a number). This makes sense as PodMonitor is all about pods, so no service port, like in ServiceMonitor. I believe one of the two should be deprecated, IMO targetPort is term from Service, so this one should be dropped.

**Comment by pgier** [comment]
I agree the name `port` makes more sense than `targetPort` for PodMonitor. Created #3078 to deprecate `targetPort` since it seems redundant.  The only concern I have is that `targetPort` is slightly different in that it allows an integer type instead of just string which allows filtering pods based on `__meta_kubernetes_pod_container_port_number`.  If this is a feature people are using, I guess we can always either un-deprecate targetPort, or change the `port` field to handle int or string.

**Comment by dave08** [comment]
We have to specify istio's scrape port (that doesn't have a name...) where they merge the application's metrics to istio's proxy metrics... is there a workaround for specifying a number as a port? As specified here: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging the scraping should be done on /stats/prometheus:15020

**Comment by dpuzikox** [comment]
Deprecation of `targetPort` making impossible scraping of e.g. auto-injected `telegraf` with `prometheus-client` as output  because  of `telegraf` container injected without `port` section. Actually the same issue as @dave08 mentioned.

**Comment by ikarlashov** [comment]
Any updates? Looks like intention was to improve configuration but in the end it's a breaking change. port and targetPort don't do the same thing as OP stated. However, it's possible to adapt so **port** will do the same thing as targetPort by following approach mentioned by @pgier. 

Please re-open PR @whut

**Comment by jbehrends** [comment]
This issue is closed currently...  It looks like it should be re-opened... or a new issue created to address referencing a port by name(string) or number(int)...

**Comment by RafalSkolasinski** [comment]
I believe that possibility to specify just port number can be helpful in some situations. In many cases using port's name is easier / cleaner but somehow you just need to be able to specify port number. Please consider re-opening this. 

P.S. Does the `targetPort` still work? It is documented but marked as deprecated.

**Comment by wsdng** [comment]
We also need to use a port number. Same problem, different szenario: The port name is not part of deployment.yaml as we have an envoy proxy from AWS AppMesh that changes the port from an named port "http" to the unnamed 443.

**Comment by simonpasquier** [comment]
> P.S. Does the targetPort still work? It is documented but marked as deprecated.

Yes it's still supported and will continue to be by the current API version (e.g. `monitoring.coreos.com/v1`).

`targetPort` was copied from the ServiceMonitor CRD but it was confusing because it relates to Kubernetes [services](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#serviceport-v1-core).
Rather than "undeprecating" `targetPort`, I'd be ok having a new `portNumber` field since it looks like many folks would benefit from it.

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  podMetricsEndpoints:
  - portNumber: 8080
```

**Comment by jeremyspykerman** [comment]
> > P.S. Does the targetPort still work? It is documented but marked as deprecated.
> 
> Yes it's still supported and will continue to be by the current API version (e.g. `monitoring.coreos.com/v1`).
> 
> `targetPort` was copied from the ServiceMonitor CRD but it was confusing because it relates to Kubernetes [services](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#serviceport-v1-core). Rather than "undeprecating" `targetPort`, I'd be ok having a new `portNumber` field since it looks like many folks would benefit from it.
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: PodMonitor
> metadata:
>   name: example-app
> spec:
>   selector:
>     matchLabels:
>       app: example-app
>   podMetricsEndpoints:
>   - portNumber: 8080
> ```

TCP ports are typically identified by their number. Other than the fact that it would be a breaking change, wouldn't it make more sense that `port` would be the number and maybe something like `portName` would be used for named ports?

**Comment by simonpasquier** [comment]
> Other than the fact that it would be a breaking change

by itself, it's a sufficient reason to not change the existing `port` field. And which is why I'm suggesting a new field.

**Comment by chlunde** [comment]
@simonpasquier should we un-deprecate `targetPort`? It's quite a lot of discussion to read through to understand that it's not suddenly going to be removed in v1 and that it's the correct field if you don't have a named port.

**Comment by simonpasquier** [comment]
@chlunde I'd rather take a step back and understand if we need targetPort as it is now or if we can think of a different API.

**Comment by DonOtuseGH** [comment]
port number should be supported in any case, no matter if you prefer `targetPort` or `port` field

**Comment by diegocejasprieto** [comment]
I would also like to know if targetPort will be deprecated as I get several warning in my prometheus operator about it. I tried by switching it to "port" with a number but that breaks everything.

**Comment by joebowbeer** [comment]
https://github.com/prometheus-operator/prometheus-operator/pull/7150 (since v0.79.0)

`targetPort` (deprecated) accepts string or number
`port` accepts string
`portNumber` accepts number
