### ISSUE TITLE
Extend Thanos sidecar container args without replacing them

### ISSUE THREAD

**Issue by bgagnon** [coreos/prometheus-operator#3077]
**What is missing?**
The ability to add extra args to containers (eg. PrometheusSpec.spec.containers) without having to replace the `args` array completely.

**Why do we need it?**
We wanted to enable JSON logging format to Thanos (`--log.format=json`), but the only way to do this is to replace the entire `args` array. At that point, the value added by the operator is significantly reduced.

**Anything else we need to know?**:
I think this is simply a consequence of the strategic merge patch. Both cases would be valid -- replacing the `args` array, or extending it.

**Comment by pgier** [comment]
We discussed this a bit in #3069 and the conclusion was that we didn't want to support additional args.  But if there is demand for this, maybe it's worth taking another look.  @brancz WDYT?

**Comment by brancz** [comment]
If there are specific features then we should implement those specifically. Otherwise we can't have upgrade guarantees from one thanos version to the other.

**Comment by bgagnon** [comment]
@brancz I agree, let's focus on specifics

How about we replicate the `logLevel` and `logFormat` fields already supported in `PrometheusSpec`,  `AlertmanagerSpec`, `ThanosRulerSpec`, etc.?

Basically, add this to ThanosSpec:

|name|description|
|-|-|
|`logLevel`| Log level for Thanos sidecar to be configured with|
|`logFormat`| Log format for Thanos sidecar to be configured with|

Which in turn injects the args into the sidecar args. Seems reasonable to me, WDYT?

**Comment by brancz** [comment]
That works for me.
