### ISSUE TITLE
podMetadata for prometheus & alertmanager still broken for first install

### ISSUE THREAD

**Issue by jbfavre** [coreos/prometheus-operator#3088]
**What happened?**
First prometheus-operator deployment with v0.37.0
podMetadata present in Helm Release, not in custom resources alertmanager & prometheuses.

Other (older) deployments were upgraded without issue.

**Did you expect to see something different?**
I expected to see pod annotations propagated to PODs and present in custom resources

**How to reproduce it (as minimally and precisely as possible)**:
Deploy prometheus-operator for the first time

**Environment**

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.37.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**:
I deleted Alertmanager resource, which deleted alertmanager PODs which was expected.
Then, operator re-created Alertmanager custom resource.
Annotations are back in the custom resource and in PODs.

I suspect a race condition at custom resource instanciation, or an issue with older CRDs (didn't check wether I already had CRDs, but I don't think so)

**Comment by brancz** [comment]
cc @pgier

**Comment by jbfavre** [comment]
Deleting Prometheuses custom resource and recreating it also fixed the issue for prometheus

**Comment by jbfavre** [comment]
Might happen because of Helm Chart providing "old" CRDs.
PR to fix it: https://github.com/helm/charts/pull/21499

**Comment by brancz** [comment]
That would make sense :) looks like we can close this here?

**Comment by jbfavre** [comment]
Not sure I fully understand why 0.36.0 CRDs could lead to that kind of issue.
But, yes, if you think it's clearly linked, I agree we can close this
