### ISSUE TITLE
Operate the Pushgateway // honor_labels?

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/prometheus-operator#309]
Any thoughts given to running pushgateway instances via prometheus-operator?

Thanks!

**Comment by snarlysodboxer** [comment]
Also, for scrapping a pushgateway, configured via prometheus-operator or other, it's preferred to [change the config slightly](https://github.com/prometheus/pushgateway#configure-the-pushgateway-as-a-target-to-scrape) for the target, namely, setting `honor_labels: true`.

Is there any way to set this for prometheus-operator?

**Comment by brancz** [comment]
Currently there is no way to set the `honor_labels` configuration field, however, it is something we definitely need. It would need to be added to the Endpoint object struct and then inserted into the Prometheus configuration when it is generated. Do you want to try and do a PR to add it @snarlysodboxer ?

**Comment by brancz** [comment]
Other than that we're not planning to explicitly add any pushgateway specifics to the Prometheus Operator as it is otherwise treated like any other target, and should likely just run as a Deployment.

**Comment by brancz** [comment]
I'll use this issue to track the `honor_labels` implementation.

**Comment by snarlysodboxer** [comment]
@brancz Thank you for the `honor_labels` functionality! This is very useful. I wasn't able to find time yet to create a PR.

For what it's worth, since the pushgateway is not highly available, one might want to run one pushgateway per service or group of services etc. (unless there's a workflow I'm missing.) But I see your point, all one needs is a deployment, no hard stuff, so what's the point?

Thanks again
