### ISSUE TITLE
Can't see any targets

### ISSUE THREAD

**Issue by manojlds** [coreos/prometheus-operator#31]
Very new to Prometheus, and was following the steps here - https://coreos.com/blog/the-prometheus-operator.html

> Shortly after Kubernetes will update the configuration in the Prometheus pod and we can see targets showing up on the "Targets" page.

The targets page is blank for me.

The only change I did to the yaml configs was to add `namespace: kube-system` to them.

**Comment by brancz** [comment]
Are you using minikube or bootkube?

**Comment by manojlds** [comment]
I am trying this out in my production k8s cluster :) 1.4.5

**Comment by brancz** [comment]
Even better! :) Note that we have also compiled [kube-prometheus](https://github.com/coreos/kube-prometheus) to get end-to-end kubernetes monitoring with Prometheus. We typically run everything in a `monitoring` namespace and only have kubernetes specific components/services in the `kube-system` namespace. Can you elaborate which manifests you deployed to which namespace(s)?

**Comment by manojlds** [comment]
I deployed everything - the operator, prometheus, the kube-state-metrics and the node exporters - to kube-system. I also tried moving them to `default`, just in case, but still targets is blank.
```
NAME                                   READY     STATUS    RESTARTS   AGE
kube-state-metrics-3229993571-gqgsr    1/1       Running   0          9m
node-exporter-2bdsz                    1/1       Running   0          9m
node-exporter-bvefm                    1/1       Running   0          9m
node-exporter-esacs                    1/1       Running   0          9m
prometheus-k8s-0                       3/3       Running   0          20m
prometheus-operator-1078305193-57s3q   1/1       Running   0          29m
```

**Comment by manojlds** [comment]
Sincere apologies - I missed the ConfigMap part 😞 

https://coreos.com/operators/prometheus/latest/prometheus-k8s-cm.yaml

**Comment by brancz** [comment]
I was about to ask. No worries. All feedback welcome! 🙂

**Comment by sabrehagen** [comment]
Does the use of TPRs Prometheus and ServiceMonitor render the ConfigMap that @manojlds missed redundant? https://coreos.com/blog/the-prometheus-operator.html

**Comment by brancz** [comment]
@sabrehagen yes, this issue is ancient for this project :slightly_smiling_face:, back then we were not able to capture all Kubernetes components with the `ServiceMonitor`s, but nowadays we can. So unless you're doing something esoteric or very specialized you will most likely never have to specify your own configuration, but the use of `ServiceMonitor`s should cover all your needs. If not it's a bug/feature request :slightly_smiling_face: .
