### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by satishrao84** [coreos/prometheus-operator#3102]
**to build the Operator, I ran make**

Getting below error:

/Users/sanupin/go-workspace/bin/client-gen \
	--go-header-file /Users/sanupin/go-workspace/src/github.com/coreos/prometheus-operator/.header --v=1 --logtostderr \
	--input-base     "" \
	--clientset-name "versioned" \
	--input	         "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1" \
	--output-package "github.com/coreos/prometheus-operator/pkg/client"
F0327 09:12:37.954756   23620 client_generator.go:322] Failed loading boilerplate: open /Users/sanupin/go-workspace/src/github.com/coreos/prometheus-operator/.header: no such file or directory
make: *** [pkg/client/versioned/clientset.go] Error 255

I don't see a coreos directory created in my Go Workspace : 
/Users/sanupin/go-workspace/src/github.com/coreos does not exist.

**Comment by pgier** [comment]
When you cloned the git repo, did you use `go get` or `git clone`?  If you use `go get` it should create the proper directory structure for you.
`go get github.com/coreos/prometheus-operator`

**Comment by paulfantom** [comment]
Closing since issue is explained and there was no response from original poster. Please reopen if needed.
