### ISSUE TITLE
Scrapping metrics from the pod without service

### ISSUE THREAD

**Issue by stanlyDoge** [coreos/prometheus-operator#3106]
Hi,

I am using Vert.x Prometheus metrics to monitor my application running as a container in kubernetes. It does expose the metrics at the port `x`. So I am able to retrieve the metrics at `pod.ip:x/metrics`.
Is it possible to scrape the metrics using `ServiceMonitor` without creating a `Service` resource?

**Comment by yeya24** [comment]
Hey, you can check out the `PodMonitor` cr, which enables you to scrape the pod metrics directly.

**Comment by stanlyDoge** [comment]
Thank you! :)
