### ISSUE TITLE
Prometheus and Alertmanager StatefulSets are not created correctly when spec.image is used versus spec.baseImage

### ISSUE THREAD

**Issue by alex-vmw** [coreos/prometheus-operator#3110]
As per #2914, `spec.baseImage` has been deprecated in favor of `spec.image`. However, when `spec.image` is used Prometheus StatefulSet is not created correctly.

When Prometheus and Alertmanager are defined with `spec.baseImage`
```
baseImage: quay.io/prometheus/prometheus
version: v2.17.1

baseImage: quay.io/prometheus/alertmanager
version: v0.20.0
```
Prometheus and Alertmanager StatefulSets get correctly created with:
```
image: quay.io/prometheus/prometheus:v2.17.1
imagePullPolicy: IfNotPresent

image: quay.io/prometheus/alertmanager:v0.20.0
imagePullPolicy: IfNotPresent
```

When Prometheus and Alertmanager are defined with `spec.image`:
```
image: quay.io/prometheus/prometheus
version: v2.17.1

image: quay.io/prometheus/alertmanager
version: v0.20.0
```
Prometheus and Alertmanager StatefulSets get incorrectly created with (notice, that both images are missing a version and are defaulting to `latest` even when version is specified):
```
image: quay.io/prometheus/prometheus
imagePullPolicy: Always

image: quay.io/prometheus/alertmanager
imagePullPolicy: Always
```

Deprecated spec option is doing the right thing and its replacement doesn't, so please fix ASAP!

P.S. API docs (https://coreos.com/operators/prometheus/docs/latest/api.html) still say that `baseImage` is the correct spec to use.

**Comment by lilic** [comment]
What version of prometheus-operator did you see this in?

> P.S. API docs (https://coreos.com/operators/prometheus/docs/latest/api.html) still say that baseImage is the correct spec to use.

Those docs as it states in the header of the webpage are migrated to this github repo and red hat docs.
> These docs are deprecated while they are being migrated to Red Hat. For the most up to date docs, please see the corresponding GitHub repository.

**Comment by alex-vmw** [comment]
@lilic I am using the latest prometheus-operator v0.38.0, but I tested all the way down to v0.35.0 and issue was there as well.

**Comment by pgier** [comment]
In the latest github docs, these fields aren't documented as being deprecated, but they should be.  I missed that in #2914 .
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

I created #3103 which updates the deprecation notices and hopefully fixes the behaviour inconsistency.
