### ISSUE TITLE
spec.storage.volumeClaimTemplate.spec.dataSource in body must be of type object: "null"

### ISSUE THREAD

**Issue by dongwangdw** [coreos/prometheus-operator#3117]
**What happened?**

we try to build a cloud app, which calls the prometheus operator api.
When to build prometheus, we need to deploy pvc for it. But we got the error
```spec.storage.volumeClaimTemplate.spec.dataSource in body must be of type object: "null"```
This is a CR validation error. I debugged it.  This value is empty, but in the code it is as `dataSource":interface {}(nil)`. This dataSource is a pointer. It should be nil but not null.

Or did I miss anytihing?
**Did you expect to see something different?**
CR is created without any problem.
**How to reproduce it (as minimally and precisely as possible)**:
we read the pvc from yaml into go and insert it into prometheus cr.
**Environment**
ocp 4.2 

* Prometheus Operator version:
prometheus-operator 0.29
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9+icp-ee", GitCommit:"fccfecc454d446967475ce34d13d3d63d407bf09", GitTreeState:"clean", BuildDate:"2019-08-27T08:46:50Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
ocp 4.2

**Comment by lilic** [comment]
Can you reproduce this in the latest release as well? https://github.com/coreos/prometheus-operator/releases/tag/v0.38.0

**Comment by dongwangdw** [comment]
@lilic Thanks for reply.
It is a little hard to upgrade now. The best method is to find the cause and resolve this.
Hope maintainers will help. I will also keep investigating this.

**Comment by dongwangdw** [comment]
This issue looks like this one: https://github.com/coreos/prometheus-operator/issues/2399.
Not sure the same reason. 
@s-urbaniak Would you please give some advice?

**Comment by lilic** [comment]
This was fixed in https://github.com/openshift/cluster-monitoring-operator/pull/260 so should be in a later release. 

You are using OCP, are you using Prometheus Operator via operator hub?

**Comment by dongwangdw** [comment]
@lilic This is dataSource segment.  The issue you mentioned is about timestamp. maybe some relationships, but not actually the same thing.

**Comment by dongwangdw** [comment]
I have assigned an empty object to DataSource and it worked.
We read the yaml and convert it to go code and create the CR. This should be the problem.  To create from yaml or go is fine. Will close this.
