### ISSUE TITLE
Hot-Deploy in Prometheus operator without downtime

### ISSUE THREAD

**Issue by clausa20** [coreos/prometheus-operator#3120]
Hello,

I have a question,

is there a way to hot-deploy the prometheus/alertmanager resources in Kubernetes without downtime?
I mean if I would like to change/add/delete some field of the Prometheus kind resource for example the image, version, retention, any other or some configuration of the additional-scrape-config, and when that change is performed then prometheus is updated (manually or automaticaly) without downtime for example some kind of rolling-update feature of kubernetes or how deployments in kubernetes works.

Thanks.

**Comment by brancz** [comment]
Can you be more specific in what happens today that you would like to be different?

**Comment by kissmikijr** [comment]
Hey, I have the same problem, for me I have a running prometheus pod in the cluster, but I'd like to let's say add some new labels to the kind Prometheus so the labels will be on my prometheus pod, 

Right now the running prometheus pods will be killed instantly, the operator is going to start new pods with the updated specification but for the prometheus pods to be ready it takes a lot of time since they are restoring some WAL in my case it took like 10-15 minutes. A lot of alerting is based on my prometheus so while it's down it is not working.

It would be nice if it could rollout the new prometheus and just kill the old pods after the new ones are up and running.

pls let me know if it is not clear what I'd like to do or if you have any idea how to do it.

**Comment by brancz** [comment]
We already perform a rolling update, where Prometheus servers created from the same `Prometheus` object are rolled out individually.

@kissmikijr could you explain your setup a bit more? What your explaining doesn't sound like the Prometheus Operator.

**Comment by kissmikijr** [comment]
Yes ofc @brancz , I am not really familiar tbh, as I interpreted the original question it seemed really familiar what I'd like to do.

so my setup:
I have a prometheus-operator running in my cluster
I have Prometheus definitions in my cluster
something like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 2
  version: v2.15.2
```

these create `prometheus-prometheus-0`, and `prometheus-prometheus-1` pods in my cluster.

I'd like to change my Prometheus specification for example adding labels to my pods that runs in the cluster:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 2
  version: v2.15.2
  podMetadata:
    labels:
      myLabel: foo
```
When I apply this Prometheus specification change, my Prometheus pods(prometheus-prometheus-0, prometheus-prometheus-1) are gonna be terminated and the new pods are gonna be created, so until they are ready there are no prometheus pods are running in my cluster.

Sorry if I do not understand it correctly and it's not the prometheus-operators job to do this. If this is the case could you point me in the right direction where should I look for stg like this?

**Comment by brancz** [comment]
I see, in this specific case, there is some room for improvement. Specifically it seems, that [today](https://github.com/coreos/prometheus-operator/blob/ca324956d4094348c35e50413a6e4239d3d47a57/pkg/prometheus/statefulset.go#L907) we are using the [entire](https://github.com/coreos/prometheus-operator/blob/ca324956d4094348c35e50413a6e4239d3d47a57/pkg/prometheus/statefulset.go#L658-L676) labels as the selector for pods, which is actually much more specific than we need it. This results in a conflict which the prometheus operator resolves by removing and recreating the entire statefulset, unfortunately that doesn't work any other way. However, we can just add these labels to the pod, and not the selector at all, it is not required in the selector, so if someone would like to do a PR to improve and decouple these, that would be highly appreciated, and I would be more than happy to review that! :)

**Comment by alexconlin** [comment]
@brancz does the same logic need to be applied to the alertmanager stateful set as well? i think it would have the same problem when adding new labels to the alertmanager pods?

**Comment by brancz** [comment]
@alexconlin indeed. You want to take care of that?
