### ISSUE TITLE
kubernetes 1.18, kubectl apply --validate=yes can't install CRD

### ISSUE THREAD

**Issue by Slach** [coreos/prometheus-operator#3122]
**What happened?**
kubectl apply --validate=yes can't install CRD from github URL

I try to run following command
```
kubectl --namespace=prometheus apply --validate=true -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
```
and got exit code 1
and following error
```
The CustomResourceDefinition "alertmanagers.monitoring.coreos.com" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

**Did you expect to see something different?**
yes, on kubectl 1.17.x and kubernetes 1.17, I didn't get any errors

**How to reproduce it (as minimally and precisely as possible)**:
- install k8s 1.18 from zero
- try install latest CRD's with validation

**Environment**
clear installation 
minikube 1.9.1 + kubernetes 1.18

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    minikube

**Comment by donbowman** [comment]
This is due to https://github.com/kubernetes/kubernetes/pull/84920

**Comment by Slach** [comment]
@donbowman could you suggest how CRD should be changed to pass this validation?

**Comment by lilic** [comment]
Can you try to do a kubectl create instead?

**Comment by Slach** [comment]
@lilic yes, same result
```
 minikube delete
     K8S_VERSION=1.18.0
    minikube config set vm-driver none
    minikube config set kubernetes-version ${K8S_VERSION}
    minikube start

 kubectl create --namespace="prometheus" -f https://raw.githubusercontent.com/coreos/prom
etheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
```
returns following error
```
The CustomResourceDefinition "alertmanagers.monitoring.coreos.com" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

**Comment by rgordill** [comment]
See https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy.

Same with kubectl create

The option may be to create a "default" field for the property, as it is explained in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190426-crd-defaulting.md, but I don't know exactly why it is not working too on my 1.18 kubectl client, raising another exception if I do so:

```
*spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Forbidden: must not be set
```

**Comment by Slach** [comment]
@sttts
@deads2k
@lavalamp
@liggitt
@mbohlool
@apelisse

guys, could you help us and figure out how exactly defaulting works currently?
could you look at https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml#L1182

and suggest why `default: "TCP"` doesn't pass validate?

**Comment by liggitt** [comment]
defaults are only available in v1 CRDs (`apiVersion: apiextensions.k8s.io/v1`)

**Comment by liggitt** [comment]
Your options are:
* use a v1 CRD and define a default for the property
* make the property required
* stop using `list-type: map` with optional non-defaulted properties

**Comment by Slach** [comment]
@liggitt thanks for explanation

could I use `kubectl convert` for converting currently CRD and add default: "TCP"?

**Comment by sttts** [comment]
> could I use `kubectl convert` for converting currently CRD and add default: "TCP"?

I doubt kubectl can do that.

v1 and v1beta1 are not that different. Mainly the versions (no top-level version and validation anymore, just by version) structure changed. Just fix that and switch to `apiextensions.k8s.io/v1` and verify your CRD is complete after `kubectl create`. Or go to a 1.17 cluster, create the CRD with kubectl and then `kubectl get customresourcesdefinitions.v1.apiextensions.k8s.io/v1` and prune the result from defaulted, unnecessary fields.

**Comment by lilic** [comment]
We in the opeator itself create the CRD programictly on the v1beta1 CRD, there is an option to do that, which we is why we haven’t been hitting it. (Its legacy)

We will switch to using v1 CRD altogether, thanks all.

**Comment by simonpasquier** [comment]
For the same reason, the current `master` version fails to start on a v1.18 Kubernetes cluster when the `-manage-crds`flag is enabled.

```
ts=2020-04-08T12:02:16.014653541Z caller=main.go:307 msg="Unhandled error received. Exiting..." err="creating CRD: Alertmanager: CustomResourceDefinition.apiextensions.k8s.io \"alertmanagers
.monitoring.coreos.com\" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: 
this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[
ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]"       
```

Note that v0.38 isn't affected because the issue has been introduced by #3107
