### ISSUE TITLE
Alertmanager statefulset should have resource limits defined (just like prom do)

### ISSUE THREAD

**Issue by somejfn** [coreos/prometheus-operator#313]
**What did you do?**

Require the use of resource memory limit at the namespace level, by setting a quota on memory.

**What did you expect to see?**

Alertmanger statefulset POD should be running

**What did you see instead? Under which circumstances?**

Alertmanager POD is not running,  as the admission controller requires all PODs to include memory limits.

**Environment**

Tectonic 1.5.3 running on AWS with quay.io/coreos/prometheus-operator:v0.7.0

* Kubernetes version information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Tectonic 1.5.3 running on AWS

* Manifests:

Any alertmanager manifest generated by the operator.   

The resource quota on the namespace:

apiVersion: v1
kind: ResourceQuota
metadata:
  name: defaultquota
spec:
  hard:
    limits.memory: 2000000Ti

* Prometheus Operator Logs:

n/a

**Comment by brancz** [comment]
Definitely! Will make sure we add this for the next release.
