### ISSUE TITLE
Switch to apiextensions.k8s.io/v1 for CRDs

### ISSUE THREAD

**Issue by simonpasquier** [coreos/prometheus-operator#3137]
As reported in https://github.com/coreos/prometheus-operator/issues/3122, the latest version of sigs.k8s.io/controller-tools (>= v0.28.0) generate CustomResourceDefinition objects that aren't compatible with Kubernetes >= v1.18.

The [recommended](https://github.com/coreos/prometheus-operator/issues/3122#issuecomment-610421183) approach is to switch from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`.

**Comment by lilic** [comment]
cc @dgrisonnet you said you were interested in some prom-operator things to work on, this is a good one for first start!

**Comment by dgrisonnet** [comment]
Looks interesting, I'll tackle it :)
