### ISSUE TITLE
no Grafana Dashboards showing: kops 1.6.0-alpha.2, Kubernetes 1.6.2, prometheus operator v0.8.1

### ISSUE THREAD

**Issue by dmcnaught** [coreos/prometheus-operator#314]
**What did you do?**
    cd kube-prometheus-temp/contrib/kube-prometheus
    git checkout v0.8.1
    ./hack/cluster-monitoring/deploy
    kubectl -n kube-system create -f manifests/k8s/self-hosted/

**What did you expect to see?**

Dashboards in Grafana

**What did you see instead? Under which circumstances?**

no Dashboards in Grafana

**Environment**

 kops 1.6.0-alpha.2, Kubernetes 1.6.2, prometheus operator v0.8.1

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kops 1.6.0-alpha.2

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Can you try from master? And if that doesn't help can you provide the logs of the grafana-watcher? Thanks for reporting!

**Comment by dmcnaught** [comment]
master is working 😄

**Comment by brancz** [comment]
Yes I believe we had a bad manifest in the release which was quickly fixed afterwards. One day I hope to also issue releases for kube-prometheus, but that will most likely be in form of packages for helm, kpm and whatever is on the horizon. Closing here as the initial problem was solved.
