### ISSUE TITLE
Migrate kubernetes clients to 1.18 release

### ISSUE THREAD

**Issue by lilic** [coreos/prometheus-operator#3146]
Since v1.18.x is out, we should update the client-go, k/api, and k/apimachinery dependencies

To help with the migration, as there were breaking changes we should make use of https://github.com/kubernetes-sigs/clientgofix

**Comment by joelanford** [comment]
@lilic I'm willing to work on this since Operator SDK has a dependency on prometheus-operator for the ServiceMonitor types and we're trying to bump to 1.18 as well.

**Comment by lilic** [comment]
Nice, thanks! Let me know if you need anything! :)
