### ISSUE TITLE
provide option to set different roles for kubernetes_sd_config

### ISSUE THREAD

**Issue by infa-ddeore** [coreos/prometheus-operator#3148]
**What is missing?**
there doesn't seem to be a way to set different type of `kubernetes_sd_config` role, eg. i want to use [service role](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#service) to scrape the metrics from servicemonitor 

**Why do we need it?**
prometheus finds pod ips and scrapes them directly, with istio enabled in strict mode "prometheus pod --> service pod" communication breaks because that goes via istio's `PassthroughCluster` so istio acts as TCP proxy and doesn't interfere the communication

workaround is to use the prometheus that comes as istio addon which doesn't support servicemonitor, another option is to add [istio-proxy sidecar](https://github.com/istio/istio/blob/release-1.5/manifests/istio-telemetry/prometheus/templates/deployment.yaml#L59) in "prometheus" object which is kind of so much to custom change to manage

other option that would work is to make prometheus scrape the metrics from k8 service rather than the pod directly, from prometheus to k8 service communication works because istio then intercepts the traffic and makes it work with mtls, but i dont see that option present

**Environment**
k8

* Prometheus Operator version:
`8.5.0`
    `quay.io/coreos/prometheus-operator:v0.34.0`
    

**Anything else we need to know?**:
No

**Comment by brancz** [comment]
Why can't you scrape metrics from each Pod? That's how Prometheus is intended to work. Even the service type discovery would be abused here, as it's meant for blackbox target discovery, not for whitebox.

**Comment by infa-ddeore** [comment]
> Why can't you scrape metrics from each Pod? That's how Prometheus is intended to work. Even the service type discovery would be abused here, as it's meant for blackbox target discovery, not for whitebox.

the problem is prometheus cant communicate with the pod directly when istio is in `STRICT` mtls mode for the target pod's namespace, but promtheus can scrape the k8 service with `STRICT` istio mtls, thats why I want to have servicemonitor support for service role.

making service role available doesn't solve this problem 100% as scraping k8 service is like scraping one of a backend pod only.

however, if prometheus can send the host header to the pod then it will work but i found that its not possible with prometheus :-(
prometheus --> scrape pod directly (with "Host: k8_service_name" header) will work even if istio enforces strict mtls. But to be able to send the host header from prometheus is different topic.

So this feature request will solve the partial problem with istio strict mtls service pod scraped by prometheus.

you can decide whether to make this feature available or not.

**Comment by brancz** [comment]
This seems like a very special request for a very narrow use case of a system that violates Prometheus best practices. I recommend that you use the `additionalScrapeConfigs` feature which allows you to specify any Prometheus scrape config you want.

Aside from that istio should allow some mechanism other than the HOST header if they ever want to play well with the Prometheus ecosystem. Ideally something where Prometheus can still scrape the targets directly.
