### ISSUE TITLE
Add ImagePullSecrets to support private registries

### ISSUE THREAD

**Issue by nirdothan** [coreos/prometheus-operator#315]
When specifying a baseImage in a [Prometheus TPR](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) and in an [Alertmanager TPR](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) there is no way to provide  [ImagePullSecrets](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) as in [kube pod spec,](https://kubernetes.io/docs/api-reference/v1.6/#podspec-v1-core) to authenticate with private secure registries.

As a consequence, Operator cannot manage Prometheus and Alertmanagers if their images are not maintained in public registries. This is a limitation, if your environment is not open to the public internet, or if you simply want to maintain your own images in a private registry.

 I am suggesting to extend the TPR spec to support optional ImagePullSecrets and if specified, include them in Prometheus and Alertmanager StatefulSets on creation and update.

PR is coming

**Comment by brancz** [comment]
Thanks for reporting, yes that totally makes sense! Looking forward to the PR! :slightly_smiling_face:

**Comment by brancz** [comment]
Added it to the next release if we can get it in in time with the other issues of that milestone
