### ISSUE TITLE
Support to set annotations for thanos's serviceaccount

### ISSUE THREAD

**Issue by vietwow** [coreos/prometheus-operator#3152]
Hi,

I'm deploying vault on EKS using IRSA so I need to set annotations for thanos's serviceaccount, I take a look to prometheus-operator but looks like this is not supported yet (please correct me if I'm wrong). So I would like to request to support this, because I think this need is common. Thank you so much.

Best regards,
VietWOW

**Comment by brancz** [comment]
You need to create the serviceaccount yourself and specify it in the prometheus or thanos ruler object. So annotating it is totally up to you :)

**Comment by vietwow** [comment]
@brancz I know this could be done manually but it should support in automatically for CI/CD and automation tasks because almost production are IaaC codes, right ?

**Comment by brancz** [comment]
I’m not sure I understand. You’re entirely in charge of creating the serviceaccount so you will just need to add the annotation.

Can you elaborate what you would have imagined the solution to be?

**Comment by vietwow** [comment]
@brancz sorry for confused you, let me explain more clearly

I am deploying prometheus-operator with thanos using official helm chart from https://github.com/helm/charts/tree/master/stable/prometheus-operator

My EKS cluster is using IRSA for security purpose, so for all services, I need to set annotations for its serviceaccount, and usually, for other charts, it supports this through values.yaml file, example with cluster-autoscaller chart, I could do it by command :

```
helm upgrade -i cluster-autoscaler stable/cluster-autoscaler \
        --set rbac.create=true \
             helm upgrade -i cluster-autoscaler stable/cluster-autoscaler \
        --set rbac.create=true \
        --set image.repository=asia.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler \
        --set image.tag=v1.15.6 \
        --set rbac.serviceAccountAnnotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::${AWS_ACCOUNT_ID}:role/cluster-autoscaler"eks\.amazonaws\.com/role-arn"=arn:aws:iam::${AWS_ACCOUNT_ID}:role/cluster-autoscaler
...
```
So I need this option (like rbac.serviceAccountAnnotations as we could see), otherwise thanos's pod will be used default serviceaccount and cannot utilized IRSA feature. So I look into helm chart of prometheus-operator and cannot see this option, but I see in chart's values.yaml , for thanos, it reference to this https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec so I just guess this need to be support by prometheus-operatos ? that's why I created this ticket and please correct me if I'm wrong. Thank you so much.

Best regards,
VietWOW

**Comment by lilic** [comment]
We do not maintain the helm chart so we don't know about that, with plain manifests that's possible so it's not an issue I would say for this repo, best to ask on k8s slack some helm folks are on prometheus-operator channel or open issue on helm.

**Comment by vietwow** [comment]
Ah Ok, so this is my misunderstand, sorry and thanks @lilic 

Best regarsd,
VietWOW
