### ISSUE TITLE
kube_persistentvolume_capacity_bytes does not show all PV/PVCs

### ISSUE THREAD

**Issue by shibumi** [coreos/prometheus-operator#3156]
**What happened?**

I've deployed the prometheus-operator via `stable/prometheus-operator` helm chart on a rancher cluster.  I want to monitor all PV/PVC in my cluster. However when I use `kube_persistentvolume_capacity_bytes` it doesn't show all PVs, it only shows the PVs in the prometheus-operator namespace. On the other hand `kubelet_volume_stats_capacity_bytes` seems to show all PVs. Any idea why this happens?

**Did you expect to see something different?**

I expect both metrics to show all PV/PVCs from all namespaces.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy the `stable/prometheus-operator` helm chart with `serviceMonitorSelectorNilUsesHelmValues: false` this will set the NamespaceSelectors on `any`.

**Environment**

Kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"archive", BuildDate:"2020-04-19T14:21:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

Helm:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"dirty", GoVersion:"go1.14.1"}
```

* Prometheus Operator version:
 Image:      quay.io/coreos/prometheus-operator:v0.37.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"archive", BuildDate:"2020-04-19T14:21:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

Rancher

**Comment by lilic** [comment]
That metric comes from kube-state-metrics, what makes you think it's an operator or prometheus problem? Note that kubelet_volume_stats_capacity_bytes comes from k8s kubelet and not kube-state-metrics.

https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolume-metrics.md

**Comment by shibumi** [comment]
@lilic thanks a lot. I just wonder why I get more namespaces on the kubelet metric. Do I need to deploy the kube-state-metric pod on every node?

I thought this is a prometheus-operator problem, because I thought the namespaceSelector for prometheus-operator doesn't work correctly. I had no other explanation for missing metrics for the kube_* metrics.

**Comment by shibumi** [comment]
Ah ok, I had a second look on the metrics.

```
kube_persistentvolume_capacity_bytes{endpoint="http",instance="10.42.137.61:8080",job="kube-state-metrics",namespace="monitoring",persistentvolume="pvc-190c9c43-78b9-432e-81df-308ed8a0b1e9",pod="monitoring-kube-state-metrics-578b595b75-k7sjd",service="monitoring-kube-state-metrics"}
```

The metric says `namespace="monitoring"`, but this is just the namespace of the kube-metrics server, the persistentvolume is from another service in another namespace, so it actually works, I just have been misreading the metric output.

Sorry for the noise. Thanks for your help @lilic.
Closing this one.
