### ISSUE TITLE
Grafana Multi-Cluster Dashboards in Prometheus Operator

### ISSUE THREAD

**Issue by moustafa-mneimneih** [coreos/prometheus-operator#3159]
**What did you do?**
Deployed prometheus operator (prometheus, alertmanager, grafana) with thanos across multiple clusters. Default alerts and rules were deployed. Default Grafana dashboards were not multi cluster so I found kubernetes-mixin (https://github.com/kubernetes-monitoring/kubernetes-mixin) which does generate multi-cluster dashboards. Upon deploying the new dashboards, I had multi cluster dashboards in Grafana that work great. 

**Did you expect to see some different?**
I was expecting there to be an override (similar to the kubernetes-mixins github project) to allow for grafana dashboards to have multi-cluster support from within prometheus operator. I see a TODO in the kubernetes-mixin project from 2 years ago but still no movement. Given thanos is shipped with prometheus operator now for multi-cluster support, I would expect there to be default dashboards 

**Environment**

* Prometheus Operator version:

    `helm chart prometheus-operator-8.12.3`
    

* Kubernetes version information:

    `v1.15.11-gke.5`
    

* Kubernetes cluster kind:

   Google Kubernetes Engine

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.

Side note, with the jsonnet based approach you would be able to add this as a configuration parameter.

**Comment by moustafa-mneimneih** [comment]
Thanks for your response. 
I've started looking at using this project instead of the helm chart. I couldn't find any docs around using jsonnet with this. Also, I couldn't find any reference to how I can enable multi-cluster setup using this prometheus operator. Ultimately I want to deploy a prometheus, alertmanager, grafana and thanos. Should i still be looking at this repo? Or would kube-prometheus be better suited?

Hoping maybe you can point me in the right direction?

**Comment by brancz** [comment]
kube-prometheus represents the "full" solution. Prometheus Operator is just the kubernetes controller that manages individual Prometheus / Alertmanager clusters. Kube-Prometheus is a concrete use of the Prometheus Operator.

**Comment by moustafa-mneimneih** [comment]
Great thanks!
