### ISSUE TITLE
Can't built docker image for ARM

### ISSUE THREAD

**Issue by rmb938** [coreos/prometheus-operator#3162]
**What happened?**

```
$ make image ARCH=arm
GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -mod=vendor -ldflags="-s -X github.com/coreos/prometheus-operator/pkg/version.Version=0.38.0" -o operator cmd/operator/main.go
docker build --build-arg ARCH=arm --build-arg OS=linux -t quay.io/coreos/prometheus-operator:c7405c84 .
Sending build context to Docker daemon    141MB
Step 1/6 : ARG ARCH="amd64"
Step 2/6 : ARG OS="linux"
Step 3/6 : FROM quay.io/prometheus/busybox-${OS}-${ARCH}:latest
unauthorized: access to the requested resource is not authorized
make: *** [Makefile:126: .hack-operator-image] Error 1

```

**Did you expect to see something different?**

The docker image built

**How to reproduce it (as minimally and precisely as possible)**:

```
make image ARCH=arm
```

**Anything else we need to know?**:

The image `quay.io/prometheus/busybox-linux-arm` does not exist, only `quay.io/prometheus/busybox-linux-armv7` exists. However I can't use `make image ARCH=armv7` because go build doesn't understand `armv7`.

Some adjustments are needed to the Makefile so when ` ARCH=arm` is given the docker arch gets set to `armv7`.

**Comment by brancz** [comment]
cc @simonpasquier @metalmatze
