### ISSUE TITLE
Quickstart installation way was broken after remove rights from ClusterRoleBinding

### ISSUE THREAD

**Issue by Slach** [coreos/prometheus-operator#3168]
**What happened?**
Installation process which recommended on https://github.com/coreos/prometheus-operator#quickstart was broken after https://github.com/coreos/prometheus-operator/commit/05a8934c678134bffc83c401b091e6d0df651d6e

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml

failed with state in CrashLoopBackOff
with error
```
creating CRDs failed: getting CRD: ThanosRuler: customresourcedefinitions.apiextensions.k8s.io "thanosrulers.monitoring.coreos.com" is forbidden: User "system:serviceaccount:prometheus:prometheus-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

cause 
ClusterRolesBinding doesn't contain required rights anymore
```
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/rbac/prometheus/prometheus-cluster-role-binding.yaml
```

what main goal was for these changes? 

do we have any workaround for this?

**Comment by brancz** [comment]
I dropped a note on your comment on the commit. We should definitely make the bundle work, but you should also not use bundles from the master branch but rather from releases. Nevertheless thanks a lot for reporting! It might have gone unnoticed into a release otherwise! :)

**Comment by Slach** [comment]
ok I can wait for a new release
and I need use `bundle.yml` from master on my staging environment
thanks a lot for clarify
