### ISSUE TITLE
Support environment variables in Prometheus

### ISSUE THREAD

**Issue by yeya24** [coreos/prometheus-operator#3170]
**What is missing?**

Currently, Prometheus CR doesn't support setting env vars for the Prometheus container

**Why do we need it?**

https://github.com/prometheus/prometheus/releases/tag/v2.18.0-rc.0 adds Jaeger integration to Prometheus. Jaeger supports different type of [env vars](https://github.com/jaegertracing/jaeger-client-go#environment-variables). We should have the ability to set env var for Prometheus container to support this feature.

**Comment by brancz** [comment]
You can already specify environment variables through the `containers` array, by "redefining" the Prometheus container, as everything you specify in there will be merged into the generated Prometheus container. That allows you to specify environment variables. Note this explicitly excludes any guarantees about upgrades as we can't make sure things work as expected when people can specify arbitrary things, but this should not be a problem given that the jaeger feature is also experimental to begin with :wink: .

**Comment by yeya24** [comment]
Thanks. Successfully trying the newest Prometheus with Jaeger, by redefining the Prometheus container!
