### ISSUE TITLE
No validation on the RemoteReadSpec fields

### ISSUE THREAD

**Issue by shay-berman** [coreos/prometheus-operator#3178]
**What happened?**
I set this remoteread detail in the prometheus CR
```
  remoteRead:
    - url: http://prom1:9090/api/v1/read
      read_recent: true
      name: prom1
    - url: http://prom2:9090/api/v1/read
      read_recent: true
      name: prom2

```
and successfully create the prometheus CR.

**Did you expect to see something different?**
I would expect that if I set a key that is not valid for remoteRead spec the creation should fail.

**How to reproduce it (as minimally and precisely as possible)**:
Create prometheus CR using the remoteRead above.

**Environment**
KGE k8s 1.15, prometheus operator latest which uses prometheus v2.15.2.

* Prometheus Operator version:
install it from stable helm chart https://github.com/helm/charts/tree/master/stable/prometheus-operator

quay.io/coreos/prometheus-operator:v0.37.0

```
+ kubectl describe pods chart1-prometheus-operator-operator-9dbc95d66-hhm7n
Name:           chart1-prometheus-operator-operator-9dbc95d66-hhm7n
Namespace:      default
Priority:       0
Node:           gke-cluster-shay-pool-1-9e99da38-fx13/10.168.0.21
Start Time:     Tue, 28 Apr 2020 10:18:01 +0300
Labels:         app=prometheus-operator-operator
                chart=prometheus-operator-8.12.12
                heritage=Helm
                pod-template-hash=9dbc95d66
                release=chart1
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container prometheus-operator; cpu request for container tls-proxy
Status:         Running
IP:             10.44.0.17
IPs:            <none>
Controlled By:  ReplicaSet/chart1-prometheus-operator-operator-9dbc95d66
Containers:
  prometheus-operator:
    Container ID:  docker://fa9978f5137c5bca74dbb649874d21634445e8ab3c19a738c923fd8758abc4d0
    Image:         quay.io/coreos/prometheus-operator:v0.37.0
    Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:51c4b3180aa4cb819ae918da49776dba9a17e11d5a5d1eb22d878e1141aa23c9
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --manage-crds=true
      --kubelet-service=kube-system/chart1-prometheus-operator-kubelet
      --logtostderr=true
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.37.0
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --config-reloader-cpu=100m
      --config-reloader-memory=25Mi
    State:          Running
      Started:      Tue, 28 Apr 2020 10:18:05 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from chart1-prometheus-operator-operator-token-lsvdv (ro)
  tls-proxy:
    Container ID:  docker://5140e6a046cec5e3692b2db15571086552831e1551854f0bbcf37876d77e05d2
    Image:         squareup/ghostunnel:v1.5.2
    Image ID:      docker-pullable://squareup/ghostunnel@sha256:70f4cf270425dee074f49626ec63fc96e6712e9c0eedf127e7254e8132d25063
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      server
      --listen=:8443
      --target=127.0.0.1:8080
      --key=cert/key
      --cert=cert/cert
      --disable-authentication
    State:          Running
      Started:      Tue, 28 Apr 2020 10:18:08 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /cert from tls-proxy-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from chart1-prometheus-operator-operator-token-lsvdv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  tls-proxy-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  chart1-prometheus-operator-admission
    Optional:    false
  chart1-prometheus-operator-operator-token-lsvdv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  chart1-prometheus-operator-operator-token-lsvdv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```
* Kubernetes version information:

    `kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

GKE

* Manifests:

```
+ kubectl describe prometheus chart1-prometheus-operator-prometheus3rr
Name:         chart1-prometheus-operator-prometheus3rr
Namespace:    default
Labels:       app=prometheus-operator-prometheus3rr
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         Prometheus
Metadata:
  Creation Timestamp:  2020-04-28T13:04:52Z
  Generation:          1
  Resource Version:    14657263
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/default/prometheuses/chart1-prometheus-operator-prometheus3rr
  UID:                 d95d4825-8950-11ea-b3d9-42010aa80034
Spec:
  Alerting:
    Alertmanagers:
      API Version:   v2
      Name:          chart1-prometheus-operator-alertmanager
      Namespace:     default
      Path Prefix:   /
      Port:          web
  Enable Admin API:  false
  External URL:      http://chart1-prometheus-operator-prometheus3rr.default:9090
  Image:             quay.io/prometheus/prometheus
  Listen Local:      false
  Log Format:        logfmt
  Log Level:         debug
  Paused:            false
  Pod Monitor Namespace Selector:
  Pod Monitor Selector:
  Port Name:  web
  Remote Read:
    Name:         prom1
    read_recent:  true
    URL:          http://chart1-prometheus-operator-prometheus1:9090/read
    Name:         prom2
    Read Recent:  true
    URL:          http://chart1-prometheus-operator-prometheus2:9090/api/v1/read
  Replicas:       1
  Retention:      10d
  Route Prefix:   /
  Rule Namespace Selector:
  Rule Selector:
    Match Labels:
      Nothing:  nothing
  Security Context:
    Fs Group:            2000
    Run As Non Root:     true
    Run As User:         1000
  Service Account Name:  chart1-prometheus-operator-prometheus
  Service Monitor Namespace Selector:
  Service Monitor Selector:
    Match Labels:
      Nothing:  nothing
  Version:      v2.15.2
Events:         <none>
```

* Prometheus Operator Logs:

**Anything else we need to know?**:

**Comment by brancz** [comment]
cc @pgier @dgrisonnet with the recent CRD changes this should now be validated as expected right?

**Comment by dgrisonnet** [comment]
Since #3107 was reverted by #3132 because we needed to upgrade CRD to v1 before upgrading controller-gen I don't think this is validated right now. However, since we recently upgraded CRD to v1 in #3175 we might be able to update controller-gen again.

I am concerned that upgrading controller-gen will break our v1beta1 CRDs again. I am not sure if controller-gen provides an opt-in way to remove the problematic `x-kubernetes-list-map-keys` field. Should I work something out to generate v1 and v1beta1 CRDs with different controller-gen version?

**Comment by brancz** [comment]
If that’s the case, why don’t we drop v1beta1 entirely? It seems like keeping it is keeping us from marking progress. People who have to use v1beta1 will just have to use an older version of prometheus operator compatible with their Kubernetes version.

**Comment by dgrisonnet** [comment]
Sounds good to me.

**Comment by shay-berman** [comment]
Thanks guys for your responsiveness.
So does this bug is going to be fixed?

**Comment by brancz** [comment]
It would be great if you could test that once #3187 merges :)

**Comment by shay-berman** [comment]
Sure @brancz. Also reviewed #3187 
But can you please clarify how merging #3187 will fix this issue?

**Comment by brancz** [comment]
#3187 actually won't cut it just yet, (the theory is) we also need to upgrade the controller tools as @dgrisonnet mentioned.

**Comment by shay-berman** [comment]
ok, thanks for the clarification.

**Comment by dgrisonnet** [comment]
Hi @shay-berman, sorry I misunderstood your initial problem. In order to validate that all the fields exist, we use Kubernetes CRD pruning. However, this feature is only available after Kubernetes v1.15.0. Because of that, we disabled it in `kube-prometheus` #2924 but I don't know how it is done in the helm chart.

Thinking about it we might want to revert https://github.com/coreos/kube-prometheus/pull/408 in `kube-prometheus` versions that should not be compatible with Kubernetes v1.14. What do you think @brancz?

**Comment by shay-berman** [comment]
Helm does nothing here.  If the CR has admission controller that fail on wrong field also the helm should fail.

**Comment by brancz** [comment]
What @dgrisonnet meant is we have no idea if the helm chart is correctly synced, it's not maintained by us as we don't use it.

**Comment by brancz** [comment]
> Thinking about it we might want to revert coreos/kube-prometheus#408 in kube-prometheus versions that should not be compatible with Kubernetes v1.14. What do you think @brancz?

I really think we should move beyond 1.14 at this point. I don't think we should put much more work into supporting it.

**Comment by pgier** [comment]
I created https://github.com/coreos/kube-prometheus/pull/519 which reverts the previous compatibility changes.  This enables validation, but the CRD will no longer apply in kube 1.14 and earlier.

**Comment by shay-berman** [comment]
@pgier \ @brancz 
You mentioned that [prometheus-operator-helm-chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) does not maintained by you(prometheus operator maintainers).

So i wonder which one should I use - the [prometheus-operator-helm-chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) or the [kube-prometheus](https://github.com/coreos/kube-prometheus)? 

from the prometheus-operator [README](https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus-vs-community-helm-chart) it looks like both are valid and maintained by the community.

What are the differences between prometheus helm vs kube-prometheus in terms of features and maintainability? (except that one is helm method and the other is jsonnet)

**Comment by brancz** [comment]
The jsonnet version of kube-prometheus is maintained by the same people who maintain the prometheus operator. You need to make your own opinion of that information (obviously we recommend the jsonnet approach, but that's _our_ opinion). We simply don't believe in helm as a technology which is why we don't use it or support it.

That said, often the jsonnet version is more up to date as it's kind of the "upstream" for the helm packaging, and the helm version is updated as the jsonnet version introduces features (things have happened the other way around as well though).

**Comment by shay-berman** [comment]
Thanks @brancz  for the clarification.

Anyway - @pgier\@dgrisonnet  should we keep this issue open?

**Comment by dgrisonnet** [comment]
I think we can close this issue as this validation is enabled in the manifests provided by this repository.

As a side note, this validation requires Kubernetes v1.15+.
