### ISSUE TITLE
edit cm(configmap) prometheus-env ,then i   restart pod to reload cm,but it does't work,like never edit it

### ISSUE THREAD

**Issue by fuguohong1024** [coreos/prometheus-operator#3186]
i want  prometheus monitoring etcd ,the i add some config  to cm like this 
`- job_name:monitoring/etcd/0
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['192.168.1.160:2379','192.168.1.161:2379','192.168.1.162:2379']`
and my prometheus-k8s.yaml
`volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
`......
 ` - emptyDir: {}
        name: config-out
`

somebody can help me,plz

**Comment by brancz** [comment]
You need to configure this in the `ServiceMonitor` custom resource. The secret containing the prometheus configuration is autogenerated and will always be reconciled so what you are experiencing is expected.

**Comment by fuguohong1024** [comment]
> You need to configure this in the `ServiceMonitor` custom resource. The secret containing the prometheus configuration is autogenerated and will always be reconciled so what you are experiencing is expected.

3Q,i know how to do it。
