### ISSUE TITLE
Why prometheus server object does NOT create service object to the Prometheus CR?

### ISSUE THREAD

**Issue by shay-berman** [coreos/prometheus-operator#3191]
**What happened?**
The creation of the prometheus CR does not create its k8s service!
It means that in order to create Prometheus Custom Resource the user should create the CR BUT also need to manually create a k8s service for this prometheus stateful-set.
So why the create of the service for the prometheus stateful-set is not part of the operator job?

**Did you expect to see something different?**
Yes - the operator usually should be responsible also for the creation of the service.
Why we need this service:
1. So grafana will be able to connect to the prometheus
2. So Thanos querier will be able to connect to the promethes sidecar container of thanos.
3. To access prometheus web UI.

**How to reproduce it (as minimally and precisely as possible)**:
Just create prometheus CR and then in order to use it you will must have to create service for it.

**Environment**
k8s 1.15

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.37.0

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

GCP
* Manifests:

* Prometheus Operator Logs:

**Anything else we need to know?**:

**Comment by brancz** [comment]
There can be infinite numbers of configurations that would be "correct" depending on the users requirements. This is not something we can generalize and universally do. We intentionally leave this up to the user, the prometheus operator is not about provisioning services, it's about the life-cycle and configuration of Prometheus itself.

**Comment by shay-berman** [comment]
Thanks @brancz  for the clarification.
Its a bit strange that the CR of the prometheus does not generate its service, because without service no one can really use the prometheus it self.   I am not sure but I think that usually operator also handle the relevant service\ingress needed for the app as part of the creation of the CR - but maybe I am wrong.

**Comment by brancz** [comment]
Prometheus Operator being the first operator that was ever created, I think if anything it would be setting the standard :) 

The problem is that there can be infinite ways to configure a service/ingress none of which would truly satisfy all users, and if it would, then we would be recreating those APIs as part of the prometheus operator, which doesn't really make sense.

**Comment by shay-berman** [comment]
ok, what about setting the headless service that needed for the thanos sidecar?  you can see my thoughts -> https://github.com/helm/charts/pull/22238

**Comment by brancz** [comment]
You can have multiple groups of Prometheus servers that may or may not be part of the same Thanos setup, having a service like that will never satisfy everyone, and to most it will just be noise.

**Comment by shay-berman** [comment]
got your point @brancz - so may I close this ticket?

**Comment by tirelibirefe** [comment]
@shay-berman ;How did you accomplish this task? How do you access to prometheus from outside of K8s?
