### ISSUE TITLE
Add support for pattern/regex matching of operator namespaces/denyNamespaces

### ISSUE THREAD

**Issue by amuraru** [coreos/prometheus-operator#3195]
**What is missing?**

Currently the operator allows setting namespaces or deny-namespaces to configure the list of NSs watched. 

In dynamic environments where the NS are dynamic and require multiple operator instances to be run it would be useful to specify these parameters as patterns/regex and not statically.

**Why do we need it?**

This allows:
- disjoint/non-overlapping set of namespaces watched by different instances of the operator
- manage dynamic set of namespaces

**Comment by brancz** [comment]
The problem with something like this is that there is no such support in the Kubernetes API for doing something like this, so all we could do is list all, and then filter, which we already allow with Kubernetes native mechanisms like label selectors.

> manage dynamic set of namespaces

This is very non trivial. The prometheus operator heavily relies on not changing this at runtime, it would be a massive refactoring to change this. I'm not opposed to it, but it's a lot of work.

**Comment by amuraru** [comment]
@brancz 
> The problem with something like this is that there is no such support in the Kubernetes API for doing something like this, so all we could do is list all, and then filter

Makes sense.

My use-case is the following: I want to run two prometheus-operator instances: one watching all namespaces (global/catch-all) and one configured to watch a single ns via `--namespaces`. The label selector works for all prom resources except `Prometheus` CR itself which when created in the namespace watched by both operators is acted upon by both operators.

Would it make sense to add a `prometheusLabelSelector` to prometheus operator so we can have a finer control on this behaviour? i.e. we can keep the allow/deny namespaces watching but there is an extra label selector that can further filter out `Prometheus` CRs at runtime.

**Comment by amuraru** [comment]
Nevermind :) - I see https://github.com/coreos/prometheus-operator/pull/2615 implemented the support for the exact use-case above. Awesome

**Comment by brancz** [comment]
Are we ok closing this then? :)

**Comment by amuraru** [comment]
yup - thanks!
