### ISSUE TITLE
Allow disabling HA mode for the alertmanager

### ISSUE THREAD

**Issue by mlushpenko** [coreos/prometheus-operator#3196]
**What is missing?**
Not possible to disable HA mode

**Why do we need it?**
Get rid of alertmanager errors on a single node cluster https://github.com/prometheus/alertmanager/issues/1814

**Anything else we need to know?**:
To disable HA mode you have to put `--cluster.listen-address=""` and it is currently hardcoded https://github.com/coreos/prometheus-operator/blob/6b1a5276fe42efd355b001cd891cf169b9bd6775/pkg/alertmanager/statefulset.go#L243

**Comment by mlushpenko** [comment]
I could try creating a PR if you can guide me a bit.

**Comment by paulfantom** [comment]
HA is a huge part of prometheus-operator since usually user wants monitoring to be one of the most reliable parts of the cluster. I don't see how disabling it can do anything good.

**Comment by brancz** [comment]
I don’t think they’re particularly good use cases but I can imagine a single node setup where it’s kind of useless to have multiple nodes. I think I could live with removing this if replicas is 1.

**Comment by mlushpenko** [comment]
I guess those errors aren't critical and maybe they don't affect anything at all, not sure. We have a number of small clusters forwarding alerts to the tools cluster and no hardcore SLAs yet, so no strong requirements for high availability. And I believe there are many companies who have test environments in a similar situation. So, for my understanding, you wouldn't do it yourself but could consider a PR, right?

**Comment by brancz** [comment]
I would be ok with that yes.

**Comment by mlushpenko** [comment]
I thought about it a bit more, laziness took over, so an extra alertmanager instance won't harm :)
