### ISSUE TITLE
KubeletDown alert rule firing, Kubelet dashboards broken

### ISSUE THREAD

**Issue by geofffranks** [coreos/prometheus-operator#3198]
**What did you do?**

We upgraded from v8.2.0 to v8.13.3 of the helm chart for prometheus-operator, our KubeletDown alerts started firing, and kubelet dashboards started breaking (no data at all, even historically). Kubelet scraping is working according to prometheus, and there are metrics for . it.

**Did you expect to see some different?**

No alerts to fire, and dashboards to keep working

**Environment**

EKS cluster - k8s 1.14.6
* Prometheus Operator version: 8.13.3

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
    AWS EKS (terraform'd)
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

**Anything else we need to know?**:

It seems like after the upgrade, we got switched to a number of rules/dashboards for k8s 1.14 and above, but they don't seem to work on our 1.14.9 cluster. Worker nodes are running kubelet v1.14.6-eks-5047ed.  Not sure if this is something related to our cluster, or if there's a bad cutoff for some of the rules/dashboards. 

The `absent(up{job="kubelet", metrics_path="/metrics"} == 1)` query fails for us in prometheus, while the older query `absent(up{job="kubelet"} == 1)` succeed. Looks like https://github.com/helm/charts/commit/71d5b06c1547ed2bf7fa3df17873f1f3f27bf7ef changed the queries for 1.14+ clusters intentionally.. Are we just missing something in our config to make this work again?

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.
