### ISSUE TITLE
Prometheus pod is not deleted on deleting the resource

### ISSUE THREAD

**Issue by manojlds** [coreos/prometheus-operator#32]
After following https://coreos.com/blog/the-prometheus-operator.html - I deleted all the resources (`kubectl delete -f .` on the folder having all the yamls)

The prometheus-k8s pod was remaining.

Finally figured out that it is running from a PetSet and had to delete that separately.

As a user I didn't create a PetSet, so I shouldn't have to be deleting it to ensure proper cleanup (or other activities.)

**Comment by brancz** [comment]
Did you also remove the prometheus-operator? If so it might have been deleted before the Prometheus resource was deleted.

**Comment by manojlds** [comment]
Yeah I remove the prometheus-operator too. So I have to make sure that the `Prometheus` resource is deleted before the prometheus-operator right?

**Comment by brancz** [comment]
Yes that is correct.
