### ISSUE TITLE
Having trouble creating the operator on GKE

### ISSUE THREAD

**Issue by ds0nt** [coreos/prometheus-operator#320]
**What did you do?**
Trying to install the prometheus-operator on a running GKE cluster. I'm using the prometheus operator yaml from the latest version of the guide. https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

My config files worked on minikube.

**What did you expect to see?**
Lots of Prometheus-stuff created.

**What did you see instead? Under which circumstances?**

```
kc create -f prometheus-operator.yaml 
error: error validating "03-prometheus-operator.yaml": error validating data: couldn't find type: v1alpha1.ClusterRoleBinding; if you choose to ignore these errors, turn validation off with --validate=false
```

**Environment**

* Kubernetes version information:

```
kc version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Created on Google Cloud Platform.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by ds0nt** [comment]
I'm wondering if I need to do something like this?

https://cloud.google.com/container-engine/docs/role-based-access-control

GKE has alpha features disabled, do you think if I recreate my cluster and enable RBAC it will solve this problem? Am I misinterpreting the error?

**Comment by brancz** [comment]
RBAC resources graduated from alpha to beta in 1.6, kubectl can gracefully handle that if you create them using `kubectl apply`.

**Comment by ds0nt** [comment]
Creating a new cluster like this seemed to work: 

`To ensure your Role-Based Access Control permissions take effect, you must create your cluster with the option --no-enable-legacy-authorization.`

Doing that got past the error above. And then running kc apply a few times seems to have gotten the resources created.

My main concern was about whether or not there are any k8s alpha APIs being used outside of RBAC (which is beta - and thankfully, GKE got it up and running). But if there are any other ones that could come and bite me later, please let me know. I'm not really sure how to check which APIs are being used by prometheus-operator. On GKE they disable alpha features, so it would change the path we take to get prometheus running.

Thanks!

Also, operators are really cool. This code-base has been a really interesting little read so far! Keep the awesome stuff coming!

**Comment by ds0nt** [comment]
Oh this is weird. Now it just started working when I applied the files again, without having enabled RBAC, on the already existing cluster.

Darn, didn't need to do that enable legacy thing!

And also. Yay!

**Comment by ds0nt** [comment]
Alright, mystery solved. A member of our team upgraded the cluster to 1.6.2 and that is what did it.
