### ISSUE TITLE
AggregatedAPIDown

### ISSUE THREAD

**Issue by sunzhen99** [coreos/prometheus-operator#3203]
Annotations
message = An aggregated API v1beta1.metrics.k8s.io/default is down. It has not been available at least for the past five minutes.
runbook_url = https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-aggregatedapidown

**Comment by sunzhen99** [comment]
![image](https://user-images.githubusercontent.com/65014110/81390817-a8947680-914e-11ea-8285-2251077ed5ce.png)

**Comment by brancz** [comment]
Please open issues following the issue template. If you don't follow it and just paste the output of an alert we don't really know how to help you.

**Comment by RahulArora31** [comment]
WARNING | ALERTNAME = AggregatedAPIDown | CLUSTER = remy-idev-rtp | NAME = v1beta1.metrics.k8s.io | DESCRIPTION = An aggregated API v1beta1.metrics.k8s.io/default is down. It has not been available at least for the past five minutes.

**Comment by RahulArora31** [comment]
PrometheusRule-  sum
  by(name, namespace) (sum_over_time(aggregator_unavailable_apiservice[5m])) >
  0 
Output - WARNING | ALERTNAME = AggregatedAPIDown | CLUSTER = remy-idev-rtp | NAME = v1beta1.metrics.k8s.io | DESCRIPTION = An aggregated API v1beta1.metrics.k8s.io/default is down. It has not been available at least for the past five minutes.

**Comment by Xuezenghuigithub** [comment]
I have also have this issue, is there a solution?
