### ISSUE TITLE
Relase notes and breaking change in 0.39

### ISSUE THREAD

**Issue by stigok** [coreos/prometheus-operator#3206]
It appears to be a breaking change in https://github.com/coreos/prometheus-operator/pull/3187, but it was noted as **[CHANGE]** in the release notes. It would be nice to note these as **[BREAKING CHANGE]**, or similar, instead, to increase the chance they are noted.

**Comment by paulfantom** [comment]
We are mostly following [prometheus format for changelog](https://github.com/prometheus/prometheus/blob/master/RELEASE.md), which is stated in our [RELEASE](REALESE.md) document.

Additionally, if you look at the changelog, the majority of previous `[CHANGE]` entries were either breaking changes in some form or they were very important for end-user.

**Comment by lilic** [comment]
Agreed, have not noticed this done in any of other repos before, can you give an example @stigok ?

**Comment by stigok** [comment]
Okay. Seems I made some fast assumptions. I thought *[BREAKING CHANGE]* was part of the semver norms, but appears this has only been described in _[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)_.

My issue with this is that it's the first release that is breaking in our environment due to some of our clusters being stuck at Kubernetes v1.15. But since this is a v0.x -release, an unstable API is to be expected, I suppose, hence this not being bumped up a major.

**Comment by arianitu** [comment]
@stigok can you explain what happened? We're still evaluating this project and we've been searching for "breaking change" or "upgrading" and trying to understand the stability of the project.

Did you upgrade Prometheus Operator to a new version that wasn't supported by your Kubernetes version? How do you know when to upgrade (we can't find docs that talk about upgrading between versions anywhere.)

**Comment by stigok** [comment]
I try to keep software up-to-date in our clusters to avoid "big jumps" if we are forced to upgrade later on. I look at the diffs in the YAML between the existing version and the new, and take a decision to update based on that diff and the changelog.

What we see now, is that a change was introduced that requires Kubernetes version 1.16, which means we will be stuck at v0.38.1 until our cluster is updated. I don't remember what version we started using the operator at v0.35.1, but up until now, I haven't seen anything other than backward compatible changes, i.e. not breaking for us on Kubernetes 1.15.

**Comment by lilic** [comment]
Seems like this issue can be closed. 

@arianitu we try not to make any breaking changes, as we use it ourselves so we are always careful unless completely necessary if there are breaking changes by k8s or other components we use, hope that answers your question.
