### ISSUE TITLE
Admission hooks block rules that promtool treats as valid

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#3223]
#### What happened?
Submitting a rule with a non-string label passes promtool but fails admission hooks:

```
labels:
  product: 123
  highPriority: false
```

#### Did you expect to see something different?
There should be parity between what is allowed to simplify creating CI pipelines.

#### Suggested solution
It should be possible to use the mutating hook we already have to alter the rules so that label values are always strings. This is what happens when they are loaded in Prometheus anyway.

I can see an objection to this in CI terms because the resources you get in the cluster are not the same as you are applying but there is definite precedent for this with mutating hooks. If necessary this could be made optional, but I think the mutating behaviour should be the default.

**Comment by brancz** [comment]
Can we first assess why this works in promtool and not in the webhook? If that doesn't help then I'm ok with this solution.

**Comment by vsliouniaev** [comment]
It's due to the definition of the `PrometheusRule` CRD only allowing strings. Prometheus using yaml instead of json natively just treats this as strings. 

At first the bad rule would just break the operator, then additional CRD-related validation was added here: https://github.com/coreos/prometheus-operator/commit/1ac10b0be2123c22ffe16f71a83640855865f534.

**Comment by vsliouniaev** [comment]
There is actually an additional issue with `absent_over_time` not being an accepted, which would need a prometheus dependency update.
