### ISSUE TITLE
Data synchronization when upscaling Prometheus PODs

### ISSUE THREAD

**Issue by caliban74** [coreos/prometheus-operator#3224]
I'm using an old version of Prometheus Operator (v0.18.1) and so far I just run a single Prometheus POD (replicas set to 1 in Prometheus object). I have also some Grafana dashboards that show its metrics. I wanted to upscale Prometheus PODs to 2 replicas and I expected the existing metrics data in the Persistent Volume of the existing POD to be copied into the new Persistent Volume of the new POD so that both PODs could return the same data. 
Actually this did not happen, and if I refresh the Grafana dashboard frequently I can see sometimes only newly ingested metrics data (I guess returned from the new POD) and some others both new and old data (I guess from the old POD). 
Is this intended or am I doing something wrong ? I tried to find some references in the documentation or in the new versions release notes but I did not find anything useful.
Thank you

**Comment by brancz** [comment]
This works as intended. If you want full data, then you need something like [Thanos](https://github.com/thanos-io/thanos) that requests both Prometheus instances and merges the results at query time.

**Comment by caliban74** [comment]
@brancz Thank you for your reply. I will try it out as soon as possible.
