### ISSUE TITLE
Can Prometheus -operator monitor another k8s cluster?Not the k8s cluster it's in

### ISSUE THREAD

**Issue by zhifei92** [coreos/prometheus-operator#3235]
**What did you do?**

Can Prometheus -operator monitor another k8s cluster?Not the k8s cluster it's in

**Comment by brancz** [comment]
It can but you’re not going to have the best experience. You’re probably best off writing your own additionalScrapeConfigs and not use service monitors etc. if that’s something you want to do. You’re in any case going to need to have network access to the pod network.
