### ISSUE TITLE
Delete ServiceMonitor does not re-update configuration

### ISSUE THREAD

**Issue by lechen26** [coreos/prometheus-operator#3236]
Hi

perhaps i'm missing something but seems like when deleting ServiceMonitor the operator does not reload the configuration and update prometheus.

after deleting serviceMonitor i dont see the change refelected on the prometheus configuration, even after along time.
adding new ServiceMonitor being added as  a new Target, but what about the opposite?
doesnt deleting ServiceMonitor should be reflected on the configuration and remove that job?

thanks
Chen

**Comment by brancz** [comment]
How long did you wait? Could you watch the secret that gets generated and see if that gets updated? Did prometheus reload successfully?

**Comment by lechen26** [comment]
i've waited long time, 5-10 minutes. 
i'm not sure what was the problem, i ended up redeploying the stack and problem didnt appear again, it might be it was an issue on the deployment, not sure.
anyway , closing this.
