### ISSUE TITLE
Not possible to change "group_by" parameter for alertmanager configuration

### ISSUE THREAD

**Issue by yevgeniyo** [coreos/prometheus-operator#3240]
**What happened?**

Not possible to change "group_by" parameter for alertmanager configuration

**Did you expect to see something different?**

By default it creates "group_by: ['job']"
If you want to change to other value like cluster or alertname it's still remains the same.

 

**How to reproduce it (as minimally and precisely as possible)**:

Build alertmanager with operator and try to change group_by and update helm deployment
Every parameter will be changed except group_by

![Screen Shot 2020-05-24 at 12 35 08](https://user-images.githubusercontent.com/14246521/82750770-0bc31180-9dbb-11ea-9627-e8ea5c22c001.png)

**Environment**

* Prometheus Operator version:
prometheus-operator-8.13.8

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    kubeadm

**Comment by vsliouniaev** [comment]
Alertmanager configuration is loaded from a secret specified by

```yaml
spec:
  configSecret: {}
```

https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec

Could you share your alertmanager resource and the configuration in the secret?

**Comment by yevgeniyo** [comment]
> Alertmanager configuration is loaded from a secret specified by
> 
> ```yaml
> spec:
>   configSecret: {}
> ```
> 
> https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec
> 
> Could you share your alertmanager resource and the configuration in the secret?

So secret had old configuration with "job" parameter
I have deleted secret, run helm upgrade and deleted pod, it fixed the issue...

Weird that another parameters like "icon_emoji" for slack are changing on the fly..... is duet to templating?

**Comment by vsliouniaev** [comment]
> Weird that another parameters like "icon_emoji" for slack are changing on the fly..... is duet to templating?

Alertmanager does not provide a direct integration to slack besides using webhooks. This could also be something downstream of alertmanager in your alerting pipeline.

**Comment by yevgeniyo** [comment]
Thank you, please close this issue
