### ISSUE TITLE
Roll over prometheus pod when no targets detected

### ISSUE THREAD

**Issue by paulfantom** [coreos/prometheus-operator#3248]
**What is missing?**
prometheus-operator rolling over prometheus pod when it doesn't have any scrape targets.

**Why do we need it?**
Currently, there is a slight chance that environment variables necessary for Prometheus SD are not set inside a pod by k8s API server. This is not a panic scenario for prometheus itself, but it causes issue which can be automatically solved by prometheus-operator.

To do this prometheus-operator can check prometheus metric, ex. `prometheus_target_scrape_pools_total` and if it is 0, then reset that prometheus instance.

**Environment**

* Prometheus Operator version: All

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

/cc @lilic

**Comment by brancz** [comment]
It can be perfectly legitimate for Prometheus to not have any scrape targets. If SD is not working, then those metrics should show that.

**Comment by paulfantom** [comment]
> It can be perfectly legitimate for Prometheus to not have any scrape targets.

Yes, when a user is using only prometheus. It isn't a legitimate situation when using prometheus-operator which is tightly coupled with k8s. 

In this particular case when k8s SD is not available and user is using prom-op, then prometheus will have metrics on which it should alert. The alert will fire, but it won't be delivered to alertmanager as those endpoints couldn't be discovered. This in turn causes prometheus to be completely unusable.

---
There is another way of fixing this, we can add an initContainer which will just check if `KUBERNETES_SERVICE_HOST` env is available. If that env doesn't exist then exit with non-zero exit code causing pod to be restarted.

**Comment by brancz** [comment]
There are arbitrary amounts of things that we could check, but I don't think that's reasonable. As far as I know `KUBERNETES_SVC_HOST` not being set is actually just a race on the kubelet and is currently being addressed there.

For any combination of these types of things going wrong, is exactly what WatchDog type alerts are for.
