### ISSUE TITLE
AggregatedAPIDown is keep triggering after the upgrade

### ISSUE THREAD

**Issue by gopisaba** [coreos/prometheus-operator#3259]
**What happened?**

After the recent prometheus-operator upgrade, `AggregatedAPIDown` alert is keep triggering

**Did you expect to see something different?**

Excepts not to see this alert. Do we need to silence or remove this alert until the issue is fixed? https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/397

**How to reproduce it (as minimally and precisely as possible)**:

Install/upgrade prometheus-operator version 8.13.0

**Environment**

All the environments

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.38.1`

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    AWS EKS

* Alert expression:

```
sum by(name, namespace) (sum_over_time(aggregator_unavailable_apiservice[5m])) > 0
```

**Comment by brancz** [comment]
I think silencing this for a long time is the best choice here. I'm closing this here, as this project is about the prometheus operator controllers only, the full solution with alerts etc. is the [kube-prometheus project](https://github.com/coreos/kube-prometheus).
