### ISSUE TITLE
connect prometheus to a outside Alertmanager

### ISSUE THREAD

**Issue by hedeesa** [coreos/prometheus-operator#3260]
I want to use an Alertmanager which is outside of the prometheus cluster, I read this https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md and I assumed that there is no way to define an  Alertmanager(which is not in the cluster) for the  prometheues.
Is there a way to do such thing ?

**Comment by pgier** [comment]
You should be able to use the additionalAlertmanagerConfigs field in your Prometheus resource to point to a secret which contains the appropriate alertmanager config.  See #1338 for a bit more information.

**Comment by brancz** [comment]
You can use the additionalAlertmanagerConfigs feature to use arbitrary service discovery mechanism to discover alertmanagers.

**Comment by hedeesa** [comment]
for now this solution works fine for me  
https://github.com/coreos/prometheus-operator/issues/871#issuecomment-356598118

**Comment by muradheydarov** [comment]
I also need to connect to external alertmanager. I want to use additionalAlertmanagerConfigs for this purpose. But I do not know how to configure it properly. Is there are someone used it and connected?

**Comment by muradheydarov** [comment]
I tested with this config but it is not worked.

`additionalAlertManagerConfigs:
 - static_configs:
   - targets: ["my-ingress-host"]`

**Comment by mayureshmudrale** [comment]
Hi @muradheydarov I have Prometheus helm chart not able to find where to place this configuration.
Also will it work with mimir alert manager ?
