### ISSUE TITLE
How to add customise tag on the volume created by pvc

### ISSUE THREAD

**Issue by sunhubs** [coreos/prometheus-operator#3283]
**What did you do?**
I create a pvc, and it will create a volume in AWS with the default tags
**Did you expect to see some different?**
I want to add customize tag due to some reason
**Environment**
helm:v3.2.1
prometheus:v2.16.0
* Prometheus Operator version:
v0.38.1

* Kubernetes version information:
client 1.14.7
server 1.16.8

* Kubernetes cluster kind:
AWS eks

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.
