### ISSUE TITLE
How can I set the ClusterDomain in AlertManager?

### ISSUE THREAD

**Issue by devlucasc** [coreos/prometheus-operator#3289]
I would like to know how can I set ClusterDomain in AlertManager to support FQDN DNS

I found this [Pull 3138](https://github.com/coreos/prometheus-operator/pull/3138/files) but I could not find any docs do handle with this.

Thanks

**Comment by paulfantom** [comment]
You can pass `--cluster-domain="some.domain.example.org"` to prometheus-operator.

**Comment by brancz** [comment]
As @paulfantom already answered, I'm gonna close this here, but feel free to keep commenting and or create another issue should you feel there is a problem with Prometheus Operator :)
