### ISSUE TITLE
Grafana dashboards not getting persisted if pod deleted/restarts

### ISSUE THREAD

**Issue by bravitejareddy** [coreos/prometheus-operator#3291]
**What did you do?**
We used config map to store all the dashboards and these dashboards are loaded to Grafana.

**Did you expect to see some different?**
All dashboards in configmap need to be stored persistently. 
**Environment**

* Prometheus Operator version: v0.38

    `Insert image tag or Git SHA here`
    Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Thu, 21 Nov 2019 05:51:19 +0000
Labels:                 k8s-app=prometheus-operator
                        velero.io/backup-name=stage-k8s-upgrade-monitoring-exclude-pv
                        velero.io/restore-name=stage-k8s-upgrade-monitoring-exclude-pv-20191121055117
Annotations:            deployment.kubernetes.io/revision: 3
Selector:               k8s-app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.38.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     200m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-5bff789fc8 (1/1 replicas created)
Events:          <none>

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind: kops

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-11-21T06:29:08Z"
  generation: 3
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: "63098583"
  selfLink: /apis/apps/v1/namespaces/monitoring/deployments/grafana
  uid: 38ecabdc-0c28-11ea-aeb1-02dad98e3180
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: grafana-credentials
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: grafana-credentials
        image: grafana/grafana:7.0.3
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/grafana-storage
          name: grafana-storage
        - mountPath: /var/lib/grafana
          name: grafana-persistent-storage
          subPath: grafana
      - args:
        - --watch-dir=/var/grafana-dashboards
        - --grafana-url=http://localhost:3000
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: grafana-credentials
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: grafana-credentials
        image: quay.io/coreos/grafana-watcher:v0.0.8
        imagePullPolicy: IfNotPresent
        name: grafana-watcher
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/grafana-dashboards
          name: grafana-dashboards
        - mountPath: /var/grafana-ingress-ctrl-dashboards
          name: nginx-ingress-ctrl-dashboard
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 472
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-persistent-storage
      - configMap:
          defaultMode: 420
          name: grafana-dashboards
        name: grafana-dashboards
      - configMap:
          defaultMode: 420
          name: nginx-ingress-ctrl-dashboard
        name: nginx-ingress-ctrl-dashboard
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-21T06:29:08Z"
    lastUpdateTime: "2020-06-18T15:43:15Z"
    message: ReplicaSet "grafana-7bb95f8655" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-06-18T15:57:21Z"
    lastUpdateTime: "2020-06-18T15:57:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

manifests relevant to the issue
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-11-21T06:29:08Z"
  generation: 3
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: "63098583"
  selfLink: /apis/apps/v1/namespaces/monitoring/deployments/grafana
  uid: 38ecabdc-0c28-11ea-aeb1-02dad98e3180
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: grafana-credentials
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: grafana-credentials
        image: grafana/grafana:7.0.3
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/grafana-storage
          name: grafana-storage
        - mountPath: /var/lib/grafana
          name: grafana-persistent-storage
          subPath: grafana
      - args:
        - --watch-dir=/var/grafana-dashboards
        - --grafana-url=http://localhost:3000
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: grafana-credentials
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: grafana-credentials
        image: quay.io/coreos/grafana-watcher:v0.0.8
        imagePullPolicy: IfNotPresent
        name: grafana-watcher
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/grafana-dashboards
          name: grafana-dashboards
        - mountPath: /var/grafana-ingress-ctrl-dashboards
          name: nginx-ingress-ctrl-dashboard
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 472
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-persistent-storage
      - configMap:
          defaultMode: 420
          name: grafana-dashboards
        name: grafana-dashboards
      - configMap:
          defaultMode: 420
          name: nginx-ingress-ctrl-dashboard
        name: nginx-ingress-ctrl-dashboard
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-21T06:29:08Z"
    lastUpdateTime: "2020-06-18T15:43:15Z"
    message: ReplicaSet "grafana-7bb95f8655" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-06-18T15:57:21Z"
    lastUpdateTime: "2020-06-18T15:57:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: "2019-11-21T06:29:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: grafana-persistent-storage
  namespace: monitoring
  resourceVersion: "20086164"
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/grafana-persistent-storage
  uid: 38eb1a4f-0c28-11ea-aeb1-02dad98e3180
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-38eb1a4f-0c28-11ea-aeb1-02dad98e3180
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
This project doesn't provide any manifests to install or manage grafana.
If you used [kube-prometheus](https://github.com/coreos/kube-prometheus) to install prometheus-operator, then your grafana instance is immutable and any changes are not persisted by default.
If you used helm chart, please open issue in helm chart repository.
