### ISSUE TITLE
Prometheus Operator watching every secret leads to high memory usage

### ISSUE THREAD

**Issue by Sayrus** [coreos/prometheus-operator#3298]
**What happened?**

After updating to Helm V3, we saw an increase in the Prometheus-Operator memory usage (enough to lead to it being OOMKilled) from Base64 decode functions and json parsing.

After investigating, we found the root cause of the problem: the operator is watching every secrets and Helm v3 created several thousands of them (and they are in the namespace of the resources instead of a namespace we can exclude such as kube-system).
The operator is therefore wasting time scanning thousands of secrets it won't be able to use.

**Did you expect to see something different?**

Prometheus-operator should either watch for secret he might be interested in or filter out the secrets he knows he can't use.
Maybe introduce an option such as `SecretWatchListSelector` and `ConfigmapWatchListSelector` to allow the user to configure it.

**How to reproduce it (as minimally and precisely as possible)**:

Create several thousands secrets and observe the memory usage behavior of the operator. 

**Environment**

GKE - Kube 1.16.8

* Prometheus Operator version: quay.io/coreos/prometheus-operator:v0.38.1 (I don't think the version is relevant)

* Kubernetes version information: v1.16.8-gke.15

* Kubernetes cluster kind: GKE

* Manifests: N/A

* Prometheus Operator Logs: No suspicious logs

**Anything else we need to know?**:

Impact of filtering out Helm V3 secrets:
```diff
--- a/pkg/prometheus/operator.go
+++ b/pkg/prometheus/operator.go
@@ -330,7 +330,7 @@ func New(conf Config, logger log.Logger, r prometheus.Registerer) (*Operator, er
        c.secrInf = cache.NewSharedIndexInformer(
                c.metrics.NewInstrumentedListerWatcher(
                        listwatch.MultiNamespaceListerWatcher(c.logger, c.config.Namespaces.PrometheusAllowList, c.config.Namespaces.DenyList, func(namespace string) cache.ListerWatcher {
-                               return cache.NewListWatchFromClient(c.kclient.CoreV1().RESTClient(), "secrets", namespace, fields.Everything())
+                               return cache.NewListWatchFromClient(c.kclient.CoreV1().RESTClient(), "secrets", namespace, fields.OneTermNotEqualSelector("type", "helm.sh/release.v1"))
                        }),
                ),
                &v1.Secret{}, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
```

Relevant go_memstat metrics after the patch:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/22404472/85850894-3aa71b80-b79d-11ea-9a78-048606ac8f24.png">

**Comment by lilic** [comment]
Interesting issue! We have not noticed this ourselves as we do not use helm, but I think that seems like a valid fix. cc @brancz any objections on your side? Not sure I would call it a bug?

**Comment by paulfantom** [comment]
As I stated in https://github.com/coreos/prometheus-operator/pull/3299#pullrequestreview-438296328, hardcoding dependency on helm label is mixing two separate technologies. If such an issue is caused by watching too many secrets then this doesn't have anything to do with helm and we should fix it in other ways (possibly by introducing new label, specific to prometheus operator).

**Comment by lilic** [comment]
Not sure its hardcoding a dependancy here, its just opinionated more :)

But yes I would prefer if this would be added as a flag so you pass the selector for which secrets to exclude.

**Comment by Sayrus** [comment]
Introducing a label sounds like the proper way to do it. Will that break existing setups? If so, should it be opt-in?
I think it would work to introduce a `WatchListSelector` so that the user is free to opt-in while not creating an unjustified dependency.

If you're fine with this approach, I can work on implementing properly.
