### ISSUE TITLE
Alertmanager not reloaded on configMaps changes

### ISSUE THREAD

**Issue by 0robustus1** [coreos/prometheus-operator#3309]
**What happened?**

We have a configmap that stores our templates (e.g. for E-Mails) for the Alertmanager.
We specify an Alertmanager resource with the `configMaps` value set.
On startup the Alertmanager correctly uses the configured templates.

However, when we update the configmap (and only the configmap) the changes do not seem to be propagated to Alertmanager. While kubernetes automatically updates the mounted files based on the new version of the configmap; the Alertmanager does not pick up on this.

It seems that the Alertmanager is not reloaded on updates to configmaps listed in the `configMaps` field.

**Did you expect to see something different?**

We would've expected Alertmanager to be automatically reloaded in order to take the changes in configmaps into account as this is what happens when updating the `configSecret` (the actual alertmanager configuration file).

**Environment**

* Prometheus Operator version:

    [`v0.39.0`](https://github.com/coreos/prometheus-operator/releases/tag/v0.39.0)
    

* Kubernetes version information:

    `kubernetes v1.16.10`
    

* Kubernetes cluster kind:

    custom

**Anything else we need to know?**:

A possible solution for this would be to configure [`configmap-reload`](https://github.com/jimmidyson/configmap-reload/tree/v0.3.0) differently. Currently it only mounts the alertmanager secret and listens to changes in those files. If we mount the entire `/etc/alertmanager` structure instead (including additional secrets (placed in `/etc/alertmanager/secrets`) and additional configmaps (placed in `/etc/alertmanager/configmaps`) and configure `configmap-reload` to use `/etc/alertmanager` as `-volume-dir` reloads should be triggered as expected.

**Comment by brancz** [comment]
Nice catch. Yeah I think it depends quite a lot on what is mounted via those configmaps, but it seems save to reload Alertmanager in any case. I don't really think this is a bug, but an enhancement though, as there is no claim that Alertmanager would do this.

That said I would definitely welcome this addition. Do you want to take a stab at it?

**Comment by 0robustus1** [comment]
Fair enough. If it originally wasn't an intended feature it makes sense to classify it as an enhancement 👍 

I'll prepare a PR.
