### ISSUE TITLE
Different memory values in the k8s

### ISSUE THREAD

**Issue by OuFinx** [coreos/prometheus-operator#3325]
**What happened?**
I wanted to see RAM metrics from the POD but see different values

**Did you expect to see something different?**
I expect to see correct RAM metrics from the POD

**How to reproduce it (as minimally and precisely as possible)**:
In the dashboard for pod used 
`sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace", pod="$pod", container!="POD", container!=""}) by (container)`
And I see that my application is using 237MiB

![image](https://user-images.githubusercontent.com/12039911/87025326-ea8b7880-c1e2-11ea-8b19-8cb645b39aa3.png)

In the dashboard for NODE used
`sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster="$cluster", node="$node",container!=""}) by (pod)`
And I see that my application is using 119MiB

![image](https://user-images.githubusercontent.com/12039911/87025593-48b85b80-c1e3-11ea-8af2-39abc15c4ee2.png)

In the Worker nodes, I used command `docker stats`
I see that my application is using 105MiB
![image](https://user-images.githubusercontent.com/12039911/87025867-9af97c80-c1e3-11ea-9ffb-6d92d88652b5.png)

And I don't understand which metrics are right `container_memory_working_set_bytes` or `node_namespace_pod_container:container_memory_working_set_bytes` to track memory usage in kubernetus. To understand what limits to set.

And what does the metric `node_namespace_pod_container` mean?

**Environment**
EKS 1.16

* Prometheus Operator version:

quay.io/prometheus/prometheus:v2.18.1
quay.io/coreos/prometheus-config-reloader:v0.38.1
docker.io/jimmidyson/configmap-reload:v0.3.0

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

`eksctl`

* Manifests:

```
helm install prometheus --namespace=monitoring --set prometheusOperator.admissionWebhooks.enabled=false --set prometheusOperator.tlsProxy.enabled=false --set defaultRules.rules.etcd=false --set kubeEtcd.enabled=false --set grafana.persistence.enabled=true --set grafana.persistence.accessModes={ReadWriteOnce} --set grafana.persistence.size=8Gi stable/prometheus-operator
```
**NOTE: 1 pod has just 1 container.**

**Comment by paulfantom** [comment]
Seems like a good question for [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/) as all those dashboards and recording rules come from there.

**Comment by paulfantom** [comment]
Closing in favour of https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/458
