### ISSUE TITLE
Prometheus deletion deletes a Secret not managed by Prometheus

### ISSUE THREAD

**Issue by Bekt** [coreos/prometheus-operator#333]
**What did you do?**
1. Create a `Secret` named `prometheus-foo` with `prometheus.yaml` data key.
2. Create a `Prometheus` resource named `foo` omitting `serviceMonitorSelector` in the spec.
3. Verify prometheus is launched with the config file specified in step 1.
4. Delete the Prometheus object created in step 2. (`kubectl delete prometheus foo`)
5. Check if Secret from step 1 is still there (`kubectl get secret prometheus-foo`). It is not.

**What did you expect to see?**
5. Secret is not deleted when `Prometheus` resource is deleted.

**What did you see instead? Under which circumstances?**
5. Secret is deleted when `Prometheus` resource is deleted.

**Environment**
prometheus-operator: v0.8.2
k8s: 1.6

Context: #324

**Comment by brancz** [comment]
If the `Secret` is managed by the Prometheus Operator it [has a label](https://github.com/coreos/prometheus-operator/blob/410b1ea8a9985d4a1b6cbd7fbb3afd05a203af87/pkg/prometheus/statefulset.go#L191) with that information, so at [deletion](https://github.com/coreos/prometheus-operator/blob/410b1ea8a9985d4a1b6cbd7fbb3afd05a203af87/pkg/prometheus/operator.go#L802-L808) we just need to check whether it is `managed-by=prometheus-operator` and only then delete it. Do you want to give it a shot @Bekt ?

**Comment by brancz** [comment]
If we can get an implementation down for this quickly I'm happy to include it in the v0.9.0 release which should be in the upcoming days.

**Comment by Bekt** [comment]
I don't have much experience with testing in Go, so it's probably better for somebody else to pick this up. 😐

**Comment by brancz** [comment]
No worries, just want to encourage people and give them a chance :slightly_smiling_face: should be able to take care of this tomorrow.
