### ISSUE TITLE
Create VolumeMount on alert Manager.

### ISSUE THREAD

**Issue by varunsrinath** [coreos/prometheus-operator#3330]
Hi Team,

I have a alert manager with a webhook config, it needs to hit a endpoint that supports mTLS.  To load certs I have a PV and PVC. I am able to create volumes, However i am not able to create a mount path. 

Is there a way to add a mount path ? or any other way to load my client certs?

**Comment by brancz** [comment]
Do the `volume` and `volumeMount` fields not work?

**Comment by varunsrinath** [comment]
No only volume works, Volume Mount needs to be under container spec and
operator does not provide a way to inject that. I tried adding even mount
in alert manager yaml under spec. But no luck!!

**Comment by brancz** [comment]
Could you share your Alertmanager object?

This is what the docs on the `volumeMounts` field say:

> VolumeMounts allows configuration of additional VolumeMounts on the output StatefulSet definition. VolumeMounts specified will be appended to other VolumeMounts in the alertmanager container, that are generated as a result of StorageSpec objects.

**Comment by varunsrinath** [comment]
I just have the volumeMounts section above the volumes in
alertmanager.yaml, i did not know any place to add it there was no
container specific portion. Do you have any sample of using a volume mount
using PV in alert manager?

Thanks,
Varun

**Comment by brancz** [comment]
Sounds like you are deploying an old version of the prometheus operator.

**Comment by varunsrinath** [comment]
Today I pulled the latest code. However my CRDS are getting overridden to
older version after the custom resource are created. They are having a
generation: 2 meta data. Do you know how is it able to load back the old
CRD. I confirmed that my source code does not have it.

Thanks,
Varun

**Comment by varunsrinath** [comment]
I found the issue, I was using the old Prometheus operator image. Funny
thing is the image ships with old CRD which was overriding my new one.

Not sure if this is a bug. But by updating my prom-operator image to latest
I was able to mount the volumes.

Please close the issue.

Thanks,
V

**Comment by brancz** [comment]
This is expected. The prometheus operator used to manage CRDs, it doesn't anymore though.
