### ISSUE TITLE
Being able to enable high availability mode for 1 replica alertmanager

### ISSUE THREAD

**Issue by sjentzsch** [coreos/prometheus-operator#3337]
**What is missing?**
With v0.40.0 and https://github.com/coreos/prometheus-operator/pull/3233 we cannot enable high availability mode for 1 replica alertmanager anymore.

**Why do we need it?**

In my case, I have two clusters with each a prometheus-operator and a single alertmanager replica; but both of those form an Alertmanager cluster.

**Environment**

* Prometheus Operator version: v0.40.0

**Anything else we need to know?**:

I see that this is a rather uncommon use case, but likely enough to still be able to enable HA mode, despite only 1 replica is managed by a single prometheus-operator.

**Comment by brancz** [comment]
You're essentially looking for a setup where there is one global Alertmanager cluster across Kubernetes clusters? I think this is a neat idea! Do you think just enabling HA with a single replica would be sufficient for this? It would be amazing if we could talk through the entire architecture of how things would work, but if we can manage to I'd be more than happy to have something like this!

**Comment by sjentzsch** [comment]
Hi @brancz , exactly ! Yes, being able to separately enable HA (and leave it disabled when having a single replica) would be sufficient, and would only be an addition on top that would support my use case here. As a workaround, I did setup two Alertmanagers in each cluster (so HA is enabled), so we have four across two clusters.

Architecture-wise we are running Kubernetes on bare metal (https://metal-stack.io/) and are limited to having separate Kubernetes clusters in different locations (instead of one cluster on separate locations node-wise). For one of our customers we had to setup HA/redundant scraping of external targets, and thus have two separate Kubernetes clusters scraping the same targets individually (with low latency), and form an Alertmanager cluster to sync/deduplicate alerts. As the gossip protocol of Alertmanager requires both TCP and UDP on the same IP, we utilize metallb's shared IP construct for that (https://metallb.universe.tf/usage/#ip-address-sharing). Hope that explains it a bit better!

**Comment by brancz** [comment]
Just my own curiosity, how do the Alertmanager instances actually discover each other?

**Comment by sjentzsch** [comment]
Via prometheus-operator's `additionalPeers` (IP:Port) :-)

**Comment by brancz** [comment]
Neat! Yeah I think having a flag to explicitly turn it on when replicas is 1 would be ok if you want to add that.

**Comment by sjentzsch** [comment]
@brancz would you mind reviewing?
