### ISSUE TITLE
Alertmanager error : failed to join cluster

### ISSUE THREAD

**Issue by perumalla-giridhar** [coreos/prometheus-operator#3346]
**What happened?**
Running CRD alertmanager in replica=1
shows error in logs of alertmanager saying "failed to join cluster"
wrong arguments are passed to alertmanger
--cluster.peer=alertmanager-ml-0.alertmanager-operated:9094
where it says host `--cluster.peer=alertmanager-ml-0.alertmanager-operated:9094` not found
actual name of the host is `--cluster.peer=alertmanager-ml-0.alertmanager:9094`
**Did you expect to see something different?**
expecting not to see the error in logs
**How to reproduce it (as minimally and precisely as possible)**:
start alertmanager with replica = 1
**Environment**
OS: ubuntu:18.04.3
* Prometheus Operator version:
`Image:      quay.io/coreos/prometheus-operator:v0.39.0`
 
    

* Kubernetes version information:
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
   
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.
installed using kubeadm

* Prometheus Operator Logs:

logs of CRD alertmanager 
`level=info ts=2020-07-20T04:42:37.529Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-07-20T04:42:37.529Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=warn ts=2020-07-20T04:42:37.614Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-ml-0.alertmanager-operated:9094: lookup alertmanager-ml-0.alertmanager-operated on <dns ip>: no such host\n\n"
level=info ts=2020-07-20T04:42:37.614Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"`

**Anything else we need to know?**:

**Comment by brancz** [comment]
Can you upgrade to v0.40.0? https://github.com/coreos/prometheus-operator/pull/3233 is only available starting with that release.

**Comment by perumalla-giridhar** [comment]
Thank you. It is working now without errors.
