### ISSUE TITLE
Prometheus "--storage.tsdb.max-block-duration=2h" time reduction.

### ISSUE THREAD

**Issue by Tikam02** [coreos/prometheus-operator#3351]
### Can we reduce the "block-duration=2h"? 

```helm install prom ./prom -n testing --set storage.tsdb.min-block-duration=30m```
it didn't worked.Changed duration during installation, but getting same "2h" default in configs.

Tried with arguments it didn't worked,also changing manually it is not allowed to change,
``` Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)```

![Screen Shot 2020-07-21 at 12 18 52 PM](https://user-images.githubusercontent.com/10548085/88050690-f5e08b80-cb74-11ea-82f3-f5cd71df1484.png)
![Screen Shot 2020-07-21 at 12 19 13 PM](https://user-images.githubusercontent.com/10548085/88050726-055fd480-cb75-11ea-968d-c37ad75a25c0.png)
![Screen Shot 2020-07-21 at 5 06 31 PM](https://user-images.githubusercontent.com/10548085/88050783-20cadf80-cb75-11ea-9e20-bdc7f21cd557.png)

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.

**Comment by abhi4u1947** [comment]
Still open issue:

https://github.com/prometheus-operator/prometheus-operator/issues/4414#issuecomment-2402832211
