### ISSUE TITLE
Can't see service monitor through Prometheus web interface

### ISSUE THREAD

**Issue by myuser-git** [coreos/prometheus-operator#3363]
**What did you do?**

I have been trying to create a service monitor to scrape metrics for the following service:

![image](https://user-images.githubusercontent.com/6596178/88412148-1c860880-cda7-11ea-8571-e6d43c9f3e46.png)

Service monitor definition (which may or may not be correct):

![image](https://user-images.githubusercontent.com/6596178/88413072-88b53c00-cda8-11ea-89bf-67fb4130d128.png)

Full disclosure, I'm far from being an expert on the topic. I have two issues:
**1. How can I tell if a service monitor is doing its job?
2. How do I make sure I can see the service monitor through the Prometheus web interface?**

FYI, here is the Prometheus configuration from said interface:

![image](https://user-images.githubusercontent.com/6596178/88412560-c82f5880-cda7-11ea-9bbf-3a7c86415912.png)

**Did you expect to see some different?**

I'd expect to see the monitor-related info show up under targets in Prometheus and that Prometheus started scarping the targets.

**Environment**

> k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Prometheus Operator version:

chart=prometheus-operator-8.13.12

**Anything else we need to know?**:

**Comment by brancz** [comment]
Could you share your Prometheus object?

**Comment by myuser-git** [comment]
After re-installing Prometheus though Helm using the --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false option, the problem went away. Marking the issue as closed.
