### ISSUE TITLE
How can I get the container's highest cpu usage for a given period of time?

### ISSUE THREAD

**Issue by CarlosDGQ** [coreos/prometheus-operator#348]
I have installed the kube-prometheus on my machine;
I want to get the container's highest cpu usage for a given period of time,
for example, to get the container named kibana-logging highest cpu usage at the period 2017-05-06T02:50:00.781Z to 2017-05-06T03:00:00.781Z.
Is there any method to solve my problem?
Thaks a lot!

**Comment by brancz** [comment]
Please refer to the [Prometheus users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) regarding Prometheus usage questions.

I'm guessing what you are looking for are the [aggregation operators](https://prometheus.io/docs/querying/operators/#aggregation-operators) available in Prometheus. Just play around with those functions and the `container_memory_usage_bytes` metric exposed by the kubelet/cAdvisor (which are collected by default using kube-prometheus).

I will close this here, feel free to ask any further usage questions on the Prometheus mailing list.
