### ISSUE TITLE
Latest HELM chart does not include kubeletObject options

### ISSUE THREAD

**Issue by t-trout** [coreos/prometheus-operator#353]
**What did you do?**
Using HELM chart to install Prometheus-Operator and wanting to have the kubeletObject values set

**What did you expect to see?**
KubeletObject value set to defaults and the kubelet-object argument sent to Prometheus-operator on startup

**What did you see instead? Under which circumstances?**
No kubelet-object argument gets passed to Prometheus-operator upon startup.

The code changes for including the kubeletObject values are shown as having been reviewed and checked in on Apr. 7, and these are included in the latest README documentation, but the latest chart at http://charts.opsgoodness.com/prometheus-operator-0.0.1.tgz does not include these updates.  

Would really like to have these updates included as they are needed to get the kubelet information.

**Comment by mgoodness** [comment]
Just published `opsgoodness/prometheus-operator:0.0.2`. Note that `kubeletObject` has changed to `kubeletService`. Check the README for details.

**Comment by t-trout** [comment]
Gracias
