### ISSUE TITLE
Unneeded alerts when running on GKE

### ISSUE THREAD

**Issue by tsloughter** [coreos/prometheus-operator#355]
**What did you do?**

Installed through kube-prometheus deploy script to GKE.

**What did you expect to see?**

No triggered alerts.

These alerts are not possible when running on GKE, correct, in which case it is a documentation issue only? Something suggesting removing certain alerts for scheduler and etcd maybe?

**What did you see instead? Under which circumstances?**

Immediately these 2 alerts are triggered:

```
[FIRING:1] kube-scheduler (K8SSchedulerDown k8s critical) 
[FIRING:1] kube-controller-manager (K8SControllerManagerDown k8s critical)
```

And 3 hours later:

```
[FIRING:1] kubernetes (K8SApiserverDown k8s critical)
```

**Environment**

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE

**Comment by brancz** [comment]
I thought GKE runs the scheduler and controller manager as Pods within the cluster, in that case all you would need to do is create the `Service`s to select them. Those services are in `manifests/k8s/self-hosted/`.

The apiserver alert, however, seems legit.

**Comment by brancz** [comment]
I'm not exactly sure how GKE runs those components. Possibly directly on the host machines, not self-hosted. We're generally only trying to target self-hosted environments, which would mean you need to maintain your own fork removing the things you don't want. That said, I'd be willing to separate the alerting rules into different files, then maintaining your fork would be easy as you can just delete the rules for the kube-scheduler and kube-controller-manager. Eventually I think GKE wants to be self-hosted as well though, so one day that should all be in sync. At least all popular install methods are converging towards self-hosted.

**Comment by gytisgreitai** [comment]
I have a somehow related question. We're also on GKE and get alerts for `K8SControllerManagerDown` and `K8SSchedulerDown`. So what I've done is deleted those from .rules files, created yaml via `hack` script and applied that yaml file.
Those Rules no longer show up in prometheus, and not in alertmanager. 
However, I get constant alert about  `Firing` and `Resolved` for these alert to the slack channel. If i click on the link there is an alert, but not for `K8SSchedulerDown` and `K8SControllerManagerDown` 
I event tried to wipe out entire prometheus data folder and restart it. Still no luck. 
Any hints of how to get rid of them?

**Comment by brancz** [comment]
@gytisgreitai which version of Alertmanager are you running? I would recommend upgrading to latest `v0.7.1`, as a couple of bugs regarding behavior as you described have been fixed.

**Comment by brancz** [comment]
@tsloughter you can try creating manual endpoints objects pointing to the scheduler and controller-manager instances, you can look at the `etcd` folder in the kube-prometheus manifests for an example of how to do this. If that works, a contribution would be more than welcome :slightly_smiling_face: .

**Comment by ScottBrenner** [comment]
Did anyone find a resolution for this? Having the same issue.

**Comment by brancz** [comment]
@ScottBrenner you can always silence alerts.

**Comment by sebglon** [comment]
I have the same. How can i find the right IP/port to put on endpoint?

**Comment by brancz** [comment]
@sebglon I would contact GKE support, I am not aware of how the topology of GKE clusters are in that way. Otherwise I recommend just silencing/removing those alerts.

**Comment by lilic** [comment]
Since there  has not had any activity for some time, closing this issue, feel free to open a new one if you are still facing this problem.
