### ISSUE TITLE
[kube-prometheus] Specify version of k8s and add backwards compatibility 

### ISSUE THREAD

**Issue by ryanwalls** [coreos/prometheus-operator#363]
**What did you do?**
Running `contrib/kube-prometheus/hack/cluster-monitoring/deploy` does not seem to work on k8s 1.5.x.

**What did you expect to see?**
Ideally the readme for kube-prometheus would indicate which version(s) of the k8s it is targeting.  If possible, would ideally have the script dynamically work with different versions of k8s either using a flag or automatically detecting the api version.

**What did you see instead? Under which circumstances?**

```
unable to decode "manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "manifests/prometheus-operator/prometheus-operator-cluster-role.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
```

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.4-rancher1", GitCommit:"6ed2b64b2e1df9637661077d877a0483c58a6ae5", GitTreeState:"clean", BuildDate:"2017-03-17T16:58:04Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Created with Rancher

* Manifests:

See `contrib/kube-prometheus/hack/cluster-monitoring/deploy`

**Comment by brancz** [comment]
Yes we should definitely write that in there. @mgoodness can we stop helm from applying if a minimum cluster version is not met? I feel that would be the safest thing to do with the points of friction.

**Comment by ryanwalls** [comment]
@brancz I was trying to make the current scripts backwards compatible with 1.5 by removing the rbac related stuff, but I'm still seeing errors when running.  Any ideas?  Is there a specific commit hash of kube-prometheus that should work with 1.5?

Output:

```
slkc:kube-prometheus ryan$ ./hack/cluster-monitoring/deploy 
Error from server (AlreadyExists): namespaces "monitoring" already exists
serviceaccount "prometheus-operator" created
deployment "prometheus-operator" created
Waiting for Operator to register third party objects...done!
daemonset "node-exporter" created
service "node-exporter" created
deployment "kube-state-metrics" created
serviceaccount "kube-state-metrics" created
service "kube-state-metrics" created
secret "grafana-credentials" created
secret "grafana-credentials" configured
configmap "grafana-dashboards" created
deployment "grafana" created
service "grafana" created
configmap "prometheus-k8s-rules" created
serviceaccount "prometheus-k8s" created
service "prometheus-k8s" created
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-alertmanager.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-apiserver.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-k8s-apps-http.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kube-state-metrics.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-node-exporter.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-prometheus.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s.yaml": no kind "Prometheus" is registered for version "monitoring.coreos.com/v1alpha1"
secret "alertmanager-main" created
service "alertmanager-main" created
error: unable to decode "manifests/alertmanager/alertmanager.yaml": no kind "Alertmanager" is registered for version "monitoring.coreos.com/v1alpha1"
```

**Comment by mgoodness** [comment]
@brancz I think we could build that logic into the charts, sure.

**Comment by dmcnaught** [comment]
@ryanwalls I've been using 13a0dfbfc44f6c025363e612b469786a3cca091b on k8s 1.5 - right before the 1.6 changes...

**Comment by brancz** [comment]
@ryanwalls those errors are just because kubectl was not able to use apply for TPRs pre 1.6. To fix those errors you're having, just replace any `kubectl apply` call to TPRs in the deploy scripts to ` kubectl create`.

**Comment by ryanwalls** [comment]
@dmcnaught When I use that commit 13a0dfbfc44f6c025363e612b469786a3cca091b, it has errors spinning up the alertmanager statefulset.  

```
MountVolume.SetUp failed for volume "kubernetes.io/configmap/4c656171-3913-11e7-b6ca-0285ffacd72b-config-volume" (spec.Name: "config-volume") pod "4c656171-3913-11e7-b6ca-0285ffacd72b" (UID: "4c656171-3913-11e7-b6ca-0285ffacd72b") with: configmaps "main" not found
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "monitoring"/"main-0". list of unattached/unmounted volumes=[config-volume]
```

It seems to be looking for a ConfigMap named `main` that doesn't seem to be created.

**Comment by brancz** [comment]
In the `v0.7.0` release we replaced all uses of `ConfigMap`s for configurations to `Secret`s, as the Alertmanager and Prometheus configs may contain secrets.

https://github.com/coreos/prometheus-operator/releases/tag/v0.7.0

**Comment by ryanwalls** [comment]
@brancz The only thing I can think of is that somehow the tagged `v0.7.0` prometheus operator has the wrong version of the alertmanager thirdpartyresource somehow.   Because I can definitely see it should be trying to load the secret instead of the configmap from https://github.com/coreos/prometheus-operator/blob/43fdeb95df2003c216b63a2cc486c052033bd4c7/pkg/alertmanager/statefulset.go#L234-L243, but the prometheus operation v0.7.0 is registering a tpr for alertmanager that is trying to load a configmap.

**Comment by brancz** [comment]
The TPR is just a mean of storing arbitrary data, the registered TPR has not changed since inception. The only difference is how the Operator handles the content of a TPR differently. You're referencing different commits of code and usage. Can you elaborate which versions you are using and if the Alertmanager pod stays this way, maybe you can post the, pod yaml so we can investigate further. Thanks! :slightly_smiling_face:

**Comment by dmcnaught** [comment]
@ryanwalls I didn't see/notice that error, but looking at my notes I did see problems with data not appearing in Grafana.
My clusters are actually running
https://github.com/coreos/kube-prometheus.git at 333bd23434a8da6ed8bf4b6e57e72e71f75dbc40

**Comment by ryanwalls** [comment]
@brancz Yeah, I'm not entirely clear on how the versions inter-operate with respect to TPRs.  

Using the commit the @dmcnaught mentioned, when I run the `/hack/cluster-monitoring/deploy` script, I get two stateful sets created.  One called `alertmanager-main` and one just called `main`.  This seems odd as previous versions created only one stateful set for alertmanager.  
![image](https://cloud.githubusercontent.com/assets/842653/26075401/5dcba0d8-3972-11e7-88e7-aae40fcc10ba.png)
Both of the stateful sets seem to be looking for ConfigMaps, not secrets.

Here is the stateful set definition for `main`:
``` yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: 2017-05-15T19:11:55Z
  generation: 5
  labels:
    alertmanager: main
    app: alertmanager
  name: main
  namespace: monitoring
  resourceVersion: "13287298"
  selfLink: /apis/apps/v1beta1/namespaces/monitoring/statefulsets/main
  uid: 5c607c7e-39a2-11e7-b6ca-0285ffacd72b
spec:
  replicas: 3
  selector:
    matchLabels:
      alertmanager: main
      app: alertmanager
  serviceName: alertmanager
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app: alertmanager
    spec:
      containers:
      - command:
        - /bin/alertmanager
        - -config.file=/etc/alertmanager/config/alertmanager.yaml
        - -web.listen-address=:9093
        - -mesh.listen-address=:6783
        - -storage.path=/etc/alertmanager/data
        - -mesh.peer=main-0.alertmanager.monitoring.svc
        - -mesh.peer=main-1.alertmanager.monitoring.svc
        - -mesh.peer=main-2.alertmanager.monitoring.svc
        image: quay.io/prometheus/alertmanager:v0.5.1
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 6783
          name: mesh
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /var/alertmanager/data
          name: main-db
      - args:
        - -webhook-url=http://localhost:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: jimmidyson/configmap-reload
        imagePullPolicy: Always
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - configMap:
          defaultMode: 420
          name: main
        name: config-volume
      - emptyDir: {}
        name: main-db
status:
  replicas: 1
```

And here is the one for `alertmanager-main`:
``` yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: 2017-05-15T19:19:58Z
  generation: 1
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
  resourceVersion: "13287694"
  selfLink: /apis/apps/v1beta1/namespaces/monitoring/statefulsets/alertmanager-main
  uid: 7c38a8dc-39a3-11e7-b6ca-0285ffacd72b
spec:
  replicas: 3
  selector:
    matchLabels:
      alertmanager: main
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app: alertmanager
    spec:
      containers:
      - command:
        - /bin/alertmanager
        - -config.file=/etc/alertmanager/config/alertmanager.yaml
        - -web.listen-address=:9093
        - -mesh.listen-address=:6783
        - -storage.path=/etc/alertmanager/data
        - -mesh.peer=alertmanager-main-0.alertmanager.monitoring.svc
        - -mesh.peer=alertmanager-main-1.alertmanager.monitoring.svc
        - -mesh.peer=alertmanager-main-2.alertmanager.monitoring.svc
        image: quay.io/prometheus/alertmanager:v0.5.1
        imagePullPolicy: IfNotPresent
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 6783
          name: mesh
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /var/alertmanager/data
          name: alertmanager-main-db
      - args:
        - -webhook-url=http://localhost:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: quay.io/coreos/configmap-reload:latest
        imagePullPolicy: Always
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - configMap:
          defaultMode: 420
          name: alertmanager-main
        name: config-volume
      - emptyDir: {}
        name: alertmanager-main-db
status:
  replicas: 0
```

**Comment by dmcnaught** [comment]
@ryanwalls - yes - that version is pre secret replacing configmaps for config...

**Comment by ryanwalls** [comment]
@dmcnaught Thanks.  Yeah I see that now.  I think the earlier commit you mentioned https://github.com/coreos/prometheus-operator/commit/13a0dfbfc44f6c025363e612b469786a3cca091b was creating a Secret but the Alertmanager was looking for a ConfigMap.  I think I have enough to get it working now.  

If I get a working example with 1.5, then I'd be happy to create a PR with a README that has instructions.  Ideally, it would be good to have a tag and/or release that is specific to 1.5.

**Comment by ryanwalls** [comment]
@dmcnaught @brancz Thanks for all the help, but keep hitting more issues...  Rules for alerting on k8s don't seem to be mounted in the prometheus pod.  So there are no alerts in prometheus.  

Also, the targets to the kubelets and kubernetes endpoints are down.  
![image](https://cloud.githubusercontent.com/assets/842653/26078064/7d5ae78e-397b-11e7-8192-e6a2a0f9e6d1.png)

I think I'm going to wave the white flag until we upgrade to 1.6 or a documented release for 1.5 is available.  Currently we are running this commit without issue: https://github.com/coreos/kube-prometheus/commit/dee7f834fba6bd8159526890a8266bf4fae6a70f

**Comment by brancz** [comment]
That commit is ancient for the speed of this project. I'd definitely recommend upgrading to 1.6 as soon as you can. Other than that there are only minor differences that would be necessary for current master to work on a 1.5 cluster. My guess would be that you have to change all `kubectl apply` calls in the `hack/` scripts to `kubectl create` as there were issues in 1.5 that did not allow `kubectl apply` on TPRs. And in addition to that all RBAC resources would have to change the apiVersion from v1beta1 back to v1alpha1. These are changes that we could in theory solve with a helm chart, but we are currently relying for those on external contributions.

**Comment by ryanwalls** [comment]
@brancz If I was to contribute a helm chart, what's your vision for where it would live and what it would encompass?  I see there's already a chart for prometheus-operator here: https://github.com/coreos/prometheus-operator/tree/master/helm.  

So would you want to add to that existing chart to include more of what `kube-prometheus` does?  Or would you envision a separate chart that is put in https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus?

**Comment by brancz** [comment]
Sorry @ryanwalls, I lost sight of this. @mgoodness is maintaining the helm charts, I'm sure he can point you at something that needs some work. All contributions welcome! :slightly_smiling_face:

**Comment by bamb00** [comment]
I'm running into this issue with kubernetes v1.6.6 and prometheus-operator 0.11.1.  Is there a workaround or a fix?

Error:
unable to decode "prometheus-k8s-service-monitor-alertmanager.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"

**Comment by bamb00** [comment]
Hi,

I'm running into this issue with Kubernetes v1.6.6 and prometheus-operator 0.11.1.  Is there a fix or a workaround for this error below?

Error:
unable to decode "prometheus-k8s-service-monitor-alertmanager.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"

Env Info:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

Thanks.

**Comment by brancz** [comment]
@bamb00 that looks like a different problem. Is that error from when you try to apply the manifest with kubectl or an excerpt from the Prometheus Operator logs?

Could you give us the output of

```
kubectl get thirdpartyresources
```

As it seems they have not been registered, which could be due to an RBAC issue.

**Comment by bamb00** [comment]
Here is the output from TRPs,

# kubectl get thirdpartyresources
NAME                                    DESCRIPTION                           VERSION(S)
alertmanager.monitoring.coreos.com      Managed Alertmanager cluster          v1alpha1
prometheus.monitoring.coreos.com        Managed Prometheus server             v1alpha1
service-monitor.monitoring.coreos.com   Prometheus monitoring for a service   v1alpha1

**Comment by bamb00** [comment]
This part of the script did not get execute manually after applying prometheus-operator,

# Wait for TPRs to be ready.
printf "Waiting for Operator to register third party objects..."
until kctl get servicemonitor > /dev/null 2>&1; do sleep 1; printf "."; done
until kctl get prometheus > /dev/null 2>&1; do sleep 1; printf "."; done
until kctl get alertmanager > /dev/null 2>&1; do sleep 1; printf "."; done
echo "done!"

**Comment by ryanwalls** [comment]
@bamb00 You might try deleting your TPRs and rerunning the script from scratch.

**Comment by bamb00** [comment]
I'm running each yaml individually.  I need a workaround to get pass registering the TPRs.

**Comment by bamb00** [comment]
I see the problem.

The objects did not get create for each of the TRPs.  How do I do that?

**Comment by brancz** [comment]
@bamb00 it seems you are trying to apply the manifests currently on master of this repository, which will not work with `v0.11.1` of the Prometheus Operator, as we've promoted the objects from `v1alpha1` to `v1`. You should check out this commit 2747557, which was the last commit, where the manifests were compatiable, with `v0.11.1` of the Prometheus Operator. Note that the Prometheus Operator `v0.12.0` requires a Kubernetes `v1.7.x` cluster, so you can only upgrade to `v0.12.0` of the Prometheus Operator once you have upgraded your Kubernetes cluster to a `v1.7.x` or higher version. The Prometheus Operator will then migrate your objects automatically when you upgrade it from `v0.11.1` to `v0.12.0`.

**Comment by gianrubio** [comment]
Closing this as outdated
