### ISSUE TITLE
[Question] How can I pass in CLI args to prometheus?

### ISSUE THREAD

**Issue by jason-riddle** [coreos/prometheus-operator#368]
I need to change the path prefix that prometheus is using for the graph in order to properly render assets since I'm an ingress and forwarding to a service. My ingress is currently forwarding traffic on `/prom`, but once forwarded the javascript and css assets are not loading since they start with `/static`. It looks like the web prefix for the graph can be changed with the following CLI arg.

```
-web.route-prefix=/prom
``` 

So, is it possible to configure this in the `contrib/kube-prometheus` setup?

**Comment by fabxc** [comment]
The Prometheus TPR spec provides a field for the route prefix directly:
https://coreos.com/operators/prometheus/docs/latest/api.html#prometheusspec

**Comment by jason-riddle** [comment]
Awesome, thanks.
