### ISSUE TITLE
Change the default retention to be 360h

### ISSUE THREAD

**Issue by Gouthamve** [coreos/prometheus-operator#376]
To be inline with Prometheus default.

**Comment by brancz** [comment]
This was chosen intentionally as we are expecting a much higher series churn in a Kubernetes environment than for Prometheus in general. The real value of monitoring is alerting and for 99% of alerting you will not need more than the past 12h of data, so 24h should be plenty. When people have a different opinion what they need then they can set that explicitly :slightly_smiling_face:
