### ISSUE TITLE
How to use with out-of-pod exporters?

### ISSUE THREAD

**Issue by TamalSaha** [coreos/prometheus-operator#387]
We are trying to use Prometheus operator to monitor our production workloads. We have a number of 
use-cases where we want to run exporter as a separate pod from workload. Examples are:

- We are running PostgreSQL database using StatefulSet.
- We run HAProxy based ingress controller using deployment.

The reasons we want to run exporter as a separate pod from workload instead of a side-car are:

- Exporter can be added later without restarting production workload.
- Exporter can be updated to add more meaningful metrics without restarting workload.
- The same exporter can be used to expose metrics for workloads of same kind (multiple postgres DB in same/diff namespace, etc.). This is particularly useful for smaller cluster.

If we were writing Prometheus config by hand, this can be done by rewriting the `__address__` and `__metrics_path__` labels, as shown [here](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L79).

The way Prometheus operator generates Prometheus config, there is no way to add these labels. Can this model of out-of-pod exporters be supported in operator? Is there way to do this already in operator? We are willing to contribute code, if that helps to add this feature.

cc: @aerokite

**Comment by TamalSaha** [comment]
I have created a pr with a potential solution for this issue in #388

**Comment by TamalSaha** [comment]
@brancz, mind taking a look?

**Comment by brancz** [comment]
I've been traveling the past couple of days and am still badly jetlagged, will have a look as soon as I can - sorry for the delay!

**Comment by TamalSaha** [comment]
@brancz , sorry for pinging again. I wonder if you can take a look at this issue.

**Comment by brancz** [comment]
While I understand the benefits you are trying to get out of this, I don't think this is a use case we want to support, especially as this would be considered an anti-pattern as it is bypassing all the whitebox assumptions the Prometheus ecosystem uses and is used to. It is definitely the recommendation to run exporters as close to the actual application as possible.

The problems you mentioned are problems in infrastructure that need to be solved anyways, databases and all other applications need to be sanely deployed and configured as well. This is a very hard task, but I would not recommend running databases in a Kubernetes cluster if you haven't solved the restart/reload/deploymend/rollout of those. Once you have that, the above mentioned issues are non-issues anymore. :slightly_smiling_face:

**Comment by brancz** [comment]
If my above argument doesn't convince you or you need this asap, then I would recommend using a custom Prometheus configuration, which you can define yourself by leaving the `serviceMonitorSelector` empty.

I'll close this here.

**Comment by TamalSaha** [comment]
@brancz , thanks for the reply and also explaining the philosophical underpinning of your reply.
