### ISSUE TITLE
Prometheus pods shouldn't require cluster-wide read access

### ISSUE THREAD

**Issue by jer** [coreos/prometheus-operator#396]
When a Prometheus pod is created by the operator, that pod requires the ability to read cluster-wide pods, services, and endpoints. This seems unnecessary, and there is not a clear path to restricting namespace owners to their own namespaces while also providing a Prometheus TPR for them to use.

Here is an example error from the Prometheus pod logs:
```
time="2017-06-06T00:42:17Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:165: Failed to list *v1.Pod: User \"system:serviceaccount:test-namespace:default\" cannot list pods at the cluster scope." component="kube_client_runtime" source="kubernetes.go:73"
```

We don't want to give this pod/serviceaccount the ability to read all pods and services in the cluster. Is it necessary to provide this access, or can the call be restricted to a specific namespace?

**Comment by jer** [comment]
It just occurred to me that this is probably Prometheus itself, and not the operator. I'll try to open the dialog with them.

**Comment by fabxc** [comment]
Same folks largely :)

Prometheus 1.7 will allow you to configure Prometheus to only consider a fixed set of namespaces. Then you can configure your RBAC accordingly to only give access to certain namespaces.

**Comment by jer** [comment]
Thanks a lot for the response! I ended up finding issues tracking this in both repos that I'm now eagerly awaiting :)
