### ISSUE TITLE
Unable to define additional command-line flags for Prometheus

### ISSUE THREAD

**Issue by anton-pydev** [coreos/prometheus-operator#412]
Looking at Prometheus API docs and prometheus-operator examples I cannot figure out how to 
Define additional command-line flags for prometheus to start with .
For example I would like to define "-storage.local.series-sync-strategy=never" when I start prometheus .
Thanks in advance.

**Comment by brancz** [comment]
I'm unsure whether this flag will still be present in Prometheus 2.0, therefore I'm hesitant to add a configuration option that is 1) questionable to be set in this way and 2) is already at creation targeted to be deprecated in an upcoming release.

**Comment by anton-pydev** [comment]
I agree . But I am not talking about that specific flag , but about an ability to control command line options .

**Comment by brancz** [comment]
As mentioned in https://github.com/coreos/prometheus-operator/issues/306, custom flags is a non-goal for the Prometheus Operator. The whole point of it is to abstract away, how you're running Prometheus. Specifically storage flags should be abstracted. If there are other flags you want to set that are currently not possible but legitimately should be possible, then that's a missing feature :slightly_smiling_face: .

**Comment by anton-pydev** [comment]
@brancz  I agree with an approach . However I have ended up recompiling prometheus operator image with new hardcoded command line flags in an attempt to solve production issue .

The issue is scrape jobs stop running with an error : 
time="2017-06-11T14:56:58Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=1121 memoryChunks=29867 source="storage.go:982" urgencyScore=1
time="2017-06-11T14:59:18Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=98 memoryChunks=28646 source="storage.go:982" urgencyScore=1

I am still not %100 sure tweaking parameters will mitigate the issue . 
I have seen several recommendations in Brian's blog post : https://prometheus.io/docs/operating/storage/
That I was going to give a try , before abandoning the idea to fix it and simply waiting for Prometheus 2.0 . 

I am running a Load Lab for a customer that certifies Prometheus on K8s as  a new corporate monitoring solution , 
I have an experience with Prometheus on Bare Metal and I remember it took us an effort and lots of tuning to make it running in a stable way .
Thanks in advance!

**Comment by brancz** [comment]
That makes sense, for that purpose I'd suggest not using the Prometheus Operator until you've found the tuning that satisfies your environment, then when you have those we can see how we can incorporate that into the Prometheus Operator. But yes that is definitely a huge pain point of operating Prometheus, the Prometheus Operator already supports running Prometheus 2.0 alpha versions so you can try whether that works better for you.

Which ever way you go, feedback (ssues on 2.0 or tuning parameters) would be highly appreciated :slightly_smiling_face: .

**Comment by brancz** [comment]
We're supporting the latest beta release of Prometheus with the Prometheus Operator. I'd suggest to try that out. Having arbitrary arguments being passed to Prometheus is a non-goal for the Prometheus Operator as is gives up the possible control over the deployments.

Feel free to re-open if you think otherwise.
