### ISSUE TITLE
Service Monitor only works with Name as port

### ISSUE THREAD

**Issue by f0** [coreos/prometheus-operator#416]
**What did you do?**
Add a Service Monitor
**What did you expect to see?**
Targets added to Prometheus
**What did you see instead? Under which circumstances?**
Errors in the operattor log, targets not added
**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
	

* Kubernetes cluster kind: 

bootkube

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: ingress
  labels:
    k8s-app: ingress
spec:
  jobLabel: k8s-app
  endpoints:
  - port: 10254
    interval: 30s
    honorLabels: true
  selector:
    matchLabels:
      k8s-app: nginx-ingress-controller
  namespaceSelector:
    matchNames:
    - kube-system
```

* Prometheus Operator Logs:

```
i E0613 06:35:08.170266       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:08.172620       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:09.175988       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:242: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:10.179055       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:242: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:11.181946       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:242: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:12.185613       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:242: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
E0613 06:35:13.188693       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:242: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string 
```

**Comment by brancz** [comment]
It's unfortunate that we were inconsistent with the naming of the port field, we should have named it `portName` and then `port` would be a number. Right now I'd recommend using `targetPort` instead, that one can be a number.

@fabxc what do you think of the proposed change? It would be breaking, but better now than later I would say.

**Comment by fabxc** [comment]
I think we are consistent with K8S core resources. When specifying a port it's an object of `name` (string) and `port` (int). The name is generally optional, sometimes only if just a single port exists. This pattern can be found in pods, endpoints, and services.

When referencing a port of another resource, `port` is an `IntOrStr`, so can either set a fixed port or by port name in the referenced resource.
`port` in our endpoints spec is, just like `targetPort` such a reference and we could extend it to be an `IntOrStr` as well and generate the respective relabeling rule.
IIRC, we just didn't do it initially because we thought everyone should generally label all ports and didn't see an urgent use case for it.

**Comment by fabxc** [comment]
@f0 we went over it again. In fact, the current behavior is the correct one. If you want to define an explicit port (which you should avoid), set it as `targetPort`.

`port` allows referencing a named service port to be scraped for every pod of that service. The actual port number is inferred by which numeric port that named service port binds to for every individual pod.
`targetPort` allows you either specify a named port of a pod, that is not surfaced in the service or to  hardcode a numeric port to be scraped on every pod. This is the functionality you want here.

**Comment by f0** [comment]
@fabxc @brancz   ok thx
