### ISSUE TITLE
hack/cluster-monitoring/deploy   gives a lot of errors

### ISSUE THREAD

**Issue by dimthe** [coreos/prometheus-operator#421]
**What did you do?**

hack/cluster-monitoring/deploy

**What did you expect to see?**
a working prometheus set up

**What did you see instead? Under which circumstances?**
these errors

kube-prometheus]# hack/cluster-monitoring/deploy
namespace "monitoring" created
serviceaccount "prometheus-operator" created
service "prometheus-operator" created
deployment "prometheus-operator" created
unable to decode "manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "manifests/prometheus-operator/prometheus-operator-cluster-role.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
Waiting for Operator to register third party objects........................................done!
daemonset "node-exporter" created
service "node-exporter" created
deployment "kube-state-metrics" created
serviceaccount "kube-state-metrics" created
service "kube-state-metrics" created
unable to decode "manifests/kube-state-metrics/kube-state-metrics-cluster-role-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "manifests/kube-state-metrics/kube-state-metrics-cluster-role.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
secret "grafana-credentials" created
secret "grafana-credentials" configured
configmap "grafana-dashboards" created
deployment "grafana" created
service "grafana" created
configmap "prometheus-k8s-rules" created
serviceaccount "prometheus-k8s" created
service "prometheus-k8s" created
unable to decode "manifests/prometheus/prometheus-cluster-role-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "manifests/prometheus/prometheus-cluster-role.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-alertmanager.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-apiserver.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kube-controller-manager.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kube-scheduler.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kube-state-metrics.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-node-exporter.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-prometheus-operator.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s-service-monitor-prometheus.yaml": no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1alpha1"
unable to decode "manifests/prometheus/prometheus-k8s.yaml": no kind "Prometheus" is registered for version "monitoring.coreos.com/v1alpha1"
secret "alertmanager-main" created
service "alertmanager-main" created
error: unable to decode "manifests/alertmanager/alertmanager.yaml": no kind "Alertmanager" is registered for version "monitoring.coreos.com/v1alpha1"
[root@atomic01 kube-prometheus]# kubectl get pods
**Environment**
centos atomic hosts 
* Kubernetes version information:

	1.5.2

* Kubernetes cluster kind: 

	i had installed kubernetes via ansible 

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
The RBAC manifests are referencing the `v1beta1` version of the resources, whereas your cluster is 1.5.2 where those were still in `v1apha1`. The errors are valid, the script is meant to be run against 1.6.x clusters. Also keep in mind this is a script in a `hack/` directory :slightly_smiling_face: .

We intend to have broader compatibility with the helm charts. However, the Prometheus Operator unfortunately doesn't support 1.5.x clusters anymore, so my suggestion would be to upgrade the cluster.

But as this is not an issue with 1.6.x clusters (I used the script today off of master :slightly_smiling_face:) I'll close this here. Feel free to ask any questions if you still have any.
