### ISSUE TITLE
prometheus_local_storage_memory_series leak over time on an empty cluster

### ISSUE THREAD

**Issue by anton-pydev** [coreos/prometheus-operator#426]
On a basic cluster setup  3 nodes . 
K8s 1.5 
Prometheus 1.7 
No pods except for  K8s system pods and monitoring pods are running.
prometheus_local_storage_memory_series is growing with time , exploding when it reaches max amount of RAM available .
Number of series is growing without any reason for that.
Probably some ID that changes frequently is being part of a label , but cannot identify where it comes from .
Started a cluster with 40K series ..ended up with 150K after 12 hours  before Prometheus died .

**Comment by anton-pydev** [comment]
I have tried to switch to latest prometheus-operator 0.10.1
And to Latest prometheus v.1.7.1 even tried prometheus v.2.0.0-alpha2
Same result . Prometheus Pod Memory is growing till it scraping stops forever .

Command-Line Flags
alertmanager.notification-queue-capacity	10000
alertmanager.timeout	10s
config.file	/etc/prometheus/config/prometheus.yaml
log.format	"logger:stderr"
log.level	"info"
query.max-concurrency	20
query.staleness-delta	5m0s
query.timeout	2m0s
storage.local.engine	persisted
storage.local.path	/var/prometheus/data
storage.tsdb.max-block-duration	74h24m0s
storage.tsdb.min-block-duration	2h0m0s
storage.tsdb.no-lockfile	true
storage.tsdb.retention	744h0m0s
version	false
web.console.libraries	console_libraries
web.console.templates	consoles
web.enable-remote-shutdown	false
web.external-url	http://prometheus-k8s-1:9090/
web.listen-address	:9090
web.max-connections	512
web.read-timeout	30s
web.route-prefix	/
web.telemetry-path	/metrics

**Comment by brancz** [comment]
How long did you leave your Prometheus instance running to observe this? 31 days retention is quite a lot of time as well.

**Comment by anton-pydev** [comment]
Well this happened after 20 hours

**Comment by brancz** [comment]
What is the "max amount of RAM" that you mentioned? Depending on the amount of samples/chunks in memory and the available RAM, this might be fine.

**Comment by anton-pydev** [comment]
Max amount of RAM is a capping by K8s , I have started with 2G gradually increasing to 32G and even 64G , it just a matter of time till Prometheus  reaches the limit and stops scrapping .

**Comment by anton-pydev** [comment]
I have conducted a test on io1 1024GB 10K IOPS  EBS , on EBS optimized  instance .
The test included 1 node K8s cluster  + prometheus operator .
No application rolled out except for Kube system and Prometheus . 
After reaching container memory cap  , scrapping job stop forever . 
No changes to original latest dev branch accept for adding PVs 
Tried to add more RAM to pod but , it just prolongs the end . 
Before scrapping job fails I've noticed a spike in dirty series .

**Comment by anton-opsguru** [comment]
Downgrading prometheus version from 1.7.x 1.6.x to 1.5.2 seems to solve the problem . 
Probably due to the memory chunks calculation in prometheus-operators that's different for 1.5 versions ( you have specific flow control for that ) .

**Comment by brancz** [comment]
I'm still curious though how this still occurs in 2.0 as you mentioned, as 2.0 doesn't have anything like this anymore.

**Comment by anton-opsguru** [comment]
@brancz  Its sounds weird , but I install a new K8s cluster , with everything default . And rollout default prometheus-operator on AWS with i3.4XL instances and IO1 10K IOPS volumes 
And the only think that run on a cluster is prometheus stack . And nothing but prometheus 1.5.2 works stable .
All the rest stops scrapping after few hours when it reaches heap size . 
I have tried running with 2-4-6-32 and 64G RAM .
So it's command line params that are generated by operator that are not optimal .

**Comment by brancz** [comment]
That does sound very odd, as we're not experiencing anything like that upstream as far as I can tell (I'm also an upstream Prometheus maintainer/contributor). Can you post your Prometheus resource yaml and the generated statefulset manifest?

**Comment by robin-opsguru** [comment]
Hi @brancz, I've been working with @anton-opsguru on this, these are the configs

Prometheus Resource:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v1.6.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 2Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  storage:
    selector:
      matchLabels:
        app: "prometheus-k8s"
    resources:
      requests:
        storage: 10Gi
```

Generated StatefulSet:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1alpha1","kind":"Prometheus","metadata":{"annotations":{},"labels":{"prometheus":"k8s"},"name":"k8s","namespace":"monitoring"},"spec":{"alerting":{"alertmanagers":[{"name":"alertmanager-main","namespace":"monitoring","port":"web"}]},"replicas":1,"resources":{"requests":{"memory":"2Gi"}},"ruleSelector":{"matchLabels":{"prometheus":"k8s","role":"prometheus-rulefiles"}},"serviceAccountName":"prometheus-k8s","serviceMonitorSelector":{"matchExpression":[{"key":"k8s-apps","operator":"Exists"}]},"storage":{"resources":{"requests":{"storage":"10Gi"}},"selector":{"matchLabels":{"app":"prometheus-k8s"}}},"version":"v1.6.1"}}
  creationTimestamp: 2017-07-18T02:30:57Z
  generation: 1
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
  resourceVersion: "34585186"
  selfLink: /apis/apps/v1beta1/namespaces/monitoring/statefulsets/prometheus-k8s
  uid: 217723b5-6b61-11e7-a555-06f12dbbe7a3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      prometheus: k8s
  serviceName: prometheus-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        prometheus: k8s
    spec:
      containers:
      - args:
        - -storage.local.retention=24h
        - -storage.local.num-fingerprint-mutexes=4096
        - -storage.local.path=/var/prometheus/data
        - -storage.local.chunk-encoding-version=2
        - -config.file=/etc/prometheus/config/prometheus.yaml
        - -storage.local.target-heap-size=1431655764
        image: quay.io/prometheus/prometheus:v1.6.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /status
            port: web
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /status
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
          readOnly: true
        - mountPath: /var/prometheus/data
          name: prometheus-k8s-db
          subPath: prometheus-db
      - args:
        - -reload-url=http://localhost:9090/-/reload
        - -config-volume-dir=/etc/prometheus/config
        - -rule-volume-dir=/etc/prometheus/rules
        image: quay.io/coreos/prometheus-config-reloader:v0.0.1
        imagePullPolicy: IfNotPresent
        name: prometheus-config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-k8s
      serviceAccountName: prometheus-k8s
      terminationGracePeriodSeconds: 600
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: prometheus-k8s
      - emptyDir: {}
        name: rules
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: prometheus-k8s-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          app: prometheus-k8s
    status:
      phase: Pending
status:
  observedGeneration: 1
  replicas: 1
```

**Comment by brancz** [comment]
Could you try the latest Prometheus `v2.0.0-beta.0` and set a memory limit? That should make the linux kernel evict memory when necessary.

**Comment by brancz** [comment]
I'm happy to take suggestions on how to improve the automatic tuning of Prometheus storage parameters based on the memory request as well.

**Comment by brancz** [comment]
Prometheus 2.0 is now the standard everywhere in this repo, and should solve your problems. Feel free to report new issues or re-open this one if you continue to have problems.
