### ISSUE TITLE
Make `defaultBaseImage` configurable for prometheus and alertmanager

### ISSUE THREAD

**Issue by mikebryant** [coreos/prometheus-operator#430]
It would be useful to make these images configurable at a cluster level.

We provide a quay mirror inside all of our Kubernetes clusters to save bandwidth, and make them resilient to loss of internet. Currently we can override the `baseImage` in every `Prometheus` / `AlertManager` resource, but we have to tell all the people using the cluster to do so.

If we had a command line argument (like `--prometheus-config-reloader`), we could set this on the cluster level and life would be easier for our users.

**Comment by xuchenhao001** [comment]
@brancz Thanks for this fixing! I'm trying to use my custom Prometheus base image, so if you can give an example about this argument?

**Comment by brancz** [comment]
Taking the [kube-prometheus Operator deployment manifest](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator.yaml) as an example.

The `args` list would just need the additional flags `--alertmanager-default-base-image=quay.io/prometheus/alertmanager` and `--prometheus-default-base-image=quay.io/prometheus/prometheus`. Those are of course the default images, but can be changed to whatever you need.

**Comment by bamb00** [comment]
@brancz Where is the manifest if I were using helm? Thanks.

**Comment by brancz** [comment]
@bamb00 I'm not sure it exists for the helm charts. (cc @gianrubio)
