### ISSUE TITLE
syncVersion "deadlocks" control loop

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#45]
This was almost clear when implementing it, but the Prometheus operator gets stuck when `syncVersion` gets stuck, e.g. because there are no sufficient scheduling resources.
The work queue won't be processed any longer and hence even downscaling the replicas won't have any further effect.

To revisit: we only have to do this in the first place because PetSets do not automatically manage template updates for us, which they are intended to in the future.

**Comment by brancz** [comment]
Makes sense. Do you have an issue to track?

**Comment by fabxc** [comment]
https://github.com/kubernetes/kubernetes/issues/28706

We should still fix what we have. 
In my test setup, reducing the replicas in my TPR updates the PetSet (after restarting the operator to unstuck it). However, the PetSet controller does not seem to apply this by deleting my second Prometheus pod that is in pending as it cannot be scheduled. 
I've to manually delete the pod. Even then it got restarted once even though the PetSet had `replicas: 1` and it only stayed away after deleting it a second time.

Very obscure – will have to investigate tomorrow.

**Comment by fabxc** [comment]
Fixed for Prometheus operator.
