### ISSUE TITLE
Handle DeletedFinalStateUnknown everywhere

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#46]
All deletion event handlers need a piece of code along these lines: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L356-L371

**Comment by fabxc** [comment]
That should be fixed for the Prometheus part of the operator with #55

**Comment by brancz** [comment]
Agreed.

**Comment by fabxc** [comment]
Not fixed for Alertmanager yet though.
