### ISSUE TITLE
Which is the canonical representation of the operator, the bundle or the kube-prometheus manifests?

### ISSUE THREAD

**Issue by aknuds1** [coreos/prometheus-operator#464]
I'm trying to figure out how to install the Prometheus operator, but there is the issue that this repository says either to install it from [bundle.yaml](https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml) or from the [kube-prometheus manifests](https://github.com/coreos/prometheus-operator/tree/v0.10.1/contrib/kube-prometheus/manifests/prometheus-operator), and the two differ from each other. Can you please either synchronize them so they are equivalent or make one of them the One True Way of installing the operator? It would be extremely helpful.

**Comment by mxinden** [comment]
@aknuds1 If you just want to use the Prometheus operator you should use the `bundle.yaml`. If you want an opinionated way how to monitor your entire k8s cluster, use the `kube-prometheus` project. For a more detailed differentiation between the Prometheus operator and kube-prometheus click [here](https://github.com/coreos/prometheus-operator/tree/v0.10.1#prometheus-operator-vs-kube-prometheus).

I do see your point though. One could maybe be generated or referenced from the other. We will have to wait for @brancz to come back from his vacation, as he set most of this up. Thanks for the feedback!

**Comment by aknuds1** [comment]
@mxinden Yeah I understand the logical difference between the two, however it will be an issue if the two go out of sync wrt. how Prometheus Operator should be installed. No-one will know which is the right way, and schizophrenia ensues :/

**Comment by brancz** [comment]
FWIW the bundle is generated and I have plans to generate the root bundle and the kube-prometheus manifest from a canonical source, but it's not very high in prio right now, but I completely understand the confusion.

Maybe a section in the docs to explain that only one operator is needed whichever namespace is runs in, would solve lots of the confusion already.

**Comment by aknuds1** [comment]
Your plan to generate root bundle and kube-prometheus manifest from the
same source sounds like the way to go.
