### ISSUE TITLE
adding external metrics?

### ISSUE THREAD

**Issue by strowi** [coreos/prometheus-operator#465]
For hardware/raid-monitoring purposes we currently have the node-exporter running directly on the cluster-nodes

How do we add external endpoints to scrape?

regards,
strowi

**Comment by fabxc** [comment]
The recommended approach is to create a headless service for which you have your configuration management or similar populate the Kubernetes endpoints object. Prometheus then sees it as just another service.

There are also "external" services in Kubernetes now, which we want to support eventually (#218)

**Comment by strowi** [comment]
ah, so i just setup a 2nd 'normal' prometheus which will be scraped. Thx for the clarification!
