### ISSUE TITLE
targetPort does not work as advertised

### ISSUE THREAD

**Issue by ewolff** [coreos/prometheus-operator#469]
**What did you do?**

Take the example app at https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/hack/example-service-monitoring

Replace `port: web` with `targetPort: 8080` as documented at https://coreos.com/operators/prometheus/docs/0.10.1/api.html#endpoint

**What did you expect to see?**

Metrics should still be display

**What did you see instead? Under which circumstances?**

No metrics are displayed any more.
Looking at https://groups.google.com/forum/#!topic/prometheus-users/dKT8JG2qbX4 it seems others have the same issue.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDate:"2017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

minikube version: v0.20.0

**Comment by tamalsaha** [comment]
cc: @aerokite

**Comment by fabxc** [comment]
You are right, thanks for reporting. #471 should fix this.
