### ISSUE TITLE
Allow specifying service port for Alertmanager

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#47]
Currently we just take the first service port in the list to generate Alertmanager URLs to add as Prometheus flags.
The user should be able to specify a port name or plain number as we cannot expect any particular order in the service ports.

Of course we can often make this assumption – especially if the Alertmanagers are run via the operator.
When using service discovery in Prometheus to find AMs, we have no guarantees around order though and don't know which one is the first.

@brancz

**Comment by brancz** [comment]
hmm ... tricky, just my initial thought: the name of an `Endpoints` object and the name of the port of it to use in the Prometheus TPR.

**Comment by fabxc** [comment]
Yes, that's what I was going for. We just have to add another field to our Alertmanager list items in the Prometheus TPR. We might want to default it to whatever the Alertmanager picks. I think I'm generally against implicitness for such a critical thing – but as we cannot report an error anyway, we might just as well try to do the right thing.

**Comment by brancz** [comment]
sgtm, if people use the alertmanager operator as well, then there's no problem ;)

**Comment by fabxc** [comment]
Fixed
