### ISSUE TITLE
ServiceMonitor cannot mount additional TLS certs for etcd

### ISSUE THREAD

**Issue by grrywlsn** [coreos/prometheus-operator#472]
I'm trying to get the ServiceMonitor to scrape my metrics endpoint of my etcd masters (external to the Kubernetes cluster), which use TLS to secure connections.  They have fixed IPs, so I can define them as endpoints, and I'm able to get basic stats in that way from Prometheus node exporter.

The problem is that I cannot define the cert and key file needed for the TLS communication. I'd also be able to mount these to the Prometheus pods created by the Operator, so that it's available when scraping the defined etcd ServiceMonitor.

Is there a way around this currently, or if not, is it something that will be made possible soon?

**Comment by fabxc** [comment]
You can specify cert and key file in the `tlsConfig` section of the [Endpoint](https://coreos.com/operators/prometheus/docs/latest/api.html#endpoint) item of the ServiceMonitor.
They accept a file path that is intended to match one of the Secrets which are provided in the `secret` list of the [Prometheus](https://coreos.com/operators/prometheus/docs/latest/api.html#prometheusspec) object. You have to stick with the path prefix specified there.

This should work today but is possibly a bit awkward. We've been thinking about directly referencing a secret by namespace/name in the `tlsConfig` in the future.

**Comment by grrywlsn** [comment]
I figured I could add the cert and key paths there, but didn't realise I could include them in the same Secrets. Thanks, will try that out.
