### ISSUE TITLE
Allow configuring logs

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/prometheus-operator#474]
Right now, logs can only be configured via command line parameter, not configuration file.

```
prometheus -h 
...
 == LOG ==

   -log.format "\"logger:stderr\""
      Set the log target and format. Example:
      "logger:syslog?appname=bob&local=7" or "logger:stdout?json=true"

   -log.level "\"info\""
      Only log messages with the given severity or above. Valid levels:
      [debug, info, warn, error, fatal]
```

We're using a paid logging aggregator, and we'd like to (1) set logging output to json and (2) limit the amount of logging e.g. we received upwards of 3.8 million log lines for "checkpointing," which ate up our logging limit.

**Comment by brancz** [comment]
This sounds reasonable, would like to try and implnement this @julianvmodesto ?

**Comment by julianvmodesto** [comment]
Sure! I'll see if I can find some time this week.

**Comment by brancz** [comment]
Great! Let me know if I can guide you if needed!

**Comment by TatyanaBol** [comment]
Hello
We use your prometheus-operator.
It fills our logs with a lot of info entries.
How can we configure log level?
Thanks

**Comment by 23doors** [comment]
Why was this closed when only loglevel config (without log format) was added? And inconsistently only to prometheus (and not to alertmanager).
