### ISSUE TITLE
kube-prometheus: Why is AlertManager configuration a secret?

### ISSUE THREAD

**Issue by aknuds1** [coreos/prometheus-operator#476]
Why configure AlertManager configuration as a secret in the cluster, considering [it's already public in GitHub](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/alertmanager/alertmanager-config.yaml)?

**Comment by mxinden** [comment]
@aknuds1 The Alertmanager configuration is in a k8s secret as it can contain all kinds of secrets e.g. your access token to *Slack*. I am not sure what you mean by "considering it's already public in GitHub".

**Comment by aknuds1** [comment]
@mxinden The [secret definition](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/alertmanager/alertmanager-config.yaml) is in GitHub.

Is it created as a secret because users are to customize the configuration according to their needs?

**Comment by mxinden** [comment]
@aknuds1 Yes exactly. With the default version there is no point in using a secret, but once you add any credentials ("customize the configuration according to their needs") a k8s secret makes sense.

**Comment by aknuds1** [comment]
@mxinden Thanks for clarifying! :) I'm just digging into this stuff, hope you don't mind my asking.

**Comment by brancz** [comment]
No worries @aknuds1 ask away, we're happy to spread knowledge :wink: .
