### ISSUE TITLE
Unable to deploy `v2.0.0-beta.0`

### ISSUE THREAD

**Issue by george-angel** [coreos/prometheus-operator#480]
We are currently running `1.7.1`.

Having updated the `version` of the `Prometheus` type to `v2.0.0-beta.0`, I have then deleted the `StatefulSet`. New one has the correct image: `quay.io/prometheus/prometheus:v2.0.0-beta.0` and following args:

```
      - args:
        - -config.file=/etc/prometheus/config/prometheus.yaml
        - -storage.local.path=/var/prometheus/data
        - -storage.tsdb.no-lockfile
        - -storage.tsdb.retention=72h
        - -web.external-url=<<address>>
```

But is unable to start:

`prometheus: error: unknown short flag '-c'`

**Comment by fabxc** [comment]
We changed our flags to use double dashes (`--`) but forgot to adjust those in the default entry point of our docker container. This is already fixed in HEAD of `dev-2.0`.

In the meantime, overriding the entry point when starting your container should work.
Additonally, `-storage.local.path` is `-storage.tsdb.path` now.

**Comment by george-angel** [comment]
@fabxc thanks for replying, when you speak of `entrypoint` what do you refer to, I only have access to: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec for modification using the operator.

Which creates the `StatefulSet`. Are you suggesting using our own version of `baseImage` with overridden `entrypoint`?

Thanks

**Comment by fabxc** [comment]
Oh, my bad – I thought this issue was filed in prometheus/prometheus. For the operator it's our job to make this transition of course.

**Comment by george-angel** [comment]
Shouldn't https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L318 have two dashes?

**Comment by vnandha** [comment]
@fabxc Is the flag `storage.local.target-heap-size` is supported in 2.x ?  (looks like it is not from the --help). 

What is the alternate way/flags to control memory?

**Comment by brancz** [comment]
@vnandha the new Prometheus storage is `mmap`ed which means that the operating system will take care of evicting memory and therefore additional resource control by Prometheus should not be necessary anymore! :slightly_smiling_face: 

Regarding what is happening in this reported issue, I'll have to investigate and report back. (I just got back from vacation and have a good size backlog :slightly_smiling_face:)

**Comment by vnandha** [comment]
Thanks for clarifying @brancz, Is there a way to limit the amount of memory visible to Prometheus container? ( I mean in k8s, does Prometheus know the request/limit memory we set in the container ? ) Sorry to deviate from the original question.

We have a situation where we use `v2.0.0-alpha.2` which has allocated request memory is 16G ( no limit is set). It keeps utilizing more memory. I hope it does not OOM if we set the limit (  I am going to try that )

**Comment by brancz** [comment]
@vnandha I talked to @lucab and he mentioned that `mmap`ed memory is one of the first things that get eviceted by the kernel, when hitting the requested amount of memory (requested as in the fields in Kubernetes).

**Comment by vnandha** [comment]
Thank you @brancz Actually setting `resource.limits.memory` for Prometheus helps to keep the memory under the limit.

**Comment by brancz** [comment]
Regarding the initial issue, the latest Prometheus Operator release (`v0.11.0`) supports for the latest Prometheus 2.0 beta release, the confusion came from the support being implemented, but not released at that point. I just tried out running the `v2.0.0-beta.0` image and it worked. Just to make sure, could you also confirm this @george-angel?

**Comment by george-angel** [comment]
Yep, all good, closing.

**Comment by raliste** [comment]
It appears that the LifeCycle API is disabled by default in v2.0.0-beta.0, thus I'm getting `ts=2017-08-02T22:44:45Z caller=main.go:214 component=volume-watcher msg="Reloading Prometheus temporarily failed." err="Received response code %!s(int=403), expected 200" next-retry=46.860582567s`. at the prometheus-config-reloader.

Normally you would just add `--web.enable-lifecycle` to the prom args, but there's no way to define extra flags at the statefulset.

**Comment by brancz** [comment]
@raliste we should indeed enable it always as we rely on that behavior for the config reloader. Do you want to create the PR to do so?
