### ISSUE TITLE
`node-exporter` DaemonSet ~> Pod 'Evicted', not Replaced => Node 'Vanishes', No Rule/Alert Triggered

### ISSUE THREAD

**Issue by hartmut-pq** [coreos/prometheus-operator#486]
**What did you do?**
Run kube-prometheus

**What did you expect to see?**
_Pods_ for `node-exporter` _DaemonSet_ all up and running.

**What did you see instead? Under which circumstances?**
Had issues with a _node_ -> _DiskPressure_ which led to pods getting evicted - expected behaviour in general..
..but I noticed the _pod_ from the _DaemonSet_ got evicted too, yet not replaced by a new one which led to having no more metrics for that node - it kind of just vanished out of existence and didn't trigger any alerts.

That may be a rare case? But still would be great to either solve the issue with the evicted DaemonSet Pod (which may be a kubernetes native issue) - or at least catch via a rule -> alert.

**Environment**

* Kubernetes version information:
v1.6.6

* Kubernetes cluster kind: 
kops

* Manifests:
https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

**Comment by hartmut-pq** [comment]
Note: Just discovered https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/assets/prometheus/rules/node.rules
which was not triggered - for the value is not `!= 1` but the whole metrics just vanishes.

**Comment by brancz** [comment]
Thanks for bringing this up! Any failure report can potentially be a valuable alerting rule! :slightly_smiling_face: 

It's a bit more complicated than that, because that rule actually triggers when _all_ targets disappear (which usually indicates, that something is wrong with discovery). That's how this rule is intended to work currently, however, I do agree, that we should add some additional ones. We [already have similar alerts for kubelets](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules#L30-L50), this sounds like it would make sense to add similar ones for nodes/node-exporter. The caveat would be that we can tell how many node-exporters there _should_ be through the metrics exposed by `kube-state-metrics`.

If you want to give this a go, I'd be happy to guide you.

**Comment by hartmut-pq** [comment]
thx, will definitely have a look!

**Comment by brancz** [comment]
@hartmut-pq do you think you can get to this? If not I'm happy to take over.

**Comment by hartmut-pq** [comment]
Hi, I think I have a solution, the rules for kubelets didn't help though - but could improve those, too...
I'm just quite busy right now - will come back to you if I can't squeeze it in... but ideally will create one/multiple PRs

**Comment by brancz** [comment]
Now I'm curious :wink: feel free to open multiple PRs. Just wanted to ping and see what's up, no rush. Thanks for all your efforts!

**Comment by brancz** [comment]
Any progress on this?

**Comment by atopuzov** [comment]
How about adding a more general rule about daemonsets? to kube-state
Something on the line of
```
    ALERT DaemonSetsNotScheduled
      IF kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
      FOR 10m
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "Daemonsets not scheduled correctly",
        description = "A number of daemonsets are not scheduled."
        }

    ALERT DaemonSetsNotRunning
      IF kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_number_ready > 0
      FOR 10m
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "Daemonsets not ready",
        description = "A number of daemonsets are not ready.."
        }

    ALERT DaemonSetsMissScheduled
      IF kube_daemonset_status_number_misscheduled > 0
      FOR 10m
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "Daemonsets not scheduled correctly",
        description = "A number of daemonsets are running where they are not supposed to run."
      }
```

**Comment by brancz** [comment]
All of those sound great! Could you open a PR for them @atopuzov ?

(they will have to be in the Prometheus 2.0 alerting rule format though :slightly_smiling_face: )

**Comment by atopuzov** [comment]
@brancz Will do. 
I'll also try to update the charts to use the new prom 2.0 rules.

**Comment by atopuzov** [comment]
@brancz does [this](https://github.com/coreos/prometheus-operator/pull/755) look ok?

**Comment by brancz** [comment]
> I'll also try to update the charts to use the new prom 2.0 rules.

That sounds fantastic! Thanks a lot!

**Comment by brancz** [comment]
With #755 merged, I'll close this here.
