### ISSUE TITLE
prometheus-config-reloader: err="decode error status: payload is not a kubernetes protobuf object"

### ISSUE THREAD

**Issue by hartmut-pq** [coreos/prometheus-operator#490]
**What did you do?**
Run kube-prometheus

**What did you expect to see?**
Prometheus being configured by _prometheus-config-reloader_

**What did you see instead? Under which circumstances?**
getting following logs for `prometheus-config-reloader`:

```
ts=2017-07-20T09:18:48Z caller=main.go:227 component=volume-watcher msg=Starting...
ts=2017-07-20T09:18:48Z caller=main.go:202 component=volume-watcher msg="Updating rule files..."
ts=2017-07-20T09:18:51Z caller=main.go:205 component=volume-watcher msg="Updating rule files failed." err="decode error status: payload is not a kubernetes protobuf object"
ts=2017-07-20T09:18:51Z caller=main.go:210 component=volume-watcher msg="Reloading Prometheus..."
ts=2017-07-20T09:18:53Z caller=main.go:215 component=volume-watcher msg="Prometheus successfully reloaded."
```

Note: Already using _prometheus-operator_ `v0.10.2`

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kops

* Prometheus Operator Logs:
looking ok...

**Comment by brancz** [comment]
Thanks for reporting!

We should add some more error tracing to see where this originates from. My question would be whether this occurs consistently in your cluster and you can reproduce it, or whether this just occurred once.

**Comment by hartmut-pq** [comment]
Hi @brancz - consistent.
Just newly applied to a new cluster - occurs for both replicas - every time when I delete / apply again. So I can't get prometheus to work at all - has blank configuration and no rules applied and is therefore effectively not working.

Have it up and running on another cluster k8s `v1.5.7` with the exact same setup.

Any way I could help debugging?

**Comment by brancz** [comment]
We're using [this](https://github.com/ericchiang/k8s) light-weight kubernetes client implementation. I think we may have hit: https://github.com/ericchiang/k8s/issues/46.

**Comment by hartmut-pq** [comment]
So it's effectively an RBAC issue first - secondly the error message returned can't be parsed/decoded properly..?
Can I reproduce the 'get configmaps' API call from inside the container somehow to find out the error / RBAC issue? what's to be retrieved exactly?

**Comment by hartmut-pq** [comment]
Oh my... :-( found the issue - I've had the ClusterRole & ClusterRoleBinding disabled for v1.5 and forgot to apply to the v1.6 cluster.. reapplied, all working fine now..!!!

Many thanks otherwise for your help and jumping on immediately!

**Comment by brancz** [comment]
Yes that would have been my next step. Unfortunately I believe there is only `wget` in that container, but what you should be able to do is launch an ubuntu container with the same service account and try to curl the api with the right ca and client certificate. I have to run right now, if you can get it working yourself that would be great if not I'll try it out a bit later.

**Comment by brancz** [comment]
Ahh cool. At least we could figure it out quickly. :slightly_smiling_face:

**Comment by hartmut-pq** [comment]
thx a lot ! 👍
