### ISSUE TITLE
Use `podManagementPolicy` for the StatefulSets

### ISSUE THREAD

**Issue by mikebryant** [coreos/prometheus-operator#491]
In 1.7, a new field `podManagementPolicy` is available.
https://kubernetes.io/docs/api-reference/v1.7/#statefulsetspec-v1beta1-apps

For Prometheus and AlertManager, we could use `podManagementPolicy: Parallel` to get faster scale up.
This would also help out in a situation where the AZ where the prometheus-0 volume is located is unavailable. (This currently means the whole prometheus cluster is down, even though we set replicas to 2, as it waits for -0 to start up before it starts -1)

In `Parallel` mode they'd all start up, which would be much better for us. And as the daemons don't interact, it shouldn't cause any problems.

**Comment by brancz** [comment]
Thanks for sharing! For Prometheus this is definitely the case, and we should enable that. I'm curious as to how this will effect the Alertmanager though especially in terms of [rolling deployments](https://github.com/coreos/prometheus-operator/pull/458), I can imagine there could be some failure scenarios for the Alertmanager.

**Comment by mikebryant** [comment]
I don't think it affects rolling deployments.

e.g. if you have 3 instances and you set an update, it will still create/destroy/create/destroy etc.

The difference is, if you have 0 running instances and you ask it for 3, it will start them all at once, instead of waiting for the first one to be ready.

**Comment by brancz** [comment]
We have some basic tests around rolling deployments, I guess we should just try it out and see how it goes.

**Comment by brancz** [comment]
Where possible it's now implemented. :tada: Closing here.
