### ISSUE TITLE
contrib/kube-prometheus installs grafana but helm chart doesn't

### ISSUE THREAD

**Issue by tsloughter** [coreos/prometheus-operator#493]
**What did you do?**

Installed the `kube-prometheus` helm chart.

**What did you expect to see?**

Either the helm chart to include grafana or `contrib/kube-prometheus` to not include it.

**Comment by brancz** [comment]
Grafana is currently not included, but coming up: https://github.com/coreos/prometheus-operator/pull/470

**Comment by tsloughter** [comment]
Oh, sorry, missed that PR! :). I'll close this.
