### ISSUE TITLE
prometheus-operator cuased k8s to behave abnormally

### ISSUE THREAD

**Issue by flyer103** [coreos/prometheus-operator#494]
**What did you do?**
Just run `kubectl apply -f bundle.yaml` to try prometheus-operator.

**What did you expect to see?**
I could use prometheus deployed by prometheus-operator.

**What did you see instead? Under which circumstances?**
After running prometheus-operator, I ran `kubectl get pod` but got

<img width="733" alt="image" src="https://user-images.githubusercontent.com/829039/28457550-2c7287b2-6e39-11e7-8aaf-8d27a344ee56.png">

I logined on to the k8s master node and found that `docker` seemed behave abnormally. So I restarted docker and then ran `kubectl get pod`:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/829039/28457582-4c14ddcc-6e39-11e7-84be-8cb4369517a6.png">

And I also found that `apiserver` crashed some times.

**Environment**
OS: ubuntu16.04

* Kubernetes version information:

1.7.0

* Kubernetes cluster kind: 

	kismatic

* Manifests:

I didn't modify the `bundle.yaml` file.

* Prometheus Operator Logs:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/829039/28457699-b5bf6436-6e39-11e7-9183-37a1b45e0b76.png">

**Comment by brancz** [comment]
I'm unsure how the Prometheus Operator might cause this. If your cluster responds, could you show us the Prometheus Operator logs?

```
$ kubectl logs deploy/prometheus-operator -f
```

**Comment by flyer103** [comment]
I have tried some times and gave up at last. 
Now I'm reinstalling k8s on new nodes which have more CPU/Memory resources and will try again.

**Comment by brancz** [comment]
Let us know how it goes :slightly_smiling_face:

**Comment by flyer103** [comment]
At first I deployed k8s master on a node which has 1CPU and 1GiB memory and in this situation, running prometheus-operator caused the k8s cluster couldn't work.
Now I have deployed k8s master on a node which has 1CPU and 2GiB memory and now everything works as expected.

So I think that prometheus-operator may need more memory that the master node couldn't offer and it makes `apiserver` or other k8s components behave abnormally.

Thank you for your attention to this matter @brancz

**Comment by brancz** [comment]
Happy that could solve your issue although it seems odd to me as I have a 1.7.0 cluster running the latest Prometheus Operator and it is using just `16777216` bytes of memory (roughly 17Mb), so I'm unsure how that could have effected it. That said, 1Gb is quite small.
