### ISSUE TITLE
tests: Expose logs of the Prometheus Operator after CI test run

### ISSUE THREAD

**Issue by mxinden** [coreos/prometheus-operator#503]
The Jenkins-CI should expose the logs of the Prometheus Operator for better debugging. One way of solving this is to write the logs of the Prometheus Operator into a file into `./build` before killing it. Whatever is in that folder will be archived by Jenkins and thereby visible after the test execution.

**Comment by brancz** [comment]
Out of necessity I added this to #555. As that's merged now, I'm closing here.
