### ISSUE TITLE
helm/prometheus: can't evaluate field serviceMonitorSelector in type interface {}

### ISSUE THREAD

**Issue by ringods** [coreos/prometheus-operator#507]
**What did you do?**

Deploy `kube-prometheus` helm chart.

**What did you expect to see?**

Correctly deployed resources.

**What did you see instead? Under which circumstances?**

```
Error: render error in "kube-prometheus/charts/prometheus/templates/servicemonitors.yaml": template: kube-prometheus/charts/prometheus/templates/servicemonitors.yaml:19:17: executing "kube-prometheus/charts/prometheus/templates/servicemonitors.yaml" at <.Values.serviceMonit...>: can't evaluate field serviceMonitorSelector in type interface {}
```

**Environment**

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kops, version 1.6.x

* Manifests:

```
kube-prometheus
```
Same when using it directly from http://charts.opsgoodness.com or from git sources.

* Prometheus Operator Logs:

```
No logs yet, as I'm still trying to deploy.
```

* Custom feedback

When looking at the sources, I see that the values file always points to the plural word `serviceMonitorsSelector`, while in this file, it refers to the singular word `serviceMonitorSelector`:

https://github.com/coreos/prometheus-operator/blob/4030fe9337b5e39781603ec56679331c39cdaf23/helm/prometheus/templates/servicemonitors.yaml#L19

Also, in the above template, this variable access is not guarded with an `if` as seen in this file:

https://github.com/coreos/prometheus-operator/blob/4030fe9337b5e39781603ec56679331c39cdaf23/helm/prometheus/templates/prometheus.yaml#L50

**Comment by brancz** [comment]
This was actually a problem in the original manifest. This has since then been fixed in the original manifests:

https://github.com/coreos/prometheus-operator/commit/91c20464849d56aa3f00d78dcd5c9ffcbf05e759#diff-8e540ec43f84715379754175fa4337ae

**Comment by ringods** [comment]
@brancz I don't get it. I'm talking about an issue with singular `serviceMonitorSelector` and plural `serviceMonitorsSelector` and you point to a commit changing singular `matchExpression` to plural `matchExpressions`.

Can you also elaborate the relation between the Helm chart in the `helm` folder and the manifests you refer to in the `contrib` folder?

**Comment by brancz** [comment]
Got it sorry. You're absolutely right, it seemed like it was the same problem, because the before the above commit we had the same outcome, but you're absolutely right, his seems like a problem with the helm chart itself.

@mgoodness could you have a look at this?

**Comment by ringods** [comment]
@mgoodness @brancz my colleague @duboisph create PR #515 to fix this. Can you have a look at it?

**Comment by brancz** [comment]
Closing here as #515 was merged.
