### ISSUE TITLE
Limits not being picked up

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#510]
**What did you do?**

I added resource limits to my custom Prometheus object file. The Prometheus Operator service consumes that and manages the StatefulSet itself. Resource limits are now enforced for all namespaces in our k8s environment.

**What did you expect to see?**

I expected to see the new limits reflected when I ran `kubectl describe statefulset prometheus-shared`.

**What did you see instead? Under which circumstances?**

I saw what I think are the default limits?
    Limits:
      cpu:		5m
      memory:		10Mi

Additionally I am seeing: 
FailedCreate	create Pod prometheus-shared-0 in StatefulSet prometheus-shared failed error: pods "prometheus-shared-0" is forbidden: failed quota: observability-resourcequota: must specify limits.cpu,limits.memory

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Custom chef deploy on bare metal CentOS 7

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Yes, this is a known problem. With Kubernetes 1.7 released (with proper StatefulSet deployments), we can now work towards deployments on any PodTemplate changes. These changes will be coming up soon.
