### ISSUE TITLE
Permission denied creating a new pod in statefulset

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#518]
**What did you do?**

I upgraded to the newer version of prometheus-operator (v0.11.0) and tried to have my pods use persistent storage using volumeClaimTemplate by adding the following to the bottom of my Prometheus yaml (but formatted correctly):

``  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: "prometheus-persistent-volume-0"
        resources:
          requests:
            storage: 50Gi``

and following the example for persistent volume here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning

**What did you expect to see?**

I expected that my pods would be created and that they would have nfs mounts as specified in my config.

**What did you see instead? Under which circumstances?**

From running kubectl describe statefulset prometheus-shared:

`  1m	1m	1	kubelet, k8s-telex-scroll.ny2.etsy.com	spec.containers{prometheus}	Warning	Failed		Failed to start container with id d27851b41aa20f12b75a4081a15b1402dac17bee4095ae0fd758d22a06f61d11 with error: rpc error: code = 2 desc = failed to start container "d27851b41aa20f12b75a4081a15b1402dac17bee4095ae0fd758d22a06f61d11": Error response from daemon: {"message":"mkdir /var/lib/kubelet/pods/75fc59dd-7301-11e7-b843-7cd30ad56ea4/volumes/kubernetes.io~nfs/prometheus-storage/prometheus-db: permission denied"}
  1m	1m	1	kubelet, k8s-telex-scroll.ny2.etsy.com					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "prometheus" with rpc error: code = 2 desc = failed to start container "d27851b41aa20f12b75a4081a15b1402dac17bee4095ae0fd758d22a06f61d11": Error response from daemon: {"message":"mkdir /var/lib/kubelet/pods/75fc59dd-7301-11e7-b843-7cd30ad56ea4/volumes/kubernetes.io~nfs/prometheus-storage/prometheus-db: permission denied"}: "Start Container Failed"`

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Custom chef deploy on bare metal CentOS 7

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
I'm unsure this has to do with the Prometheus Operator. Could you try to mount that particular volume through a PVC with an extra Pod?

**Comment by nuala33** [comment]
@brancz you were right. This was actually resolved by just fixing the permissions of the directory on the storage host. Thanks!

**Comment by brancz** [comment]
Always happy to help! Feel free to open issue whenever you have a problem!
