### ISSUE TITLE
Update prometheus-operator.yaml on blog entry

### ISSUE THREAD

**Issue by jpds** [coreos/prometheus-operator#526]
Hello,

Not sure where to file this as it's more for this blog entry:

- https://coreos.com/blog/the-prometheus-operator.html

This blog references this URL:

- https://coreos.com/operators/prometheus/latest/prometheus-operator.yaml

Which deploys v0.0.1 of the operator that is affected by things such as #21.

Can this be updated to point at https://github.com/coreos/prometheus-operator/tree/master/example ?

**Comment by brancz** [comment]
Blog posts quickly get outdated. We have a getting started guide, that we keep up to date: https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

**Comment by brancz** [comment]
I made sure to have a banner added at the top of the article stating that it's outdated and that the docs are a better point of reference.

> Note: The instructions in this post are out of date. To try out the Prometheus Operator, view the latest Prometheus docs for an up-to-date guide to get started.

Thanks for opening this issue! There is always room to improve. Everywhere! :slightly_smiling_face:
