### ISSUE TITLE
kube-prometheus node exporter not successfully scraped using host network

### ISSUE THREAD

**Issue by ryanwalls** [coreos/prometheus-operator#528]
**What did you do?**
Deployed kube-prometheus helm charts.

**What did you expect to see?**
I expected node exporters to be scraped successfully.

**What did you see instead? Under which circumstances?**
It seems that this line: https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/charts/exporter-node/templates/deamonset.yaml#L39 causes the service endpoint to be discovered using the node's IP address instead of the backing pods IP address.  By default the service for the node exporter is set to `ClusterIP`.  So not sure how the node exporter would work without making it a `NodePort` or turning off host networking (and thus allowing the pods to be discovered directly.)

**Environment**
AWS

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.6-rancher1", GitCommit:"973d2fa162b887a6f696f4574b85e949d480a071", GitTreeState:"clean", BuildDate:"2017-06-17T03:54:44Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Created using Rancher.

* Manifests:

See https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/charts/exporter-node/templates/deamonset.yaml#L39

* Prometheus Operator Logs:
n/a

**Comment by ryanwalls** [comment]
By the way, to get it working I just set:
```
hostNetwork: false
hostPID: false
```
in the DaemonSet manifest for the `exporter-node` chart.

**Comment by brancz** [comment]
@ryanwalls those settings are required for the node-exporter to be able to collect metrics from the host network namespace and the host pid namespaces. Even with a `ClusterIP` type `Service`, the underlying Pods can just have the hostIP, it must be something else, like a firewall issue that you're facing.

**Comment by ryanwalls** [comment]
@brancz But how does the port for collecting metrics get exposed on the node if the service is set to `ClusterIP`?  

E.g.  When I setup the node exporter using the host network, the target that prometheus adds is the IP address of my node plus the port of the metrics endpoint.  So 172.19.32.1:9100/metrics.  But if the service is set to `ClusterIP`, how is the endpoint externally routable?

**Comment by brancz** [comment]
I'm not aware of the exact details, but IIRC the Cluster IP is simply routed via iptables to whatever IPs the endpoints object has.

**Comment by ryanwalls** [comment]
@brancz Yep, this is definitely a "me" issue. :)  I figure out the reason it works despite using a Cluster IP for the service is because the DaemonSet sets a `hostPort`.  https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods.  So the DaemonSet is opening a port on the node, not the service.  

So this should work.  Will investigate possible firewall issues.

I'm on AWS and opened all ports within the same security group, so not sure what the issue would be... 

Closing.  Thanks for the help.

**Comment by brancz** [comment]
Always happy to help :slightly_smiling_face: .
