### ISSUE TITLE
kube-prometheus - monitoring of kube-apiserver fails since v0.11.0

### ISSUE THREAD

**Issue by xvzup** [coreos/prometheus-operator#530]
**What did you do?**
Used kube-prometheus  to install v0.11.1 of prometheus operator
**What did you expect to see?**
kube-apiserver should be listed as target in prometheus-k8s
**What did you see instead? Under which circumstances?**
kube-apiserver were not listed
**Environment**
prometheus-operator v0.11.1
* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1+coreos.0", GitCommit:"fdd5383472eb43e60d2222503f03c76445e49899", GitTreeState:"clean", BuildDate:"2017-07-18T19:44:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

bootkube

* Prometheus-k8s Logs:
time="2017-08-01T12:19:41Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list pods in the namespace "default". (get pods)" component="kube_client_runtime" source="kubernetes.go:75"

**Comment by brancz** [comment]
Can you make sure that you have the latest roles and role bindings in place?

* [Roles](https://github.com/coreos/prometheus-operator/blob/e0003a00fe6d5f6aca71c5a10d11a0e715a92362/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-roles.yaml)
* [Role-Bindings](https://github.com/coreos/prometheus-operator/blob/e0003a00fe6d5f6aca71c5a10d11a0e715a92362/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-role-bindings.yaml)

Starting with `v0.11.0` we generate the Prometheus (only if Prometheus `v1.7.0` and above) configuration in a way that only those namespaces are requested that are really needed, if my suspicion is correct, then that may have resulted in this special service needing extra permissions (see the RBAC role for the default namespace). Although I'm curious why it doesn't work with the "old" RBAC roles as they were generally more relaxed as they just allowed access to all namespaces.

The reason we did this is to have very granular control over what the Prometheus instance can do.

**Comment by xvzup** [comment]
In role prometheus-k8s for namespace default the resource pods is missing:

**Default namespace**
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
  name: prometheus-k8s
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch

**Comment by brancz** [comment]
Yes! You're absolutely right! Would you like to create a PR to fix this @xvzup ?

**Comment by brancz** [comment]
Closing as #531 is merged. Thanks a lot again @xvzup !
