### ISSUE TITLE
Prometheus -- connection refused

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#538]
**What did you do?**

I created 2 prometheus pods, each with persistent storage. Though they have both been created successfully, Prometheus is not currently accessible on port 9090 and I am seeing this error repeatedly on one of the pods:

`ts=2017-08-01T17:49:01Z caller=main.go:214 component=volume-watcher msg="Reloading Prometheus temporarily failed." err="Post http://localhost:9090/-/reload: dial tcp [::1]:9090: getsockopt: connection refused" next-retry=19.180701245s`

* Kubernetes version information:

4132:prometheus-shared ngaffey$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Custom chef deploy on bare metal CentOS 7

**Comment by brancz** [comment]
Which version of Prometheus are you trying to run?

**Comment by nuala33** [comment]
@brancz We are running v1.7.0

**Comment by nuala33** [comment]
@brancz one other thing that might be important here. We are also seeing these errors on each of the pods:

  20m		51s		5	kubelet, k8s-pandora-mammal.ny2.etsy.com							Warning		FailedSync		Error syncing pod, skipping: failed to "KillContainer" for "prometheus" with KillContainerError: "rpc error: code = 4 desc = context deadline exceeded"

  51s	51s	1	kubelet, k8s-pandora-mammal.ny2.etsy.com	spec.containers{prometheus}	Normal	Killing	Killing container with id docker://b8300f175fac2b3e73d72523059f4132a08222c26e02721ea8798615e6f37d26:pod "prometheus-shared-1_observability(2c5877ba-786c-11e7-b843-7cd30ad56ea4)" container "prometheus" is unhealthy, it will be killed and re-created.

Additionally, while the prometheus-config-reloader eventually does succeed after some time, 'Targets' often appears blank in the prometheus UI for one or the other, presumably due to the reloader struggling.

**Comment by nuala33** [comment]
Probably also worth mentioning we're running Docker version 1.12.6...

**Comment by nuala33** [comment]
Solved by upping our CPU resource limit from 5m to 1000m :)

**Comment by brancz** [comment]
Yes 5m is pretty low considering Prometheus is a real time time-series database :slightly_smiling_face: . Great that you found the solution though!
