### ISSUE TITLE
About roadmap

### ISSUE THREAD

**Issue by nghialv** [coreos/prometheus-operator#548]
Hi

Is there a scheduled release date for the beta version?

**Comment by brancz** [comment]
Hi @nghialv we're actually about to release v0.12.0 which does the last bit that we wanted to get done before graduating this project to beta. Realistically this project has not had a significant change in its APIs for a long time, so I would consider it beta by most standards already.

**Comment by nghialv** [comment]
Great! 
I really want to use prometheus-operator in our project.
Thank you for your reply and your hark work.
