### ISSUE TITLE
node-exporter is not running on master

### ISSUE THREAD

**Issue by idealhack** [coreos/prometheus-operator#570]
I failed to find any clues about this.

Also I'm not sure whether this is an issue of prometheus-operator or Kubernetes.

**What did you do?**

Deploy kube-prometheus

**What did you expect to see?**

node-exporter running on all nodes, including master

**What did you see instead? Under which circumstances?**

```
kubectl get ds --all-namespaces
NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR                   AGE
kube-system   kube-flannel-ds   4         4         4         4            4           beta.kubernetes.io/arch=amd64   20d
kube-system   kube-proxy        4         4         4         4            4           <none>                          20d
monitoring    node-exporter     3         3         3         3            3           <none>                          22h
```

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

[node-exporter-daemonset.yaml](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml)

**Comment by ArchiFleKs** [comment]
Maybe we just need to support the taint which is by default on Master on 1.7 I think, we should add 

```
tolerations:
            - effect: NoSchedule
              operator: Exists
```

to the DS

**Comment by brancz** [comment]
In our production clusters we have

```
      - key: node-role.kubernetes.io/master                                                                                                                                                                         
        operator: Exists                                                                                                                                                                                            
        effect: NoSchedule
```

but it seems that is too opinionated regarding the node labeling.

@idealhack if you can confirm that @ArchiFleKs's suggestion or another way works in a generic way I'm happy to include that change in the kube-prometheus manifest collection. Always happy about contributions! :slightly_smiling_face:

**Comment by ArchiFleKs** [comment]
Are the taint the correct one? Because you have multiple ways / discussion
regarding master taint even if node-role seems to be the latest official
one.

You can also remove the key and schedule the daemon set on every node with
no schedule just by leaving operator and effect. Weaves does that for
example.

**Comment by brancz** [comment]
I don't have a strong opinion as long as it's either best practice or works generically :slightly_smiling_face:

**Comment by idealhack** [comment]
@ArchiFleKs @brancz Thank you! I didn't found this taint before. I'll test tolerations and maybe submit a patch later.

**Comment by brancz** [comment]
@idealhack any update on this? :slightly_smiling_face:

**Comment by idealhack** [comment]
@brancz Hi, sorry for the late reply. We’ve tested this and here’s the patch: #610.

**Comment by brancz** [comment]
Awesome! Thanks a lot! Closing here as #610 was merged.
