### ISSUE TITLE
Container prometheus-config-reloader terminates with OOM

### ISSUE THREAD

**Issue by kevtaylor** [coreos/prometheus-operator#573]
**What did you do?**

prometheus operator installed via helm chart

**What did you expect to see?**
fully operational containers

**What did you see instead? Under which circumstances?**
prometheus-config-reloader container is in failed backoff state by failing OOM

**Environment**
coreos/AWS

* Kubernetes version information:
1.6.2

	insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
kube-aws

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
```
prometheus-config-reloader:
    Container ID:       docker://9731823d7a22da33aaf7582e6ae73817bd58fb57c8e6934ad0c563976683b84f
    Image:              quay.io/coreos/prometheus-config-reloader:v0.0.1
    Image ID:           docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:2c828783482b299882f21bd67b3dfbfdc7a7499aac3af2a812390079c0de8e35
    Port:
    Args:
      -reload-url=http://localhost:9090/-/reload
      -config-volume-dir=/etc/prometheus/config
      -rule-volume-dir=/etc/prometheus/rules
    State:              Running
      Started:          Thu, 17 Aug 2017 20:50:03 +0000
    Last State:         Terminated
      Reason:           OOMKilled
      Exit Code:        137
      Started:          Mon, 01 Jan 0001 00:00:00 +0000
      Finished:         Thu, 17 Aug 2017 20:50:02 +0000
    Ready:              True
    Restart Count:      1
    Limits:
      cpu:      5m
      memory:   10Mi
    Requests:
      cpu:              5m
      memory:           10Mi
    Environment:        <none>
    Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cs8xt (ro)
```

It does not appear possible to configure this container externally - the values are hardcoded in the operator

**Comment by brancz** [comment]
It's odd as I can't come up with a point where this container might leak memory as I would have expected that to have happened much earlier, but this could also have to do with the sheer size of the prometheus configuration and rule files. I'd suggest for now to bump the limit to `50Mi` memory and `10m` cpu. Would you like to adapt this? I'd be wary of allowing to set these limits via flags or something as this is likely to just confuse as there are already a lot of flags.

**Comment by kevtaylor** [comment]
I would be happy if you increase the constraints, but I would suggest that this will just continue to cause problems in the future, if the values are hardcoded inside the go code. It might be better to template the statefulset definition and then get the operator to load it, instead of dynamically constructing it, but not sure of the feasibility

**Comment by brancz** [comment]
The general idea of the Operator is to not worry about tuning, so for the time being we'll adapt the limits.
