### ISSUE TITLE
grafana-deployment.yaml may be has some error

### ISSUE THREAD

**Issue by wkjun** [coreos/prometheus-operator#574]
**What did you do?**

after deployment, i found  in kubernete's pod ,grafana could not share grafana when a container down ,the next container start ,this result cause my grafana data all be emptied. this is terrible.

**What did you expect to see?**

i want to pod work correctly,so grafana can share grafana.

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Manifests:

```
contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
```

* Reason:

```
storage dir miss match:
in your grafana-deployment.yaml  use ` /var/grafana-storage`,but  grafana docker images use `/var/lib/grafana`,

what i do is :

--- a/contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
+++ b/contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
@@ -29,7 +29,7 @@ spec:
               key: password
         volumeMounts:
         - name: grafana-storage
-          mountPath: /var/grafana-storage
+          mountPath: /var/lib/grafana
         ports:
         - name: web
           containerPort: 3000


which has sloved the problem.

**Comment by brancz** [comment]
The entire intention here is to run grafana in an ephemeral fashion, if this is not how you want to run grafana, then you are not required to use the manifests provided by this project. We merely share the way we think grafana should be operated. And given that grafana is just a dashboarding solution we felt like it's unnecessary to run a full blown database to run a few dashboards that we could provision on start up.

**Comment by wkjun** [comment]
may be ,you have not understand what i mean,emptyDir 

Containers in the pod can all read and write the same files in the emptyDir volume

````
volumes:
      - name: grafana-storage
        emptyDir: {}

  volumeMounts:
         - name: grafana-storage
-          mountPath: /var/grafana-storage
```

use default config,  if one container down , new one start ,visist  dashboard ,the dashboard data will be emptied.

**Comment by eedugon** [comment]
Maybe I'm missing something, but shouldn't `grafana-watcher` sync the
dashboards content when you start a new pod?

I have never seen the issue you mention, always using the default manifests
from kube-prometheus.

**Comment by brancz** [comment]
I'm still not sure I understand your problem @wkjun. Could you try to write up how to reproduce your problem?

**Comment by brancz** [comment]
As it seems to work for all other users, we'll need a write up of how to reproduce this. I'll close this here, but feel free to re-open if you feel it's necessary :slightly_smiling_face: .
