### ISSUE TITLE
Deploy script in contrib for cluster-monitoring fails

### ISSUE THREAD

**Issue by albert0815** [coreos/prometheus-operator#581]
**What did you do?**
Running deploy script for prometheus:
prometheus-operator/contrib/kube-prometheus/hack/cluster-monitoring/deploy

**What did you expect to see?**
Prometheu operator gets installed.

**What did you see instead? Under which circumstances?**
With release from yesterday (0.12.0) this script doesn't proceed over "Waiting for Operator to register third party objects" - it waits forever. With the release before (0.11.1) this works fine for me. In the release notes I can read change: "Use Kubernetes CustomResourceDefinitions instead of ThirdPartyResources." So I assume it might be related to this change as the script is waiting for third party objects which are not used any more (if I get this right).

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"li
nux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1+coreos.0", GitCommit:"fdd5383472eb43e60d2222503f03c76445e49899", GitTreeState:"clean", BuildDate:"2017-07-18T19:44:47Z", GoVersion:"go1.8.3", Compiler:"gc", Pla
tform:"linux/amd64"}

Ommitting the rest of the requested information as prometheus-operator deployment is actually failing. I understand that the contribution and the script is in a directory with the name "hack". Maybe somebody is nevertheless able to help with this issue. It would be at least helpful to understand whether this is actually not working anymore due to some structural change in the operator or whether the script is expected to be working fine and the problem is related to our setup. 

At least the very same deployments works fine with 0.11.1 so that might be a hint it is related to the script / changes in operator.

**Comment by brancz** [comment]
Thanks for reporting! Did you previously have a Prometheus Operator deployed? If so, did you update the RBAC roles?

**Comment by albert0815** [comment]
I removed prometheus operator pod from kubernetes before installing new version. Is this not expected to work? How could I update the roles?

**Comment by brancz** [comment]
Interesting. I'm not seeing this behavior on a new cluster at least.

```
ts=2017-08-25T13:38:45Z caller=operator.go:231 component=prometheusoperator msg="connection established" cluster-version=v1.7.2
ts=2017-08-25T13:38:45Z caller=operator.go:148 component=alertmanageroperator msg="connection established" cluster-version=v1.7.2
ts=2017-08-25T13:38:45Z caller=operator.go:581 component=alertmanageroperator msg="CRD created" crd=Alertmanager
ts=2017-08-25T13:38:45Z caller=operator.go:1068 component=prometheusoperator msg="CRD created" crd=Prometheus
ts=2017-08-25T13:38:45Z caller=operator.go:1068 component=prometheusoperator msg="CRD created" crd=ServiceMonitor
ts=2017-08-25T13:38:48Z caller=operator.go:175 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2017-08-25T13:38:51Z caller=operator.go:251 component=prometheusoperator msg="CRD API endpoints ready"
```

Will try to setup a cluster with the old version and just update the manifests.

The hack script should do the same, but you can change the RBAC roles with

```
kubectl replace -f manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
```

**Comment by brancz** [comment]
Seems to work for me from the previous version as well:

```
ts=2017-08-25T13:58:15Z caller=migrator.go:146 msg="Performing TPR to CRD migration."
ts=2017-08-25T13:58:15Z caller=migrator.go:148 msg="Backing up TPR objects."
ts=2017-08-25T13:58:15Z caller=migrator.go:156 msg="Deleting TPR objects."
ts=2017-08-25T13:58:15Z caller=migrator.go:168 msg="Deleting TPRs."
ts=2017-08-25T13:58:15Z caller=migrator.go:180 msg="Creating CRDs."
ts=2017-08-25T13:58:17Z caller=migrator.go:192 msg="Waiting for CRDs to be ready."
ts=2017-08-25T13:58:26Z caller=migrator.go:200 msg="Restoring backed up objects."
ts=2017-08-25T13:58:26Z caller=operator.go:148 component=alertmanageroperator msg="connection established" cluster-version=v1.7.2
ts=2017-08-25T13:58:26Z caller=operator.go:231 component=prometheusoperator msg="connection established" cluster-version=v1.7.2
ts=2017-08-25T13:58:26Z caller=operator.go:581 component=alertmanageroperator msg="CRD created" crd=Alertmanager
ts=2017-08-25T13:58:26Z caller=operator.go:1068 component=prometheusoperator msg="CRD created" crd=Prometheus
ts=2017-08-25T13:58:26Z caller=operator.go:1068 component=prometheusoperator msg="CRD created" crd=ServiceMonitor
ts=2017-08-25T13:58:29Z caller=operator.go:175 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2017-08-25T13:58:32Z caller=operator.go:251 component=prometheusoperator msg="CRD API endpoints ready"
```

**Comment by albert0815** [comment]
Not sure whether I completly get it. I tried following:

1. With version v0.11.1 run script hack/cluster-monitoring/deploy (works fine)
2. remove prometheus-operator pod
3. Run latest release with above script
```
namespace "monitoring" created
clusterrolebinding "prometheus-operator" created
clusterrole "prometheus-operator" created
serviceaccount "prometheus-operator" created
service "prometheus-operator" created
deployment "prometheus-operator" created

Waiting for Operator to register third party objects..................................................................................................
```
This now continues forever. In the meantime I tried above given command (for updating the RBAC roles) after step 2 but nothing changes.

**Comment by VinceMD** [comment]
I have the same issue with 0.12.0 on a cluster where I haven't installed prometheus before.
The logs of the pod:

```ts=2017-08-28T01:53:35Z caller=operator.go:231 component=prometheusoperator msg="connection established" cluster-version=v1.6.3+coreos.0
ts=2017-08-28T01:53:35Z caller=operator.go:148 component=alertmanageroperator msg="connection established" cluster-version=v1.6.3+coreos.0
ts=2017-08-28T01:53:35Z caller=main.go:148 msg="Unhandled error received. Exiting..." err="creating CRDs failed: creating CRD: Prometheus: the server could not find the requested resource"```

**Comment by VinceMD** [comment]
do we need to install Prometheus-operator outside? Reading the contrib/kube-prometheus,  I'm under the impression that running the deploy command will do everything for me

**Comment by brancz** [comment]
@VinceMD yes as noted in the release notes, `v0.12.0` of the Prometheus Operator requires a 1.7 cluster. So you will first have to upgrade your kubernetes cluster and then the Prometheus Operator from `v0.11.1` to `v0.12.0`.

**Comment by brancz** [comment]
I believe I understand the problem now though. Yes the `hack/` scripts are not intended to be used for upgrading from one version to another, it is a mere coincidence, if it ever worked. That said I believe the changes to the script should be minimal so I'm trying it out right now and will open a PR if it turns out working.

**Comment by bamb00** [comment]
@brancz 

I run into this problem quite a few times where the CRDs does not get register on new k8s cluster.

Any workaround, maybe registering manually.

Prometheus-Operator: 0.14.0, K8s: 1.7.4

**Comment by brancz** [comment]
@bamb00 do you have steps to reproduce this? I run the prometheus operator hundreds of times a month and have never encountered that. Maybe it's an RBAC issue?

**Comment by bamb00** [comment]
The steps are pretty simple to reproduce.  I would run the script on a fresh CentOS 7.3 environment VM the CRD does not get register.  Then reran the script moment later the CRDs gets register.

**Comment by brancz** [comment]
Could you elaborate a bit more @bamb00 ? Which environment, how can I reproduce this?

**Comment by bamb00** [comment]
Run the 'deploy' script in a fresh environment below.

OS: CentOS 7.3
Kernel: Linux 3.10.0-514.el7.x86_64
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bamb00** [comment]
I have a question regarding the behavior when CRDs get register.

The prometheus-operator container has to be 'running' before the CRDs actually get register?

**Comment by brancz** [comment]
Yes. The Prometheus pod starts running and will register the CRDs. Only then can you start creating Prometheus, alertmanager and servicemonitor objects.
