### ISSUE TITLE
prometheus-operator Pod Error

### ISSUE THREAD

**Issue by linuxvip** [coreos/prometheus-operator#59]
$ kubectl apply -f manifests/prometheus-operator.yaml
$ kubectl get pod
prometheus-operator-1805596728-4ehlz   0/1       CrashLoopBackOff   20         1h
$ kubectl logs prometheus-operator-1805596728-4ehlz 
communicating with server failed: Get https://10.254.0.1:443/version: x509: cannot validate certificate for 10.254.0.1 because it doesn't contain any IP SANs

--------------------------------------------------------------------------------------------------
Why certificate cannot be verified?
How to create certificate?
my command:
$ openssl genrsa -out ca.key 2048
$ openssl req -x509 -new -nodes -key ca.key -subj "/CN=10.254.0.1" -days 5000 -out ca.crt
$ openssl genrsa -out server.key 2048
$ openssl req -new -key server.key -subj "/CN=10.254.0.1" -out server.csr
$ openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 5000

---------------------------------------------------------------------------------------------------
the prometheus-operator  container is to connect 10.254.0.1? 
How did it get?

Thanks!

**Comment by brancz** [comment]
This is a general issue with your setup. The Prometheus operator relies on service accounts to be setup correctly and certificates to be issued according to the configuration of those. I would recommend asking in kubernetes slack if you have problems with setting up those correctly.
