### ISSUE TITLE
Error when creating Cluster Role [Windows] [Kubernetes]

### ISSUE THREAD

**Issue by mfaizanse** [coreos/prometheus-operator#596]
**What did you do?**
Ran "kubectl apply -f bundle.yaml"

**What did you expect to see?**
It should create the clusterrole.

**What did you see instead? Under which circumstances?**
`Error from server (Forbidden): error when creating "promethius-clusterrole.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [{[*] [extensions] [thirdpartyresources] [] []} {[*] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[*] [monitoring.coreos.com] [alertmanagers] [] []} {[*] [monitoring.coreos.com] [prometheuses] [] []} {[*] [monitoring.coreos.com] [servicemonitors] [] []} {[*] [apps] [statefulsets] [] []} {[*] [] [configmaps] [] []} {[*] [] [secrets] [] []} {[list] [] [pods] [] []} {[delete] [] [pods] [] []} {[get] [] [services] [] []} {[create] [] [services] [] []} {[update] [] [services] [] []} {[get] [] [endpoints] [] []} {[create] [] [endpoints] [] []} {[update] [] [endpoints] [] []} {[list] [] [nodes] [] []} {[watch] [] [nodes] [] []} {[list] [] [namespaces] [] []}] user=&{kubeconfig [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]`

**Environment**
Azure Container Service with:
1x Master Node (Linux)
2x Worker Nodes (**Windows**)

* Kubernetes version information:

	insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Created kubernetes cluster using Azure Container Service

* Note:
I have tried binding cluster-admin role to kubernetes user but still the same issue.
`kubectl create clusterrolebinding beconnectcontainersmgmt-admin-binding --clusterrole=cluster-admin --user=beconnectcontainersmgmt-admin`
Related Link: https://coreos.com/operators/prometheus/docs/latest/troubleshooting.html

==> I am using windows containers.
==> My main goal is to get Horizontal Pod Autoscaling working with windows containers.

**Comment by brancz** [comment]
I believe your issue is unrelated to the Prometheus Operator, and rather RBAC as a whole. You are trying to give the Prometheus Operator `ServiceAccount` more RBAC roles than you currently have. I'm not sure about Azure Container Service, but I know that on GKE this is the exact same thing exists, where by default users don't have full cluster admin RBAC roles themselves, therefore they cannot grant more roles than they have.

This is something you need to ask Azure support about, but we're happy to include it in the troubleshooting guide, once you figure it out! :slightly_smiling_face:

**Comment by mfaizanse** [comment]
Thank You @bonifaido, I will update the thread once I get the resolution. Apart, can you share some document or sample for deployment/integration of prometheus operator with windows containers?

**Comment by brancz** [comment]
This is the very first time to my knowledge, that anyone has tried the Prometheus Operator with windows containers, so while I'm happy to hear about your experience, I don't have any docs to help you.

**Comment by xussof** [comment]
Ha, a Windows SysAdmin aporting to the community, nice one.
I have the same problem too but with CoreOs on GoogleCloud while deploying this bundle

**Comment by brancz** [comment]
@xussof can you elaborate and share the errors you're getting, logs, manifests, versions etc.? (you can also feel free to open a new issue unless it's exactly the same as above)

**Comment by xussof** [comment]
Yep, sorry I found the solution on this link. I think we can close this issue:
https://stackoverflow.com/a/47332612/2225987

**Comment by mfaizanse** [comment]
The issue was with Azure Container Service, that RBAC was not enabled in it. Now the issue is resolved in Azure Kubernetes Service.
