### ISSUE TITLE
User unaware of 1.6 incompatibility, make clearer in docs?

### ISSUE THREAD

**Issue by pgburt** [coreos/prometheus-operator#598]
This is from a user on the #coreos IRC https://botbot.me/freenode/coreos/2017-09-01/?msg=90543886&page=1

**What did you do?**

User tried to install Prometheus-Operator on Kubernetes 1.6.

**What did you expect to see?**

User did not realize CRDs were a new feature, so was expecting the install to work.

**What did you see instead? Under which circumstances?**

User got an error regarding CRDs.

**Environment**

Kubernetes 1.6 on GKE

**Suggestion**

We should review the install docs, and insure it's clear that CRDs are new to 1.7, and that's the minimum version required.

**Comment by brancz** [comment]
Absolutely! I noted it in the [release notes](https://github.com/coreos/prometheus-operator/releases/tag/v0.12.0), but if people run into it, then clearly it needs more visibility.

@joshix what is your take on this? Maybe we can insert a banner on all `v0.12.0`+ docs that only `v1.7.x`+ is supported?

**Comment by brancz** [comment]
cc @radhikapc @athai @zbwright

**Comment by athai** [comment]
@joshix @pgburt @brancz 

If we add the following to the top of the markdown files:
```
<br>    
<div class="alert alert-info" role="alert">
    <i class="fa fa-exclamation-triangle"></i><b> Note:</b> Starting with v0.12.0, Prometheus Operator requires use of Kubernetes v1.7.x and up.    
</div>
```

It should add a note before the heading that will be displayed like so on coreos.com:
<img width="767" alt="screen shot 2017-09-06 at 5 02 56 pm" src="https://user-images.githubusercontent.com/6801364/30139912-b315bfb2-9325-11e7-96ff-f0fd1503b1d5.png">

And within the GH docs, it'll just appear as:

**Note:** Starting with v0.12.0, Prometheus Operator requires use of Kubernetes v1.7.x and up.

---

Alternatively, we can do what etcd does: 
* [As seen on coreos.com](https://coreos.com/etcd/docs/latest/v2/api.html)
* [As seen in straight up GH markdown](https://github.com/coreos/etcd/blob/master/Documentation/v2/api.md)

**Comment by brancz** [comment]
Good idea @athai. I added the headers in #605 .
