### ISSUE TITLE
change default scrape_interval 

### ISSUE THREAD

**Issue by nrobert13** [coreos/prometheus-operator#606]
**What did you do?**
installed prometheus with kube-prometheus

**What did you expect to see?**
an option in the Prometheus TPR to change the scrape_interval in the global section of the config

**What did you see instead? Under which circumstances?**
didn't find

**Environment**
* Kubernetes version information:

# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kubespray

* Manifests:

kube-prometheus as of Tue Sep 5 10:00:29 2017 +0200
* Prometheus Operator Logs:

none

**Comment by brancz** [comment]
`30s` is a sane option, it's rather an edge case when this is not an appropriate value, so setting other intervals on a servicemonitor basis makes sense. What does your case look like? I'm not entirely opposed, but want to avoid duplicating the entire prometheus config.

**Comment by nrobert13** [comment]
I find 30s to short. in a 20 node cluster monitoring only the core components, what kube-prometheus brings, the database is like 3GB. I'd go for a longer default like 2m, and rather define the default to be 2m than defining in each and every servicemonitor the interval. if I need to change the interval, I need to change all the ServiceMonitors. Beeing able to define the global default, would make life easier...., and define interval only for servicemonitors where differs from defult.

**Comment by nrobert13** [comment]
thank you for the offer :). I'd be happy to implement it, but unfortunately I have no GO knowledge, so you would potentially need to guide me not only through prometheus-operator challenges but also GO language challenges ...

**Comment by brancz** [comment]
No problem, always happy to help a new-comer :slightly_smiling_face: . If you are on kubernetes slack we could have a quicker feedback cycle, let me know what you think and or ping me there.

**Comment by mikebryant** [comment]
@brancz I think this issue can be closed? - the feature was merged in #628

**Comment by brancz** [comment]
You're absolutely right @mikebryant ! Thanks for the ping!
