### ISSUE TITLE
Dangling link to ServiceMonitor from kube-prometheus README

### ISSUE THREAD

**Issue by aknuds1** [coreos/prometheus-operator#613]
The [kube-prometheus README](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) has a [link](https://github.com/coreos/prometheus-operator/blob/master/Documentation/service-monitor.md) to ServiceMonitor, which results in a 404. I would rectify this in a PR if I knew of the URL to the ServiceMonitor documentation, in fact I am looking for this myself :)

**Comment by brancz** [comment]
Always feel free to fix those kinds of things, but thanks for checking in with us! :slightly_smiling_face: The kube-prometheus readme had previously been in a separate repository, so I can imagine that this might not be the only problem.

**Comment by aknuds1** [comment]
@brancz What's the correct URL to ServiceMonitor documentation? Does it exist?

**Comment by brancz** [comment]
I believe we distilled it into [this](https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor) section of the `design.md` document, so we should link there.
