### ISSUE TITLE
K8SControllerManagerDown and K8SSchedulerDown

### ISSUE THREAD

**Issue by wkjun** [coreos/prometheus-operator#618]
**What did you do?**

K8SControllerManagerDown and K8SSchedulerDown

**What did you expect to see?**
K8SControllerManagerDown and K8SSchedulerDown  dones't firing

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Kubeadm

* Manifests:

```

prometheus-operator：

prometheus-operator/contrib/kube-prometheus/manifests/k8s/self-hosted/kube-controller-manager.yaml

kubernetes：

/etc/kubernetes/manifests/kube-controller-manager.yaml

```

* Prometheus Operator Logs:

```
[tutu@tutuvss-6 ~]$ kubectl get pods -n kube-system
NAME                                    READY     STATUS    RESTARTS   AGE
etcd-tutuvss-6                          1/1       Running   6          22d
heapster-84017538-srs85                 1/1       Running   0          16d
kube-apiserver-tutuvss-6                1/1       Running   6          22d
kube-controller-manager-tutuvss-6       1/1       Running   0          42m
kube-dns-2425271678-cfs2t               3/3       Running   0          3h
kube-flannel-ds-0kd4w                   2/2       Running   8          48d
kube-flannel-ds-0s17s                   2/2       Running   405        16d
kube-flannel-ds-fl1n7                   2/2       Running   3          3d
kube-flannel-ds-fv1bm                   2/2       Running   4          15d
kube-flannel-ds-vjlkz                   2/2       Running   24         48d
kube-proxy-8b25w                        1/1       Running   1          22d
kube-proxy-mc58z                        1/1       Running   1          3d
kube-proxy-n0prm                        1/1       Running   6          22d
kube-proxy-w903f                        1/1       Running   145        16d
kube-proxy-wmz57                        1/1       Running   1          15d
kube-scheduler-tutuvss-6                1/1       Running   6          22d
kubernetes-dashboard-3313488171-nf6hj   1/1       Running   11         28d
monitoring-grafana-1850655027-r0lw4     1/1       Running   0          7d
monitoring-influxdb-1870447071-bxcn2    1/1       Running   0          16d

kubectl get pods -n kube-system kube-controller-manager-tutuvss-6 -o yaml

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: c4297cfafbd1aad1a9afc00e3b3d3349
    kubernetes.io/config.mirror: c4297cfafbd1aad1a9afc00e3b3d3349
    kubernetes.io/config.seen: 2017-09-14T20:16:46.933902678+08:00
    kubernetes.io/config.source: file
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: 2017-09-14T12:16:52Z
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager-tutuvss-6
  namespace: kube-system
  resourceVersion: "7552959"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-controller-manager-tutuvss-6
  uid: 974893b2-9946-11e7-8c68-d05099c192bc
spec:
  containers:
  - command:
    - kube-controller-manager
    - --leader-elect=true
    - --use-service-account-credentials=true
    - --controllers=*,bootstrapsigner,tokencleaner
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --address=127.0.0.1
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --allocate-node-cidrs=true
    - --cluster-cidr=10.244.0.0/16
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.7.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/pki
      name: pki
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: tutuvss-6
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /etc/pki
    name: pki
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-09-14T12:16:51Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-09-14T12:16:54Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-09-14T12:16:51Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://81f75997fa7d420507f07381d6dc9363750ae22b8b85a308902536d197295e47
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.7.4
    imageID: docker://sha256:d2adddc4b1cb2cb8021f8fd84b03b191833b5cc8a1c6fb9198c714d71f1c2072
    lastState: {}
    name: kube-controller-manager
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2017-09-14T12:16:53Z
  hostIP: 10.10.10.36
  phase: Running
  podIP: 10.10.10.36
  qosClass: Burstable
  startTime: 2017-09-14T12:16:51Z

 kubectl get svc -n kube-system
NAME                                           CLUSTER-IP       EXTERNAL-IP   PORT(S)               AGE
heapster                                       10.96.104.219    <none>        80/TCP                43d
kube-controller-manager-prometheus-discovery   None             <none>        10252/TCP             4h
kube-dns                                       10.96.0.10       <none>        53/UDP,53/TCP         49d
kube-dns-prometheus-discovery                  None             <none>        10055/TCP,10054/TCP   4h
kube-scheduler-prometheus-discovery            None             <none>        10251/TCP             4h
kubelet                                        None             <none>        10250/TCP             29d
kubernetes-dashboard                           10.98.194.194    <none>        80/TCP                46d
monitoring-grafana                             10.105.253.92    10.10.10.64   80/TCP                43d
monitoring-influxdb                            10.103.219.166   <none>        8086/TCP              49d


```
i select controller-manager-prometheus as a sample .after i read some issues ,i try run `kubectl apply -f contrib/kube-prometheus/manifests/k8s/self-hosted/kube-controller-manager.yaml`, it create  `kube-controller-manager-prometheus-discovery` service,but no pod in the service,because prometheus-operator use label k8s: kube-controller-manager when kubernetes use component: kube-controller-manager,my problem is what i can do with this?

**Comment by paalkr** [comment]
Have you checked your security group settings?

Prometheus needs access on port 10252 and 10251 on the controllers to scrape metrics. Usually Prometheus ends up running in a regular worker pool, while controllers run in another pool. Each pool usually have their own dedicated security group. So basically you need to open the ports mentioned like
WorkerSecurityGroup -> ControllersSecurityGroup on port 10252 and 10251

**Comment by wkjun** [comment]
i didn't use aws,just installed kubernete on normal server ,so nodes are not in security group enviroment

**Comment by brancz** [comment]
Yes we're aware of the inconsistencies between cluster setup tools, we just most commonly use bootkube which is why those manifests are as they are. I'm happy to accept PRs for different manifests as we already have `k8s/minikube/` and k8s/self-hosted/`, so what do you think of adding working manifests with the correct selectors and ports to `k8s/kubeadm`?

**Comment by wkjun** [comment]
Sorry for late replay:

one problem is kube-controller-manager's and kube-scheduler's label do not match witch default label  in `prometheus-operator/contrib/kube-prometheus/manifests/k8s`'s Service selector which Start witch ` k8s-app`  when My kube-controller-manager start witch `component`

Refer to  https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus i fond one way to solve the problem:
1. modify `self-hosted Service selecto` and   `kube-scheduler  kube-controller-manager bind address `
 kuberletes (/etc/kubernetes/manifests/kube-controller-manager.yaml)
```
  labels:
    component: kube-controller-manager
```
 kuberletes (/etc/kubernetes/manifests/kube-scheduler.yaml)
```
    labels:
      component: kube-scheduler
```
  modify  self-hosted/kube-controller-manager.yaml
```
   spec:
     selector:
 #    k8s-app: kube-controller-manager
       component: kube-controller-manager
```
  modify  self-hosted/kube-controller-manager.yaml
```
   spec:
     selector:
 #    k8s-app: kube-controller-manager
       component: kube-controller-manager
```
 apply modify
 ```
kubectl -n kube-system apply -f self-hosted
 ```
  modify kube-controller-manager and kube-scheduler  bind address
```
/etc/kubernetes/manifests/kube-controller-manager.yaml
#    - --address=0.0.0.0
    - --address=127.0.0.1

/etc/kubernetes/manifests/kube-scheduler.yaml
#    - --address=0.0.0.0
    - --address=127.0.0.1
```
restart kubelet
```
sudo systemctl restart kubelet
```
This is OK

**Comment by brancz** [comment]
Would you like to create a `k8s/kubeadm/` directory next to the `self-hosted` directory, to add the manifests in kubeadm style? Happy to review a PR for this :slightly_smiling_face: 

I'm curious though why you think the address binding and kubelet restart was necessary? I don't see those things to be connected.

**Comment by dimm0** [comment]
Trying to make this work too...
By default kube-controller and kube-scheduler are only allowing connections from localhost, by having:

    - --address=127.0.0.1

Any ideas how to avoid changing the default behavior?

**Comment by wkjun** [comment]
@brancz  i think, it is a  rough way to make modify work,i is was not necessary ,may use `kubectl apply -f` to do this.
@brancz  @dimm0  ,when i discuss  with my colleague ,he has the same question ，
Any ideas how to avoid changing the default behavior `- --address=127.0.0.1`?
i try to use NodePort in Service ,but not success

**Comment by dimm0** [comment]
NodePort still means the request can come from anywhere in the cluster... I was thinking about scheduling some container to run on the controller node and bound to the physical host's network, in that case it can call the localhost port.

**Comment by brancz** [comment]
I see, yes the `--address=0.0.0.0` actually makes sense, and you restarted the kubelet to apply the changes. This actually sounds like the correct approach. The default value is something, that kubeadm would need to take care of, I would ask the maintainers of kubeadm directly.

**Comment by dimm0** [comment]
Still not working for 1.8.0... Default behavior is allowing connections from localhost.

**Comment by brancz** [comment]
You can feel free to open an issue on kubernetes/kubernetes to change this, but I'm uncertain whether that will happen. Alternatively I'm open to having docs on how to get this working with kubeadm. Does that sound good?

**Comment by loganasherjones** [comment]
Another way to solve this issue while using `kubeadm` is to use the [https://kubernetes.io/docs/reference/generated/kubeadm/#config-file](kubeadm config file). It will let you specify these things during `init` or `join`.

**Comment by brancz** [comment]
@loganasherjones thanks for mentioning it! It would be great if someone could get around to documenting these :slightly_smiling_face: .

**Comment by loganasherjones** [comment]
I don't mind doing that. Where do you want the documentation?

**Comment by brancz** [comment]
As #770 is merged I'll close this here.
