### ISSUE TITLE
Instructions in README.md to install the operator in a different space dont work

### ISSUE THREAD

**Issue by tricky42** [coreos/prometheus-operator#638]
I read the README.md to get ready to install the prometheus-operator in a fresh minikube instances and wanted to make sure, all elements of the installation end up in a new namespace called *monitoring*. 
So I created this namespace and also adjusted the namespace specified in the bundle.yaml to *monitoring* as described in the README.md file. 

But when I checked what got installed all see all elements ended up in the *default* namespace.

**Environment**
```
>kubectl version                                                                                                                                            
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-07T18:20:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}* 

>minikube version 
minikube version: v0.22.0
```
Cluster Type: minikube

**Comment by brancz** [comment]
Can you explain where in the `README.md` it sounds like you need to install it into the `monitoring` namespace? The `bundle.yaml` is indeed designed to be deployed in the `default` namespace - primarily for a quickstart.

**Comment by brancz** [comment]
For a full monitoring setup checkout `contrib/kube-prometheus/`. The `bundle.yaml` is just meant for a quickstart to apply and try out things. Closing this here, but feel free to re-open or open a new issue if there is anything else :slightly_smiling_face:!
