### ISSUE TITLE
Cannot monitor other namespaces out-of-the-box

### ISSUE THREAD

**Issue by emas80** [coreos/prometheus-operator#639]
**What did you do?**
Run the "contrib/kube-prometheus/hack/deploy" script

**What did you expect to see?**
Prometheus up and running with the possibility to monitor any desired application by providing the necessary ServiceMonitor

**What did you see instead? Under which circumstances?**
If the service is deployed in a namespace other than the default "monitoring" one (or the one where prometheus is running), then the service monitor will never be able to reach the application.
The only possibility for you to understand this is looking at the logs of the prometheus-k8-0 pod, and the service monitor is loaded properly and prometheus configuration is correctly updated with the new rule.

**Environment**

* Manifests:
Prometheus Operator version 0.13.0

* Prometheus Operator Logs:

```
ime="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:179: Failed to list *v1.Endpoints: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list endpoints in the namespace "utility". (get endpoints)" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list pods at the cluster scope. (get pods)" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list pods in the namespace "utility". (get pods)" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list services in the namespace "kube-ingress". (get services)" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list services at the cluster scope. (get services)" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-09-24T08:52:09Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: User "system:serviceaccount:monitoring:prometheus-k8s" cannot list services in the namespace "utility". (get services)" component="kube_client_runtime" source="kubernetes.go:75" 

```

I see two options here
1 - Modifying the prometheus-k8s-roles.yaml by adding 

```
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
```
in the prometheus-k8s ClusterRole

2 - Keeping the default permissions, and adding a paragraph to the documentation explaining that we need to modify the default ClusterRole permission if we want to monitor services in different namespaces

**Comment by brancz** [comment]
The kube-prometheus manifest collection is exactly that, a collection of manifests. They are very opinionated and are meant to be taken and adapted to your need. Along with that you're executing a script in a `hack/` directory, which goes even further, it says this _is_ a hack, it is just making our life a bit easier.

That said, the kube-prometheus manifests are designed to follow the principle of least privilege. The state the manifests are in they have exactly the permissions they need, and none more. Giving the stack a `ClusterRole` would compromise this principle. If you wish to monitor services in an additional namespace, I would recommend to create the RBAC [`Role`](https://github.com/coreos/prometheus-operator/blob/bcb91cabbe1b8427d6aa85c9bd649ba0c2af75c9/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-roles.yaml#L32-L43) in that namespace only.

**Comment by emas80** [comment]
Ok, fair enough.
Thank you @brancz !
