### ISSUE TITLE
HighNumberOfFailedHTTPRequests Alarms Firing Unnecessarily

### ISSUE THREAD

**Issue by Capitrium** [coreos/prometheus-operator#642]
I've noticed the `HighNumberOfFailedHTTPRequests` etcd alarms firing whenever a new node is added to my k8s cluster. Digging into the logs, I noticed the following error on the kube-controller-manager while a new node was spinning up:

```
daemoncontroller.go:254] kube-system/kube-flannel-ds failed with : error storing status for daemon set &v1beta1.DaemonSet{...}: Operation cannot be fulfilled on daemonsets.extensions "kube-flannel-ds": the object has been modified; please apply your changes to the latest version and try again
```

Seems like this is a pretty common failure that doesn't necessarily warrant the level of alerting we currently have on it due to the following:
  * the daemon controller is designed to [retry these status updates automatically](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L997)
  * PUTs to etcd appear to be limited to the [`Update/UpdateStatus` functions on clients](https://github.com/kubernetes/kubernetes/blob/cce1c9b41e7fea9a04de2e28c4e2a408a5fe1302/pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/daemonset.go#L127)
  * editing a DaemonSet (and likely other resources) via `kubectl` uses a PATCH instead of a PUT

Might be worth excluding PUT requests from the existing `HighNumberOfFailedHTTPRequests` alarms, and possibly adding some `HighNumberOfFailedPUTRequests` alarms with higher thresholds.

**Comment by brancz** [comment]
The DaemonSetController doesn't talk to etcd, so this retry handling has nothing to do with this. The errors the DaemonSetController gets are errors returned by the apiserver. Only the apiserver talks to etcd. Could you share the false alert that you have received so we can further examine what happened here?

**Comment by Capitrium** [comment]
<img width="2993" alt="alerts" src="https://user-images.githubusercontent.com/5111534/30865344-b0adc54e-a2ac-11e7-96b6-1670d24f104d.png">

<img width="3002" alt="metric" src="https://user-images.githubusercontent.com/5111534/30865356-b7704604-a2ac-11e7-865a-b0d83439b2e4.png">

The false alert is pretty easy to reproduce. Spin up a small cluster (<5 nodes), deploy the Prometheus Operator, then spin up another node. The `HighNumberOfHTTPFailures` alert gets triggered around the same time the new node becomes Ready.

We're using K8s 1.7.6 on AWS.

**Comment by brancz** [comment]
What tooling did you use to setup your cluster, and which networking solution are you using? As far as I can tell the Kubelets don't talk to etcd directly, but networking solutions, like flannel might.

**Comment by Capitrium** [comment]
Our clusters are setup using a custom terraform config, and we're using flannel as our container networking interface. Flannel is running as a daemonset configured with the `kube-subnet-mgr` flag, so writes to etcd should be delegated to the apiserver AFAIK, but if the kubelets don't talk to etcd it would make a lot of sense for flannel to be the source of these PUT errors since they seem to only happen once per node (re)boot.

**Comment by brancz** [comment]
I would expect flannel and or etcd to log on an actual erroring API call. Could you check those logs? If this happens when a new node is joining the cluster, then this should be a good clue as to when these events should be happening.

**Comment by Capitrium** [comment]
Seems like these PUT errors are actually caused by the `etcd-lock` [container linux update strategy](https://coreos.com/os/docs/1465.8.0/update-strategies.html). Closing this issue as the alarm doesn't fire when using the [container linux update operator](https://github.com/coreos/container-linux-update-operator), which is a better solution for updating nodes in kubernetes clusters anyway.

**Comment by lucab** [comment]
@Capitrium so it looks like locksmithd is correctly talking to etcd but there a number of failing PUT attempts. If you have more details in locksmith logs, can you please forward them to a coreos/bugs ticket? I'm not 100% sure about what's going on, it sounds fishy but it may even be correct behavior.
