### ISSUE TITLE
K8s nodes keep being scraped after shutdown

### ISSUE THREAD

**Issue by mbugeia** [coreos/prometheus-operator#643]
**What did you do?**
We make a change on some workload of our cluster that cause the cluster autoscaler to shutdown some nodes. 

**What did you expect to see?**
Nothing particular, dead nodes shouldn't be scraped anymore since they aren't in the cluster.

**What did you see instead? Under which circumstances?**

3 alerts firing K8SKubeletDown (warning and critical) and TargetDown (on job kubelet).

**Environment**

* Kubernetes version information:

	kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kops

* Manifests:

We use https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

* Prometheus Operator Logs:

Nothing particular.

My guess is that my old nodes are still present in the metrics that prometheus (or the operator ?) use to build the list of node to scrap. But I can't find where the list is constructed.

**Comment by brancz** [comment]
The alert probably just needs a better `FOR` clause. The nodes may continue being discovered for up to 3 minutes.

**Comment by mbugeia** [comment]
I don't think it's only the alert, it seems my nodes continue being discovered forever (it's been here for 3 days now). Do you know which metric is doing  the node discovery part ?

**Comment by mbugeia** [comment]
Maybe the issue is not related to the prometheus operator `kubectl describe endpoints kubelet -n kube-system` still contain all my old nodes.

**Comment by mbugeia** [comment]
I found the solution (not related to prometheus-operator):
`kubectl get endpoints kubelet -o yaml > kubelet.yaml`
Manually remove the dead nodes from kubelet.yaml
`kubectl replace -f kubelet.yaml`
