### ISSUE TITLE
Support certificates stored as Kubernetes secrets

### ISSUE THREAD

**Issue by JosephSalisbury** [coreos/prometheus-operator#648]
Hi!

At Giant Swarm, we're developing a platform for managing and running Kubernetes clusters. We run our control plane on Kubernetes, and use that to spin up Kubernetes clusters.

I'd like to use Prometheus to scrape these 'guest' Kubernetes clusters (api server, kubelet, node exporters, to begin with). As a customer requirement, we need to use https for the scrape itself.

Our operators provide a Kubernetes Service in the host cluster that points to the masters / workers of the guest cluster.

The certificates for these guest clusters are stored as Kubernetes Secrets in the 'host' cluster. Configuring Prometheus to use these certificates is currently not possible OOB.

Adding support to Prometheus to read certificates from kubernetes secrets doesn't make a lot of sense (as it's very focused on Kubernetes / our use case, see https://github.com/prometheus/prometheus/issues/3218) - does adding support to `prometheus-operator` to use certificates stored as secrets for the scrape make sense to you?

If it doesn't, we're going to write our own tool to manage the configuration / certificates, but it made sense to me to reach out, as there could be some overlapping work here.

Writing this to start a discussion, happy to start on a PR if it makes sense.

**Comment by brancz** [comment]
I'm not sure how much sense automatically discovering secrets would work or make sense, but we do allow a list of secrets to be mounted into Prometheus pods. This however will always trigger a re-deploy of the Prometheus instance on a new secret (which I imagine should not be very often, but still possible).

**Comment by JosephSalisbury** [comment]
Yeah, that wouldn't work for us, we'd be restarting prometheus very frequently.

**Comment by brancz** [comment]
Sounds like your best bet would be to have a sidecar that retrieves the certs from the Kubernetes API and writes them and reloads Prometheus.

**Comment by JosephSalisbury** [comment]
Cool, we'll go with our own approach. Thanks for your time!
