### ISSUE TITLE
Grafana-Watcher import of dashboards exported via UI leads to nil pointer dereference

### ISSUE THREAD

**Issue by vuza** [coreos/prometheus-operator#649]
**What did you do?**
I exported Grafana dashboards via the web UI, mounted them via a k8s configmap to the grafana-watcher and let grafana-watcher import the dashbords.

**What did you expect to see?**
I expected the dashbaords to be imported to Grafana

**What did you see instead? Under which circumstances?**
I realized this leads to an server side error on Grafana and the grafana-watcher received 500 from the Grafana API

**Environment**
Grafana 4.4.3
grafana-watcher 0.0.8

**Solution**
The used Grafana API to import dashboards (`/api/dashboards/import`), which [isn't documented](https://github.com/grafana/grafana/issues/7592#issuecomment-280407404), expects the dashboard JSON to be wrapped in `{dashboard: {}}`. This wrapper is missing, when exporting dashboards via the web UI. The grafana-watcher should check for this syntax and optionally add this wrapper automatically.

Example:

Via web ui exported dashboard JSON, which leads to exception if imported via `/api/dashboards/import` (API used by grafana-watcher) to Grafana:
```
{"id":null,"rows":[{"collapse":false,"height":"250px","panels":[],"repeat":null,"repeatIteration":null,"repeatRowId":null,"showTitle":false,"title":"Dashboard Row","titleSize":"h6"}],"schemaVersion":6,"title":"New dashboard Copy","version":0}
```

Manually modified web ui exported JSON, which gets imported correctly:
```
{"dashboard": {"id":null,"rows":[{"collapse":false,"height":"250px","panels":[],"repeat":null,"repeatIteration":null,"repeatRowId":null,"showTitle":false,"title":"Dashboard Row","titleSize":"h6"}],"schemaVersion":6,"title":"New dashboard Copy","version":0}}
```

**Comment by brancz** [comment]
When exporting a dashboard from the UI, you need to drop it into the `assets/grafana/` directory and then run the `make generate` make target, it will take care of wrapping the exported blob correctly as you described and generate a `ConfigMap` manifest accordingly.

Let us know or feel free to contribute to this document:

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/developing-alerts-and-dashboards.md

If the content was not clear enough :slightly_smiling_face: . Or if you didn't see it, let us know how you think we could highlight it more so people find it :slightly_smiling_face: .

**Comment by vuza** [comment]
Thank you @brancz for the fast reply! The problem was, that we are not using the whole prometheus-operator ecosystem, but only the grafana-watcher docker-image, which most probably is not what it is designed for.
Would you accept an PR adding a README to https://github.com/coreos/prometheus-operator/tree/master/contrib/grafana-watcher with some basic information about just this part of the prometheus-operator? This would have helped me a lot.

**Comment by brancz** [comment]
Definitely! I've been meaning to add a `README.md` to the grafana-watcher, but haven't gotten around doing it. If you are up for it, it would be highly appreciated if you could write up one :slightly_smiling_face: .

**Comment by vuza** [comment]
PR: https://github.com/coreos/prometheus-operator/pull/656
