### ISSUE TITLE
Grafana dashboard error "Server side error :( Failed to get settings"

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#663]
**What did you do?**
     Running grafana with prometheus-operator release-0.11
 
**What did you expect to see?**
     Dashboard continue displaying metrics from k8s cluster

**What did you see instead? Under which circumstances?**
     When the error "Server side error :( failed to get settings" occurs the files & dirs in the Grafana container is deleted automatically/mysteriously (/var/lib/grafana, /etc/grafana).

**Environment**
     CentOS 7.3

* Kubernetes version information:
     Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
	kubeadm init --kubernetes-version {{KUBERNETES_VERSION}} --skip-preflight-checks

* Manifests:
       kube-cluster

* Prometheus Operator Logs:
N/A

**Comment by brancz** [comment]
I'm not sure I understand the way of how you got into this situation, could you describe more in detail, which objects/manifests you have in your cluster and their version, what you did and expected to happen, and what actually happened.

**Comment by brancz** [comment]
Unfortunately we can't help without enough information. I'll close this here, but feel free to re-open or open a new issue with more information and detail :slightly_smiling_face:!
