### ISSUE TITLE
feature request toleration selection 

### ISSUE THREAD

**Issue by mad01** [coreos/prometheus-operator#668]
currently it's supported to use node selector for prometheus. it would be grate if we could add support for toleration to be able to use tainted instance groups for monitoring. The use case is in a senario were you have a very elastic workload and the cluster instance groups scales up/down frequently. If you have a separate instance group that is tainted you could use that instance for the prometheus instances which would mean that that you have a lower chance to loose the prometheus instance in the node scaling events   

[k8s toleration docs](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)

**Comment by brancz** [comment]
Actually the latest release (`v0.13.0`) introduced this. Unfortunately the docs haven't been synced on coreos.com yet, but the docs on master of this repo are accurate. Let me know if there is still anything missing! :slightly_smiling_face:

**Comment by mad01** [comment]
aa cool that is awesome. will take a look a that then
