### ISSUE TITLE
update liveness and readiness probes for Prometheus 1.8.x

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/prometheus-operator#669]
With https://github.com/prometheus/prometheus/issues/2831 being added to the Prometheus 1.8 release, there are now more accurate endpoints for liveness and readiness probes, the `/-/healthy` and `/-/ready` endpoints. This helps address https://github.com/coreos/prometheus-operator/issues/658 for Prometheus >= 1.8, 2.

**Comment by brancz** [comment]
Adding these definitely make sense, do you want to give it a go?

**Comment by julianvmodesto** [comment]
Sure I'll give this a go.

**Comment by brancz** [comment]
closing here as #675 is merged, thanks a lot for the contribution @julianvmodesto !
