### ISSUE TITLE
Disk space usage depcited in Grafana correct?

### ISSUE THREAD

**Issue by xvzup** [coreos/prometheus-operator#677]
**What did you do?**
Open the Grafana dashboard "Nodes" which is provided by prometheus operator.
**What did you expect to see?**
For a given Kubernetes node the disk space usage was given with 10.41%
**What did you see instead? Under which circumstances?**
Calculating the value by hand I end up with a value of 8.31%. The following expression is used to calculate Disk space usage: 
expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"})"

Executing the exression in prometheus I can see that my root partition is listed three times. Each time with a different mountpoint:

- node_filesystem_size{device="/dev/xvda9",endpoint="http-metrics",fstype="ext4",instance="10.134.121.114:9100",job="node-exporter",mountpoint="/etc/hostname",namespace="monitoring",pod="node-exporter-lmrjv",service="node-exporter"}

- node_filesystem_size{device="/dev/xvda9",endpoint="http-metrics",fstype="ext4",instance="10.134.121.114:9100",job="node-exporter",mountpoint="/etc/resolv.conf",namespace="monitoring",pod="node-exporter-lmrjv",service="node-exporter"}

- node_filesystem_size{device="/dev/xvda9",endpoint="http-metrics",fstype="ext4",instance="10.134.121.114:9100",job="node-exporter",mountpoint="/etc/hosts",namespace="monitoring",pod="node-exporter-lmrjv",service="node-exporter"}
--

The same applies to tmpfs which is listed twice. In the end the given expression provides an inaccurate result and inaccuracy depends on the disk sizes used. 

**Environment**

Container Linux as operating system
Two hard disks in node mentioned. One disk contains the root partition and tmpfs and so on and the second disk is assigned to Docker.

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-29T00:18:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+coreos.0", GitCommit:"2aa47c8ec16177de41d4c8cad63c1ba0b7bd6d78", GitTreeState:"clean", BuildDate:"2017-09-29T22:25:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

bootkube

* Manifests:

Manifests provided by prometheus operator v0.13.0

**Comment by brancz** [comment]
Yes, you're right. How do you think we should solve this? I was thinking of maybe adding a recording rule to have the percentage per logical filesystem:

```
node_filesystem_size:min = min by(device, instance) (node_filesystem_size{device!="rootfs"})
node_filesystem_free:min = min by(device, instance) (node_filesystem_free{device!="rootfs"})
```

Then the query we can do would be this:

```
(sum(node_filesystem_size:min{instance="$server"}) - sum(node_filesystem_free:min{instance="$server"})) / sum(node_filesystem_size:min{instance="$server"})
```

Also a neat one to be able to explore which disk on that host has high utilization

```
node_filesystem_utilization = ((min by(device, instance) (node_filesystem_size{device!="rootfs"}) -
min by(device, instance) (node_filesystem_free{device!="rootfs"})) /
min by(device, instance) (node_filesystem_size{device!="rootfs"}))
```

**Comment by xvzup** [comment]
Hi,

I would prefer the first solution. This looks good to me!

Thx

**Comment by keithf4** [comment]
I'm seeing something similar, but doesn't seem to be caused by duplication of the mount point. It's just flat out calculating the size wrong when summarizing to larger unit scales. Using prometheus as the data source, it is returning the correct values.

```
Filesystem          1K-blocks    Used Available Use% Mounted on
/dev/mapper/cl-root  13092864 6194464   6898400  48% /
devtmpfs               926000       0    926000   0% /dev
tmpfs                  941712    8932    932780   1% /dev/shm
tmpfs                  941712    9004    932708   1% /run
tmpfs                  941712       0    941712   0% /sys/fs/cgroup
/dev/sda1             1038336  233088    805248  23% /boot
tmpfs                  188344       4    188340   1% /run/user/42
tmpfs                  188344      32    188312   1% /run/user/1000
```
```
node_filesystem_avail{device="rootfs",fstype="rootfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/"}	7063990272
node_filesystem_avail{device="sunrpc",fstype="rpc_pipefs",instance="127.0.0.1:9100",job="Prod",mountpoint="/var/lib/nfs/rpc_pipefs"}	0
node_filesystem_avail{device="/dev/sda1",fstype="xfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/boot"}	824573952
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run/user/42"}	192860160
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run/user/1000"}	192831488
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run"}	955092992
node_filesystem_avail{device="/dev/mapper/cl-root",fstype="xfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/"}	7063990272
```
`df` returns values in kilobytes and I checked the conversion values to bytes in prometheus and they match
```
If I just leave the units as "none" in grafana, it shows the matching value from prometheus in grafana. However, setting the unit type to "bytes"(either IEC or Metric) in grafana, the values it calculates when summarizing to GB are off. The above values convert to roughly 6.6GB and 787MB for the xfs partitions, but grafana is reporting it as about 7.06GB and 825MB respectively.

**Comment by brancz** [comment]
Both seems to be applicable. The initial issue was for averaging all utilization, but what you report also sounds reasonable for single file systems as well.

**Comment by keithf4** [comment]
Shouldn't need to make a custom rule to get a correct unit scale adjustment, though. Something seems wrong in grafana's internal calculation.

**Comment by keithf4** [comment]
Perhaps this is the related bug  https://github.com/grafana/grafana/issues/8957

**Comment by brancz** [comment]
@keithf4 yes, what I was saying is that I believe what you are suggesting is correct, the Grafana behavior seems to be wrong. In addition to that the average calculation over all filesystems by us is also off.

**Comment by gaopeiliang** [comment]
I have seen same problem with sum filesystem error , because the duplication  mount point !  but I have used option in node_exporter daemonset
```
            - --collector.filesystem.ignored-mount-points
            - '"^/(sys|proc|dev|host|etc)($|/)"'
```
why not ignore  mountpoint like /etc/hostname ....

---------

with more test ,  I have found the mistake in yml file.
```
            - --collector.filesystem.ignored-mount-points
            - '^/(sys|proc|dev|host|etc)($|/)'
```

maybe help ............

**Comment by lilic** [comment]
Since there  has not had any activity for some time, closing this issue, feel free to open a new one if you are still facing this problem.
