### ISSUE TITLE
kube-prometheus: Mismatch between dashboards and rules

### ISSUE THREAD

**Issue by mikebryant** [coreos/prometheus-operator#686]
https://github.com/coreos/prometheus-operator/blob/9d4f8feb906d465008a0ea45fb94782c3f90446a/contrib/kube-prometheus/assets/prometheus/rules/kubernetes.rules#L134 has `cluster_resource_verb:apiserver_latency:quantile_seconds`

https://github.com/coreos/prometheus-operator/blob/9d4f8feb906d465008a0ea45fb94782c3f90446a/contrib/kube-prometheus/assets/grafana/kubernetes-control-plane-status-dashboard.json#L401 references `apiserver_latency_seconds:quantile`

I can't find a definition for `apiserver_latency_seconds:quantile`, so the dashboard doesn't work.

(Similar issue for all the graphs that aren't `...UP` in that dashboard)

**Comment by brancz** [comment]
Yes, you're right this happened due to some syncronization issues with internal extensions to these rules, I'll try to figure out how to solve this properly. Sorry about this, I'll try to make sure there is a smooth solution to this now and in the future.

**Comment by brancz** [comment]
We've made the decision to open source core rules for Kubernetes clusters, so I will soon be synchronizing them back into this repository so they will be consistent with alerts and dashboards.

**Comment by Arslanbekov** [comment]
@brancz hello, no news on this issue?

**Comment by brancz** [comment]
Sorry about, this I should be able to get to this very soon.
