### ISSUE TITLE
Where can  I config image name in manifests

### ISSUE THREAD

**Issue by Madixin** [coreos/prometheus-operator#690]
**What did you do?**
I have used kube-prometheus in inner network that can not pull image from proxy.  

**What did you expect to see?**
I have pushed all images which kube-prometheus used into our private registry ,and have renamed it to like myPrivateRegistryIP/quay.io/prometheus/xxx , and want to modify the deploy script to use the new image name.

**What did you see instead? Under which circumstances?**

I can not find some image name to config ,such as quay.io/prometheus/prometheus   , quay.io/coreos/prometheus-config-reloader and so on.

**Environment**
kube-prometheus 0.11.2

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

     CentOS  Bare Metal Install

**Comment by brancz** [comment]
The config-reloader images are configured using flags of the prometheus operator binary. They default to

* `--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.0.2`
* `--config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1`

Additionally you can configure the default base images of Prometheus and Alertmanager containers with flags and through fields in the objects (whichever one you like better). The flags are:

* `--alertmanager-default-base-image=quay.io/prometheus/alertmanager`
* `--prometheus-default-base-image=quay.io/prometheus/prometheus`

And the fields in the manifests are the `baseImage` fields in the [`PrometheusSpec`](https://github.com/coreos/prometheus-operator/blob/5da727d9f98e9644d01a17b3c08eb8a68f793533/Documentation/api.md#prometheusspec) and [`AlertmanagerSpec`](https://github.com/coreos/prometheus-operator/blob/5da727d9f98e9644d01a17b3c08eb8a68f793533/Documentation/api.md#alertmanagerspec).

**Comment by Madixin** [comment]
Thanks,I get it. It works.

**Comment by bamb00** [comment]
@brancz,

For private registry do I use the flag like this,
  --prometheus-config-reloader=private_registry.io/prometheus/prometheus

How do I specify the default base image of Prometheus,
 --prometheus-default-base-image=quay.io/prometheus/prometheus

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
  namespace: {{ PROMETHEUS_NS }}
spec:
  replicas: 2
  version: v2.0.0-rc.1
...
...

**Comment by bamb00** [comment]
I think I got it.  Thanks.
