### ISSUE TITLE
Plans to upgrade to client-go 5.0.0

### ISSUE THREAD

**Issue by tamalsaha** [coreos/prometheus-operator#693]
We are trying to use Prometheus operator client from a project that used client-go 5.0.0. This causes build failures due to the k8s.io/api package. I am wondering what are the plans for migration to client-go 5.0.0 .

**Comment by brancz** [comment]
We definitely want to upgrade to client-go 5.0, just haven't gotten to it yet. If you want to, feel free to have a go at it :slightly_smiling_face: .

**Comment by tamalsaha** [comment]
Thanks @brancz ! I did try it and here is the commit from my fork. https://github.com/coreos/prometheus-operator/compare/master...tamalsaha:client-go-5?expand=1 . This complies but has some issues:

Here is a list of things I have changed:

1. Import paths:  I have done global replacement of the following imports
```
k8s.io/client-go/pkg/api/v1 -> k8s.io/api/core/v1
k8s.io/client-go/pkg/apis/ -> k8s.io/api/
```

2. In client-go 5, `runtime.Object` has a new method called `DeepCopy()`. This needs to be implemented for `Resource` and `ResourceList` types.  I have added a stub implementation to compile code. If you use https://github.com/kubernetes/code-generator to generate clients, this method will be auto generated. Given this will need some change in build process, it will be better you folks do it. You can probably talk to your [etcd-operator team](https://github.com/kubernetes/code-generator/issues/4).

3. I am not familiar with govendor, I just tried the dep tool. This is unrelated and unnecessary change in the context of this issue.

So, what will it take to get client-go-5 migration?

**Comment by brancz** [comment]
Thanks for the info! We should probably switch to go dep or glide anyways, and yes I've seen the `DeepCopy` bits before. I'll let you know when we get to upgrading. Can't promise when that will be though.

**Comment by tamalsaha** [comment]
https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/ exists now.

**Comment by tamalsaha** [comment]
FYI, [client-g0 5.0.0](https://github.com/kubernetes/client-go/releases/tag/v5.0.0) has been released.

**Comment by tamalsaha** [comment]
Here is how I am using code-generator for Voyger repo;

https://github.com/appscode/voyager/blob/master/hack/codegen.sh

I am using a Docker image to pre-build code-generators:
https://github.com/appscode/gengo-builder/blob/release-1.8/gengo/Dockerfile

**Comment by brancz** [comment]
Perfect! Thanks for sharing! I’ll be at open source summit EU all week, but should be able to get to it the week after.

**Comment by tamalsaha** [comment]
@brancz , I noticed that master branch now used client-go 5. I am wondering when do you plant to cut the next release for operator. I am trying to decide to decide whether to keep using my fork / switch to unreleased master or wait for next release . :)

**Comment by brancz** [comment]
I don’t think it’s going to be before the holidays, but other than the above code generation we’re done and then we can release.

**Comment by brancz** [comment]
With much delay we're finally there. The `DeepCopy` functions are properly generated. I'm going to close this here as the issue in itself is resolved, we just need to release.

Happy holidays! :tada:
