### ISSUE TITLE
Unable to connect to web UI for Prometheus after creating service

### ISSUE THREAD

**Issue by shaunthium** [coreos/prometheus-operator#71]
I'm running `minikube` v0.14.0 and was following this tutorial here: https://coreos.com/blog/the-prometheus-operator.html, but after creating the `prometheus` TPR and service using `kubectl create -f https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml` in the `Managed Deployments` step, I was unable to connect to the web UI. Running `minikube service prometheus-k8s` simply continuously outputs `Waiting, endpoint for service is not ready yet` before error-ing out.

Any assistance would be greatly appreciated! Thank you.

**Comment by fabxc** [comment]
Seems like your Prometheus pod has trouble starting up fully. Does `kubectl describe <prometheus-pod>` show you anything interesting?

**Comment by shaunthium** [comment]
@fabxc After checking the logs for the pod, I believe the issue is with the migration to `StatefulSets` from `PetSets` in Kubernetes 1.5, as the vendored code for Prometheus Operator seems to still be trying to retrieve the deprecated `PetSets` resource. I'll try again once this PR https://github.com/coreos/prometheus-operator/pull/72 has been merged and see if the issue goes away. Thank you for your help!

**Comment by fabxc** [comment]
Yes, that's certainly it.
The migration from PetSet to StatefulSet will require a new release. We'll cut 0.2.0 once #72 is in.

**Comment by shaunthium** [comment]
The web UI portion is fine now after 0.2.0, so I'll be closing out this issue. Thank you for your time @fabxc !
