### ISSUE TITLE
Make a release for v0.11.2 to fix #644

### ISSUE THREAD

**Issue by nghialv** [coreos/prometheus-operator#710]
Hi

Please make a new release for `v0.11.2` to fix #644.

>> Hi @brancz
Can you make a new release for v0.11.2 with this fix?
We are using v0.11.2 on Kubernetes v1.6.7.

>> I’m currently at ossummit eu, I won’t get to it anytime this week, please open an issue so I’ll remember to backport the fix.

**Comment by brancz** [comment]
Closed by #713
