### ISSUE TITLE
kube-prometheus - Grafana Password Secret can only be admin

### ISSUE THREAD

**Issue by shadycuz** [coreos/prometheus-operator#716]
**What did you do?**
Changed password for grafana
**What did you expect to see?**
I expected to login, but I could only login if I made the password admin
**What did you see instead? Under which circumstances?**

**Environment**
Cloud
* Kubernetes version information:

1.8.1

* Kubernetes cluster kind: 

KubeSpray

* Manifests:

```
cluster-monitoring
```

* Prometheus Operator Logs:
Dont even know what this is ^
```
insert Prometheus Operator logs relevant to the issue here
```

I can only use value of "admin" for grafana password in kube secrets or else I can'y login.

**Comment by brancz** [comment]
How did you generate the base64 encoded string for this? You need to make sure to not have a line break in there.

The command we use to generate it is:

```bash
echo -n <password> | base64 --wrap=0
```

**Comment by shadycuz** [comment]
Hmmm let me give that a shot, most likely my issue.

**Comment by shadycuz** [comment]
@brancz We shall never talk about this again...

So I do have one last question. I read the grafana watcher README and I'm still not sure what it does. It watches the configmap for changes to the dashboards and reloads them into grafana? Or when you change a dashboard in grafana it saves it to the configmap for persistence?

Great work on this by the way. Super easy to get great monitoring out of the box. I'm going to adjust some metrics and submit a PR.

**Comment by brancz** [comment]
No worries, it took me some time to figure it out on the first try as well when I was just seeing base64 encoded strings it's hard to catch a line-break :slightly_smiling_face: .

The grafana-watcher actually has nothing to do with Kubernetes, it just plays well into the way Kubernetes does things. The grafana-watcher just watches files and directories for changes and provisions the Grafana instances with the datasources and dashboards from the files. If any files changes, all dashboards are truncated, and re-provisioned. We do this as it allows us to operate Grafana in a declarative way, where we can scale Grafana up and down depending on our need, without the trouble of running a mysql database or equivalent, just to save some dashboard definitions globally. The operational side is one thing and it also allows us to check in the dashboards into version control, that way we can do reviews for the dashboards before applying them through CI or whatever tooling you choose to use. Lastly, we (or rather a very hard working community) recently converted the Grafana dashboard json definitions to use [grafanalib](), which allows us to define the dashboards as python code, and ultimately allow us to write abstractions above graphs as they are 98% of the time exactly the same with a different query.

Note that we've been talking with Grafana and they're actually working on getting most of this functionality of the grafana-watcher directly integrated into Grafana (slightly different but same end result), so hopefully in the future we won't need to maintain the grafana-watcher, but until then it's a way to fast forward into the future :slightly_smiling_face: .

**Comment by shadycuz** [comment]
@brancz 
Kube-prometheus has grafana-watcher set to look at a configmap, but I thought that was static, a 1 time mapping when the pod is created? So if you did update the config map you would still have to kill that pod to get grafana-watcher to update grafana?

**Comment by brancz** [comment]
The grafana-watcher actually watches file-system events, because when a ConfigMap gets updated, it gets re-mounted into a Pod, triggering the file-system events, which makes grafana-watcher re-provision the "local" Grafana instance.

**Comment by brancz** [comment]
This makes updating Grafana dashboards very easy, as a CI pipeline just applies the ConfigMap with dashboards, and the grafana-watcher ensures the Grafana instance ends up in the correct state, without having to worry about the existing state currently present in the Grafana instance.

**Comment by shadycuz** [comment]
@brancz Ahhh I didn't know that config map values got reloaded live into pods. Neat =). Thanks for being so helpful. 

I did change some metrics in the included dashboards to be more "fitting"  and my api response time and scheduler charts didn't work at all with kubernetes 1.8.1 one. Should I submit a PR?

**Comment by shadycuz** [comment]
@brancz 
# Before
![image](https://user-images.githubusercontent.com/17090999/32330550-d29670f8-bfb6-11e7-9a83-fa5bd88c7b31.png)
# After
![image](https://user-images.githubusercontent.com/17090999/32330601-fa03235c-bfb6-11e7-8479-fede42b15d16.png)

Couple things like that ^

**Comment by brancz** [comment]
Generally yes, all contributions are welcome :slightly_smiling_face:, the exact queries we'll have to review to ensure that they are still appropriate.
