### ISSUE TITLE
AlertManager Liveness & Readiness probe failed: ... getsockopt: connection refused

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#720]
**What did you do?**
Deploy prometheus-operator 0.14.0 to Kubernetes and alertmanager (statefulsets) has the liveness & readiness getsockopt: connection refused.  I had to reboot the VM and the alertmanager works again.

**What did you expect to see?**
alertmanager-main pod does not failed
**What did you see instead? Under which circumstances?**
Liveness and Readiness probe failed: Get http://10.32.0.40:9093/api/v1/status: dial tcp 10.32.0.40:9093: getsockopt: connection refused
**Environment**
Prometheus-operator 0.14.0, CentOS 7.4 and Kubernetes 1.7.4
* Kubernetes version information:

     Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
     Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
	kubeadm

* Manifests:
     alertmanager, prometheus-k8s, kube-state-metrics, prometheus-operator, node-exporter, grafana

* Prometheus Operator Logs:
     time="2017-10-30T23:43:53Z" level=info msg="Starting alertmanager (version=0.9.1, branch=HEAD, revision=9f5f4b2a516d35cfaf196530b277f1d109254569)" source="main.go:109"
     time="2017-10-30T23:43:53Z" level=info msg="Build context (go=go1.9, user=root@3b87d661c3dd, date=20170929-12:59:03)" source="main.go:110"

* Events:
      Liveness probe failed: Get http://10.32.0.25:9093/api/v1/status: dial tcp 10.32.0.25:9093: getsockopt: connection refused 

     Readiness probe failed: Get http://10.32.0.25:9093/api/v1/status: dial tcp 10.32.0.25:9093: getsockopt: connection refused 

     Killing container with id docker://alertmanager:pod "alertmanager-main-0_monitoring(d2383df4-c2a1-11e7-815f-0050569193bf)" container "alertmanager" is unhealthy, it will be killed and re-created.

**Comment by brancz** [comment]
> I had to reboot the VM and the alertmanager works again.

This doesn't sound like a problem with the Prometheus Operator.

**Comment by bamb00** [comment]
Actually, rebooting the VM does not help resolve the CrashLoopBack error to the alertmanager statefulsets.  But it would be helpful to pinpoint what's causing the network issue between alertmanager and prometheus.
