### ISSUE TITLE
Chart at opsgoodness/prometheus-operator:0.0.6 is out of sync

### ISSUE THREAD

**Issue by cofyc** [coreos/prometheus-operator#723]
**What did you do?**

Install prometheus-operator v0.14.1 with opsgoodness/prometheus-operator:0.0.6 chart.

**What did you expect to see?**

Everything should be ok.

This commit https://github.com/coreos/prometheus-operator/commit/3ea7085ae076d1c32b9436fba5ee66beeb97b322#diff-f968b7bf1e41336c32aa557114213c78 update charts templates but did not update chart version.

Release a new chart version 0.0.7?

**Comment by brancz** [comment]
We're currently looking to have a new home for the charts, related to #676

**Comment by gianrubio** [comment]
Can we close this?
