### ISSUE TITLE
kubernetes_io_hostname missing in metrics

### ISSUE THREAD

**Issue by skuda** [coreos/prometheus-operator#725]
**What did you do?**
Tried to install this grafana dashboard https://grafana.com/dashboards/315

**What did you expect to see?**
Dashboard working.

**What did you see instead? Under which circumstances?**
Graphs are showing "no data points"

**Environment**
Using kube-prometheus with v0.14.1 prometheus-operator release.

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-04T09:07:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Minikube but tried too in an Azure cluster created with acs-engine.

It seems that some labels are missing from a lot of metrics, I don't know if the problem is related to Prometheus v2.0 or some other problem related with prometheus-operator itself, this is one of the metrics are failing now from the linked dashboard:
`sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))`

There was a problem getting the node name in the dashboard but I fixed that, now the next thing is failing and I am don't know how to fix is that container_network_receive_bytes_total doesn't have the label kubernetes_io_hostname available.

I would like to be able to integrate that dashboard, does anyone how to fix that? Thanks!

**Comment by brancz** [comment]
The metrics on cAdvisor have no stability guarantees unfortunately, so these may have changed. We'll have to investigate.

**Comment by Morriz** [comment]
That dash works fine with me, I expect some of the exporters not to work correctly.

**Comment by skuda** [comment]
Hey @Morriz, I am using kube-prometheus directly, not helm based installation, maybe the problem is related?

I don't see the label kubernetes_io_hostname in any of the metrics used in that dashboard so it's impossible in my setup for those charts to work.

**Comment by Morriz** [comment]
Then I think you are not correctly deploying the `hack/...` scripts, or have not generated the correct artefacts. Also, I have only been able to get the manifests to work together by NOT specifying a namespace with `kubectl apply`. So trying to deploy everything into a 'monitoring' namespace has been no success (I am only deploying on minikube for now, so I assume it's not rbac related, as that is not active on minikube yet).

Anyway, you have to check the 'targets' section of the prometheus server to see if your exporters are scrapable.

Personally, I suggest you do go the helm way, as it packages up what you are trying to deploy atomically, and makes you think about how to do that...

**Comment by skuda** [comment]
For me, everything is working perfectly fine using the monitoring namespace and the kube-prometheus scripts. 

You can see the Prometheus targets here:
[![Screenshot from Gyazo](https://gyazo.com/4c463bf9ad3eb863d54bf68fe17bdc1d/raw)](https://gyazo.com/4c463bf9ad3eb863d54bf68fe17bdc1d)

All the included dashboards in kube-prometheus work perfectly fine, and other dashboards I integrated directly from grafana are working fine too. The only one is failing for me is this specific dashboard because it makes use of kubernetes_io_hostname.

The other dashboards that use `label_values(node_boot_time, instance)` as node identification are working fine. I will try a minikube based installation with helm but I had problems using the helm based installation with my acs-engine deployed cluster, that is the reason why I am using kube-prometheus directly.

Miguel.

**Comment by Morriz** [comment]
that is strange, as I just added it and it works nicely :|

**Comment by brancz** [comment]
The `ClusterRoleBinding`s of the kube-prometheus stack assume the `monitoring` namespace, if you wish to deploy it to another namespace you'll have to check those manifests and adapt them. The helm charts, are currently in a bit of a rough state, we're working on getting them into shape. I'd recommend [this article](https://itnext.io/kubernetes-monitoring-with-prometheus-in-15-minutes-8e54d1de2e13) if you still want to use helm to deploy the kube-prometheus stack with it.

**Comment by skuda** [comment]
I used monitoring namespace and kube-prometheus scripts, indeed everything is working fine for me, other than the kubernetes_io_hostname label is not inside metrics.

**Comment by brancz** [comment]
@skuda can you just query for `container_network_receive_bytes_total` in the Prometheus UI, and paste the "console" output here? I'm guessing that the label was renamed.

**Comment by skuda** [comment]
I don't think so, but here it is:
```

container_network_receive_bytes_total{container_name="POD",endpoint="http-metrics",id="/kubepods/besteffort/pod4256e17ced5ddf3c3d2993e020b26592/40b24544b3051051f767fa5cc0aecb27490b4099c17b7c4a220134763b961454",image="gcrio.azureedge.net/google_containers/pause-amd64:3.0",instance="10.240.255.5:10255",interface="eth0",job="kubelet",name="k8s_POD_kube-scheduler-k8s-master-42737137-0_kube-system_4256e17ced5ddf3c3d2993e020b26592_3",namespace="kube-system",pod_name="kube-scheduler-k8s-master-42737137-0",service="kubelet"} | 69473372821

container_network_receive_bytes_total{container_name="POD",endpoint="http-metrics",id="/kubepods/besteffort/pod427d3a4dadff5c4319c62797574c7106/97b8e6fd078dce2663e66a3d6a7c7d086342e6e4f3676e45dafa652f29484c35",image="gcrio.azureedge.net/google_containers/pause-amd64:3.0",instance="10.240.255.5:10255",interface="cbr0",job="kubelet",name="k8s_POD_kube-apiserver-k8s-master-42737137-0_kube-system_427d3a4dadff5c4319c62797574c7106_0",namespace="kube-system",pod_name="kube-apiserver-k8s-master-42737137-0",service="kubelet"} | 3248871
```

**Comment by brancz** [comment]
hmm .. sounds like there was a change upstream then. Could you open an issue on the cadvisor repository and tag me? We can leave this open until we resolve things there.

**Comment by stuxnet78** [comment]
@skuda I've also followed the same way that you have tried. Even me too ended up with the same problem that you are facing label `kubernetes_io_hostname` is not present on Prometheus. 

But when I tried with helm method I don't see that problem, but it creates other problem like no alerts configurations on Prometheus alerts page.

I'm using Kubernetes 1.6 with RBAC disabled on helm method.

**Comment by Morriz** [comment]
The helm chart is too bloated and should be split up to be able to use the prometheus and alertmanager charts (they are now bundled up with kube-prometheus). 

Take a look at morriz/mostack to see what I did. It has a lot of work in figuring out how to deal with helm, rbac and network policies.

**Comment by brancz** [comment]
I totally agree @Morriz, I documented what I imagine the helm charts to look one day: #592. We don't use helm for the prometheus-operator, so we rely on the community to maintain them.

**Comment by skuda** [comment]
@stuxnet78 I am waiting for cadvisor maintainers to check the issue I created to have a proper fix, the only Grafana dashboard that fails for me is the one I linked in the first post so I can live without `kubernetes_io_hostname` for now.

**Comment by brancz** [comment]
Closing this as there doesn’t seem to be a problem with the Prometheus operator, I’ll try to follow up with the cAdvisor people.
