### ISSUE TITLE
How to update kube-prometheus manually on Tectonic stack, when Tectonic stack failed to update from 1.6.8 to 1.7.1 then to 1.7.5?

### ISSUE THREAD

**Issue by kubebc** [coreos/prometheus-operator#741]
Hi, Team,
Maybe you have some tips on this ticket? Thanks! :) 
https://github.com/coreos/tectonic-forum/issues/211
"How to move on "Migration from TPR to CRDs"? My Prometheus Operator didn't automatically migrate TPRs to CRDs when the whole Tectonic got updated from 1.6.8 to 1.7.1 then to 1.7.5 #211"

**Comment by brancz** [comment]
Commented on the other issue.

**Comment by kubebc** [comment]
Thanks!
So your suggestion is better to restore to TPR,
and not to migrates TPRs to CRDs manually,
and not to let Prometheus Operator automatically migrates TPRs to CRDs again,
right?

**Comment by brancz** [comment]
Actually since your TPRs are already de-registered and the CRDs registered, and a recent version of the Prometheus Operator is started, I'd just recommend to restore the CRDs directly.

**Comment by brancz** [comment]
Closing here due to staleness. Feel free to re-open or open a new issue should you still have a problem! :slightly_smiling_face:
