### ISSUE TITLE
Running kube-prometheus results in 2 kublet targets per node with one failing

### ISSUE THREAD

**Issue by shadycuz** [coreos/prometheus-operator#742]
**What did you do?**  

Ran `git pull` and then deployed the self-hosted deploy.  

**What did you expect to see?**  

Awesome monitoring per the usual  

**What did you see instead? Under which circumstances?**  

I see extra targets for Kubelet that are now failing.  

![image](https://user-images.githubusercontent.com/17090999/32607542-56dba2f0-c527-11e7-89e4-cde64568436e.png)

**Environment**  

Bare-metal
* Kubernetes version information:

```
root@master01:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeSta
te:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeSta
te:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Kube-Spray

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
This sounds like there is a problem with the firewall or kube-spray disabling the `:4194` cAdvisor port.

**Comment by shadycuz** [comment]
@brancz when I deployed 2 or 3 weeks ago it was only the 1 target per node. I ran git pull and redeployed and got the 2. I can check with kubespray about the metrics.

**Comment by shadycuz** [comment]
@brancz They just added it 3 days ago. https://github.com/kubernetes-incubator/kubespray/pull/1908/files and it's default port is 0. I'm guessing off. Closing this. 

Congrats on prometheus 2.0. Can't wait till we are using it in kube-prometheus. Looking forward to the 16th.

**Comment by brancz** [comment]
Yes, since Kubernetes 1.7.3 the kubelet serves _only_ its own metrics on the `/metrics` endpoint and container metrics on `/metrics/cadvisor`. The `/metrics` endpoint on the `:4194` port is identical to the `/metrics/cadvisor` endpoint, only that it was available before and afterwards. You can also change the `ServiceMonitor` to use the 10255 port with the `/metrics/cadvisor` endpoint instead, then you won't need to adapt firewall rules if that's the problem.

**Comment by shadycuz** [comment]
I will probably try to change the service advisor to go back to 10255. Pod and deployment charts worked so it must have been getting cadvisor metrics.
