### ISSUE TITLE
RFE: Nodes Summary

### ISSUE THREAD

**Issue by rocketraman** [coreos/prometheus-operator#743]
In the dashboards, I'd love to see a Nodes summary dashboard. Currently, each node has its own dashboard which is great for digging into the details, but often times one just wants a high-level view of node CPU, memory, and I/O across the cluster.

**Comment by brancz** [comment]
This already exists in the "Kubernetes Capacity Planning" dashboard is :slightly_smiling_face: it literally has the same layout, just all nodes summed up.

**Comment by rocketraman** [comment]
That's useful for some things but isn't that I'm looking for. I'm looking for individual node level data, summarized. Summing the node data is ideal for capacity planning but obscures issues with individual nodes. For example if I have one node with a CPU at 100% due to a bug in some host software, I won't see that in the sum.

**Comment by brancz** [comment]
I see. Not sure how you would do that, but happy to accept PRs, if you have a reasonable strategy :slightly_smiling_face:

**Comment by rocketraman** [comment]
Maybe just one chart for each of CPU, memory, I/O, and network send/receive showing one line for current usage for every node? This will allow an at-a-glance view of the normal ranges of these values, and any outliers.

Memory usage would be a percent of total so it is normalized.

Network usage would just be summed across all interfaces for the node.

**Comment by brancz** [comment]
That sounds great!

**Comment by brancz** [comment]
fyi there is now a cluster wide dashboard, it doesn't include I/O and network metrics though, maybe you want to add it? The source for it is developed here: https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by lilic** [comment]
Since there  has not had any activity for some time, closing this issue, feel free to open a new one in https://github.com/kubernetes-monitoring/kubernetes-mixin if you are still facing this problem.
