### ISSUE TITLE
node_exporter should use recording rules to publish node name

### ISSUE THREAD

**Issue by rocketraman** [coreos/prometheus-operator#744]
Quoting @brancz from https://github.com/coreos/prometheus-operator/issues/135#issuecomment-341131667:

> As I mentioned above the problem is solvable with recording rules today. I have been playing with this lately and will probably publish the recording rules and updated dashboards accordingly, although I believe the node name is most useful here, as it's modifiable to contain whatever you want and typically defaults to the hostname.

Creating this issue to track this! Thank you.

**Comment by dimm0** [comment]
Any updates on this? The stats are quite unusable with IPs...

**Comment by brancz** [comment]
I apologize for still not having gotten to this, we are currently reworking our Grafana dashboards, once we have the transition done, we will be able to take care of this easily.

**Comment by dimm0** [comment]
Still looking forward to getting this done (although I've already implemented a bunch of workarounds, none of them seem to be completely fixing the issue)

**Comment by whypro** [comment]
Adding node name to timeseries can be implemented by:
1. set node-exporter endpoints' `targetRef.kind` to `Node`, then prometheus will add `__meta_kubernetes_node_name` label to time series.
```
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: node-exporter
  name: node-exporter
subsets:
- addresses:
  - ip: 192.168.128.116
    targetRef:
      kind: Node
      name: k8s-dev-1
```
Thanks to: https://github.com/prometheus/prometheus/pull/3748#issuecomment-361817651

2. make prometheus-operator generate relabel config that converting `__meta_kubernetes_node_name` to `node`. 
(As a result, `node="k8s-dev-1"` will be added to all time series scraped from node-exporter)
reference commit: https://github.com/whypro/prometheus-operator/commit/c341123348528da3b8058d434f7e80c3f0417150

It is useful for metrics exposed by kubelet and node-exporter (or any node-binding exporter). And our team is using in this way.

**Comment by whypro** [comment]
Will recording rules result in some performance problems?
IMHO, it could also be implemented by: https://github.com/coreos/prometheus-operator/issues/135#issuecomment-383617438.

**Comment by midnightconman** [comment]
Can we have an update on this issue?

**Comment by brancz** [comment]
Coincidentally I'm actually working on this currently. Updates coming soonish.

**Comment by dimm0** [comment]
Still no progress on this?

**Comment by brancz** [comment]
Actually this is now done, the dashboards allow you to select by node name now instead of node IP, and there are recording rules to do this in the expression browser as well. Closing here :tada:.

**Comment by dimm0** [comment]
Should I update to master to get this? Could you point me at the commit plz?

**Comment by zytek** [comment]
I've just deleted my prometheus stack (whole monitoring namespace) and created it with newest manifests from repo and Nodes dashboard still shows virtual IP addresses.

**Comment by brancz** [comment]
It uses whatever the name of your node objects is. The same as when you do `kubectl get nodes`.

**Comment by zytek** [comment]
Should I somehow regenerate manifests to get this ? 

My nodes are named after AWS private dns, but as I said dashboard still shows node-exporters pod IP addresses.

**Comment by brancz** [comment]
Somewhat depends on how you installed your stack, but even if you just apply the manifests in `contrib/kube-prometheus/manifests/` against your cluster you should see this in the "K8s / USE Method / Node" dashboard.

**Comment by brancz** [comment]
Yes, there is still some cleaning up/migrating to do but, the goal is to have one set of dashboards that can be shared among the whole community! :slightly_smiling_face: This effort is being worked on in this repo: https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by dimm0** [comment]
@brancz where is the magic line to convert the instance to node name? I want to do the same for my dashboards, but can't find it so far..

**Comment by brancz** [comment]
@dimm0 for example the "K8s / USE Method / Node" dashboard does selection based on [`kube_node_info`](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/297f40ffc7dc07b690bf715f3952a8b729ba9197/dashboards/use.libsonnet#L85). Then queries this recording rule: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/297f40ffc7dc07b690bf715f3952a8b729ba9197/dashboards/use.libsonnet#L90

And the recording rule is defined here: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/rules.libsonnet#L128-L134

**Comment by dimm0** [comment]
Great, thanks!

**Comment by brancz** [comment]
It somewhat depends on how these daemons are deployed. Are they just a daemonset? If that's the case, then they are just pods, and you can use the `kube_pod_info` metric to figure out the relationship between private IP and node name: https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/pod-metrics.md

**Comment by dimm0** [comment]
Daemons are not running in a container at all, they are deployed on the nodes. I'm manyally setting the endpoints for those:

https://gitlab.com/dimm/prp_k8s_config/blob/master/monitoring/rules.jsonnet#L145-211

https://prometheus.nautilus.optiputer.net/targets

https://grafana.nautilus.optiputer.net/d/lhzgeA3zk/all-cuda-gpu?

**Comment by brancz** [comment]
You have two options, you can either specify entirely your own Prometheus scrape config using the `additionalScrapeConfigs` feature, or you re-use the kubelet endpoints object and set the port you want to scrape manually by just specifying the `targetPort` as the port number you want to scrape.

**Comment by dimm0** [comment]
How is that helping me to see the hostname?
Scraping works fine, I just can't convert the IP to hostname when displaying data in grafana dashboard

**Comment by dimm0** [comment]
> you can either specify entirely your own Prometheus scrape config using the additionalScrapeConfigs feature

Can I add just my scrape config, or I have to repeat the whole config you have already? And what exactly should I add to it?

>or you re-use the kubelet endpoints object and set the port you want to scrape manually by just specifying the targetPort as the port number you want to scrape

How would that help having the node name show up in dashboard?

**Comment by mxinden** [comment]
> Can I add just my scrape config, or I have to repeat the whole config you have already? And what exactly should I add to it?

Whatever you put into `prometheus.spec.additionalScrapeConfig` will be added to the [`scrape_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) section of your Prometheus configuration.

**Comment by dimm0** [comment]
Ok, great. But I still don't have the __meta_kubernetes_node_name field after setting targetRef.kind to Node...

https://github.com/coreos/prometheus-operator/issues/135#issuecomment-383617438

**Comment by brancz** [comment]
What is depicted in https://github.com/coreos/prometheus-operator/issues/135#issuecomment-383617438 is not true, as the PR never got merged. The following meta labels will be added with the respective values:

* `__meta_kubernetes_endpoint_address_target_kind`: will be set to `Node`
* `__meta_kubernetes_endpoint_address_target_name`: will be set to the nodes name

**Comment by dimm0** [comment]
I don't see those either..

**Comment by dimm0** [comment]
I solved this by running GPU exporters as pods.
