### ISSUE TITLE
Place holder for a PR I am Working on IGNORE

### ISSUE THREAD

**Issue by shadycuz** [coreos/prometheus-operator#745]
# Dashboard Updates

### Before
![image](https://user-images.githubusercontent.com/17090999/32632587-2c4aba4e-c572-11e7-9984-c0f06559a4f0.png)
![image](https://user-images.githubusercontent.com/17090999/32632612-443fa434-c572-11e7-8a39-eedde136ff08.png)

### After

![image](https://user-images.githubusercontent.com/17090999/32632657-6c60669c-c572-11e7-94db-b0add117f081.png)
![image](https://user-images.githubusercontent.com/17090999/32632671-7b5192f2-c572-11e7-894f-78862598badc.png)

### Before
![image](https://user-images.githubusercontent.com/17090999/32633648-531414a0-c576-11e7-86bd-f5ae7638456d.png)

![image](https://user-images.githubusercontent.com/17090999/32633657-611bdf06-c576-11e7-9045-6b6900b1022e.png)

![image](https://user-images.githubusercontent.com/17090999/32633675-778f5c4a-c576-11e7-984c-63fc78c2bc5a.png)

### After
Have not worked out the other charts yet

![image](https://user-images.githubusercontent.com/17090999/32635171-17532256-c57d-11e7-989d-7b5a153c60ea.png)

### Before
![image](https://user-images.githubusercontent.com/17090999/32663109-ccba2b80-c5fa-11e7-92f5-555b3d178787.png)

![image](https://user-images.githubusercontent.com/17090999/32663125-d81c7bd6-c5fa-11e7-85c0-7ee47f39e316.png)

![image](https://user-images.githubusercontent.com/17090999/32663145-e56e98e6-c5fa-11e7-9714-1c124bc67b0d.png)

![image](https://user-images.githubusercontent.com/17090999/32663160-f0488d80-c5fa-11e7-950d-a478b1ab35d3.png)

## After
![image](https://user-images.githubusercontent.com/17090999/32663582-74cd7998-c5fc-11e7-97bd-ec7f3323da9d.png)

![image](https://user-images.githubusercontent.com/17090999/32663590-7f91b2e0-c5fc-11e7-9617-b36139385d92.png)

![image](https://user-images.githubusercontent.com/17090999/32663608-8d3d79e2-c5fc-11e7-9894-1cc337842a98.png)

![image](https://user-images.githubusercontent.com/17090999/32663659-cb1906dc-c5fc-11e7-927e-1b3939a3247c.png)

### Before
![image](https://user-images.githubusercontent.com/17090999/32663957-c47e7d56-c5fd-11e7-91b6-4d2c5d883da8.png)

### After

![image](https://user-images.githubusercontent.com/17090999/32664036-fcdd85b6-c5fd-11e7-92c6-a1a8f7c95f39.png)

**Comment by brancz** [comment]
The request latency is just a result of us not having synced recording rules with our internal set. I'm about to publish all internal recording rules for core kubernetes components, so that will be solved.

**Comment by shadycuz** [comment]
Interested in those changes @brancz , I will submit the PR as soon as I get that configmap generation script to run. Also I noticed those charts are in python? Can I submit json?

**Comment by brancz** [comment]
The json changes are overridden by the json generated by the python scripts. It should generally be pretty easy to adapt through the python code, if not the abstraction is not good enough :slightly_smiling_face:

**Comment by brancz** [comment]
That said, wait until early next week, when I have synced the open source rules with the internal set.

**Comment by lilic** [comment]
Since there  has not had any activity for some time, closing this issue, feel free to open a new one if you still want this feature.
