### ISSUE TITLE
Allow security context to be specified explicitly

### ISSUE THREAD

**Issue by alexlokshin** [coreos/prometheus-operator#746]
It appears the security context is set to 1000:2000:non-root, we're running into an issue with the hostPath volumes where a specific gid/uid have to be used. Please support securityContext at the spec level.

```
 		gid := int64(2000)
 		uid := int64(1000)
 		nr := true
 		securityContext = v1.PodSecurityContext{
 			FSGroup: &gid,
 			RunAsNonRoot: &nr,
 			RunAsUser: &uid,
 		}
```

**Comment by lucasvel** [comment]
Having this same issue as of right now

**Comment by brancz** [comment]
I'm fine with adding this, and defaulting to what is currently in use.

**Comment by lucasvel** [comment]
@brancz do you know when a new release should be out with this fix?

**Comment by brancz** [comment]
Not before the holidays but probably soon after :) happy holidays.
