### ISSUE TITLE
Include alerting in Prometheus Helm Charts

### ISSUE THREAD

**Issue by keithjohnhowe** [coreos/prometheus-operator#747]
I am planning to use Prometheus to monitor an application which (when finished) will sit on a K8s cluster. 
Unfortunately I am having some problems with alerting. As far as I understand the alerting rules are set in the rules_file, these rules are then handled by the Alertmanager. However my question is -- How do I set these to send an alert if for example a pod fails or the CPU reaches 90% and is it possible to incorporate the alerts into a Helm file ? 

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
I'm not sure I understand the question. Alerting rules are loaded by Prometheus. A common practice is that each team runs their own Prometheus instance(s), and then all alerts are fired against a single Alertmanager cluster, where they can then be globally deduplicated and grouped in a meaningful way to then be sent via your favorite notification provider.

**Comment by keithjohnhowe** [comment]
Many thanks for getting back -   I would like to use Prometheus for monitoring and alerting an app that will sit on a K8s cluster. I have used Helm to install Prometheus along with Grafana and can now use it for monitoring nodes/pods etc. However it is alerting that I'm having problems getting my head around. I understand the theory of using prometheus.yaml to point to the rules_file which is then used to define the alerting rules and then the AlertManager is used to send alerts etc. 
I need to deliver Prometheus monitoring/alerting in a helm file so as far as I understand it will be the values.yaml file I need to edit to set the rules ?  Basically I would welcome some guidelines on how to go about setting a few alerts to monitor a k8s cluster ie. how to define alerts when pods go down or CPU goes above 80%.

**Comment by brancz** [comment]
The `Prometheus` object defines a `ruleSelector` meaning, that any `ConfigMap` that has matching labels, will be retrieved by the prometheus-config-reloader side-car and then the files inside it will be loaded by Prometheus. The Prometheus Operator ensures, that the `prometheus.yaml` config is adapted properly in order to do this. Meaning, that any helm chart that puts a `ConfigMap` that has the correct labels and contains alerting rules will be loaded.

**Comment by keithjohnhowe** [comment]
Thanks for the reply -- I will look into using a ConfigMap to define alerting alerts and let you know how I get on.

**Comment by keithjohnhowe** [comment]
Could you please advice - I have created a configmap.yaml in the helm/prometheus/templates with rules and a a label - backend. I can execute
 $helm install --name prometheus --set serviceMonitorsSelector.app=prometheus --set ruleSelector.app=prometheus --namespace=monitoring helm/prometheus
so I assume the the configmap is running.
I have also created the follow configmap for the alertmanager. When I run 
$helm install --name alertmanager --namespace=monitoring helm/alertmanager
I am getting -
Error: error validating "": error validating data: found invalid field route for v1.ConfigMap
Apologies if this is a silly question, I am new to this and a few pointers would be welcome. 

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
data:
  alertmanager.yml: |-

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  group_by: []
  group_wait: 30s
  group_interval: 5m
  receiver: 'team-emails'

  routes:
  # This routes performs a regular expression match on alert labels to
  # catch alerts that are related to a list of services.
  - match_re:
     service: backend
    receiver: team-emails
    continue: true

  receivers:
  - name: 'team-emails'
    email_configs:
    - to: xxxxxxxxxxxx
      from: xxxxxxxxxxx
      smarthost: smtp.gmail.com:587
      auth_username: "xxxxxxx"
      auth_identity: "xxxxxxx"
      auth_password: "xxxxxxx"

**Comment by brancz** [comment]
The Alertmanager configuration actually needs to be a `Secret`, not a `ConfigMap`. I'd suggest to go through the [Getting Started](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md) and [Alerting](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) guides without helm, in order to understand the way things play together. Then you can go ahead and automate things away with helm, or whatever your favorite tool ends up being :slightly_smiling_face: .

**Comment by keithjohnhowe** [comment]
Many thanks, I'll have a look at the guides and follow your suggestion about helm.

**Comment by brancz** [comment]
I'll close this issue here, but feel free to re-open or open a new issue if you run into problems.

**Comment by keithjohnhowe** [comment]
I have followed the guides and have got a basic operator in place with the idea of changing this once I get it to work. However I start to run in to problems when I add the AlertManager. I have added the references to the prometheus.yaml to point to the alermanager.yaml and created the relevant resources as described in the guides so I'm not sure were I'm going wrong and would be grateful for some guidance.  I have included my prometheus.yaml file.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:

  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
global:
rule_files:
  name: ./example.rules
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.14.1
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: prometheus-operator
        spec:
          replicas: 2
          alerting:
            alertmanagers:
            - namespace: default
              name: alertmanager-example
              port: web
