### ISSUE TITLE
K8SApiServerLatency always triggering but can't find why

### ISSUE THREAD

**Issue by iJanki** [coreos/prometheus-operator#751]
I'm running an on premise k8s 1.8.1 cluster installed with kubespray.
There are 2 API servers.
The alert 
```
histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"}) WITHOUT (instance, resource)) / 1e+06 > 1
```

is always triggering.

```
{endpoint="https",job="apiserver",namespace="default",scope="cluster",service="kubernetes",subresource="",verb="POST"} | 8
```

I can't see anything wrong on the cluster. I also checked the logs of apiservers for POSTS, and the response time is never above 1 second.

Could help me find out what's wrong?

**Comment by brancz** [comment]
This definitely means, that your apiserver is responding slowly, to _some_ request. You should query the Prometheus UI to see which ones those are. Just run

```
histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"}) WITHOUT (instance, resource)) / 1e+06
```

in the Prometheus expression browser, and you should be able to find the values that are too high. You might need to graph it to see it historically (this query might take some time as it's a lot of data and calculations).

**Comment by iJanki** [comment]
Thanks for reply, if i do that i get

{endpoint="https",job="apiserver",namespace="default",scope="cluster",service="kubernetes",subresource="",verb="POST"}   8

But still can't pinpoint what request is that. 
If i theck api servers logs i get lines like

I1113 14:27:22.545325       1 wrap.go:42] POST /api/v1/namespaces/monitoring/events: (6.05608ms) 201 [[kubelet/v1.8.1+coreos.0 (linux/amd64) kubernetes/59359d9] 10.88.51.17:57328]

but the time (6.05608ms) is never more than 1 second.

**Comment by brancz** [comment]
What's odd is that the `resource` label is empty. Can you check when you do a raw query without the `histogram_quantile` function, whether there is the `resource` label?

**Comment by iJanki** [comment]
using "WITHOUT (instance, resource)" does not remove the resource?

if i do
```
histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"}) WITHOUT (instance)) / 1e+06 > 1
```
i get
```
{endpoint="https",job="apiserver",namespace="default",resource="namespaces",scope="cluster",service="kubernetes",subresource="",verb="POST"}   8
```

**Comment by iJanki** [comment]
Hmm, these are the actual metrics from apiserver /metrics (for verb=POST and resource=namespaces) 

```
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="125000"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="250000"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="500000"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="1e+06"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="2e+06"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="4e+06"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="8e+06"} 0
apiserver_request_latencies_bucket{resource="namespaces",scope="cluster",subresource="",verb="POST",le="+Inf"} 1
```

**Comment by brancz** [comment]
The buckets are cumulative, meaning this request happened at some point in time, so the logs don't help unless we find the actual request. It seems that there was a single request, that took longer than 8 seconds. Does the alert still fire? I would expect it not to, as it should only fire if there was an increase of this value.

**Comment by iJanki** [comment]
I tried to restart the apiserver pods, and that bucket still has 1. I can't find any request that take that long in the logs... so weird.
And it alerts yes, even if that number stays the same.

**Comment by brancz** [comment]
I see, yes actually that is expected, we would need to add a `rate` in addition to the `sum` in the `histogram_quantile` function in order to do this based on let's say the past 10 minutes. Right now it's just saying the 99th percentile of all requests ever is >8s, which is not as useful.

Two things to do:
* improve the alerting rule to be based on recent data points
* figure out where that "create namespace" request is coming from and why it's taking so long and more importantly why it occurs everytime, even when you restart the apiserver

**Comment by brancz** [comment]
Would you like to take a shot at improving the alerting rule? :slightly_smiling_face:

**Comment by iJanki** [comment]
I'll give it a try:)

**Comment by iJanki** [comment]
how about

```
histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"}[10m])) by (le)) / 1e+06 > 1
```
