### ISSUE TITLE
Prometheus Exporters

### ISSUE THREAD

**Issue by kaarthikeyan1987** [coreos/prometheus-operator#759]
**What did you do?**
I have Prometheus implemented using Prometheus-operator.
**What did you expect to see?**
I would like to setup monitoring for the applications like Nginx, Tomcat, Mysql, Redis, Elastisearch
**What did you see instead? Under which circumstances?**
I tried different approaches and failed to get things up and running on the prometheus dashboard
**Environment**
AWS
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
KOPS

* Manifests:
Need to create one but I do not have a documentation or walk through on step by step procedure to implement exporters. I just have a running cluster with KOPS monitoring through prometheus on pod and container level metrics. I would like to accomplish the same for applications mentioned above.

**Comment by brancz** [comment]
We have a walk through for exporters in our documentation: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/running-exporters.md

Let us know if you have any more questions.

**Comment by kaarthikeyan1987** [comment]
Thanks for your reply Brancz. From the link that you provided I could see code for creating service and service monitor, But I need to know on how to integrate the exporters itself.
I would like to know how to setup exporter deployment to make it running as a pod, may be post which I have to create service and service monitor

**Comment by brancz** [comment]
Can you elaborate? Exporters are run in Kubernetes just like any other workload.

**Comment by brancz** [comment]
Closing this due to lack of information. Feel free to continue to comment, re-open or open a new issue. There doesn’t seem to be an issue with the Prometheus Operator itself here.
