### ISSUE TITLE
Mertics Data Storage

### ISSUE THREAD

**Issue by hamid2013** [coreos/prometheus-operator#760]
Hello All,

Need help on this.
I have implemented the kube-prometheus. I checked all the files but didn't find where exactly the data is getting stored. For that i need to use persistent data disk. (Which we are using Glusterfs).

Another question i have, when i run the deploy script, its deploy all the necessary services on the kubernetes cluster in the monitoring namespace. But without the password we can view all the dashboard. How can we restrict that with the credential.

**Comment by brancz** [comment]
It's important to understand that the kube-prometheus collection merely contains examples, you are encouraged to take it and adapt it to the way you need it. Have a look at the Grafana documentation to find out how to configure authentication and adapt the deployment. And modifying the object to fit your persistent storage solution is absolutely encouraged.

**Comment by mfaizanse** [comment]
@brancz can you share any blog or instructions for persistent storage solution?

**Comment by brancz** [comment]
We have documentation on this here: https://coreos.com/operators/prometheus/docs/latest/user-guides/storage.html

Multiple persistent storage providers are described there. Feel free to ask follow up questions.
