### ISSUE TITLE
auto add v2.0.0-rc.1 tag to prom/prometheus images

### ISSUE THREAD

**Issue by shenshouer** [coreos/prometheus-operator#762]
Run Deployment with image `coreos/prometheus-operator::v0.14.1`  when set flag `--prometheus-default-base-image=thub.autohome.com.cn/prom/prometheus:v2.0.0`, will pull error images: `Failed to apply default image tag "thub.autohome.com.cn/prom/prometheus:v2.0.0:v2.0.0-rc.1": couldn't parse image reference "thub.autohome.com.cn/prom/prometheus:v2.0.0:v2.0.0-rc.1": invalid reference format`

**Comment by brancz** [comment]
This flag is only to override the default `baseImage` of Prometheus objects. You can set the version used in your Prometheus object with the `version` field. (see https://coreos.com/operators/prometheus/docs/latest/api.html#prometheusspec)

**Comment by shenshouer** [comment]
Tks, It work fine when I specific the version on prometheus Spec.
