### ISSUE TITLE
http_requests_total metrics for my custom pods not showing

### ISSUE THREAD

**Issue by mfaizanse** [coreos/prometheus-operator#763]
**What did you do?**
I deployed prometheus-operator (kube-prometheus) and then deployed my application pods and services. Now on the prometheus ui, when I executed 'http_requests_total'

**What did you expect to see?**
When I execute 'http_requests_total', it should return http requests stats of my deployed pods. 

**What did you see instead? Under which circumstances?**
It only returned data of monitoring namespaces resources, not any stats for my deployed pods. 

**Environment**
Azure kubernetes Service (aks)
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Azure kubernetes Service (aks)

Do I have to expose http_requests_total from my applications (pods) using the Prometheus client library? Or is there any other way around?

**Comment by brancz** [comment]
The kube-prometheus stack is highly locked down to only monitor your Kubernetes cluster itself. You can modify this, however, common practice is to have a separate instance of Prometheus for application monitoring.

**Comment by mfaizanse** [comment]
@brancz Does kubernetes has any metrics for keeping track of http requests to pods?

**Comment by brancz** [comment]
Kubernetes is not aware of application level metrics, it only exposes metrics in the form of generic workload metrics: CPU, memory, network I/O, etc. Istio might at some point offer something like this. And you probably also want metrics from your Ingress.

**Comment by brancz** [comment]
I'll close this here, feel free to re-open or create a new issue, if your problem has not been resolved.

**Comment by AnkitVaidya01** [comment]
so can you please tell me how I will get my pods stats in http_requests_total? do I have to deploy prometheus in my application namespace? @brancz @mfaizanse

**Comment by brancz** [comment]
@AnkitVaidya01 yes, the idea is that you deploy a separate Prometheus server for application monitoring purposes.

**Comment by mfaizanse** [comment]
@brancz  What did you meant when you said that "common practice is to have a separate instance of Prometheus for application monitoring."? Do you mean that deploy a separate Prometheus server apart from Prometheus-operator? Or we can ask the Prometheus-operator to create a new instance of Prometheus which we can use with ServiceMonitors to monitor our applications? If yes, can share any guide or video explaining this in detail?

**Comment by brancz** [comment]
Yes, that's what the Prometheus Operator is all about :slightly_smiling_face: . Our getting started guide takes you through this: https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html

**Comment by sreedharbukya** [comment]
@brancz , Please can give me configuration files which can help me create. I do not want to create another Prometheus server, but instead of I would love to use existing Prometheus operator but using servicemonitor

**Comment by brancz** [comment]
This has changed in the meantime and the prometheus operator can discover servicemonitor objects across namespaces, so this is perfectly possible now. Check out the kube prometheus docs on how to do this.

**Comment by Tejeev** [comment]
@brancz are you able to please provide links to the resources or more information on how to actually get the metric from custom pods or what versions the above referenced changes were merged in on?  It would be very helpful and this conversation appears to be circular with many people, including myself, not knowing what you are actually alluding to.

**Comment by Tejeev** [comment]
@mfaizanse you can not deploy multiple prometheus-operators in a single environment.  I think brancz may be saying to deploy another copy of prometheus with prometheus-operator disabled.  This can be done by adding the following to the answers file of a prometheus helm chart:
```
prometheus-operator:
  enabled: false
```

I'm not yet sure how to broaden the scope of permissions for scraping or in what version of Prometheus this has been done

**Comment by Tejeev** [comment]
For future searchers, in retrospect, on a reread, it is clear now:
brancz was saying that the metric `http_requests_total` is not one commonly exposed by Kubernetes pods.  If your custom workload _does_ expose it but happens to be in a separate namespace from the Prometheus server there may be difficulty scraping this metric, though there may or may not be a PR out there that opened Prometheus Pod restrictions up a bit so that this is no longer the case(?).  I believe he was alluding to the fact that the Operator is used to deploy the actual server and other related resources.  You can only have one Operator in a cluster.  You would modify the Operator's configs so that it would then deploy more instances of Prometheus for different namespaces (if this is still required).

Unfortunately my focus is not so deep so I have not had time to dig up the docs or I would link them for you here.  Take my above explenation with a grain of salt but it's the most sense I can make of brancz's posts in passing.  

Hope it helps :)

**Comment by diegocejasprieto** [comment]
Hello, where's the documentation to scrape network requests from custom app pods? Cannot find it anywhere
