### ISSUE TITLE
Adding custom dashboard instructions for tectonic-installer

### ISSUE THREAD

**Issue by hacor** [coreos/prometheus-operator#772]
**What did you do?**
I have a running bare-metal setup using the Tectonic-installer and a working Prometheus operator and dashboards. I'm using [rook.io](rook.io) for storage and I wanted to add these to the existing monitoring cluster.
I created a working `ServiceMonitor` object and the Ceph cluster parameters appear in the Prometheus webpage and the data can be accessed.

I wanted to add the [ceph-cluster dashboard](https://grafana.com/dashboards/917) to the Prometheus operator dashboards. I first tried to add it from the UI to test if it could find all the data and it could. It worked perfectly. Then to permanently add the dashboard to my setup:

```
kubectl -n tectonic-system get configmap/grafana-dashboards -o yaml
```

I opened the file and added `ceph-cluster-dashboard.json` part:

```yaml
apiVersion: v1
data:
  deployment-dashboard.json: ...
  kubernetes-capacity-planing-dashboard.json: ...
  kubernetes-cluster-health-dashboard.json: ...
  kubernetes-cluster-status-dashboard.json: ...
  kubernetes-control-plane-status-dashboard.json: ...
  kubernetes-resource-requests-dashboard.json: ...
  nodes-dashboard.json: ...
  pods-dashboard.json: ...
  prometheus-datasource.json: ...
  ceph-cluster-dashboard.json: |
    {
      "dashboard": {
          HERE-THE-CONTENTS-FROM-THE-DASHBOARD-JSON-ON-THE-GRAFANA-WEBSITE
      },
      "inputs": [
        {
          "name": "DS_PROMETHEUS",
          "pluginId": "prometheus",
          "type": "datasource",
          "value": "prometheus"
        }
      ],
      "overwrite": true
    }
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: tectonic-system
```
After this I save the file and re-apply:

```
kubectl apply -f grafana-dashboards.yaml
```

**What did you expect to see?**
I hoped the ceph-cluster-dashboard.json to be added permanently to my setup. But as you can see in the log file of the `grafana-watcher` container, it seems to be automatically overwritten again to the old setup a minute later. No other log files leave me a clue.

**What did you see instead? Under which circumstances?**
The `grafana-watcher` changed the configuration back a minute later.
I read on several Github issues ([kube-prometheus repo](https://github.com/coreos/kube-prometheus/issues/41), [issue on the Prometheus-operator repo](https://github.com/coreos/prometheus-operator/pull/621)) that it should be possible by running a script from the Prometheus-operator repo. [This](https://github.com/coreos/prometheus-operator/issues/649#issuecomment-332782407) comment says how to do it, but I'm curious how to run this script from a running Tectonic installation.
Do I need to clone the Prometheus-operator repo and run the `make generate` or is this script somewhere available in my installation (in a container, in the installer assets,...)?

**Environment**
Tectonic release: v1.7.5+coreos.1
Kubernetes release: v1.7.5+coreos.1
Prometheus operator: quay.io/coreos/prometheus-operator:v0.12.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5+coreos.1", GitCommit:"070d238cd2ec359928548e486a9171b498573181", GitTreeState:"clean", BuildDate:"2017-09-25T20:07:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

Tectonic-installer

* Manifests:
All the manifests are standard.

* Prometheus Operator Logs:
```
2017/11/20 16:09:39 ConfigMap modified
2017/11/20 16:09:39 Retrieving existing dashboards
2017/11/20 16:09:39 Deleting 8 dashboards
2017/11/20 16:09:39 Deleting dashboard: deployment
2017/11/20 16:09:39 Deleting dashboard: kubernetes-capacity-planing
2017/11/20 16:09:39 Deleting dashboard: kubernetes-cluster-health
2017/11/20 16:09:39 Deleting dashboard: kubernetes-cluster-status
2017/11/20 16:09:40 Deleting dashboard: kubernetes-control-plane-status
2017/11/20 16:09:40 Deleting dashboard: kubernetes-resource-requests
2017/11/20 16:09:40 Deleting dashboard: nodes
2017/11/20 16:09:40 Deleting dashboard: pods
2017/11/20 16:09:40 Creating dashboard from: /var/grafana-dashboards/ceph-cluster-dashboard.json
2017/11/20 16:09:41 Creating dashboard from: /var/grafana-dashboards/deployment-dashboard.json
2017/11/20 16:09:41 Creating dashboard from: /var/grafana-dashboards/kubernetes-capacity-planing-dashboard.json
2017/11/20 16:09:41 Creating dashboard from: /var/grafana-dashboards/kubernetes-cluster-health-dashboard.json
2017/11/20 16:09:41 Creating dashboard from: /var/grafana-dashboards/kubernetes-cluster-status-dashboard.json
2017/11/20 16:09:42 Creating dashboard from: /var/grafana-dashboards/kubernetes-control-plane-status-dashboard.json
2017/11/20 16:09:42 Creating dashboard from: /var/grafana-dashboards/kubernetes-resource-requests-dashboard.json
2017/11/20 16:09:42 Creating dashboard from: /var/grafana-dashboards/nodes-dashboard.json
2017/11/20 16:09:42 Creating dashboard from: /var/grafana-dashboards/pods-dashboard.json
2017/11/20 16:09:42 Retrieving existing datasources
2017/11/20 16:09:43 Deleting 1 datasources
2017/11/20 16:09:43 Deleting datasource: prometheus
2017/11/20 16:09:43 Creating datasource from: /var/grafana-dashboards/prometheus-datasource.json
2017/11/20 16:10:41 ConfigMap modified
2017/11/20 16:10:41 Retrieving existing dashboards
2017/11/20 16:10:41 Deleting 9 dashboards
2017/11/20 16:10:41 Deleting dashboard: ceph-cluster
2017/11/20 16:10:41 Deleting dashboard: deployment
2017/11/20 16:10:41 Deleting dashboard: kubernetes-capacity-planing
2017/11/20 16:10:42 Deleting dashboard: kubernetes-cluster-health
2017/11/20 16:10:42 Deleting dashboard: kubernetes-cluster-status
2017/11/20 16:10:42 Deleting dashboard: kubernetes-control-plane-status
2017/11/20 16:10:42 Deleting dashboard: kubernetes-resource-requests
2017/11/20 16:10:42 Deleting dashboard: nodes
2017/11/20 16:10:43 Deleting dashboard: pods
2017/11/20 16:10:43 Creating dashboard from: /var/grafana-dashboards/deployment-dashboard.json
2017/11/20 16:10:43 Creating dashboard from: /var/grafana-dashboards/kubernetes-capacity-planing-dashboard.json
2017/11/20 16:10:43 Creating dashboard from: /var/grafana-dashboards/kubernetes-cluster-health-dashboard.json
2017/11/20 16:10:44 Creating dashboard from: /var/grafana-dashboards/kubernetes-cluster-status-dashboard.json
2017/11/20 16:10:44 Creating dashboard from: /var/grafana-dashboards/kubernetes-control-plane-status-dashboard.json
2017/11/20 16:10:44 Creating dashboard from: /var/grafana-dashboards/kubernetes-resource-requests-dashboard.json
2017/11/20 16:10:44 Creating dashboard from: /var/grafana-dashboards/nodes-dashboard.json
2017/11/20 16:10:44 Creating dashboard from: /var/grafana-dashboards/pods-dashboard.json
2017/11/20 16:10:45 Retrieving existing datasources
2017/11/20 16:10:45 Deleting 1 datasources
2017/11/20 16:10:45 Deleting datasource: prometheus
2017/11/20 16:10:45 Creating datasource from: /var/grafana-dashboards/prometheus-datasource.json
```

**Comment by brancz** [comment]
This is intended behavior in Tectonic. The Tectonic Monitoring stack is managed by us, this includes the alerting rules, dashboards, etc. In order for us to be able have any guarantee around working automated updates. Some things are configurable, those are documented [here](https://coreos.com/tectonic/docs/latest/tectonic-prometheus-operator/user-guides/configuring-tectonic-monitoring.html).

For additional Grafana dashboards, and monitoring targets, we recommend creating separate Grafana and Prometheus instances, that can then be fully managed by you.

**Comment by brancz** [comment]
As an additional explanation. The kube-prometheus stack is very bare bone, for open source users it's meant to be taken and adapted as one needs. It is far from a production ready setup. In Tectonic we make it production ready as we can make assumptions around authentication, ssl, Ingress, and more as well as plug things together with the Tectonic console and other Tectonic components.

**Comment by hacor** [comment]
@brancz This is a very clear explanation. I will create my own Grafana/Prometheus instances.

Thanks!
Best regards!
