### ISSUE TITLE
Problem with load alerts rules to Prometheus

### ISSUE THREAD

**Issue by cleberwarmling** [coreos/prometheus-operator#785]
**What did you do?**

Deployed kube-prometheus using `./hack/cluster-monitoring/self-hosted-deploy`

**What did you expect to see?**

Grafana, Alertmanager and Prometheus with alert rules from https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml

**What did you see instead? Under which circumstances?**

Everything works fine except Prometheus that didn't load alert rules. I saw an error on prometheus-config-reloader `ts=2017-11-26T16:03:50Z caller=main.go:207 component=volume-watcher msg="Updating rule files failed." err="decode error status: payload is not a kubernetes protobuf object"` but I can't figure out why it is appearing. I already tried to re-checkout the repository and not luck yet. 

The only things that I did is to include an Ingress manifest to Prometheus (that's working fine) and edit `alertmanager-config.yaml` to include my Slack configuration (also working fine). Everything else is identical to the master branch.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:44:37Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
```
KOPS on AWS with RBAC enabled
```

* Prometheus Config Reload Logs:

```
ts=2017-11-26T16:03:50Z caller=main.go:231 component=volume-watcher msg=Starting...
ts=2017-11-26T16:03:50Z caller=main.go:204 component=volume-watcher msg="Updating rule files..."
ts=2017-11-26T16:03:50Z caller=main.go:207 component=volume-watcher msg="Updating rule files failed." err="decode error status: payload is not a kubernetes protobuf object"
ts=2017-11-26T16:03:50Z caller=main.go:212 component=volume-watcher msg="Reloading Prometheus..."
ts=2017-11-26T16:03:54Z caller=main.go:219 component=volume-watcher msg="Prometheus successfully reloaded."
```
 * Resources at Monitoring namespace

```
kubectl get all -n monitoring                                                                                                     
NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/grafana               1         1         1            1           3m
deploy/kube-state-metrics    1         1         1            1           3m
deploy/prometheus-operator   1         1         1            1           3m

NAME                                DESIRED   CURRENT   READY     AGE
rs/grafana-2315080943               1         1         1         3m
rs/kube-state-metrics-3281504101    0         0         0         3m
rs/kube-state-metrics-599741161     1         1         1         3m
rs/prometheus-operator-2365681585   1         1         1         3m

NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/grafana               1         1         1            1           3m
deploy/kube-state-metrics    1         1         1            1           3m
deploy/prometheus-operator   1         1         1            1           3m

NAME                             DESIRED   CURRENT   AGE
statefulsets/alertmanager-main   1         1         2m
statefulsets/prometheus-k8s      2         2         2m

NAME                                      READY     STATUS    RESTARTS   AGE
po/alertmanager-main-0                    2/2       Running   0          2m
po/grafana-2315080943-2x3zp               2/2       Running   0          3m
po/kube-state-metrics-599741161-vxlpq     2/2       Running   0          3m
po/node-exporter-lm5l1                    1/1       Running   0          3m
po/node-exporter-vn55p                    1/1       Running   0          3m
po/prometheus-k8s-0                       2/2       Running   0          2m
po/prometheus-k8s-1                       2/2       Running   0          2m
po/prometheus-operator-2365681585-6h7s8   1/1       Running   0          3m
```

**Comment by cleberwarmling** [comment]
I think that I figured out what is happening.

On kube-api log I saw this HTTP 403:

```
I1126 16:50:47.275446       5 wrap.go:42] GET /api/v1/namespaces/monitoring/configmaps/prometheus-k8s-rules: (1.207172ms) 403 [[Go-http-client/2.0] 10.10.23.100:34166]
I1126 16:50:47.375893       5 wrap.go:42] GET /api/v1/namespaces/monitoring/configmaps/prometheus-k8s-rules: (1.41864ms) 403 [[Go-http-client/2.0] 10.10.23.100:47580]
```

So, I checked every Role and Rolebinding I conclude that everithing is correct. Then, I tried to "force a  restart" to Prometheus pods `k delete pod Prometheus-k8s-0 -n monitoring and surprisingly  the config-reloader was able to load the rule file. 

```
k logs -f prometheus-k8s-0 prometheus-config-reloader -n monitoring                                                                
ts=2017-11-26T17:17:19Z caller=main.go:231 component=volume-watcher msg=Starting...
ts=2017-11-26T17:17:19Z caller=main.go:204 component=volume-watcher msg="Updating rule files..."
ts=2017-11-26T17:17:19Z caller=main.go:209 component=volume-watcher msg="Rule files updated."
```

So I think that is something related to the creating order maybe 🤔 

Any ideas? 

PS: I'm new to the project and I swear that I'll study how all components works and reread the docs. 'Cause I think that I maybe be missing something and so this happened.

**Comment by brancz** [comment]
I'm unsure I understand from your last comment whether your situation is fixed or still a problem?

There is certainly the possibility for timing issues where the roles the prometheus pod has were granted after the prometheus-config-reloader started.

This

```
decode error status: payload is not a kubernetes protobuf object
```

is a known issue of the kubernetes client we're using in the project, which occurs when there is an error (as the Kubernetes API encodes errors as json even when protobuf is requested), typically in our case RBAC related, as you have already figured out from your logs.

**Comment by cleberwarmling** [comment]
@brancz I think we can call this solved based on what you provided. Btw, thanks a lot for your help 😄

**Comment by brancz** [comment]
Always happy to help. Feel free to open issues when you run into anything, if not a problem in code it usually means docs are not good enough :)
