### ISSUE TITLE
Exposing /metrics endpoint to public facing Service?

### ISSUE THREAD

**Issue by neuromantik33** [coreos/prometheus-operator#800]
I'm sorry to be asking this here but I've searched everywhere but I can't find a working solution.
So after successfully installing prometheus operator and all associated apps/services I have a security problem with the /metrics route exposed within my app.

At first I had a public `LoadBalancer` (it's a web tracker) with a public IP but then I noticed that the `/metrics` endpoint was exposed which is kind of unacceptable. Afterwards I changed the service type to `NodePort` and attempted to create an `Ingress` resource but I can't seem to figure out how to disallow/filter/blacklist the /metrics route on my monitored application.

Again sorry for the question as it is more of a Prometheus on Kubernetes one and not specifically a prometheus-operator one but any help is much appreciated.

Thanks in advance

**Comment by brancz** [comment]
Common approaches:

1) Have the metrics on a separate port, that is not exposed via Ingress
2) AuthN & AuthZ
3) Deny access to the `/metrics` path (https://github.com/nginxinc/kubernetes-ingress/issues/161)

**Comment by neuromantik33** [comment]
Option 3 finally worked! A bit of a hassle though, as I only have one service behind the `Ingress` resource. I'll need to look at option 2. Thanks!

**Comment by brancz** [comment]
AuthN & AuthZ is often achieved with mTLS.

**Comment by lboix** [comment]
@neuromantik33 @brancz I tried option 3 at the Ingress Controller specification and it worked well, thanks for your help 👍 

```kind: ConfigMap
apiVersion: v1
...
data:
  ...
  server-snippet: |
    location /metrics {
      return 403;
    }
---
apiVersion: apps/v1
kind: Deployment
...
---
kind: Service
apiVersion: v1
...```
