### ISSUE TITLE
how to monitor kube-router 

### ISSUE THREAD

**Issue by huyipow** [coreos/prometheus-operator#801]
I'm going to use prometheus-operator to monitor kube-router. Whether prometheus-operator supports monitoring kube-router? if kube-router has a metrics port to be monitored for monitoring?

**Comment by brancz** [comment]
kube-router can be deployed like any other workload as a DaemonSet` on Kubernetes, so you just need to put a `Service` in front of it, and discover them like any other targets with the Prometheus Operator :)

**Comment by huyipow** [comment]
Kube-router has been deployed in a Daemonset manner. 
```cat kube-router-svc.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-router-prometheus-discovery
  labels:
    k8s-app: kube-router
spec:
  selector:
    k8s-app: kube-router
  type: ClusterIP
  clusterIP: None
  ports:
  - name: bgp-metrics
    port: 179
    targetPort: 179
    protocol: TCP
  - name: grpc-metrics
    port: 50051
    targetPort: 50051
    protocol: TCP
```
I tried to ask kuber-router's metrics to return the result to fail
```
curl http://10.18.19.143:50051/metrics
curl: (56) Recv failure: Connection reset by peer
curl http://10.18.19.143:179/metrics
curl: (56) Recv failure: Connection reset by peer`

**Comment by gianrubio** [comment]
I'm not familiar with kube-router but looking to [the code](https://github.com/cloudnativelabs/kube-router/blob/75bdfa2a10ba995062f084924b73764290601c23/app/controllers/network_services_controller.go#L141) I saw that prometheus is exposed on port :8080.

**Comment by brancz** [comment]
You need to first make sure that you can find your metrics exposed by your application, there can be many different things why this is the case, but unrelated to the Prometheus Operator. I will close this issue here. Feel free to re-open, once you can reach your metrics endpoint, but the target still doesn't show up in Prometheus.
