### ISSUE TITLE
Need instructions on adding new dashboards to grafana on tectonic

### ISSUE THREAD

**Issue by harsh-px** [coreos/prometheus-operator#802]
**What did you do?**
I'm running Tectonic 1.7.9 which ships with Prometheus and Grafana managed by the prometheus-operator.

1. I downloaded the existing `grafana-dashboards` config map. 
2. Updated the `data` section and added a new dashboard.
3. Delete existing config map: `kubectl delete -f configmap-grafana-dashboards.yaml`
4. Apply new config map with added dashboards `kubectl apply -f configmap-grafana-dashboards.yaml`

**What did you expect to see?**
The `grafana-dashboards` config map should have been updated with my new dashboards.

**What did you see instead? Under which circumstances?**
The `grafana-dashboards` config map was reset to the default data.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9+coreos.0", GitCommit:"2ded8a1912d014561208d882cfcc12dfa5374f22", GitTreeState:"clean", BuildDate:"2017-10-24T13:07:42Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
	tectonic-installer on AWS

* Manifests:
Below is the updated config map which I was applying. It was correct syntactically since kubectl apply accepted it.

[configmap-grafana-dashboards.txt](https://github.com/coreos/prometheus-operator/files/1533532/configmap-grafana-dashboards.txt)

* Prometheus Operator Logs:

Below are the operator logs but these may have rolled over and I didn't find any useful reference to grafana-dashboard here (apart from `operator.go:127] AppVersion (tectonic-system/grafana-dashboards) not monitoring related`.)

[prometheus-operator.log](https://github.com/coreos/prometheus-operator/files/1533524/prometheus-operator.log)

**Comment by brancz** [comment]
The Grafana instance shipped as part of the Tectonic Monitoring stack is effectively immutable. Tectonic will always override changes you make. We do this as otherwise we cannot guarantee consistent reliable upgrades. For additional dashboards, you will need to deploy an additional Grafana instance.

**Comment by harsh-px** [comment]
Thanks for the quick reply.

Is the same true for the `prometheus-k8s-rules` config map used by the prometheus operator to get the alerting rules?

So based on your comment, is the recommendation to deploy an entire new stack i.e 1) `kind: Prometheus` object 2) Grafana `Deployment` 3) `kind: AlertManager` object?

**Comment by brancz** [comment]
Exactly :slightly_smiling_face:

**Comment by harsh-px** [comment]
Thank you for the help!

At some point in future, it will be really useful to use the same instances to add more rules and dashboards. Many end users I talk to find it useful to just have to manage a single instance.
