### ISSUE TITLE
Operator Pod not triggering rest of deployment

### ISSUE THREAD

**Issue by snoby** [coreos/prometheus-operator#810]
**What did you do?**
Created a single node cluster with kubeadm, installed calico network overlay then cloned coreos/prometheus-operator repo and ran `kubectl apply -f bundle.yaml`

**What did you expect to see?**
I expected to see the operator pod get installed along with running prometheus, alertmanager and grafana
**What did you see instead? Under which circumstances?**
I see the operator pod get started with no errors and just reports this to the logs then nothing happens:
```
ts=2017-12-10T02:34:00Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.8.4
ts=2017-12-10T02:34:00Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.8.4
ts=2017-12-10T02:34:00Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2017-12-10T02:34:00Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
```
**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	single cluster kubeadm with taint removed so that i can run workloads on single node.
I should mention that i have run the operator "hack" directory method to start and run operator in minikube.  Minikube that is bootstrapped with kubeadm.  I just don't have any logs or any errors telling me why nothing is getting kicked off.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
```
ts=2017-12-10T02:34:00Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.8.4
ts=2017-12-10T02:34:00Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.8.4
ts=2017-12-10T02:34:00Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2017-12-10T02:34:00Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
```

**Comment by brancz** [comment]
I'm confused with the description of what you did. Did you do `kubectl apply -f bundle.yaml` or run the scripts in `contrib/kube-prometheus/hack` to deploy the entire stack?

The contents of `bundle.yaml` only start the Prometheus Operator, nothing else. If you want the entire stack that includes the Prometheus instances, Alertmanager cluster, grafana, etc then have a look at the `contrib/kube-prometheus` directory/sub-project.

**Comment by snoby** [comment]
Ah I see now, I didn't understand from the talks at KubeCon and from looking at the README that the additional steps were necessary.  However after seeing everything now I understand the process. Thank you!
