### ISSUE TITLE
Central Prometheus to query 2 different k8s clusters

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#815]
Hey Prometheus Operators,

Quick question: Is there a recommended way to use 1 central Prometheus to aggregate and query the metrics normally found by querying 2 different Prometheus instances in 2 different Kubernetes clusters in 2 different data centers?

If there is, I would love to get some tips on the best way to go about this.

Thank you!

**Comment by brancz** [comment]
This is generally a question that is worth asking the larger Prometheus community, as it's not really specific to the Prometheus Operator. (https://groups.google.com/forum/#!forum/prometheus-users)

If not absolutely necessary I would actually just keep the instances apart, and just make each of them send their alerts to a single, organization wide Alertmanager cluster. This also still allows you to create dashboards with multiple datasources, one per cluster.

If you absolutely need all data from all Prometheus servers in one, then [federation](https://prometheus.io/docs/prometheus/latest/federation/) is the answer. If possible I try to stay away from federation though, as it makes the setup often more complex where it doesn't need to be.

**Comment by nuala33** [comment]
Thanks, @brancz!

**Comment by brancz** [comment]
Closing this here, but let me know if there is anything else :slightly_smiling_face: .
