### ISSUE TITLE
Monitoring custom services guide in kube-prometheus doesn't add example-app to targets

### ISSUE THREAD

**Issue by stphivos** [coreos/prometheus-operator#817]
**What did you do?**
Created a local kubernetes cluster using `minikube`. From `contrib/kube-prometheus`, I installed monitoring using `hack/cluster-monitoring/deploy` and deployed the example-app using `hack/example-service-monitoring/deploy`.

**What did you expect to see?**
I expected to see the example-app in the list of prometheus targets at `http://192.168.99.100:30900/targets` as shown in this [screenshot](https://coreos.com/sites/default/files/inline-images/p2.png).

**What did you see instead? Under which circumstances?**
The only targets registered were:
* alertmanager-main (3/3 up)
* apiserver (1/1 up)
* kube-state-metrics (1/1 up)
* kubelet (2/2 up)
* node-exporter (1/1 up)
* prometheus-k8s (2/2 up)
* prometheus-operator (1/1 up)

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:27:47Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

```
minikube version: v0.24.1
```

* Manifests:

[Manifests](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/examples/example-app) used by `hack/example-service-monitoring/deploy`.

* Prometheus Operator Logs:

```
...
ts=2017-12-13T19:33:55Z caller=operator.go:327 component=prometheusoperator msg="Prometheus updated" key=default/frontend
ts=2017-12-13T19:33:55Z caller=operator.go:327 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2017-12-13T19:33:55Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/frontend
ts=2017-12-13T19:33:55Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:33:55Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-13T19:33:55Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:34:40Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-13T19:34:40Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:34:40Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/frontend
ts=2017-12-13T19:34:40Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:34:40Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-13T19:34:40Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:34:50Z caller=operator.go:323 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2017-12-13T19:34:50Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2017-12-13T19:35:11Z caller=operator.go:327 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2017-12-13T19:35:11Z caller=operator.go:327 component=prometheusoperator msg="Prometheus updated" key=default/frontend
ts=2017-12-13T19:35:11Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-13T19:35:11Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-13T19:35:11Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/frontend
ts=2017-12-13T19:35:11Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
...
```

**Comment by brancz** [comment]
Note, that these are two separate sets of Prometheus servers, one for cluster monitoring and one specifically for application monitoring. This is a common practice of how people run their Prometheus monitoring infrastructure.

The Prometheus server for application monitoring should be available under the `30100` port. With the `hack/example-service-monitoring/deploy` script.

**Comment by amir-hadi** [comment]
Hi @brancz,

is this still the case? To me it looks like that it was removed, because I don't have a second instance of prometheus running.

Also would this second instance be defined as source in Grafana?

Note: I am new to this deployment and Prometheus in general.

**Comment by brancz** [comment]
@amir-hadi only the cluster monitoring hack script was removed as it's now a simple `kubectl create -f manifests/` to create and `kubectl delete -f manifests/` to teardown the stack. Eventually this will happen with the remaining manifests as well, but as of now the example-service-monitoring scripts still exist.
