### ISSUE TITLE
k8s.io cache cannot find the "namespace" Indexer at master branch

### ISSUE THREAD

**Issue by mmerrill3** [coreos/prometheus-operator#823]
**What did you do?**
Built from the master branch and installed in my dev environment
**What did you expect to see?**
Normal operations
**What did you see instead? Under which circumstances?**
In the log file, I see this consistently, which means that the Indexer for the namespace cache is missing

ERROR: logging before flag.Parse: W1214 18:26:12.791794       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
ERROR: logging before flag.Parse: W1214 18:26:12.791965       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist

**Environment**
Kubernetes
* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:12:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	Cluster runnning on AWS through kops

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
this just repeats:

ts=2017-12-14T18:25:46.83198663Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=dev-monitoring/prometheus
ts=2017-12-14T18:25:46.937541708Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-14T18:26:12.790914215Z caller=operator.go:327 component=prometheusoperator msg="Prometheus updated" key=dev-monitoring/prometheus
ERROR: logging before flag.Parse: W1214 18:26:12.791794       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
ERROR: logging before flag.Parse: W1214 18:26:12.791965       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
ts=2017-12-14T18:26:12.791712411Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=dev-monitoring/prometheus
ts=2017-12-14T18:26:12.84456898Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-12-14T18:26:53.871210884Z caller=operator.go:323 component=alertmanageroperator msg="Alertmanager updated" key=dev-monitoring/main
ts=2017-12-14T18:26:53.871363536Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=dev-monitoring/main
ERROR: logging before flag.Parse: W1214 18:26:59.634235       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
ts=2017-12-14T18:26:59.634050115Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=dev-monitoring/prometheus
ERROR: logging before flag.Parse: W1214 18:26:59.635236       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
ts=2017-12-14T18:26:59.670662285Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Thanks for reporting, we will have to look into this.

**Comment by mmerrill3** [comment]
Hi @brancz, we could use CommandLine instance of a flagset from the flag package, which is what glog checks when it sees if the command line has been parsed.  Glog is used b/c of the k8s client.

As opposed to creating a new flag set in main.go, just use the one from the flag package that's already there.  That's a simple enough change, and "should" stop the stderr messages in the log from glog.

**Comment by brancz** [comment]
:man_facepalming: I think you're right. Do you want to create the PR to fix this?

**Comment by mmerrill3** [comment]
@brancz, sure, I'll run my changes locally today.

**Comment by mmerrill3** [comment]
Opened https://github.com/coreos/prometheus-operator/pull/849

**Comment by prune998** [comment]
@mmerrill3 I've deployed the 0.22.2 version (then upgraded to `master` docker image) and I do see the same exact log.

I've deployed using the Ksonnet/Jsonnet scripts

**Comment by brancz** [comment]
@prune998 could you open a new issue with all your details and the exact SHA of the image you ran? That would be highly appreciated! Thanks! :slightly_smiling_face:

**Comment by prune998** [comment]
@brancz it's done in https://github.com/coreos/prometheus-operator/issues/1694
