### ISSUE TITLE
No Datapoints Found in Prometheus using release-0.15 + K8s 1.8.2

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#825]
**What did you do?**
     Deploy the script hack/cluster-monitoring/deploy to K8s 1.8.2

**What did you expect to see?**
     Metrics like Nodes datapoints in Prometheus page or grafana dashboard

**What did you see instead? Under which circumstances?**
    No datapoints found.  Tested the prometheus datasource and is working correctly

**Environment**
 
* Kubernetes version information:

	  Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
      Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	  kubeadm

* Manifests:

```
      alertmanager, grafana, kube-state-metrics, node-exporter, prometheus-operator, prometheus
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
      W1214 13:24:30.558184       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
      W1214 13:25:43.353196       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist
      W1214 13:25:43.353234       1 listers.go:63] can not retrieve list of objects using index : Index with name namespace does not exist

**Comment by brancz** [comment]
can you share what you solution was?
