### ISSUE TITLE
How to update rules content in deployed prometheus helm chart ?

### ISSUE THREAD

**Issue by theogq** [coreos/prometheus-operator#833]
**What did you do?**
I set the (Recording) rules in values.yaml 

I deployed Prometheus helm chart from 
https://github.com/coreos/prometheus-operator/tree/master/helm/prometheus
When I go to gui under `/rules`, I can see the rules that I have set.

Now I want to change some values in `etcd.rules.yml`.
I can edit configmap with
`kubectl get configmap prometheus-<NAME>-rules -oyaml > configmap.yaml`
`kubectl replace -f configmap.yaml`

I can see the prometheus-<NAME>-rules configmap changed, but the rules are not changing when I go to gui under `/rules`. 

Is there a way to change the rules? 

**Environment**

* Kubernetes version information:

```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:26:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```



https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/_configmaps.json.tpl
```
{ "items": [
{{- if and .Values.rules.specifiedInValues .Values.rules.value }}
  {
    "key": "{{ .Release.Namespace }}/prometheus-{{ .Release.Name }}-rules",
    "checksum": "0000000000000000000000000000000000000000000000000000000000000000"
  }
{{- end }}
]}
```

https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/rules.yaml
```
{{- if and .Values.rules.specifiedInValues .Values.rules.value }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- if .Values.rulesSelector }}
{{ toYaml .Values.rulesSelector | indent 4 }}
    {{- end }}
  name: prometheus-{{ .Release.Name }}-rules
data:
{{ toYaml .Values.rules.value | indent 2 }}
{{- end }}
```
https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/secret.yaml
```
{{- if and (and .Values.config.specifiedInValues .Values.config.value ) ( not .Values.serviceMonitorSelector ) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
  name: prometheus-{{ .Release.Name }}
data:
  configmaps.json: {{ include (print  (dir $.Template.Name) "/_configmaps.json.tpl") . | b64enc | quote }}
  prometheus.yaml: {{ toYaml .Values.config.value | b64enc | quote }}
{{- end }}
```

**Comment by brancz** [comment]
The charts are in some ways (like this) in a somewhat rough shape, which is why they are in pre-alpha stage. All rules should in my opinion should simply be a value passed to the kube-prometheus stack, instead of a hardcoded configmap.

/cc @gianrubio 

Related to #592

**Comment by harbesc** [comment]
It is possible to work around this by (1) making changes to the config map and then (2) deleting the exporter-node pods. The pods will automatically be recreated by the daemonset with the updated rules. 

Although after stumbling upon this issue I agree it'd be wonderful for folks to be able to pass their own rules to kube-prometheus while also still using the defaults.

**Comment by gianrubio** [comment]
@theogq there's some changes on the helm charts after this issue was opened. I followed your steps to edit the configmap and I can see the changes were applied to my prometheus. I'll close this issue for now once it was fixed, feel free to reopen.

```
...
ts=2018-02-02T08:40:50Z caller=main.go:219 component=volume-watcher msg="Prometheus successfully reloaded."
...
``` 



@harbesc I'm not sure if I understood what you mean but all the charts has the ability to customize rules.
For instance you can customize kube-promethues [here](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/templates/configmap.yaml#L13) or kube-etc [here](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/configmap.yaml#L13)
