### ISSUE TITLE
Helm install fail due to missing CustomeResourceDefinition

### ISSUE THREAD

**Issue by luisyonaldo** [coreos/prometheus-operator#846]
**What did you do?**

``` helm install helm/kube-prometheus```

**What did you expect to see?**

Install `kube-prometheus` dependencies (`prometheus`, `prometheus-operator`, etc..).

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	minikube

* Helm Logs:

```
helm install helm/kube-prometheus/
Error: apiVersion "monitoring.coreos.com/v1" in kube-prometheus/charts/exporter-kube-scheduler/templates/servicemonitor.yaml is not available
```

As far as I know, to fix this you can add a pre-install hook to the `CustomeResourceDefinition` or define it in a different chart but I can't see any deffiniton of the CRD object in the repo. I can only see `get-crd-job.yaml` which only do
```
kubectl get crd alertmanagers.monitoring.coreos.com prometheuses.monitoring.coreos.com servicemonitors.monitoring.coreos.com
```

**Comment by gianrubio** [comment]
Prometheus-operator is not a dependency for kube-prometheus, you should install prometheus-operator before installing kube-prometheus. We're missing a README form kube-prometheus, and we been working to have a better helm charts, this issue is already mapped on https://github.com/coreos/prometheus-operator/issues/592

**Comment by luisyonaldo** [comment]
but it is a dependencies according to `requirements.yaml`, isn't it? @gianrubio

**Comment by gianrubio** [comment]
hum...it's a mistake in the requirements [that will be fixed](https://github.com/gianrubio/prometheus-operator/blob/59421f7018bbeaabbec27631d882b6a7ab521a1d/helm/kube-prometheus/requirements.yaml#L63) on #592. 

Could you try to install prometheus-operator before installing kube-prometheus?

**Comment by luisyonaldo** [comment]
yes if you do it like that it works, just didn't get why if it is a dependency (so helm will try to install it before running the `kube-prometheus` chart) it fails if you haven't installed `prometheus-operator` chart yet.

**Comment by gianrubio** [comment]
> ... , just didn't get why if it is a dependency 

It's a race condition, kube-prometheus need the `crd` that is going to be created by prometheus-operator, because takes few seconds to create the crd kube-prometheus fails.
