### ISSUE TITLE
Support tmpfs as a storage option

### ISSUE THREAD

**Issue by crandles** [coreos/prometheus-operator#851]
Instead of defaulting to emptydir volumes, I'd like to use a tmpfs volume. Is this a change that would be accepted upstream?

This section would need to allow for the EmptyDir.Medium to be set to "Memory"
https://github.com/coreos/prometheus-operator/blob/281d3e7d5c26e72ad66871cee503bc183c1bc6a1/pkg/prometheus/statefulset.go#L137-L142

To support this, I think an additional configuration would need to be added to the PrometheusSpec. Open to suggestions or alternate solutions.

**Comment by brancz** [comment]
I would propose to add the `medium` and `sizeLimit` fields to the `StorageSpec`, then one can override the fields as wanted. Wdyt?

**Comment by crandles** [comment]
That sounds good. I'll have a PR ready for this soon.

**Comment by crandles** [comment]
Would it make sense to add a layer between StorageSpec & these emptyDir configurations?

```
storage:
  emptyDir:
    medium: Memory
    sizeLimit: 2Gi
```

I think it may make the documentation clearer if those values that only affect the emptyDir usage are not top-level, as right now anything related to the use of a volume is under `volumeClaimTemplate`

**Comment by brancz** [comment]
That sounds like a better idea, yes. Looking forward to the PR! :)
