### ISSUE TITLE
Prometheus pod failed to start with db "Locked by other process"

### ISSUE THREAD

**Issue by travisn** [coreos/prometheus-operator#854]
**What did you do?**
Prometheus was happily collecting metrics in the k8s cluster. There was a shutdown of a machine due to power outage. When the machine was brought back up, the prometheus pod failed to start. 

v0.14.1 of the prometheus operator was running.

**What did you expect to see?**
Expected prometheus to start up successfully again after the node restart.

**What did you see instead? Under which circumstances?**
The `prometheus-k8s-0` pod failed to start with a "Locked by other process" message. 

The following was found in its log.
```
level=info ts=2018-01-03T21:56:07.173825499Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"
level=info ts=2018-01-03T21:56:07.173871294Z caller=main.go:216 build_context="(go=go1.9.2, user=root@615b82cb36b6, date=20171108-07:11:59)"
level=info ts=2018-01-03T21:56:07.173888097Z caller=main.go:217 host_details="(Linux 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 prometheus-k8s-0 (none))"
level=info ts=2018-01-03T21:56:07.175870142Z caller=main.go:314 msg="Starting TSDB"
level=info ts=2018-01-03T21:56:07.175877793Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-01-03T21:56:07.175890242Z caller=targetmanager.go:71 component="target manager" msg="Starting target manager..."
level=error ts=2018-01-03T21:56:07.176126854Z caller=main.go:323 msg="Opening storage failed" err="open DB in /var/prometheus/data: Locked by other process"
```

This looks like the same root cause as this [prometheus issue](https://github.com/prometheus/prometheus/issues/2689). The only workarounds mentioned were to delete the `lock` file or else start the prometheus container with the parameter `--storage.tsdb.no-lockfile`

How can we recover from this issue? The prometheus pod needs to be able to start even though the lock file still exists from an unclean shutdown. Is there a better solution than passing the `no-lockfile` arg? Or how do we tell the prometheus operator to use that flag?

I was able to workaround this issue by adding the `no-lockfile` arg to the container args:
```
kubectl  delete deploy prometheus-operator
kubectl patch sts prometheus-k8s -p '{"spec":{"replicas":0}}'
kubectl edit sts prometheus-k8s
# Add the following argument to the prometheus container args
  - --storage.tsdb.no-lockfile
kubectl patch sts prometheus-k8s -p '{"spec":{"replicas":1}}'
```

Then I was able to connect to the container and delete the lockfile in /var/prometheus/data and restart the prometheus operator.

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
kubeadm

**Comment by brancz** [comment]
Thanks a lot for reporting! We seem to have missed to add that flag. I'll create a fix.

**Comment by diwakarpp** [comment]
hi, I have just deployed the latest TiDB today(20th Aug 2018) in our cluster. I am seeing this in the Prometheus log and its not starting up. I am not sure if this issue related to the above one or has recurred in the latest version. Could you pl confirm and suggest me a fix?

level=info ts=2018-08-20T13:26:57.272676241Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.1, branch=HEAD, revision=bc6058c81272a8d938c05e75607371284236aadc)"
level=info ts=2018-08-20T13:26:57.272719078Z caller=main.go:221 build_context="(go=go1.10, user=root@149e5b3f0829, date=20180314-14:15:45)"
level=info ts=2018-08-20T13:26:57.272732113Z caller=main.go:222 host_details="(Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 tlyuk3 (none))"
level=info ts=2018-08-20T13:26:57.272741842Z caller=main.go:223 fd_limits="(soft=1000000, hard=1000000)"
level=info ts=2018-08-20T13:26:57.274849599Z caller=web.go:382 component=web msg="Start listening for connections" address=:9090
level=info ts=2018-08-20T13:26:57.274812159Z caller=main.go:504 msg="Starting TSDB ..."
level=info ts=2018-08-20T13:26:57.275377658Z caller=main.go:398 msg="Stopping scrape discovery manager..."
level=info ts=2018-08-20T13:26:57.27540428Z caller=main.go:411 msg="Stopping notify discovery manager..."
level=info ts=2018-08-20T13:26:57.275416378Z caller=main.go:432 msg="Stopping scrape manager..."
level=info ts=2018-08-20T13:26:57.275435374Z caller=manager.go:460 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-08-20T13:26:57.275427416Z caller=main.go:394 msg="Scrape discovery manager stopped"
level=info ts=2018-08-20T13:26:57.275447659Z caller=manager.go:466 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-08-20T13:26:57.27545168Z caller=main.go:426 msg="Scrape manager stopped"
level=info ts=2018-08-20T13:26:57.275457946Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-08-20T13:26:57.275465096Z caller=main.go:407 msg="Notify discovery manager stopped"
level=info ts=2018-08-20T13:26:57.275471446Z caller=main.go:573 msg="Notifier manager stopped"
level=error ts=2018-08-20T13:26:57.27691684Z caller=main.go:582 err="Opening storage failed open DB in /home/tidb/deploy/prometheus2.0.0.data.metrics: Locked by other process"
level=info ts=2018-08-20T13:26:57.276949884Z caller=main.go:584 msg="See you next time!"
level=info ts=2018-08-20T13:27:12.523126812Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.1, branch=HEAD, revision=bc6058c81272a8d938c05e75607371284236aadc)"
level=info ts=2018-08-20T13:27:12.523175156Z caller=main.go:221 build_context="(go=go1.10, user=root@149e5b3f0829, date=20180314-14:15:45)"
level=info ts=2018-08-20T13:27:12.523188617Z caller=main.go:222 host_details="(Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 tlyuk3 (none))"
level=info ts=2018-08-20T13:27:12.523198563Z caller=main.go:223 fd_limits="(soft=1000000, hard=1000000)"
level=info ts=2018-08-20T13:27:12.524247793Z caller=main.go:504 msg="Starting TSDB ..."
level=info ts=2018-08-20T13:27:12.524287548Z caller=web.go:382 component=web msg="Start listening for connections" address=:9090
level=info ts=2018-08-20T13:27:12.524652316Z caller=main.go:398 msg="Stopping scrape discovery manager..."
level=info ts=2018-08-20T13:27:12.52466487Z caller=main.go:411 msg="Stopping notify discovery manager..."
level=info ts=2018-08-20T13:27:12.524670404Z caller=main.go:432 msg="Stopping scrape manager..."
level=info ts=2018-08-20T13:27:12.524677821Z caller=manager.go:460 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-08-20T13:27:12.52468619Z caller=manager.go:466 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-08-20T13:27:12.524692146Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-08-20T13:27:12.524702167Z caller=main.go:394 msg="Scrape discovery manager stopped"
level=info ts=2018-08-20T13:27:12.524715107Z caller=main.go:426 msg="Scrape manager stopped"
level=info ts=2018-08-20T13:27:12.524714587Z caller=main.go:573 msg="Notifier manager stopped"
level=info ts=2018-08-20T13:27:12.524726938Z caller=main.go:407 msg="Notify discovery manager stopped"
level=error ts=2018-08-20T13:27:12.52529427Z caller=main.go:582 err="Opening storage failed open DB in /home/tidb/deploy/prometheus2.0.0.data.metrics: Locked by other process"
level=warn ts=2018-08-20T13:27:12.525317008Z caller=web.go:461 component=web msg="error serving gRPC" err="grpc: the server has been stopped"
level=info ts=2018-08-20T13:27:12.525323413Z caller=main.go:584 msg="See you next time!"
