### ISSUE TITLE
[kube-prometheus] Helm chart won't deploy without TPR/CRDs in place

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#861]
**What did you do?**

```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/kube-prometheus
```

**What did you expect to see?**

Prometheus deployed

**What did you see instead? Under which circumstances?**

```
Error: apiVersion "monitoring.coreos.com/v1" in kube-prometheus/charts/exporter-kubernetes/templates/servicemonitor.yaml is not available
```

**Environment**

Kubernetes 1.8 with RBAC

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

[`kube-aws`](https://github.com/kubernetes-incubator/kube-aws)

* Manifests:

Used the [Helm chart](https://github.com/coreos/prometheus-operator/tree/master/helm).

* Discussion:

Looks like a chicken and egg problem with the chart and CRDs. Could we have a `helm/README.md` that gives us the steps to deploy with Helm? Maybe a Helm chart just to create the CRDs, then a second chart to actually deploy?

**Comment by whereisaaron** [comment]
Found a [comment in another issue](https://github.com/coreos/prometheus-operator/issues/592#issuecomment-355142097) by @gianrubio. Looks like the missing bootstrap info for `helm/README.md`!


> Charts finally got synced with s3, everyone can enjoy prometheus 2.0 using helm :)
```
$ helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/ …
$ helm install coreos/prometheus-operator --name prometheus-operator
$ helm install coreos/kube-prometheus --name kube-prometheus --set rbacEnable=true
```

**Comment by whereisaaron** [comment]
Added a helm/README.md with this vital bootstrap info in PR #863

**Comment by gianrubio** [comment]
Indeed is a chicken egg problem, maybe we can solve using a pre-install hook in a job to check if the `crd` is created, something like this [job](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/templates/get-crd-job.yaml)

**Comment by whereisaaron** [comment]
True, except I think that hook just waits for the CRDs to exist - which will never happen if you only install 'kube-prometheus'. But, you could do that as a pre-install hook for things that need the CRDs, and then include 'prometheus-operator' and a 'kube-prometheus' sub-chart. So all the other charts will wait (on the hook) for 'p-o' to start-up and create the CRDs?

**Comment by whereisaaron** [comment]
@gianrubio I found this in an old pre-helm prometheus-operator deployment script I wrote. I wonder if it is a debateable design decision that p-o run time creates the TPR/CRDs at run time.? When you `helm delete` the chart, the TPR/CRDs get left behind, they don't get cleaned up. If the TPR/CRDs were part of the deployment manifest (with or without Helm) we wouldn't have some of this awkwardness, and the TPR/CRDs would be cleaned up.

Could we dodge the whole problem and add the TPR/CRD manifests to Helm chart? Would p-o mind if we create them first?

```
# Wait for third party resources created by prometheus-operator to be ready
printf "Waiting for Operator to register third party objects..."
until kc-ns get servicemonitor > /dev/null 2>&1; do sleep 1; printf "."; done
until kc-ns get prometheus > /dev/null 2>&1; do sleep 1; printf "."; done
until kc-ns get alertmanager > /dev/null 2>&1; do sleep 1; printf "."; done
echo "done."
```

**Comment by gianrubio** [comment]
Related to helm delete, I have an old PR https://github.com/coreos/prometheus-operator/pull/433 to fix that. Do you mind to test it?

**Comment by whereisaaron** [comment]
Sure, once I get it working first :-)
(The helm chart has no option to add Ingress resources...)

**Comment by gianrubio** [comment]
Closing this issue because we provide the instruction on how to skip the error, this should be fixed in helm not here. https://github.com/kubernetes/helm/issues/2994

**Comment by MPV** [comment]
Would it be an option to use the Helm hook called `crd-install` to deploy the Prometheus CRDs? 

If I understand it right, then Helm would use that hook and create the CRDs first to prevent this issue?

See https://docs.helm.sh/developing_charts#defining-a-crd-with-the-crd-install-hook
