### ISSUE TITLE
kube-prmetheus kubelet exporter target forbidden

### ISSUE THREAD

**Issue by luisyonaldo** [coreos/prometheus-operator#867]
**What did you do?**
```
helm install coreos/prometheus-operator --name prometheus-operator --namespace=monitoring
helm install coreos/kube-prometheus --name kube-prometheus --namespace=monitoring
```

**What did you expect to see?**
All prometheus exporter targets on prometheus dashboard

**What did you see instead? Under which circumstances?**
target on prometheus dashboard: `server returned HTTP status 403 Forbidden`

**Environment**
RedHat

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kube-spray/kube-admin

* Manifests:
Kubelet Service Monitor
```
kubectl get ServiceMonitor -n monitoring kube-prometheus-exporter-kubelets -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  clusterName: ""
  creationTimestamp: 2018-01-08T14:11:35Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  generation: 0
  labels:
    chart: exporter-kubelets-0.1.2
    component: kubelets
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus-exporter-kubelets
  namespace: monitoring
  resourceVersion: "66465"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/kube-prometheus-exporter-kubelets
  uid: d5b50f43-f47d-11e7-9293-005056a4032b
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - honorLabels: true
    interval: 30s
    port: cadvisor
  jobLabel: kube-prometheus-exporter-kubelets
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
```

* Prometheus Operator Logs:
Kubelet
```
Jan 08 13:41:27 tapps773 kubelet[54973]: goroutine 27204 [running]:
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4205ea620, 0x193)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4205ea620, 0x193)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc420cc80c0, 0x193)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x41
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc420cc80c0, 0x193, 0xc4228c4050, 0x50, 0x4, 0xc422
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x46
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc422ed30e0, 0xc420cc80c0, 0xc422ed3020)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:246 +0x4fa
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc422ed3020, 0xc422ed30e0, 0xc420cc80c0)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).HandleWithFilter.func1(0x9a9d760, 0xc4205ea620, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:313 +0x355
Jan 08 13:41:27 tapps773 kubelet[54973]: net/http.HandlerFunc.ServeHTTP(0xc420b59c60, 0x9a9d760, 0xc4205ea620, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /usr/local/go/src/net/http/server.go:1942 +0x44
Jan 08 13:41:27 tapps773 kubelet[54973]: net/http.(*ServeMux).ServeHTTP(0xc4207df590, 0x9a9d760, 0xc4205ea620, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /usr/local/go/src/net/http/server.go:2238 +0x130
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc4211fb830, 0x9a9d760, 0xc4205ea620, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
Jan 08 13:41:27 tapps773 kubelet[54973]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc420aaa9b0, 0x9a9d760, 0xc4205ea620, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:778 +0x110
Jan 08 13:41:27 tapps773 kubelet[54973]: net/http.serverHandler.ServeHTTP(0xc4205a2b00, 0x9a9e9e0, 0xc420791960, 0xc42304c500)
Jan 08 13:41:27 tapps773 kubelet[54973]: /usr/local/go/src/net/http/server.go:2568 +0x92
Jan 08 13:41:27 tapps773 kubelet[54973]: net/http.(*conn).serve(0xc421ab2140, 0x9aa2160, 0xc4213ec240)
Jan 08 13:41:27 tapps773 kubelet[54973]: /usr/local/go/src/net/http/server.go:1825 +0x612
Jan 08 13:41:27 tapps773 kubelet[54973]: created by net/http.(*Server).Serve
Jan 08 13:41:27 tapps773 kubelet[54973]: /usr/local/go/src/net/http/server.go:2668 +0x2ce
Jan 08 13:41:27 tapps773 kubelet[54973]: logging error output: "Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=metrics)"
Jan 08 13:41:27 tapps773 kubelet[54973]: [[Prometheus/2.0.0] 10.94.130.14:33920]
Jan 08 13:41:29 tapps773 kubelet[54973]: E0108 13:41:29.322199   54973 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 4; ignoring extra CPUs
Jan 08 13:41:42 tapps773 kubelet[54973]: I0108 13:41:42.027127   54973 server.go:245] Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=metrics)
Jan 08 13:41:42 tapps773 kubelet[54973]: I0108 13:41:42.027206   54973 server.go:779] GET /metrics: (123.477µs) 403
```

Note: api server is able to communicate with same config. Also, it works if I change ServiceMonitor to use `http` instead of `https`.

**Comment by brancz** [comment]
It's slightly more tricky with the kubelet. I actually have a branch ready to do this with the kubelet. See here: https://github.com/brancz/prometheus-operator/commit/0b96a8d86716e47b2c1028e2930c8aeca4ae8b3a

What you need to make sure though, is that these two flags are enabled on your kubelets:

* `--authentication-token-webhook`
* `--authorization-mode=Webhook`

I will open a PR and merge that branch as soon as there is a way to do that with minikube.

**Comment by luisyonaldo** [comment]
yes I can confirm it work, `--authentication-token-webhook` did the trick for me, also added the role permit

**Comment by brancz** [comment]
Awesome! Glad it helped, will close this here.

**Comment by kedare** [comment]
To which role did you add this ? I could not make it work correctly

**Comment by luisyonaldo** [comment]
`prometheus` cluster role, it was added to master already, even with that it doesn't work for you?

**Comment by kedare** [comment]
I did the setup yesterday using the same commands and I still had the issue

**Comment by luisyonaldo** [comment]
do you receive `user=system:anonymous` on `kubelete` logs? if so, then rbac webhook is not configured

**Comment by kedare** [comment]
Nothing related to that so far in the Kubelet

There are my parameters on the Kubelet, I don't think I miss anything 

```
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
Environment="KUBELET_CUSTOM_ARGS=--authentication-token-webhook --authorization-mode=Webhook"
```

**Comment by brancz** [comment]
@kedare what does your `ServiceMonitor` for the kubelet look like?

**Comment by brancz** [comment]
Those are flags you need to have on your command that runs the kubelet, but a 500 error is not what you should be seeing as a result, it should be a 401 or 403. You should have a look at your kubelet logs.

**Comment by bamb00** [comment]
@brancz It was a status 403.  Sorry about the mix up.

     https://172.22.16.61:10250/metrics/cadvisor      server returned HTTP status 403 Forbidden
     https://172.22.16.61:10250/metrics    server returned HTTP status 403 Forbidden

**Comment by bamb00** [comment]
How do I set the correct permission for prometheus? This install is directly clone from prometheus-operator github.

**Comment by brancz** [comment]
If you use the helm charts or the manifests provided in `contrib/kube-prometheus/` then the permissions are already configured correctly. Can you share more concretely what you applied and what didn't work?

**Comment by azzaka** [comment]
Hi @brancz 

I beg to differ on that score. I used the helm charts and had no issues with the install nor any issues with permissions. 

I have since updated k8s to 10.0.2 and the Prometheus Helm Chart no longer has permission to talk to the pods:

endpoint="https-metrics" instance="10.26.3.63:10250" namespace="kube-system" service="kubelet" - server returned HTTP status 403 Forbidden

I have checked all other services, and all others are fine, however connection to the pods is now a no joy senario. Looking at the configs, they appear to have the correct level of access, except as you can see there is no allowable connection.

Regards,

**Comment by brancz** [comment]
cc @gianrubio this sounds like there may be a problem with the helm charts

**Comment by MichaelLiZhou** [comment]
### Environment
`Server Version: version.Info{Major:"1", Minor:"10"`

I used the manifest files with different namespace + node-ports. I too get a 403 on the kubelets but my apiserver + operator is up. 

I checked the the service role and looks like its what was described above.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```

**Comment by azzaka** [comment]
I can get metrics from other namespaces, just not kube-system.

**Comment by azzaka** [comment]
@brancz can you reopen the issue please as it's still not resolved. 

Or would you prefer we open a new issue? It's clear there t a fault somewhere and looks to be the heml chart. All other perms work except those for kube-system.

**Comment by azzaka** [comment]
No problem. I have added a new issue here: [https://github.com/coreos/prometheus-operator/issues/1415](issue:1415)

Thanks for all the help @brancz

**Comment by shankerbalan** [comment]
As suggested in this thread, KUBELET_EXTRA_ARGS fixes it.

$ cat /etc/systemd/system/kubelet.service.d/01-kubeadm.conf
# Ansible managed
[Service]
Environment="KUBELET_EXTRA_ARGS=--authentication-token-webhook"

**Comment by bamb00** [comment]
@shankerbalan After making the suggested change the error when from 402 forbidden to connection refused.

       Get https://172.22.16.61:10250/metrics: dial tcp 172.22.16.61:10250: connect: connection refused
       Get https://172.22.16.61:10250/metrics/cadvisor: dial tcp 172.22.16.61:10250: connect: connection refused

**Comment by swethakrish** [comment]
I tried to monitor kubelets using prometheus operator and got the same error. This resolved my issue as well.

**Comment by pdhung** [comment]
Hi everyone,
I am new to prometheus and not an expert of k8s authc and authz. I have several questions:
1. Is it still possible to allow Prometheus to use TLS x509 authentication to kubelet? Or the only way is to add the flag "--authentication-token-webhook" to kubelet args?
2. If kubelet has **only** the flag "--authentication-token-webhook", does it mean that right now every service account in the k8s cluster can now connect to kubelet to scrape metric info?
3. So in order to control which service account can access kubelet metric, is it right that we have to add "--authorization-mode=Webhook" to further control access/authorization? But where is the endpoint of this Webhook? Can you help me to understand how to control these accesses/authorizations?
Any answer or comment or info link from you guys are much appreciated.
Thanks!

**Comment by brancz** [comment]
1) Yes, x509 TLS client cert authentication is always available, if you are able to create and manage (rotate etc.) the certificates properly, I would even encourage you to use this over token authentication, but it turns out all management aspects are much easier for most users, but if you and your organization is capable of running a proper PKI, then go for it :slightly_smiling_face:.
2) Yes they could, as you would only have authentication turned on, but not authorization.
3) This means that the kubelet will ask the Kubernetes API whether the requesting entity has permissions to request the respective endpoint (metrics in our case). Enabling this means the kubelet will check on any request also for those with TLS certificates not just for tokens (but you will need to grant access to a "user" not a serviceaccount as that is what the kubelet interprets the common name of a client certificate as. Even if you are using TLS I recommend turning this on, as otherwise that means that the Prometheus server could do all actions on the kubelet, which really only the Kubernetes API should ever do.

**Comment by pdhung** [comment]
@brancz thanks a lot for the useful information. 

I have some more questions and comments:
1. Can you elaborate on why do you prefer x509 cert over bearer token for authentication?
2. What are the criteria for a proper PKI that you mentioned? Do Prometheus support the cert rotation?
3. I am using RKE to bootstrap the cluster. Currently RKE does not support "--authorization-mode=Webhook". Therefore it is a potential security problem when the prometheus pod (with x509 cert) is compromised (e.g. one pod on the same node is misconfigured and got broken out), the attackers can just control every kubelet in the cluster. Do you have any idea how to mitigate this issue?

**Comment by brancz** [comment]
1) client certificate authentication actually has a challenge response, whereas the token is essentially transferred in plaintext, so the receiving side can impersonate the Prometheus server.
2) I think Prometheus currently requires a reload (sighup, or POST to /-/reload) to reload certificates, but better support has been discussed. Rotation, short expiry, etc. are must have's.
3) Sadly no, but that's exactly why authorization was introduced in the kubelet :slightly_smiling_face: .

**Comment by pdhung** [comment]
@brancz: thank you! That makes sense now.
Just to be on the safe side, I would like to confirm the client cert authentication is configured under tls_config yml group. Is that right?

**Comment by brancz** [comment]
That is correct.

**Comment by philwinder** [comment]
Hi everyone. I have another work around. Some background: I'm on EKS and I didn't want to have to change the default kubelet arguments from what they specify in the AMI. 

I came across [this code](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L78) from the core prometheus library that attempts to scrape metrics using the main k8s proxy, rather than going direct to the kubelet port like it does in all the examples.

I tried that in the `additionalScrapeConfigs` and it worked! However, I didn't want to stop there, I wanted it inside a ServiceMonitor object. After a lot of hacking around I finally found a standard `ServiceMonitor` definition that uses relabelling to use the main k8s proxy. Please find the code below:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: exporter-kubelets
  name: exporter-kubelets
spec:
  jobLabel: component
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
    - port: https-metrics
      scheme: https
      interval: 15s
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabelings:
        - targetLabel: "__address__"
          replacement: "kubernetes.default.svc:443"
        - sourceLabels: ["__meta_kubernetes_endpoint_address_target_name"]
          regex: "(.+)"
          targetLabel: "__metrics_path__"
          replacement: "/api/v1/nodes/${1}/proxy/metrics"
    - port: https-metrics
      scheme: https
      interval: 15s
      honorLabels: true
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabelings:
        - targetLabel: "__address__"
          replacement: "kubernetes.default.svc:443"
        - sourceLabels: ["__meta_kubernetes_endpoint_address_target_name"]
          regex: "(.+)"
          targetLabel: "__metrics_path__"
          replacement: "/api/v1/nodes/${1}/proxy/metrics/cadvisor"
```

Note that you'll need prometheus operator version > 0.24, which is where the `relabelings` parameter was introduced. This works by changing the address and metrics path metadata just before doing the ingestion, using the node name information coming from the endpoint.

Hopefully there will be better solution soon (via a kube-rbac-proxy perhaps?) but I find this solution cleaner than having to alter the kubelet parameters.

Thanks!

**Comment by berezinsn** [comment]
Hello, please lemme know, how it works?
--authentication-token-webhook this param is really working, but how?
