### ISSUE TITLE
ServiceMonitors unable to work

### ISSUE THREAD

**Issue by shaunthium** [coreos/prometheus-operator#87]
Using the latest v2.2 of the Prometheus Operator and following the instructions here https://coreos.com/blog/the-prometheus-operator.html, I'm unable to get any Targets from the ServiceMonitors displaying in the Prometheus UI. None of the logs for pods etc. seem to show any errors or unusual activity; simply that none of the ServiceMonitor targets are showing up on the Targets page. 

Interestingly enough, I did not encounter this problem in v0.10 of the Prometheus Operator, only in subsequent versions up to the latest (v2.2).

Any help would be greatly appreciated! Please do let me know as well if there are any logs that would be helpful.

**Comment by fabxc** [comment]
@brancz could that be the bug fixed by #85? Seems like it only prevents reloading if an external URL is actually set, right?

@shaunthium can you paste any relevant YAMLs in here and the generated Prometheus configuration displayed on the status page?

**Comment by brancz** [comment]
Yes sounds like it, could you check the logs of the reloaders?

```
kubectl -n monitoring logs prometheus-k8s-0 config-reloader
```

Depending on your namespace and pod name of course. If that has an output of something like `got 404 but expected 200` then it is indeed the case.

**Comment by brancz** [comment]
Other than that the instructions are slightly outdated from that blog post and won't work entirely for that version. We are working on versioned user guides, but are not there yet. You can find up to date manifests in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus).

**Comment by snarlysodboxer** [comment]
I'm having the same issue with v0.2.2, and I have no `externalURL` set. (BTW, `externalURL` is not mentioned in the [documentation](https://github.com/coreos/prometheus-operator/blob/v0.2.2/Documentation/prometheus.md).)

I have several services with matching labels, yet my `scrape_configs` remain empty.
```shell
david@machine:~/prometheus$ kubectl get svc -l name=prometheus-front-tier-private
NAME                            CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
prometheus-front-tier-private   100.66.155.97   <none>        9090/TCP   22h
test-this                       100.66.3.8      <none>        9090/TCP   17h
david@machine:~/prometheus$
```
ServiceMonitor object:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: prometheus-front-tier
  labels:
    name: prometheus-front-tier
spec:
  selector:
    matchLabels:
      name: prometheus-front-tier-private
  endpoints:
  - port: test-this
    interval: 10s
  - port: prometheus-front-tier-private
    interval: 10s
```
ConfigMap was auto generated, not manually specified. Output of `kubectl get configmap prometheus-front-tier -o yaml`:
```yaml
apiVersion: v1
data:
  prometheus.yaml: |
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: keep
          regex: alertmanager
          source_labels:
          - __meta_kubernetes_service_name
        - action: keep
          regex: default
          source_labels:
          - __meta_kubernetes_namespace
        scheme: http
    global:
      evaluation_interval: 30s
      scrape_interval: 30s
    rule_files:
    - /etc/prometheus/rules/*.rules
    scrape_configs: []
kind: ConfigMap
metadata:
  creationTimestamp: 2017-01-05T03:38:10Z
  name: prometheus-front-tier
  namespace: default
  resourceVersion: "4177278"
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-front-tier
  uid: 612e73ba-d2f8-11e6-9621-023750e49fbf
```
Or am I doing something wrong?

**Comment by brancz** [comment]
There is an [example](https://github.com/coreos/kube-prometheus/tree/master/manifests/examples/example-app) application in [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus) there was a new release to fix a bug regarding reloading configs that could be the problem. (new version: `v0.2.3` for v1.5.x clusters and `v0.1.3` for v1.4.x clusters)

Thanks for mentioning the missing docs, I will add them tomorrow!

**Comment by snarlysodboxer** [comment]
@brancz My cluster is 1.5.1, and for now I have all involved resources in the `default` namespace.

I just upgraded to Prometheus Operator v0.2.3, and created the example app, and it worked; `scrape_configs` were configured correctly.

Thanks!

**Comment by brancz** [comment]
Actually can you show us the definition of those services and endpoints objects? (`kubectl get svc -l name=prometheus-front-tier-private -oyaml`, `kubectl get endpoints -l name=prometheus-front-tier-private -oyaml`) An `Endpoints` object is just a list of addresses maintained automatically by a `Service` object. The endpoints section in your `ServiceMonitor` seems off:

```
  endpoints:
  - port: test-this
    interval: 10s
  - port: prometheus-front-tier-private
    interval: 10s
```

These should be the ports specified in the `Service` object.

**Comment by snarlysodboxer** [comment]
@brancz it's true, it still isn't working for my setup. (i figure i have something wrong.)
`kubectl get svc -l name=prometheus-front-tier-private -oyaml`:
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"prometheus-front-tier-private","creationTimestamp":null,"labels":{"name":"prometheus-front-tier-private"},"annotations":{"prometheus.io/scrape":"true"}},"spec"
:{"ports":[{"name":"prometheus-front-tier-private","protocol":"TCP","port":9090,"targetPort":"web"}],"selector":{"prometheus":"prometheus-front-tier"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}'
      prometheus.io/scrape: "true"
    creationTimestamp: 2017-01-04T22:17:36Z
    labels:
      name: prometheus-front-tier-private
    name: prometheus-front-tier-private
    namespace: default
    resourceVersion: "4104355"
    selfLink: /api/v1/namespaces/default/services/prometheus-front-tier-private
    uid: 98c79e05-d2cb-11e6-9621-023750e49fbf
  spec:
    clusterIP: 123.123.123.123
    ports:
    - name: prometheus-front-tier-private
      port: 9090
      protocol: TCP
      targetPort: web
    selector:
      prometheus: prometheus-front-tier
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"test-this","creationTimestamp":null,"labels":{"name":"prometheus-front-tier-private"},"annotations":{"prometheus.io/scrape":"true"}},"spec":{"ports":[{"name":"
test-this","protocol":"TCP","port":9090,"targetPort":"web"}],"selector":{"prometheus":"prometheus-front-tier"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}'
      prometheus.io/scrape: "true"
    creationTimestamp: 2017-01-05T02:50:40Z
    labels:
      name: prometheus-front-tier-private
    name: test-this
    namespace: default
    resourceVersion: "4104236"
    selfLink: /api/v1/namespaces/default/services/test-this
    uid: bea1c95d-d2f1-11e6-9621-023750e49fbf
  spec:
    clusterIP: 123.123.123.123
    ports:
    - name: test-this
      port: 9090
      protocol: TCP
      targetPort: web
    selector:
      prometheus: prometheus-front-tier
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```
`kubectl get endpoints -l name=prometheus-front-tier-private -oyaml`:
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2017-01-04T22:17:36Z
    labels:
      name: prometheus-front-tier-private
    name: prometheus-front-tier-private
    namespace: default
    resourceVersion: "4195021"
    selfLink: /api/v1/namespaces/default/endpoints/prometheus-front-tier-private
    uid: 98c871af-d2cb-11e6-9621-023750e49fbf
  subsets: []
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2017-01-05T02:50:40Z
    labels:
      name: prometheus-front-tier-private
    name: test-this
    namespace: default
    resourceVersion: "4195019"
    selfLink: /api/v1/namespaces/default/endpoints/test-this
    uid: bea34be3-d2f1-11e6-9621-023750e49fbf
  subsets: []
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

**Comment by shaunthium** [comment]
Thanks for pointing me to the updated manifests @brancz , I can confirm that the `ServiceMonitors` now work perfectly fine for me. @snarlysodboxer Not sure if this might help, but my `Prometheus` config is as follows:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: monitors
  namespace: monitoring
  labels:
    prometheus: monitors
spec:
  version: v1.4.1
  serviceMonitorSelector:
    matchLabels:
      tier: monitors
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
```
And my `ServiceMonitor` config:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: secure
  namespace: monitoring
  labels:
    tier: monitors
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: my-app
  endpoints:
  - port: web
    interval: 10s
```
`namespaceSelector` is required to ensure that the generated config is able to pick up Targets from different namespaces. Hope this helps! This issue is resolved for me, thanks again @brancz @fabxc

**Comment by snarlysodboxer** [comment]
@shaunthium thanks! i got it working after modeling my labels after the example app.

thanks guys, v0.2.3 fixed this. resolved for me.

**Comment by snarlysodboxer** [comment]
jfyi, i was able to get away without setting `namespaceSelector`, since for now i have everything in one namespace for testing.

**Comment by brancz** [comment]
Great! Let us know if there are any other questions or problems coming up! :)

**Comment by kaarthikeyan1987** [comment]
I am getting below error while trying to implement kubectl create -f https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml

Error from server (BadRequest): error when creating "https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml": the API version in the data (monitoring.coreos.com/v1alpha1) does not match the expected API version (monitoring.coreos.com/v1)

Error from server (Invalid): error when creating "https://coreos.com/operators/prometheus/latest/prometheus-k8s.yaml": Service "prometheus-k8s" is invalid: spec.ports[0].nodePort: Invalid value: 30900: provided port is already allocated

Please need help to further proceed with the prrometheus operator deployment

**Comment by brancz** [comment]
@kaarthikeyan1987 the blog post is outdated, as noted in the header

> Note: The instructions in this post are out of date. To try out the Prometheus Operator, view the latest Prometheus docs for an up-to-date guide to get started.

Please try out the getting started in the docs, that is kept up to date. If that doesn't work, we need to fix it.
