### ISSUE TITLE
failed to get componentstatus after modify 127.0.0.1 to local IP.

### ISSUE THREAD

**Issue by KeithTt** [coreos/prometheus-operator#870]
Defaultly, endpoints of controller-manager and scheduler all listen to `127.0.0.1`, but in prome-operater they are node ip:

![image](https://user-images.githubusercontent.com/15189954/34771318-1781aa84-f63f-11e7-910c-b8f46d0cc56a.png)

After modifying the ip address, then I found this problem:
```
# kubectl get componentstatus
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
etcd-0               Healthy     {"health": "true"}
etcd-2               Healthy     {"health": "true"}
etcd-1               Healthy     {"health": "true"}
```

**Comment by KeithTt** [comment]
Yes, the prome-operator is working now. 

Controller-manager and Scheduler only listen `127.0.0.1` by default, but operator get data from node ip like `192.168.5.42, ...`, and I modify the config file from `127.0.0.1` to node ip, then I found the status of controller-manager and scheduler turn Unhealthy, because it get data from `127.0.0.1`...

```
![image](https://user-images.githubusercontent.com/15189954/34787804-8a9fa776-f673-11e7-82d8-9bf6a703310e.png)
```

**Comment by brancz** [comment]
simply listen on all interfaces `0.0.0.0` that should satisfy both

**Comment by KeithTt** [comment]
I have 3 controller-manager and 3 scheduler, to ensure there is only one instance can modify the status of the cluster in a time, in theory they should not listen on `0.0.0.0`......

**Comment by brancz** [comment]
I don't understand what HA has to do with not binding against `0.0.0.0`. Can you elaborate?

**Comment by KeithTt** [comment]
Change address to `0.0.0.0`, everything turns working, and lease lock is normal.

![image](https://user-images.githubusercontent.com/15189954/34857518-26fbe414-f786-11e7-8009-2996786a6a6f.png)

I guess I miss understand something, I will do my homework in this weekend.

And I found a guide, there is a config file where they listen on `0.0.0.0`.

@brancz Thanks a lot. Close it.
