### ISSUE TITLE
[helm/grafana] grafana-watcher can't reach grafana on localhost

### ISSUE THREAD

**Issue by danielm0hr** [coreos/prometheus-operator#875]
**What did you do?**

Deployed the Grafana helm chart.

**What did you expect to see?**

grafana-watcher updating the Grafana dashboards trough its REST API.

**What did you see instead? Under which circumstances?**

The grafana-watcher application can't reach grafana which is running in the same pod. What I see in the grafana-watcher log:
```Get http://admin:admin@localhost:3000/api/datasources: dial tcp 10.41.131.85:3000: i/o timeout```

I don't know what's the IP address above to which grafana-watcher resolves ```localhost```. Both grafana* containers have the IP ```10.233.76.104```.

When going into the grafana-watcher container with ```kubectl exec``` I can reach grafana with ```telnet``` at ```localhost:3000``` (which resolves to 127.0.0.1 in the shell), ```10.233.76.104:3000``` and ```kube-prometheus-grafana:80```. Thus, I suppose networking and DNS work correctly, right?

Also when running grafana-watcher manually in the container with one of the above grafana URLs, it works fine.

Why does grafana-watcher resolve ```localhost``` to this strange IP above?

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Bare-Metal cluster deployed with Kubespray 2.3.0, using Calico as network plugin.

**Comment by brancz** [comment]
> Why does grafana-watcher resolve localhost to this strange IP above?

Which container runtime are you using? I'm expecting this not to be a problem with the chart or the Prometheus Operator. Can you just try changing the address from localhost to `127.0.0.1`?

**Comment by danielm0hr** [comment]
Container runtime is Docker v1.13.

As I wrote: Yes, it works, when changing the address to ```127.0.0.1```. However, ```localhost``` is hardcoded in the Helm chart's deployment manifest. Thus, this would be a code change.

But: When doing a ```telnet localhost 3000``` from inside the grafana-watcher container, I can reach grafana. There, ```localhost``` resolves to ```127.0.0.1```. But why not inside the application? To me it feels like an issue with Golang's net/http DNS resolution.

**Comment by brancz** [comment]
Grafana has started implementing the functionality we implemented with the grafana-watcher in the latest versions, so I'm not inclined to start debugging code that is on my list to be removed. Would just updating the chart to use `127.0.0.1` work for you?

**Comment by danielm0hr** [comment]
Yes, that's fine for me. Please see my PR above. Thanks!
