### ISSUE TITLE
Can alertmanager be upgraded to a newer version?

### ISSUE THREAD

**Issue by KeithTt** [coreos/prometheus-operator#891]
I need to try a  new notifier in this feature: https://github.com/prometheus/alertmanager/pull/1059

And I have tried to change the version of alertmanager from `v0.9.1` to `v0.12.0`, the alertmager pod can not work.

**Comment by brancz** [comment]
Yeah I noticed this as well, I'm in the process of updating all versions, coming soon! :)

**Comment by KeithTt** [comment]
@brancz Thanks, waiting for your update.

**Comment by secat** [comment]
@brancz The version of alertmanger `v0.13.0` is currently not supported by the prometheus-operator. The alertmanager arguments are now using 2 dashes instead of one.

Example:
```
--config.file=...
```

**Comment by KeithTt** [comment]
@brancz `v0.13.0` is available now?

**Comment by KeithTt** [comment]
@brancz Thanks a lot, wait for you.

**Comment by brancz** [comment]
@KeithTt done, the manifests in `contrib/kube-prometheus` are updated and the Prometheus Operator `v0.16.1` has been released.

**Comment by KeithTt** [comment]
@brancz Thanks a lot！！！
