### ISSUE TITLE
Enabling Open Cloud Application via Tectonic console does not show all available namespaces.

### ISSUE THREAD

**Issue by mluedke** [coreos/prometheus-operator#899]
**What did you do?**
Via the Tectonic console: Tried to enable the Vault Open Cloud Application on a specific namespace on a cluster with over 100 namespaces.

**What did you expect to see?**
A list of all namespaces after clicking the "Enable" button on the `/catalog` page.

**What did you see instead? Under which circumstances?**
A list of 122 namespaces, instead of the 131 namespaces we have in our cluster.

**Environment**

* Kubernetes version information:

	Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	1.8.4-tectonic.3

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Comment by mluedke** [comment]
Not sure if related or not, but one of the alm pods is crashing...
```
alm-operator-59946d847-5mkzx                             0/1       CrashLoopBackOff   5351       10d
tectonic-alm-operator-1205878-4bgt8                      1/1       Running            0          10d
```
This is the only thing I see in the logs:
```
kubectl logs alm-operator-59946d847-5mkzx -n tectonic-system
time="2018-01-16T16:19:57Z" level=info msg="Using in-cluster kube client config"
```

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, please contact Tectonic customer support.
