### ISSUE TITLE
Query kubelet via proxy / metricRelabelings issue

### ISSUE THREAD

**Issue by champtar** [coreos/prometheus-operator#902]
Default helm deployment doesn't work out of the box as kublet querying doesn't work
There is an issue to fix the cadvisor part #633 
Another issue is that on some cluster token auth doesn't work on the kubelet https endpoint (at least on GKE (https://github.com/kubernetes/kubernetes/issues/44330 https://github.com/prometheus/prometheus/issues/2606#issuecomment-294869099 https://github.com/prometheus/prometheus/pull/2641 https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication) and kubespay)

The proper fix, which is in prometheus repo, is to query trough the API server using relabeling black magic
https://github.com/prometheus/prometheus/blob/fae3bd17b950f4574a0827d975e4e7df80d5abfb/documentation/examples/prometheus-kubernetes.yml#L59

**What did you do?**
Try to use metricRelabelings
```
diff --git a/helm/exporter-kubelets/templates/servicemonitor.yaml b/helm/exporter-kubelets/templates/servicemonitor.yaml
index 69718e4..8c6e226 100644
--- a/helm/exporter-kubelets/templates/servicemonitor.yaml
+++ b/helm/exporter-kubelets/templates/servicemonitor.yaml
@@ -26,6 +26,15 @@ spec:
       # for the kubelet on API server nodes fail.
       insecureSkipVerify: true
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
+    metricRelabelings:
+    - action: labelmap
+      regex: __meta_kubernetes_node_label_(.+)
+    - targetLabel: __address__
+      replacement: kubernetes.default.svc:443
+    - sourceLabels: [__meta_kubernetes_node_name]
+      regex: (.+)
+      targetLabel: __metrics_path__
+      replacement: /api/v1/nodes/${1}/proxy/metrics
   - port: cadvisor
     interval: 30s
     honorLabels: true
```

**What did you expect to see?**
see this conf "mixed" into prometheus conf (/conf)

**What did you see instead? Under which circumstances?**
nothing is happening, `metricRelabelings` section is ignored
(no error in the operator logs)

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Installed a default cluster on Centos 7.4 node using kubespay

* Prometheus Operator version:
latest version (1fb131970e93e35f37db3dbc2fbee66e35ca696f) deployed from git using helm

**Comment by olvesh** [comment]
Here is another issue with relevant discussion on this topic https://github.com/prometheus/prometheus/issues/2606#issuecomment-294869099

@champtar  - could it be you need to adjust the ClusterRole to allow `nodes/proxy` as well?

I am fixing just this issue my self.. Will report the progress.

**Comment by brancz** [comment]
Please do not touch relabeling if you don't need to, this is why we didn't add it for the longest time, and the relabeling we support is not the type you're looking for (we currently only support metric relabeling and remote read/write relabeling). The API docs on coreos.com have not been synchronized yet, but current docs can be found in this repository.

Regarding the issue you are seeing and the "recommended" way that is proposed in the Prometheus repo. I am in the process of changing this as I believe the way described in the repo is what works for most people but is not a sane setup (https://github.com/prometheus/prometheus/pull/3661). For reasons that I have stated in that PR I feel strongly that it is not the way anyone should operate Prometheus on their cluster.

Your other choices using the Prometheus Operator are:

* use separate cadvisor port (this is the current default)
* enable kubelet token auth (this will soon become the default; in kubespray this should be an easy addition; GKE should add it, and to my knowledge is planning to do so)
* use a client certificate to authenticate with the kubelets
* If really none of the above options are possible for you, I suggest using a [custom config](https://github.com/coreos/prometheus-operator/blob/master/Documentation/custom-configuration.md) for now and adapt your approach to one of the above options later

Hope this helps. Let me know if you have any other questions.

**Comment by olvesh** [comment]
Thanks @brancz 

So, what you are saying is that on GKE we should wait until they add kubelet token auth? 
Looks like Google have no plans on doing that: https://github.com/kubernetes/kubernetes/issues/44330#issuecomment-294023219

I'll look into using a client certificate, not sure how (especially in GKE). Guess I will have to learn something new :-)

**Comment by brancz** [comment]
Yeah sounds like client cert auth is what you want to do as described in the description you posted:

> you can create a client certificate using the certificates API for prometheus to use when contacting kubelets

**Comment by champtar** [comment]
For now I'm using the unauthenticated http port (http-metrics) but I was looking for a solution that work everywhere
Thanks for all the infos
