### ISSUE TITLE
kube-prometheus chart update to 0.11 broke installation

### ISSUE THREAD

**Issue by simon-k8s** [coreos/prometheus-operator#921]
**What did you do?**

I updated the kube-prometheus helm chart from 0.10 to 0.11

**What did you expect to see?**

An updated kube-prometheus setup

**What did you see instead? Under which circumstances?**

The discovery of the kubelet does not work anymore. I get this error:

``
Get https://192.168.1.15:10250/metrics: x509: cannot validate certificate for 192.168.1.15 because it doesn't contain any IP SANs
``

I tried to configure the option insecureSkipVerify but it did not work. I had to downgrade to 0.10 to get my prometheus working again. How can I fix this? The problem seems to be this commit

[https://github.com/coreos/prometheus-operator/commit/564f78eabf9bc4ecb53913c9412107bbe06b95b3](url)

**Environment**
Ubuntu 16.04 LTS

* Kubernetes version information:
``
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
``

**Comment by brancz** [comment]
Note that the helm charts are under heavy development, breaking changes now and then are expected. Does it only break on upgrade or also on fresh install?

**Comment by simon-k8s** [comment]
@brancz it breaks both the upgrade and a fresh install. The service discovery of the kubelets breaks. So I don't get any stats from my pods. After downgrading everything is fine.

**Comment by mogaal** [comment]
I am facing exactly the same problem, I would add on the top of this the screenshot:

<img width="1666" alt="screen shot 2018-01-26 at 14 58 49" src="https://user-images.githubusercontent.com/134855/35445599-0341df2c-02aa-11e8-9c5a-5f2c99f5574f.png">

I am assuming installation [out of the box](https://github.com/coreos/prometheus-operator/blob/master/helm/README.md)

If I understand you it is better off avoid using charts for the time being. What is the recommended/more-stable installation method?

**Comment by simon-k8s** [comment]
@mogaal for the time being you could downgrade to the previous version with helm:

`helm --namespace=monitoring install --name kube-prometheus --version 0.0.10 -f values.yaml coreos/kube-prometheus`

That worked fine for me.

**Comment by erkolson** [comment]
I'm seeing the initial problem as well.  For me (in AWS) it is because the Subject of the certificate matches the hostname with is something like: `ip-172-17-157-108.ec2.internal` and as the error above says, there is no SAN defined for the hostname `172.17.157.108`.  So we need a way to configure the exporter for different hostnames.

@mogaal - I think you are seeing a different problem.  In my cluster at least, I see those same etcd errors but that is because there are iptables rules blocking access to etcd for everything except the master nodes.  In my case it was configured by kops, not sure I can change it so I will have to figure out how to get an etcd-exporter scheduled on a master node.

**Comment by gianrubio** [comment]
I could confirm the issue, it was introduced on #869, I'll work on a fix for that.

**Comment by mogaal** [comment]
@simon-k8s Still getting errors with the etcd service (not exporter). For the time being the only one that works is https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md
