### ISSUE TITLE
Helm grafana - add possibility to add Env variable from values

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#929]
**What did you do?**
I want to configure many plugin like Google Oauth.
And now i can't define it on my values.yaml

**What did you expect to see?**
To have new param env that can be append on grafana deployement.

**Comment by brancz** [comment]
We envision to run Grafana in a completely stateless manner where it is really just concerned about dashboarding and dashboarding alone. We run the bitly/oauth2_proxy in front of it. This allows us to inject the auth proxy wherever we need to. It's @gianrubio's call whether to add it to the helm charts, but I'd like to keep the setup of Grfana as simple as possible. IMHO Grafana shouldn't have authentication itself, but that's a longer story.

**Comment by gianrubio** [comment]
I agree with @brancz, @sebglon you can achieve the same results using the oauth2_proxy + injecting annotations, take a look on [this link](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/external-auth). Please share the results 😋

**Comment by sebglon** [comment]
I understand for oauth, but this is the same for all other extensions or config custo. For example smtp, analytics, log, metrics, ...

**Comment by brancz** [comment]
Agreed. I think this is an issue with helm in general :slightly_smiling_face:, just auth in particular I think doesn't belong in Grafana IMHO.

**Comment by sebglon** [comment]
Can i create a PR to add 
```
      {{- range $key, $value := .Values.envs }}
        {{ $key }}: {{ $value }}
      {{- end }}
```
for simple Key / value env to append

**Comment by sebglon** [comment]
or make the same than `{{ toYaml .Values.dataSource | indent 2 }}`

**Comment by gianrubio** [comment]
You can add this flags if you don't break the current configuration :)

**Comment by sebglon** [comment]
An implementation for drupal: https://github.com/kubernetes/charts/blob/88f7f82ba96e8b3ebb24a97e734b2ce9a4a10ff6/stable/drupal/templates/deployment.yaml#L66

**Comment by sebglon** [comment]
@gianrubio PR ready and Work without break
