### ISSUE TITLE
[kube-prometheus] node-exporter can not be scraped with k8s 1.7

### ISSUE THREAD

**Issue by slintes** [coreos/prometheus-operator#932]
**What did you do?**
install kube-prometheus with `make generate` && `./hack/cluster-monitoring/self-hosted-deploy` using the `v0.16.1` tag

**What did you expect to see?**
all targets can be scraped

**What did you see instead? Under which circumstances?**
- node exporter couldn't be scraped because of 401
- logs of node-exporter/kube-rbac-proxy showed `Unable to authenticate the request due to an error: User "system:serviceaccount:monitoring:node-exporter" cannot create tokenreviews.authentication.k8s.io at the cluster scope.`
- noticed I missed errors during running deploy script:
  - `error validating "manifests/node-exporter/node-exporter-cluster-role-binding.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"rbac.authorization.k8s.io", Version:"v1", Kind:"ClusterRoleBinding"}; if you choose to ignore these errors, turn validation off with --validate=false`
  - `error validating "manifests/node-exporter/node-exporter-cluster-role.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"rbac.authorization.k8s.io", Version:"v1", Kind:"ClusterRole"}; if you choose to ignore these errors, turn validation off with --validate=false`

**Environment**

* Kubernetes version information:

	`Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Solution**

I fixed this by changing `apiVersion` of `node-exporter-cluster-role.yaml` and `...-binding.yaml` from `rbac.authorization.k8s.io/v1` to `rbac.authorization.k8s.io/v1beta1`. Not sure if that also works for newer k8s versions, but at least the prometheus rolebindings use the same api version.
If you agree, I can create a PR.

**Comment by brancz** [comment]
The kube-prometheus manifest collection has no stability guarantees and is generally kept up to date to work with the latest version of Kubernetes.

Incompatibilities like this can be solved with the helm charts.

**Comment by brancz** [comment]
This is not an issue with the Prometheus Operator and since there are no guarantees on the compatibility of the kube-prometheus collection I will close this issue.
