### ISSUE TITLE
Feature: Generate Listers and Informers for CRD types

### ISSUE THREAD

**Issue by tamalsaha** [coreos/prometheus-operator#945]
We watch prometheus CRDs from our code. It will be helpful, if the listers and informers where generated using the code generator and made available from this repo.

**Comment by brancz** [comment]
Unfortunately due to the fact that we need to be able to inject the name of CRDs and API group, I'm unsure whether we can actually make use of that code generation.

**Comment by tamalsaha** [comment]
It is done for sometime https://github.com/coreos/prometheus-operator/tree/master/pkg/client
