### ISSUE TITLE
Set sessionAffinity in prometheus service spec

### ISSUE THREAD

**Issue by jaglade** [coreos/prometheus-operator#946]
Reading the documentation, there are several mentions of using sessionAffinity when configuring for HA.  I have not found a way to configure that in the Prometheus service.  Looking at the helm charts, it does not appear to be configurable right now and just defaults to "none".  

My question is - how do i properly setup ha so that i'm not bouncing between different prometheus servers?  I see a PR was closed/rejected concerning this, but i am not sure why and what i am supposed to do.

**Comment by gianrubio** [comment]
@jaglade I'll be glad to have a PR adding the sessionAfinity configuration in the helm charts. Yesterday I wrote a doc explainning [how to contribute](https://github.com/gianrubio/prometheus-operator/blob/03f652eb627c20aeee4dcd583972b0d85a52c59c/helm/README.md) to helm charts. Let me know if you can make it

**Comment by jaglade** [comment]
@gianrubio I'd like to take a crack at it.  Will submit a PR once i get it written and tested.  Thanks.

**Comment by jaglade** [comment]
@gianrubio PR submitted.  #952 
Also note that i found an issue with the 'how to contribute' instructions.  Packaging the prometheus-operator led to me installing it twice (since we already installed it once in the first line of instructions) which wreaked havoc in my cluster.

**Comment by gianrubio** [comment]
I made a small comment on the PR feel free to express your thoughts and thanks for reviewing the contribute instructions.

**Comment by gianrubio** [comment]
Solved on #952

**Comment by jaglade** [comment]
@gianrubio Thank you for merging my PR.  The issue is that someone used the chart version that i was using (0.0.13) and was merged first.  I had to submit another pull request to bump chart versions.  Can you please take a look and merge?  #963 
Thanks.

**Comment by gianrubio** [comment]
sorry for the inconvenience, #917 will fix that
