### ISSUE TITLE
Pass Prometheus object's labels through to StatefulSets? (and thus Pods)

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/prometheus-operator#95]
Currently Prometheus Operator provides no way to add custom labels to pods created by `StatefulSet`s (created by `Prometheus`es.) `StatefulSet`s already pass through their metadata label sets through to the pods created by themselves, so Prometheus Operator would only need to read a `Prometheus` object's labels and pass them through to the `StatefulSet`s it creates.

I believe [this](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L180) is the relevant code.

Also, it wasn't clear to me in the docs that the Operator forces the label `prometheus: <prometheus object name>`, which caused me some confusion for a time until I read the code.

**Comment by snarlysodboxer** [comment]
I just realized, while we're on this topic, what do you guys think about also passing annotations through to the `statefulSet`s? - This would allow. for example, the setting of inter-pod anti-affinity to ensure the pods created by the `statefulSet`s are "spread out" across machines/zones.

**Comment by brancz** [comment]
That is indeed the relevant code, however, I'm unsure whether just blindly passing through the labels and annotations is a good idea. I understand that it is desirable to be able to specify custom labels/annotations. Maybe we can pass through the labels and annotations from the `Prometheus` object to the `StatefulSet` and then have fields in the spec to specify further labels/annotations for the `PodTemplate` of the `StatefulSet`? Wdyt @fabxc ?

**Comment by fabxc** [comment]
I'm 👍 on the labels – seems just to be consistent with other resources.

Unsure on annotations. They are interpreted a fair bit more and it might cause unexpected side effects. It's probably okay to pass them on to the StatefulSet. But I would say no to the pods for now.

If we do it, than probably explicitly as @brancz described. But I think anti-affinity is something we want to enable by default eventually. Running multiple replicas and not wanting anti-affinity on them is not a use case I ever see.
The thing about those interpreted annotations is, that they are often just an intermediate step before going into the proper spec of a resource. So in the long run, they won't be usable anymore and we have to either make a call on a default or add it to the proper spec of our TPRs to be propagated.

**Comment by snarlysodboxer** [comment]
@brancz @fabxc Your comments sparked a little closer investigation, and when I add the label `test-this: test-label` to my etcd `statefulSet`'s [podTemplateSpec](http://kubernetes.io/docs/resources-reference/1_5/#podtemplatespec-v1) metadata, (_not_ the `statefulSet` itself's metadata,) that label shows up when I `kubectl describe pods/etcd-0`. - So I was wrong when I said the labels could be passed through to the `statefulSet`, instead they would need to be passed through to the `statefulSet`'s `podTemplateSpec`, which happens to be what you're already doing, as seen in the [mentioned code](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L180).

@brancz Your idea of [passing] "through the labels and annotations from the Prometheus object to the StatefulSet and then have fields in the [_prometheus object's_] spec to specify further labels/annotations for the PodTemplate of the StatefulSet" sounds like a good solution.

@fabxc I see your point about annotations. Default anti-affinity settings would have to be tunable, E.G host vs zone in AWS, and likely more custom things for some. Hmm..

**Comment by brancz** [comment]
I think we can pass through labels and annotations from the `Prometheus`/`Alertmanager` TPR and wait for a solid use-case to allow passing it through to the `PodTemplate`.

**Comment by brancz** [comment]
Closed by #108
