### ISSUE TITLE
Change images for StatefulSets ?

### ISSUE THREAD

**Issue by jbvmio** [coreos/prometheus-operator#951]
**What did you do?**
Pulled all images to private onsite registry. Edited all yaml file to point to new image location and deployed kube-prometheus. Our K8s Nodes are currently  unable to download public images directly.

**What did you expect to see?**
A working kube-prometheus deployment.

**What did you see instead? Under which circumstances?**
Prometheus and Alertmanager pods in a crashloop status, unable to pull from quay.io.

**Environment**
Onsite, baremetal, CentOS7

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
From scratch.

**Workaround**
Pull the images manually to each node and retag as:
quay.io/prometheus/alertmanager:v0.9.1
quay.io/prometheus/prometheus:v2.0.0

**Comment by brancz** [comment]
Those are exactly the images that would be pulled by default. Can you share more of your setup? Did you adapt any flags or options in the Prometheus/Alertmanager manifests?

**Comment by jbvmio** [comment]
Yes, those are the images pulled by default. I want to pull them from:
<my_registry>/alertmanager:v0.9.1
<my_registry>/prometheus:v2.0.0

instead. I've modified every manifiest file replacing every image reference as indicated above for every image, but I can't find where these 2 images are referenced for the given statefulsets.

Where are these defined so I can modify the pull location?

I only see the following references for those 2 images in the following files:
/prometheus-operator/helm/alertmanager/values.yaml
/prometheus-operator/helm/kube-prometheus/values.yaml
/prometheus-operator/test/framework/alertmanager.go

/prometheus-operator/helm/kube-prometheus/values.yaml
/prometheus-operator/helm/prometheus/values.yaml
/prometheus-operator/test/framework/prometheus.go

I'm not using Helm for deployment.

**Comment by brancz** [comment]
The flags of the Prometheus Operator, that you are looking for are:

```
  -alertmanager-default-base-image string
        Alertmanager default base image (default "quay.io/prometheus/alertmanager")
  -config-reloader-image string    
        Reload Image (default "quay.io/coreos/configmap-reload:v0.0.1")
  -prometheus-config-reloader string                                  
        Config and rule reload image (default "quay.io/coreos/prometheus-config-reloader:v0.0.2")
  -prometheus-default-base-image string
        Prometheus default base image (default "quay.io/prometheus/prometheus")
```

Let me know if this is what you were looking for.

**Comment by jbvmio** [comment]
Thanks brancz - This looks like it should be it. My apologies if this was documented somewhere and I just missed it. I am looking over the prometheus-operator deployment yaml now, will add these flags and test this week. Appreciate it -

**Comment by jbvmio** [comment]
Chiming back in to state this indeed was what I was looking for. Thanks @brancz.

**Comment by bamb00** [comment]
Hi, @brancz

I'm using helm and pull the images from quay.io and re-tag it.  In the values.yaml file
the image is setup like below the deployment.yaml is unchanged.  The alertmanager deployment failed with CrashLoopBack and prometheus does not even deploy to k8s dashboard.  What am missing?

image:
   repository: private_registry_path
   tag: some_arbitrary_value

quay.io/prometheus/alertmanager:v0.14.0
quay.io/prometheus/prometheus:v2.1.1

Thanks.

**Comment by brancz** [comment]
the tag can't be an arbitrary value, it's what decides the version, so it must be a valid semver tag

```
    tag: some_arbitrary_value
```

the error you are getting is likely because the wrong version is selected due to not being able to decide the version

**Comment by bamb00** [comment]
Hi @brancz 

Is there a constraint restriction for the semver tag?

Try it with an arbitrary value but with prefix.  For example:  v2.0.0.25-master-0056-180504002721

**Comment by brancz** [comment]
anything that's an actually valid semver string works, the library we use is https://github.com/blang/semver you can test with that to find out if your string does what you think
