### ISSUE TITLE
Grafana installPlugins: key

### ISSUE THREAD

**Issue by lfaoro** [coreos/prometheus-operator#955]
The official Grafana helm chart has a section in the deployment file:
```
{{- if .Values.server.installPlugins }}
            - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "grafana.server.fullname" . }}-config
                  key: grafana-install-plugins
            {{- end }}
            {{- range $key, $value := .Values.server.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
```
https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/deployment.yaml#L48

Could you please include this section into the prometheus-operator/kube-prometheus official chart to allow us to inject plugins via overriding the values.yaml during helm install/upgrade?

**Comment by gianrubio** [comment]
Fixed on #954
