### ISSUE TITLE
Grafana default password for admin

### ISSUE THREAD

**Issue by ericzji** [coreos/prometheus-operator#956]
kube-prometheus

After run hack/cluster-monitoring/deploy 
We should be able to reach Grafana on node port 30902

I am wondering what's the Grafana default password for admin user? Not able to login with admin/admin

thanks
-Eric

**Comment by elisiano** [comment]
If you use kube-prometheus then did you try looking into the manifest that generates the secret `grafana-credentials`: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-credentials.yaml ? (not tested that's just a guess)

**Comment by elisiano** [comment]
according to this https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-credentials.yaml it looks like it's admin/admin (the manifest has the values base64 encoded)

**Comment by ericzji** [comment]
@elisiano thanks for reply. Tried admin/admin, but failed.
Any way I can get the admin password? 

I can use the following command
`   kubectl get secret --namespace default my-release-grafana -o jsonpath="{.data.grafana-admin-password}" | base64 --decode ; echo`
if I run "helm install --name my-grafana stable/grafana"

Any way I can get the admin password for this installation?
thanks

**Comment by elisiano** [comment]
I'm not familiar with the chart installation method but if you used the deploy script without setting a `NAMESPACE` variable then it uses `monitoring` by [default](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/deploy#L11). Try looking up the secret in that namespace. 

My experience is limited I'm not sure I can be of further help. 
How are you trying to access grafana?
 "it works for me" with `kubectl proxy`  and then accessing http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/http:grafana:3000/proxy/ but you could also use `port-forward` instead of proxy

**Comment by ericzji** [comment]
@elisiano Thanks. 
Same issue with port-forward

seems the password should be "admin" as per the following:
scs@k8s-master:~/prometheus-operator/contrib/kube-prometheus$ kubectl get secret --namespace  monitoring grafana-credentials -o yaml
apiVersion: v1
data:
  password: YWRtaW4=
  user: YWRtaW4=
scs@k8s-master:~/prometheus-operator/contrib/kube-prometheus$ echo "YWRtaW4=" | base64 --decode
admin

Now, every time I login to http://127.0.0.1:30902/login, it reports the error:
Server side error :(
runtime error: index out of range
check the Grafana server logs for the detailed error message.

**Comment by elisiano** [comment]
Are you using a non-standard port? Because with port-forward by default it's port 3000

**Comment by mike-henders** [comment]
I am encountering this problem as well.  Looking at the logs it appears the directory /grafana/data does not exist and the grafana does not have permission to add it.

I worked around it by creating a new emptyDir: {} volume and mounting it to /grafana/data in the container.  I don't know if this is the correct solution.  I'm experiment so I can afford to lose data if I make a mistake.

**Comment by gianrubio** [comment]
@ericzji could you past the grafana logs?

@mike-henders probably your issue is the same as https://github.com/coreos/prometheus-operator/issues/924 right?

**Comment by mike-henders** [comment]
@gianrubio Yes.  My issue looks the same as #924.

**Comment by ericzji** [comment]
@gianrubio I am sorry but where I can get grafana logs? don't see it from /var/log/grafana/grafana.log

BTW, I am running as a non-root user

**Comment by ericzji** [comment]
![prometheus-status-targets](https://user-images.githubusercontent.com/26015473/35825689-7b95d7a8-0a6b-11e8-83f1-8a1b655cb587.png)

Also in my case, the kubelet are not up as shown from prometheus. (attached)

**Comment by gianrubio** [comment]
Use ``` kubect logs -f -n monitoring grafana-pod-name ```

**Comment by ScottBrenner** [comment]
@ericzji This helped me resolve the kuebelet 403 issue you're seeing: https://github.com/kubernetes/kubernetes/issues/44330#issuecomment-293287575

**Comment by brancz** [comment]
Make sure your clusters actually follow the requirements on kubelet authorization and authentication. https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#prerequisites

**Comment by brancz** [comment]
As there doesn’t seem to be an issue with the Prometheus operator here I’m closing this.

**Comment by HYChou0515** [comment]
According to the README from https://github.com/helm/charts/tree/master/stable/prometheus-operator#grafana, the default password is `prom-operator`. (The username is `admin`)

**Comment by gadelkareem** [comment]
Now it is ```kubectl get secret grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo```

**Comment by metalmatze** [comment]
At most this is related to kube-prometheus and not the Prometheus Operator. I'm locking this conversation going forward.
