### ISSUE TITLE
Add alert on prometheus pod memory usage

### ISSUE THREAD

**Issue by audip** [coreos/prometheus-operator#958]
**What did you do?**
Deployed prometheus using prometheus operator in kubernetes (using kops) and I'm impressed by the alerting rule provided out-of-the-box. While the alerts are great, the [file at this path](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml) lacks any alerting when memory usage on the prometheus pod is at a critical mark.

**What did you expect to see?**
An alert with severity of warning/critical for when prometheus pods are running high on memory specified in prometheus operator CRD.

**What did you see instead? Under which circumstances?**

**Environment**

- AWS EC2 instances in us-east-1 region

* Kubernetes version information: kubernetes 1.8.5

* Kubernetes cluster kind: kops 1.8.0

**Comment by brancz** [comment]
> An alert with severity of warning/critical for when prometheus pods are running high on memory specified in prometheus operator CRD.

This is out of scope for the kube-prometheus manifests. Users are expected to do vendor the manifests into their own infrastructure repository and adapt to their needs.

In that sense I will close this, but feel free to contribute an alert if you put something together that works for you.

**Comment by akshays244** [comment]
i have successfully configured alerts Related to Nodes for CPU,MEMORY , NODE DOWN , FILE SYSTEM . but i am struggling to do the same for PODs in our infra

**Comment by audip** [comment]
@akshays244 Can you share more on what kubernetes version you're running? And what alerts are you looking to configure?

**Comment by akshays244** [comment]
@audip  :hi aditya thanks for response : below is the version details : 

root@umaster1:~# kubectl version
**Client Version:** version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
**Server Version**: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+icp+ee", GitCommit:"5bf8ff102c9cd883604f1902d01745c73b44fe6c", GitTreeState:"clean", BuildDate:"2017-12-12T23:16:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

-------------------------------------------------------------

but my issue is not related to version of K8s . i want to configure prometheus alerts which implicitly uses alertmanager where we can customize our alerts according to our requirement .  

----  as prometheus doesn't comes up with predefined POD metrices so we have tocustomize  alerts using the metrices provided i have tried to use below code but these seems not working good for my env .

    **ALERT POD_CPU_HIGH_UTILIZATION
      IF (sum(rate(container_cpu_usage_seconds_total[5m]))by(pod_name)*100)>80
      FOR 1m
      LABELS { severity ="warning" }
      ANNOTATIONS {
         summary ="HIGH CPU USAGE WARNING for POD {{$labels.pod} on{{$labels.host}}",
         description = "pod {{$labels.pod}} is using high cpu",
       }**
    **ALERT POD_MEMORY_HIGH_UTILIZATION
      IF (sum(rate(container_memory_usage_bytes[5m]))by(pod_name)*100) >80
      FOR 1m
      LABELS { severity ="warning" }
      ANNOTATIONS {
         summary ="HIGH Memory USAGE WARNING for{{$labels.pod}}",
         description = "pod {{$labels.pod}} is using high memory",
       }**

@brancz . please help

**Comment by brancz** [comment]
That is the Prometheus 1.x alert rule format, you need to adapt it to the new format. https://prometheus.io/docs/prometheus/latest/migration/#recording-rules-and-alerts

**Comment by akshays244** [comment]
i was just wondering why does prometheus doesn't provide Kubernetes POD related  inbuild matrices

**Comment by brancz** [comment]
Prometheus is not opinionated about what it monitors, plus there would be endless opinions on the "correct" queries, alerts, dashboards, etc. That's the purpose of external projects like kube-prometheus.

**Comment by jolson490** [comment]
Note that at this point [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus):
 * has been re-designed to use jsonnet
 * uses https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/resource_alerts.libsonnet, which defines the following (`KubeMemOvercommit` meets the request this GH issue was originally opened for):
```
KubeCPUOvercommit
  message: Overcommited CPU resource request quota on Namespaces.
  message: Overcommited CPU resource requests on Pods, cannot tolerate node failure.
KubeMemOvercommit
  message: Overcommited Memory resource requests on Pods, cannot tolerate node failure.
  message: Overcommited Memory resource request quota on Namespaces.
```
