### ISSUE TITLE
Multiple prometheus objects in the same namespace get added to the same default 'prometheus' service

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/prometheus-operator#96]
Prometheus Operator seems to create default `service` objects named `prometheus` and `alertmanager`. If you create more than one `prometheus` object in the same namespace (E.G. `frontend` and `backend`, both in the `monitoring` namespace,) then both get added to the same default service named `prometheus`, as seen in the related `endpoints` object. (Looks like the same would happen if for some reason you wanted more than one `alertmanager` object in the same namespace.)

This is confusing and I imagine not what was intended. (Or maybe there's a purpose I'm missing?)

I'm unclear as to the purpose of these default `service` objects. I'm creating my own as I need to control various aspects including annotations.

P.S. Hope I'm not creating too many issues, love what you guys are doing, hoping to help!

**Comment by brancz** [comment]
No worries - all feedback is good feedback! 👍 

Those `Service` objects are created to satisfy the `StatefulSet`s need for a governing service, for stable DNS names. These services are not suitable for accessing the underlying Prometheus/Alertmanager instances. For that purpose we wanted to be unopinionated about how someone exposes those.

We're working on versioned user-guides and documentation, but are not quite ready yet unfortunately, but I can imagine this kind of information going there. Until then open as many issues as you want 🙂

**Comment by snarlysodboxer** [comment]
@brancz thanks!

OK. It sounds like it's OK to have more than one `prometheus` object connected to this governing service, do you agree? - It's just for internal usage by Prometheus Operator?

I think we can close this issue.

**Comment by brancz** [comment]
Yep it is purely intended for internal use. If we hit any issues regarding that we can reconsider it, but it allows us to just make sure there is one `Service` per `Namespace` and not worry about it further. But if we hit any limitations on this path it won't be a problem to change this behavior.
