### ISSUE TITLE
[Operator] Prometheus Version wrong parsing 

### ISSUE THREAD

**Issue by vielktus** [coreos/prometheus-operator#961]
**What did you do?**
Change the version in "contrib/kube-prometheus/manifests/prometheus-k8s.yaml"
`Version: v2.1.0` to `Version: Master`

**What did you expect to see?**
Prometheus Operator creates a Prometheus instance using the image with the tag "Master"

**What did you see instead? Under which circumstances?**
Prometheus Operator fails to create Prometheus instance when executing "kube-prometheus/hack/cluster-monitoring/selfhosted-deploy"

**Environment**

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

	kops

* Manifests:

```
contrib/kube-prometheus/manifests/prometheus-k8s.yaml
```

* Prometheus Operator Logs:
somekind of
```
operator.go:678
Error in parsing version No Major.Minor elements found
```

I think there's something wrong  in the file "pkg/prometheus/promcfg.go" (line 65). It only accepts the strings with like "v[0-9].[0-9].[0-9]", but not "Master" or "Latest" or something like that. 
```
version, err := semver.Parse(strings.TrimLeft(versionStr, "v"))
	if err != nil {
		return nil, errors.Wrap(err, "parse version")
	}
```

**Comment by brancz** [comment]
Yes this is correct, the version must follow semantic versioning, as configuration of Prometheus differs across versions. This is the intended behavior. If you want to try a newer version you can use a different `baseImage` compile it and push it to the image repository you control.
