### ISSUE TITLE
Wrong version of package in helm?

### ISSUE THREAD

**Issue by jakinc** [coreos/prometheus-operator#964]
**What did you do?**
Tried to install prometheus with helm on k8s 1.8.6

**What did you expect to see?**
Successful installation.

**What did you see instead? Under which circumstances?**
Helm was pulling prometheus-operator-0.0.11.tgz from the repo rather than prometheus-operator-0.16.1.tgz

**Environment**
Cluster in GKE. Win10 helm client.

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-gke.0", GitCommit:"ee9a97661f14ee0b1ca31d6edd30480c89347c79", GitTreeState:"clean", BuildDate:"2018-01-05T03:36:42Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE

**Comment by brancz** [comment]
cc @gianrubio

**Comment by gianrubio** [comment]
@jakinc helm charts versions doesn't have follow packages version number. On the helm chart prometheus-operator 0.11 you have the prometheus-operator v0.16.1. 

Please check what deployment image from prometheus-operator you have on the installed charts, it should be 0.16.1.

**Comment by gianrubio** [comment]
Marking this issue because we didn't receive any reply
