### ISSUE TITLE
What is the preferred way to run exporters (automatically) on the cluster for deployed applications?

### ISSUE THREAD

**Issue by galexrt** [coreos/prometheus-operator#97]
What would be the preferred way to gather stats from applications that don't have prometheus support (yet), but for example have an exporter written for them?

Would this be a feature to implement in prometheus-operator to be able to create/run exporters from some sort of notation, labels or ServiceMonitor object?

**Comment by brancz** [comment]
As the prometheus-operator runs vanilla Prometheus and just manages those, the notion of exporters doesn't change. You run the exporter in the kubernetes cluster, put a (headless) `Service` in front of it, and choose matching labels for it to be discovered using the `ServiceMonitor` definition. Examples of that can be found in [kube-prometheus](https://github.com/coreos/kube-prometheus), for example you run the [node-exporter](https://github.com/coreos/kube-prometheus/blob/dee7f834fba6bd8159526890a8266bf4fae6a70f/manifests/exporters/node-exporter-ds.yaml) in a `DaemonSet` as usual and then add a `Service`, like [this](https://github.com/coreos/kube-prometheus/blob/dee7f834fba6bd8159526890a8266bf4fae6a70f/manifests/exporters/node-exporter-svc.yaml).

**Comment by galexrt** [comment]
Thanks for the quick answer!
I think that this information would be good in the documentation, as I may not be the only one with this question in mind.

**Comment by brancz** [comment]
Definitely. We are working hard to get user guides up on coreos.com, but have decided that in the mean time we will add documentation to this repo. So stay tuned for docs getting added 🙂 . Feel free to open any issues like these, it helps us understand what to focus on in user guides and documentation.

**Comment by galexrt** [comment]
I looked for an issue on here about creating documentation, but I didn't found on.
Is there a plan to create an issue for this so I can add it to the list?

**Comment by brancz** [comment]
There is currently no issue to collect these. Feel free to open one and point out which parts in particular you would like us to highlight on 🙂

**Comment by galexrt** [comment]
@brancz I created #98 for user found documentation findings/questions.
