### ISSUE TITLE
Datasource named prometheus-k8s was not found in Grafana

### ISSUE THREAD

**Issue by Ludek2** [coreos/prometheus-operator#972]
**What did you do?**

Generated configmap for grafana dasboards using hack/scripts/generate-dashboards-configmap.sh
and applied contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml

**What did you expect to see?**

Dasboards in Grafana

**What did you see instead? Under which circumstances?**

Error message in grafana: "Datasource named prometheus-k8s was not found"

There is a wrong datasource in generate-dashboards-configmap.sh

https://github.com/coreos/prometheus-operator/blob/091e2a120239e7bc517376f17800517dd003d346/contrib/kube-prometheus/hack/scripts/generate-dashboards-configmap.sh#L37

It should be:
hack/scripts/wrap-dashboard.sh $f prometheus | sed "s/^/    /g" 

I'll create a pull request to fix this issue

**Comment by brancz** [comment]
closed by #973
