### ISSUE TITLE
Prometheus kubelet target reports "server returned HTTP status 401 Unauthorized"

### ISSUE THREAD

**Issue by dejaeghered** [coreos/prometheus-operator#976]
**What did you do?**
Deploy kube-prometheus using: 
hack/cluster-monitoring/self-hosted-deploy

**What did you expect to see?**
kubelet metrics being scraped

**What did you see instead? Under which circumstances?**
server returned HTTP status 401 Unauthorized upon scraping kubelet https endpoint

**Environment**
CoreOS on openstack vms.

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

cluster managed and installed using kubespray

**Comment by brancz** [comment]
Do your kubelets have RBAC authorization enabled? https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#prerequisites

**Comment by brancz** [comment]
Albeit the name `401 Unauthorized` it tells us that the problem is the authentication (if it was an authorization issue it would be `403 Forbidden`. Just to make sure, both of these flags are enabled, right?

* `--authentication-token-webhook=true`
* `--authorization-mode=Webhook`

Next I would check the kubelet logs as well as the apiserver logs to find the declined `TokenReview` request, which is the action that verifies that the ServiceAccount token that the Prometheus instance gives the kubelet to authenticate itself.

**Comment by dejaeghered** [comment]
Those flags were missing indeed.  Thank you for the swift help!

**Comment by carlosedp** [comment]
One question, this happened to my cluster deployed with Kubeadm. Is there any option to add the parameters to the kubeadm config file that is referred here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md

Maybe update that document to add this.

**Comment by brancz** [comment]
@carlosedp would you like to create a PR for that? :slightly_smiling_face:

**Comment by carlosedp** [comment]
Done on #1031

**Comment by akshayrathod2** [comment]
> Albeit the name `401 Unauthorized` it tells us that the problem is the authentication (if it was an authorization issue it would be `403 Forbidden`. Just to make sure, both of these flags are enabled, right?
> 
>     * `--authentication-token-webhook=true`
> 
>     * `--authorization-mode=Webhook`
> 
> 
> Next I would check the kubelet logs as well as the apiserver logs to find the declined `TokenReview` request, which is the action that verifies that the ServiceAccount token that the Prometheus instance gives the kubelet to authenticate itself.

@brancz Hello there I am new to kubernetes. I'm facing the same issue and unable to figure out where to put this parameter. I am using https://github.com/kubernetes-incubator/metrics-server.git this repo

**Comment by brancz** [comment]
Metrics server is totally different from this repo. What are you trying to do?
