### ISSUE TITLE
Bug: Operator hard-codes the PVC accessModes, preventing ReadWriteMany storage

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#978]
Prometheus operator hard-codes the value of PVC `accessModes` [here](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L165) and [here](https://github.com/coreos/prometheus-operator/blob/master/pkg/alertmanager/statefulset.go#L120) preventing the use of any access mode other than `ReadWriteOnce`, so e.g. `ReadWriteMany` storage (or other future values) cannot be specified.

https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L165
https://github.com/coreos/prometheus-operator/blob/master/pkg/alertmanager/statefulset.go#L120
```
		pvcTemplate := storageSpec.VolumeClaimTemplate
		pvcTemplate.Name = volumeName(am.Name)
		pvcTemplate.Spec.AccessModes = []v1.PersistentVolumeAccessMode{v1.ReadWriteOnce}
		pvcTemplate.Spec.Resources = storageSpec.VolumeClaimTemplate.Spec.Resources
		pvcTemplate.Spec.Selector = storageSpec.VolumeClaimTemplate.Spec.Selector
```

Worse, you can't even [manually provision](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning) `ReadWriteMany` storage because the hard-coding overrides that too.

`AccessModes` should be configurable in the `storageSpec`.

**What did you do?**

Deploy kube-prometheus with storageSpec enabled

**What did you expect to see?**

Prometheus and AlertManager deployed

**What did you see instead? Under which circumstances?**

No StatefulSet deployments and nothing in operator log.

After commenting out the storageSpec and redeploying, Prometheus and Altermanager were deployed, but with no persistent volumes.

**Environment**

k8s 0.8.7

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7+coreos.0", GitCommit:"768e049ab5230010251f30475e0e785e2e999566", GitTreeState:"clean", BuildDate:"2018-01-18T00:17:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

`kube-aws`

* Manifests:

(the `default` StorageClass exist and works, for `accessModes: [ ReadWriteMany ]`)
```
  storageSpec:
    class: default
    resources:
      requests:
        storage: 1Gi
```

* Prometheus Operator Logs:

There was nothing to indicate any error has occurred in the operator logs 😢
```
kubectl logs --namespace=prometheus prometheus-operator-f74c6c94f-jl8s9 prometheus-operator
ts=2018-02-09T18:22:22.761880822Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.8.7+coreos.0
ts=2018-02-09T18:22:22.761956601Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.8.7+coreos.0
ts=2018-02-09T18:22:22.843004302Z caller=operator.go:538 component=alertmanageroperator msg="CRD created" crd=Alertmanager
ts=2018-02-09T18:22:22.845761203Z caller=operator.go:1035 component=prometheusoperator msg="CRD created" crd=Prometheus
ts=2018-02-09T18:22:22.854480783Z caller=operator.go:1035 component=prometheusoperator msg="CRD created" crd=ServiceMonitor
ts=2018-02-09T18:22:25.872079221Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-02-09T18:22:28.965933758Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-02-09T19:08:41.078680997Z caller=operator.go:303 component=alertmanageroperator msg="Alertmanager added" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.078781973Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.143484484Z caller=operator.go:307 component=prometheusoperator msg="Prometheus added" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.143578837Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.164463805Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.242750326Z caller=operator.go:969 component=prometheusoperator msg="creating configuration"
ts=2018-02-09T19:08:41.283746522Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.342448798Z caller=operator.go:983 component=prometheusoperator msg="current config or current configmaps has changed"
ts=2018-02-09T19:08:41.3425047Z caller=operator.go:989 component=prometheusoperator msg="updating configuration"
ts=2018-02-09T19:08:41.375071036Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T19:08:41.447312391Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
```

**Comment by brancz** [comment]
Can you elaborate on your use case? This was done intentionally, in order to prevent users from shooting themselves in the foot, as using the same volume for two different Prometheus instances or Alertmanager instances is incorrect. It would turn coordination free or AP systems into something rather unpredictable.

**Comment by whereisaaron** [comment]
Hi @brancz, I was testing an EFS mount, which creates ReadWriteMany PVs. It mysteriously didn't work until I found this override in the code. I was able to fool `prometheus-operator` by artificially creating the EFS PV as 'ReadWriteOnce' and get it deployed.

Maybe I'm selfish here, but IMHO I shouldn't have to waste time doing the extra trouble-shooting to uncover why `prometheus-operator` isn't working with my legit 'ReadWriteMany' volume (that I promise I'm only using once! :-), nor have to create workarounds to compensate for this hard-coded override.

I understand the noble goal of helping the user, but I don't think this measure is actually effective at that?

1) In the most common use case, 'prometheus-operator' is creating the PVC, so you are guaranteed a newly provisioned volume not used elsewhere - regardless of the access mode. I guess in the self-provisioned `selector` PVC use case you could use the same `selector` for two 'Prometheus' resources, but is k8s willing to bind the same PV to two PVCs? Even if it is, the access mode isn't going to stop that binding, you'd have to spot the `selector` re-use.

2) Even the EBS case, 'ReadWriteOnce' volumes can still be mounted by multiple Prometheus instances, if they are scheduled on the same node. The 'ReadWriteOnce' is a [node limit, not a container limit](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes). Neither the filesystem drive nor k8s provides a way to limit PVs to only being mounted on one container?

> - ReadWriteOnce – the volume can be mounted as read-write by a single node
> - ReadOnlyMany – the volume can be mounted read-only by many nodes
> - ReadWriteMany – the volume can be mounted as read-write by many nodes

3) It inflicts a silent failure mode on p-o deployments that the user has to troubleshoot. It would be better to abort the deployment and log into the 'prometheus-operator' log what the problem is. Silently overwriting the user's specification and creating this silent failure mode is not, IMHO, helpful! 😄 If you really think the override is the way to go, please at least log that you've done that.

**Comment by brancz** [comment]
Fair enough. Do you want to add a PR to allow setting the value, but defaulting to the current one?

**Comment by jungopro** [comment]
Hi Guys. 
Great discussion, it helped me understand about the limitations of multiple Prometheus operator instances as it relates to storage
I’m running p-o on-prem (using kube-Prometheus) and I though about implementing HA. Is there a way to create 2 p-o replicas writing to the same nfs folder? Or am I complicating things here...? Is there a better approach to ensure HA in the deployment? I looked through the docs and did sent see a clear way to implement it...
Many thanks
Omer

**Comment by jungopro** [comment]
thanks @brancz
I understand that, but I'm in the dark as to how to properly setup multiple replicas of my p-o... should I create 2 separate deployments of kube-prometheues, each with it's own nfs pv?
I simply don't want to "re-invent the wheel"... If there is a straigh-forward way to implement it, I will gladly adopt it. If there isn't, I will come up with one and share 😄

**Comment by brancz** [comment]
I think we're mixing up a few things. The Prometheus Operator itself does not have any PVs attached itself. Only the Prometheus servers deployed and managed by the Prometheus Operator do. The Prometheus Operator is fine to be run with a single replica.

**Comment by jungopro** [comment]
@brancz you're correct, I wasn't clear enough, sorry about that
I meant the prometheus server that the p-o creates. 
I want to run it in HA mode with PV on NFS storage (on-prem)
I currently have the prometheus server with a single replica and I'm wondering the best way to implement it with the kube-prometheus deployment

**Comment by brancz** [comment]
1. I highly recommend not using NFS, it's unsupported by the Prometheus project so if you have data-loss or anything it is only supported on a best effort basis, there are 0 guarantees.
2. You just need a second PV that matches your requirements :slightly_smiling_face: and then set the replicas to 2.

**Comment by jungopro** [comment]
I will give it a try, thanks!

**Comment by whereisaaron** [comment]
Hi @jungopro for what it is worth I've been running Prometheus 2.x on NFS 4 for about 9 months now with zero issue. It allows us to provide excellent availability without necessarily running multiple replica's and meshed alert managers on every cluster.

I would not have done that with Prometheus 1.x, as the storage subsystem was hard to manage at the best of times, even on local disk. But the 2.x TSDB storage subsystem is _vastly_ improved, and a comparative dream is use (credit the Prometheus team 👍 🎉).

For reference our clusters and monitoring needs about 200-250Mbit of network bandwidth to run Prometheus on NFS 4, so plan accordingly.

The quite fairly [maligned NFS protocol](https://www.kernel.org/doc/ols/2006/ols2006v2-pages-59-72.pdf)* has moved on considerably with NFS 4 and NFS 4.1, which are stateful and have native locking. It is still not _fully_ POSIX compliant, but then [neither is ext4](https://github.com/coreos/prometheus-operator/issues/830#issuecomment-364548754) and we still use that when appropriate 😄. (* Note this 2006 article predates [2010's NFS 4.1](https://tools.ietf.org/html/rfc5661), which added [sessions, callbacks, and directory delegation](http://www.iaps.com/nfsv4.1-new-features.html).)

In my experience NFS 4.1 works just great with the Prometheus 2.x TSDB storage subsystem.
