### ISSUE TITLE
helm chart 'kube-prometheus' 'values.yaml' has incorrect values for child charts (v0.0.19)

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#979]
This simple Prometheus CRD storage spec fails to create a PVC and StatefulSet. If I remove the `storage` spec it works fine. If I create a simple PVC myself with the same settings the PV is created. The prometheus-operator logs contain nothing to explain why it doesn't work. Am I missing something simple?

```
kind: Prometheus
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.13
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus
spec:
...
  storage:
    class: ebs
    resources:
      requests:
        storage: 40Gi
    selector: {}
  version: "v2.1.0"
```

I know the PVC and provisioner work, because this test works fine
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-ebs-vol-1
spec:
  storageClassName: ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
```

```
$ kubectl apply --namespace=prometheus -f pvc-test.yaml
persistentvolumeclaim "test-ebs-vol-1" created

$ kubectl get pvc,pv --namespace=prometheus
NAME                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/test-ebs-vol-1            Bound     pvc-715ed550-0de2-11e8-b2f4-0208b3513f7e   40Gi       RWO            ebs            26s

NAME                                          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                STORAGECLASS   REASON    AGE
pv/pvc-715ed550-0de2-11e8-b2f4-0208b3513f7e   40Gi       RWO            Delete           Bound     prometheus/test-ebs-vol-1            ebs 
```

The prometheus-operator logs contain nothing to explain why it doesn't work (this is the entire log):
```
$ kubectl logs --namespace=prometheus prometheus-operator-f74c6c94f-j4bkj
ts=2018-02-09T21:49:01.060783646Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.8.7+coreos.0
ts=2018-02-09T21:49:01.06082803Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.8.7+coreos.0
ts=2018-02-09T21:49:01.065780791Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-02-09T21:49:01.145915732Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-02-09T21:49:14.966188622Z caller=operator.go:303 component=alertmanageroperator msg="Alertmanager added" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:14.966297902Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.05221503Z caller=operator.go:307 component=prometheusoperator msg="Prometheus added" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.052413121Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.243384494Z caller=operator.go:636 component=prometheusoperator msg="update handler" old=63333 cur=63337
ts=2018-02-09T21:49:15.24382822Z caller=operator.go:343 component=alertmanageroperator msg="update handler" old=63333 cur=63337
ts=2018-02-09T21:49:15.243870427Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.253403724Z caller=operator.go:969 component=prometheusoperator msg="creating configuration"
ts=2018-02-09T21:49:15.311573741Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.345514091Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-02-09T21:49:15.368312547Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=prometheus/kube-prometheus
ts=2018-02-09T21:49:15.463143481Z caller=operator.go:980 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-02-09T21:49:46.352523602Z caller=operator.go:636 component=prometheusoperator msg="update handler" old=63337 cur=63571
ts=2018-02-09T21:49:46.354195459Z caller=operator.go:343 component=alertmanageroperator msg="update handler" old=63337 cur=63571
ts=2018-02-09T21:49:46.35429624Z caller=operator.go:379 component=alertmanageroperator msg="sync alertmanager" key=prometheus/kube-prometheus
```

**Comment by gianrubio** [comment]
Do you have errors or warnings in the k8s events?

**Comment by whereisaaron** [comment]
Thanks for asking @gianrubio. I have tracked this down to a problem with the `helm` charts. The `kube-operator` chart `values.yaml` file is out of date with its child charts like `prometheus` which themselves contain errors.

The `kube-operator` chart tells chart users (`helm inspect values`) that storage is specified like this:
```
  storageSpec: {}
  #   class: default
  #   resources:
  #     requests:
  #       storage: 16Gi
  #   selector: {}
```

But the current `prometheus` chart says (`helm inspect values kube-operator`) they are actually specified like this:
```
storageSpec: {}
#   volumeClaimTemplate:
#     spec:
#       resources:
#         requests:
#           storage: 50Gi
#   selector: {}
```
That too is wrong since `selector` needs to be indented under spec:
```
storageSpec: {}
#   volumeClaimTemplate:
#     spec:
#       resources:
#         requests:
#           storage: 50Gi
#       selector: {}
```
So it is basically a whole lot of wrongness in the `helm` chart documentation.

I changed my deployment values to this and it worked fine.
```
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: ebs
        resources:
          requests:
            storage: 40Gi
      selector: {}
```

Got the volume, except for the silly double name, which is also a chart issue.
```
NAME                                                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc/kube-prometheus-grafana                                      Bound     pvc-d4cd9ab3-0e92-11e8-b6cc-02700be2c214   1Gi        RWX            efs            14m
pvc/prometheus-kube-prometheus-db-prometheus-kube-prometheus-0   Bound     pvc-d50950c3-0e92-11e8-821d-0a0f3170e16e   40Gi       RWO            ebs            14m

NAME                                          CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                                                   STORAGECLASS   REASON    AGE
pv/pvc-d4cd9ab3-0e92-11e8-b6cc-02700be2c214   1Gi        RWX            Delete           Bound     prometheus/kube-prometheus-grafana                                      efs                      14m
pv/pvc-d50950c3-0e92-11e8-821d-0a0f3170e16e   40Gi       RWO            Delete           Bound     prometheus/prometheus-kube-prometheus-db-prometheus-kube-prometheus-0   ebs                      14m
```

**Comment by gianrubio** [comment]
@whereisaaron nice catch!!!  Do you mind to make a PR to fix that?

**Comment by leifmadsen** [comment]
I've submitted a PR

CC: @whereisaaron

**Comment by leifmadsen** [comment]
I also think there is another issue here that needs to be addressed. The way that the templates deal with the persistent volume claim results in issues with the PVC claimName that is much too long. I'm basically on day one with Helm here, but looking at how the grafana chart deals with a separate `pvc.yaml` might also be required here.

That way we can likely better control the naming of the pvc, because right now, I get something like this:

```

**Comment by leifmadsen** [comment]
(my current work around is to name the deploy just `kp` instead of `kube-prometheus`)

**Comment by whereisaaron** [comment]
Good catch @leifmadsen, a common way people handle this is to have templates in `_helpers.tpl` that ensure generated names are not too long.

First, modern charts avoid duplicating the chart name in resource names, if the release name actually already contains the chart name. This avoids the `prometheus-kube-prometheus-prometheus-kube-prometheus-*` junk.

Second, you can get the template to test the length and use some algorithm to shorten resource names, usually people just truncate the name, but you could also truncate it more and add a random sequence. They also accept override settings that let you take control over the resource name prefixes.

Here's [an example](https://github.com/mintel/dex-k8s-authenticator/blob/master/charts/dex/templates/_helpers.tpl#L9-L25):

```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "dex.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by minhdanh** [comment]
> (my current work around is to name the deploy just kp instead of kube-prometheus)

@leifmadsen the work around is not working for me, as it still results in a pvc name that is still long like this `prometheus-kp-prometheus-db-prometheus-kp-prometheus-0`, which is 72 characters.

Any way to fix this completely?

**Comment by leifmadsen** [comment]
@minhdanh I haven't figured out where the operator chooses to do the naming convention. I started looking and played around with some naming overrides in the CRD, but I think it's embedded in the container image. I haven't gone through all the code to figure out where the naming happens.

This isn't a Helm issue though, as I'm deploying Operator without Helm at all. I ported all the original static templates to Ansible jinja2 templates to deploy them on Kubernetes, and have since migrated to openshift-ansible to deploy on OpenShift.

**Comment by minhdanh** [comment]
Yeah, this isn't an issue with Helm but with Prometheus Operator.

So you ported all the charts in /helm/ to deploy to Kubernetes, right? I wonder how that could help with the gluster volume name issue, as there's no template file to define a PVC in kube-prometheus chart, like Grafana (https://github.com/coreos/prometheus-operator/blob/fa10f2751c62a00a7f4c3114cd9e5a31b3ec2e8f/helm/grafana/templates/pvc.yaml)

For the naming of the volume I think maybe it is in this function:
```
func volumeName(name string) string {
	return fmt.Sprintf("%s-db", prefixedName(name))
}
```
https://github.com/coreos/prometheus-operator/blob/2a02847f59577558ef9a580ce98a0a73e15aba4f/pkg/prometheus/statefulset.go#L629

**Comment by minhdanh** [comment]
I report the issue with too long glusterfs volume name here: https://github.com/coreos/prometheus-operator/issues/1357

**Comment by leifmadsen** [comment]
@minhdanh I ported the static files, not the helm charts.
