### ISSUE TITLE
401 Unauthorized against Kubelet targets

### ISSUE THREAD

**Issue by bitva77** [coreos/prometheus-operator#982]
I'm not reporting an issue so much as also showing how I fixed it, in case any one else has a similar issue.

**What did you do?**

Executed ./hack/cluster-monitoring/deploy

**What did you expect to see?**

Everything green in the Grafana Dashboard.

**What did you see instead? Under which circumstances?**

First checked the Grafana dashboard and saw a few alerts firing.  Also the control plane and scheduler checks were set to "NA".  So, then I went into Prometheus and found that none of the Kubelets could be scraped against any of the endpoints to https://IPADDRESS:10250.  The error message was a 401 unauthorized.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubespray

* Manifests:

After some google searching, it appeared that other people where having similar issues but in using GKE an GKE not securing those endpoints. I guess the same is true for a kubepsray install on-prem.

My fix, is to have Prometheus scrape the HTTP endpoint instead.  I accomplished this by editing the contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml and changing https-metrics to http-metrics and the https scheme to http.  From prometheus/prometheus-operator/contrib/kube-prometheus:

sed -i 's/https-metrics/http-metrics/' ../../contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml
sed -i 's/scheme: https/scheme: http/' ../../contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml

I assume there are no major issues in doing this change?  Let me know if I've done something wrong please   :)

**Comment by brancz** [comment]
The controller-manager and scheduler can't be scraped on GKE as far as I know. The second change is correct, actually a lot of people have run into this, would you mind adding a section/doc on GKE here? https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/docs

**Comment by leifmadsen** [comment]
I actually had an issue with a virtualized vanilla kubernetes 1.9.3 (not GKE, etc) as well. Looks like it's the same type of problem. I'll have to try out the work around next time I deploy here.

**Comment by brancz** [comment]
@leifmadsen do make sure the prerequisites (token authentication and RBAC authorization on kubelet) are met: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#prerequisites

**Comment by strzelecki-maciek** [comment]
Affected with the same issue, running GKE 1.9.2 getting 401 when quering the https kubelet port, and getting metrics when quering the non-http port (10255 if i remember correctly). 
What is the least-hacky way to apply a simple relabel to the helm-deployed stable prometheus-operator (would appreciate some explanation with steps)? Thanks!

**Comment by brancz** [comment]
@gianrubio maby in the helm charts we could have an option say “insecureLubeletMetrics” and have it default to false, then people on GKE just need to enable that. Wdyt?

**Comment by bitva77** [comment]
Looks like for a kubespray install it might be passing these to kubelet huh:

--authentication-token-webhook
--kubeconfig
--require-kubeconfig flags

see https://github.com/kubernetes/kubeadm/issues/650

**Comment by leifmadsen** [comment]
@brancz yea that looks to be my issue. Learning about authn/authz now :)

**Comment by gianrubio** [comment]
@brancz the helm chart [already have](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kubelets/values.yaml#L4) this flags, what're missing is a document explaining about it.

**Comment by Atoms** [comment]
in kubespray PR is merged with fix for this
https://github.com/kubernetes-incubator/kubespray/pull/2184

**Comment by gianrubio** [comment]
Can we close this issue?

**Comment by speedupmate** [comment]
you should reopen this as in GCE the setup fails due kublet requiring authentication and token based auth disabed on kubelet by default in GCE . This should be documented clearly , currently every GCE n00b needs to spend hours on getting this working there and wondering where the auth chain fails or where even to place the config needed to fix

you can get it working by adding a `--set exporter-kubelets.https=false` as a workaround and then kubelet monitoring is done over http 

full call:
`helm install coreos/prometheus-operator --name prometheus-operator --set global.rbacEnable=true --set exporter-kubelets.https=false --namespace monitoring
`
but that does not solve the real issue and is only a workaround to disable authentication need , way to get it working properly is also discussed in prometheus github issues https://github.com/prometheus/prometheus/issues/2606#issuecomment-294869099

**Comment by speedupmate** [comment]
@brancz great to know. Just tried to add my input here as lot of searches on this topic lead here. It took a lot of time for n00b like me to get this working and is not essential at all and not documented

**Comment by Wenzil** [comment]
@speedupmate What version of coreos/prometheus-operator are you using to be able to set `exporter-kubelets.https` to false? It's not documented and it's not listed in the [default values](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/values.yaml) either.

**Comment by speedupmate** [comment]
@Wenzil I'm using whatever comes out of helm installation today and on google container engine where by default the installation succeeds but kubelet information is not available due auth issues

**Comment by gianrubio** [comment]
@Wenzil I don’t  have experience with GKE and Prometheus, I think this is the flag you are looking for https://github.com/coreos/prometheus-operator/blob/7b51c6052f165b4729657771b94ab2dddb667fc2/helm/exporter-kubelets/values.yaml#L2
