### ISSUE TITLE
Unable to run exporter-node on all nodes

### ISSUE THREAD

**Issue by grebois** [coreos/prometheus-operator#983]
**What did you do?**

```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring
```

**What did you expect to see?**

Node Exporter on all nodes

**What did you see instead? Under which circumstances?**

Node Exporter only on master nodes

**Environment**

AWS

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind: 

Kops

@mbenabda @gianrubio If I remove this lines it does not even deploy on masters nodes:

https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-node/templates/deamonset.yaml#L45-L47

**Comment by codexpage** [comment]
@grebois  Have you solved the problem ?  I have the same issue on my cluster. The operator only deploy node-exporter on master node.

**Comment by flouthoc** [comment]
@grebois Did solve this ?

**Comment by grebois** [comment]
Looks good now, using https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by flouthoc** [comment]
Yes for me the issue was that some previous version of node-exporter was running on some other namespace removed it and worked for me as well. Thanks for the reply.
