### ISSUE TITLE
Rules stored in emptyDir ?

### ISSUE THREAD

**Issue by dobesv** [coreos/prometheus-operator#998]
**What did you do?**

Setup prometheus operator with a cluster managed by cluster-autoscaler.

**What did you expect to see?**

Nodes with prometheus running on them could be terminated

**What did you see instead? Under which circumstances?**

cluster-autoscaler compains `Fast evaluation: node ip-172-20-52-38.ec2.internal cannot be removed: pod with local storage present: prometheus-k8s-0`

**Environment**

kops aws k8s cluster

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kops

Because the prometheus StatefulSet creates an `emptyDir` volume to store rules, it blocks autoscaling activity unless you do some extra work.  I think it would save people some time if this volume were not created.  Either store the rules on the same volume as the data or put them into `/tmp` or something.

**Comment by brancz** [comment]
I think this makes sense, but we need to think carefully about making sure, that we're not breaking the Prometheus data directory (for 1.x and 2.x) in any way. Just `/tmp` I don't think would work, as mount namespaces are not shared among containers, therefore the `/tmp` directory would not be accessible by both containers.

**Comment by brancz** [comment]
cc @fabxc is it safe to write something into the data dir of 1.x Prometheus servers other than storage related things? Or do you think it's just safest to move the data dir one level down and have a `data`, `rules`, etc directory in the then "main" volume?

**Comment by fabxc** [comment]
Yea, you can put anything there just fine. But probably still better to separate it.

**Comment by dobesv** [comment]
It appears that `alertmanager` has the same issue, `cluster-autoscaler` thinks it cannot be evicted because it has local storage.

**Comment by dobesv** [comment]
Ah, I didn't realize alertmanager had a persistent volume claim template, thanks.

**Comment by brancz** [comment]
In the latest release (`v0.20.0`) we removed all of the rule handling via emptydir, so this should not be a problem anymore from now on.

Closing this here, but feel free to re-open or create a new issue should you run into any problems with it! :slightly_smiling_face:
